<?php
#This file was last reorganized on 19th of September 2017 08:54:24 AM UTC

$text['title-sip_profiles']['en-us'] = "SIP Profiles";
$text['title-sip_profiles']['en-gb'] = "SIP Profiles";
$text['title-sip_profiles']['ar-eg'] = "";
$text['title-sip_profiles']['de-at'] = "SIP Profile"; //copied from de-de
$text['title-sip_profiles']['de-ch'] = "SIP Profile"; //copied from de-de
$text['title-sip_profiles']['de-de'] = "SIP Profile";
$text['title-sip_profiles']['es-cl'] = "Perfiles SIP";
$text['title-sip_profiles']['es-mx'] = "Perfiles SIP"; //copied from es-cl
$text['title-sip_profiles']['fr-ca'] = "Profiles SIP"; //copied from fr-fr
$text['title-sip_profiles']['fr-fr'] = "Profiles SIP";
$text['title-sip_profiles']['he-il'] = "";
$text['title-sip_profiles']['it-it'] = "Profili SIP";
$text['title-sip_profiles']['nl-nl'] = "SIP Profielen";
$text['title-sip_profiles']['pl-pl'] = "Profile SIP";
$text['title-sip_profiles']['pt-br'] = "Perfis SIP"; //copied from pt-pt
$text['title-sip_profiles']['pt-pt'] = "Perfis SIP";
$text['title-sip_profiles']['ro-ro'] = "";
$text['title-sip_profiles']['ru-ru'] = "Профили SIP";
$text['title-sip_profiles']['sv-se'] = "SIP Profiler";
$text['title-sip_profiles']['uk-ua'] = "SIP профілі";

$text['title-sip_profile']['en-us'] = "SIP Profile";
$text['title-sip_profile']['en-gb'] = "SIP Profile";
$text['title-sip_profile']['ar-eg'] = "";
$text['title-sip_profile']['de-at'] = "SIP Profil"; //copied from de-de
$text['title-sip_profile']['de-ch'] = "SIP Profil"; //copied from de-de
$text['title-sip_profile']['de-de'] = "SIP Profil";
$text['title-sip_profile']['es-cl'] = "Perfil SIP";
$text['title-sip_profile']['es-mx'] = "Perfil SIP"; //copied from es-cl
$text['title-sip_profile']['fr-ca'] = "Profile SIP"; //copied from fr-fr
$text['title-sip_profile']['fr-fr'] = "Profile SIP";
$text['title-sip_profile']['he-il'] = "";
$text['title-sip_profile']['it-it'] = "Profilo SIP";
$text['title-sip_profile']['nl-nl'] = "SIP Profiel";
$text['title-sip_profile']['pl-pl'] = "Profil SIP";
$text['title-sip_profile']['pt-br'] = "Perfis SIP";
$text['title-sip_profile']['pt-pt'] = "Perfil SIP";
$text['title-sip_profile']['ro-ro'] = "";
$text['title-sip_profile']['ru-ru'] = "Профиль SIP";
$text['title-sip_profile']['sv-se'] = "SIP Profil";
$text['title-sip_profile']['uk-ua'] = "SIP профіль";

$text['title-sip_profile_domains']['en-us'] = "Domains";
$text['title-sip_profile_domains']['en-gb'] = "Domains";
$text['title-sip_profile_domains']['ar-eg'] = "";
$text['title-sip_profile_domains']['de-at'] = "Domänen"; //copied from de-de
$text['title-sip_profile_domains']['de-ch'] = "Domänen"; //copied from de-de
$text['title-sip_profile_domains']['de-de'] = "Domänen";
$text['title-sip_profile_domains']['es-cl'] = "";
$text['title-sip_profile_domains']['es-mx'] = "";
$text['title-sip_profile_domains']['fr-ca'] = "Domaines";
$text['title-sip_profile_domains']['fr-fr'] = "Domaines";
$text['title-sip_profile_domains']['he-il'] = "";
$text['title-sip_profile_domains']['it-it'] = "";
$text['title-sip_profile_domains']['nl-nl'] = "Domeinen";
$text['title-sip_profile_domains']['pl-pl'] = "";
$text['title-sip_profile_domains']['pt-br'] = "";
$text['title-sip_profile_domains']['pt-pt'] = "";
$text['title-sip_profile_domains']['ro-ro'] = "";
$text['title-sip_profile_domains']['ru-ru'] = "Домены";
$text['title-sip_profile_domains']['sv-se'] = "Domäner";
$text['title-sip_profile_domains']['uk-ua'] = "";

$text['title-sip_profile_domain']['en-us'] = "Domain";
$text['title-sip_profile_domain']['en-gb'] = "Domain";
$text['title-sip_profile_domain']['ar-eg'] = "";
$text['title-sip_profile_domain']['de-at'] = "Domäne"; //copied from de-de
$text['title-sip_profile_domain']['de-ch'] = "Domäne"; //copied from de-de
$text['title-sip_profile_domain']['de-de'] = "Domäne";
$text['title-sip_profile_domain']['es-cl'] = "";
$text['title-sip_profile_domain']['es-mx'] = "";
$text['title-sip_profile_domain']['fr-ca'] = "Domaine";
$text['title-sip_profile_domain']['fr-fr'] = "Domaine";
$text['title-sip_profile_domain']['he-il'] = "";
$text['title-sip_profile_domain']['it-it'] = "";
$text['title-sip_profile_domain']['nl-nl'] = "Domein";
$text['title-sip_profile_domain']['pl-pl'] = "";
$text['title-sip_profile_domain']['pt-br'] = "";
$text['title-sip_profile_domain']['pt-pt'] = "";
$text['title-sip_profile_domain']['ro-ro'] = "";
$text['title-sip_profile_domain']['ru-ru'] = "Домен";
$text['title-sip_profile_domain']['sv-se'] = "Domän";
$text['title-sip_profile_domain']['uk-ua'] = "";

$text['title-sip_profile_setting']['en-us'] = "Profile Setting";
$text['title-sip_profile_setting']['en-gb'] = "Profile Setting";
$text['title-sip_profile_setting']['ar-eg'] = "";
$text['title-sip_profile_setting']['de-at'] = "Profil Einstellungen"; //copied from de-de
$text['title-sip_profile_setting']['de-ch'] = "Profil Einstellungen"; //copied from de-de
$text['title-sip_profile_setting']['de-de'] = "Profil Einstellungen";
$text['title-sip_profile_setting']['es-cl'] = "Configuración de Perfil";
$text['title-sip_profile_setting']['es-mx'] = "Configuración de Perfil"; //copied from es-cl
$text['title-sip_profile_setting']['fr-ca'] = "Paramètres du Profile"; //copied from fr-fr
$text['title-sip_profile_setting']['fr-fr'] = "Paramètres du Profile";
$text['title-sip_profile_setting']['he-il'] = "";
$text['title-sip_profile_setting']['it-it'] = "";
$text['title-sip_profile_setting']['nl-nl'] = "Profiel Instelling";
$text['title-sip_profile_setting']['pl-pl'] = "Ustawienia profilu";
$text['title-sip_profile_setting']['pt-br'] = "Configurações do perfil";
$text['title-sip_profile_setting']['pt-pt'] = "Definições do Perfil";
$text['title-sip_profile_setting']['ro-ro'] = "";
$text['title-sip_profile_setting']['ru-ru'] = "Настройки профиля";
$text['title-sip_profile_setting']['sv-se'] = "Profilinställning";
$text['title-sip_profile_setting']['uk-ua'] = "Налаштування профілю";

$text['label-sip_profile_name']['en-us'] = "Name";
$text['label-sip_profile_name']['en-gb'] = "Name";
$text['label-sip_profile_name']['ar-eg'] = "";
$text['label-sip_profile_name']['de-at'] = "Name"; //copied from de-de
$text['label-sip_profile_name']['de-ch'] = "Name"; //copied from de-de
$text['label-sip_profile_name']['de-de'] = "Name";
$text['label-sip_profile_name']['es-cl'] = "Nombre";
$text['label-sip_profile_name']['es-mx'] = "Nombre"; //copied from es-cl
$text['label-sip_profile_name']['fr-ca'] = "Nom"; //copied from fr-fr
$text['label-sip_profile_name']['fr-fr'] = "Nom";
$text['label-sip_profile_name']['he-il'] = "";
$text['label-sip_profile_name']['it-it'] = "";
$text['label-sip_profile_name']['nl-nl'] = "Naam";
$text['label-sip_profile_name']['pl-pl'] = "Nazwa";
$text['label-sip_profile_name']['pt-br'] = "Nome"; //copied from pt-pt
$text['label-sip_profile_name']['pt-pt'] = "Nome";
$text['label-sip_profile_name']['ro-ro'] = "";
$text['label-sip_profile_name']['ru-ru'] = "Название";
$text['label-sip_profile_name']['sv-se'] = "Namn";
$text['label-sip_profile_name']['uk-ua'] = "Назва";

$text['label-sip_profile_value']['en-us'] = "Value";
$text['label-sip_profile_value']['en-gb'] = "Value";
$text['label-sip_profile_value']['ar-eg'] = "";
$text['label-sip_profile_value']['de-at'] = "Wert"; //copied from de-de
$text['label-sip_profile_value']['de-ch'] = "Wert"; //copied from de-de
$text['label-sip_profile_value']['de-de'] = "Wert";
$text['label-sip_profile_value']['es-cl'] = "Valor";
$text['label-sip_profile_value']['es-mx'] = "Valor"; //copied from es-cl
$text['label-sip_profile_value']['fr-ca'] = "Valeur"; //copied from fr-fr
$text['label-sip_profile_value']['fr-fr'] = "Valeur";
$text['label-sip_profile_value']['he-il'] = "";
$text['label-sip_profile_value']['it-it'] = "";
$text['label-sip_profile_value']['nl-nl'] = "Waarde";
$text['label-sip_profile_value']['pl-pl'] = "Wartość";
$text['label-sip_profile_value']['pt-br'] = "Valor"; //copied from pt-pt
$text['label-sip_profile_value']['pt-pt'] = "Valor";
$text['label-sip_profile_value']['ro-ro'] = "";
$text['label-sip_profile_value']['ru-ru'] = "Значение";
$text['label-sip_profile_value']['sv-se'] = "Värde";
$text['label-sip_profile_value']['uk-ua'] = "Значення";

$text['label-sip_profile_enabled']['en-us'] = "Enabled";
$text['label-sip_profile_enabled']['en-gb'] = "Enabled";
$text['label-sip_profile_enabled']['ar-eg'] = "";
$text['label-sip_profile_enabled']['de-at'] = "Aktiv"; //copied from de-de
$text['label-sip_profile_enabled']['de-ch'] = "Aktiv"; //copied from de-de
$text['label-sip_profile_enabled']['de-de'] = "Aktiv";
$text['label-sip_profile_enabled']['es-cl'] = "Activado";
$text['label-sip_profile_enabled']['es-mx'] = "Activado"; //copied from es-cl
$text['label-sip_profile_enabled']['fr-ca'] = "Actif"; //copied from fr-fr
$text['label-sip_profile_enabled']['fr-fr'] = "Actif";
$text['label-sip_profile_enabled']['he-il'] = "";
$text['label-sip_profile_enabled']['it-it'] = "";
$text['label-sip_profile_enabled']['nl-nl'] = "Aan";
$text['label-sip_profile_enabled']['pl-pl'] = "Włączony";
$text['label-sip_profile_enabled']['pt-br'] = "Habilitado"; //copied from pt-pt
$text['label-sip_profile_enabled']['pt-pt'] = "Habilitado";
$text['label-sip_profile_enabled']['ro-ro'] = "";
$text['label-sip_profile_enabled']['ru-ru'] = "Включено";
$text['label-sip_profile_enabled']['sv-se'] = "Aktiverad";
$text['label-sip_profile_enabled']['uk-ua'] = "Включено";

$text['label-sip_profile_description']['en-us'] = "Description";
$text['label-sip_profile_description']['en-gb'] = "Description";
$text['label-sip_profile_description']['ar-eg'] = "";
$text['label-sip_profile_description']['de-at'] = "Beschreibung"; //copied from de-de
$text['label-sip_profile_description']['de-ch'] = "Beschreibung"; //copied from de-de
$text['label-sip_profile_description']['de-de'] = "Beschreibung";
$text['label-sip_profile_description']['es-cl'] = "Descripción";
$text['label-sip_profile_description']['es-mx'] = "Descripción"; //copied from es-cl
$text['label-sip_profile_description']['fr-ca'] = "Description"; //copied from fr-fr
$text['label-sip_profile_description']['fr-fr'] = "Description";
$text['label-sip_profile_description']['he-il'] = "";
$text['label-sip_profile_description']['it-it'] = "";
$text['label-sip_profile_description']['nl-nl'] = "Omschrijving";
$text['label-sip_profile_description']['pl-pl'] = "Opis";
$text['label-sip_profile_description']['pt-br'] = "Descrição"; //copied from pt-pt
$text['label-sip_profile_description']['pt-pt'] = "Descrição";
$text['label-sip_profile_description']['ro-ro'] = "";
$text['label-sip_profile_description']['ru-ru'] = "Описание";
$text['label-sip_profile_description']['sv-se'] = "Beskrivning";
$text['label-sip_profile_description']['uk-ua'] = "Опис";

$text['label-sip_profile_domain_name']['en-us'] = "Name";
$text['label-sip_profile_domain_name']['en-gb'] = "Name";
$text['label-sip_profile_domain_name']['ar-eg'] = "";
$text['label-sip_profile_domain_name']['de-at'] = "Name"; //copied from de-de
$text['label-sip_profile_domain_name']['de-ch'] = "Name"; //copied from de-de
$text['label-sip_profile_domain_name']['de-de'] = "Name";
$text['label-sip_profile_domain_name']['es-cl'] = "Nombre";
$text['label-sip_profile_domain_name']['es-mx'] = "Nombre"; //copied from es-cl
$text['label-sip_profile_domain_name']['fr-ca'] = "Nom"; //copied from fr-fr
$text['label-sip_profile_domain_name']['fr-fr'] = "Nom";
$text['label-sip_profile_domain_name']['he-il'] = "";
$text['label-sip_profile_domain_name']['it-it'] = "";
$text['label-sip_profile_domain_name']['nl-nl'] = "Naam";
$text['label-sip_profile_domain_name']['pl-pl'] = "Nazwa";
$text['label-sip_profile_domain_name']['pt-br'] = "Nome"; //copied from pt-pt
$text['label-sip_profile_domain_name']['pt-pt'] = "Nome";
$text['label-sip_profile_domain_name']['ro-ro'] = "";
$text['label-sip_profile_domain_name']['ru-ru'] = "Название";
$text['label-sip_profile_domain_name']['sv-se'] = "Namn";
$text['label-sip_profile_domain_name']['uk-ua'] = "Назва";

$text['label-sip_profile_domain_alias']['en-us'] = "Alias";
$text['label-sip_profile_domain_alias']['en-gb'] = "Alias";
$text['label-sip_profile_domain_alias']['ar-eg'] = "";
$text['label-sip_profile_domain_alias']['de-at'] = "Alias"; //copied from de-de
$text['label-sip_profile_domain_alias']['de-ch'] = "Alias"; //copied from de-de
$text['label-sip_profile_domain_alias']['de-de'] = "Alias";
$text['label-sip_profile_domain_alias']['es-cl'] = "";
$text['label-sip_profile_domain_alias']['es-mx'] = "";
$text['label-sip_profile_domain_alias']['fr-ca'] = "Alias";
$text['label-sip_profile_domain_alias']['fr-fr'] = "Alias";
$text['label-sip_profile_domain_alias']['he-il'] = "";
$text['label-sip_profile_domain_alias']['it-it'] = "";
$text['label-sip_profile_domain_alias']['nl-nl'] = "Alternatief";
$text['label-sip_profile_domain_alias']['pl-pl'] = "";
$text['label-sip_profile_domain_alias']['pt-br'] = "";
$text['label-sip_profile_domain_alias']['pt-pt'] = "";
$text['label-sip_profile_domain_alias']['ro-ro'] = "";
$text['label-sip_profile_domain_alias']['ru-ru'] = "Псевдоним";
$text['label-sip_profile_domain_alias']['sv-se'] = "Alias";
$text['label-sip_profile_domain_alias']['uk-ua'] = "";

$text['label-sip_profile_domain_parse']['en-us'] = "Parse";
$text['label-sip_profile_domain_parse']['en-gb'] = "Parse";
$text['label-sip_profile_domain_parse']['ar-eg'] = "";
$text['label-sip_profile_domain_parse']['de-at'] = "Analysieren"; //copied from de-de
$text['label-sip_profile_domain_parse']['de-ch'] = "Analysieren"; //copied from de-de
$text['label-sip_profile_domain_parse']['de-de'] = "Analysieren";
$text['label-sip_profile_domain_parse']['es-cl'] = "";
$text['label-sip_profile_domain_parse']['es-mx'] = "";
$text['label-sip_profile_domain_parse']['fr-ca'] = "Analyser";
$text['label-sip_profile_domain_parse']['fr-fr'] = "Analyser";
$text['label-sip_profile_domain_parse']['he-il'] = "";
$text['label-sip_profile_domain_parse']['it-it'] = "";
$text['label-sip_profile_domain_parse']['nl-nl'] = "Analyseren";
$text['label-sip_profile_domain_parse']['pl-pl'] = "";
$text['label-sip_profile_domain_parse']['pt-br'] = "";
$text['label-sip_profile_domain_parse']['pt-pt'] = "";
$text['label-sip_profile_domain_parse']['ro-ro'] = "";
$text['label-sip_profile_domain_parse']['ru-ru'] = "Parse";
$text['label-sip_profile_domain_parse']['sv-se'] = "Parse";
$text['label-sip_profile_domain_parse']['uk-ua'] = "";

$text['label-sip_profile_setting_name']['en-us'] = "Name";
$text['label-sip_profile_setting_name']['en-gb'] = "Name";
$text['label-sip_profile_setting_name']['ar-eg'] = "";
$text['label-sip_profile_setting_name']['de-at'] = "Name"; //copied from de-de
$text['label-sip_profile_setting_name']['de-ch'] = "Name"; //copied from de-de
$text['label-sip_profile_setting_name']['de-de'] = "Name";
$text['label-sip_profile_setting_name']['es-cl'] = "Nombre";
$text['label-sip_profile_setting_name']['es-mx'] = "Nombre"; //copied from es-cl
$text['label-sip_profile_setting_name']['fr-ca'] = "Nom"; //copied from fr-fr
$text['label-sip_profile_setting_name']['fr-fr'] = "Nom";
$text['label-sip_profile_setting_name']['he-il'] = "";
$text['label-sip_profile_setting_name']['it-it'] = "";
$text['label-sip_profile_setting_name']['nl-nl'] = "Naam";
$text['label-sip_profile_setting_name']['pl-pl'] = "Nazwa";
$text['label-sip_profile_setting_name']['pt-br'] = "Nome"; //copied from pt-pt
$text['label-sip_profile_setting_name']['pt-pt'] = "Nome";
$text['label-sip_profile_setting_name']['ro-ro'] = "";
$text['label-sip_profile_setting_name']['ru-ru'] = "Название";
$text['label-sip_profile_setting_name']['sv-se'] = "Namn";
$text['label-sip_profile_setting_name']['uk-ua'] = "Назва";

$text['label-sip_profile_setting_value']['en-us'] = "Value";
$text['label-sip_profile_setting_value']['en-gb'] = "Value";
$text['label-sip_profile_setting_value']['ar-eg'] = "";
$text['label-sip_profile_setting_value']['de-at'] = "Wert"; //copied from de-de
$text['label-sip_profile_setting_value']['de-ch'] = "Wert"; //copied from de-de
$text['label-sip_profile_setting_value']['de-de'] = "Wert";
$text['label-sip_profile_setting_value']['es-cl'] = "Valor";
$text['label-sip_profile_setting_value']['es-mx'] = "Valor"; //copied from es-cl
$text['label-sip_profile_setting_value']['fr-ca'] = "Valeur"; //copied from fr-fr
$text['label-sip_profile_setting_value']['fr-fr'] = "Valeur";
$text['label-sip_profile_setting_value']['he-il'] = "";
$text['label-sip_profile_setting_value']['it-it'] = "";
$text['label-sip_profile_setting_value']['nl-nl'] = "Waarde";
$text['label-sip_profile_setting_value']['pl-pl'] = "Wartość";
$text['label-sip_profile_setting_value']['pt-br'] = "Valor"; //copied from pt-pt
$text['label-sip_profile_setting_value']['pt-pt'] = "Valor";
$text['label-sip_profile_setting_value']['ro-ro'] = "";
$text['label-sip_profile_setting_value']['ru-ru'] = "Значение";
$text['label-sip_profile_setting_value']['sv-se'] = "Värde";
$text['label-sip_profile_setting_value']['uk-ua'] = "Значення";

$text['label-sip_profile_setting_enabled']['en-us'] = "Enabled";
$text['label-sip_profile_setting_enabled']['en-gb'] = "Enabled";
$text['label-sip_profile_setting_enabled']['ar-eg'] = "";
$text['label-sip_profile_setting_enabled']['de-at'] = "Aktiv"; //copied from de-de
$text['label-sip_profile_setting_enabled']['de-ch'] = "Aktiv"; //copied from de-de
$text['label-sip_profile_setting_enabled']['de-de'] = "Aktiv";
$text['label-sip_profile_setting_enabled']['es-cl'] = "Activado";
$text['label-sip_profile_setting_enabled']['es-mx'] = "Activado"; //copied from es-cl
$text['label-sip_profile_setting_enabled']['fr-ca'] = "Actif"; //copied from fr-fr
$text['label-sip_profile_setting_enabled']['fr-fr'] = "Actif";
$text['label-sip_profile_setting_enabled']['he-il'] = "";
$text['label-sip_profile_setting_enabled']['it-it'] = "";
$text['label-sip_profile_setting_enabled']['nl-nl'] = "Aan";
$text['label-sip_profile_setting_enabled']['pl-pl'] = "Włączony";
$text['label-sip_profile_setting_enabled']['pt-br'] = "Habilitado"; //copied from pt-pt
$text['label-sip_profile_setting_enabled']['pt-pt'] = "Habilitado";
$text['label-sip_profile_setting_enabled']['ro-ro'] = "";
$text['label-sip_profile_setting_enabled']['ru-ru'] = "Включено";
$text['label-sip_profile_setting_enabled']['sv-se'] = "Aktiverad";
$text['label-sip_profile_setting_enabled']['uk-ua'] = "Включено";

$text['label-sip_profile_setting_description']['en-us'] = "Description";
$text['label-sip_profile_setting_description']['en-gb'] = "Description";
$text['label-sip_profile_setting_description']['ar-eg'] = "";
$text['label-sip_profile_setting_description']['de-at'] = "Beschreibung"; //copied from de-de
$text['label-sip_profile_setting_description']['de-ch'] = "Beschreibung"; //copied from de-de
$text['label-sip_profile_setting_description']['de-de'] = "Beschreibung";
$text['label-sip_profile_setting_description']['es-cl'] = "Descripción";
$text['label-sip_profile_setting_description']['es-mx'] = "Descripción"; //copied from es-cl
$text['label-sip_profile_setting_description']['fr-ca'] = "Description"; //copied from fr-fr
$text['label-sip_profile_setting_description']['fr-fr'] = "Description";
$text['label-sip_profile_setting_description']['he-il'] = "";
$text['label-sip_profile_setting_description']['it-it'] = "";
$text['label-sip_profile_setting_description']['nl-nl'] = "Omschrijving";
$text['label-sip_profile_setting_description']['pl-pl'] = "Opis";
$text['label-sip_profile_setting_description']['pt-br'] = "Descrição"; //copied from pt-pt
$text['label-sip_profile_setting_description']['pt-pt'] = "Descrição";
$text['label-sip_profile_setting_description']['ro-ro'] = "";
$text['label-sip_profile_setting_description']['ru-ru'] = "Описание";
$text['label-sip_profile_setting_description']['sv-se'] = "Beskrivning";
$text['label-sip_profile_setting_description']['uk-ua'] = "Опис";

$text['label-sip_profile_hostname']['en-us'] = "Hostname";
$text['label-sip_profile_hostname']['en-gb'] = "Hostname";
$text['label-sip_profile_hostname']['ar-eg'] = "";
$text['label-sip_profile_hostname']['de-at'] = "Hostname"; //copied from de-de
$text['label-sip_profile_hostname']['de-ch'] = "Hostname"; //copied from de-de
$text['label-sip_profile_hostname']['de-de'] = "Hostname";
$text['label-sip_profile_hostname']['es-cl'] = "";
$text['label-sip_profile_hostname']['es-mx'] = "";
$text['label-sip_profile_hostname']['fr-ca'] = "Nom d'hôte"; //copied from fr-fr
$text['label-sip_profile_hostname']['fr-fr'] = "Nom d'hôte";
$text['label-sip_profile_hostname']['he-il'] = "";
$text['label-sip_profile_hostname']['it-it'] = "";
$text['label-sip_profile_hostname']['nl-nl'] = "Hostnaam";
$text['label-sip_profile_hostname']['pl-pl'] = "Nazwa hosta";
$text['label-sip_profile_hostname']['pt-br'] = "Hostname"; //copied from pt-pt
$text['label-sip_profile_hostname']['pt-pt'] = "Hostname";
$text['label-sip_profile_hostname']['ro-ro'] = "";
$text['label-sip_profile_hostname']['ru-ru'] = "Имя хоста";
$text['label-sip_profile_hostname']['sv-se'] = "Hostname";
$text['label-sip_profile_hostname']['uk-ua'] = "Назва хоста";

$text['label-sip_profile_settings']['en-us'] = "Settings";
$text['label-sip_profile_settings']['en-gb'] = "Settings";
$text['label-sip_profile_settings']['ar-eg'] = "";
$text['label-sip_profile_settings']['de-at'] = "Einstellungen"; //copied from de-de
$text['label-sip_profile_settings']['de-ch'] = "Einstellungen"; //copied from de-de
$text['label-sip_profile_settings']['de-de'] = "Einstellungen";
$text['label-sip_profile_settings']['es-cl'] = "Configuraciones";
$text['label-sip_profile_settings']['es-mx'] = "Configuraciones"; //copied from es-cl
$text['label-sip_profile_settings']['fr-ca'] = "Paramètres"; //copied from fr-fr
$text['label-sip_profile_settings']['fr-fr'] = "Paramètres";
$text['label-sip_profile_settings']['he-il'] = "";
$text['label-sip_profile_settings']['it-it'] = "";
$text['label-sip_profile_settings']['nl-nl'] = "Instellingen";
$text['label-sip_profile_settings']['pl-pl'] = "Ustawienia";
$text['label-sip_profile_settings']['pt-br'] = "Configurações";
$text['label-sip_profile_settings']['pt-pt'] = "Definições";
$text['label-sip_profile_settings']['ro-ro'] = "";
$text['label-sip_profile_settings']['ru-ru'] = "Настройки";
$text['label-sip_profile_settings']['sv-se'] = "Inställningar";
$text['label-sip_profile_settings']['uk-ua'] = "Параметри";

$text['label-new_sip_profile_name']['en-us'] = "Enter new SIP Profile Name";
$text['label-new_sip_profile_name']['en-gb'] = "Enter new SIP Profile Name";
$text['label-new_sip_profile_name']['ar-eg'] = "Enter new SIP Profile Name";
$text['label-new_sip_profile_name']['de-at'] = "Enter new SIP Profile Name";
$text['label-new_sip_profile_name']['de-ch'] = "Enter new SIP Profile Name";
$text['label-new_sip_profile_name']['de-de'] = "Enter new SIP Profile Name";
$text['label-new_sip_profile_name']['es-cl'] = "Enter new SIP Profile Name";
$text['label-new_sip_profile_name']['es-mx'] = "Enter new SIP Profile Name";
$text['label-new_sip_profile_name']['fr-ca'] = "Entrez le nouveau nom de profil SIP";
$text['label-new_sip_profile_name']['fr-fr'] = "Entrez le nouveau nom de profil SIP";
$text['label-new_sip_profile_name']['he-il'] = "Enter new SIP Profile Name";
$text['label-new_sip_profile_name']['it-it'] = "Enter new SIP Profile Name";
$text['label-new_sip_profile_name']['nl-nl'] = "Enter new SIP Profile Name";
$text['label-new_sip_profile_name']['pl-pl'] = "Enter new SIP Profile Name";
$text['label-new_sip_profile_name']['pt-br'] = "Enter new SIP Profile Name";
$text['label-new_sip_profile_name']['pt-pt'] = "Enter new SIP Profile Name";
$text['label-new_sip_profile_name']['ro-ro'] = "Enter new SIP Profile Name";
$text['label-new_sip_profile_name']['ru-ru'] = "Enter new SIP Profile Name";
$text['label-new_sip_profile_name']['sv-se'] = "Enter new SIP Profile Name";
$text['label-new_sip_profile_name']['uk-ua'] = "Enter new SIP Profile Name";

$text['header-sip_profiles']['en-us'] = "SIP Profiles";
$text['header-sip_profiles']['en-gb'] = "SIP Profiles";
$text['header-sip_profiles']['ar-eg'] = "";
$text['header-sip_profiles']['de-at'] = "SIP Profile"; //copied from de-de
$text['header-sip_profiles']['de-ch'] = "SIP Profile"; //copied from de-de
$text['header-sip_profiles']['de-de'] = "SIP Profile";
$text['header-sip_profiles']['es-cl'] = "Perfiles SIP";
$text['header-sip_profiles']['es-mx'] = "Perfiles SIP"; //copied from es-cl
$text['header-sip_profiles']['fr-ca'] = "Profiles SIP"; //copied from fr-fr
$text['header-sip_profiles']['fr-fr'] = "Profiles SIP";
$text['header-sip_profiles']['he-il'] = "";
$text['header-sip_profiles']['it-it'] = "Profili SIP";
$text['header-sip_profiles']['nl-nl'] = "SIP Profielen";
$text['header-sip_profiles']['pl-pl'] = "Profile SIP";
$text['header-sip_profiles']['pt-br'] = "Perfis SIP"; //copied from pt-pt
$text['header-sip_profiles']['pt-pt'] = "Perfis SIP";
$text['header-sip_profiles']['ro-ro'] = "";
$text['header-sip_profiles']['ru-ru'] = "Профили SIP";
$text['header-sip_profiles']['sv-se'] = "SIP Profiler";
$text['header-sip_profiles']['uk-ua'] = "SIP профілі";

$text['header-sip_profile']['en-us'] = "SIP Profile";
$text['header-sip_profile']['en-gb'] = "SIP Profile";
$text['header-sip_profile']['ar-eg'] = "";
$text['header-sip_profile']['de-at'] = "SIP Profile"; //copied from de-de
$text['header-sip_profile']['de-ch'] = "SIP Profile"; //copied from de-de
$text['header-sip_profile']['de-de'] = "SIP Profile";
$text['header-sip_profile']['es-cl'] = "";
$text['header-sip_profile']['es-mx'] = "";
$text['header-sip_profile']['fr-ca'] = "Profile SIP"; //copied from fr-fr
$text['header-sip_profile']['fr-fr'] = "Profile SIP";
$text['header-sip_profile']['he-il'] = "";
$text['header-sip_profile']['it-it'] = "Profilo SIP";
$text['header-sip_profile']['nl-nl'] = "SIP Profiel";
$text['header-sip_profile']['pl-pl'] = "Profil SIP";
$text['header-sip_profile']['pt-br'] = "Perfil SIP"; //copied from pt-pt
$text['header-sip_profile']['pt-pt'] = "Perfil SIP";
$text['header-sip_profile']['ro-ro'] = "";
$text['header-sip_profile']['ru-ru'] = "Профиль SIP";
$text['header-sip_profile']['sv-se'] = "SIP Profil";
$text['header-sip_profile']['uk-ua'] = "SIP профіль";

$text['header-sip_profile_setting']['en-us'] = "Profile Setting";
$text['header-sip_profile_setting']['en-gb'] = "Profile Setting";
$text['header-sip_profile_setting']['ar-eg'] = "";
$text['header-sip_profile_setting']['de-at'] = "Profil Einstellungen"; //copied from de-de
$text['header-sip_profile_setting']['de-ch'] = "Profil Einstellungen"; //copied from de-de
$text['header-sip_profile_setting']['de-de'] = "Profil Einstellungen";
$text['header-sip_profile_setting']['es-cl'] = "Configuración de Perfil";
$text['header-sip_profile_setting']['es-mx'] = "Configuración de Perfil"; //copied from es-cl
$text['header-sip_profile_setting']['fr-ca'] = "Paramètres du Profile"; //copied from fr-fr
$text['header-sip_profile_setting']['fr-fr'] = "Paramètres du Profile";
$text['header-sip_profile_setting']['he-il'] = "";
$text['header-sip_profile_setting']['it-it'] = "";
$text['header-sip_profile_setting']['nl-nl'] = "Profiel Instellingen";
$text['header-sip_profile_setting']['pl-pl'] = "Ustawienia profilu";
$text['header-sip_profile_setting']['pt-br'] = "Configurações do perfil";
$text['header-sip_profile_setting']['pt-pt'] = "Definições do Perfil";
$text['header-sip_profile_setting']['ro-ro'] = "";
$text['header-sip_profile_setting']['ru-ru'] = "Настройки профиля";
$text['header-sip_profile_setting']['sv-se'] = "Profilinställning";
$text['header-sip_profile_setting']['uk-ua'] = "Налаштування профілю";

$text['header-sip_profile_hostname']['en-us'] = "Hostname";
$text['header-sip_profile_hostname']['en-gb'] = "Hostname";
$text['header-sip_profile_hostname']['ar-eg'] = "";
$text['header-sip_profile_hostname']['de-at'] = "Hostname"; //copied from de-de
$text['header-sip_profile_hostname']['de-ch'] = "Hostname"; //copied from de-de
$text['header-sip_profile_hostname']['de-de'] = "Hostname";
$text['header-sip_profile_hostname']['es-cl'] = "";
$text['header-sip_profile_hostname']['es-mx'] = "";
$text['header-sip_profile_hostname']['fr-ca'] = "Nom d'hôte"; //copied from fr-fr
$text['header-sip_profile_hostname']['fr-fr'] = "Nom d'hôte";
$text['header-sip_profile_hostname']['he-il'] = "";
$text['header-sip_profile_hostname']['it-it'] = "";
$text['header-sip_profile_hostname']['nl-nl'] = "Hostnaam";
$text['header-sip_profile_hostname']['pl-pl'] = "Nazwa hosta";
$text['header-sip_profile_hostname']['pt-br'] = "Hostname"; //copied from pt-pt
$text['header-sip_profile_hostname']['pt-pt'] = "Hostname";
$text['header-sip_profile_hostname']['ro-ro'] = "";
$text['header-sip_profile_hostname']['ru-ru'] = "Имя хоста";
$text['header-sip_profile_hostname']['sv-se'] = "Hostname";
$text['header-sip_profile_hostname']['uk-ua'] = "Назва хоста";

$text['description-sip_profiles']['en-us'] = "Manage settings for SIP profiles.";
$text['description-sip_profiles']['en-gb'] = "Manage settings for SIP profiles.";
$text['description-sip_profiles']['ar-eg'] = "";
$text['description-sip_profiles']['de-at'] = "SIP Profil Einstellungen verwalten."; //copied from de-de
$text['description-sip_profiles']['de-ch'] = "SIP Profil Einstellungen verwalten."; //copied from de-de
$text['description-sip_profiles']['de-de'] = "SIP Profil Einstellungen verwalten.";
$text['description-sip_profiles']['es-cl'] = "Administrar configuraciones para perfiles SIP.";
$text['description-sip_profiles']['es-mx'] = "Administrar configuraciones para perfiles SIP."; //copied from es-cl
$text['description-sip_profiles']['fr-ca'] = "Gérer les paramètres du profile SIP"; //copied from fr-fr
$text['description-sip_profiles']['fr-fr'] = "Gérer les paramètres du profile SIP";
$text['description-sip_profiles']['he-il'] = "";
$text['description-sip_profiles']['it-it'] = "Gestione parametri dei profili SIP.";
$text['description-sip_profiles']['nl-nl'] = "Beheer instellingen voor SIP profielen.";
$text['description-sip_profiles']['pl-pl'] = "Zarządzaj ustawieniami profili SIP.";
$text['description-sip_profiles']['pt-br'] = "Gerenciar configurações para os perfis SIP";
$text['description-sip_profiles']['pt-pt'] = "Gerir definições para os perfis SIP.";
$text['description-sip_profiles']['ro-ro'] = "";
$text['description-sip_profiles']['ru-ru'] = "Управление настройками профилей SIP.";
$text['description-sip_profiles']['sv-se'] = "Hantera inställningar för SIP profiler.";
$text['description-sip_profiles']['uk-ua'] = "Налаштування профілю";

$text['description-sip_profile']['en-us'] = "Manage settings for the SIP profile.";
$text['description-sip_profile']['en-gb'] = "Manage settings for the SIP profile.";
$text['description-sip_profile']['ar-eg'] = "";
$text['description-sip_profile']['de-at'] = "SIP Profil Einstellungen verwalten."; //copied from de-de
$text['description-sip_profile']['de-ch'] = "SIP Profil Einstellungen verwalten."; //copied from de-de
$text['description-sip_profile']['de-de'] = "SIP Profil Einstellungen verwalten.";
$text['description-sip_profile']['es-cl'] = "Administrar configuraciones para perfiles SIP.";
$text['description-sip_profile']['es-mx'] = "Administrar configuraciones para perfiles SIP."; //copied from es-cl
$text['description-sip_profile']['fr-ca'] = "Gérer les paramètres du profile SIP"; //copied from fr-fr
$text['description-sip_profile']['fr-fr'] = "Gérer les paramètres du profile SIP";
$text['description-sip_profile']['he-il'] = "";
$text['description-sip_profile']['it-it'] = "Gestione parametri dei profili SIP.";
$text['description-sip_profile']['nl-nl'] = "Beheer instellingen voor het SIP profiel.";
$text['description-sip_profile']['pl-pl'] = "Zarządzaj ustawienia profilu SIP.";
$text['description-sip_profile']['pt-br'] = "Gerenciar configurações para o perfil SIP";
$text['description-sip_profile']['pt-pt'] = "Gerir definições para o perfil SIP.";
$text['description-sip_profile']['ro-ro'] = "";
$text['description-sip_profile']['ru-ru'] = "Управление настройками профиля SIP.";
$text['description-sip_profile']['sv-se'] = "Hantera inställningar för SIP profil.";
$text['description-sip_profile']['uk-ua'] = "Налаштування SIP профілю";

$text['description-sip_profile_setting_value']['en-us'] = "Enter the value.";
$text['description-sip_profile_setting_value']['en-gb'] = "Enter the value.";
$text['description-sip_profile_setting_value']['ar-eg'] = "";
$text['description-sip_profile_setting_value']['de-at'] = "Geben Sie einen Wert an."; //copied from de-de
$text['description-sip_profile_setting_value']['de-ch'] = "Geben Sie einen Wert an."; //copied from de-de
$text['description-sip_profile_setting_value']['de-de'] = "Geben Sie einen Wert an.";
$text['description-sip_profile_setting_value']['es-cl'] = "Ingrese un valor.";
$text['description-sip_profile_setting_value']['es-mx'] = "Ingrese un valor."; //copied from es-cl
$text['description-sip_profile_setting_value']['fr-ca'] = "Entrer la valeur."; //copied from fr-fr
$text['description-sip_profile_setting_value']['fr-fr'] = "Entrer la valeur.";
$text['description-sip_profile_setting_value']['he-il'] = "";
$text['description-sip_profile_setting_value']['it-it'] = "";
$text['description-sip_profile_setting_value']['nl-nl'] = "Voer de waarde in.";
$text['description-sip_profile_setting_value']['pl-pl'] = "Wprowadź wartość.";
$text['description-sip_profile_setting_value']['pt-br'] = "Insira o valor";
$text['description-sip_profile_setting_value']['pt-pt'] = "Introduza o valor.";
$text['description-sip_profile_setting_value']['ro-ro'] = "";
$text['description-sip_profile_setting_value']['ru-ru'] = "Введите значение.";
$text['description-sip_profile_setting_value']['sv-se'] = "Ange värde.";
$text['description-sip_profile_setting_value']['uk-ua'] = "Вкажіть значення";

$text['description-sip_profile_setting_name']['en-us'] = "Enter the name.";
$text['description-sip_profile_setting_name']['en-gb'] = "Enter the name.";
$text['description-sip_profile_setting_name']['ar-eg'] = "";
$text['description-sip_profile_setting_name']['de-at'] = "Geben Sie den Namen an."; //copied from de-de
$text['description-sip_profile_setting_name']['de-ch'] = "Geben Sie den Namen an."; //copied from de-de
$text['description-sip_profile_setting_name']['de-de'] = "Geben Sie den Namen an.";
$text['description-sip_profile_setting_name']['es-cl'] = "Ingrese un nombre.";
$text['description-sip_profile_setting_name']['es-mx'] = "Ingrese un nombre."; //copied from es-cl
$text['description-sip_profile_setting_name']['fr-ca'] = "Entrer le nom."; //copied from fr-fr
$text['description-sip_profile_setting_name']['fr-fr'] = "Entrer le nom.";
$text['description-sip_profile_setting_name']['he-il'] = "";
$text['description-sip_profile_setting_name']['it-it'] = "";
$text['description-sip_profile_setting_name']['nl-nl'] = "Voer de naam in.";
$text['description-sip_profile_setting_name']['pl-pl'] = "Wpisz nazwę.";
$text['description-sip_profile_setting_name']['pt-br'] = "Insira o nome";
$text['description-sip_profile_setting_name']['pt-pt'] = "Introduza o nome.";
$text['description-sip_profile_setting_name']['ro-ro'] = "";
$text['description-sip_profile_setting_name']['ru-ru'] = "Введите название.";
$text['description-sip_profile_setting_name']['sv-se'] = "Ange Namnet.";
$text['description-sip_profile_setting_name']['uk-ua'] = "Вкажіть назву";

$text['description-sip_profile_setting_enabled']['en-us'] = "Choose to enable or disable this.";
$text['description-sip_profile_setting_enabled']['en-gb'] = "Choose to enable or disable this.";
$text['description-sip_profile_setting_enabled']['ar-eg'] = "";
$text['description-sip_profile_setting_enabled']['de-at'] = "Wählen Sie ob Sie dieses aktivieren oder deaktivieren möchten"; //copied from de-de
$text['description-sip_profile_setting_enabled']['de-ch'] = "Wählen Sie ob Sie dieses aktivieren oder deaktivieren möchten"; //copied from de-de
$text['description-sip_profile_setting_enabled']['de-de'] = "Wählen Sie ob Sie dieses aktivieren oder deaktivieren möchten";
$text['description-sip_profile_setting_enabled']['es-cl'] = "Indique si desea activar o desactivar esto.";
$text['description-sip_profile_setting_enabled']['es-mx'] = "Indique si desea activar o desactivar esto."; //copied from es-cl
$text['description-sip_profile_setting_enabled']['fr-ca'] = "Choisir si le paramètre sera actif ou non."; //copied from fr-fr
$text['description-sip_profile_setting_enabled']['fr-fr'] = "Choisir si le paramètre sera actif ou non.";
$text['description-sip_profile_setting_enabled']['he-il'] = "";
$text['description-sip_profile_setting_enabled']['it-it'] = "";
$text['description-sip_profile_setting_enabled']['nl-nl'] = "Kien om dit aan of uit te zetten.";
$text['description-sip_profile_setting_enabled']['pl-pl'] = "Wybierz, aby włączyć lub wyłączyć tę funkcję.";
$text['description-sip_profile_setting_enabled']['pt-br'] = "Escolha se o parâmetro fica habilitado ou desabilitado. ";
$text['description-sip_profile_setting_enabled']['pt-pt'] = "Escolha se o parâmetro fica habilitado ou desabilitado.";
$text['description-sip_profile_setting_enabled']['ro-ro'] = "";
$text['description-sip_profile_setting_enabled']['ru-ru'] = "Выберите для включенья или отключения функции.";
$text['description-sip_profile_setting_enabled']['sv-se'] = "Välj att Aktivera eller Inaktivare detta.";
$text['description-sip_profile_setting_enabled']['uk-ua'] = "Ви";

$text['description-sip_profile_setting_description']['en-us'] = "Enter the description.";
$text['description-sip_profile_setting_description']['en-gb'] = "Enter the description.";
$text['description-sip_profile_setting_description']['ar-eg'] = "";
$text['description-sip_profile_setting_description']['de-at'] = "Geben Sie eine Beschreibung ein."; //copied from de-de
$text['description-sip_profile_setting_description']['de-ch'] = "Geben Sie eine Beschreibung ein."; //copied from de-de
$text['description-sip_profile_setting_description']['de-de'] = "Geben Sie eine Beschreibung ein.";
$text['description-sip_profile_setting_description']['es-cl'] = "Ingrese una descripción.";
$text['description-sip_profile_setting_description']['es-mx'] = "Ingrese una descripción."; //copied from es-cl
$text['description-sip_profile_setting_description']['fr-ca'] = "Entrer la description."; //copied from fr-fr
$text['description-sip_profile_setting_description']['fr-fr'] = "Entrer la description.";
$text['description-sip_profile_setting_description']['he-il'] = "";
$text['description-sip_profile_setting_description']['it-it'] = "";
$text['description-sip_profile_setting_description']['nl-nl'] = "Voer de omschrijving in.";
$text['description-sip_profile_setting_description']['pl-pl'] = "Wprowadź opis.";
$text['description-sip_profile_setting_description']['pt-br'] = "Insira uma descrição";
$text['description-sip_profile_setting_description']['pt-pt'] = "Introduza uma descrição.";
$text['description-sip_profile_setting_description']['ro-ro'] = "";
$text['description-sip_profile_setting_description']['ru-ru'] = "Введите описание.";
$text['description-sip_profile_setting_description']['sv-se'] = "Ange en Beskrivning.";
$text['description-sip_profile_setting_description']['uk-ua'] = "Введіть опис";

$text['description-sip_profile_name']['en-us'] = "Enter the SIP Profile name.";
$text['description-sip_profile_name']['en-gb'] = "Enter the SIP Profile name.";
$text['description-sip_profile_name']['ar-eg'] = "";
$text['description-sip_profile_name']['de-at'] = "Geben Sie den Namen des SIP Profils ein."; //copied from de-de
$text['description-sip_profile_name']['de-ch'] = "Geben Sie den Namen des SIP Profils ein."; //copied from de-de
$text['description-sip_profile_name']['de-de'] = "Geben Sie den Namen des SIP Profils ein.";
$text['description-sip_profile_name']['es-cl'] = "Ingrese el nombre de perfil SIP.";
$text['description-sip_profile_name']['es-mx'] = "Ingrese el nombre de perfil SIP."; //copied from es-cl
$text['description-sip_profile_name']['fr-ca'] = "Entrer le nom du Profile SIP."; //copied from fr-fr
$text['description-sip_profile_name']['fr-fr'] = "Entrer le nom du Profile SIP.";
$text['description-sip_profile_name']['he-il'] = "";
$text['description-sip_profile_name']['it-it'] = "";
$text['description-sip_profile_name']['nl-nl'] = "Voer de SIP profielnaam in";
$text['description-sip_profile_name']['pl-pl'] = "Wprowadź nazwę";
$text['description-sip_profile_name']['pt-br'] = "Insira o nome do menu";
$text['description-sip_profile_name']['pt-pt'] = "Introduza o nome do perfil SIP.";
$text['description-sip_profile_name']['ro-ro'] = "";
$text['description-sip_profile_name']['ru-ru'] = "Введите имя профиля SIP.";
$text['description-sip_profile_name']['sv-se'] = "Skriv in namnet på SIP Profilen.";
$text['description-sip_profile_name']['uk-ua'] = "Введіть назву профілю";

$text['description-sip_profile_hostname']['en-us'] = "Enter the hostname / switchname.";
$text['description-sip_profile_hostname']['en-gb'] = "Enter the hostname / switchname.";
$text['description-sip_profile_hostname']['ar-eg'] = "";
$text['description-sip_profile_hostname']['de-at'] = "Geben Sie den Hostnamen / Switchnamen an."; //copied from de-de
$text['description-sip_profile_hostname']['de-ch'] = "Geben Sie den Hostnamen / Switchnamen an."; //copied from de-de
$text['description-sip_profile_hostname']['de-de'] = "Geben Sie den Hostnamen / Switchnamen an.";
$text['description-sip_profile_hostname']['es-cl'] = "";
$text['description-sip_profile_hostname']['es-mx'] = "";
$text['description-sip_profile_hostname']['fr-ca'] = "Entrer le nom de l'hôte / du switch."; //copied from fr-fr
$text['description-sip_profile_hostname']['fr-fr'] = "Entrer le nom de l'hôte / du switch.";
$text['description-sip_profile_hostname']['he-il'] = "";
$text['description-sip_profile_hostname']['it-it'] = "";
$text['description-sip_profile_hostname']['nl-nl'] = "Voer de hostnaam / centralenaam in.";
$text['description-sip_profile_hostname']['pl-pl'] = "Wprowadź nazwę hosta / PBXu.";
$text['description-sip_profile_hostname']['pt-br'] = "Insira o hostname";
$text['description-sip_profile_hostname']['pt-pt'] = "Introduza o hostname";
$text['description-sip_profile_hostname']['ro-ro'] = "";
$text['description-sip_profile_hostname']['ru-ru'] = "Введите имя хоста / имя PBX.";
$text['description-sip_profile_hostname']['sv-se'] = "Fyll i hostname / switchname.";
$text['description-sip_profile_hostname']['uk-ua'] = "Введіть назву хоста / switchname.";

$text['description-sip_profile_enabled']['en-us'] = "Control the state of the profile.";
$text['description-sip_profile_enabled']['en-gb'] = "Control the state of the profile.";
$text['description-sip_profile_enabled']['ar-eg'] = "";
$text['description-sip_profile_enabled']['de-at'] = "Setzen Sie den Status dieses Profils."; //copied from de-de
$text['description-sip_profile_enabled']['de-ch'] = "Setzen Sie den Status dieses Profils."; //copied from de-de
$text['description-sip_profile_enabled']['de-de'] = "Setzen Sie den Status dieses Profils.";
$text['description-sip_profile_enabled']['es-cl'] = "";
$text['description-sip_profile_enabled']['es-mx'] = "";
$text['description-sip_profile_enabled']['fr-ca'] = "Contrôler l'état du profil."; //copied from fr-fr
$text['description-sip_profile_enabled']['fr-fr'] = "Contrôler l'état du profil.";
$text['description-sip_profile_enabled']['he-il'] = "";
$text['description-sip_profile_enabled']['it-it'] = "";
$text['description-sip_profile_enabled']['nl-nl'] = "Stel de status van het profiel in.";
$text['description-sip_profile_enabled']['pl-pl'] = "Kontroluj stan profilu.";
$text['description-sip_profile_enabled']['pt-br'] = "Controlar o estado do perfil."; //copied from pt-pt
$text['description-sip_profile_enabled']['pt-pt'] = "Controlar o estado do perfil.";
$text['description-sip_profile_enabled']['ro-ro'] = "";
$text['description-sip_profile_enabled']['ru-ru'] = "Управление состоянием профиля.";
$text['description-sip_profile_enabled']['sv-se'] = "Styr tillståndet i profilen.";
$text['description-sip_profile_enabled']['uk-ua'] = "Керування станом профілю";

?>
