<?php
#This file was last reorganized on 19th of September 2017 08:54:24 AM UTC

$text['title-dialplan-inbound-add']['en-us'] = "Inbound Call Routing";
$text['title-dialplan-inbound-add']['en-gb'] = "Inbound Call Routing";
$text['title-dialplan-inbound-add']['ar-eg'] = "";
$text['title-dialplan-inbound-add']['de-at'] = "Routing eingehender Anrufe"; //copied from de-de
$text['title-dialplan-inbound-add']['de-ch'] = "Routing eingehender Anrufe"; //copied from de-de
$text['title-dialplan-inbound-add']['de-de'] = "Routing eingehender Anrufe";
$text['title-dialplan-inbound-add']['es-cl'] = "Ruteo de Llamadas Entrantes";
$text['title-dialplan-inbound-add']['es-mx'] = "Ruteo de Llamadas Entrantes"; //copied from es-cl
$text['title-dialplan-inbound-add']['fr-ca'] = "Routage des appels entrant"; //copied from fr-fr
$text['title-dialplan-inbound-add']['fr-fr'] = "Routage des appels entrant";
$text['title-dialplan-inbound-add']['he-il'] = "";
$text['title-dialplan-inbound-add']['it-it'] = "Istradamento Chiamate in Ingresso";
$text['title-dialplan-inbound-add']['nl-nl'] = "Inkomende oproep routering";
$text['title-dialplan-inbound-add']['pl-pl'] = "Przesyłanie (routing) rozmów przychodzących";
$text['title-dialplan-inbound-add']['pt-br'] = "Encaminhamento de chamadas de entrada"; //copied from pt-pt
$text['title-dialplan-inbound-add']['pt-pt'] = "Encaminhamento de chamadas de entrada";
$text['title-dialplan-inbound-add']['ro-ro'] = "";
$text['title-dialplan-inbound-add']['ru-ru'] = "Маршрутизация входящих вызовов";
$text['title-dialplan-inbound-add']['sv-se'] = "Inkommande Call Routing";
$text['title-dialplan-inbound-add']['uk-ua'] = "Маршрутизація вхідних дзвінків";

$text['option-uuid']['en-us'] = "UUID";
$text['option-uuid']['en-gb'] = "UUID";
$text['option-uuid']['ar-eg'] = "";
$text['option-uuid']['de-at'] = "UUID"; //copied from de-de
$text['option-uuid']['de-ch'] = "UUID"; //copied from de-de
$text['option-uuid']['de-de'] = "UUID";
$text['option-uuid']['es-cl'] = "UUID";
$text['option-uuid']['es-mx'] = "UUID"; //copied from es-cl
$text['option-uuid']['fr-ca'] = "UUID"; //copied from fr-fr
$text['option-uuid']['fr-fr'] = "UUID";
$text['option-uuid']['he-il'] = "";
$text['option-uuid']['it-it'] = "UUID";
$text['option-uuid']['nl-nl'] = "UUID";
$text['option-uuid']['pl-pl'] = "UUID";
$text['option-uuid']['pt-br'] = "UUID"; //copied from pt-pt
$text['option-uuid']['pt-pt'] = "UUID";
$text['option-uuid']['ro-ro'] = "";
$text['option-uuid']['ru-ru'] = "UUID";
$text['option-uuid']['sv-se'] = "UUID";
$text['option-uuid']['uk-ua'] = "UUID";

$text['option-username']['en-us'] = "Username";
$text['option-username']['en-gb'] = "Username";
$text['option-username']['ar-eg'] = "";
$text['option-username']['de-at'] = "Benutzername"; //copied from de-de
$text['option-username']['de-ch'] = "Benutzername"; //copied from de-de
$text['option-username']['de-de'] = "Benutzername";
$text['option-username']['es-cl'] = "Nombre de usuario";
$text['option-username']['es-mx'] = "Nombre de usuario"; //copied from es-cl
$text['option-username']['fr-ca'] = "Nom d'utilisateur"; //copied from fr-fr
$text['option-username']['fr-fr'] = "Nom d'utilisateur";
$text['option-username']['he-il'] = "";
$text['option-username']['it-it'] = "Username";
$text['option-username']['nl-nl'] = "Gebruikersnaam";
$text['option-username']['pl-pl'] = "Użytkownik";
$text['option-username']['pt-br'] = "Usuário"; //copied from pt-pt
$text['option-username']['pt-pt'] = "Nome de Utilizador";
$text['option-username']['ro-ro'] = "";
$text['option-username']['ru-ru'] = "Имя Пользователя";
$text['option-username']['sv-se'] = "Användarnamn";
$text['option-username']['uk-ua'] = "Користувач";

$text['option-source']['en-us'] = "Source";
$text['option-source']['en-gb'] = "Source";
$text['option-source']['ar-eg'] = "";
$text['option-source']['de-at'] = "Quelle"; //copied from de-de
$text['option-source']['de-ch'] = "Quelle"; //copied from de-de
$text['option-source']['de-de'] = "Quelle";
$text['option-source']['es-cl'] = "Fuente";
$text['option-source']['es-mx'] = "Fuente"; //copied from es-cl
$text['option-source']['fr-ca'] = "Source"; //copied from fr-fr
$text['option-source']['fr-fr'] = "Source";
$text['option-source']['he-il'] = "";
$text['option-source']['it-it'] = "Sorgente";
$text['option-source']['nl-nl'] = "Bron";
$text['option-source']['pl-pl'] = "Źródło";
$text['option-source']['pt-br'] = "Origem"; //copied from pt-pt
$text['option-source']['pt-pt'] = "Fonte";
$text['option-source']['ro-ro'] = "";
$text['option-source']['ru-ru'] = "Источник";
$text['option-source']['sv-se'] = "Källa";
$text['option-source']['uk-ua'] = "Джерело";

$text['option-rdnis']['en-us'] = "RDNIS";
$text['option-rdnis']['en-gb'] = "RDNIS";
$text['option-rdnis']['ar-eg'] = "";
$text['option-rdnis']['de-at'] = "RDNIS"; //copied from de-de
$text['option-rdnis']['de-ch'] = "RDNIS"; //copied from de-de
$text['option-rdnis']['de-de'] = "RDNIS";
$text['option-rdnis']['es-cl'] = "RDNIS";
$text['option-rdnis']['es-mx'] = "RDNIS"; //copied from es-cl
$text['option-rdnis']['fr-ca'] = "RDNIS"; //copied from fr-fr
$text['option-rdnis']['fr-fr'] = "RDNIS";
$text['option-rdnis']['he-il'] = "";
$text['option-rdnis']['it-it'] = "RDNIS";
$text['option-rdnis']['nl-nl'] = "RDNIS";
$text['option-rdnis']['pl-pl'] = "RDNIS";
$text['option-rdnis']['pt-br'] = "RDNIS"; //copied from pt-pt
$text['option-rdnis']['pt-pt'] = "RDNIS";
$text['option-rdnis']['ro-ro'] = "";
$text['option-rdnis']['ru-ru'] = "RDNIS";
$text['option-rdnis']['sv-se'] = "RDNIS";
$text['option-rdnis']['uk-ua'] = "RDNIS";

$text['option-public']['en-us'] = "Public";
$text['option-public']['en-gb'] = "Public";
$text['option-public']['ar-eg'] = "";
$text['option-public']['de-at'] = "Öffentlich"; //copied from de-de
$text['option-public']['de-ch'] = "Öffentlich"; //copied from de-de
$text['option-public']['de-de'] = "Öffentlich";
$text['option-public']['es-cl'] = "Público";
$text['option-public']['es-mx'] = "Público"; //copied from es-cl
$text['option-public']['fr-ca'] = "Publique";
$text['option-public']['fr-fr'] = "Publique";
$text['option-public']['he-il'] = "";
$text['option-public']['it-it'] = "Public";
$text['option-public']['nl-nl'] = "Openbaar";
$text['option-public']['pl-pl'] = "Publiczny";
$text['option-public']['pt-br'] = "Público"; //copied from pt-pt
$text['option-public']['pt-pt'] = "Público";
$text['option-public']['ro-ro'] = "";
$text['option-public']['ru-ru'] = "Публичный";
$text['option-public']['sv-se'] = "Publik";
$text['option-public']['uk-ua'] = "Публічний";

$text['option-network_addr']['en-us'] = "Network Address";
$text['option-network_addr']['en-gb'] = "Network Address";
$text['option-network_addr']['ar-eg'] = "";
$text['option-network_addr']['de-at'] = "Netzwerk Adresse"; //copied from de-de
$text['option-network_addr']['de-ch'] = "Netzwerk Adresse"; //copied from de-de
$text['option-network_addr']['de-de'] = "Netzwerk Adresse";
$text['option-network_addr']['es-cl'] = "Dirección de Red";
$text['option-network_addr']['es-mx'] = "Dirección de Red"; //copied from es-cl
$text['option-network_addr']['fr-ca'] = "Adresse Réseau"; //copied from fr-fr
$text['option-network_addr']['fr-fr'] = "Adresse Réseau";
$text['option-network_addr']['he-il'] = "";
$text['option-network_addr']['it-it'] = "Indirizzo di Rete";
$text['option-network_addr']['nl-nl'] = "Netwerk adres";
$text['option-network_addr']['pl-pl'] = "Adres sieci";
$text['option-network_addr']['pt-br'] = "Endereço de Rede"; //copied from pt-pt
$text['option-network_addr']['pt-pt'] = "Endereço de Rede";
$text['option-network_addr']['ro-ro'] = "";
$text['option-network_addr']['ru-ru'] = "Сетевой адрес";
$text['option-network_addr']['sv-se'] = "Nätverk Address";
$text['option-network_addr']['uk-ua'] = "Адреси мережі";

$text['option-destination_number']['en-us'] = "Destination Number";
$text['option-destination_number']['en-gb'] = "Destination Number";
$text['option-destination_number']['ar-eg'] = "";
$text['option-destination_number']['de-at'] = "Ziel Rufnummer"; //copied from de-de
$text['option-destination_number']['de-ch'] = "Ziel Rufnummer"; //copied from de-de
$text['option-destination_number']['de-de'] = "Ziel Rufnummer";
$text['option-destination_number']['es-cl'] = "Número de Destino";
$text['option-destination_number']['es-mx'] = "Número de Destino"; //copied from es-cl
$text['option-destination_number']['fr-ca'] = "Numéro de Destination"; //copied from fr-fr
$text['option-destination_number']['fr-fr'] = "Numéro de Destination";
$text['option-destination_number']['he-il'] = "";
$text['option-destination_number']['it-it'] = "Numero Destinazione";
$text['option-destination_number']['nl-nl'] = "Bestemmingsnummer";
$text['option-destination_number']['pl-pl'] = "Numer destynacji";
$text['option-destination_number']['pt-br'] = "Número de Destino"; //copied from pt-pt
$text['option-destination_number']['pt-pt'] = "Número de Destino";
$text['option-destination_number']['ro-ro'] = "";
$text['option-destination_number']['ru-ru'] = "Целевой номер";
$text['option-destination_number']['sv-se'] = "Destination Nummer";
$text['option-destination_number']['uk-ua'] = "Номер призначення";

$text['option-context']['en-us'] = "Context";
$text['option-context']['en-gb'] = "Context";
$text['option-context']['ar-eg'] = "";
$text['option-context']['de-at'] = "Kontext"; //copied from de-de
$text['option-context']['de-ch'] = "Kontext"; //copied from de-de
$text['option-context']['de-de'] = "Kontext";
$text['option-context']['es-cl'] = "Contexto";
$text['option-context']['es-mx'] = "Contexto"; //copied from es-cl
$text['option-context']['fr-ca'] = "Contexte"; //copied from fr-fr
$text['option-context']['fr-fr'] = "Contexte";
$text['option-context']['he-il'] = "";
$text['option-context']['it-it'] = "Contesto";
$text['option-context']['nl-nl'] = "Context";
$text['option-context']['pl-pl'] = "Kontekst";
$text['option-context']['pt-br'] = "Contexto"; //copied from pt-pt
$text['option-context']['pt-pt'] = "Contexto";
$text['option-context']['ro-ro'] = "";
$text['option-context']['ru-ru'] = "Контекст";
$text['option-context']['sv-se'] = "Context";
$text['option-context']['uk-ua'] = "Контекст";

$text['option-chan_name']['en-us'] = "Channel Name";
$text['option-chan_name']['en-gb'] = "Channel Name";
$text['option-chan_name']['ar-eg'] = "";
$text['option-chan_name']['de-at'] = "Kanal Name"; //copied from de-de
$text['option-chan_name']['de-ch'] = "Kanal Name"; //copied from de-de
$text['option-chan_name']['de-de'] = "Kanal Name";
$text['option-chan_name']['es-cl'] = "Nombre de Canal";
$text['option-chan_name']['es-mx'] = "Nombre de Canal"; //copied from es-cl
$text['option-chan_name']['fr-ca'] = "Nom de canal"; //copied from fr-fr
$text['option-chan_name']['fr-fr'] = "Nom de canal";
$text['option-chan_name']['he-il'] = "";
$text['option-chan_name']['it-it'] = "Nome Canale";
$text['option-chan_name']['nl-nl'] = "Kanaalnaam";
$text['option-chan_name']['pl-pl'] = "Nazwa kanału";
$text['option-chan_name']['pt-br'] = "Nome do Canal"; //copied from pt-pt
$text['option-chan_name']['pt-pt'] = "Nome do Canal";
$text['option-chan_name']['ro-ro'] = "";
$text['option-chan_name']['ru-ru'] = "Имя Канала";
$text['option-chan_name']['sv-se'] = "Kanal Namn";
$text['option-chan_name']['uk-ua'] = "Назва каналу";

$text['option-caller_id_number']['en-us'] = "Caller ID Number";
$text['option-caller_id_number']['en-gb'] = "Caller ID Number";
$text['option-caller_id_number']['ar-eg'] = "";
$text['option-caller_id_number']['de-at'] = "Anruferkennung (Nummer)"; //copied from de-de
$text['option-caller_id_number']['de-ch'] = "Anruferkennung (Nummer)"; //copied from de-de
$text['option-caller_id_number']['de-de'] = "Anruferkennung (Nummer)";
$text['option-caller_id_number']['es-cl'] = "Número de Caller ID";
$text['option-caller_id_number']['es-mx'] = "Número de Caller ID"; //copied from es-cl
$text['option-caller_id_number']['fr-ca'] = "Numéro d'appelant"; //copied from fr-fr
$text['option-caller_id_number']['fr-fr'] = "Numéro d'appelant";
$text['option-caller_id_number']['he-il'] = "";
$text['option-caller_id_number']['it-it'] = "ID Numero Chiamante";
$text['option-caller_id_number']['nl-nl'] = "CID nummer";
$text['option-caller_id_number']['pl-pl'] = "Prezentacja numeru dzwoniącego";
$text['option-caller_id_number']['pt-br'] = "Número do ID do Chamador"; //copied from pt-pt
$text['option-caller_id_number']['pt-pt'] = "Número do Chamador";
$text['option-caller_id_number']['ro-ro'] = "";
$text['option-caller_id_number']['ru-ru'] = "Идентификационный Номер (Caller ID) вызывающего абонента";
$text['option-caller_id_number']['sv-se'] = "Caller ID Nummer";
$text['option-caller_id_number']['uk-ua'] = "Caller ID Номер";

$text['option-caller_id_name']['en-us'] = "Caller ID Name";
$text['option-caller_id_name']['en-gb'] = "Caller ID Name";
$text['option-caller_id_name']['ar-eg'] = "";
$text['option-caller_id_name']['de-at'] = "Anruferkennung (Name)"; //copied from de-de
$text['option-caller_id_name']['de-ch'] = "Anruferkennung (Name)"; //copied from de-de
$text['option-caller_id_name']['de-de'] = "Anruferkennung (Name)";
$text['option-caller_id_name']['es-cl'] = "Nombre de Caller ID";
$text['option-caller_id_name']['es-mx'] = "Nombre de Caller ID"; //copied from es-cl
$text['option-caller_id_name']['fr-ca'] = "Nom d'appelant"; //copied from fr-fr
$text['option-caller_id_name']['fr-fr'] = "Nom d'appelant";
$text['option-caller_id_name']['he-il'] = "";
$text['option-caller_id_name']['it-it'] = "ID Nome Chiamante";
$text['option-caller_id_name']['nl-nl'] = "CID Naam";
$text['option-caller_id_name']['pl-pl'] = "Prezentacja nazwy dzwoniącego";
$text['option-caller_id_name']['pt-br'] = "Nome de ID do Chamador"; //copied from pt-pt
$text['option-caller_id_name']['pt-pt'] = "Nome do Chamador";
$text['option-caller_id_name']['ro-ro'] = "";
$text['option-caller_id_name']['ru-ru'] = "Идентификационный Имя (Caller ID) вызывающего абонента";
$text['option-caller_id_name']['sv-se'] = "Caller ID Namn";
$text['option-caller_id_name']['uk-ua'] = "Caller ID Назва";

$text['option-ani2']['en-us'] = "ANI2";
$text['option-ani2']['en-gb'] = "ANI2";
$text['option-ani2']['ar-eg'] = "";
$text['option-ani2']['de-at'] = "ANI2"; //copied from de-de
$text['option-ani2']['de-ch'] = "ANI2"; //copied from de-de
$text['option-ani2']['de-de'] = "ANI2";
$text['option-ani2']['es-cl'] = "ANI2";
$text['option-ani2']['es-mx'] = "ANI2"; //copied from es-cl
$text['option-ani2']['fr-ca'] = "ANI2"; //copied from fr-fr
$text['option-ani2']['fr-fr'] = "ANI2";
$text['option-ani2']['he-il'] = "";
$text['option-ani2']['it-it'] = "ANI2";
$text['option-ani2']['nl-nl'] = "ANI2";
$text['option-ani2']['pl-pl'] = "ANI2";
$text['option-ani2']['pt-br'] = "ANI2"; //copied from pt-pt
$text['option-ani2']['pt-pt'] = "ANI2";
$text['option-ani2']['ro-ro'] = "";
$text['option-ani2']['ru-ru'] = "ANI2";
$text['option-ani2']['sv-se'] = "ANI2";
$text['option-ani2']['uk-ua'] = "ANI2";

$text['option-ani']['en-us'] = "ANI";
$text['option-ani']['en-gb'] = "ANI";
$text['option-ani']['ar-eg'] = "";
$text['option-ani']['de-at'] = "ANI"; //copied from de-de
$text['option-ani']['de-ch'] = "ANI"; //copied from de-de
$text['option-ani']['de-de'] = "ANI";
$text['option-ani']['es-cl'] = "ANI";
$text['option-ani']['es-mx'] = "ANI"; //copied from es-cl
$text['option-ani']['fr-ca'] = "ANI"; //copied from fr-fr
$text['option-ani']['fr-fr'] = "ANI";
$text['option-ani']['he-il'] = "";
$text['option-ani']['it-it'] = "ANI";
$text['option-ani']['nl-nl'] = "ANI";
$text['option-ani']['pl-pl'] = "ANI";
$text['option-ani']['pt-br'] = "ANI"; //copied from pt-pt
$text['option-ani']['pt-pt'] = "ANI";
$text['option-ani']['ro-ro'] = "";
$text['option-ani']['ru-ru'] = "ANI";
$text['option-ani']['sv-se'] = "ANI";
$text['option-ani']['uk-ua'] = "ANI";

$text['label-select-inbound-destination-number']['en-us'] = "Select the inbound destination number.";
$text['label-select-inbound-destination-number']['en-gb'] = "Select the inbound destination number.";
$text['label-select-inbound-destination-number']['ar-eg'] = "";
$text['label-select-inbound-destination-number']['de-at'] = "Wählen Sie die Zielnummer für eingehende Anrufe."; //copied from de-de
$text['label-select-inbound-destination-number']['de-ch'] = "Wählen Sie die Zielnummer für eingehende Anrufe."; //copied from de-de
$text['label-select-inbound-destination-number']['de-de'] = "Wählen Sie die Zielnummer für eingehende Anrufe.";
$text['label-select-inbound-destination-number']['es-cl'] = "Seleccione el número de destino entrante.";
$text['label-select-inbound-destination-number']['es-mx'] = "Seleccione el número de destino entrante."; //copied from es-cl
$text['label-select-inbound-destination-number']['fr-ca'] = "Sélectionnez le numéro de destination entrant.";
$text['label-select-inbound-destination-number']['fr-fr'] = "Sélectionnez le numéro de destination entrant.";
$text['label-select-inbound-destination-number']['he-il'] = "";
$text['label-select-inbound-destination-number']['it-it'] = "Seleziona il numero di destinazione in ingresso.";
$text['label-select-inbound-destination-number']['nl-nl'] = "Kies het inkomende bestemmingsnummer.";
$text['label-select-inbound-destination-number']['pl-pl'] = "Wybierz destynację numeru przychodzącego.";
$text['label-select-inbound-destination-number']['pt-br'] = "Selecione o número de entrada."; //copied from pt-pt
$text['label-select-inbound-destination-number']['pt-pt'] = "Escolha um número de entrada.";
$text['label-select-inbound-destination-number']['ro-ro'] = "";
$text['label-select-inbound-destination-number']['ru-ru'] = "Выберите номер входящего набора.";
$text['label-select-inbound-destination-number']['sv-se'] = "Välj inkommande destinations nummer.";
$text['label-select-inbound-destination-number']['uk-ua'] = "Виберіть вхідний номер";

$text['label-required-domain_uuid']['en-us'] = "Please provide: domain_uuid";
$text['label-required-domain_uuid']['en-gb'] = "Please provide: domain_uuid";
$text['label-required-domain_uuid']['ar-eg'] = "";
$text['label-required-domain_uuid']['de-at'] = "Bitte angeben: domain_uuid"; //copied from de-de
$text['label-required-domain_uuid']['de-ch'] = "Bitte angeben: domain_uuid"; //copied from de-de
$text['label-required-domain_uuid']['de-de'] = "Bitte angeben: domain_uuid";
$text['label-required-domain_uuid']['es-cl'] = "Por favor indique: domain_uuid";
$text['label-required-domain_uuid']['es-mx'] = "Por favor indique: domain_uuid"; //copied from es-cl
$text['label-required-domain_uuid']['fr-ca'] = "Merci d'indiquer: domain_uuid"; //copied from fr-fr
$text['label-required-domain_uuid']['fr-fr'] = "Merci d'indiquer: domain_uuid";
$text['label-required-domain_uuid']['he-il'] = "";
$text['label-required-domain_uuid']['it-it'] = "Prego fornire: domain_uuid";
$text['label-required-domain_uuid']['nl-nl'] = "Geef aub.: domein_uuid";
$text['label-required-domain_uuid']['pl-pl'] = "Label 10";
$text['label-required-domain_uuid']['pt-br'] = "Por favor indique: domain_uuid"; //copied from pt-pt
$text['label-required-domain_uuid']['pt-pt'] = "Por favor indique: domain_uuid";
$text['label-required-domain_uuid']['ro-ro'] = "";
$text['label-required-domain_uuid']['ru-ru'] = "Пожалуйста укажите: domain_uuid";
$text['label-required-domain_uuid']['sv-se'] = "Var god ange: domain_uuid";
$text['label-required-domain_uuid']['uk-ua'] = "Будь ласка, надайте: UUID домену";

$text['label-required-dialplan_name']['en-us'] = "Please provide: Extension Name";
$text['label-required-dialplan_name']['en-gb'] = "Please provide: Extension Name";
$text['label-required-dialplan_name']['ar-eg'] = "";
$text['label-required-dialplan_name']['de-at'] = "Bitte angeben: Namen der Nebenstelle"; //copied from de-de
$text['label-required-dialplan_name']['de-ch'] = "Bitte angeben: Namen der Nebenstelle"; //copied from de-de
$text['label-required-dialplan_name']['de-de'] = "Bitte angeben: Namen der Nebenstelle";
$text['label-required-dialplan_name']['es-cl'] = "Por favor indique: Nombre Extensión";
$text['label-required-dialplan_name']['es-mx'] = "Por favor indique: Nombre Extensión"; //copied from es-cl
$text['label-required-dialplan_name']['fr-ca'] = "Merci d'indiquer: Nom d'extension"; //copied from fr-fr
$text['label-required-dialplan_name']['fr-fr'] = "Merci d'indiquer: Nom d'extension";
$text['label-required-dialplan_name']['he-il'] = "";
$text['label-required-dialplan_name']['it-it'] = "Prego fornire: Nome Interno";
$text['label-required-dialplan_name']['nl-nl'] = "Geef aub.: Toestel naam";
$text['label-required-dialplan_name']['pl-pl'] = "Wprowadź: Nazwę numeru wewnętrznego";
$text['label-required-dialplan_name']['pt-br'] = "Por favor indique: Nome do Ramal"; //copied from pt-pt
$text['label-required-dialplan_name']['pt-pt'] = "Por favor indique: Nome da Extensão";
$text['label-required-dialplan_name']['ro-ro'] = "";
$text['label-required-dialplan_name']['ru-ru'] = "Пожалуйста укажите: Имя Внутреннего Номера";
$text['label-required-dialplan_name']['sv-se'] = "Var god ange: Anknytning Namn";
$text['label-required-dialplan_name']['uk-ua'] = "Будь ласка, надайте назву розширення";

$text['label-required-condition_field_1']['en-us'] = "Please provide: Condition Field";
$text['label-required-condition_field_1']['en-gb'] = "Please provide: Condition Field";
$text['label-required-condition_field_1']['ar-eg'] = "";
$text['label-required-condition_field_1']['de-at'] = "Bitte angeben: Feld für Bedingung"; //copied from de-de
$text['label-required-condition_field_1']['de-ch'] = "Bitte angeben: Feld für Bedingung"; //copied from de-de
$text['label-required-condition_field_1']['de-de'] = "Bitte angeben: Feld für Bedingung";
$text['label-required-condition_field_1']['es-cl'] = "Por favor indique: Campo de Condición";
$text['label-required-condition_field_1']['es-mx'] = "Por favor indique: Campo de Condición"; //copied from es-cl
$text['label-required-condition_field_1']['fr-ca'] = "Merci d'indiquer: Champs Condition"; //copied from fr-fr
$text['label-required-condition_field_1']['fr-fr'] = "Merci d'indiquer: Champs Condition";
$text['label-required-condition_field_1']['he-il'] = "";
$text['label-required-condition_field_1']['it-it'] = "Prego fornire: Condizione";
$text['label-required-condition_field_1']['nl-nl'] = "Geef aub.: Voorwaarde veld";
$text['label-required-condition_field_1']['pl-pl'] = "Wprowadź: pole warunku";
$text['label-required-condition_field_1']['pt-br'] = "Por favor indique: Condição"; //copied from pt-pt
$text['label-required-condition_field_1']['pt-pt'] = "Por favor indique: Condição";
$text['label-required-condition_field_1']['ro-ro'] = "";
$text['label-required-condition_field_1']['ru-ru'] = "Пожалуйста укажите: Условия участия";
$text['label-required-condition_field_1']['sv-se'] = "Var god ange:  Villkor Fält";
$text['label-required-condition_field_1']['uk-ua'] = "Будь ласка, надайте поле умови";

$text['label-required-condition_expression_1']['en-us'] = "Please provide: Condition Expression";
$text['label-required-condition_expression_1']['en-gb'] = "Please provide: Condition Expression";
$text['label-required-condition_expression_1']['ar-eg'] = "";
$text['label-required-condition_expression_1']['de-at'] = "Bitte angeben: Ausdruck für Bedingung"; //copied from de-de
$text['label-required-condition_expression_1']['de-ch'] = "Bitte angeben: Ausdruck für Bedingung"; //copied from de-de
$text['label-required-condition_expression_1']['de-de'] = "Bitte angeben: Ausdruck für Bedingung";
$text['label-required-condition_expression_1']['es-cl'] = "Por favor indique: Expresión de Condición";
$text['label-required-condition_expression_1']['es-mx'] = "Por favor indique: Expresión de Condición"; //copied from es-cl
$text['label-required-condition_expression_1']['fr-ca'] = "Merci d'indiquer: Expression Condition"; //copied from fr-fr
$text['label-required-condition_expression_1']['fr-fr'] = "Merci d'indiquer: Expression Condition";
$text['label-required-condition_expression_1']['he-il'] = "";
$text['label-required-condition_expression_1']['it-it'] = "Prego fornire: Espressione Condizione";
$text['label-required-condition_expression_1']['nl-nl'] = "Geef aub.: voorwaardelijke uitdrukking";
$text['label-required-condition_expression_1']['pl-pl'] = "Wprowadź: warunek wyrażenia";
$text['label-required-condition_expression_1']['pt-br'] = "Por favor indique: Expressão para Condição"; //copied from pt-pt
$text['label-required-condition_expression_1']['pt-pt'] = "Por favor indique: Expressão para Condição";
$text['label-required-condition_expression_1']['ro-ro'] = "";
$text['label-required-condition_expression_1']['ru-ru'] = "Пожалуйста укажите: выражение условия";
$text['label-required-condition_expression_1']['sv-se'] = "Var god ange: Villkor Uttryck";
$text['label-required-condition_expression_1']['uk-ua'] = "Будь ласка, надайте  вираз умови";

$text['label-required-action_application_1']['en-us'] = "Please provide: Action Application";
$text['label-required-action_application_1']['en-gb'] = "Please provide: Action Application";
$text['label-required-action_application_1']['ar-eg'] = "";
$text['label-required-action_application_1']['de-at'] = "Bitte angeben: Anwendung für Aktion"; //copied from de-de
$text['label-required-action_application_1']['de-ch'] = "Bitte angeben: Anwendung für Aktion"; //copied from de-de
$text['label-required-action_application_1']['de-de'] = "Bitte angeben: Anwendung für Aktion";
$text['label-required-action_application_1']['es-cl'] = "Por favor indique: Aplicación de Acción";
$text['label-required-action_application_1']['es-mx'] = "Por favor indique: Aplicación de Acción"; //copied from es-cl
$text['label-required-action_application_1']['fr-ca'] = "Merci d'indiquer: Application Action"; //copied from fr-fr
$text['label-required-action_application_1']['fr-fr'] = "Merci d'indiquer: Application Action";
$text['label-required-action_application_1']['he-il'] = "";
$text['label-required-action_application_1']['it-it'] = "Prego fornire: Applicazione";
$text['label-required-action_application_1']['nl-nl'] = "Geef aub.: Aktie applicatie";
$text['label-required-action_application_1']['pl-pl'] = "Wprowadź:aplikację operacji";
$text['label-required-action_application_1']['pt-br'] = "Por favor indique: Ação para Aplicação"; //copied from pt-pt
$text['label-required-action_application_1']['pt-pt'] = "Por favor indique: Acção para Aplicação";
$text['label-required-action_application_1']['ro-ro'] = "";
$text['label-required-action_application_1']['ru-ru'] = "Пожалуйста укажите: Применение приложения";
$text['label-required-action_application_1']['sv-se'] = "Var god ange:  Action Applikation";
$text['label-required-action_application_1']['uk-ua'] = "Будь ласка, надайте додаток для дії";

$text['label-caller-id-number-prefix']['en-us'] = "Caller ID Number Prefix";
$text['label-caller-id-number-prefix']['en-gb'] = "Caller ID Number Prefix";
$text['label-caller-id-number-prefix']['ar-eg'] = "";
$text['label-caller-id-number-prefix']['de-at'] = "Präfix für Anruferkennung"; //copied from de-de
$text['label-caller-id-number-prefix']['de-ch'] = "Präfix für Anruferkennung"; //copied from de-de
$text['label-caller-id-number-prefix']['de-de'] = "Präfix für Anruferkennung";
$text['label-caller-id-number-prefix']['es-cl'] = "Redial prefijo de salida";
$text['label-caller-id-number-prefix']['es-mx'] = "Redial prefijo de salida"; //copied from es-cl
$text['label-caller-id-number-prefix']['fr-ca'] = "Préfixe d'identification de l'appelant"; //copied from fr-fr
$text['label-caller-id-number-prefix']['fr-fr'] = "Préfixe d'identification de l'appelant";
$text['label-caller-id-number-prefix']['he-il'] = "";
$text['label-caller-id-number-prefix']['it-it'] = "Prefisso Numero Chiamante";
$text['label-caller-id-number-prefix']['nl-nl'] = "CID Nummer voorloop";
$text['label-caller-id-number-prefix']['pl-pl'] = "Prefiks ponownego wybierania";
$text['label-caller-id-number-prefix']['pt-br'] = "Prefixo do número de ID do chamador"; //copied from pt-pt
$text['label-caller-id-number-prefix']['pt-pt'] = "Remarcar prefixo de saída";
$text['label-caller-id-number-prefix']['ro-ro'] = "";
$text['label-caller-id-number-prefix']['ru-ru'] = "Префикс номера (Caller ID) вызывающего абонента";
$text['label-caller-id-number-prefix']['sv-se'] = "Caller ID Nummer Prefix";
$text['label-caller-id-number-prefix']['uk-ua'] = "Префікс для повторного набору вихідного дзвінка";

$text['label-limit']['en-us'] = "Limit";
$text['label-limit']['en-gb'] = "Limit";
$text['label-limit']['ar-eg'] = "";
$text['label-limit']['de-at'] = "Obergrenze"; //copied from de-de
$text['label-limit']['de-ch'] = "Obergrenze"; //copied from de-de
$text['label-limit']['de-de'] = "Obergrenze";
$text['label-limit']['es-cl'] = "Límite";
$text['label-limit']['es-mx'] = "Límite"; //copied from es-cl
$text['label-limit']['fr-ca'] = "Limite"; //copied from fr-fr
$text['label-limit']['fr-fr'] = "Limite";
$text['label-limit']['he-il'] = "";
$text['label-limit']['it-it'] = "Limite";
$text['label-limit']['nl-nl'] = "Limiet";
$text['label-limit']['pl-pl'] = "Limit";
$text['label-limit']['pt-br'] = "Limite"; //copied from pt-pt
$text['label-limit']['pt-pt'] = "Limite";
$text['label-limit']['ro-ro'] = "";
$text['label-limit']['ru-ru'] = "Лимит";
$text['label-limit']['sv-se'] = "Begränsning";
$text['label-limit']['uk-ua'] = "Обмеження";

$text['label-field']['en-us'] = "Field";
$text['label-field']['en-gb'] = "Field";
$text['label-field']['ar-eg'] = "";
$text['label-field']['de-at'] = "Feld"; //copied from de-de
$text['label-field']['de-ch'] = "Feld"; //copied from de-de
$text['label-field']['de-de'] = "Feld";
$text['label-field']['es-cl'] = "Campo";
$text['label-field']['es-mx'] = "Campo"; //copied from es-cl
$text['label-field']['fr-ca'] = "Champs"; //copied from fr-fr
$text['label-field']['fr-fr'] = "Champs";
$text['label-field']['he-il'] = "";
$text['label-field']['it-it'] = "Campo";
$text['label-field']['nl-nl'] = "Veld";
$text['label-field']['pl-pl'] = "Pole";
$text['label-field']['pt-br'] = "Campo"; //copied from pt-pt
$text['label-field']['pt-pt'] = "Campo";
$text['label-field']['ro-ro'] = "";
$text['label-field']['ru-ru'] = "Поле";
$text['label-field']['sv-se'] = "Fält";
$text['label-field']['uk-ua'] = "Поле";

$text['label-expression']['en-us'] = "Expression";
$text['label-expression']['en-gb'] = "Expression";
$text['label-expression']['ar-eg'] = "";
$text['label-expression']['de-at'] = "Ausdruck"; //copied from de-de
$text['label-expression']['de-ch'] = "Ausdruck"; //copied from de-de
$text['label-expression']['de-de'] = "Ausdruck";
$text['label-expression']['es-cl'] = "Expresión";
$text['label-expression']['es-mx'] = "Expresión"; //copied from es-cl
$text['label-expression']['fr-ca'] = "Expression"; //copied from fr-fr
$text['label-expression']['fr-fr'] = "Expression";
$text['label-expression']['he-il'] = "";
$text['label-expression']['it-it'] = "Espressione";
$text['label-expression']['nl-nl'] = "Uitdrukking";
$text['label-expression']['pl-pl'] = "Wyrażenie";
$text['label-expression']['pt-br'] = "Expressão"; //copied from pt-pt
$text['label-expression']['pt-pt'] = "Expressão";
$text['label-expression']['ro-ro'] = "";
$text['label-expression']['ru-ru'] = "Выражение";
$text['label-expression']['sv-se'] = "Uttryck";
$text['label-expression']['uk-ua'] = "Вираз";

$text['label-destination-number']['en-us'] = "Destination Number";
$text['label-destination-number']['en-gb'] = "Destination Number";
$text['label-destination-number']['ar-eg'] = "";
$text['label-destination-number']['de-at'] = "Zielrufnummer"; //copied from de-de
$text['label-destination-number']['de-ch'] = "Zielrufnummer"; //copied from de-de
$text['label-destination-number']['de-de'] = "Zielrufnummer";
$text['label-destination-number']['es-cl'] = "Número de destino";
$text['label-destination-number']['es-mx'] = "Número de destino"; //copied from es-cl
$text['label-destination-number']['fr-ca'] = "Numéro de Destination"; //copied from fr-fr
$text['label-destination-number']['fr-fr'] = "Numéro de Destination";
$text['label-destination-number']['he-il'] = "";
$text['label-destination-number']['it-it'] = "Numero Destinazione";
$text['label-destination-number']['nl-nl'] = "Bestemmingsnummer";
$text['label-destination-number']['pl-pl'] = "Numer destynacji";
$text['label-destination-number']['pt-br'] = "Número de Destino"; //copied from pt-pt
$text['label-destination-number']['pt-pt'] = "Número de Destino";
$text['label-destination-number']['ro-ro'] = "";
$text['label-destination-number']['ru-ru'] = "Целевой номер";
$text['label-destination-number']['sv-se'] = "Destination Nummer";
$text['label-destination-number']['uk-ua'] = "Номер";

$text['label-condition_2']['en-us'] = "Condition 2";
$text['label-condition_2']['en-gb'] = "Condition 2";
$text['label-condition_2']['ar-eg'] = "";
$text['label-condition_2']['de-at'] = "Bedingung 2"; //copied from de-de
$text['label-condition_2']['de-ch'] = "Bedingung 2"; //copied from de-de
$text['label-condition_2']['de-de'] = "Bedingung 2";
$text['label-condition_2']['es-cl'] = "Condición 2";
$text['label-condition_2']['es-mx'] = "Condición 2"; //copied from es-cl
$text['label-condition_2']['fr-ca'] = "Condition 2"; //copied from fr-fr
$text['label-condition_2']['fr-fr'] = "Condition 2";
$text['label-condition_2']['he-il'] = "";
$text['label-condition_2']['it-it'] = "Condizione 2";
$text['label-condition_2']['nl-nl'] = "Voorwaarde 2";
$text['label-condition_2']['pl-pl'] = "Warunek 2";
$text['label-condition_2']['pt-br'] = "Condição 2"; //copied from pt-pt
$text['label-condition_2']['pt-pt'] = "Condição 2";
$text['label-condition_2']['ro-ro'] = "";
$text['label-condition_2']['ru-ru'] = "Условие 2";
$text['label-condition_2']['sv-se'] = "Villkor 2";
$text['label-condition_2']['uk-ua'] = "Умова 2";

$text['label-condition_1']['en-us'] = "Condition 1";
$text['label-condition_1']['en-gb'] = "Condition 1";
$text['label-condition_1']['ar-eg'] = "";
$text['label-condition_1']['de-at'] = "Bedingung 1"; //copied from de-de
$text['label-condition_1']['de-ch'] = "Bedingung 1"; //copied from de-de
$text['label-condition_1']['de-de'] = "Bedingung 1";
$text['label-condition_1']['es-cl'] = "Condición 1";
$text['label-condition_1']['es-mx'] = "Condición 1"; //copied from es-cl
$text['label-condition_1']['fr-ca'] = "Condition 1"; //copied from fr-fr
$text['label-condition_1']['fr-fr'] = "Condition 1";
$text['label-condition_1']['he-il'] = "";
$text['label-condition_1']['it-it'] = "Condizione 1";
$text['label-condition_1']['nl-nl'] = "Voorwaarde 2";
$text['label-condition_1']['pl-pl'] = "Warunek 1";
$text['label-condition_1']['pt-br'] = "Condição 1"; //copied from pt-pt
$text['label-condition_1']['pt-pt'] = "Condição 1";
$text['label-condition_1']['ro-ro'] = "";
$text['label-condition_1']['ru-ru'] = "Условие 1";
$text['label-condition_1']['sv-se'] = "Villkor 1";
$text['label-condition_1']['uk-ua'] = "Умова 1";

$text['label-action_2']['en-us'] = "Action 2";
$text['label-action_2']['en-gb'] = "Action 2";
$text['label-action_2']['ar-eg'] = "";
$text['label-action_2']['de-at'] = "Aktion 2"; //copied from de-de
$text['label-action_2']['de-ch'] = "Aktion 2"; //copied from de-de
$text['label-action_2']['de-de'] = "Aktion 2";
$text['label-action_2']['es-cl'] = "Acción 2";
$text['label-action_2']['es-mx'] = "Acción 2"; //copied from es-cl
$text['label-action_2']['fr-ca'] = "Action 2"; //copied from fr-fr
$text['label-action_2']['fr-fr'] = "Action 2";
$text['label-action_2']['he-il'] = "";
$text['label-action_2']['it-it'] = "Azione 2";
$text['label-action_2']['nl-nl'] = "Aktie 2";
$text['label-action_2']['pl-pl'] = "Operacja 2";
$text['label-action_2']['pt-br'] = "Ação 2"; //copied from pt-pt
$text['label-action_2']['pt-pt'] = "Acção 2";
$text['label-action_2']['ro-ro'] = "";
$text['label-action_2']['ru-ru'] = "Действие 2";
$text['label-action_2']['sv-se'] = "Action 2";
$text['label-action_2']['uk-ua'] = "Дія 2";

$text['label-action_1']['en-us'] = "Action 1";
$text['label-action_1']['en-gb'] = "Action 1";
$text['label-action_1']['ar-eg'] = "";
$text['label-action_1']['de-at'] = "Aktion 1"; //copied from de-de
$text['label-action_1']['de-ch'] = "Aktion 1"; //copied from de-de
$text['label-action_1']['de-de'] = "Aktion 1";
$text['label-action_1']['es-cl'] = "Acción 1";
$text['label-action_1']['es-mx'] = "Acción 1"; //copied from es-cl
$text['label-action_1']['fr-ca'] = "Action 1"; //copied from fr-fr
$text['label-action_1']['fr-fr'] = "Action 1";
$text['label-action_1']['he-il'] = "";
$text['label-action_1']['it-it'] = "Azione 1";
$text['label-action_1']['nl-nl'] = "Aktie 1";
$text['label-action_1']['pl-pl'] = "Operacja 1";
$text['label-action_1']['pt-br'] = "Ação 1"; //copied from pt-pt
$text['label-action_1']['pt-pt'] = "Acção 1";
$text['label-action_1']['ro-ro'] = "";
$text['label-action_1']['ru-ru'] = "Действие 1";
$text['label-action_1']['sv-se'] = "Action 1";
$text['label-action_1']['uk-ua'] = "Дія 1";

$text['label-action']['en-us'] = "Action";
$text['label-action']['en-gb'] = "Action";
$text['label-action']['ar-eg'] = "";
$text['label-action']['de-at'] = "Aktion"; //copied from de-de
$text['label-action']['de-ch'] = "Aktion"; //copied from de-de
$text['label-action']['de-de'] = "Aktion";
$text['label-action']['es-cl'] = "Acción";
$text['label-action']['es-mx'] = "Acción"; //copied from es-cl
$text['label-action']['fr-ca'] = "Action"; //copied from fr-fr
$text['label-action']['fr-fr'] = "Action";
$text['label-action']['he-il'] = "";
$text['label-action']['it-it'] = "Azione";
$text['label-action']['nl-nl'] = "Aktie";
$text['label-action']['pl-pl'] = "Operacja (gdzie przesłać rozmowę).";
$text['label-action']['pt-br'] = "Ação"; //copied from pt-pt
$text['label-action']['pt-pt'] = "Acção";
$text['label-action']['ro-ro'] = "";
$text['label-action']['ru-ru'] = "Действие";
$text['label-action']['sv-se'] = "Action";
$text['label-action']['uk-ua'] = "Дія";

$text['label-access-denied']['en-us'] = "access denied";
$text['label-access-denied']['en-gb'] = "access denied";
$text['label-access-denied']['ar-eg'] = "";
$text['label-access-denied']['de-at'] = "Zugriff verweigert"; //copied from de-de
$text['label-access-denied']['de-ch'] = "Zugriff verweigert"; //copied from de-de
$text['label-access-denied']['de-de'] = "Zugriff verweigert";
$text['label-access-denied']['es-cl'] = "acceso denegado";
$text['label-access-denied']['es-mx'] = "acceso denegado"; //copied from es-cl
$text['label-access-denied']['fr-ca'] = "accès refusé"; //copied from fr-fr
$text['label-access-denied']['fr-fr'] = "accès refusé";
$text['label-access-denied']['he-il'] = "";
$text['label-access-denied']['it-it'] = "Accesso Negato";
$text['label-access-denied']['nl-nl'] = "toegang geweigerd";
$text['label-access-denied']['pl-pl'] = "brak dostępu";
$text['label-access-denied']['pt-br'] = "acesso negado"; //copied from pt-pt
$text['label-access-denied']['pt-pt'] = "acesso negado";
$text['label-access-denied']['ro-ro'] = "";
$text['label-access-denied']['ru-ru'] = "доступ закрыт";
$text['label-access-denied']['sv-se'] = "tillträde beviljas ej";
$text['label-access-denied']['uk-ua'] = "в доступі відмовлено";

$text['description-caller-id-number-prefix']['en-us'] = "Set a prefix on the caller ID number.";
$text['description-caller-id-number-prefix']['en-gb'] = "Set a prefix on the caller ID number.";
$text['description-caller-id-number-prefix']['ar-eg'] = "";
$text['description-caller-id-number-prefix']['de-at'] = "Präfix für Anruferkennung (Nummer) setzen."; //copied from de-de
$text['description-caller-id-number-prefix']['de-ch'] = "Präfix für Anruferkennung (Nummer) setzen."; //copied from de-de
$text['description-caller-id-number-prefix']['de-de'] = "Präfix für Anruferkennung (Nummer) setzen.";
$text['description-caller-id-number-prefix']['es-cl'] = "";
$text['description-caller-id-number-prefix']['es-mx'] = "";
$text['description-caller-id-number-prefix']['fr-ca'] = "Définissez un préfixe sur le numéro d'identification de l'appelant.";
$text['description-caller-id-number-prefix']['fr-fr'] = "Définissez un préfixe sur le numéro d'identification de l'appelant.";
$text['description-caller-id-number-prefix']['he-il'] = "";
$text['description-caller-id-number-prefix']['it-it'] = "Imposta un prefisso per il numero chiamante.";
$text['description-caller-id-number-prefix']['nl-nl'] = "Stel de voorloop op een CID nummer";
$text['description-caller-id-number-prefix']['pl-pl'] = "";
$text['description-caller-id-number-prefix']['pt-br'] = "Define um prefixo para o número ID do chamador.";
$text['description-caller-id-number-prefix']['pt-pt'] = "";
$text['description-caller-id-number-prefix']['ro-ro'] = "";
$text['description-caller-id-number-prefix']['ru-ru'] = "Задайте префикс идентификатора (caller ID) вызывающего абонента.";
$text['description-caller-id-number-prefix']['sv-se'] = "Ange ett prefix för caller iID nummer.";
$text['description-caller-id-number-prefix']['uk-ua'] = "";

$text['description-name']['en-us'] = "Please enter an inbound route name.";
$text['description-name']['en-gb'] = "Please enter an inbound route name.";
$text['description-name']['ar-eg'] = "";
$text['description-name']['de-at'] = "Bitte geben Sie einen Namen für die eingehende Route an."; //copied from de-de
$text['description-name']['de-ch'] = "Bitte geben Sie einen Namen für die eingehende Route an."; //copied from de-de
$text['description-name']['de-de'] = "Bitte geben Sie einen Namen für die eingehende Route an.";
$text['description-name']['es-cl'] = "Por favor infrese un nombre de ruta entrante.";
$text['description-name']['es-mx'] = "Por favor infrese un nombre de ruta entrante."; //copied from es-cl
$text['description-name']['fr-ca'] = "Merci d'entrer le nom d'une route entrante"; //copied from fr-fr
$text['description-name']['fr-fr'] = "Merci d'entrer le nom d'une route entrante";
$text['description-name']['he-il'] = "";
$text['description-name']['it-it'] = "Prego inserire un nome per la rotta d'ingresso.";
$text['description-name']['nl-nl'] = "Geef aub.: inkomende routenaam";
$text['description-name']['pl-pl'] = "Wprowadź nazwę";
$text['description-name']['pt-br'] = "Por favor insira um nome para a rota de entrada."; //copied from pt-pt
$text['description-name']['pt-pt'] = "Por favor introduza um nome para a rota de entrada.";
$text['description-name']['ro-ro'] = "";
$text['description-name']['ru-ru'] = "Введите название входящего маршрута.";
$text['description-name']['sv-se'] = "Var god ange ett namn för inkommande route.";
$text['description-name']['uk-ua'] = "Введіть назву меню";

$text['description-dialplan-inbound-add']['en-us'] = "The public dialplan is used to route incoming calls to destinations based on one or more conditions and context. It can send incoming calls to an auto attendant, huntgroup, extension, external number, or a script.";
$text['description-dialplan-inbound-add']['en-gb'] = "The public dialplan is used to route incoming calls to destinations based on one or more conditions and context. It can send incoming calls to an auto attendant, huntgroup, extension, external number, or a script.";
$text['description-dialplan-inbound-add']['ar-eg'] = "";
$text['description-dialplan-inbound-add']['de-at'] = "Der öffentliche Wählplan wird verwendet, um eingehende Anrufe anhand von einem oder mehrere Bedingungen an bestimmte Ziele weiter zu leiten."; //copied from de-de
$text['description-dialplan-inbound-add']['de-ch'] = "Der öffentliche Wählplan wird verwendet, um eingehende Anrufe anhand von einem oder mehrere Bedingungen an bestimmte Ziele weiter zu leiten."; //copied from de-de
$text['description-dialplan-inbound-add']['de-de'] = "Der öffentliche Wählplan wird verwendet, um eingehende Anrufe anhand von einem oder mehrere Bedingungen an bestimmte Ziele weiter zu leiten.";
$text['description-dialplan-inbound-add']['es-cl'] = "El plan de marcado público es usado para dirigir llamadas entrantes a destinos basados en una o más condiciones y contexto. Puede enviar llamadas entrantes a un IVR, grupo, extensión, número externo o un script";
$text['description-dialplan-inbound-add']['es-mx'] = "El plan de marcado público es usado para dirigir llamadas entrantes a destinos basados en una o más condiciones y contexto. Puede enviar llamadas entrantes a un IVR, grupo, extensión, número externo o un script"; //copied from es-cl
$text['description-dialplan-inbound-add']['fr-ca'] = "Le plan de numérotation public est utilisé pour acheminer les appels aux destinations en se basant sur une ou plusieurs conditions ou contextes. Les appels peuvent être acheminé au opératrices auto, groupements, extensions, numéro externe ou script."; //copied from fr-fr
$text['description-dialplan-inbound-add']['fr-fr'] = "Le plan de numérotation public est utilisé pour acheminer les appels aux destinations en se basant sur une ou plusieurs conditions ou contextes. Les appels peuvent être acheminé au opératrices auto, groupements, extensions, numéro externe ou script.";
$text['description-dialplan-inbound-add']['he-il'] = "";
$text['description-dialplan-inbound-add']['it-it'] = "Il Piano Numerazioni è usato per configurare le destinazioni di chiamata basate su condizioni e contesti. Puoi usarlo per mandare le chiamate verso gateways, risponditori, numeri esterni, scripts o qualsia altra destinazione. ";
$text['description-dialplan-inbound-add']['nl-nl'] = "Het openbare belplan wordt gebruikt om ikomende oproepen naar bestemmingen te leiden gebaseerd op een of meer voorwaarden en context. Het kan oproepen doorsturen naar automatisch antwoord apparaat, toestel, extern nummer, zoekgroep of een script.";
$text['description-dialplan-inbound-add']['pl-pl'] = "Dialplan publiczny jest używany do przesyłania polaczeń przychodzących do miejsc  przeznaczenia na podstawie jednego lub kilku warunków i kontekstu. Można je wysyłać do Zapowiedzi Głosowych (IVR), grup telefonów, numerów wewnętrznych/zewnętrznych lub skryptu.";
$text['description-dialplan-inbound-add']['pt-br'] = "O dialplan público é usado para encaminhar chamadas de entrada para destinos baseados em uma ou mais condições e contexto. As chamadas de entrada podem ser enviadas para um atendimento automático, um grupo de ramais, um ramal, um número externo, ou um script."; //copied from pt-pt
$text['description-dialplan-inbound-add']['pt-pt'] = "O dialplan público é usado para encaminhar chamadas de entrada para destinos baseados em uma ou mais condições. As chamadas de entrada podem ser enviadas para um atendimento automático, um huntgroup, uma extensão, um número externo, ou um script.";
$text['description-dialplan-inbound-add']['ro-ro'] = "";
$text['description-dialplan-inbound-add']['ru-ru'] = "Общедоступный План Нумерации используется для маршрутизации входящих вызовов в пункты назначения на основе одного или нескольких условий и контекста. Он может отправлять входящие вызовы автосекретарю, группе поиска, внутреннему номеру, внешнему номеру или сценарию";
$text['description-dialplan-inbound-add']['sv-se'] = "";
$text['description-dialplan-inbound-add']['uk-ua'] = "Маршрутизація спрямовує вхідні дзвінки в напрямку відповідно до умов і контексту. Можна спрямувати вхідні виклики на групи, автоматичне обслуговування, зовнішні номери, сценарії або інші напрямки. ";

$text['confirm-update-complete']['en-us'] = "Update Complete";
$text['confirm-update-complete']['en-gb'] = "Update Complete";
$text['confirm-update-complete']['ar-eg'] = "";
$text['confirm-update-complete']['de-at'] = "Aktualisierung abgeschlossen"; //copied from de-de
$text['confirm-update-complete']['de-ch'] = "Aktualisierung abgeschlossen"; //copied from de-de
$text['confirm-update-complete']['de-de'] = "Aktualisierung abgeschlossen";
$text['confirm-update-complete']['es-cl'] = "Actualización Completa";
$text['confirm-update-complete']['es-mx'] = "Actualización Completa"; //copied from es-cl
$text['confirm-update-complete']['fr-ca'] = "Mis à jour"; //copied from fr-fr
$text['confirm-update-complete']['fr-fr'] = "Mis à jour";
$text['confirm-update-complete']['he-il'] = "";
$text['confirm-update-complete']['it-it'] = "Aggiornamento Completato.";
$text['confirm-update-complete']['nl-nl'] = "Bijwerken gereed";
$text['confirm-update-complete']['pl-pl'] = "Zaktualizowano pomyślnie";
$text['confirm-update-complete']['pt-br'] = "Atualização Completa"; //copied from pt-pt
$text['confirm-update-complete']['pt-pt'] = "Actualização Efectuada";
$text['confirm-update-complete']['ro-ro'] = "";
$text['confirm-update-complete']['ru-ru'] = "Обновление завершено";
$text['confirm-update-complete']['sv-se'] = "Ändring Utförd";
$text['confirm-update-complete']['uk-ua'] = "Оновлення завершено";

?>
