<?php
	
	//application details
		$apps[$x]['name'] = "Wizard";
		$apps[$x]['uuid'] = "cfb04b51-452a-4ece-803e-bb43a2918141";
		$apps[$x]['category'] = "Accounts";
		$apps[$x]['subcategory'] = "";
		$apps[$x]['version'] = "";
		$apps[$x]['license'] = "Mozilla Public License 1.1";
		$apps[$x]['url'] = "http://www.fusionpbx.com";
		$apps[$x]['description']['en-us'] = "Wizard";

	//permission details

		$y = 0;
		$apps[$x]['permissions'][$y]['name'] = "wizard_add";
		$apps[$x]['permissions'][$y]['menu']['uuid'] = "a5baed2c-cebd-4539-910c-9c65e3fc26b0";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "wizard_import";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "wizard_template_view";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;		
		$apps[$x]['permissions'][$y]['name'] = "wizard_template_add";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "wizard_template_delete";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "wizard_template_edit";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		
	//schema details
		$y = 1; //table array index
		$z = 0; //field array index
		$apps[$x]['db'][$y]['table'] = "v_wizard_templates";
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_domains";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "domain_uuid";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "wizard_template_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
		$z++;
		$apps[$x]['db'][$y]['table'] = "v_wizard_templates";
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "wizard_group_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_groups";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "group_uuid";
		$z++;		
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "wizard_template_name";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "outbound_caller_id_number";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en'] = "";
		$z++;		
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "emergency_caller_id_number";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "call_group";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "toll_allow";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "hold_music";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "user_record";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "call_timeout";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "forward_user_not_registered_destination";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "forward_user_not_registered_enabled";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "time_zone";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "description";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en'] = "";
		$z++;	
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "forward_busy_destination";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "forward_busy_enabled";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "forward_no_answer_destination";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "forward_no_answer_enabled";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en'] = "";
		$z++;		
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "directory_visible";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en'] = "";
		$z++;		
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "directory_exten_visible";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en'] = "";
		$z++;			
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "limit_max";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en'] = "";
		$z++;
?>