<?php
#This file was last reorganized on 19th of September 2017 08:54:24 AM UTC

$text['title-call-block']['en-us'] = "Call Block";
$text['title-call-block']['ar-eg'] = "حظر المكالمات";
$text['title-call-block']['de-at'] = "Sperrlisten"; //copied from de-de
$text['title-call-block']['de-ch'] = "Sperrlisten"; //copied from de-de
$text['title-call-block']['de-de'] = "Sperrlisten";
$text['title-call-block']['es-cl'] = "Bloqueo de llamadas";
$text['title-call-block']['es-mx'] = "Bloqueo de llamadas"; //copied from es-cl
$text['title-call-block']['fr-ca'] = "Liste noire"; //copied from fr-fr
$text['title-call-block']['fr-fr'] = "Liste noire";
$text['title-call-block']['he-il'] = "חסימת מספר";
$text['title-call-block']['it-it'] = "Blocco Chiamate";
$text['title-call-block']['nl-nl'] = "";
$text['title-call-block']['pl-pl'] = "Blokowanie rozmów";
$text['title-call-block']['pt-br'] = "Bloqueio de chamadas";
$text['title-call-block']['pt-pt'] = "Bloqueio de Chamadas";
$text['title-call-block']['ro-ro'] = "Blocare apel";
$text['title-call-block']['ru-ru'] = "Черный список";
$text['title-call-block']['sv-se'] = "Blockera Samtal";
$text['title-call-block']['uk-ua'] = "Блокування дзвінків";

$text['prompt-block_recent_name']['en-us'] = "Block Recent Call - Edit the Name, if desired...";
$text['prompt-block_recent_name']['ar-eg'] = "";
$text['prompt-block_recent_name']['de-at'] = "Kürzliche Anrufe Blockieren - Bearbeiten Sie den Namen, falls gewünscht..."; //copied from de-de
$text['prompt-block_recent_name']['de-ch'] = "Kürzliche Anrufe Blockieren - Bearbeiten Sie den Namen, falls gewünscht..."; //copied from de-de
$text['prompt-block_recent_name']['de-de'] = "Kürzliche Anrufe Blockieren - Bearbeiten Sie den Namen, falls gewünscht...";
$text['prompt-block_recent_name']['es-cl'] = "Bloqueo de llamadas recientes - Edite el nombre, si lo desea...";
$text['prompt-block_recent_name']['es-mx'] = "Bloqueo de llamadas recientes - Edite el nombre, si lo desea..."; //copied from es-cl
$text['prompt-block_recent_name']['fr-ca'] = "Bloquer appels récents - Modifiez le nom, si vous le souhaitez..."; //copied from fr-fr
$text['prompt-block_recent_name']['fr-fr'] = "Bloquer appels récents - Modifiez le nom, si vous le souhaitez...";
$text['prompt-block_recent_name']['he-il'] = "";
$text['prompt-block_recent_name']['it-it'] = "Blocca le chiamate recenti - Inserire il Nome, se desiderato...";
$text['prompt-block_recent_name']['nl-nl'] = "";
$text['prompt-block_recent_name']['pl-pl'] = "Zablokuj ostatnią rozmowę. Edytuj nazwę";
$text['prompt-block_recent_name']['pt-br'] = "Bloquear chamadas recentes, edite o nome se assim desejar...";
$text['prompt-block_recent_name']['pt-pt'] = "Bloquear Chamadas Recentes - Edite o nome, se desejar...";
$text['prompt-block_recent_name']['ro-ro'] = "Blocare apel recent - Editați  numele dacă doriți";
$text['prompt-block_recent_name']['ru-ru'] = "Блокировать недавний вызов. Отредактируйте название, если необходимо...";
$text['prompt-block_recent_name']['sv-se'] = "Blockera Senaste Samtal, editera namnet om nödvändigt...";
$text['prompt-block_recent_name']['uk-ua'] = "Блокувати недавній дзвінок. Відредагуйте назву за бажанням";

$text['label-update-complete']['en-us'] = "Update Complete";
$text['label-update-complete']['ar-eg'] = "اكتمال التحديث";
$text['label-update-complete']['de-at'] = "Aktualisierung abgeschlossen"; //copied from de-de
$text['label-update-complete']['de-ch'] = "Aktualisierung abgeschlossen"; //copied from de-de
$text['label-update-complete']['de-de'] = "Aktualisierung abgeschlossen";
$text['label-update-complete']['es-cl'] = "Actualización Completa";
$text['label-update-complete']['es-mx'] = "Actualización Completa"; //copied from es-cl
$text['label-update-complete']['fr-ca'] = "Mise à jour effectuée"; //copied from fr-fr
$text['label-update-complete']['fr-fr'] = "Mise à jour effectuée";
$text['label-update-complete']['he-il'] = "העדכון הושלם";
$text['label-update-complete']['it-it'] = "Aggiornamento Completato";
$text['label-update-complete']['nl-nl'] = "";
$text['label-update-complete']['pl-pl'] = "Zaktualizowano poprawnie";
$text['label-update-complete']['pt-br'] = "Atualização Completa";
$text['label-update-complete']['pt-pt'] = "Actualização Efectuada";
$text['label-update-complete']['ro-ro'] = "Actualizare completă";
$text['label-update-complete']['ru-ru'] = "Обновление завершено";
$text['label-update-complete']['sv-se'] = "Uppdatering Klar";
$text['label-update-complete']['uk-ua'] = "Оновлено";

$text['label-reject']['en-us'] = "Reject";
$text['label-reject']['ar-eg'] = "رفض";
$text['label-reject']['de-at'] = "Zurückweisen"; //copied from de-de
$text['label-reject']['de-ch'] = "Zurückweisen"; //copied from de-de
$text['label-reject']['de-de'] = "Zurückweisen";
$text['label-reject']['es-cl'] = "Rechazar";
$text['label-reject']['es-mx'] = "Rechazar"; //copied from es-cl
$text['label-reject']['fr-ca'] = "Rejeter"; //copied from fr-fr
$text['label-reject']['fr-fr'] = "Rejeter";
$text['label-reject']['he-il'] = "לדחות";
$text['label-reject']['it-it'] = "Blocca";
$text['label-reject']['nl-nl'] = "";
$text['label-reject']['pl-pl'] = "Odrzuć ";
$text['label-reject']['pt-br'] = "Rejeitar"; //copied from pt-pt
$text['label-reject']['pt-pt'] = "Rejeitar";
$text['label-reject']['ro-ro'] = "";
$text['label-reject']['ru-ru'] = "Отклонить";
$text['label-reject']['sv-se'] = "Neka";
$text['label-reject']['uk-ua'] = "Відхилити";

$text['label-provide-number']['en-us'] = "Please provide: Number";
$text['label-provide-number']['ar-eg'] = "من فضلك أدخل: الرقم";
$text['label-provide-number']['de-at'] = "Bitte geben Sie die Nummer an"; //copied from de-de
$text['label-provide-number']['de-ch'] = "Bitte geben Sie die Nummer an"; //copied from de-de
$text['label-provide-number']['de-de'] = "Bitte geben Sie die Nummer an";
$text['label-provide-number']['es-cl'] = "Por favor agregue: Número";
$text['label-provide-number']['es-mx'] = "Por favor agregue: Número"; //copied from es-cl
$text['label-provide-number']['fr-ca'] = "Merci d'indiquer: Numéro"; //copied from fr-fr
$text['label-provide-number']['fr-fr'] = "Merci d'indiquer: Numéro";
$text['label-provide-number']['he-il'] = "אנא הכנס מספר";
$text['label-provide-number']['it-it'] = "Prego fornire: Numero";
$text['label-provide-number']['nl-nl'] = "";
$text['label-provide-number']['pl-pl'] = " Wprowadź numer";
$text['label-provide-number']['pt-br'] = "Por favor indique: Número"; //copied from pt-pt
$text['label-provide-number']['pt-pt'] = "Por favor indique: Número";
$text['label-provide-number']['ro-ro'] = "";
$text['label-provide-number']['ru-ru'] = "Введите номер";
$text['label-provide-number']['sv-se'] = "Ange: Nummer";
$text['label-provide-number']['uk-ua'] = "Введіть номер";

$text['label-provide-name']['en-us'] = "Please provide: Name";
$text['label-provide-name']['ar-eg'] = "من فضلك أدخل: الأسم";
$text['label-provide-name']['de-at'] = "Bitte geben Sie den Namen an"; //copied from de-de
$text['label-provide-name']['de-ch'] = "Bitte geben Sie den Namen an"; //copied from de-de
$text['label-provide-name']['de-de'] = "Bitte geben Sie den Namen an";
$text['label-provide-name']['es-cl'] = "Por favor agregue: Nombre";
$text['label-provide-name']['es-mx'] = "Por favor agregue: Nombre"; //copied from es-cl
$text['label-provide-name']['fr-ca'] = "Merci d'indiquer: Nom"; //copied from fr-fr
$text['label-provide-name']['fr-fr'] = "Merci d'indiquer: Nom";
$text['label-provide-name']['he-il'] = "אנא הכנס שם";
$text['label-provide-name']['it-it'] = "Prego fornire: Nome";
$text['label-provide-name']['nl-nl'] = "";
$text['label-provide-name']['pl-pl'] = " Wprowadź nazwę ";
$text['label-provide-name']['pt-br'] = "Por favor indique: Nome"; //copied from pt-pt
$text['label-provide-name']['pt-pt'] = "Por favor indique: Nome";
$text['label-provide-name']['ro-ro'] = "";
$text['label-provide-name']['ru-ru'] = "Пожалуйста, введите: Имя";
$text['label-provide-name']['sv-se'] = "Ange: Namn";
$text['label-provide-name']['uk-ua'] = "Введіть назву";

$text['label-provide-enabled']['en-us'] = "Please provide: Enabled";
$text['label-provide-enabled']['ar-eg'] = "";
$text['label-provide-enabled']['de-at'] = "Bitte geben Sie folgendes an: Aktiv"; //copied from de-de
$text['label-provide-enabled']['de-ch'] = "Bitte geben Sie folgendes an: Aktiv"; //copied from de-de
$text['label-provide-enabled']['de-de'] = "Bitte geben Sie folgendes an: Aktiv";
$text['label-provide-enabled']['es-cl'] = "Por favor agregue: Activo";
$text['label-provide-enabled']['es-mx'] = "Por favor agregue: Activo"; //copied from es-cl
$text['label-provide-enabled']['fr-ca'] = "Merci d'indiquer: Actif"; //copied from fr-fr
$text['label-provide-enabled']['fr-fr'] = "Merci d'indiquer: Actif";
$text['label-provide-enabled']['he-il'] = "";
$text['label-provide-enabled']['it-it'] = "Prego fornire: Abilitazione";
$text['label-provide-enabled']['nl-nl'] = "";
$text['label-provide-enabled']['pl-pl'] = " Wprowadź: Włączony";
$text['label-provide-enabled']['pt-br'] = "Por favor indique se está habilitado";
$text['label-provide-enabled']['pt-pt'] = "Por favor indique: Activado";
$text['label-provide-enabled']['ro-ro'] = "";
$text['label-provide-enabled']['ru-ru'] = "Пожалуйста, введите: Включить";
$text['label-provide-enabled']['sv-se'] = "Ange: Aktiverad";
$text['label-provide-enabled']['uk-ua'] = "Включити/відключити";

$text['label-number']['en-us'] = "Number";
$text['label-number']['ar-eg'] = "رقم";
$text['label-number']['de-at'] = "Nummer"; //copied from de-de
$text['label-number']['de-ch'] = "Nummer"; //copied from de-de
$text['label-number']['de-de'] = "Nummer";
$text['label-number']['es-cl'] = "Número";
$text['label-number']['es-mx'] = "Número"; //copied from es-cl
$text['label-number']['fr-ca'] = "Numéro"; //copied from fr-fr
$text['label-number']['fr-fr'] = "Numéro";
$text['label-number']['he-il'] = "מספר";
$text['label-number']['it-it'] = "Numero";
$text['label-number']['nl-nl'] = "";
$text['label-number']['pl-pl'] = "Numer";
$text['label-number']['pt-br'] = "Número"; //copied from pt-pt
$text['label-number']['pt-pt'] = "Número";
$text['label-number']['ro-ro'] = "Număr";
$text['label-number']['ru-ru'] = "Номер";
$text['label-number']['sv-se'] = "Nummer";
$text['label-number']['uk-ua'] = "Номер";

$text['label-message']['en-us'] = "Message";
$text['label-message']['ar-eg'] = "رسالة";
$text['label-message']['de-at'] = "Nachricht"; //copied from de-de
$text['label-message']['de-ch'] = "Nachricht"; //copied from de-de
$text['label-message']['de-de'] = "Nachricht";
$text['label-message']['es-cl'] = "Mensaje";
$text['label-message']['es-mx'] = "Mensaje"; //copied from es-cl
$text['label-message']['fr-ca'] = "Message"; //copied from fr-fr
$text['label-message']['fr-fr'] = "Message";
$text['label-message']['he-il'] = "הודעה";
$text['label-message']['it-it'] = "Messaggio";
$text['label-message']['nl-nl'] = "";
$text['label-message']['pl-pl'] = "Wiadomość";
$text['label-message']['pt-br'] = "Mensagem"; //copied from pt-pt
$text['label-message']['pt-pt'] = "Mensagem";
$text['label-message']['ro-ro'] = "Mesaj";
$text['label-message']['ru-ru'] = "Сообщение";
$text['label-message']['sv-se'] = "Meddelande";
$text['label-message']['uk-ua'] = "Повідомлення";

$text['label-local']['en-us'] = "Local";
$text['label-local']['ar-eg'] = "محلي";
$text['label-local']['de-at'] = "Lokal"; //copied from de-de
$text['label-local']['de-ch'] = "Lokal"; //copied from de-de
$text['label-local']['de-de'] = "Lokal";
$text['label-local']['es-cl'] = "Local";
$text['label-local']['es-mx'] = "Local"; //copied from es-cl
$text['label-local']['fr-ca'] = "Local"; //copied from fr-fr
$text['label-local']['fr-fr'] = "Local";
$text['label-local']['he-il'] = "מקומי";
$text['label-local']['it-it'] = "Locale";
$text['label-local']['nl-nl'] = "";
$text['label-local']['pl-pl'] = "Lokalny";
$text['label-local']['pt-br'] = "Local"; //copied from pt-pt
$text['label-local']['pt-pt'] = "Local";
$text['label-local']['ro-ro'] = "Local";
$text['label-local']['ru-ru'] = "Локальный";
$text['label-local']['sv-se'] = "Lokal";
$text['label-local']['uk-ua'] = "Місцевий";

$text['label-inbound']['en-us'] = "Inbound";
$text['label-inbound']['ar-eg'] = "";
$text['label-inbound']['de-at'] = "Eingehend"; //copied from de-de
$text['label-inbound']['de-ch'] = "Eingehend"; //copied from de-de
$text['label-inbound']['de-de'] = "Eingehend";
$text['label-inbound']['es-cl'] = "Entrada";
$text['label-inbound']['es-mx'] = "Entrada"; //copied from es-cl
$text['label-inbound']['fr-ca'] = "Entrant"; //copied from fr-fr
$text['label-inbound']['fr-fr'] = "Entrant";
$text['label-inbound']['he-il'] = "";
$text['label-inbound']['it-it'] = "In ingresso";
$text['label-inbound']['nl-nl'] = "";
$text['label-inbound']['pl-pl'] = "Przychodzący";
$text['label-inbound']['pt-br'] = "Entrada"; //copied from pt-pt
$text['label-inbound']['pt-pt'] = "Entrada";
$text['label-inbound']['ro-ro'] = "";
$text['label-inbound']['ru-ru'] = "Входящий";
$text['label-inbound']['sv-se'] = "Inkommande";
$text['label-inbound']['uk-ua'] = "Вихідний";

$text['label-edit-note']['en-us'] = "Block calls from a number. Edit the name and enable/disable below.";
$text['label-edit-note']['ar-eg'] = "";
$text['label-edit-note']['de-at'] = "Anrufe von einer Rufnummer sperren. Bearbeiten Sie den Namen und aktivieren/deaktivieren Sie diesen unten."; //copied from de-de
$text['label-edit-note']['de-ch'] = "Anrufe von einer Rufnummer sperren. Bearbeiten Sie den Namen und aktivieren/deaktivieren Sie diesen unten."; //copied from de-de
$text['label-edit-note']['de-de'] = "Anrufe von einer Rufnummer sperren. Bearbeiten Sie den Namen und aktivieren/deaktivieren Sie diesen unten.";
$text['label-edit-note']['es-cl'] = "Bloquea llamadas desde un número. Edite el nombre y active/desactive abajo.";
$text['label-edit-note']['es-mx'] = "Bloquea llamadas desde un número. Edite el nombre y active/desactive abajo."; //copied from es-cl
$text['label-edit-note']['fr-ca'] = "Bloquer les appels à partir d'un numéro. Editer le nom et activer/désactiver ci-dessous."; //copied from fr-fr
$text['label-edit-note']['fr-fr'] = "Bloquer les appels à partir d'un numéro. Editer le nom et activer/désactiver ci-dessous.";
$text['label-edit-note']['he-il'] = "";
$text['label-edit-note']['it-it'] = "Blocca le chiamate da un numero. Inserire il nome e abilitare/disabilitare qui sotto.";
$text['label-edit-note']['nl-nl'] = "";
$text['label-edit-note']['pl-pl'] = "Blokowanie połączeń z danego numeru. Edytuj nazwę i włącz/wyłącz poniżej.";
$text['label-edit-note']['pt-br'] = "Bloquear chamadas a partir de um número. Edite o nome e ative ou desative";
$text['label-edit-note']['pt-pt'] = "Bloquear chamadas a partir de um número. Edite o nome e active/desactive.";
$text['label-edit-note']['ro-ro'] = "Blocați apelurile de la un număr. Editați numele și activați/dezactivați mai jos.";
$text['label-edit-note']['ru-ru'] = "Блокировать вызовы от номера. Отредактируйте имя и включено/выключено ниже.";
$text['label-edit-note']['sv-se'] = "Blockera samtal från nummer. Editera namn och Aktiv/Inaktiv nedan.";
$text['label-edit-note']['uk-ua'] = "Блокувати дзвінки з номера. Змініть ім'я і включіть/відключіть нижче.";

$text['label-edit-edit']['en-us'] = "Call Block";
$text['label-edit-edit']['ar-eg'] = "";
$text['label-edit-edit']['de-at'] = "Sperrlisten"; //copied from de-de
$text['label-edit-edit']['de-ch'] = "Sperrlisten"; //copied from de-de
$text['label-edit-edit']['de-de'] = "Sperrlisten";
$text['label-edit-edit']['es-cl'] = "Bloqueo de llamada";
$text['label-edit-edit']['es-mx'] = "Bloqueo de llamada"; //copied from es-cl
$text['label-edit-edit']['fr-ca'] = "Liste noire"; //copied from fr-fr
$text['label-edit-edit']['fr-fr'] = "Liste noire";
$text['label-edit-edit']['he-il'] = "חסימת שיחה";
$text['label-edit-edit']['it-it'] = "Blocco Chiamate";
$text['label-edit-edit']['nl-nl'] = "";
$text['label-edit-edit']['pl-pl'] = "Blokowanie rozmów";
$text['label-edit-edit']['pt-br'] = "Bloqueio de chamadas";
$text['label-edit-edit']['pt-pt'] = "Bloqueio de Chamadas";
$text['label-edit-edit']['ro-ro'] = "Blocare apel";
$text['label-edit-edit']['ru-ru'] = "Черный список";
$text['label-edit-edit']['sv-se'] = "Blockera Samtal";
$text['label-edit-edit']['uk-ua'] = "Блокування дзвінків";

$text['label-edit-add-recent']['en-us'] = "Recent Calls";
$text['label-edit-add-recent']['ar-eg'] = "";
$text['label-edit-add-recent']['de-at'] = "Kürzliche Anrufe"; //copied from de-de
$text['label-edit-add-recent']['de-ch'] = "Kürzliche Anrufe"; //copied from de-de
$text['label-edit-add-recent']['de-de'] = "Kürzliche Anrufe";
$text['label-edit-add-recent']['es-cl'] = "Llamadas Recientes";
$text['label-edit-add-recent']['es-mx'] = "Llamadas Recientes"; //copied from es-cl
$text['label-edit-add-recent']['fr-ca'] = "Appels Récents"; //copied from fr-fr
$text['label-edit-add-recent']['fr-fr'] = "Appels Récents";
$text['label-edit-add-recent']['he-il'] = "שיחות אחרונות";
$text['label-edit-add-recent']['it-it'] = "Chiamate Recenti";
$text['label-edit-add-recent']['nl-nl'] = "";
$text['label-edit-add-recent']['pl-pl'] = "Ostatnie rozmowy";
$text['label-edit-add-recent']['pt-br'] = "Chamadas recentes";
$text['label-edit-add-recent']['pt-pt'] = "Chamadas Recentes";
$text['label-edit-add-recent']['ro-ro'] = "Apeluri recente";
$text['label-edit-add-recent']['ru-ru'] = "Недавние вызовы";
$text['label-edit-add-recent']['sv-se'] = "Senaste Samtal";
$text['label-edit-add-recent']['uk-ua'] = "Останні дзвінки";

$text['label-edit-add']['en-us'] = "Call Block";
$text['label-edit-add']['ar-eg'] = "حظر المكالمات";
$text['label-edit-add']['de-at'] = "Sperrlisten"; //copied from de-de
$text['label-edit-add']['de-ch'] = "Sperrlisten"; //copied from de-de
$text['label-edit-add']['de-de'] = "Sperrlisten";
$text['label-edit-add']['es-cl'] = "Agregar bloqueo de llamada";
$text['label-edit-add']['es-mx'] = "Agregar bloqueo de llamada"; //copied from es-cl
$text['label-edit-add']['fr-ca'] = "Ajouter bloquage d'appel"; //copied from fr-fr
$text['label-edit-add']['fr-fr'] = "Ajouter bloquage d'appel";
$text['label-edit-add']['he-il'] = "חסימת שיחה";
$text['label-edit-add']['it-it'] = "Blocco Chiamate";
$text['label-edit-add']['nl-nl'] = "";
$text['label-edit-add']['pl-pl'] = "Blokowaie rozmów";
$text['label-edit-add']['pt-br'] = "Adicionar bloqueio de chamadas";
$text['label-edit-add']['pt-pt'] = "Adicionar Bloqueio de Chamadas";
$text['label-edit-add']['ro-ro'] = "Blocare apel";
$text['label-edit-add']['ru-ru'] = "Черный список";
$text['label-edit-add']['sv-se'] = "Blockera Samtal";
$text['label-edit-add']['uk-ua'] = "Блокування дзвінків";

$text['label-duration']['en-us'] = "Duration";
$text['label-duration']['ar-eg'] = "المدة";
$text['label-duration']['de-at'] = "Dauer"; //copied from de-de
$text['label-duration']['de-ch'] = "Dauer"; //copied from de-de
$text['label-duration']['de-de'] = "Dauer";
$text['label-duration']['es-cl'] = "Duración";
$text['label-duration']['es-mx'] = "Duración"; //copied from es-cl
$text['label-duration']['fr-ca'] = "Durée"; //copied from fr-fr
$text['label-duration']['fr-fr'] = "Durée";
$text['label-duration']['he-il'] = "משך השיחה";
$text['label-duration']['it-it'] = "Durata";
$text['label-duration']['nl-nl'] = "";
$text['label-duration']['pl-pl'] = "Czas trwania";
$text['label-duration']['pt-br'] = "Duração"; //copied from pt-pt
$text['label-duration']['pt-pt'] = "Duração";
$text['label-duration']['ro-ro'] = "Durată";
$text['label-duration']['ru-ru'] = "Длительность";
$text['label-duration']['sv-se'] = "Samtalstid";
$text['label-duration']['uk-ua'] = "Тривалість";

$text['label-delete-complete']['en-us'] = "Delete Complete";
$text['label-delete-complete']['ar-eg'] = "اكتمال المسح";
$text['label-delete-complete']['de-at'] = "Erfolgreich gelöscht"; //copied from de-de
$text['label-delete-complete']['de-ch'] = "Erfolgreich gelöscht"; //copied from de-de
$text['label-delete-complete']['de-de'] = "Erfolgreich gelöscht";
$text['label-delete-complete']['es-cl'] = "Eliminar Completo";
$text['label-delete-complete']['es-mx'] = "Eliminar Completo"; //copied from es-cl
$text['label-delete-complete']['fr-ca'] = "Supprimé"; //copied from fr-fr
$text['label-delete-complete']['fr-fr'] = "Supprimé";
$text['label-delete-complete']['he-il'] = "המחיקה הושלמה";
$text['label-delete-complete']['it-it'] = "Cancellazione Completata";
$text['label-delete-complete']['nl-nl'] = "";
$text['label-delete-complete']['pl-pl'] = "Usunięto poprawnie";
$text['label-delete-complete']['pt-br'] = "Remoção efetuada";
$text['label-delete-complete']['pt-pt'] = "Remoção Efectuada";
$text['label-delete-complete']['ro-ro'] = "Ștergere completă";
$text['label-delete-complete']['ru-ru'] = "Удаление завершено";
$text['label-delete-complete']['sv-se'] = "Borttagning Klar";
$text['label-delete-complete']['uk-ua'] = "Видалено";

$text['label-date-added']['en-us'] = "Date Added";
$text['label-date-added']['ar-eg'] = "تم اضافة التاريخ";
$text['label-date-added']['de-at'] = "Datum hinzugefügt"; //copied from de-de
$text['label-date-added']['de-ch'] = "Datum hinzugefügt"; //copied from de-de
$text['label-date-added']['de-de'] = "Datum hinzugefügt";
$text['label-date-added']['es-cl'] = "Fecha de ingreso";
$text['label-date-added']['es-mx'] = "Fecha de ingreso"; //copied from es-cl
$text['label-date-added']['fr-ca'] = "Date d'ajout"; //copied from fr-fr
$text['label-date-added']['fr-fr'] = "Date d'ajout";
$text['label-date-added']['he-il'] = "התאריך נוסף";
$text['label-date-added']['it-it'] = "Data Aggiunta";
$text['label-date-added']['nl-nl'] = "";
$text['label-date-added']['pl-pl'] = "Dodano datę";
$text['label-date-added']['pt-br'] = "Data adicionada"; //copied from pt-pt
$text['label-date-added']['pt-pt'] = "Data adicionada";
$text['label-date-added']['ro-ro'] = "Data adăugării";
$text['label-date-added']['ru-ru'] = "Дата добавления";
$text['label-date-added']['sv-se'] = "Datum Tillagt";
$text['label-date-added']['uk-ua'] = "Додано";

$text['label-count']['en-us'] = "Count";
$text['label-count']['ar-eg'] = "";
$text['label-count']['de-at'] = "Zähler"; //copied from de-de
$text['label-count']['de-ch'] = "Zähler"; //copied from de-de
$text['label-count']['de-de'] = "Zähler";
$text['label-count']['es-cl'] = "Conteo";
$text['label-count']['es-mx'] = "Conteo"; //copied from es-cl
$text['label-count']['fr-ca'] = "Nombre d'appels"; //copied from fr-fr
$text['label-count']['fr-fr'] = "Nombre d'appels";
$text['label-count']['he-il'] = "";
$text['label-count']['it-it'] = "Conteggio";
$text['label-count']['nl-nl'] = "";
$text['label-count']['pl-pl'] = "Wyliczenie";
$text['label-count']['pt-br'] = "Contagem"; //copied from pt-pt
$text['label-count']['pt-pt'] = "Contagem";
$text['label-count']['ro-ro'] = "";
$text['label-count']['ru-ru'] = "Количество";
$text['label-count']['sv-se'] = "Räkna";
$text['label-count']['uk-ua'] = "Кількість";

$text['label-called-on']['en-us'] = "Called on";
$text['label-called-on']['ar-eg'] = "تم الأتصال علي";
$text['label-called-on']['de-at'] = "Anruf am"; //copied from de-de
$text['label-called-on']['de-ch'] = "Anruf am"; //copied from de-de
$text['label-called-on']['de-de'] = "Anruf am";
$text['label-called-on']['es-cl'] = "Llamó en";
$text['label-called-on']['es-mx'] = "Llamó en"; //copied from es-cl
$text['label-called-on']['fr-ca'] = "Appelé sur"; //copied from fr-fr
$text['label-called-on']['fr-fr'] = "Appelé sur";
$text['label-called-on']['he-il'] = "";
$text['label-called-on']['it-it'] = "Chiamato il";
$text['label-called-on']['nl-nl'] = "";
$text['label-called-on']['pl-pl'] = "Zadzwoniono na";
$text['label-called-on']['pt-br'] = "Chamada em ";
$text['label-called-on']['pt-pt'] = "Chamado em";
$text['label-called-on']['ro-ro'] = "Sunat pe";
$text['label-called-on']['ru-ru'] = "Направление";
$text['label-called-on']['sv-se'] = "Ringdes på";
$text['label-called-on']['uk-ua'] = "Дзвінок здійснено";

$text['label-busy']['en-us'] = "Busy";
$text['label-busy']['ar-eg'] = "مشغول";
$text['label-busy']['de-at'] = "Besetzt"; //copied from de-de
$text['label-busy']['de-ch'] = "Besetzt"; //copied from de-de
$text['label-busy']['de-de'] = "Besetzt";
$text['label-busy']['es-cl'] = "Ocupado";
$text['label-busy']['es-mx'] = "Ocupado"; //copied from es-cl
$text['label-busy']['fr-ca'] = "Occupé"; //copied from fr-fr
$text['label-busy']['fr-fr'] = "Occupé";
$text['label-busy']['he-il'] = "תפוס";
$text['label-busy']['it-it'] = "Occupato";
$text['label-busy']['nl-nl'] = "";
$text['label-busy']['pl-pl'] = "Zajęty";
$text['label-busy']['pt-br'] = "Ocupado"; //copied from pt-pt
$text['label-busy']['pt-pt'] = "Ocupado";
$text['label-busy']['ro-ro'] = "Ocupat";
$text['label-busy']['ru-ru'] = "Занято";
$text['label-busy']['sv-se'] = "Upptagen";
$text['label-busy']['uk-ua'] = "Зайнято";

$text['label-hold']['en-us'] = "Hold";
$text['label-hold']['ar-eg'] = "";
$text['label-hold']['de-at'] = "Halten"; //copied from de-de
$text['label-hold']['de-ch'] = "Halten"; //copied from de-de
$text['label-hold']['de-de'] = "Halten";
$text['label-hold']['es-cl'] = "";
$text['label-hold']['es-mx'] = "";
$text['label-hold']['fr-ca'] = "Attente";
$text['label-hold']['fr-fr'] = "Attente";
$text['label-hold']['he-il'] = "";
$text['label-hold']['it-it'] = "In attesa";
$text['label-hold']['nl-nl'] = "";
$text['label-hold']['pl-pl'] = "";
$text['label-hold']['pt-br'] = "Espera"; //copied from pt-pt
$text['label-hold']['pt-pt'] = "Espera";
$text['label-hold']['ro-ro'] = "";
$text['label-hold']['ru-ru'] = "Удержание";
$text['label-hold']['sv-se'] = "Vänt";
$text['label-hold']['uk-ua'] = "";

$text['label-voicemail']['en-us'] = "Voicemail";
$text['label-voicemail']['ar-eg'] = "";
$text['label-voicemail']['de-at'] = "Mailbox"; //copied from de-de
$text['label-voicemail']['de-ch'] = "Mailbox"; //copied from de-de
$text['label-voicemail']['de-de'] = "Mailbox";
$text['label-voicemail']['es-cl'] = "Correo de Voz";
$text['label-voicemail']['es-mx'] = "Correo de Voz"; //copied from es-cl
$text['label-voicemail']['fr-ca'] = "Messagerie Vocale"; //copied from fr-fr
$text['label-voicemail']['fr-fr'] = "Messagerie Vocale";
$text['label-voicemail']['he-il'] = "תא קולי";
$text['label-voicemail']['it-it'] = "Voicemail";
$text['label-voicemail']['nl-nl'] = "";
$text['label-voicemail']['pl-pl'] = "Poczta głosowa";
$text['label-voicemail']['pt-br'] = "Correio de voz";
$text['label-voicemail']['pt-pt'] = "Correio de Voz";
$text['label-voicemail']['ro-ro'] = "";
$text['label-voicemail']['ru-ru'] = "Голосовая почта";
$text['label-voicemail']['sv-se'] = "Röstbrevlåda";
$text['label-voicemail']['uk-ua'] = "Голосова пошта";

$text['label-add-note']['en-us'] = "Block calls from a number. Either select a number from the list above or enter the number, name and enable below.";
$text['label-add-note']['ar-eg'] = "";
$text['label-add-note']['de-at'] = "Anrufe einer Rufnummer sperren. Wählen Sie eine Nummer von der Liste oder geben Sie eine Nummer und einen Name ein. Aktivieren Sie die Sperrliste unten."; //copied from de-de
$text['label-add-note']['de-ch'] = "Anrufe einer Rufnummer sperren. Wählen Sie eine Nummer von der Liste oder geben Sie eine Nummer und einen Name ein. Aktivieren Sie die Sperrliste unten."; //copied from de-de
$text['label-add-note']['de-de'] = "Anrufe einer Rufnummer sperren. Wählen Sie eine Nummer von der Liste oder geben Sie eine Nummer und einen Name ein. Aktivieren Sie die Sperrliste unten.";
$text['label-add-note']['es-cl'] = "Bloquea llamadas desde un número. Puede elegir un número de la lista de arriba o ingresar el n&uacute, nombre y activarlo abajo.";
$text['label-add-note']['es-mx'] = "Bloquea llamadas desde un número. Puede elegir un número de la lista de arriba o ingresar el n&uacute, nombre y activarlo abajo."; //copied from es-cl
$text['label-add-note']['fr-ca'] = "Bloquer les appels à partir d'un numéro. Choisissez un numéro dans liste ou entrez un numéro, nom et activer le."; //copied from fr-fr
$text['label-add-note']['fr-fr'] = "Bloquer les appels à partir d'un numéro. Choisissez un numéro dans liste ou entrez un numéro, nom et activer le.";
$text['label-add-note']['he-il'] = "";
$text['label-add-note']['it-it'] = "Blocca le chiamate da un numero. Seleziona un numero dalla lista sovrastante o inserisci il numero, il nome e l'abilitazione qui sotto.";
$text['label-add-note']['nl-nl'] = "";
$text['label-add-note']['pl-pl'] = "Blokowanie połączeń z danego numeru. Wybierz numer z powyższej listy j lub wpisz numer, nazwę i załącz poniżej.";
$text['label-add-note']['pt-br'] = "Bloquear chamadas a partir de um número. Selecione um número a partir da lista indicada ou insira um número e um nome em seguida ative";
$text['label-add-note']['pt-pt'] = "Bloquear chamadas a partir de um número. Seleccione um número a partir da lista indicada ou introduza um número, nome e active.";
$text['label-add-note']['ro-ro'] = "";
$text['label-add-note']['ru-ru'] = "Блокировка вызовов от номера. Выберите номер из списка выше либо введите его самостоятельно, имя и включите ниже.";
$text['label-add-note']['sv-se'] = "Blockera samtal från ett nummer. Välj antingen ett nummer från listan ovan eller fyll i nummer, namn och aktivera nedan.";
$text['label-add-note']['uk-ua'] = "Блокувати дзвінки з номера. Або вибрати номер зі списку вище або введіть номер, ім'я і включити нижче.";

$text['label-add-complete']['en-us'] = "Add Complete";
$text['label-add-complete']['ar-eg'] = "تمت الأضافة";
$text['label-add-complete']['de-at'] = "Erfolgreich hinzugefügt"; //copied from de-de
$text['label-add-complete']['de-ch'] = "Erfolgreich hinzugefügt"; //copied from de-de
$text['label-add-complete']['de-de'] = "Erfolgreich hinzugefügt";
$text['label-add-complete']['es-cl'] = "Agregar Completo";
$text['label-add-complete']['es-mx'] = "Agregar Completo"; //copied from es-cl
$text['label-add-complete']['fr-ca'] = "Ajouté"; //copied from fr-fr
$text['label-add-complete']['fr-fr'] = "Ajouté";
$text['label-add-complete']['he-il'] = "הוספה הושלמה";
$text['label-add-complete']['it-it'] = "Inserimento Completato";
$text['label-add-complete']['nl-nl'] = "";
$text['label-add-complete']['pl-pl'] = "Dodano poprawnie";
$text['label-add-complete']['pt-br'] = "Criação efetuada ";
$text['label-add-complete']['pt-pt'] = "Adição Efectuada";
$text['label-add-complete']['ro-ro'] = "Adăugare completă";
$text['label-add-complete']['ru-ru'] = "Добавление завершено";
$text['label-add-complete']['sv-se'] = "Tillagd";
$text['label-add-complete']['uk-ua'] = "Додано";

$text['label-action']['en-us'] = "Action";
$text['label-action']['ar-eg'] = "";
$text['label-action']['de-at'] = "Aktion"; //copied from de-de
$text['label-action']['de-ch'] = "Aktion"; //copied from de-de
$text['label-action']['de-de'] = "Aktion";
$text['label-action']['es-cl'] = "Acción";
$text['label-action']['es-mx'] = "Acción"; //copied from es-cl
$text['label-action']['fr-ca'] = "Action"; //copied from fr-fr
$text['label-action']['fr-fr'] = "Action";
$text['label-action']['he-il'] = "פעולה";
$text['label-action']['it-it'] = "Azione";
$text['label-action']['nl-nl'] = "";
$text['label-action']['pl-pl'] = "Operacja";
$text['label-action']['pt-br'] = "Ação";
$text['label-action']['pt-pt'] = "Acção";
$text['label-action']['ro-ro'] = "Acțiune";
$text['label-action']['ru-ru'] = "Действие";
$text['label-action']['sv-se'] = "Åtgärd";
$text['label-action']['uk-ua'] = "Дія";

$text['description-number']['en-us'] = "Enter the number. This may be a regex expression or SQL match depending on the setting of the call_block_matching setting.";
$text['description-number']['ar-eg'] = "";
$text['description-number']['de-at'] = "Geben Sie die Nummer an. Es kann sich hierbei um eine regulären Ausdruck oder einen SQL Vergleich handeln, je nach Wert der call_block_matching Einstellung."; //copied from de-de
$text['description-number']['de-ch'] = "Geben Sie die Nummer an. Es kann sich hierbei um eine regulären Ausdruck oder einen SQL Vergleich handeln, je nach Wert der call_block_matching Einstellung."; //copied from de-de
$text['description-number']['de-de'] = "Geben Sie die Nummer an. Es kann sich hierbei um eine regulären Ausdruck oder einen SQL Vergleich handeln, je nach Wert der call_block_matching Einstellung.";
$text['description-number']['es-cl'] = "Ingrese el nú exacto.";
$text['description-number']['es-mx'] = "Ingrese el nú exacto."; //copied from es-cl
$text['description-number']['fr-ca'] = "Entrer le numéro exact."; //copied from fr-fr
$text['description-number']['fr-fr'] = "Entrer le numéro exact.";
$text['description-number']['he-il'] = "הכנס את המספר המבוקש";
$text['description-number']['it-it'] = "Inserisci il numero esatto.";
$text['description-number']['nl-nl'] = "";
$text['description-number']['pl-pl'] = "Wprowadź dokładny numer.";
$text['description-number']['pt-br'] = "Insira o número exato.";
$text['description-number']['pt-pt'] = "Introduza o número exacto.";
$text['description-number']['ro-ro'] = "Introduceți numărul exact";
$text['description-number']['ru-ru'] = "Введите точный номер.";
$text['description-number']['sv-se'] = "Ange det exakta numret";
$text['description-number']['uk-ua'] = "Введіть точний номер";

$text['description-name']['en-us'] = "Enter the name.";
$text['description-name']['ar-eg'] = "أدخل الأسم";
$text['description-name']['de-at'] = "Geben Sie den Namen an"; //copied from de-de
$text['description-name']['de-ch'] = "Geben Sie den Namen an"; //copied from de-de
$text['description-name']['de-de'] = "Geben Sie den Namen an";
$text['description-name']['es-cl'] = "Introduzca el nombre.";
$text['description-name']['es-mx'] = "Introduzca el nombre."; //copied from es-cl
$text['description-name']['fr-ca'] = "Entrez le nom."; //copied from fr-fr
$text['description-name']['fr-fr'] = "Entrez le nom.";
$text['description-name']['he-il'] = "הכנס את השם";
$text['description-name']['it-it'] = "Inserisci il nome.";
$text['description-name']['nl-nl'] = "";
$text['description-name']['pl-pl'] = "Wprowadź nazwę";
$text['description-name']['pt-br'] = "Insira o nome.";
$text['description-name']['pt-pt'] = "Digite o nome.";
$text['description-name']['ro-ro'] = "Introduceți numele";
$text['description-name']['ru-ru'] = "Введите имя.";
$text['description-name']['sv-se'] = "Skriv in namnet.";
$text['description-name']['uk-ua'] = "Введіть назву меню";

$text['description-enable']['en-us'] = "Set to true to enable call blocking for this number.";
$text['description-enable']['ar-eg'] = "";
$text['description-enable']['de-at'] = "Setzen Sie auf An, um die Sperrung für diese Nummer zu aktivieren."; //copied from de-de
$text['description-enable']['de-ch'] = "Setzen Sie auf An, um die Sperrung für diese Nummer zu aktivieren."; //copied from de-de
$text['description-enable']['de-de'] = "Setzen Sie auf An, um die Sperrung für diese Nummer zu aktivieren.";
$text['description-enable']['es-cl'] = "Seleccione verdadero para activar el bloqueo de llamadas desde este número.";
$text['description-enable']['es-mx'] = "Seleccione verdadero para activar el bloqueo de llamadas desde este número."; //copied from es-cl
$text['description-enable']['fr-ca'] = "Choisir Oui pour activer le bloquage d'appel."; //copied from fr-fr
$text['description-enable']['fr-fr'] = "Choisir Oui pour activer le bloquage d'appel.";
$text['description-enable']['he-il'] = "";
$text['description-enable']['it-it'] = "Selezionare 'true' per abilitare il blocco chiamate da questo numero.";
$text['description-enable']['nl-nl'] = "";
$text['description-enable']['pl-pl'] = "Ustaw wartość na TAK, aby umożliwić blokowanie tego numeru ";
$text['description-enable']['pt-br'] = "Escolha 'sim' para ativar o bloqueio  de chamadas para este número.";
$text['description-enable']['pt-pt'] = "Escolha 'sim' para activar o bloqueio de chamadas para este número.";
$text['description-enable']['ro-ro'] = "";
$text['description-enable']['ru-ru'] = "Выберите 'Да', чтобы блокировать вызовы с данного номера.";
$text['description-enable']['sv-se'] = "Välj Sann för att blockera detta nummer.";
$text['description-enable']['uk-ua'] = "Виберіть 'Так', щоб блокувати дзвінки з даного номера.";

$text['description-call-block']['en-us'] = "A list of numbers from which to block calls.";
$text['description-call-block']['ar-eg'] = "";
$text['description-call-block']['de-at'] = "Eine Liste von Nummern die gesperrt werden sollen."; //copied from de-de
$text['description-call-block']['de-ch'] = "Eine Liste von Nummern die gesperrt werden sollen."; //copied from de-de
$text['description-call-block']['de-de'] = "Eine Liste von Nummern die gesperrt werden sollen.";
$text['description-call-block']['es-cl'] = "Un listado de números desde los cuales se bloquean las llamadas";
$text['description-call-block']['es-mx'] = "Un listado de números desde los cuales se bloquean las llamadas"; //copied from es-cl
$text['description-call-block']['fr-ca'] = "Une liste de numéro dont on veut bloquer les appels"; //copied from fr-fr
$text['description-call-block']['fr-fr'] = "Une liste de numéro dont on veut bloquer les appels";
$text['description-call-block']['he-il'] = "";
$text['description-call-block']['it-it'] = "Una lista di numeri per cui è possibile bloccare le chiamate.";
$text['description-call-block']['nl-nl'] = "";
$text['description-call-block']['pl-pl'] = "Lista numerów, z których rozmowy są blokowane.";
$text['description-call-block']['pt-br'] = "Uma lista de números que deseja bloquear as chamadas";
$text['description-call-block']['pt-pt'] = "Uma lista de números que deseje bloquear as chamadas";
$text['description-call-block']['ro-ro'] = "";
$text['description-call-block']['ru-ru'] = "Список номеров, с которых блокируются вызовы.";
$text['description-call-block']['sv-se'] = "En lista med nummer för blockering av samtal.";
$text['description-call-block']['uk-ua'] = "Список номерів, з яких блокуються дзвінки.";

$text['description-action']['en-us'] = "Set an action for calls from this number.";
$text['description-action']['ar-eg'] = "";
$text['description-action']['de-at'] = "Wählen Sie eine Aktion für Anrufe von dieser Nummer."; //copied from de-de
$text['description-action']['de-ch'] = "Wählen Sie eine Aktion für Anrufe von dieser Nummer."; //copied from de-de
$text['description-action']['de-de'] = "Wählen Sie eine Aktion für Anrufe von dieser Nummer.";
$text['description-action']['es-cl'] = "Configurar una acción para llamadas desde este número.";
$text['description-action']['es-mx'] = "Configurar una acción para llamadas desde este número."; //copied from es-cl
$text['description-action']['fr-ca'] = "Choisir une action pour les appels venant de ce numéro."; //copied from fr-fr
$text['description-action']['fr-fr'] = "Choisir une action pour les appels venant de ce numéro.";
$text['description-action']['he-il'] = "";
$text['description-action']['it-it'] = "Seleziona un'azione per le chiamate da questo numero.";
$text['description-action']['nl-nl'] = "";
$text['description-action']['pl-pl'] = "Ustaw co zrobić w przypadku polaczeń z tego numeru.";
$text['description-action']['pt-br'] = "Escolha uma ação para chamadas reailzadas por este número.";
$text['description-action']['pt-pt'] = "Escolha uma acção para chamadas com origem neste número.";
$text['description-action']['ro-ro'] = "";
$text['description-action']['ru-ru'] = "Установите действие для вызовов с данного номера.";
$text['description-action']['sv-se'] = "Välj en aktion för samtal från detta nummer.";
$text['description-action']['uk-ua'] = "Встановіть дію для дзвінків з цього номера.";

?>
