<?php
#This file was last reorganized on 19th of September 2017 08:54:24 AM UTC

$text['title-call-block']['en-us'] = "Call Block";
$text['title-call-block']['en-gb'] = "Call Block";
$text['title-call-block']['ar-eg'] = "حظر المكالمات";
$text['title-call-block']['de-at'] = "Sperrlisten"; //copied from de-de
$text['title-call-block']['de-ch'] = "Sperrlisten"; //copied from de-de
$text['title-call-block']['de-de'] = "Sperrlisten";
$text['title-call-block']['el-gr'] = "Λίστα αποκλεισμών";
$text['title-call-block']['es-cl'] = "Bloqueo de llamadas";
$text['title-call-block']['es-mx'] = "Bloqueo de llamadas"; //copied from es-cl
$text['title-call-block']['fr-ca'] = "Filtrage d'appel"; //copied from fr-fr
$text['title-call-block']['fr-fr'] = "Filtrage d'appel";
$text['title-call-block']['he-il'] = "חסימת מספר";
$text['title-call-block']['it-it'] = "Blocco Chiamate";
$text['title-call-block']['nl-nl'] = "Oproep blokkade";
$text['title-call-block']['pl-pl'] = "Blokowanie rozmów";
$text['title-call-block']['pt-br'] = "Bloqueio de chamadas";
$text['title-call-block']['pt-pt'] = "Bloqueio de Chamadas";
$text['title-call-block']['ro-ro'] = "Blocare apel";
$text['title-call-block']['ru-ru'] = "Черный список";
$text['title-call-block']['sv-se'] = "Blockera Samtal";
$text['title-call-block']['uk-ua'] = "Блокування дзвінків";

$text['heading-recent_calls']['en-us'] = "Recent Calls";
$text['heading-recent_calls']['en-gb'] = "Recent Calls";
$text['heading-recent_calls']['ar-eg'] = "";
$text['heading-recent_calls']['de-at'] = "Kürzliche Anrufe"; //copied from de-de
$text['heading-recent_calls']['de-ch'] = "Kürzliche Anrufe"; //copied from de-de
$text['heading-recent_calls']['de-de'] = "Kürzliche Anrufe";
$text['heading-recent_calls']['el-gr'] = "Πρόσφατες Κλήσεις";
$text['heading-recent_calls']['es-cl'] = "Llamadas Recientes";
$text['heading-recent_calls']['es-mx'] = "Llamadas Recientes"; //copied from es-cl
$text['heading-recent_calls']['fr-ca'] = "Appels récents"; //copied from fr-fr
$text['heading-recent_calls']['fr-fr'] = "Appels récents";
$text['heading-recent_calls']['he-il'] = "שיחות אחרונות";
$text['heading-recent_calls']['it-it'] = "Chiamate Recenti";
$text['heading-recent_calls']['nl-nl'] = "Recente oproepen";
$text['heading-recent_calls']['pl-pl'] = "Ostatnie rozmowy";
$text['heading-recent_calls']['pt-br'] = "Chamadas recentes";
$text['heading-recent_calls']['pt-pt'] = "Chamadas Recentes";
$text['heading-recent_calls']['ro-ro'] = "Apeluri recente";
$text['heading-recent_calls']['ru-ru'] = "Недавние вызовы";
$text['heading-recent_calls']['sv-se'] = "Senaste Samtal";
$text['heading-recent_calls']['uk-ua'] = "Останні дзвінки";

$text['heading-block_recent_calls']['en-us'] = "Block Recent Calls";
$text['heading-block_recent_calls']['en-gb'] = "Block Recent Calls";
$text['heading-block_recent_calls']['ar-eg'] = "";
$text['heading-block_recent_calls']['de-at'] = "Kürzliche Anrufe Blockieren"; //copied from de-de
$text['heading-block_recent_calls']['de-ch'] = "Kürzliche Anrufe Blockieren"; //copied from de-de
$text['heading-block_recent_calls']['de-de'] = "Kürzliche Anrufe Blockieren";
$text['heading-block_recent_calls']['el-gr'] = "Αποκλεισμός Πρόσφατης Κλήσης";
$text['heading-block_recent_calls']['es-cl'] = "Bloqueo de llamadas recientes";
$text['heading-block_recent_calls']['es-mx'] = "Bloqueo de llamadas recientes"; //copied from es-cl
$text['heading-block_recent_calls']['fr-ca'] = "Bloquer appels récents"; //copied from fr-fr
$text['heading-block_recent_calls']['fr-fr'] = "Bloquer appels récents";
$text['heading-block_recent_calls']['he-il'] = "";
$text['heading-block_recent_calls']['it-it'] = "Blocca le chiamate recenti";
$text['heading-block_recent_calls']['nl-nl'] = "Blokkeer recente oproep";
$text['heading-block_recent_calls']['pl-pl'] = "Zablokuj ostatnią rozmowę";
$text['heading-block_recent_calls']['pt-br'] = "Bloquear chamadas recentes";
$text['heading-block_recent_calls']['pt-pt'] = "Bloquear Chamadas Recentes";
$text['heading-block_recent_calls']['ro-ro'] = "Blocare apel recent";
$text['heading-block_recent_calls']['ru-ru'] = "Блокировать недавний вызов";
$text['heading-block_recent_calls']['sv-se'] = "Blockera Senaste Samtal";
$text['heading-block_recent_calls']['uk-ua'] = "Блокувати недавній дзвінок";

$text['label-update-complete']['en-us'] = "Update Complete";
$text['label-update-complete']['en-gb'] = "Update Complete";
$text['label-update-complete']['ar-eg'] = "اكتمال التحديث";
$text['label-update-complete']['de-at'] = "Aktualisierung abgeschlossen"; //copied from de-de
$text['label-update-complete']['de-ch'] = "Aktualisierung abgeschlossen"; //copied from de-de
$text['label-update-complete']['de-de'] = "Aktualisierung abgeschlossen";
$text['label-update-complete']['el-gr'] = "Η ενημέρωση ολοκληρώθηκε";
$text['label-update-complete']['es-cl'] = "Actualización Completa";
$text['label-update-complete']['es-mx'] = "Actualización Completa"; //copied from es-cl
$text['label-update-complete']['fr-ca'] = "Mise à jour effectuée"; //copied from fr-fr
$text['label-update-complete']['fr-fr'] = "Mise à jour effectuée";
$text['label-update-complete']['he-il'] = "העדכון הושלם";
$text['label-update-complete']['it-it'] = "Aggiornamento Completato";
$text['label-update-complete']['nl-nl'] = "Bijgewerkt";
$text['label-update-complete']['pl-pl'] = "Zaktualizowano poprawnie";
$text['label-update-complete']['pt-br'] = "Atualização Completa";
$text['label-update-complete']['pt-pt'] = "Actualização Efectuada";
$text['label-update-complete']['ro-ro'] = "Actualizare completă";
$text['label-update-complete']['ru-ru'] = "Обновление завершено";
$text['label-update-complete']['sv-se'] = "Uppdatering Klar";
$text['label-update-complete']['uk-ua'] = "Оновлено";

$text['label-reject']['en-us'] = "Reject";
$text['label-reject']['en-gb'] = "Reject";
$text['label-reject']['ar-eg'] = "رفض";
$text['label-reject']['de-at'] = "Zurückweisen"; //copied from de-de
$text['label-reject']['de-ch'] = "Zurückweisen"; //copied from de-de
$text['label-reject']['de-de'] = "Zurückweisen";
$text['label-reject']['el-gr'] = "Απόρριψη";
$text['label-reject']['es-cl'] = "Rechazar";
$text['label-reject']['es-mx'] = "Rechazar"; //copied from es-cl
$text['label-reject']['fr-ca'] = "Rejeter"; //copied from fr-fr
$text['label-reject']['fr-fr'] = "Rejeter";
$text['label-reject']['he-il'] = "לדחות";
$text['label-reject']['it-it'] = "Blocca";
$text['label-reject']['nl-nl'] = "Weigeren";
$text['label-reject']['pl-pl'] = "Odrzuć ";
$text['label-reject']['pt-br'] = "Rejeitar"; //copied from pt-pt
$text['label-reject']['pt-pt'] = "Rejeitar";
$text['label-reject']['ro-ro'] = "";
$text['label-reject']['ru-ru'] = "Отклонить";
$text['label-reject']['sv-se'] = "Neka";
$text['label-reject']['uk-ua'] = "Відхилити";

$text['label-provide-number']['en-us'] = "Please provide: Number";
$text['label-provide-number']['en-gb'] = "Please provide: Number";
$text['label-provide-number']['ar-eg'] = "من فضلك أدخل: الرقم";
$text['label-provide-number']['de-at'] = "Bitte geben Sie die Nummer an"; //copied from de-de
$text['label-provide-number']['de-ch'] = "Bitte geben Sie die Nummer an"; //copied from de-de
$text['label-provide-number']['de-de'] = "Bitte geben Sie die Nummer an";
$text['label-provide-number']['el-gr'] = "Εισάγετε: Αριθμό";
$text['label-provide-number']['es-cl'] = "Por favor agregue: Número";
$text['label-provide-number']['es-mx'] = "Por favor agregue: Número"; //copied from es-cl
$text['label-provide-number']['fr-ca'] = "S'il vous plaît indiquer: Numéro"; 
$text['label-provide-number']['fr-fr'] = "Merci d'indiquer: Numéro";
$text['label-provide-number']['he-il'] = "אנא הכנס מספר";
$text['label-provide-number']['it-it'] = "Prego fornire: Numero";
$text['label-provide-number']['nl-nl'] = "Geef aub: Nummer";
$text['label-provide-number']['pl-pl'] = " Wprowadź numer";
$text['label-provide-number']['pt-br'] = "Por favor indique: Número"; //copied from pt-pt
$text['label-provide-number']['pt-pt'] = "Por favor indique: Número";
$text['label-provide-number']['ro-ro'] = "";
$text['label-provide-number']['ru-ru'] = "Введите номер";
$text['label-provide-number']['sv-se'] = "Ange: Nummer";
$text['label-provide-number']['uk-ua'] = "Введіть номер";

$text['label-provide-name']['en-us'] = "Please provide: Name";
$text['label-provide-name']['en-gb'] = "Please provide: Name";
$text['label-provide-name']['ar-eg'] = "من فضلك أدخل: الأسم";
$text['label-provide-name']['de-at'] = "Bitte geben Sie den Namen an"; //copied from de-de
$text['label-provide-name']['de-ch'] = "Bitte geben Sie den Namen an"; //copied from de-de
$text['label-provide-name']['de-de'] = "Bitte geben Sie den Namen an";
$text['label-provide-name']['el-gr'] = "Εισάγετε: Όνομα";
$text['label-provide-name']['es-cl'] = "Por favor agregue: Nombre";
$text['label-provide-name']['es-mx'] = "Por favor agregue: Nombre"; //copied from es-cl
$text['label-provide-name']['fr-ca'] = "S'il vous plaît indiquer: Nom"; //copied from fr-fr
$text['label-provide-name']['fr-fr'] = "Merci d'indiquer: Nom";
$text['label-provide-name']['he-il'] = "אנא הכנס שם";
$text['label-provide-name']['it-it'] = "Prego fornire: Nome";
$text['label-provide-name']['nl-nl'] = "Geef aub: Naam";
$text['label-provide-name']['pl-pl'] = " Wprowadź nazwę ";
$text['label-provide-name']['pt-br'] = "Por favor indique: Nome"; //copied from pt-pt
$text['label-provide-name']['pt-pt'] = "Por favor indique: Nome";
$text['label-provide-name']['ro-ro'] = "";
$text['label-provide-name']['ru-ru'] = "Пожалуйста, введите: Имя";
$text['label-provide-name']['sv-se'] = "Ange: Namn";
$text['label-provide-name']['uk-ua'] = "Введіть назву";

$text['label-provide-enabled']['en-us'] = "Please provide: Enabled";
$text['label-provide-enabled']['en-gb'] = "Please provide: Enabled";
$text['label-provide-enabled']['ar-eg'] = "";
$text['label-provide-enabled']['de-at'] = "Bitte geben Sie folgendes an: Aktiv"; //copied from de-de
$text['label-provide-enabled']['de-ch'] = "Bitte geben Sie folgendes an: Aktiv"; //copied from de-de
$text['label-provide-enabled']['de-de'] = "Bitte geben Sie folgendes an: Aktiv";
$text['label-provide-enabled']['el-gr'] = "Εισάγετε: Ενεργοποιημένο";
$text['label-provide-enabled']['es-cl'] = "Por favor agregue: Activo";
$text['label-provide-enabled']['es-mx'] = "Por favor agregue: Activo"; //copied from es-cl
$text['label-provide-enabled']['fr-ca'] = "S'il vous plaît indiquer: Actif"; //copied from fr-fr
$text['label-provide-enabled']['fr-fr'] = "Merci d'indiquer: Actif";
$text['label-provide-enabled']['he-il'] = "";
$text['label-provide-enabled']['it-it'] = "Prego fornire: Abilitazione";
$text['label-provide-enabled']['nl-nl'] = "Geef aub: Aktief";
$text['label-provide-enabled']['pl-pl'] = " Wprowadź: Włączony";
$text['label-provide-enabled']['pt-br'] = "Por favor indique se está habilitado";
$text['label-provide-enabled']['pt-pt'] = "Por favor indique: Activado";
$text['label-provide-enabled']['ro-ro'] = "";
$text['label-provide-enabled']['ru-ru'] = "Пожалуйста, введите: Включить";
$text['label-provide-enabled']['sv-se'] = "Ange: Aktiverad";
$text['label-provide-enabled']['uk-ua'] = "Включити/відключити";

$text['label-country_code']['en-us'] = "Country Code";
$text['label-country_code']['en-gb'] = "Country Code";
$text['label-country_code']['ar-eg'] = "";
$text['label-country_code']['de-at'] = ""; //copied from de-de
$text['label-country_code']['de-ch'] = ""; //copied from de-de
$text['label-country_code']['de-de'] = "";
$text['label-country_code']['es-cl'] = "";
$text['label-country_code']['es-mx'] = ""; //copied from es-cl
$text['label-country_code']['fr-ca'] = "Préfixe"; //copied from fr-fr
$text['label-country_code']['fr-fr'] = "Préfixe";
$text['label-country_code']['he-il'] = "";
$text['label-country_code']['it-it'] = "";
$text['label-country_code']['nl-nl'] = "Voorloop";
$text['label-country_code']['pl-pl'] = "";
$text['label-country_code']['pt-br'] = "Prefixo"; //copied from pt-pt
$text['label-country_code']['pt-pt'] = "";
$text['label-country_code']['ro-ro'] = "";
$text['label-country_code']['ru-ru'] = "";
$text['label-country_code']['sv-se'] = "";
$text['label-country_code']['uk-ua'] = "";

$text['label-number']['en-us'] = "Number";
$text['label-number']['en-gb'] = "Number";
$text['label-number']['ar-eg'] = "رقم";
$text['label-number']['de-at'] = "Nummer"; //copied from de-de
$text['label-number']['de-ch'] = "Nummer"; //copied from de-de
$text['label-number']['de-de'] = "Nummer";
$text['label-number']['el-gr'] = "Αριθμός";
$text['label-number']['es-cl'] = "Número";
$text['label-number']['es-mx'] = "Número"; //copied from es-cl
$text['label-number']['fr-ca'] = "Numéro"; //copied from fr-fr
$text['label-number']['fr-fr'] = "Numéro";
$text['label-number']['he-il'] = "מספר";
$text['label-number']['it-it'] = "Numero";
$text['label-number']['nl-nl'] = "Nummer";
$text['label-number']['pl-pl'] = "Numer";
$text['label-number']['pt-br'] = "Número"; //copied from pt-pt
$text['label-number']['pt-pt'] = "Número";
$text['label-number']['ro-ro'] = "Număr";
$text['label-number']['ru-ru'] = "Номер";
$text['label-number']['sv-se'] = "Nummer";
$text['label-number']['uk-ua'] = "Номер";

$text['label-message']['en-us'] = "Message";
$text['label-message']['en-gb'] = "Message";
$text['label-message']['ar-eg'] = "رسالة";
$text['label-message']['de-at'] = "Nachricht"; //copied from de-de
$text['label-message']['de-ch'] = "Nachricht"; //copied from de-de
$text['label-message']['de-de'] = "Nachricht";
$text['label-message']['el-gr'] = "Μήνυμα";
$text['label-message']['es-cl'] = "Mensaje";
$text['label-message']['es-mx'] = "Mensaje"; //copied from es-cl
$text['label-message']['fr-ca'] = "Message"; //copied from fr-fr
$text['label-message']['fr-fr'] = "Message";
$text['label-message']['he-il'] = "הודעה";
$text['label-message']['it-it'] = "Messaggio";
$text['label-message']['nl-nl'] = "Bericht";
$text['label-message']['pl-pl'] = "Wiadomość";
$text['label-message']['pt-br'] = "Mensagem"; //copied from pt-pt
$text['label-message']['pt-pt'] = "Mensagem";
$text['label-message']['ro-ro'] = "Mesaj";
$text['label-message']['ru-ru'] = "Сообщение";
$text['label-message']['sv-se'] = "Meddelande";
$text['label-message']['uk-ua'] = "Повідомлення";

$text['label-local']['en-us'] = "Local";
$text['label-local']['en-gb'] = "Local";
$text['label-local']['ar-eg'] = "محلي";
$text['label-local']['de-at'] = "Lokal"; //copied from de-de
$text['label-local']['de-ch'] = "Lokal"; //copied from de-de
$text['label-local']['de-de'] = "Lokal";
$text['label-local']['el-gr'] = "Τοπικό";
$text['label-local']['es-cl'] = "Local";
$text['label-local']['es-mx'] = "Local"; //copied from es-cl
$text['label-local']['fr-ca'] = "Local"; //copied from fr-fr
$text['label-local']['fr-fr'] = "Local";
$text['label-local']['he-il'] = "מקומי";
$text['label-local']['it-it'] = "Locale";
$text['label-local']['nl-nl'] = "Lokaal";
$text['label-local']['pl-pl'] = "Lokalny";
$text['label-local']['pt-br'] = "Local"; //copied from pt-pt
$text['label-local']['pt-pt'] = "Local";
$text['label-local']['ro-ro'] = "Local";
$text['label-local']['ru-ru'] = "Локальный";
$text['label-local']['sv-se'] = "Lokal";
$text['label-local']['uk-ua'] = "Місцевий";

$text['label-inbound']['en-us'] = "Inbound";
$text['label-inbound']['en-gb'] = "Inbound";
$text['label-inbound']['ar-eg'] = "";
$text['label-inbound']['de-at'] = "Eingehend"; //copied from de-de
$text['label-inbound']['de-ch'] = "Eingehend"; //copied from de-de
$text['label-inbound']['de-de'] = "Eingehend";
$text['label-inbound']['el-gr'] = "Εισερχόμενο";
$text['label-inbound']['es-cl'] = "Entrada";
$text['label-inbound']['es-mx'] = "Entrada"; //copied from es-cl
$text['label-inbound']['fr-ca'] = "Entrant"; //copied from fr-fr
$text['label-inbound']['fr-fr'] = "Entrant";
$text['label-inbound']['he-il'] = "";
$text['label-inbound']['it-it'] = "In ingresso";
$text['label-inbound']['nl-nl'] = "Inkomend";
$text['label-inbound']['pl-pl'] = "Przychodzący";
$text['label-inbound']['pt-br'] = "Entrada"; //copied from pt-pt
$text['label-inbound']['pt-pt'] = "Entrada";
$text['label-inbound']['ro-ro'] = "";
$text['label-inbound']['ru-ru'] = "Входящий";
$text['label-inbound']['sv-se'] = "Inkommande";
$text['label-inbound']['uk-ua'] = "Вихідний";

$text['label-outbound']['en-us'] = "Outbound";
$text['label-outbound']['en-gb'] = "Outbound";
$text['label-outbound']['ar-eg'] = "";
$text['label-outbound']['de-at'] = "Ausgehend"; //copied from de-de
$text['label-outbound']['de-ch'] = "Ausgehend"; //copied from de-de
$text['label-outbound']['de-de'] = "Ausgehend";
$text['label-outbound']['es-cl'] = "Salida";
$text['label-outbound']['es-mx'] = "Salida"; //copied from es-cl
$text['label-outbound']['fr-ca'] = "Sortant"; //copied from fr-fr
$text['label-outbound']['fr-fr'] = "Sortant";
$text['label-outbound']['he-il'] = "";
$text['label-outbound']['it-it'] = "In Uscita";
$text['label-outbound']['nl-nl'] = "";
$text['label-outbound']['pl-pl'] = "Wychodzące";
$text['label-outbound']['pt-br'] = "Saída"; //copied from pt-pt
$text['label-outbound']['pt-pt'] = "Saída";
$text['label-outbound']['ro-ro'] = "";
$text['label-outbound']['ru-ru'] = "Исходящие";
$text['label-outbound']['sv-se'] = "Utgående";
$text['label-outbound']['uk-ua'] = "";

$text['label-destination']['en-us'] = "Destination";
$text['label-destination']['en-gb'] = "Destination";
$text['label-destination']['ar-eg'] = "";
$text['label-destination']['de-at'] = "Ziel"; //copied from de-de
$text['label-destination']['de-ch'] = "Ziel"; //copied from de-de
$text['label-destination']['de-de'] = "Ziel";
$text['label-destination']['es-cl'] = "Destino";
$text['label-destination']['es-mx'] = "Destino"; //copied from es-cl
$text['label-destination']['fr-ca'] = "Destination"; //copied from fr-fr
$text['label-destination']['fr-fr'] = "Destination";
$text['label-destination']['he-il'] = "";
$text['label-destination']['it-it'] = "Destinazione";
$text['label-destination']['nl-nl'] = "";
$text['label-destination']['pl-pl'] = "Numer docelowy";
$text['label-destination']['pt-br'] = "Número de destino";
$text['label-destination']['pt-pt'] = "Destino";
$text['label-destination']['ro-ro'] = "";
$text['label-destination']['ru-ru'] = "Назначение";
$text['label-destination']['sv-se'] = "Destination";
$text['label-destination']['uk-ua'] = "Номер";

$text['label-edit-note']['en-us'] = "Block calls from a number. Edit the name and enable/disable below.";
$text['label-edit-note']['en-gb'] = "Block calls from a number. Edit the name and enable/disable below.";
$text['label-edit-note']['ar-eg'] = "";
$text['label-edit-note']['de-at'] = "Anrufe von einer Rufnummer sperren. Bearbeiten Sie den Namen und aktivieren/deaktivieren Sie diesen unten."; //copied from de-de
$text['label-edit-note']['de-ch'] = "Anrufe von einer Rufnummer sperren. Bearbeiten Sie den Namen und aktivieren/deaktivieren Sie diesen unten."; //copied from de-de
$text['label-edit-note']['de-de'] = "Anrufe von einer Rufnummer sperren. Bearbeiten Sie den Namen und aktivieren/deaktivieren Sie diesen unten.";
$text['label-edit-note']['el-gr'] = "Απόρριψη κλήσεων από ένα αριθμό. Τροποποιήστε το όνομα και (απ)ενεργοποιήστε το παρακάτω.";
$text['label-edit-note']['es-cl'] = "Bloquea llamadas desde un número. Edite el nombre y active/desactive abajo.";
$text['label-edit-note']['es-mx'] = "Bloquea llamadas desde un número. Edite el nombre y active/desactive abajo."; //copied from es-cl
$text['label-edit-note']['fr-ca'] = "Bloquer les appels à partir d'un numéro. Vérifiez le nom et activez/désactivez ci-dessous."; //copied from fr-fr
$text['label-edit-note']['fr-fr'] = "Bloquer les appels à partir d'un numéro. vérifiez le nom et activez/désactivez ci-dessous.";
$text['label-edit-note']['he-il'] = "";
$text['label-edit-note']['it-it'] = "Blocca le chiamate da un numero. Inserire il nome e abilitare/disabilitare qui sotto.";
$text['label-edit-note']['nl-nl'] = "Blokkeer oproepen van een nummer. Pas de naam aan en (de)aktiveer hieronder.";
$text['label-edit-note']['pl-pl'] = "Blokowanie połączeń z danego numeru. Edytuj nazwę i włącz/wyłącz poniżej.";
$text['label-edit-note']['pt-br'] = "Bloquear chamadas a partir de um número. Edite o nome e ative ou desative";
$text['label-edit-note']['pt-pt'] = "Bloquear chamadas a partir de um número. Edite o nome e active/desactive.";
$text['label-edit-note']['ro-ro'] = "Blocați apelurile de la un număr. Editați numele și activați/dezactivați mai jos.";
$text['label-edit-note']['ru-ru'] = "Блокировать вызовы от номера. Отредактируйте имя и включено/выключено ниже.";
$text['label-edit-note']['sv-se'] = "Blockera samtal från nummer. Editera namn och Aktiv/Inaktiv nedan.";
$text['label-edit-note']['uk-ua'] = "Блокувати дзвінки з номера. Змініть ім'я і включіть/відключіть нижче.";

$text['label-edit-edit']['en-us'] = "Call Block";
$text['label-edit-edit']['en-gb'] = "Call Block";
$text['label-edit-edit']['ar-eg'] = "";
$text['label-edit-edit']['de-at'] = "Sperrlisten"; //copied from de-de
$text['label-edit-edit']['de-ch'] = "Sperrlisten"; //copied from de-de
$text['label-edit-edit']['de-de'] = "Sperrlisten";
$text['label-edit-edit']['el-gr'] = "Απόρριψη Κλήσεων";
$text['label-edit-edit']['es-cl'] = "Bloqueo de llamada";
$text['label-edit-edit']['es-mx'] = "Bloqueo de llamada"; //copied from es-cl
$text['label-edit-edit']['fr-ca'] = "Filtrage d'appel"; //copied from fr-fr
$text['label-edit-edit']['fr-fr'] = "Filtrage d'appel";
$text['label-edit-edit']['he-il'] = "חסימת שיחה";
$text['label-edit-edit']['it-it'] = "Blocco Chiamate";
$text['label-edit-edit']['nl-nl'] = "Oproep blokkade";
$text['label-edit-edit']['pl-pl'] = "Blokowanie rozmów";
$text['label-edit-edit']['pt-br'] = "Bloqueio de chamadas";
$text['label-edit-edit']['pt-pt'] = "Bloqueio de Chamadas";
$text['label-edit-edit']['ro-ro'] = "Blocare apel";
$text['label-edit-edit']['ru-ru'] = "Черный список";
$text['label-edit-edit']['sv-se'] = "Blockera Samtal";
$text['label-edit-edit']['uk-ua'] = "Блокування дзвінків";

$text['label-edit-add']['en-us'] = "Call Block";
$text['label-edit-add']['en-gb'] = "Call Block";
$text['label-edit-add']['ar-eg'] = "حظر المكالمات";
$text['label-edit-add']['de-at'] = "Sperrlisten"; //copied from de-de
$text['label-edit-add']['de-ch'] = "Sperrlisten"; //copied from de-de
$text['label-edit-add']['de-de'] = "Sperrlisten";
$text['label-edit-add']['el-gr'] = "Λίστα Απόρριψης";
$text['label-edit-add']['es-cl'] = "Agregar bloqueo de llamada";
$text['label-edit-add']['es-mx'] = "Agregar bloqueo de llamada"; //copied from es-cl
$text['label-edit-add']['fr-ca'] = "Ajouter au filtrage d'appels"; //copied from fr-fr
$text['label-edit-add']['fr-fr'] = "Ajouter filtrage d'appel";
$text['label-edit-add']['he-il'] = "חסימת שיחה";
$text['label-edit-add']['it-it'] = "Blocco Chiamate";
$text['label-edit-add']['nl-nl'] = "Oproep blokkade";
$text['label-edit-add']['pl-pl'] = "Blokowaie rozmów";
$text['label-edit-add']['pt-br'] = "Adicionar bloqueio de chamadas";
$text['label-edit-add']['pt-pt'] = "Adicionar Bloqueio de Chamadas";
$text['label-edit-add']['ro-ro'] = "Blocare apel";
$text['label-edit-add']['ru-ru'] = "Черный список";
$text['label-edit-add']['sv-se'] = "Blockera Samtal";
$text['label-edit-add']['uk-ua'] = "Блокування дзвінків";

$text['label-duration']['en-us'] = "Duration";
$text['label-duration']['en-gb'] = "Duration";
$text['label-duration']['ar-eg'] = "المدة";
$text['label-duration']['de-at'] = "Dauer"; //copied from de-de
$text['label-duration']['de-ch'] = "Dauer"; //copied from de-de
$text['label-duration']['de-de'] = "Dauer";
$text['label-duration']['el-gr'] = "Διάρκεια";
$text['label-duration']['es-cl'] = "Duración";
$text['label-duration']['es-mx'] = "Duración"; //copied from es-cl
$text['label-duration']['fr-ca'] = "Durée"; //copied from fr-fr
$text['label-duration']['fr-fr'] = "Durée";
$text['label-duration']['he-il'] = "משך השיחה";
$text['label-duration']['it-it'] = "Durata";
$text['label-duration']['nl-nl'] = "Duur";
$text['label-duration']['pl-pl'] = "Czas trwania";
$text['label-duration']['pt-br'] = "Duração"; //copied from pt-pt
$text['label-duration']['pt-pt'] = "Duração";
$text['label-duration']['ro-ro'] = "Durată";
$text['label-duration']['ru-ru'] = "Длительность";
$text['label-duration']['sv-se'] = "Samtalstid";
$text['label-duration']['uk-ua'] = "Тривалість";

$text['label-delete-complete']['en-us'] = "Delete Complete";
$text['label-delete-complete']['en-gb'] = "Delete Complete";
$text['label-delete-complete']['ar-eg'] = "اكتمال المسح";
$text['label-delete-complete']['de-at'] = "Erfolgreich gelöscht"; //copied from de-de
$text['label-delete-complete']['de-ch'] = "Erfolgreich gelöscht"; //copied from de-de
$text['label-delete-complete']['de-de'] = "Erfolgreich gelöscht";
$text['label-delete-complete']['el-gr'] = "Η διαγραφή ολοκληρώθηκε";
$text['label-delete-complete']['es-cl'] = "Eliminar Completo";
$text['label-delete-complete']['es-mx'] = "Eliminar Completo"; //copied from es-cl
$text['label-delete-complete']['fr-ca'] = "Supprimé"; //copied from fr-fr
$text['label-delete-complete']['fr-fr'] = "Supprimé";
$text['label-delete-complete']['he-il'] = "המחיקה הושלמה";
$text['label-delete-complete']['it-it'] = "Cancellazione Completata";
$text['label-delete-complete']['nl-nl'] = "Verwijderen gereed";
$text['label-delete-complete']['pl-pl'] = "Usunięto poprawnie";
$text['label-delete-complete']['pt-br'] = "Remoção efetuada";
$text['label-delete-complete']['pt-pt'] = "Remoção Efectuada";
$text['label-delete-complete']['ro-ro'] = "Ștergere completă";
$text['label-delete-complete']['ru-ru'] = "Удаление завершено";
$text['label-delete-complete']['sv-se'] = "Borttagning Klar";
$text['label-delete-complete']['uk-ua'] = "Видалено";

$text['label-date-added']['en-us'] = "Date Added";
$text['label-date-added']['en-gb'] = "Date Added";
$text['label-date-added']['ar-eg'] = "تم اضافة التاريخ";
$text['label-date-added']['de-at'] = "Datum hinzugefügt"; //copied from de-de
$text['label-date-added']['de-ch'] = "Datum hinzugefügt"; //copied from de-de
$text['label-date-added']['de-de'] = "Datum hinzugefügt";
$text['label-date-added']['el-gr'] = "Η ημερομηνία προστέθηκε";
$text['label-date-added']['es-cl'] = "Fecha de ingreso";
$text['label-date-added']['es-mx'] = "Fecha de ingreso"; //copied from es-cl
$text['label-date-added']['fr-ca'] = "Date d'ajout"; //copied from fr-fr
$text['label-date-added']['fr-fr'] = "Date d'ajout";
$text['label-date-added']['he-il'] = "התאריך נוסף";
$text['label-date-added']['it-it'] = "Data Aggiunta";
$text['label-date-added']['nl-nl'] = "Datum toegevoegd";
$text['label-date-added']['pl-pl'] = "Dodano datę";
$text['label-date-added']['pt-br'] = "Data adicionada"; //copied from pt-pt
$text['label-date-added']['pt-pt'] = "Data adicionada";
$text['label-date-added']['ro-ro'] = "Data adăugării";
$text['label-date-added']['ru-ru'] = "Дата добавления";
$text['label-date-added']['sv-se'] = "Datum Tillagt";
$text['label-date-added']['uk-ua'] = "Додано";

$text['label-count']['en-us'] = "Count";
$text['label-count']['en-gb'] = "Count";
$text['label-count']['ar-eg'] = "";
$text['label-count']['de-at'] = "Zähler"; //copied from de-de
$text['label-count']['de-ch'] = "Zähler"; //copied from de-de
$text['label-count']['de-de'] = "Zähler";
$text['label-count']['el-gr'] = "Μετρητής";
$text['label-count']['es-cl'] = "Conteo";
$text['label-count']['es-mx'] = "Conteo"; //copied from es-cl
$text['label-count']['fr-ca'] = "Nombre d'appels"; //copied from fr-fr
$text['label-count']['fr-fr'] = "Nombre d'appels";
$text['label-count']['he-il'] = "";
$text['label-count']['it-it'] = "Conteggio";
$text['label-count']['nl-nl'] = "Aantal";
$text['label-count']['pl-pl'] = "Wyliczenie";
$text['label-count']['pt-br'] = "Contagem"; //copied from pt-pt
$text['label-count']['pt-pt'] = "Contagem";
$text['label-count']['ro-ro'] = "";
$text['label-count']['ru-ru'] = "Количество";
$text['label-count']['sv-se'] = "Räkna";
$text['label-count']['uk-ua'] = "Кількість";

$text['label-called']['en-us'] = "Called";
$text['label-called']['en-gb'] = "Called";
$text['label-called']['ar-eg'] = "تم الأتصال علي";
$text['label-called']['de-at'] = "Anruf"; //copied from de-de
$text['label-called']['de-ch'] = "Anruf"; //copied from de-de
$text['label-called']['de-de'] = "Anruf";
$text['label-called']['el-gr'] = "Η κλήση πραγματοποιήθηκε";
$text['label-called']['es-cl'] = "Llamó";
$text['label-called']['es-mx'] = "Llamó"; //copied from es-cl
$text['label-called']['fr-ca'] = "Appelé"; //copied from fr-fr
$text['label-called']['fr-fr'] = "Appelé";
$text['label-called']['he-il'] = "Opgeroepen";
$text['label-called']['it-it'] = "Chiamato";
$text['label-called']['nl-nl'] = "Aangeroepen";
$text['label-called']['pl-pl'] = "Zadzwoniono";
$text['label-called']['pt-br'] = "Chamada";
$text['label-called']['pt-pt'] = "Chamado";
$text['label-called']['ro-ro'] = "Sunat";
$text['label-called']['ru-ru'] = "Направление";
$text['label-called']['sv-se'] = "Ringdes";
$text['label-called']['uk-ua'] = "Дзвінок здійснено";

$text['label-busy']['en-us'] = "Busy";
$text['label-busy']['en-gb'] = "Busy";
$text['label-busy']['ar-eg'] = "مشغول";
$text['label-busy']['de-at'] = "Besetzt"; //copied from de-de
$text['label-busy']['de-ch'] = "Besetzt"; //copied from de-de
$text['label-busy']['de-de'] = "Besetzt";
$text['label-busy']['el-gr'] = "Κατειλημμένο";
$text['label-busy']['es-cl'] = "Ocupado";
$text['label-busy']['es-mx'] = "Ocupado"; //copied from es-cl
$text['label-busy']['fr-ca'] = "Occupé"; //copied from fr-fr
$text['label-busy']['fr-fr'] = "Occupé";
$text['label-busy']['he-il'] = "תפוס";
$text['label-busy']['it-it'] = "Occupato";
$text['label-busy']['nl-nl'] = "Bezet";
$text['label-busy']['pl-pl'] = "Zajęty";
$text['label-busy']['pt-br'] = "Ocupado"; //copied from pt-pt
$text['label-busy']['pt-pt'] = "Ocupado";
$text['label-busy']['ro-ro'] = "Ocupat";
$text['label-busy']['ru-ru'] = "Занято";
$text['label-busy']['sv-se'] = "Upptagen";
$text['label-busy']['uk-ua'] = "Зайнято";

$text['label-hold']['en-us'] = "Hold";
$text['label-hold']['en-gb'] = "Hold";
$text['label-hold']['ar-eg'] = "";
$text['label-hold']['de-at'] = "Halten"; //copied from de-de
$text['label-hold']['de-ch'] = "Halten"; //copied from de-de
$text['label-hold']['de-de'] = "Halten";
$text['label-hold']['el-gr'] = "Αναμονή";
$text['label-hold']['es-cl'] = "";
$text['label-hold']['es-mx'] = "";
$text['label-hold']['fr-ca'] = "Attente";
$text['label-hold']['fr-fr'] = "Attente";
$text['label-hold']['he-il'] = "";
$text['label-hold']['it-it'] = "In attesa";
$text['label-hold']['nl-nl'] = "Aanhouden";
$text['label-hold']['pl-pl'] = "";
$text['label-hold']['pt-br'] = "Espera"; //copied from pt-pt
$text['label-hold']['pt-pt'] = "Espera";
$text['label-hold']['ro-ro'] = "";
$text['label-hold']['ru-ru'] = "Удержание";
$text['label-hold']['sv-se'] = "Vänt";
$text['label-hold']['uk-ua'] = "";

$text['label-voicemail']['en-us'] = "Voicemail";
$text['label-voicemail']['en-gb'] = "Voicemail";
$text['label-voicemail']['ar-eg'] = "";
$text['label-voicemail']['de-at'] = "Mailbox"; //copied from de-de
$text['label-voicemail']['de-ch'] = "Mailbox"; //copied from de-de
$text['label-voicemail']['de-de'] = "Mailbox";
$text['label-voicemail']['el-gr'] = "Φωνοκιβώτιο";
$text['label-voicemail']['es-cl'] = "Correo de Voz";
$text['label-voicemail']['es-mx'] = "Correo de Voz"; //copied from es-cl
$text['label-voicemail']['fr-ca'] = "Messagerie vocale"; //copied from fr-fr
$text['label-voicemail']['fr-fr'] = "Messagerie vocale";
$text['label-voicemail']['he-il'] = "תא קולי";
$text['label-voicemail']['it-it'] = "Voicemail";
$text['label-voicemail']['nl-nl'] = "Opname";
$text['label-voicemail']['pl-pl'] = "Poczta głosowa";
$text['label-voicemail']['pt-br'] = "Correio de voz";
$text['label-voicemail']['pt-pt'] = "Correio de Voz";
$text['label-voicemail']['ro-ro'] = "";
$text['label-voicemail']['ru-ru'] = "Голосовая почта";
$text['label-voicemail']['sv-se'] = "Röstbrevlåda";
$text['label-voicemail']['uk-ua'] = "Голосова пошта";

$text['label-add-note']['en-us'] = "Block calls from a number. Either select a number from the list above or enter the number, name and enable below.";
$text['label-add-note']['en-gb'] = "Block calls from a number. Either select a number from the list above or enter the number, name and enable below.";
$text['label-add-note']['ar-eg'] = "";
$text['label-add-note']['de-at'] = "Anrufe einer Rufnummer sperren. Wählen Sie eine Nummer von der Liste oder geben Sie eine Nummer und einen Name ein. Aktivieren Sie die Sperrliste unten."; //copied from de-de
$text['label-add-note']['de-ch'] = "Anrufe einer Rufnummer sperren. Wählen Sie eine Nummer von der Liste oder geben Sie eine Nummer und einen Name ein. Aktivieren Sie die Sperrliste unten."; //copied from de-de
$text['label-add-note']['de-de'] = "Anrufe einer Rufnummer sperren. Wählen Sie eine Nummer von der Liste oder geben Sie eine Nummer und einen Name ein. Aktivieren Sie die Sperrliste unten.";
$text['label-add-note']['el-gr'] = "Απόρριψη κλήσεων από ένα αριθμό. Επιλέξτε από την παρακάτω λίστα ή εισάγετε ένα αριθμό, όνομα και την ενεργοποίηση παρακάτω";
$text['label-add-note']['es-cl'] = "Bloquea llamadas desde un número. Puede elegir un número de la lista de arriba o ingresar el n&uacute, nombre y activarlo abajo.";
$text['label-add-note']['es-mx'] = "Bloquea llamadas desde un número. Puede elegir un número de la lista de arriba o ingresar el n&uacute, nombre y activarlo abajo."; //copied from es-cl
$text['label-add-note']['fr-ca'] = "Bloquer les appels à partir d'un numéro. Choisissez un numéro dans liste ou entrez un numéro, nom et activez ci-dessous."; //copied from fr-fr
$text['label-add-note']['fr-fr'] = "Bloquer les appels à partir d'un numéro. Choisissez un numéro dans liste ou entrez un numéro, nom et activez ci-dessous.";
$text['label-add-note']['he-il'] = "";
$text['label-add-note']['it-it'] = "Blocca le chiamate da un numero. Seleziona un numero dalla lista sovrastante o inserisci il numero, il nome e l'abilitazione qui sotto.";
$text['label-add-note']['nl-nl'] = "Blokkeer oproepen van een nummer. Of select het nummer van de bovenstaande lijst, of voer het nummer, de naam en aktivering hieronder.";
$text['label-add-note']['pl-pl'] = "Blokowanie połączeń z danego numeru. Wybierz numer z powyższej listy j lub wpisz numer, nazwę i załącz poniżej.";
$text['label-add-note']['pt-br'] = "Bloquear chamadas a partir de um número. Selecione um número a partir da lista indicada ou insira um número e um nome em seguida ative";
$text['label-add-note']['pt-pt'] = "Bloquear chamadas a partir de um número. Seleccione um número a partir da lista indicada ou introduza um número, nome e active.";
$text['label-add-note']['ro-ro'] = "";
$text['label-add-note']['ru-ru'] = "Блокировка вызовов от номера. Выберите номер из списка выше либо введите его самостоятельно, имя и включите ниже.";
$text['label-add-note']['sv-se'] = "Blockera samtal från ett nummer. Välj antingen ett nummer från listan ovan eller fyll i nummer, namn och aktivera nedan.";
$text['label-add-note']['uk-ua'] = "Блокувати дзвінки з номера. Або вибрати номер зі списку вище або введіть номер, ім'я і включити нижче.";

$text['label-add-complete']['en-us'] = "Add Complete";
$text['label-add-complete']['en-gb'] = "Add Complete";
$text['label-add-complete']['ar-eg'] = "تمت الأضافة";
$text['label-add-complete']['de-at'] = "Erfolgreich hinzugefügt"; //copied from de-de
$text['label-add-complete']['de-ch'] = "Erfolgreich hinzugefügt"; //copied from de-de
$text['label-add-complete']['de-de'] = "Erfolgreich hinzugefügt";
$text['label-add-complete']['el-gr'] = "Η προσθήκη ολοκληρώθηκε";
$text['label-add-complete']['es-cl'] = "Agregar Completo";
$text['label-add-complete']['es-mx'] = "Agregar Completo"; //copied from es-cl
$text['label-add-complete']['fr-ca'] = "Ajouté"; //copied from fr-fr
$text['label-add-complete']['fr-fr'] = "Ajouté";
$text['label-add-complete']['he-il'] = "הוספה הושלמה";
$text['label-add-complete']['it-it'] = "Inserimento Completato";
$text['label-add-complete']['nl-nl'] = "Toevoegen gereed";
$text['label-add-complete']['pl-pl'] = "Dodano poprawnie";
$text['label-add-complete']['pt-br'] = "Criação efetuada ";
$text['label-add-complete']['pt-pt'] = "Adição Efectuada";
$text['label-add-complete']['ro-ro'] = "Adăugare completă";
$text['label-add-complete']['ru-ru'] = "Добавление завершено";
$text['label-add-complete']['sv-se'] = "Tillagd";
$text['label-add-complete']['uk-ua'] = "Додано";

$text['label-action']['en-us'] = "Action";
$text['label-action']['en-gb'] = "Action";
$text['label-action']['ar-eg'] = "";
$text['label-action']['de-at'] = "Aktion"; //copied from de-de
$text['label-action']['de-ch'] = "Aktion"; //copied from de-de
$text['label-action']['de-de'] = "Aktion";
$text['label-action']['el-gr'] = "Ενέργεια";
$text['label-action']['es-cl'] = "Acción";
$text['label-action']['es-mx'] = "Acción"; //copied from es-cl
$text['label-action']['fr-ca'] = "Action"; //copied from fr-fr
$text['label-action']['fr-fr'] = "Action";
$text['label-action']['he-il'] = "פעולה";
$text['label-action']['it-it'] = "Azione";
$text['label-action']['nl-nl'] = "Actie";
$text['label-action']['pl-pl'] = "Operacja";
$text['label-action']['pt-br'] = "Ação";
$text['label-action']['pt-pt'] = "Acção";
$text['label-action']['ro-ro'] = "Acțiune";
$text['label-action']['ru-ru'] = "Действие";
$text['label-action']['sv-se'] = "Åtgärd";
$text['label-action']['uk-ua'] = "Дія";

$text['label-direction']['en-us'] = "Direction";
$text['label-direction']['en-gb'] = "Direction";
$text['label-direction']['ar-eg'] = "";
$text['label-direction']['de-at'] = "Richtung"; //copied from de-de
$text['label-direction']['de-ch'] = "Richtung"; //copied from de-de
$text['label-direction']['de-de'] = "Richtung";
$text['label-direction']['es-cl'] = "Dirección";
$text['label-direction']['es-mx'] = "Dirección"; //copied from es-cl
$text['label-direction']['fr-ca'] = "Direction"; //copied from fr-fr
$text['label-direction']['fr-fr'] = "Direction";
$text['label-direction']['he-il'] = "";
$text['label-direction']['it-it'] = "Direzione";
$text['label-direction']['nl-nl'] = "";
$text['label-direction']['pl-pl'] = "Kierunek";
$text['label-direction']['pt-br'] = "Direção";
$text['label-direction']['pt-pt'] = "Direcção";
$text['label-direction']['ro-ro'] = "";
$text['label-direction']['ru-ru'] = "Направление";
$text['label-direction']['sv-se'] = "Riktning";
$text['label-direction']['uk-ua'] = "Напрям";

$text['description-direction']['en-us'] = "Select the direction of the calls to block.";
$text['description-direction']['en-gb'] = "Select the direction of the calls to block.";
$text['description-direction']['ar-eg'] = "Select the direction of the calls to block.";
$text['description-direction']['de-at'] = "Select the direction of the calls to block.";
$text['description-direction']['de-ch'] = "Select the direction of the calls to block.";
$text['description-direction']['de-de'] = "Select the direction of the calls to block.";
$text['description-direction']['el-gr'] = "Select the direction of the calls to block.";
$text['description-direction']['es-cl'] = "Select the direction of the calls to block.";
$text['description-direction']['es-mx'] = "Select the direction of the calls to block.";
$text['description-direction']['fr-ca'] = "Sélectionnez la direction des appels à bloquer.";
$text['description-direction']['fr-fr'] = "Sélectionnez la direction des appels à bloquer.";
$text['description-direction']['he-il'] = "Select the direction of the calls to block.";
$text['description-direction']['it-it'] = "Select the direction of the calls to block.";
$text['description-direction']['nl-nl'] = "Select the direction of the calls to block.";
$text['description-direction']['pl-pl'] = "Select the direction of the calls to block.";
$text['description-direction']['pt-br'] = "Select the direction of the calls to block.";
$text['description-direction']['pt-pt'] = "Select the direction of the calls to block.";
$text['description-direction']['ro-ro'] = "Select the direction of the calls to block.";
$text['description-direction']['ru-ru'] = "Select the direction of the calls to block.";
$text['description-direction']['sv-se'] = "Select the direction of the calls to block.";
$text['description-direction']['uk-ua'] = "Select the direction of the calls to block.";

$text['description-call_block_name']['en-us'] = "Enter the Caller ID Name to block.";
$text['description-call_block_name']['en-gb'] = "Enter the Caller ID Name to block.";
$text['description-call_block_name']['ar-eg'] = "";
$text['description-call_block_name']['de-at'] = "";
$text['description-call_block_name']['de-ch'] = "";
$text['description-call_block_name']['de-de'] = "";
$text['description-call_block_name']['el-gr'] = "Εισάγετε την ταυτότητα καλούντος προς απόρριψη.";
$text['description-call_block_name']['es-cl'] = "";
$text['description-call_block_name']['es-mx'] = "";
$text['description-call_block_name']['fr-ca'] = "Entrez le nom d'affichage à bloquer.";
$text['description-call_block_name']['fr-fr'] = "Entrez le nom d'affichage à bloquer.";
$text['description-call_block_name']['he-il'] = "";
$text['description-call_block_name']['it-it'] = "";
$text['description-call_block_name']['nl-nl'] = "Voer het te blokkeren CID Naam in.";
$text['description-call_block_name']['pl-pl'] = "";
$text['description-call_block_name']['pt-br'] = "";
$text['description-call_block_name']['pt-pt'] = "";
$text['description-call_block_name']['ro-ro'] = "";
$text['description-call_block_name']['ru-ru'] = "";
$text['description-call_block_name']['sv-se'] = "";
$text['description-call_block_name']['uk-ua'] = "";

$text['description-country_code']['en-us'] = "Enter the Country Code prefix.";
$text['description-country_code']['en-gb'] = "Enter the Country Code prefix.";
$text['description-country_code']['ar-eg'] = "";
$text['description-country_code']['de-at'] = ""; //copied from de-de
$text['description-country_code']['de-ch'] = ""; //copied from de-de
$text['description-country_code']['de-de'] = "";
$text['description-country_code']['es-cl'] = "";
$text['description-country_code']['es-mx'] = ""; //copied from es-cl
$text['description-country_code']['fr-ca'] = "Entrez le préfixe de destination."; //copied from fr-fr
$text['description-country_code']['fr-fr'] = "Entrez le préfixe de destination.";
$text['description-country_code']['he-il'] = "";
$text['description-country_code']['it-it'] = "";
$text['description-country_code']['nl-nl'] = "Voer de bestemming prefix in.";
$text['description-country_code']['pl-pl'] = "";
$text['description-country_code']['pt-br'] = "Insira o prefixo do destino.";
$text['description-country_code']['pt-pt'] = "";
$text['description-country_code']['ro-ro'] = "";
$text['description-country_code']['ru-ru'] = "";
$text['description-country_code']['sv-se'] = "";
$text['description-country_code']['uk-ua'] = "";

$text['description-call_block_number']['en-us'] = "Enter the Country Code and Caller ID Number to block.";
$text['description-call_block_number']['en-gb'] = "Enter the Country Code and Caller ID Number to block.";
$text['description-call_block_number']['ar-eg'] = "";
$text['description-call_block_number']['de-at'] = "";
$text['description-call_block_number']['de-ch'] = "";
$text['description-call_block_number']['de-de'] = "";
$text['description-call_block_number']['el-gr'] = "Εισάγετε την ταυτότητα καλούντος προς απόρριψη.";
$text['description-call_block_number']['es-cl'] = "";
$text['description-call_block_number']['es-mx'] = "";
$text['description-call_block_number']['fr-ca'] = "Entrez le numéro d'affichage à bloquer.";
$text['description-call_block_number']['fr-fr'] = "Entrez le numéro d'affichage à bloquer.";
$text['description-call_block_number']['he-il'] = "";
$text['description-call_block_number']['it-it'] = "";
$text['description-call_block_number']['nl-nl'] = "Voer het te blokkeren CID Nummer in.";
$text['description-call_block_number']['pl-pl'] = "";
$text['description-call_block_number']['pt-br'] = "";
$text['description-call_block_number']['pt-pt'] = "";
$text['description-call_block_number']['ro-ro'] = "";
$text['description-call_block_number']['ru-ru'] = "";
$text['description-call_block_number']['sv-se'] = "";
$text['description-call_block_number']['uk-ua'] = "";

$text['description-extension']['en-us'] = "Select the extension to be affected.";
$text['description-extension']['en-gb'] = "Select the extension to be affected.";
$text['description-extension']['ar-eg'] = "";
$text['description-extension']['de-at'] = "";
$text['description-extension']['de-ch'] = "";
$text['description-extension']['de-de'] = "";
$text['description-extension']['el-gr'] = "Επιλέξτε το εσωτερικό προς απόρριψη.";
$text['description-extension']['es-cl'] = "";
$text['description-extension']['es-mx'] = "";
$text['description-extension']['fr-ca'] = "Choissizez le poste sur lequel cette règle sera appliquée.";
$text['description-extension']['fr-fr'] = "Choissizez le poste sur lequel cette règle sera appliquée.";
$text['description-extension']['he-il'] = "";
$text['description-extension']['it-it'] = "";
$text['description-extension']['nl-nl'] = "Selecteer het toestel dat geblokkeerd moet worden.";
$text['description-extension']['pl-pl'] = "";
$text['description-extension']['pt-br'] = "";
$text['description-extension']['pt-pt'] = "";
$text['description-extension']['ro-ro'] = "";
$text['description-extension']['ru-ru'] = "";
$text['description-extension']['sv-se'] = "";
$text['description-extension']['uk-ua'] = "";

$text['description-enable']['en-us'] = "Set to true to enable call blocking for this number.";
$text['description-enable']['en-gb'] = "Set to true to enable call blocking for this number.";
$text['description-enable']['ar-eg'] = "";
$text['description-enable']['de-at'] = "Setzen Sie auf An, um die Sperrung für diese Nummer zu aktivieren."; //copied from de-de
$text['description-enable']['de-ch'] = "Setzen Sie auf An, um die Sperrung für diese Nummer zu aktivieren."; //copied from de-de
$text['description-enable']['de-de'] = "Setzen Sie auf An, um die Sperrung für diese Nummer zu aktivieren.";
$text['description-enable']['el-gr'] = "Επιλέξτε το για να ενεργοποιήστε την απόρριψη κλήσεων για τον αριθμό αυτό.";
$text['description-enable']['es-cl'] = "Seleccione verdadero para activar el bloqueo de llamadas desde este número.";
$text['description-enable']['es-mx'] = "Seleccione verdadero para activar el bloqueo de llamadas desde este número."; //copied from es-cl
$text['description-enable']['fr-ca'] = "Choisir oui pour activer le filtrage d'appel pour ce numéro."; //copied from fr-fr
$text['description-enable']['fr-fr'] = "Choisir oui pour activer le filtrage d'appel pour ce numéro.";
$text['description-enable']['he-il'] = "";
$text['description-enable']['it-it'] = "Selezionare 'true' per abilitare il blocco chiamate da questo numero.";
$text['description-enable']['nl-nl'] = "Aktiveer om de blokkade aan te zetten voor dit nummer.";
$text['description-enable']['pl-pl'] = "Ustaw wartość na TAK, aby umożliwić blokowanie tego numeru ";
$text['description-enable']['pt-br'] = "Escolha 'sim' para ativar o bloqueio  de chamadas para este número.";
$text['description-enable']['pt-pt'] = "Escolha 'sim' para activar o bloqueio de chamadas para este número.";
$text['description-enable']['ro-ro'] = "";
$text['description-enable']['ru-ru'] = "Выберите 'Да', чтобы блокировать вызовы с данного номера.";
$text['description-enable']['sv-se'] = "Välj Sann för att blockera detta nummer.";
$text['description-enable']['uk-ua'] = "Виберіть 'Так', щоб блокувати дзвінки з даного номера.";

$text['description-call-block']['en-us'] = "A list of numbers from which to block calls.";
$text['description-call-block']['en-gb'] = "A list of numbers from which to block calls.";
$text['description-call-block']['ar-eg'] = "";
$text['description-call-block']['de-at'] = "Eine Liste von Nummern die gesperrt werden sollen."; //copied from de-de
$text['description-call-block']['de-ch'] = "Eine Liste von Nummern die gesperrt werden sollen."; //copied from de-de
$text['description-call-block']['de-de'] = "Eine Liste von Nummern die gesperrt werden sollen.";
$text['description-call-block']['el-gr'] = "Μια λίστα από αριθμούς προς απόρριψη εισερχομένων κλήσεων.";
$text['description-call-block']['es-cl'] = "Un listado de números desde los cuales se bloquean las llamadas";
$text['description-call-block']['es-mx'] = "Un listado de números desde los cuales se bloquean las llamadas"; //copied from es-cl
$text['description-call-block']['fr-ca'] = "Une liste de numéros à partir de laquelle vous pouvez bloquer les appels."; //copied from fr-fr
$text['description-call-block']['fr-fr'] = "Une liste de numéros depuis lesquels vous pouvez bloquer les appels";
$text['description-call-block']['he-il'] = "";
$text['description-call-block']['it-it'] = "Una lista di numeri per cui è possibile bloccare le chiamate.";
$text['description-call-block']['nl-nl'] = "Een lijst van nummers die geblokkeerd moeten worden.";
$text['description-call-block']['pl-pl'] = "Lista numerów, z których rozmowy są blokowane.";
$text['description-call-block']['pt-br'] = "Uma lista de números que deseja bloquear as chamadas";
$text['description-call-block']['pt-pt'] = "Uma lista de números que deseje bloquear as chamadas";
$text['description-call-block']['ro-ro'] = "";
$text['description-call-block']['ru-ru'] = "Список номеров, с которых блокируются вызовы.";
$text['description-call-block']['sv-se'] = "En lista med nummer för blockering av samtal.";
$text['description-call-block']['uk-ua'] = "Список номерів, з яких блокуються дзвінки.";

$text['description-action']['en-us'] = "Set an action for calls from this number.";
$text['description-action']['en-gb'] = "Set an action for calls from this number.";
$text['description-action']['ar-eg'] = "";
$text['description-action']['de-at'] = "Wählen Sie eine Aktion für Anrufe von dieser Nummer."; //copied from de-de
$text['description-action']['de-ch'] = "Wählen Sie eine Aktion für Anrufe von dieser Nummer."; //copied from de-de
$text['description-action']['de-de'] = "Wählen Sie eine Aktion für Anrufe von dieser Nummer.";
$text['description-action']['el-gr'] = "Ορίστε ενέργεια για τις κλήσεις από αυτόν τον αριθμό.";
$text['description-action']['es-cl'] = "Configurar una acción para llamadas desde este número.";
$text['description-action']['es-mx'] = "Configurar una acción para llamadas desde este número."; //copied from es-cl
$text['description-action']['fr-ca'] = "Choisir une action pour les appels de ce numéro."; //copied from fr-fr
$text['description-action']['fr-fr'] = "Choisir une action pour les appels de ce numéro.";
$text['description-action']['he-il'] = "";
$text['description-action']['it-it'] = "Seleziona un'azione per le chiamate da questo numero.";
$text['description-action']['nl-nl'] = "Stel actie voor oproepen vanaf dit nummer in.";
$text['description-action']['pl-pl'] = "Ustaw co zrobić w przypadku polaczeń z tego numeru.";
$text['description-action']['pt-br'] = "Escolha uma ação para chamadas reailzadas por este número.";
$text['description-action']['pt-pt'] = "Escolha uma acção para chamadas com origem neste número.";
$text['description-action']['ro-ro'] = "";
$text['description-action']['ru-ru'] = "Установите действие для вызовов с данного номера.";
$text['description-action']['sv-se'] = "Välj en aktion för samtal från detta nummer.";
$text['description-action']['uk-ua'] = "Встановіть дію для дзвінків з цього номера.";

$text['confirm-block']['en-us'] = "Do you really want to block this?";
$text['confirm-block']['en-gb'] = "Do you really want to block this?";
$text['confirm-block']['ar-eg'] = "Do you really want to block this?";
$text['confirm-block']['de-at'] = "Do you really want to block this?";
$text['confirm-block']['de-ch'] = "Do you really want to block this?";
$text['confirm-block']['de-de'] = "Do you really want to block this?";
$text['confirm-block']['el-gr'] = "Do you really want to block this?";
$text['confirm-block']['es-cl'] = "Do you really want to block this?";
$text['confirm-block']['es-mx'] = "Do you really want to block this?";
$text['confirm-block']['fr-ca'] = "Voulez-vous vraiment bloquer ceci?";
$text['confirm-block']['fr-fr'] = "Voulez-vous vraiment bloquer ceci?";
$text['confirm-block']['he-il'] = "Do you really want to block this?";
$text['confirm-block']['it-it'] = "Do you really want to block this?";
$text['confirm-block']['nl-nl'] = "Do you really want to block this?";
$text['confirm-block']['pl-pl'] = "Do you really want to block this?";
$text['confirm-block']['pt-br'] = "Do you really want to block this?";
$text['confirm-block']['pt-pt'] = "Do you really want to block this?";
$text['confirm-block']['ro-ro'] = "Do you really want to block this?";
$text['confirm-block']['ru-ru'] = "Do you really want to block this?";
$text['confirm-block']['sv-se'] = "Do you really want to block this?";
$text['confirm-block']['uk-ua'] = "Do you really want to block this?";
$text['confirm-block']['tr-tr'] = "Do you really want to block this?";

$text['button-block']['en-us'] = "Block";
$text['button-block']['en-gb'] = "Block";
$text['button-block']['ar-eg'] = "Block";
$text['button-block']['de-at'] = "Block";
$text['button-block']['de-ch'] = "Block";
$text['button-block']['de-de'] = "Block";
$text['button-block']['el-gr'] = "Block";
$text['button-block']['es-cl'] = "Block";
$text['button-block']['es-mx'] = "Block";
$text['button-block']['fr-ca'] = "Bloquer";
$text['button-block']['fr-fr'] = "Bloquer";
$text['button-block']['he-il'] = "Block";
$text['button-block']['it-it'] = "Block";
$text['button-block']['nl-nl'] = "Block";
$text['button-block']['pl-pl'] = "Block";
$text['button-block']['pt-br'] = "Block";
$text['button-block']['pt-pt'] = "Block";
$text['button-block']['ro-ro'] = "Block";
$text['button-block']['ru-ru'] = "Block";
$text['button-block']['sv-se'] = "Block";
$text['button-block']['uk-ua'] = "Block";
$text['button-block']['tr-tr'] = "Block";

?>
