<?php
#This file was last reorganized on 19th of September 2017 08:54:24 AM UTC

$text['title-databases']['en-us'] = "Databases";
$text['title-databases']['en-gb'] = "Databases";
$text['title-databases']['ar-eg'] = "قواعد البيانات";
$text['title-databases']['de-at'] = "Datenbanken"; //copied from de-de
$text['title-databases']['de-ch'] = "Datenbanken"; //copied from de-de
$text['title-databases']['de-de'] = "Datenbanken";
$text['title-databases']['es-cl'] = "Bases de datos";
$text['title-databases']['es-mx'] = "Bases de datos"; //copied from es-cl
$text['title-databases']['fr-ca'] = "Bases de données"; //copied from fr-fr
$text['title-databases']['fr-fr'] = "Bases de données";
$text['title-databases']['he-il'] = "";
$text['title-databases']['it-it'] = "Databases";
$text['title-databases']['nl-nl'] = "";
$text['title-databases']['pl-pl'] = "Bazy danych";
$text['title-databases']['pt-br'] = "Banco de dados";
$text['title-databases']['pt-pt'] = "Bases de Dados";
$text['title-databases']['ro-ro'] = "";
$text['title-databases']['ru-ru'] = "Базы данных";
$text['title-databases']['sv-se'] = "Databaser";
$text['title-databases']['uk-ua'] = "Бази даних";

$text['title-database-edit']['en-us'] = "Database Edit";
$text['title-database-edit']['en-gb'] = "Database Edit";
$text['title-database-edit']['ar-eg'] = "تعديل قاعدة البيانات";
$text['title-database-edit']['de-at'] = "Datenbank editieren"; //copied from de-de
$text['title-database-edit']['de-ch'] = "Datenbank editieren"; //copied from de-de
$text['title-database-edit']['de-de'] = "Datenbank editieren";
$text['title-database-edit']['es-cl'] = "Editar base de datos";
$text['title-database-edit']['es-mx'] = "Editar base de datos"; //copied from es-cl
$text['title-database-edit']['fr-ca'] = "Editer la Base de données"; //copied from fr-fr
$text['title-database-edit']['fr-fr'] = "Editer la Base de données";
$text['title-database-edit']['he-il'] = "";
$text['title-database-edit']['it-it'] = "Modifica Database";
$text['title-database-edit']['nl-nl'] = "";
$text['title-database-edit']['pl-pl'] = "Edytuj bazę danych";
$text['title-database-edit']['pt-br'] = "Editar banco de dados";
$text['title-database-edit']['pt-pt'] = "Editar a Base de Dados";
$text['title-database-edit']['ro-ro'] = "";
$text['title-database-edit']['ru-ru'] = "Изменение базы данных";
$text['title-database-edit']['sv-se'] = "Ändra Databas";
$text['title-database-edit']['uk-ua'] = "Редагування бази даних";

$text['title-database-add']['en-us'] = "Database Add";
$text['title-database-add']['en-gb'] = "Database Add";
$text['title-database-add']['ar-eg'] = "إضافة قاعدة بيانات";
$text['title-database-add']['de-at'] = "Datenbank hinzufügen"; //copied from de-de
$text['title-database-add']['de-ch'] = "Datenbank hinzufügen"; //copied from de-de
$text['title-database-add']['de-de'] = "Datenbank hinzufügen";
$text['title-database-add']['es-cl'] = "Agregar Base de Datos";
$text['title-database-add']['es-mx'] = "Agregar Base de Datos"; //copied from es-cl
$text['title-database-add']['fr-ca'] = "Ajouter une Base de données"; //copied from fr-fr
$text['title-database-add']['fr-fr'] = "Ajouter une Base de données";
$text['title-database-add']['he-il'] = "";
$text['title-database-add']['it-it'] = "Inserisci Database";
$text['title-database-add']['nl-nl'] = "";
$text['title-database-add']['pl-pl'] = "Dodaj bazę danych";
$text['title-database-add']['pt-br'] = "Adicionar banco de dados";
$text['title-database-add']['pt-pt'] = "Adicionar Base de Dados";
$text['title-database-add']['ro-ro'] = "";
$text['title-database-add']['ru-ru'] = "Добавить базу данных";
$text['title-database-add']['sv-se'] = "Lägg Till Databas";
$text['title-database-add']['uk-ua'] = "Додавання бази даних";

$text['label-username']['en-us'] = "Username";
$text['label-username']['en-gb'] = "Username";
$text['label-username']['ar-eg'] = "اسم المستخدم";
$text['label-username']['de-at'] = "Benutzername"; //copied from de-de
$text['label-username']['de-ch'] = "Benutzername"; //copied from de-de
$text['label-username']['de-de'] = "Benutzername";
$text['label-username']['es-cl'] = "Nombre de usuario";
$text['label-username']['es-mx'] = "Nombre de usuario"; //copied from es-cl
$text['label-username']['fr-ca'] = "Utilisateur"; //copied from fr-fr
$text['label-username']['fr-fr'] = "Utilisateur";
$text['label-username']['he-il'] = "";
$text['label-username']['it-it'] = "Username";
$text['label-username']['nl-nl'] = "";
$text['label-username']['pl-pl'] = "Użytkownik";
$text['label-username']['pt-br'] = "Nome do Usuário";
$text['label-username']['pt-pt'] = "Utilizador";
$text['label-username']['ro-ro'] = "";
$text['label-username']['ru-ru'] = "Имя пользователя";
$text['label-username']['sv-se'] = "Användarnamn";
$text['label-username']['uk-ua'] = "Ім’я користувача";

$text['label-port']['en-us'] = "Port";
$text['label-port']['en-gb'] = "Port";
$text['label-port']['ar-eg'] = "منفذ";
$text['label-port']['de-at'] = "Port"; //copied from de-de
$text['label-port']['de-ch'] = "Port"; //copied from de-de
$text['label-port']['de-de'] = "Port";
$text['label-port']['es-cl'] = "Puerto";
$text['label-port']['es-mx'] = "Puerto"; //copied from es-cl
$text['label-port']['fr-ca'] = "Port"; //copied from fr-fr
$text['label-port']['fr-fr'] = "Port";
$text['label-port']['he-il'] = "";
$text['label-port']['it-it'] = "Porta";
$text['label-port']['nl-nl'] = "";
$text['label-port']['pl-pl'] = "Port";
$text['label-port']['pt-br'] = "Porta";
$text['label-port']['pt-pt'] = "Porto";
$text['label-port']['ro-ro'] = "";
$text['label-port']['ru-ru'] = "Порт";
$text['label-port']['sv-se'] = "Port";
$text['label-port']['uk-ua'] = "Порт";

$text['label-path']['en-us'] = "Path";
$text['label-path']['en-gb'] = "Path";
$text['label-path']['ar-eg'] = "";
$text['label-path']['de-at'] = "Pfad"; //copied from de-de
$text['label-path']['de-ch'] = "Pfad"; //copied from de-de
$text['label-path']['de-de'] = "Pfad";
$text['label-path']['es-cl'] = "Ruta";
$text['label-path']['es-mx'] = "Ruta"; //copied from es-cl
$text['label-path']['fr-ca'] = "Chemin"; //copied from fr-fr
$text['label-path']['fr-fr'] = "Chemin";
$text['label-path']['he-il'] = "";
$text['label-path']['it-it'] = "Percorso";
$text['label-path']['nl-nl'] = "";
$text['label-path']['pl-pl'] = "Ścieżka";
$text['label-path']['pt-br'] = "Caminho"; //copied from pt-pt
$text['label-path']['pt-pt'] = "Caminho";
$text['label-path']['ro-ro'] = "";
$text['label-path']['ru-ru'] = "Путь";
$text['label-path']['sv-se'] = "Sökväg";
$text['label-path']['uk-ua'] = "Шлях";

$text['label-host']['en-us'] = "Host";
$text['label-host']['en-gb'] = "Host";
$text['label-host']['ar-eg'] = "مضيف";
$text['label-host']['de-at'] = "Host"; //copied from de-de
$text['label-host']['de-ch'] = "Host"; //copied from de-de
$text['label-host']['de-de'] = "Host";
$text['label-host']['es-cl'] = "Host";
$text['label-host']['es-mx'] = "Host"; //copied from es-cl
$text['label-host']['fr-ca'] = "Hôte"; //copied from fr-fr
$text['label-host']['fr-fr'] = "Hôte";
$text['label-host']['he-il'] = "";
$text['label-host']['it-it'] = "Host";
$text['label-host']['nl-nl'] = "";
$text['label-host']['pl-pl'] = "Host";
$text['label-host']['pt-br'] = "Servidor"; //copied from pt-pt
$text['label-host']['pt-pt'] = "Máquina";
$text['label-host']['ro-ro'] = "";
$text['label-host']['ru-ru'] = "Хост";
$text['label-host']['sv-se'] = "Värd";
$text['label-host']['uk-ua'] = "Хост";

$text['label-driver']['en-us'] = "Driver";
$text['label-driver']['en-gb'] = "Driver";
$text['label-driver']['ar-eg'] = "";
$text['label-driver']['de-at'] = "Treiber"; //copied from de-de
$text['label-driver']['de-ch'] = "Treiber"; //copied from de-de
$text['label-driver']['de-de'] = "Treiber";
$text['label-driver']['es-cl'] = "Controlador";
$text['label-driver']['es-mx'] = "Controlador"; //copied from es-cl
$text['label-driver']['fr-ca'] = "Driver"; //copied from fr-fr
$text['label-driver']['fr-fr'] = "Driver";
$text['label-driver']['he-il'] = "";
$text['label-driver']['it-it'] = "Driver";
$text['label-driver']['nl-nl'] = "";
$text['label-driver']['pl-pl'] = "Sterownik";
$text['label-driver']['pt-br'] = "Driver"; //copied from pt-pt
$text['label-driver']['pt-pt'] = "Driver";
$text['label-driver']['ro-ro'] = "";
$text['label-driver']['ru-ru'] = "Драйвер";
$text['label-driver']['sv-se'] = "Drivrutin";
$text['label-driver']['uk-ua'] = "Драйвер";

$text['header-databases']['en-us'] = "Databases";
$text['header-databases']['en-gb'] = "Databases";
$text['header-databases']['ar-eg'] = "قواعد البيانات";
$text['header-databases']['de-at'] = "Datenbanken"; //copied from de-de
$text['header-databases']['de-ch'] = "Datenbanken"; //copied from de-de
$text['header-databases']['de-de'] = "Datenbanken";
$text['header-databases']['es-cl'] = "Bases de datos";
$text['header-databases']['es-mx'] = "Bases de datos"; //copied from es-cl
$text['header-databases']['fr-ca'] = "Bases de données"; //copied from fr-fr
$text['header-databases']['fr-fr'] = "Bases de données";
$text['header-databases']['he-il'] = "";
$text['header-databases']['it-it'] = "Database";
$text['header-databases']['nl-nl'] = "";
$text['header-databases']['pl-pl'] = "Bazy danych";
$text['header-databases']['pt-br'] = "Banco de dados";
$text['header-databases']['pt-pt'] = "Bases de Dados";
$text['header-databases']['ro-ro'] = "";
$text['header-databases']['ru-ru'] = "Базы данных";
$text['header-databases']['sv-se'] = "Databaser";
$text['header-databases']['uk-ua'] = "Бази даних";

$text['header-database-edit']['en-us'] = "Database Edit";
$text['header-database-edit']['en-gb'] = "Database Edit";
$text['header-database-edit']['ar-eg'] = "تعديل قاعدة البيانات";
$text['header-database-edit']['de-at'] = "Datenbanken bearbeiten"; //copied from de-de
$text['header-database-edit']['de-ch'] = "Datenbanken bearbeiten"; //copied from de-de
$text['header-database-edit']['de-de'] = "Datenbanken bearbeiten";
$text['header-database-edit']['es-cl'] = "Editar base de datos";
$text['header-database-edit']['es-mx'] = "Editar base de datos"; //copied from es-cl
$text['header-database-edit']['fr-ca'] = "Editer la Base de données"; //copied from fr-fr
$text['header-database-edit']['fr-fr'] = "Editer la Base de données";
$text['header-database-edit']['he-il'] = "";
$text['header-database-edit']['it-it'] = "Modifica Database";
$text['header-database-edit']['nl-nl'] = "";
$text['header-database-edit']['pl-pl'] = "Edytuj bazę danych";
$text['header-database-edit']['pt-br'] = "Editar o banco de dados";
$text['header-database-edit']['pt-pt'] = "Editar a Base de Dados";
$text['header-database-edit']['ro-ro'] = "";
$text['header-database-edit']['ru-ru'] = "Изменение базы данных";
$text['header-database-edit']['sv-se'] = "Ändra Databas";
$text['header-database-edit']['uk-ua'] = "Редагування бази даних";

$text['header-database-add']['en-us'] = "Database Add";
$text['header-database-add']['en-gb'] = "Database Add";
$text['header-database-add']['ar-eg'] = "إضافة قاعدة بيانات";
$text['header-database-add']['de-at'] = "Datenbanken hinzufügen"; //copied from de-de
$text['header-database-add']['de-ch'] = "Datenbanken hinzufügen"; //copied from de-de
$text['header-database-add']['de-de'] = "Datenbanken hinzufügen";
$text['header-database-add']['es-cl'] = "Agregar Base de Datos";
$text['header-database-add']['es-mx'] = "Agregar Base de Datos"; //copied from es-cl
$text['header-database-add']['fr-ca'] = "Ajouter une Base de données"; //copied from fr-fr
$text['header-database-add']['fr-fr'] = "Ajouter une Base de données";
$text['header-database-add']['he-il'] = "";
$text['header-database-add']['it-it'] = "Inserisci Database";
$text['header-database-add']['nl-nl'] = "";
$text['header-database-add']['pl-pl'] = "Dodaj bazę danych";
$text['header-database-add']['pt-br'] = "Adicionar banco de dados";
$text['header-database-add']['pt-pt'] = "Adicionar Base de Dados";
$text['header-database-add']['ro-ro'] = "";
$text['header-database-add']['ru-ru'] = "Добавить базу данных";
$text['header-database-add']['sv-se'] = "Lägg Till Databas";
$text['header-database-add']['uk-ua'] = "Додавання бази даних";

$text['description-username']['en-us'] = "Enter the database username.";
$text['description-username']['en-gb'] = "Enter the database username.";
$text['description-username']['ar-eg'] = "أدخل اسم المستخدم هنا";
$text['description-username']['de-at'] = "Geben Sie den Datenbank Benutzernamen an."; //copied from de-de
$text['description-username']['de-ch'] = "Geben Sie den Datenbank Benutzernamen an."; //copied from de-de
$text['description-username']['de-de'] = "Geben Sie den Datenbank Benutzernamen an.";
$text['description-username']['es-cl'] = "Ingrese el nombre de usuario de la base de datos.";
$text['description-username']['es-mx'] = "Ingrese el nombre de usuario de la base de datos."; //copied from es-cl
$text['description-username']['fr-ca'] = "Entrer le nom d'utilisateur de la Base de données."; //copied from fr-fr
$text['description-username']['fr-fr'] = "Entrer le nom d'utilisateur de la Base de données.";
$text['description-username']['he-il'] = "";
$text['description-username']['it-it'] = "Inserire lo username del database.";
$text['description-username']['nl-nl'] = "";
$text['description-username']['pl-pl'] = "Wprowadź nazwę użytkownika";
$text['description-username']['pt-br'] = "Insira o nome do usuário";
$text['description-username']['pt-pt'] = "Introduza o utilizador da base de dados.";
$text['description-username']['ro-ro'] = "";
$text['description-username']['ru-ru'] = "Введите имя пользователя базы данных.";
$text['description-username']['sv-se'] = "Ange databasen användarnamn här.";
$text['description-username']['uk-ua'] = "Введіть ім’я користувача бази даних";

$text['description-type']['en-us'] = "Select the database type.";
$text['description-type']['en-gb'] = "Select the database type.";
$text['description-type']['ar-eg'] = "إختر نوع قاعدة البيانات";
$text['description-type']['de-at'] = "Wählen Sie den Datenbank Typ."; //copied from de-de
$text['description-type']['de-ch'] = "Wählen Sie den Datenbank Typ."; //copied from de-de
$text['description-type']['de-de'] = "Wählen Sie den Datenbank Typ.";
$text['description-type']['es-cl'] = "Seleccione el tipo de base de datos";
$text['description-type']['es-mx'] = "Seleccione el tipo de base de datos"; //copied from es-cl
$text['description-type']['fr-ca'] = "Choisir le type de Base de données."; //copied from fr-fr
$text['description-type']['fr-fr'] = "Choisir le type de Base de données.";
$text['description-type']['he-il'] = "";
$text['description-type']['it-it'] = "Selezionare il tipo di database.";
$text['description-type']['nl-nl'] = "";
$text['description-type']['pl-pl'] = "Wprowadź rodzaj bazy danych";
$text['description-type']['pt-br'] = "Escolha o tipo de base de dados.";
$text['description-type']['pt-pt'] = "Escolha o tipo de base de dados.";
$text['description-type']['ro-ro'] = "";
$text['description-type']['ru-ru'] = "Выберите тип базы данных.";
$text['description-type']['sv-se'] = "Välj databastyp";
$text['description-type']['uk-ua'] = "Виберіть тип бази даних";

$text['description-port']['en-us'] = "Enter the port number.";
$text['description-port']['en-gb'] = "Enter the port number.";
$text['description-port']['ar-eg'] = "أدخل رقم المنفذ";
$text['description-port']['de-at'] = "Geben Sie die Port Nummer an."; //copied from de-de
$text['description-port']['de-ch'] = "Geben Sie die Port Nummer an."; //copied from de-de
$text['description-port']['de-de'] = "Geben Sie die Port Nummer an.";
$text['description-port']['es-cl'] = "Ingrese el número del puerto.";
$text['description-port']['es-mx'] = "Ingrese el número del puerto."; //copied from es-cl
$text['description-port']['fr-ca'] = "Entrer le numéro de port."; //copied from fr-fr
$text['description-port']['fr-fr'] = "Entrer le numéro de port.";
$text['description-port']['he-il'] = "";
$text['description-port']['it-it'] = "Inserire il numero di porta.";
$text['description-port']['nl-nl'] = "";
$text['description-port']['pl-pl'] = "Wprowadź numer portu";
$text['description-port']['pt-br'] = "Insira o número da porta.";
$text['description-port']['pt-pt'] = "Introduza o número do porto.";
$text['description-port']['ro-ro'] = "";
$text['description-port']['ru-ru'] = "Введите номер порта.";
$text['description-port']['sv-se'] = "Ange portnummer";
$text['description-port']['uk-ua'] = "Введіть номер порта";

$text['description-path']['en-us'] = "Enter the database file path (SQLite only).";
$text['description-path']['en-gb'] = "Enter the database file path (SQLite only).";
$text['description-path']['ar-eg'] = "";
$text['description-path']['de-at'] = "Geben Sie den Datenbank Pfad an (nur für SQLite)."; //copied from de-de
$text['description-path']['de-ch'] = "Geben Sie den Datenbank Pfad an (nur für SQLite)."; //copied from de-de
$text['description-path']['de-de'] = "Geben Sie den Datenbank Pfad an (nur für SQLite).";
$text['description-path']['es-cl'] = "Ingrese la ruta al archivo de datos (solo SQLite).";
$text['description-path']['es-mx'] = "Ingrese la ruta al archivo de datos (solo SQLite)."; //copied from es-cl
$text['description-path']['fr-ca'] = "Entrer le chemin du fichier Base de données (Spécifique SQLite)."; //copied from fr-fr
$text['description-path']['fr-fr'] = "Entrer le chemin du fichier Base de données (Spécifique SQLite).";
$text['description-path']['he-il'] = "";
$text['description-path']['it-it'] = "Inserire il percorso del file database (solo SQLite).";
$text['description-path']['nl-nl'] = "";
$text['description-path']['pl-pl'] = "Wprowadź ścieżkę do pliku bazy danych (tylko SQLite)";
$text['description-path']['pt-br'] = "Insira o caminho da base de dados (SQLite)";
$text['description-path']['pt-pt'] = "Introduza o caminho da base de dados (apenas SQLite)";
$text['description-path']['ro-ro'] = "";
$text['description-path']['ru-ru'] = "Введите путь к файлу базы данных (только для SQLite).";
$text['description-path']['sv-se'] = "Ange databasens sökväg (gäller endast SQLite).";
$text['description-path']['uk-ua'] = "Вкажіть шлях до файлу бази даних (тільки SQLite).";

$text['description-password']['en-us'] = "Enter the database password.";
$text['description-password']['en-gb'] = "Enter the database password.";
$text['description-password']['ar-eg'] = "أدخل الرقم السري الخاص بقاعدة البيانات";
$text['description-password']['de-at'] = "Geben Sie das Datenbank Passwort ein."; //copied from de-de
$text['description-password']['de-ch'] = "Geben Sie das Datenbank Passwort ein."; //copied from de-de
$text['description-password']['de-de'] = "Geben Sie das Datenbank Passwort ein.";
$text['description-password']['es-cl'] = "Ingrese la contraseña de la base de datos.";
$text['description-password']['es-mx'] = "Ingrese la contraseña de la base de datos."; //copied from es-cl
$text['description-password']['fr-ca'] = "Entrer le mot de passe pour la Base de données."; //copied from fr-fr
$text['description-password']['fr-fr'] = "Entrer le mot de passe pour la Base de données.";
$text['description-password']['he-il'] = "";
$text['description-password']['it-it'] = "Inserire la password del database.";
$text['description-password']['nl-nl'] = "";
$text['description-password']['pl-pl'] = "Wpisz hasło";
$text['description-password']['pt-br'] = "Entre com a senha da base de dados.";
$text['description-password']['pt-pt'] = "Introduza a palavra-chave da base de dados.";
$text['description-password']['ro-ro'] = "";
$text['description-password']['ru-ru'] = "Введите пароль базы данных.";
$text['description-password']['sv-se'] = "Ange databasens lösenord.";
$text['description-password']['uk-ua'] = "Введіть пароль бази даних.";

$text['description-name']['en-us'] = "Enter the database name.";
$text['description-name']['en-gb'] = "Enter the database name.";
$text['description-name']['ar-eg'] = "أدخل إسم قاعدة البيانات";
$text['description-name']['de-at'] = "Geben Sie den Namen der Datenbank an"; //copied from de-de
$text['description-name']['de-ch'] = "Geben Sie den Namen der Datenbank an"; //copied from de-de
$text['description-name']['de-de'] = "Geben Sie den Namen der Datenbank an";
$text['description-name']['es-cl'] = "Ingrese el nombre de la base de datos.";
$text['description-name']['es-mx'] = "Ingrese el nombre de la base de datos."; //copied from es-cl
$text['description-name']['fr-ca'] = "Entrer le nom de la Base de données."; //copied from fr-fr
$text['description-name']['fr-fr'] = "Entrer le nom de la Base de données.";
$text['description-name']['he-il'] = "";
$text['description-name']['it-it'] = "Inserire il nome del database.";
$text['description-name']['nl-nl'] = "";
$text['description-name']['pl-pl'] = "Wprowadź nazwę bazy danych.";
$text['description-name']['pt-br'] = "Insira o nome da base de dados.";
$text['description-name']['pt-pt'] = "Introduza o nome da base de dados.";
$text['description-name']['ro-ro'] = "";
$text['description-name']['ru-ru'] = "Введите имя базы данных.";
$text['description-name']['sv-se'] = "Ange databasens namn.";
$text['description-name']['uk-ua'] = "Введіть ім'я бази даних.";

$text['description-host']['en-us'] = "Enter the host name.";
$text['description-host']['en-gb'] = "Enter the host name.";
$text['description-host']['ar-eg'] = "أدخل إسم المضيف";
$text['description-host']['de-at'] = "Geben Sie den Host Namen ein."; //copied from de-de
$text['description-host']['de-ch'] = "Geben Sie den Host Namen ein."; //copied from de-de
$text['description-host']['de-de'] = "Geben Sie den Host Namen ein.";
$text['description-host']['es-cl'] = "Ingrese el nombre de host";
$text['description-host']['es-mx'] = "Ingrese el nombre de host"; //copied from es-cl
$text['description-host']['fr-ca'] = "Entrer le nom de l'hôte."; //copied from fr-fr
$text['description-host']['fr-fr'] = "Entrer le nom de l'hôte.";
$text['description-host']['he-il'] = "";
$text['description-host']['it-it'] = "Inserire il nome host.";
$text['description-host']['nl-nl'] = "";
$text['description-host']['pl-pl'] = "Wprowadź nazwę hosta.";
$text['description-host']['pt-br'] = "Insira o nome do servidor.";
$text['description-host']['pt-pt'] = "Introduza o nome da máquina.";
$text['description-host']['ro-ro'] = "";
$text['description-host']['ru-ru'] = "Введите имя хоста.";
$text['description-host']['sv-se'] = "Ange värdnamnet";
$text['description-host']['uk-ua'] = "Введіть ім'я хоста.";

$text['description-driver']['en-us'] = "Select the database driver.";
$text['description-driver']['en-gb'] = "Select the database driver.";
$text['description-driver']['ar-eg'] = "";
$text['description-driver']['de-at'] = "Wählen Sie den Datenbank Treiber."; //copied from de-de
$text['description-driver']['de-ch'] = "Wählen Sie den Datenbank Treiber."; //copied from de-de
$text['description-driver']['de-de'] = "Wählen Sie den Datenbank Treiber.";
$text['description-driver']['es-cl'] = "Seleccione un controlador de base de datos.";
$text['description-driver']['es-mx'] = "Seleccione un controlador de base de datos."; //copied from es-cl
$text['description-driver']['fr-ca'] = "Choisir le driver de la Base de données."; //copied from fr-fr
$text['description-driver']['fr-fr'] = "Choisir le driver de la Base de données.";
$text['description-driver']['he-il'] = "";
$text['description-driver']['it-it'] = "Selezionare il driver del database.";
$text['description-driver']['nl-nl'] = "";
$text['description-driver']['pl-pl'] = "Wybierz sterownik bazy danych.";
$text['description-driver']['pt-br'] = "Escolha o driver do banco de dados"; //copied from pt-pt
$text['description-driver']['pt-pt'] = "Escolha o driver da base de dados";
$text['description-driver']['ro-ro'] = "";
$text['description-driver']['ru-ru'] = "Выберите драйвер базы данных.";
$text['description-driver']['sv-se'] = "Välj databas drivrutin.";
$text['description-driver']['uk-ua'] = "Виберіть драйвер бази даних.";

$text['description-databases']['en-us'] = "Database information.";
$text['description-databases']['en-gb'] = "Database information.";
$text['description-databases']['ar-eg'] = "بيانات قاعدة البيانات";
$text['description-databases']['de-at'] = "Datenbank Information."; //copied from de-de
$text['description-databases']['de-ch'] = "Datenbank Information."; //copied from de-de
$text['description-databases']['de-de'] = "Datenbank Information.";
$text['description-databases']['es-cl'] = "Información de bases de datos.";
$text['description-databases']['es-mx'] = "Información de bases de datos."; //copied from es-cl
$text['description-databases']['fr-ca'] = "Informations sur les bases de données"; //copied from fr-fr
$text['description-databases']['fr-fr'] = "Informations sur les bases de données";
$text['description-databases']['he-il'] = "";
$text['description-databases']['it-it'] = "Informazioni Database.";
$text['description-databases']['nl-nl'] = "";
$text['description-databases']['pl-pl'] = "Informacje o bazie danych.";
$text['description-databases']['pt-br'] = "Informações sobre o banco de dados";
$text['description-databases']['pt-pt'] = "Informação da Base de Dados";
$text['description-databases']['ro-ro'] = "";
$text['description-databases']['ru-ru'] = "Информация о базе данных.";
$text['description-databases']['sv-se'] = "Databasinformation.";
$text['description-databases']['uk-ua'] = "Інформація про базу даних.";

$text['description-database-edit']['en-us'] = "Database connection information.";
$text['description-database-edit']['en-gb'] = "Database connection information.";
$text['description-database-edit']['ar-eg'] = "بيانات الإتصال الخاص بقاعدة البيانات";
$text['description-database-edit']['de-at'] = "Datenbank Verbindungs Information."; //copied from de-de
$text['description-database-edit']['de-ch'] = "Datenbank Verbindungs Information."; //copied from de-de
$text['description-database-edit']['de-de'] = "Datenbank Verbindungs Information.";
$text['description-database-edit']['es-cl'] = "Información de conexión a base de datos.";
$text['description-database-edit']['es-mx'] = "Información de conexión a base de datos."; //copied from es-cl
$text['description-database-edit']['fr-ca'] = "Informations de connexion à la Base"; //copied from fr-fr
$text['description-database-edit']['fr-fr'] = "Informations de connexion à la Base";
$text['description-database-edit']['he-il'] = "";
$text['description-database-edit']['it-it'] = "Informazioni connessione Database.";
$text['description-database-edit']['nl-nl'] = "";
$text['description-database-edit']['pl-pl'] = "Informacje o połączeniach z bazą danych.";
$text['description-database-edit']['pt-br'] = "Informações da conexão ao banco de dados";
$text['description-database-edit']['pt-pt'] = "Informação da ligação à base de dados.";
$text['description-database-edit']['ro-ro'] = "";
$text['description-database-edit']['ru-ru'] = "Информация о соединении с базой данных.";
$text['description-database-edit']['sv-se'] = "Information om Databasanslutning";
$text['description-database-edit']['uk-ua'] = "інформація про підключення до бази даних.";

$text['description-database-add']['en-us'] = "Database connection information.";
$text['description-database-add']['en-gb'] = "Database connection information.";
$text['description-database-add']['ar-eg'] = "بيانات الإتصال الخاص بقاعدة البيانات";
$text['description-database-add']['de-at'] = "Datenbank Verbindungs Information."; //copied from de-de
$text['description-database-add']['de-ch'] = "Datenbank Verbindungs Information."; //copied from de-de
$text['description-database-add']['de-de'] = "Datenbank Verbindungs Information.";
$text['description-database-add']['es-cl'] = "Información de conexión a base de datos.";
$text['description-database-add']['es-mx'] = "Información de conexión a base de datos."; //copied from es-cl
$text['description-database-add']['fr-ca'] = "Informations de connexion à la Base."; //copied from fr-fr
$text['description-database-add']['fr-fr'] = "Informations de connexion à la Base.";
$text['description-database-add']['he-il'] = "";
$text['description-database-add']['it-it'] = "Informazioni connessione Database.";
$text['description-database-add']['nl-nl'] = "";
$text['description-database-add']['pl-pl'] = "Informacje o połączeniach z bazą danych.";
$text['description-database-add']['pt-br'] = "Informações da conexão ao banco de dados";
$text['description-database-add']['pt-pt'] = "Informação da ligação à base de dados.";
$text['description-database-add']['ro-ro'] = "";
$text['description-database-add']['ru-ru'] = "Информация о соединении с базой данных.";
$text['description-database-add']['sv-se'] = "Information om Databasanslutning";
$text['description-database-add']['uk-ua'] = "інформація про підключення до бази даних.";

?>
