<?php

	//application details
		$apps[$x]['name'] = "Flyingvoice";
		$apps[$x]['uuid'] = "aca95e7b-c46a-4df6-b4f2-1481e876ea8c";
		$apps[$x]['category'] = "Vendor";
		$apps[$x]['subcategory'] = "";
		$apps[$x]['version'] = "1.0";
		$apps[$x]['license'] = "Mozilla Public License 1.1";
		$apps[$x]['url'] = "http://www.fusionpbx.com";
		$apps[$x]['description']['en-us'] = "";
		$apps[$x]['description']['en-gb'] = "";
		$apps[$x]['description']['ar-eg'] = "";
		$apps[$x]['description']['de-at'] = "";
		$apps[$x]['description']['de-ch'] = "";
		$apps[$x]['description']['de-de'] = "";
		$apps[$x]['description']['es-cl'] = "";
		$apps[$x]['description']['es-mx'] = "";
		$apps[$x]['description']['fr-ca'] = "";
		$apps[$x]['description']['fr-fr'] = "";
		$apps[$x]['description']['he-il'] = "";
		$apps[$x]['description']['it-it'] = "";
		$apps[$x]['description']['nl-nl'] = "";
		$apps[$x]['description']['pl-pl'] = "";
		$apps[$x]['description']['pt-br'] = "";
		$apps[$x]['description']['pt-pt'] = "";
		$apps[$x]['description']['ro-ro'] = "";
		$apps[$x]['description']['ru-ru'] = "";
		$apps[$x]['description']['sv-se'] = "";
		$apps[$x]['description']['uk-ua'] = "";

	//default settings
		$y=0;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "d4dc5b68-fb6d-4d31-9e9b-490db1b66147";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_provision_url";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Provisioning URL for Flyingvoice";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "890057f0-d68c-42d2-b0b0-3ebe9874b12f";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_time_zone";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "-5";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Time zone ranges from -11 to +12";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "bc21f16d-a23c-4f3e-ab26-3e676b4f4553";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_time_zone_name";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "United States-Eastern Time";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Time zone name example United States-Mountain Time";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "5466c69f-457c-493e-8a11-d9ba86caf1c7";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_time_format";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "1";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "0-12 Hour, 1-24 Hour";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "4c7f4041-ab1e-4c5c-8e23-080e9a066241";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_date_format";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "3";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "0-WWW MMM DD (default), 1-DD-MMM-YY, 2-YYYY-MM-DD, 3-DD/MM/YYYY, 4-MM/DD/YY, 5-DD MMM YYYY, 6-WWW DD MMM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "39c1b559-18d5-4b23-b0e1-477fdc137507";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_rport";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "1";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Enable or disable the NAT Rport. 0-Disabled (default), 1-Enabled.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "e0e76447-4efe-43bc-b7ba-29911629748e";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_session_timer";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "0";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "SIP Session Timers";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "71184546-0f2f-44b6-8d43-06e632e09363";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_retransmission";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "0";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Retransmission";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "cb8e0cc4-171d-4b1c-990d-4f99e60f9fe7";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_subscribe_mwi";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "0";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "subscribe the message waiting indicator 0-Disabled (default), 1-Enabled";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "2a12d9fe-52e3-4f42-a104-472d7ae57588";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_subscribe_mwi_to_vm";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "1";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Subscribe to the voicemail MWI 0-Disabled (default), 1-Enabled";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "ffc10cd2-295a-40eb-8b66-b0228dbdfd13";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_srtp_encryption";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "0";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "0=Disabled, 1=Optional, 2=Compulsory";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "ce610423-994b-4fe2-81a5-cdcff46b5a69";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_call_waiting";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "1";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Call Waiting 1=enabled 0=disable";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "6fe9f03d-8300-4a1a-91c0-8a44f6a24296";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_direct_pickup_enable";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "1";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Direct Pickup 0-Disabled, 1-Enabled (default)";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "31e87d85-7c25-45ed-8012-29e082c4088f";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_outbound_proxy_fallback_interval";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "3600";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Integer from 0 to 65535";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "f1591ec2-9586-4861-902b-3a12d380be19";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_rfc2543_hold";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "0";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Default 0";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "2a00b1d6-9389-4810-8731-5728ccf628e0";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_trust_ctrl";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "1";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "(0-Disabled;1-Enabled)";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "f730b0c2-6903-455c-81fe-99d2be78c8ba";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_direct_ip_call_enable";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "0";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "0-Disabled, 1-Enabled";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "fc33f376-3d95-4ccc-86d8-38d271924859";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_missed_call_power_led_flash_enable";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "0";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "0-Disabled:power indicator LED is off, 1-Enabled:power indicator LED is solid red";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "6de28537-8f9e-4415-bf1d-5823fc5215b3";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_voice_mail_popup_enable";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "0";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Display Voice Mail Popup";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "bf8dc43e-364f-4f1f-b403-a66f68f4ab5a";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_missed_call_popup_enable";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "0";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Display Missed Call Popup";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "6d87fbc2-b6eb-466c-b0f3-301ec0ec3e3d";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_cid_source";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "2";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "The type of SIP header(s) to carry the caller ID; 0-FROM, 1-PAI 2-PAI-FROM (default), 3-PRID-PAI-FROM, 4-PAI-RPID-FROM, 5-RPID-FROM, 6-Preference";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "21f2b13e-218b-4464-b1c4-38ac2560a0cd";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_dtmf_type";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "1";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "0-INBAND, 1-RFC 2833 (default), 2-SIP INFO, 3-RFC2833 + SIP INFO";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "85fd4e1a-5147-4b17-9293-06e5eaa1fc09";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_sip_listen_port";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "5060";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "5060 default";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "c555d265-38b0-4045-9940-e0e6d8831353";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_url";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "https://server.yourdomain.com/app/flyingvoice/resources/firmware";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Base URL for Flyingvoice Firmware. Download from http://support.flyingvoice.com";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "db7c983e-5a66-4b92-84e2-8699160d340f";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_fip10";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "FIP10-FVUI_V0.5.32.3_202105111814_RC.bin";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the FIP10/FIP10P firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "95918ea8-763b-4f6c-b756-03e6dff55e2a";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_fip11c";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "FIP11C-FVUI_V0.5.32.3_202105111814_RC.bin";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the FIP11C/FIP11CP firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "8c1db35d-0c82-4ab5-af83-3faf22c51778";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_fip12wp";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "FIP12WP-FVUI12_V0.5.7_202012041402_RC.bin";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the FIP12WP firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "1696ac12-8d83-4cde-8d42-3720a7eea665";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_fip13g";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "FIP13G-FVUI_V0.5.32.3_202105111814_RC.bin";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the FIP13G firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "69fe61ff-d21c-4fa9-a6a9-f4ab1cdb4485";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_fip14g";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "FIP14G-FVUI_V0.5.32.3_202105111814_RC.bin";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the FIP14G firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "641db839-f61a-4f09-a5b3-57e907baacb0";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_fip15g";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "FIP15G-FVUI_V0.5.32.3_202105111814_RC.bin";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the FIP15G firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "b53faa9b-62db-407e-8f04-2e38bec9de18";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_fip16";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "FIP16-FVUI16_V0.5.15.4_202102231619_RC.bin";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the FIP16 firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "aca8973f-2825-4c14-85c2-1360664012b1";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_fip16plus";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the FIP16Plus firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "ea26d039-4927-4b52-833e-75643722252d";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_fip15gplus";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the FIP15GPlus firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "0b6da5ab-8b0c-4598-822a-23b0d7906d75";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_P10";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the P10/P/G firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "e28c8ffc-82b9-4c90-8432-cdac3e86904b";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_p10w";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the P10W firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "8fc01356-71e5-11ed-a39b-000c29a55d69";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_p10lte";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the P10lte firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "a02032a8-71e5-11ed-b7ea-000c29a55d69";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_p11";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the P11/P/G firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "3938d3c6-a1da-4214-86d5-d0520b904e60";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_p11w";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the P11W firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "40a6eb43-f15c-4ba4-80c0-71816b493b0c";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_p11lte";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the P11LTE firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "a640adc9-83c6-4072-b20a-7bd6b0d5d81d";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_p20";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the P20/P/G firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "505eb94c-8a74-4f6c-b680-30f0514d286a";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_p20w";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the P20W firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "63a4118b-175c-499a-a775-02762396b385";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_p21";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the P21/P firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "bcce7a02-401f-4c8a-b787-e31f3c45bc58";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_p21w";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the P21W firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "35d73d76-4dc3-4053-9d75-a0ba5512f346";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_p22";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the P22P/G firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "b37e20f8-9317-40d3-b3df-834d42cb3465";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_p23g";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the P23G firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "8ba69e8e-e816-4171-bb8d-f99abe9d9a4f";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_p23gw";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the P23GW firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "6d77d684-c652-43b1-a85b-33fea8379e20";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_p24gw";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the P24GW firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "5a57281e-a285-440d-be27-145b3cebe53b";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_p33";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the P33/P/G firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "727518ee-d00b-4140-a12f-67a5068335f8";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_p53";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the P53 firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "7e0870f7-0a92-4aa5-b191-f0ae1f7f1de4";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_p54";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the P54 firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "eb451f04-539b-451b-b7a6-c14f36f1c7ca";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_p55";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the P55 firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "47ed8de1-cc14-427c-a2be-6022f1099901";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_p57";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the P57 firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "57726aa3-118b-4e53-bade-4cfee9b2cb8e";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_p58";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the P58 firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "3e3e9229-3c3c-40c8-86aa-4b2b9d31ae57";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_p510";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the P510 firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "00759459-942e-4885-8d0d-bfdbdf1df98a";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_i86box";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the i86Box Series firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "77b75510-ec76-4370-b617-3b8652695691";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_imetalbox";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the iMetalBox Series firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "dda30a6f-7698-4bda-bb52-4610736adddc";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_firmware_audiokit";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Filename of the audioKit Series firmware ROM";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "db870a88-0f26-483a-aa81-bc462d29fc26";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_network_vpn_enable";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "1";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "(0-Disabled;1-Enabled)";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "3d32be82-873b-4d7d-92c2-ddb2eb6bd8bd";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_openvpn_url";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "https://replace-this.url/openvpn.tar";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "(URL within 511 characters)";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "73321c8f-1c7d-4569-9c7d-aabea50d3fc6";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_ip_address_mode";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "0";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "IP Address mode 0-ipv4, 1-ipv6, 2-ipv4&ipv6";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "e60da254-993d-45f7-aa30-a83f74160684";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_lldp_enable";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "0";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "LLDP 0-Disabled, 1-Enabled";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "bac5f772-ce1f-4e61-85a9-a409250ffe3c";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_cdp_enable";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "0";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "CDP 0-Disabled, 1-Enabled";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "4f4339c6-9840-490e-8785-38c401d14896";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_dsskey_length";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "0";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "DSS Key Label Length 0-Default, 1-Extended, 2-Mid Range";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "22f735ac-9d5b-4b01-b881-d92fb8b7b6fb";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_feature_key_sync";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "0";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Enable or disable the feature key synchronization; 0-Disabled (default), 1-Enabled";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "1b57b5d5-9ceb-4c0b-a364-41f0c5da85a7";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_predial_autodial";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "0";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Auto dial after digit timeout 0-Disabled (default), 1-Enabled";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "5ed9a8b4-e42f-458a-8678-ea3b1fcdf594";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_remote_phonebook_1_name";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "Personal";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Remote Phonebook Users on Flyingvoice";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "83b5e672-ebf9-4637-8e15-a3c54f09df78";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_remote_phonebook_2_name";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "Global";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Remote Phonebook Groups on Flyingvoice";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "c6c6ed5b-7e5d-4951-84b0-2e0d7ae95503";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_remote_phonebook_3_name";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "Local";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Remote Phonebook Extensions on Flyingvoice";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "faa48558-ef56-4b7a-94e5-ce4d1631ccad";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_remote_phonebook_enable";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "0";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Enable phone to query the contact names from the remote phonebook when receiving incoming calls. 0-Disabled (default), 1-Enabled;";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "deaeacf3-fb38-4f3b-99a4-31fa045f12b2";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_local_directory_enable";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "1";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Enable the Local Directory.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "612d8c27-8926-4023-b9f5-813d08ad3a21";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_ring_text_1";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "1";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Text to map the keywords contained in the Alert-info header.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "56a2ef9a-170f-434c-99f1-0757ee16cd1a";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_ring_text_2";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "2";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Text to map the keywords contained in the Alert-info header.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "139bd035-ef07-41c1-844b-12516c3ba5e3";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_ring_text_3";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "3";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Text to map the keywords contained in the Alert-info header.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "8382a914-d26c-4b02-9c74-dc88c95df4ea";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_ring_text_4";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "4";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Text to map the keywords contained in the Alert-info header.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "a0362d6d-17ec-419f-95c8-ffad1b0b8612";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_ring_text_5";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "5";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Text to map the keywords contained in the Alert-info header.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "6f722052-674f-407d-a075-7a0600d96bde";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_ring_text_6";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "6";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Text to map the keywords contained in the Alert-info header.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "b64db5e7-1393-4fb9-8aeb-10c527ee201c";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_ring_text_7";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "7";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Text to map the keywords contained in the Alert-info header.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "418ed154-2c12-4f74-9d6a-b8ef03630d6e";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_ring_text_8";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "8";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Text to map the keywords contained in the Alert-info header.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "1f649fb8-5e63-44e7-87ab-11bfd50eb49b";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_ring_text_9";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "9";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Text to map the keywords contained in the Alert-info header.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "a08e69f9-b1e1-40f1-84a9-1a046f83d283";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_ring_text_10";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "10";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Text to map the keywords contained in the Alert-info header.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "b7955a2f-c760-4b62-84ef-a4f7acdca47b";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_ring_file_1";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "Ring1.wav";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Ring tone for each text ranges from 1 to 10. The default value 1 stands for Ring1.wav.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "86382dce-b946-47b5-ad45-78afc02cd656";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_ring_file_2";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "Ring2.wav";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Ring tone for each text ranges from 1 to 10. The value 2 stands for Ring2.wav.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "955a2151-d7df-46fa-8fb4-bdc4f2b9ced3";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_ring_file_3";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "Ring3.wav";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Ring tone for each text ranges from 1 to 10. The value 3 stands for Ring3.wav.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "22e2477b-4f86-4147-8c58-164ebd124b83";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_ring_file_4";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "Ring4.wav";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Ring tone for each text ranges from 1 to 10. The value 4 stands for Ring4.wav.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "7f1752b1-fd64-4ddb-b792-ebda08591a6c";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_ring_file_5";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "Ring5.wav";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Ring tone for each text ranges from 1 to 10. The value 5 stands for Ring5.wav.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "e1132c81-deea-4879-93bf-a1c72c5a68a9";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_ring_file_6";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "Ring6.wav";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Ring tone for each text ranges from 1 to 10. The value 6 stands for Ring6.wav.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "ac013695-d637-4b0a-9287-e2d5779d1d4a";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_ring_file_7";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "Ring7.wav";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Ring tone for each text ranges from 1 to 10. The value 7 stands for Ring7.wav.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "e9a81a58-4667-4d90-8c76-53cc826bc543";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_ring_file_8";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "Ring8.wav";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Ring tone for each text ranges from 1 to 10. The value 8 stands for Ring8.wav.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "cb72561b-3fdf-41ba-a30e-17b2bd7fd9b5";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_ring_file_9";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "Ring9.wav";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Ring tone for each text ranges from 1 to 10. The value 9 stands for Ring7.wav.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "814c50cc-1da5-41f4-8a9d-5805e0f060f3";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_ring_file_10";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "Ring10.wav";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Ring tone for each text ranges from 1 to 10. The value 10 stands for Ring8.wav.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "7160edf8-0f88-4679-80fa-1900323df269";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_dsskey_transfer_mode";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "2";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "DSS key transfer mode: 0-Display Number, 1 Attended Transfer, 2 Blind Transfer (default).";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "ddc88401-3f43-4374-b327-747a5d0093a1";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_language_gui";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "The language used in phone interface.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "2960fdcb-4f31-4ca9-94b8-5982bac6214b";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_transfer_semi_attended";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "1";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "0-Disabled, 1-Enabled (default). Enable or disable the transferee to display the missed call prompt when receiving a semi_attended transfer call.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "9c1fa3fa-eaa9-4d81-a012-7d23a5077c7b";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_voice_tone_country";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "United States";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "For example, United States, France, Germany etc.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "88736c5c-df21-4172-90b0-9b9a3555ec21";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_trust_certificates";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Required trusted certificate for provisioning.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "baf1a63a-01d3-44f6-b332-e793af0232f7";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_codec_opus_enable";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set to enable or disable the selected Flyingvoice codec.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "9ef9aabb-e356-4723-830b-dac779a1be1e";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_codec_g723_63_enable";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set to enable or disable the selected Flyingvoice codec.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "cc79e9de-4f89-486e-935e-9d02a574e36c";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_codec_g722_enable";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set to enable or disable the selected Flyingvoice codec.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "c87b1e11-8825-46b4-8baf-d658e127c695";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_codec_g723_53_enable";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set to enable or disable the selected Flyingvoice codec.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "2abb8b58-c00c-4d14-ab42-1dd14b76ffa4";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_codec_g729_enable";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set to enable or disable the selected Flyingvoice codec.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "3858b9cc-d006-4860-8b31-5a827c183cda";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_codec_pcma_enable";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set to enable or disable the selected Flyingvoice codec.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "546a5f92-3887-45ba-ba3a-9cfab55542d8";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_codec_pcmu_enable";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set to enable or disable the selected Flyingvoice codec.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "fa12f54a-7df4-4d00-9dd2-78ad7d3ae2b5";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_codec_ilbc_enable";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set to enable or disable the selected Flyingvoice codec.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "1824fce2-be0b-4299-8293-24a2f2bf0d15";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_codec_g726_32_enable";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set to enable or disable the selected Flyingvoice codec.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "07256172-8d66-4e7d-9f29-6b13cb33b60d";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_codec_opus_priority";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "13";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set to enable or disable the selected Flyingvoice codec.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "5a4d9569-86b8-4dd7-9c9e-e216f547ad08";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_codec_g723_53_priority";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "5";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set to enable or disable the selected Flyingvoice codec.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "df6b8419-aa13-43c5-b83a-0018d94e0faf";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_codec_g729_priority";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "3";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set to enable or disable the selected Flyingvoice codec.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "baab7270-a564-428b-a0bd-15316868ff9c";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_codec_pcmu_priority";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "1";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set to enable or disable the selected Flyingvoice codec.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "90dd21a4-01a5-40c1-9a4e-6ecfc0f484ec";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_codec_pcma_priority";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "2";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set to enable or disable the selected Flyingvoice codec.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "c408e8b2-7120-4484-a595-2071fbc26b42";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_codec_g723_63_priority";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "6";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set to enable or disable the selected Flyingvoice codec.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "e7e5e650-ef8a-466d-b8dd-47438aeaaeda";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_codec_g722_priority";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "4";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set to enable or disable the selected Flyingvoice codec.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "8fdabbb2-883b-45b0-94e2-c3f18a1e0d2f";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_codec_ilbc_priority";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "7";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set to enable or disable the selected Flyingvoice codec.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "1f910548-8d68-4d9e-83e5-93904c805228";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_codec_g726_32_priority";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "10";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set to enable or disable the selected Flyingvoice codec.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "b757b5e0-04e5-45c2-a59c-049bb1df5255";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_usb_record_enable";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "0";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set 1 = ON 0 = OFF.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "804608c3-55b5-432a-a558-20884d7b8d91";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_inter_digit_time";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "4";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "#Configure the time (in seconds) the phone automatically dials out the dialed digits. It ranges from 1 to 14, the default value is 4.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "e7513b07-7226-4e19-8fc4-f5b2a87ce693";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_fwd_allow";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "1";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set 1 = On, 0 = Off";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "5a781ad4-5d7a-4a01-b920-452ff723375d";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_dnd_allow";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "1";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set 1 = On, 0 = off";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "6930a930-daf4-449d-882a-5f8f888bfe45";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_voice_cng";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "1";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set 1 = On (default), 0 = Off";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "0031bdf2-9df0-422f-b54c-e5645cc95fab";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_voice_vad";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "1";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set 1 = On, 0 = Off (default)";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "947c6f97-b4ea-42f1-96d3-9038443f0f83";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_security_default_ssl_method";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "3";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Configures the TLS version to use. 0-TLS 1.0 only, 3-SSL V23 automatic negotiation with the server, 4-TLS 1.1 only, 5-TLS 1.2 only, Default 3";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "1923c1f3-862b-437b-b808-8ad6aa84f970";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_vlan_cos";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Configure the Internet VLAN priority, it ranges from 0 (default) to 7.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "64b8a209-dc1f-40ce-9f1a-0cabb8b8a030";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_vlan_id";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Configure the Internet port VLAN ID, it ranges from 0 to 4094, the default value is 0.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "696e4acc-510f-4b56-850d-f1be10da4980";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_vlan_enable";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Internet port VLAN enable Set 1 = ON 0 = OFF.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "80d0885a-4488-4145-968c-ee98bd83e8e3";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_vlan_pc_cos";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Configure the VLAN PC port priority, it ranges from 0 (default) to 7.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "4aec3d25-9cce-4c78-9bc8-d5a0d0517ace";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_vlan_pc_id";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Configure the PC VLAN ID, it ranges from 0 to 4094, the default value is 1.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "0d4f8dee-209c-4108-a3ef-9e814d027527";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_vlan_pc_enable";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "PC port VLAN enable Set 1 = ON 0 = OFF.";	
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "34c38d01-e419-4640-acf7-c36e3cab091d";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_forward_always_on_code";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "*72";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "98d9de3d-2efe-4c43-88a4-16683f9820c0";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "flyingvoice_forward_always_off_code";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "*73";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "";

?>
