<?php
#This file was last reorganized on 19th of September 2017 08:54:24 AM UTC

$text['title-status']['en-us'] = "Status";
$text['title-status']['ar-eg'] = "";
$text['title-status']['de-at'] = "Status"; //copied from de-de
$text['title-status']['de-ch'] = "Status"; //copied from de-de
$text['title-status']['de-de'] = "Status";
$text['title-status']['es-cl'] = "Estado";
$text['title-status']['es-mx'] = "Estado"; //copied from es-cl
$text['title-status']['fr-ca'] = "Statut"; //copied from fr-fr
$text['title-status']['fr-fr'] = "Statut";
$text['title-status']['he-il'] = "";
$text['title-status']['it-it'] = "Stato";
$text['title-status']['nl-nl'] = "";
$text['title-status']['pl-pl'] = "Status ";
$text['title-status']['pt-br'] = "Estado"; //copied from pt-pt
$text['title-status']['pt-pt'] = "Estado";
$text['title-status']['ro-ro'] = "";
$text['title-status']['ru-ru'] = "Статус";
$text['title-status']['sv-se'] = "Status";
$text['title-status']['uk-ua'] = "Стан";

$text['title-sofia-status-profile']['en-us'] = "sofia status profile";
$text['title-sofia-status-profile']['ar-eg'] = "";
$text['title-sofia-status-profile']['de-at'] = "sofia status profile"; //copied from de-de
$text['title-sofia-status-profile']['de-ch'] = "sofia status profile"; //copied from de-de
$text['title-sofia-status-profile']['de-de'] = "sofia status profile";
$text['title-sofia-status-profile']['es-cl'] = "perfil de estado sofia";
$text['title-sofia-status-profile']['es-mx'] = "perfil de estado sofia"; //copied from es-cl
$text['title-sofia-status-profile']['fr-ca'] = "profile statut sofia"; //copied from fr-fr
$text['title-sofia-status-profile']['fr-fr'] = "profile statut sofia";
$text['title-sofia-status-profile']['he-il'] = "";
$text['title-sofia-status-profile']['it-it'] = "sofia status profile";
$text['title-sofia-status-profile']['nl-nl'] = "";
$text['title-sofia-status-profile']['pl-pl'] = "Status profilu sofia";
$text['title-sofia-status-profile']['pt-br'] = "Perfil associado ao estado do módulo Sofia";
$text['title-sofia-status-profile']['pt-pt'] = "perfil associado ao estado do módulo sofia";
$text['title-sofia-status-profile']['ro-ro'] = "";
$text['title-sofia-status-profile']['ru-ru'] = "Профиль статуса sofia";
$text['title-sofia-status-profile']['sv-se'] = "sofia status profil";
$text['title-sofia-status-profile']['uk-ua'] = "sofia status profile ";

$text['title-sofia-status']['en-us'] = "sofia status";
$text['title-sofia-status']['ar-eg'] = "";
$text['title-sofia-status']['de-at'] = "sofia status"; //copied from de-de
$text['title-sofia-status']['de-ch'] = "sofia status"; //copied from de-de
$text['title-sofia-status']['de-de'] = "sofia status";
$text['title-sofia-status']['es-cl'] = "estado sofia";
$text['title-sofia-status']['es-mx'] = "estado sofia"; //copied from es-cl
$text['title-sofia-status']['fr-ca'] = "sofia statut"; //copied from fr-fr
$text['title-sofia-status']['fr-fr'] = "sofia statut";
$text['title-sofia-status']['he-il'] = "";
$text['title-sofia-status']['it-it'] = "sofia status";
$text['title-sofia-status']['nl-nl'] = "";
$text['title-sofia-status']['pl-pl'] = "status sofi";
$text['title-sofia-status']['pt-br'] = "Estado do módulo Sofia";
$text['title-sofia-status']['pt-pt'] = "estado do módulo sofia";
$text['title-sofia-status']['ro-ro'] = "";
$text['title-sofia-status']['ru-ru'] = "sofia статус";
$text['title-sofia-status']['sv-se'] = "sofia status";
$text['title-sofia-status']['uk-ua'] = "sofia status ";

$text['title-sip-status']['en-us'] = "SIP Status";
$text['title-sip-status']['ar-eg'] = "";
$text['title-sip-status']['de-at'] = "SIP Status"; //copied from de-de
$text['title-sip-status']['de-ch'] = "SIP Status"; //copied from de-de
$text['title-sip-status']['de-de'] = "SIP Status";
$text['title-sip-status']['es-cl'] = "SIP Estado";
$text['title-sip-status']['es-mx'] = "SIP Estado"; //copied from es-cl
$text['title-sip-status']['fr-ca'] = "SIP État"; //copied from fr-fr
$text['title-sip-status']['fr-fr'] = "SIP État";
$text['title-sip-status']['he-il'] = "";
$text['title-sip-status']['it-it'] = "Stato SIP";
$text['title-sip-status']['nl-nl'] = "";
$text['title-sip-status']['pl-pl'] = "Status SIP";
$text['title-sip-status']['pt-br'] = "Estado SIP";
$text['title-sip-status']['pt-pt'] = "SIP Estado";
$text['title-sip-status']['ro-ro'] = "";
$text['title-sip-status']['ru-ru'] = "SIP Статус";
$text['title-sip-status']['sv-se'] = "SIP Status";
$text['title-sip-status']['uk-ua'] = "Стан SIP";

$text['label-action']['en-us'] = "Action";
$text['label-action']['ar-eg'] = "";
$text['label-action']['de-at'] = "Aktion"; //copied from de-de
$text['label-action']['de-ch'] = "Aktion"; //copied from de-de
$text['label-action']['de-de'] = "Aktion";
$text['label-action']['es-cl'] = "Acción";
$text['label-action']['es-mx'] = "Acción"; //copied from es-cl
$text['label-action']['fr-ca'] = "Action"; //copied from fr-fr
$text['label-action']['fr-fr'] = "Action";
$text['label-action']['he-il'] = "";
$text['label-action']['it-it'] = "";
$text['label-action']['nl-nl'] = "";
$text['label-action']['pl-pl'] = "Operacja";
$text['label-action']['pt-br'] = "Ação";
$text['label-action']['pt-pt'] = "Acção";
$text['label-action']['ro-ro'] = "";
$text['label-action']['ru-ru'] = "Действие";
$text['label-action']['sv-se'] = "Åtgärd";
$text['label-action']['uk-ua'] = "Дія";

$text['label-state']['en-us'] = "State";
$text['label-state']['ar-eg'] = "";
$text['label-state']['de-at'] = "Status"; //copied from de-de
$text['label-state']['de-ch'] = "Status"; //copied from de-de
$text['label-state']['de-de'] = "Status";
$text['label-state']['es-cl'] = "Estado";
$text['label-state']['es-mx'] = "Estado"; //copied from es-cl
$text['label-state']['fr-ca'] = "Etat"; //copied from fr-fr
$text['label-state']['fr-fr'] = "Etat";
$text['label-state']['he-il'] = "";
$text['label-state']['it-it'] = "Stato";
$text['label-state']['nl-nl'] = "";
$text['label-state']['pl-pl'] = "Status";
$text['label-state']['pt-br'] = "Estado"; //copied from pt-pt
$text['label-state']['pt-pt'] = "Estado";
$text['label-state']['ro-ro'] = "";
$text['label-state']['ru-ru'] = "Состояние";
$text['label-state']['sv-se'] = "Status";
$text['label-state']['uk-ua'] = "Стан";

$text['label-message']['en-us'] = "Message";
$text['label-message']['ar-eg'] = "";
$text['label-message']['de-at'] = "Nachricht"; //copied from de-de
$text['label-message']['de-ch'] = "Nachricht"; //copied from de-de
$text['label-message']['de-de'] = "Nachricht";
$text['label-message']['es-cl'] = "Mensaje";
$text['label-message']['es-mx'] = "Mensaje"; //copied from es-cl
$text['label-message']['fr-ca'] = "Message"; //copied from fr-fr
$text['label-message']['fr-fr'] = "Message";
$text['label-message']['he-il'] = "";
$text['label-message']['it-it'] = "Messaggio";
$text['label-message']['nl-nl'] = "";
$text['label-message']['pl-pl'] = "Wiadomość";
$text['label-message']['pt-br'] = "Mensagem"; //copied from pt-pt
$text['label-message']['pt-pt'] = "Mensagem";
$text['label-message']['ro-ro'] = "";
$text['label-message']['ru-ru'] = "Сообщение";
$text['label-message']['sv-se'] = "Meddelande";
$text['label-message']['uk-ua'] = "Повідомлення";

$text['label-data']['en-us'] = "Data";
$text['label-data']['ar-eg'] = "";
$text['label-data']['de-at'] = "Daten"; //copied from de-de
$text['label-data']['de-ch'] = "Daten"; //copied from de-de
$text['label-data']['de-de'] = "Daten";
$text['label-data']['es-cl'] = "Datos";
$text['label-data']['es-mx'] = "Datos"; //copied from es-cl
$text['label-data']['fr-ca'] = "Données"; //copied from fr-fr
$text['label-data']['fr-fr'] = "Données";
$text['label-data']['he-il'] = "";
$text['label-data']['it-it'] = "Dati";
$text['label-data']['nl-nl'] = "";
$text['label-data']['pl-pl'] = "Dane";
$text['label-data']['pt-br'] = "Data";
$text['label-data']['pt-pt'] = "Dados";
$text['label-data']['ro-ro'] = "";
$text['label-data']['ru-ru'] = "Дата";
$text['label-data']['sv-se'] = "Data";
$text['label-data']['uk-ua'] = "Дані";

$text['header-sip-status']['en-us'] = "SIP Status";
$text['header-sip-status']['ar-eg'] = "";
$text['header-sip-status']['de-at'] = "SIP Status"; //copied from de-de
$text['header-sip-status']['de-ch'] = "SIP Status"; //copied from de-de
$text['header-sip-status']['de-de'] = "SIP Status";
$text['header-sip-status']['es-cl'] = "SIP Estado";
$text['header-sip-status']['es-mx'] = "SIP Estado"; //copied from es-cl
$text['header-sip-status']['fr-ca'] = "SIP État"; //copied from fr-fr
$text['header-sip-status']['fr-fr'] = "SIP État";
$text['header-sip-status']['he-il'] = "";
$text['header-sip-status']['it-it'] = "Stato SIP";
$text['header-sip-status']['nl-nl'] = "";
$text['header-sip-status']['pl-pl'] = "Status SIP";
$text['header-sip-status']['pt-br'] = "SIP Estado"; //copied from pt-pt
$text['header-sip-status']['pt-pt'] = "SIP Estado";
$text['header-sip-status']['ro-ro'] = "";
$text['header-sip-status']['ru-ru'] = "Статус SIP";
$text['header-sip-status']['sv-se'] = "SIP Status";
$text['header-sip-status']['uk-ua'] = "Стан SIP";

$text['error-event-socket']['en-us'] = "Connection to Event Socket failed.";
$text['error-event-socket']['ar-eg'] = "";
$text['error-event-socket']['de-at'] = "Verbindung zum Event Socket fehlgeschlagen."; //copied from de-de
$text['error-event-socket']['de-ch'] = "Verbindung zum Event Socket fehlgeschlagen."; //copied from de-de
$text['error-event-socket']['de-de'] = "Verbindung zum Event Socket fehlgeschlagen.";
$text['error-event-socket']['es-cl'] = "Conexión a Socket de Eventos fallida.";
$text['error-event-socket']['es-mx'] = "Conexión a Socket de Eventos fallida."; //copied from es-cl
$text['error-event-socket']['fr-ca'] = "Connexion à l'Event Socket en echec."; //copied from fr-fr
$text['error-event-socket']['fr-fr'] = "Connexion à l'Event Socket en echec.";
$text['error-event-socket']['he-il'] = "";
$text['error-event-socket']['it-it'] = "Connessione alla Event Socket fallita.";
$text['error-event-socket']['nl-nl'] = "";
$text['error-event-socket']['pl-pl'] = "Połączenie do “Event Socket” nie powiodło się";
$text['error-event-socket']['pt-br'] = "A conexão do evento socket falhou";
$text['error-event-socket']['pt-pt'] = "A ligação ao Event Socket falhou.";
$text['error-event-socket']['ro-ro'] = "";
$text['error-event-socket']['ru-ru'] = "Не удалось подключиться к сокету событий.";
$text['error-event-socket']['sv-se'] = "Kontakten till 'Event Socket' misslyckades.";
$text['error-event-socket']['uk-ua'] = "Помилка підключення до сокета подій";

$text['button-rescan']['en-us'] = "Rescan";
$text['button-rescan']['ar-eg'] = "";
$text['button-rescan']['de-at'] = "Neu scannen"; //copied from de-de
$text['button-rescan']['de-ch'] = "Neu scannen"; //copied from de-de
$text['button-rescan']['de-de'] = "Neu scannen";
$text['button-rescan']['es-cl'] = "Vuelva a Explorar";
$text['button-rescan']['es-mx'] = "Vuelva a Explorar"; //copied from es-cl
$text['button-rescan']['fr-ca'] = "Rescan"; //copied from fr-fr
$text['button-rescan']['fr-fr'] = "Rescan";
$text['button-rescan']['he-il'] = "";
$text['button-rescan']['it-it'] = "Rescan";
$text['button-rescan']['nl-nl'] = "";
$text['button-rescan']['pl-pl'] = "Przeskanuj";
$text['button-rescan']['pt-br'] = "Digite novamente";
$text['button-rescan']['pt-pt'] = "Redigitalize";
$text['button-rescan']['ro-ro'] = "";
$text['button-rescan']['ru-ru'] = "Пересканировать";
$text['button-rescan']['sv-se'] = "Sök Igen";
$text['button-rescan']['uk-ua'] = "Пересканувати";

$text['button-reload_xml']['en-us'] = "Reload XML";
$text['button-reload_xml']['ar-eg'] = "";
$text['button-reload_xml']['de-at'] = "XML neu laden"; //copied from de-de
$text['button-reload_xml']['de-ch'] = "XML neu laden"; //copied from de-de
$text['button-reload_xml']['de-de'] = "XML neu laden";
$text['button-reload_xml']['es-cl'] = "Actualizar XML";
$text['button-reload_xml']['es-mx'] = "Actualizar XML"; //copied from es-cl
$text['button-reload_xml']['fr-ca'] = "Reload XML"; //copied from fr-fr
$text['button-reload_xml']['fr-fr'] = "Reload XML";
$text['button-reload_xml']['he-il'] = "";
$text['button-reload_xml']['it-it'] = "Reload XML";
$text['button-reload_xml']['nl-nl'] = "";
$text['button-reload_xml']['pl-pl'] = "Przeładuj XML";
$text['button-reload_xml']['pt-br'] = "Carregar novamente XML";
$text['button-reload_xml']['pt-pt'] = "Recarregar XML";
$text['button-reload_xml']['ro-ro'] = "";
$text['button-reload_xml']['ru-ru'] = "перезагрузить XML";
$text['button-reload_xml']['sv-se'] = "Ladda Om XML";
$text['button-reload_xml']['uk-ua'] = "Перезагрузити XML";

$text['button-reload_acl']['en-us'] = "Reload ACL";
$text['button-reload_acl']['ar-eg'] = "";
$text['button-reload_acl']['de-at'] = "ACL neu laden"; //copied from de-de
$text['button-reload_acl']['de-ch'] = "ACL neu laden"; //copied from de-de
$text['button-reload_acl']['de-de'] = "ACL neu laden";
$text['button-reload_acl']['es-cl'] = "Actualizar ACL";
$text['button-reload_acl']['es-mx'] = "Actualizar ACL"; //copied from es-cl
$text['button-reload_acl']['fr-ca'] = "Reload ACL"; //copied from fr-fr
$text['button-reload_acl']['fr-fr'] = "Reload ACL";
$text['button-reload_acl']['he-il'] = "";
$text['button-reload_acl']['it-it'] = "Reload ACL";
$text['button-reload_acl']['nl-nl'] = "";
$text['button-reload_acl']['pl-pl'] = "Przeładuj  listę kontroli dostępu";
$text['button-reload_acl']['pt-br'] = "Carregar novamente ACL";
$text['button-reload_acl']['pt-pt'] = "Recarregar ACL";
$text['button-reload_acl']['ro-ro'] = "";
$text['button-reload_acl']['ru-ru'] = "Перезагрузить ACL ";
$text['button-reload_acl']['sv-se'] = "Ladda Om ACL";
$text['button-reload_acl']['uk-ua'] = "Перезагрузити ACL ";

$text['button-registrations']['en-us'] = "Registrations";
$text['button-registrations']['ar-eg'] = "";
$text['button-registrations']['de-at'] = "Registrierungen"; //copied from de-de
$text['button-registrations']['de-ch'] = "Registrierungen"; //copied from de-de
$text['button-registrations']['de-de'] = "Registrierungen";
$text['button-registrations']['es-cl'] = "Inscripciones";
$text['button-registrations']['es-mx'] = "Inscripciones"; //copied from es-cl
$text['button-registrations']['fr-ca'] = "Enregistrements"; //copied from fr-fr
$text['button-registrations']['fr-fr'] = "Enregistrements";
$text['button-registrations']['he-il'] = "";
$text['button-registrations']['it-it'] = "Registrazioni";
$text['button-registrations']['nl-nl'] = "";
$text['button-registrations']['pl-pl'] = "Rejestracje";
$text['button-registrations']['pt-br'] = "Inscrições"; //copied from pt-pt
$text['button-registrations']['pt-pt'] = "Inscrições";
$text['button-registrations']['ro-ro'] = "";
$text['button-registrations']['ru-ru'] = "Регистрация";
$text['button-registrations']['sv-se'] = "Registreringar";
$text['button-registrations']['uk-ua'] = "Реєстрації";

$text['button-flush_registrations']['en-us'] = "Flush Registrations";
$text['button-flush_registrations']['ar-eg'] = "";
$text['button-flush_registrations']['de-at'] = "Registrierungen verwerfen"; //copied from de-de
$text['button-flush_registrations']['de-ch'] = "Registrierungen verwerfen"; //copied from de-de
$text['button-flush_registrations']['de-de'] = "Registrierungen verwerfen";
$text['button-flush_registrations']['es-cl'] = "Inscripciones Flush";
$text['button-flush_registrations']['es-mx'] = "Inscripciones Flush"; //copied from es-cl
$text['button-flush_registrations']['fr-ca'] = "Nettoyer enregistrements"; //copied from fr-fr
$text['button-flush_registrations']['fr-fr'] = "Nettoyer enregistrements";
$text['button-flush_registrations']['he-il'] = "";
$text['button-flush_registrations']['it-it'] = "Pulisci Registrazioni";
$text['button-flush_registrations']['nl-nl'] = "";
$text['button-flush_registrations']['pl-pl'] = "Wyrejestruj";
$text['button-flush_registrations']['pt-br'] = "Nivelar Inscrições ";
$text['button-flush_registrations']['pt-pt'] = "Inscrições Lavar";
$text['button-flush_registrations']['ro-ro'] = "";
$text['button-flush_registrations']['ru-ru'] = "Сбросить регистрацию";
$text['button-flush_registrations']['sv-se'] = "'Flush' Registreringar";
$text['button-flush_registrations']['uk-ua'] = "Скинути реєстрації";

$text['button-flush_cache']['en-us'] = "Flush Cache";
$text['button-flush_cache']['ar-eg'] = "";
$text['button-flush_cache']['de-at'] = "Cache leeren"; //copied from de-de
$text['button-flush_cache']['de-ch'] = "Cache leeren"; //copied from de-de
$text['button-flush_cache']['de-de'] = "Cache leeren";
$text['button-flush_cache']['es-cl'] = "Cache Flush";
$text['button-flush_cache']['es-mx'] = "Cache Flush"; //copied from es-cl
$text['button-flush_cache']['fr-ca'] = "Vider Cache"; //copied from fr-fr
$text['button-flush_cache']['fr-fr'] = "Vider Cache";
$text['button-flush_cache']['he-il'] = "";
$text['button-flush_cache']['it-it'] = "Pulisci Cache";
$text['button-flush_cache']['nl-nl'] = "";
$text['button-flush_cache']['pl-pl'] = "Opróżnij pamięć podręczną";
$text['button-flush_cache']['pt-br'] = "Nivelar cache";
$text['button-flush_cache']['pt-pt'] = "Cache Lavar";
$text['button-flush_cache']['ro-ro'] = "";
$text['button-flush_cache']['ru-ru'] = "Сбросить кеш память";
$text['button-flush_cache']['sv-se'] = "Flush Cache ";
$text['button-flush_cache']['uk-ua'] = "Скинути кеш";

?>
