<?php
#This file was last reorganized on 19th of September 2017 08:54:24 AM UTC

$text['title-2']['en-us'] = "Active Extensions";
$text['title-2']['en-gb'] = "Active Extensions";
$text['title-2']['ar-eg'] = "";
$text['title-2']['de-at'] = "Aktive Nebenstellen"; //copied from de-de
$text['title-2']['de-ch'] = "Aktive Nebenstellen"; //copied from de-de
$text['title-2']['de-de'] = "Aktive Nebenstellen";
$text['title-2']['es-cl'] = "Extensiones Activas";
$text['title-2']['es-mx'] = "Extensiones Activas"; //copied from es-cl
$text['title-2']['fr-ca'] = "Extensions Actives"; //copied from fr-fr
$text['title-2']['fr-fr'] = "Extensions Actives";
$text['title-2']['he-il'] = "שלוחה פעילה";
$text['title-2']['it-it'] = "Interni Attivi";
$text['title-2']['nl-nl'] = "Aktieve toestellen";
$text['title-2']['pl-pl'] = "Aktywne numery wewnętrzne";
$text['title-2']['pt-br'] = "Ramais ativos";
$text['title-2']['pt-pt'] = "Extensões Ativas";
$text['title-2']['ro-ro'] = "";
$text['title-2']['ru-ru'] = "Активные внутренние номера";
$text['title-2']['sv-se'] = "Aktiva anknytningar";
$text['title-2']['uk-ua'] = "Активні розширення";

$text['title']['en-us'] = "Active Calls";
$text['title']['en-gb'] = "Active Calls";
$text['title']['ar-eg'] = "";
$text['title']['de-at'] = "Aktive Gespräche"; //copied from de-de
$text['title']['de-ch'] = "Aktive Gespräche"; //copied from de-de
$text['title']['de-de'] = "Aktive Gespräche";
$text['title']['es-cl'] = "Llamadas Activas";
$text['title']['es-mx'] = "Llamadas Activas"; //copied from es-cl
$text['title']['fr-ca'] = "Communications Actives"; //copied from fr-fr
$text['title']['fr-fr'] = "Communications Actives";
$text['title']['he-il'] = "הגדרת חשבון";
$text['title']['it-it'] = "Chiamate Attive";
$text['title']['nl-nl'] = "Aktieve gesprekken";
$text['title']['pl-pl'] = "Aktywne Rozmowy";
$text['title']['pt-br'] = "Configurações da Conta";
$text['title']['pt-pt'] = "Chamadas Ativas";
$text['title']['ro-ro'] = "";
$text['title']['ru-ru'] = "Активные вызовы";
$text['title']['sv-se'] = "Aktiva Samtal";
$text['title']['uk-ua'] = "Активні дзвінки";

$text['label-time']['en-us'] = "Time";
$text['label-time']['en-gb'] = "Time";
$text['label-time']['ar-eg'] = "";
$text['label-time']['de-at'] = "Zeit"; //copied from de-de
$text['label-time']['de-ch'] = "Zeit"; //copied from de-de
$text['label-time']['de-de'] = "Zeit";
$text['label-time']['es-cl'] = "Tiempo";
$text['label-time']['es-mx'] = "Tiempo"; //copied from es-cl
$text['label-time']['fr-ca'] = "Temps"; //copied from fr-fr
$text['label-time']['fr-fr'] = "Temps";
$text['label-time']['he-il'] = "אזור זמן";
$text['label-time']['it-it'] = "Tempo";
$text['label-time']['nl-nl'] = "Tijd";
$text['label-time']['pl-pl'] = "Strefa czasowa";
$text['label-time']['pt-br'] = "Fuso Horário";
$text['label-time']['pt-pt'] = "Tempo";
$text['label-time']['ro-ro'] = "";
$text['label-time']['ru-ru'] = "Время";
$text['label-time']['sv-se'] = "Tid";
$text['label-time']['uk-ua'] = "Час";

$text['label-stop']['en-us'] = "stop record";
$text['label-stop']['en-gb'] = "stop record";
$text['label-stop']['ar-eg'] = "";
$text['label-stop']['de-at'] = "Stoppe Aufnahme"; //copied from de-de
$text['label-stop']['de-ch'] = "Stoppe Aufnahme"; //copied from de-de
$text['label-stop']['de-de'] = "Stoppe Aufnahme";
$text['label-stop']['es-cl'] = "terminar grabación";
$text['label-stop']['es-mx'] = "terminar grabación"; //copied from es-cl
$text['label-stop']['fr-ca'] = "arrêter l'enregistrement"; //copied from fr-fr
$text['label-stop']['fr-fr'] = "arrêter l'enregistrement";
$text['label-stop']['he-il'] = "הפסק הקלטה";
$text['label-stop']['it-it'] = "stop registra";
$text['label-stop']['nl-nl'] = "Stop opname";
$text['label-stop']['pl-pl'] = "zatrzymaj nagrywanie";
$text['label-stop']['pt-br'] = "Parar";
$text['label-stop']['pt-pt'] = "parar de gravar";
$text['label-stop']['ro-ro'] = "";
$text['label-stop']['ru-ru'] = "остановить запись";
$text['label-stop']['sv-se'] = "Stoppa inspelning";
$text['label-stop']['uk-ua'] = "Зупинити запис";

$text['label-status']['en-us'] = "Status";
$text['label-status']['en-gb'] = "Status";
$text['label-status']['ar-eg'] = "";
$text['label-status']['de-at'] = "Status"; //copied from de-de
$text['label-status']['de-ch'] = "Status"; //copied from de-de
$text['label-status']['de-de'] = "Status";
$text['label-status']['es-cl'] = "Estado";
$text['label-status']['es-mx'] = "Estado"; //copied from es-cl
$text['label-status']['fr-ca'] = "Etat"; //copied from fr-fr
$text['label-status']['fr-fr'] = "Etat";
$text['label-status']['he-il'] = "סטטוס";
$text['label-status']['it-it'] = "Stato";
$text['label-status']['nl-nl'] = "Status";
$text['label-status']['pl-pl'] = "Status";
$text['label-status']['pt-br'] = "Estado"; //copied from pt-pt
$text['label-status']['pt-pt'] = "Estado";
$text['label-status']['ro-ro'] = "";
$text['label-status']['ru-ru'] = "Статус";
$text['label-status']['sv-se'] = "Status";
$text['label-status']['uk-ua'] = "Статус";

$text['label-start']['en-us'] = "start record";
$text['label-start']['en-gb'] = "start record";
$text['label-start']['ar-eg'] = "";
$text['label-start']['de-at'] = "Starte Aufnahme"; //copied from de-de
$text['label-start']['de-ch'] = "Starte Aufnahme"; //copied from de-de
$text['label-start']['de-de'] = "Starte Aufnahme";
$text['label-start']['es-cl'] = "iniciar grabación";
$text['label-start']['es-mx'] = "iniciar grabación"; //copied from es-cl
$text['label-start']['fr-ca'] = "Commencer l'enregistrement"; //copied from fr-fr
$text['label-start']['fr-fr'] = "Commencer l'enregistrement";
$text['label-start']['he-il'] = "התחל הקלטה";
$text['label-start']['it-it'] = "registra";
$text['label-start']['nl-nl'] = "Start opname";
$text['label-start']['pl-pl'] = "rozpocznij nagrywanie";
$text['label-start']['pt-br'] = "Iniciar";
$text['label-start']['pt-pt'] = "iniciar a gravação";
$text['label-start']['ro-ro'] = "";
$text['label-start']['ru-ru'] = "начать запись";
$text['label-start']['sv-se'] = "Starta inspelning";
$text['label-start']['uk-ua'] = "Запустити запис";

$text['label-secure']['en-us'] = "Secure";
$text['label-secure']['en-gb'] = "Secure";
$text['label-secure']['ar-eg'] = "";
$text['label-secure']['de-at'] = "Sicher"; //copied from de-de
$text['label-secure']['de-ch'] = "Sicher"; //copied from de-de
$text['label-secure']['de-de'] = "Sicher";
$text['label-secure']['es-cl'] = "Seguro";
$text['label-secure']['es-mx'] = "Seguro"; //copied from es-cl
$text['label-secure']['fr-ca'] = "Securisé"; //copied from fr-fr
$text['label-secure']['fr-fr'] = "Securisé";
$text['label-secure']['he-il'] = "מאובטח";
$text['label-secure']['it-it'] = "Sicura";
$text['label-secure']['nl-nl'] = "Veilig";
$text['label-secure']['pl-pl'] = "Bezpieczny";
$text['label-secure']['pt-br'] = "Seguro"; //copied from pt-pt
$text['label-secure']['pt-pt'] = "Seguro";
$text['label-secure']['ro-ro'] = "";
$text['label-secure']['ru-ru'] = "Безопасный";
$text['label-secure']['sv-se'] = "Skydda";
$text['label-secure']['uk-ua'] = "Захищено";

$text['label-refresh_pause']['en-us'] = "Pause Refresh";
$text['label-refresh_pause']['en-gb'] = "Pause Refresh";
$text['label-refresh_pause']['ar-eg'] = "";
$text['label-refresh_pause']['de-at'] = "Seite neu laden deaktivieren"; //copied from de-de
$text['label-refresh_pause']['de-ch'] = "Seite neu laden deaktivieren"; //copied from de-de
$text['label-refresh_pause']['de-de'] = "Seite neu laden deaktivieren";
$text['label-refresh_pause']['es-cl'] = "Actualizar Pausa";
$text['label-refresh_pause']['es-mx'] = "Actualizar Pausa"; //copied from es-cl
$text['label-refresh_pause']['fr-ca'] = "Pause Actualiser"; //copied from fr-fr
$text['label-refresh_pause']['fr-fr'] = "Pause Actualiser";
$text['label-refresh_pause']['he-il'] = "עצור רענון";
$text['label-refresh_pause']['it-it'] = "Pausa";
$text['label-refresh_pause']['nl-nl'] = "Stop pagina verversen";
$text['label-refresh_pause']['pl-pl'] = "Pauzuj odÅ›wieÅ¼anie";
$text['label-refresh_pause']['pt-br'] = "Pausar atualizaÃ§Ã£o";
$text['label-refresh_pause']['pt-pt'] = "Pausa Atualizar";
$text['label-refresh_pause']['ro-ro'] = "";
$text['label-refresh_pause']['ru-ru'] = "Приостановить обновление";
$text['label-refresh_pause']['sv-se'] = "Paus Uppdatera";
$text['label-refresh_pause']['uk-ua'] = "пауза Оновити";

$text['label-refresh_enable']['en-us'] = "Enable Refresh";
$text['label-refresh_enable']['en-gb'] = "Enable Refresh";
$text['label-refresh_enable']['ar-eg'] = "";
$text['label-refresh_enable']['de-at'] = "Seite neu laden aktivieren"; //copied from de-de
$text['label-refresh_enable']['de-ch'] = "Seite neu laden aktivieren"; //copied from de-de
$text['label-refresh_enable']['de-de'] = "Seite neu laden aktivieren";
$text['label-refresh_enable']['es-cl'] = "Activar Actualizar";
$text['label-refresh_enable']['es-mx'] = "Activar Actualizar"; //copied from es-cl
$text['label-refresh_enable']['fr-ca'] = "Activer Actualiser"; //copied from fr-fr
$text['label-refresh_enable']['fr-fr'] = "Activer Actualiser";
$text['label-refresh_enable']['he-il'] = "אפשר רענון";
$text['label-refresh_enable']['it-it'] = "Riprendi";
$text['label-refresh_enable']['nl-nl'] = "Zet pagina verversen aan";
$text['label-refresh_enable']['pl-pl'] = "WÅ‚Ä…cz odÅ›wieÅ¼anie";
$text['label-refresh_enable']['pt-br'] = "Habilitar atualizaÃ§Ã£o";
$text['label-refresh_enable']['pt-pt'] = "Habilitar Atualização";
$text['label-refresh_enable']['ro-ro'] = "";
$text['label-refresh_enable']['ru-ru'] = "Включить обновление";
$text['label-refresh_enable']['sv-se'] = "Aktivera Uppdatering";
$text['label-refresh_enable']['uk-ua'] = "включити Оновити";

$text['label-profile']['en-us'] = "Profile";
$text['label-profile']['en-gb'] = "Profile";
$text['label-profile']['ar-eg'] = "";
$text['label-profile']['de-at'] = "Profil"; //copied from de-de
$text['label-profile']['de-ch'] = "Profil"; //copied from de-de
$text['label-profile']['de-de'] = "Profil";
$text['label-profile']['es-cl'] = "Perfil";
$text['label-profile']['es-mx'] = "Perfil"; //copied from es-cl
$text['label-profile']['fr-ca'] = "Profil"; //copied from fr-fr
$text['label-profile']['fr-fr'] = "Profil";
$text['label-profile']['he-il'] = "פרופיל";
$text['label-profile']['it-it'] = "Profilo";
$text['label-profile']['nl-nl'] = "Profiel";
$text['label-profile']['pl-pl'] = "Profil";
$text['label-profile']['pt-br'] = "Perfil"; //copied from pt-pt
$text['label-profile']['pt-pt'] = "Perfil";
$text['label-profile']['ro-ro'] = "";
$text['label-profile']['ru-ru'] = "Профиль";
$text['label-profile']['sv-se'] = "Profil";
$text['label-profile']['uk-ua'] = "Профіль";

$text['label-park-extension']['en-us'] = "Park";
$text['label-park-extension']['en-gb'] = "Park";
$text['label-park-extension']['ar-eg'] = "";
$text['label-park-extension']['de-at'] = "Parken"; //copied from de-de
$text['label-park-extension']['de-ch'] = "Parken"; //copied from de-de
$text['label-park-extension']['de-de'] = "Parken";
$text['label-park-extension']['es-cl'] = "Parquear Extensión";
$text['label-park-extension']['es-mx'] = "Parquear Extensión"; //copied from es-cl
$text['label-park-extension']['fr-ca'] = "Parquer"; //copied from fr-fr
$text['label-park-extension']['fr-fr'] = "Parquer";
$text['label-park-extension']['he-il'] = "חניה";
$text['label-park-extension']['it-it'] = "Parcheggia";
$text['label-park-extension']['nl-nl'] = "Parkeer";
$text['label-park-extension']['pl-pl'] = "Parkowanie";
$text['label-park-extension']['pt-br'] = "Extensão estacionamento";
$text['label-park-extension']['pt-pt'] = "Parquear Extensão";
$text['label-park-extension']['ro-ro'] = "";
$text['label-park-extension']['ru-ru'] = "Парковка";
$text['label-park-extension']['sv-se'] = "Parkera";
$text['label-park-extension']['uk-ua'] = "Паркувати";

$text['label-park']['en-us'] = "park";
$text['label-park']['en-gb'] = "park";
$text['label-park']['ar-eg'] = "";
$text['label-park']['de-at'] = "parken"; //copied from de-de
$text['label-park']['de-ch'] = "parken"; //copied from de-de
$text['label-park']['de-de'] = "parken";
$text['label-park']['es-cl'] = "parquear";
$text['label-park']['es-mx'] = "parquear"; //copied from es-cl
$text['label-park']['fr-ca'] = "Parquer"; //copied from fr-fr
$text['label-park']['fr-fr'] = "Parquer";
$text['label-park']['he-il'] = "חניה";
$text['label-park']['it-it'] = "parcheggia";
$text['label-park']['nl-nl'] = "parkeer";
$text['label-park']['pl-pl'] = "parkowanie";
$text['label-park']['pt-br'] = "Estacionamento";
$text['label-park']['pt-pt'] = "parquear";
$text['label-park']['ro-ro'] = "";
$text['label-park']['ru-ru'] = "парковка";
$text['label-park']['sv-se'] = "parkera";
$text['label-park']['uk-ua'] = "паркувати";

$text['label-opt']['en-us'] = "Options";
$text['label-opt']['en-gb'] = "Options";
$text['label-opt']['ar-eg'] = "";
$text['label-opt']['de-at'] = "Optionen"; //copied from de-de
$text['label-opt']['de-ch'] = "Optionen"; //copied from de-de
$text['label-opt']['de-de'] = "Optionen";
$text['label-opt']['es-cl'] = "Opciones";
$text['label-opt']['es-mx'] = "Opciones"; //copied from es-cl
$text['label-opt']['fr-ca'] = "Options"; //copied from fr-fr
$text['label-opt']['fr-fr'] = "Options";
$text['label-opt']['he-il'] = "אפשרויות";
$text['label-opt']['it-it'] = "Opzioni";
$text['label-opt']['nl-nl'] = "Opties";
$text['label-opt']['pl-pl'] = "Opcje";
$text['label-opt']['pt-br'] = "Opções"; //copied from pt-pt
$text['label-opt']['pt-pt'] = "Opções";
$text['label-opt']['ro-ro'] = "";
$text['label-opt']['ru-ru'] = "Опции";
$text['label-opt']['sv-se'] = "Alternativ";
$text['label-opt']['uk-ua'] = "Опції";

$text['label-number']['en-us'] = "Number";
$text['label-number']['en-gb'] = "Number";
$text['label-number']['ar-eg'] = "";
$text['label-number']['de-at'] = "Nummer"; //copied from de-de
$text['label-number']['de-ch'] = "Nummer"; //copied from de-de
$text['label-number']['de-de'] = "Nummer";
$text['label-number']['es-cl'] = "Número";
$text['label-number']['es-mx'] = "Número"; //copied from es-cl
$text['label-number']['fr-ca'] = "Numéro"; //copied from fr-fr
$text['label-number']['fr-fr'] = "Numéro";
$text['label-number']['he-il'] = "מספר";
$text['label-number']['it-it'] = "Numero";
$text['label-number']['nl-nl'] = "Nummer";
$text['label-number']['pl-pl'] = "Numer";
$text['label-number']['pt-br'] = "Número";
$text['label-number']['pt-pt'] = "Numero";
$text['label-number']['ro-ro'] = "";
$text['label-number']['ru-ru'] = "Номер";
$text['label-number']['sv-se'] = "Nummer";
$text['label-number']['uk-ua'] = "Номер";

$text['label-message']['en-us'] = "Message";
$text['label-message']['en-gb'] = "Message";
$text['label-message']['ar-eg'] = "";
$text['label-message']['de-at'] = "Nachricht"; //copied from de-de
$text['label-message']['de-ch'] = "Nachricht"; //copied from de-de
$text['label-message']['de-de'] = "Nachricht";
$text['label-message']['es-cl'] = "Mensaje";
$text['label-message']['es-mx'] = "Mensaje"; //copied from es-cl
$text['label-message']['fr-ca'] = "Message"; //copied from fr-fr
$text['label-message']['fr-fr'] = "Message";
$text['label-message']['he-il'] = "הודעה";
$text['label-message']['it-it'] = "Messaggio";
$text['label-message']['nl-nl'] = "Boodschap";
$text['label-message']['pl-pl'] = "Wiadomość";
$text['label-message']['pt-br'] = "Mensagem"; //copied from pt-pt
$text['label-message']['pt-pt'] = "Mensagem";
$text['label-message']['ro-ro'] = "";
$text['label-message']['ru-ru'] = "Сообщение";
$text['label-message']['sv-se'] = "Meddelande";
$text['label-message']['uk-ua'] = "Повідомлення";

$text['label-hangup']['en-us'] = "Hangup";
$text['label-hangup']['en-gb'] = "Hangup";
$text['label-hangup']['ar-eg'] = "";
$text['label-hangup']['de-at'] = "Auflegen"; //copied from de-de
$text['label-hangup']['de-ch'] = "Auflegen"; //copied from de-de
$text['label-hangup']['de-de'] = "Auflegen";
$text['label-hangup']['es-cl'] = "Terminar";
$text['label-hangup']['es-mx'] = "Terminar"; //copied from es-cl
$text['label-hangup']['fr-ca'] = "Raccrocher"; //copied from fr-fr
$text['label-hangup']['fr-fr'] = "Raccrocher";
$text['label-hangup']['he-il'] = "ניתוק";
$text['label-hangup']['it-it'] = "Chiudi";
$text['label-hangup']['nl-nl'] = "Ophangen";
$text['label-hangup']['pl-pl'] = "Zakończ rozmowę";
$text['label-hangup']['pt-br'] = "Desligar";
$text['label-hangup']['pt-pt'] = "Terminar";
$text['label-hangup']['ro-ro'] = "";
$text['label-hangup']['ru-ru'] = "Завершить";
$text['label-hangup']['sv-se'] = "Avsluta";
$text['label-hangup']['uk-ua'] = "Розірвати";

$text['label-ext']['en-us'] = "Ext";
$text['label-ext']['en-gb'] = "Ext";
$text['label-ext']['ar-eg'] = "";
$text['label-ext']['de-at'] = "Nst"; //copied from de-de
$text['label-ext']['de-ch'] = "Nst"; //copied from de-de
$text['label-ext']['de-de'] = "Nst";
$text['label-ext']['es-cl'] = "Extensión";
$text['label-ext']['es-mx'] = "Extensión"; //copied from es-cl
$text['label-ext']['fr-ca'] = "extension"; //copied from fr-fr
$text['label-ext']['fr-fr'] = "extension";
$text['label-ext']['he-il'] = "שלוחה";
$text['label-ext']['it-it'] = "Int.";
$text['label-ext']['nl-nl'] = "Tst.";
$text['label-ext']['pl-pl'] = "Numer wewnętrzny";
$text['label-ext']['pt-br'] = "Extensão"; //copied from pt-pt
$text['label-ext']['pt-pt'] = "Extensão";
$text['label-ext']['ro-ro'] = "";
$text['label-ext']['ru-ru'] = "Вн.";
$text['label-ext']['sv-se'] = "Ank";
$text['label-ext']['uk-ua'] = "Ext ";

$text['label-domain']['en-us'] = "Domain";
$text['label-domain']['en-gb'] = "Domain";
$text['label-domain']['ar-eg'] = "";
$text['label-domain']['de-at'] = "Domäne"; //copied from de-de
$text['label-domain']['de-ch'] = "Domäne"; //copied from de-de
$text['label-domain']['de-de'] = "Domäne";
$text['label-domain']['es-cl'] = "Dominio";
$text['label-domain']['es-mx'] = "Dominio"; //copied from es-cl
$text['label-domain']['fr-ca'] = "Domaine"; //copied from fr-fr
$text['label-domain']['fr-fr'] = "Domaine";
$text['label-domain']['he-il'] = "תחום";
$text['label-domain']['it-it'] = "Dominio";
$text['label-domain']['nl-nl'] = "Domein";
$text['label-domain']['pl-pl'] = "Domena";
$text['label-domain']['pt-br'] = "Dominio";
$text['label-domain']['pt-pt'] = "Domínio";
$text['label-domain']['ro-ro'] = "";
$text['label-domain']['ru-ru'] = "Домен";
$text['label-domain']['sv-se'] = "Domän";
$text['label-domain']['uk-ua'] = "Домен";

$text['label-destination']['en-us'] = "Dest";
$text['label-destination']['en-gb'] = "Dest";
$text['label-destination']['ar-eg'] = "";
$text['label-destination']['de-at'] = "Ziel"; //copied from de-de
$text['label-destination']['de-ch'] = "Ziel"; //copied from de-de
$text['label-destination']['de-de'] = "Ziel";
$text['label-destination']['es-cl'] = "Destino";
$text['label-destination']['es-mx'] = "Destino"; //copied from es-cl
$text['label-destination']['fr-ca'] = "Dest"; //copied from fr-fr
$text['label-destination']['fr-fr'] = "Dest";
$text['label-destination']['he-il'] = "יעד";
$text['label-destination']['it-it'] = "Dest";
$text['label-destination']['nl-nl'] = "Doel";
$text['label-destination']['pl-pl'] = "Destynacja";
$text['label-destination']['pt-br'] = "Número de destino";
$text['label-destination']['pt-pt'] = "Destino";
$text['label-destination']['ro-ro'] = "";
$text['label-destination']['ru-ru'] = "Назн.";
$text['label-destination']['sv-se'] = "Dest";
$text['label-destination']['uk-ua'] = "Номер";

$text['label-created']['en-us'] = "Created";
$text['label-created']['en-gb'] = "Created";
$text['label-created']['ar-eg'] = "";
$text['label-created']['de-at'] = "Erstellt"; //copied from de-de
$text['label-created']['de-ch'] = "Erstellt"; //copied from de-de
$text['label-created']['de-de'] = "Erstellt";
$text['label-created']['es-cl'] = "Creado";
$text['label-created']['es-mx'] = "Creado"; //copied from es-cl
$text['label-created']['fr-ca'] = "Créé"; //copied from fr-fr
$text['label-created']['fr-fr'] = "Créé";
$text['label-created']['he-il'] = "נוצר";
$text['label-created']['it-it'] = "Creata";
$text['label-created']['nl-nl'] = "Gemaakt";
$text['label-created']['pl-pl'] = "Utworzno";
$text['label-created']['pt-br'] = "Criado"; //copied from pt-pt
$text['label-created']['pt-pt'] = "Criado";
$text['label-created']['ro-ro'] = "";
$text['label-created']['ru-ru'] = "Создан";
$text['label-created']['sv-se'] = "Skapad";
$text['label-created']['uk-ua'] = "Створено";

$text['label-codec']['en-us'] = "Read / Write Codec";
$text['label-codec']['en-gb'] = "Read / Write Codec";
$text['label-codec']['ar-eg'] = "";
$text['label-codec']['de-at'] = "Lese / Schreib Codec"; //copied from de-de
$text['label-codec']['de-ch'] = "Lese / Schreib Codec"; //copied from de-de
$text['label-codec']['de-de'] = "Lese / Schreib Codec";
$text['label-codec']['es-cl'] = "Codec de Lectura / Escritura ";
$text['label-codec']['es-mx'] = "Codec de Lectura / Escritura "; //copied from es-cl
$text['label-codec']['fr-ca'] = "décode/encode"; //copied from fr-fr
$text['label-codec']['fr-fr'] = "décode/encode";
$text['label-codec']['he-il'] = "קריאה / כתיבה codec";
$text['label-codec']['it-it'] = "Codec Lett./Scrit.";
$text['label-codec']['nl-nl'] = "Lees / Schrijf codec";
$text['label-codec']['pl-pl'] = "Kodek read/write";
$text['label-codec']['pt-br'] = "Codec da leitura / escrita";
$text['label-codec']['pt-pt'] = "Codec de Leitura / Escrita ";
$text['label-codec']['ro-ro'] = "";
$text['label-codec']['ru-ru'] = "Кодек Чтение / Запись";
$text['label-codec']['sv-se'] = "Läs/Skriv Codec";
$text['label-codec']['uk-ua'] = "Кодеки читання/запису";

$text['label-cid-number']['en-us'] = "CID Number";
$text['label-cid-number']['en-gb'] = "CID Number";
$text['label-cid-number']['ar-eg'] = "";
$text['label-cid-number']['de-at'] = "Anrufer Nummer"; //copied from de-de
$text['label-cid-number']['de-ch'] = "Anrufer Nummer"; //copied from de-de
$text['label-cid-number']['de-de'] = "Anrufer Nummer";
$text['label-cid-number']['es-cl'] = "Número CID";
$text['label-cid-number']['es-mx'] = "Número CID"; //copied from es-cl
$text['label-cid-number']['fr-ca'] = "Numéro Appelant"; //copied from fr-fr
$text['label-cid-number']['fr-fr'] = "Numéro Appelant";
$text['label-cid-number']['he-il'] = "זהוי מספר";
$text['label-cid-number']['it-it'] = "Numero CID";
$text['label-cid-number']['nl-nl'] = "CID Nummer";
$text['label-cid-number']['pl-pl'] = "Prezentacja numeru dzwoniącego";
$text['label-cid-number']['pt-br'] = "Número CID"; //copied from pt-pt
$text['label-cid-number']['pt-pt'] = "Número CID";
$text['label-cid-number']['ro-ro'] = "";
$text['label-cid-number']['ru-ru'] = "CID Номер";
$text['label-cid-number']['sv-se'] = "CID, nummerspresentation";
$text['label-cid-number']['uk-ua'] = "CID Номер";

$text['label-cid-name']['en-us'] = "CID Name";
$text['label-cid-name']['en-gb'] = "CID Name";
$text['label-cid-name']['ar-eg'] = "";
$text['label-cid-name']['de-at'] = "Anrufer Name"; //copied from de-de
$text['label-cid-name']['de-ch'] = "Anrufer Name"; //copied from de-de
$text['label-cid-name']['de-de'] = "Anrufer Name";
$text['label-cid-name']['es-cl'] = "Nombre CID";
$text['label-cid-name']['es-mx'] = "Nombre CID"; //copied from es-cl
$text['label-cid-name']['fr-ca'] = "Nom Appelant"; //copied from fr-fr
$text['label-cid-name']['fr-fr'] = "Nom Appelant";
$text['label-cid-name']['he-il'] = "זהוי שם";
$text['label-cid-name']['it-it'] = "Nome CID";
$text['label-cid-name']['nl-nl'] = "CID Naam";
$text['label-cid-name']['pl-pl'] = "Prezentacja nazwy dzwoniącego";
$text['label-cid-name']['pt-br'] = "Nome CID"; //copied from pt-pt
$text['label-cid-name']['pt-pt'] = "Nome CID";
$text['label-cid-name']['ro-ro'] = "";
$text['label-cid-name']['ru-ru'] = "CID Имя";
$text['label-cid-name']['sv-se'] = "CID namnpresentation";
$text['label-cid-name']['uk-ua'] = "CID Ім’я";

$text['label-app']['en-us'] = "Application";
$text['label-app']['en-gb'] = "Application";
$text['label-app']['ar-eg'] = "";
$text['label-app']['de-at'] = "Anwendung"; //copied from de-de
$text['label-app']['de-ch'] = "Anwendung"; //copied from de-de
$text['label-app']['de-de'] = "Anwendung";
$text['label-app']['es-cl'] = "Aplicación";
$text['label-app']['es-mx'] = "Aplicación"; //copied from es-cl
$text['label-app']['fr-ca'] = "Application"; //copied from fr-fr
$text['label-app']['fr-fr'] = "Application";
$text['label-app']['he-il'] = "אפליקציה";
$text['label-app']['it-it'] = "Applicazione";
$text['label-app']['nl-nl'] = "Toepassing";
$text['label-app']['pl-pl'] = "Aplikacja";
$text['label-app']['pt-br'] = "Aplicação"; //copied from pt-pt
$text['label-app']['pt-pt'] = "Aplicação";
$text['label-app']['ro-ro'] = "";
$text['label-app']['ru-ru'] = "Приложение";
$text['label-app']['sv-se'] = "Ansökan";
$text['label-app']['uk-ua'] = "Додаток";

$text['description-2']['en-us'] = "Use this to view all extensions and monitor and interact with active calls.";
$text['description-2']['en-gb'] = "Use this to view all extensions and monitor and interact with active calls.";
$text['description-2']['ar-eg'] = "";
$text['description-2']['de-at'] = "Benutzen Sie die Funktionen um alle Nebenstellen anzuzeigen, zu überwachen und aktive Gespräche zu steuern."; //copied from de-de
$text['description-2']['de-ch'] = "Benutzen Sie die Funktionen um alle Nebenstellen anzuzeigen, zu überwachen und aktive Gespräche zu steuern."; //copied from de-de
$text['description-2']['de-de'] = "Benutzen Sie die Funktionen um alle Nebenstellen anzuzeigen, zu überwachen und aktive Gespräche zu steuern.";
$text['description-2']['es-cl'] = "Utilice este menú para ver todas las extensiones, monitorear e interactuar con las llamadas activas.";
$text['description-2']['es-mx'] = "Utilice este menú para ver todas las extensiones, monitorear e interactuar con las llamadas activas."; //copied from es-cl
$text['description-2']['fr-ca'] = "Voir toutes les extensions, superviser et interagir avec les Communications Actives."; //copied from fr-fr
$text['description-2']['fr-fr'] = "Voir toutes les extensions, superviser et interagir avec les Communications Actives.";
$text['description-2']['he-il'] = "";
$text['description-2']['it-it'] = "Usa questo servizio per vedere lo stato degli interni, monitorare e interagire con le chiamate.";
$text['description-2']['nl-nl'] = "Gebruik dit overzicht om alle toestellen te bekijken en reageer op aktieve gesprekken.";
$text['description-2']['pl-pl'] = "Użyj tej opcji, aby zobaczyć wszystkie numery wewnętrzne i monitorować interakcję z aktywnymi rozmowami.";
$text['description-2']['pt-br'] = "A informação contem a origem, destino, duração e outros detalhes úteis da chamada.";
$text['description-2']['pt-pt'] = "Utilize este menu para ver todas as extensões, monitorizar e interagir com as chamadas activas.";
$text['description-2']['ro-ro'] = "";
$text['description-2']['ru-ru'] = "Используйте для просмотра всех внутренних номеров и мониторинга и взаимодействия с активными вызовами.";
$text['description-2']['sv-se'] = "Använd detta för att se alla anknytningar och monitorera och hantera aktiva samtal.";
$text['description-2']['uk-ua'] = "Використовуйте це, щоб переглянути всі розширення, контролювати і взаємодіяти з активними викликами.";

$text['description']['en-us'] = "Use this to monitor and interact with the active calls.";
$text['description']['en-gb'] = "Use this to monitor and interact with the active calls.";
$text['description']['ar-eg'] = "";
$text['description']['de-at'] = "Benutzen Sie die Funktionen um aktive Gespräche zu steuern."; //copied from de-de
$text['description']['de-ch'] = "Benutzen Sie die Funktionen um aktive Gespräche zu steuern."; //copied from de-de
$text['description']['de-de'] = "Benutzen Sie die Funktionen um aktive Gespräche zu steuern.";
$text['description']['es-cl'] = "Utilice este menú para monitorear e interactuar con las llamadas activas.";
$text['description']['es-mx'] = "Utilice este menú para monitorear e interactuar con las llamadas activas."; //copied from es-cl
$text['description']['fr-ca'] = "Superviser et interagir avec les Communications Actives."; //copied from fr-fr
$text['description']['fr-fr'] = "Superviser et interagir avec les Communications Actives.";
$text['description']['he-il'] = "ערוך את פרטי החשבון";
$text['description']['it-it'] = "Usa questo servizio per monitorare e interagire con le chiamate attive.";
$text['description']['nl-nl'] = "Gebruik deze functie om te reageren op gesprekken.";
$text['description']['pl-pl'] = "Użyć tej opcji do monitorowania i interakcji z aktywnymi rozmowami.";
$text['description']['pt-br'] = "Editar informações da conta.";
$text['description']['pt-pt'] = "Utilize este menu para monitorizar e interagir com as chamadas activas.";
$text['description']['ro-ro'] = "";
$text['description']['ru-ru'] = "Используйте для отслеживания и взаимодействия с активными вызовами.";
$text['description']['sv-se'] = "Använd detta för att monitorera och hantera aktiva samtal.";
$text['description']['uk-ua'] = "Використовуйте це, щоб контролювати і взаємодіяти з активними викликами.";

$text['confirm-socket']['en-us'] = "Connection to Event Socket failed.";
$text['confirm-socket']['en-gb'] = "Connection to Event Socket failed.";
$text['confirm-socket']['ar-eg'] = "";
$text['confirm-socket']['de-at'] = "Verbindung zum Event-Socket fehlgeschlagen."; //copied from de-de
$text['confirm-socket']['de-ch'] = "Verbindung zum Event-Socket fehlgeschlagen."; //copied from de-de
$text['confirm-socket']['de-de'] = "Verbindung zum Event-Socket fehlgeschlagen.";
$text['confirm-socket']['es-cl'] = "Conexión con socket fallida.";
$text['confirm-socket']['es-mx'] = "Conexión con socket fallida."; //copied from es-cl
$text['confirm-socket']['fr-ca'] = "la Connexion au Event Socket a échoué."; //copied from fr-fr
$text['confirm-socket']['fr-fr'] = "la Connexion au Event Socket a échoué.";
$text['confirm-socket']['he-il'] = "";
$text['confirm-socket']['it-it'] = "Connessione alla Event Socket fallita.";
$text['confirm-socket']['nl-nl'] = "Verbinding met 'Event-Socket' mislukt";
$text['confirm-socket']['pl-pl'] = "Polaczenie do  Event Socket nie powiodło się";
$text['confirm-socket']['pt-br'] = "A conexão ao evento socket falhou";
$text['confirm-socket']['pt-pt'] = "A conexão ao Event Socket falhou.";
$text['confirm-socket']['ro-ro'] = "";
$text['confirm-socket']['ru-ru'] = "Не удалось подключиться к сокету событий.";
$text['confirm-socket']['sv-se'] = "Anslutning till 'Event Socket' misslyckades";
$text['confirm-socket']['uk-ua'] = "Помилка підключення до сокета подій";

$text['confirm-hangup']['en-us'] = "Do you really want to hangup this call?";
$text['confirm-hangup']['en-gb'] = "Do you really want to hangup this call?";
$text['confirm-hangup']['ar-eg'] = "";
$text['confirm-hangup']['de-at'] = "Wollen Sie dieses Gespräch wirklich beenden?"; //copied from de-de
$text['confirm-hangup']['de-ch'] = "Wollen Sie dieses Gespräch wirklich beenden?"; //copied from de-de
$text['confirm-hangup']['de-de'] = "Wollen Sie dieses Gespräch wirklich beenden?";
$text['confirm-hangup']['es-cl'] = "¿Realmente desea terminar esta llamada?";
$text['confirm-hangup']['es-mx'] = "¿Realmente desea terminar esta llamada?"; //copied from es-cl
$text['confirm-hangup']['fr-ca'] = "Voulez-vous vraiment raccrocher cette communication?"; //copied from fr-fr
$text['confirm-hangup']['fr-fr'] = "Voulez-vous vraiment raccrocher cette communication?";
$text['confirm-hangup']['he-il'] = "";
$text['confirm-hangup']['it-it'] = "Vuoi veramente chiudere questa chiamata?";
$text['confirm-hangup']['nl-nl'] = "Wil je dit gesprek werkelijk verbreken?";
$text['confirm-hangup']['pl-pl'] = "Czy na pewno chcesz się rozłączyć tę rozmowę?";
$text['confirm-hangup']['pt-br'] = "Deseja realmente finalizar essa chamada?";
$text['confirm-hangup']['pt-pt'] = "Deseja realmente terminar esta chamada?";
$text['confirm-hangup']['ro-ro'] = "";
$text['confirm-hangup']['ru-ru'] = "Вы действительно хотите завершить вызов?";
$text['confirm-hangup']['sv-se'] = "Vill du verkligen avsluta detta samtal";
$text['confirm-hangup']['uk-ua'] = "Ви дійсно бажаєте розірвати дзвінок?";

$text['confirm-hangups']['en-us'] = "Do you really want to hangup these calls?";
$text['confirm-hangups']['en-gb'] = "Do you really want to hangup these calls?";
$text['confirm-hangups']['ar-eg'] = "";
$text['confirm-hangups']['de-at'] = "Wollen Sie dieses Gespräch wirklich beenden?"; //copied from de-de
$text['confirm-hangups']['de-ch'] = "Wollen Sie dieses Gespräch wirklich beenden?"; //copied from de-de
$text['confirm-hangups']['de-de'] = "Wollen Sie dieses Gespräch wirklich beenden?";
$text['confirm-hangups']['es-cl'] = "¿Realmente desea terminar esta llamada?";
$text['confirm-hangups']['es-mx'] = "¿Realmente desea terminar esta llamada?"; //copied from es-cl
$text['confirm-hangups']['fr-ca'] = "Voulez-vous vraiment raccrocher cette communication?"; //copied from fr-fr
$text['confirm-hangups']['fr-fr'] = "Voulez-vous vraiment raccrocher cette communication?";
$text['confirm-hangups']['he-il'] = "";
$text['confirm-hangups']['it-it'] = "Vuoi veramente chiudere questa chiamata?";
$text['confirm-hangups']['nl-nl'] = "Wil je deze gesprekken werkelijk verbreken?";
$text['confirm-hangups']['pl-pl'] = "Czy na pewno chcesz się rozłączyć tę rozmowę?";
$text['confirm-hangups']['pt-br'] = "Deseja realmente finalizar essa chamada?";
$text['confirm-hangups']['pt-pt'] = "Deseja realmente terminar esta chamada?";
$text['confirm-hangups']['ro-ro'] = "";
$text['confirm-hangups']['ru-ru'] = "Вы действительно хотите завершить вызов?";
$text['confirm-hangups']['sv-se'] = "Vill du verkligen avsluta detta samtal";
$text['confirm-hangups']['uk-ua'] = "Ви дійсно бажаєте розірвати дзвінок?";

$text['check-onbreak-status']['en-us'] = "On Break";
$text['check-onbreak-status']['en-gb'] = "On Break";
$text['check-onbreak-status']['ar-eg'] = "";
$text['check-onbreak-status']['de-at'] = "Auf Pause"; //copied from de-de
$text['check-onbreak-status']['de-ch'] = "Auf Pause"; //copied from de-de
$text['check-onbreak-status']['de-de'] = "Auf Pause";
$text['check-onbreak-status']['es-cl'] = "En Pausa";
$text['check-onbreak-status']['es-mx'] = "En Pausa"; //copied from es-cl
$text['check-onbreak-status']['fr-ca'] = "En Pause"; //copied from fr-fr
$text['check-onbreak-status']['fr-fr'] = "En Pause";
$text['check-onbreak-status']['he-il'] = "בהפסקה";
$text['check-onbreak-status']['it-it'] = "In Pausa";
$text['check-onbreak-status']['nl-nl'] = "Onderbroken";
$text['check-onbreak-status']['pl-pl'] = "Na przerwie";
$text['check-onbreak-status']['pt-br'] = "Em Pausa"; //copied from pt-pt
$text['check-onbreak-status']['pt-pt'] = "Em Pausa";
$text['check-onbreak-status']['ro-ro'] = "";
$text['check-onbreak-status']['ru-ru'] = "Перерыв";
$text['check-onbreak-status']['sv-se'] = "På Rast";
$text['check-onbreak-status']['uk-ua'] = "На перерві";

$text['check-loggedout-status']['en-us'] = "Logged Out";
$text['check-loggedout-status']['en-gb'] = "Logged Out";
$text['check-loggedout-status']['ar-eg'] = "";
$text['check-loggedout-status']['de-at'] = "Abgemeldet"; //copied from de-de
$text['check-loggedout-status']['de-ch'] = "Abgemeldet"; //copied from de-de
$text['check-loggedout-status']['de-de'] = "Abgemeldet";
$text['check-loggedout-status']['es-cl'] = "Desconectado";
$text['check-loggedout-status']['es-mx'] = "Desconectado"; //copied from es-cl
$text['check-loggedout-status']['fr-ca'] = "Déconnecté"; //copied from fr-fr
$text['check-loggedout-status']['fr-fr'] = "Déconnecté";
$text['check-loggedout-status']['he-il'] = "התנתק";
$text['check-loggedout-status']['it-it'] = "Sloggato";
$text['check-loggedout-status']['nl-nl'] = "Afgelogd";
$text['check-loggedout-status']['pl-pl'] = "Wylogowany";
$text['check-loggedout-status']['pt-br'] = "Desligado"; //copied from pt-pt
$text['check-loggedout-status']['pt-pt'] = "Desligado";
$text['check-loggedout-status']['ro-ro'] = "";
$text['check-loggedout-status']['ru-ru'] = "Не в сети";
$text['check-loggedout-status']['sv-se'] = "Utloggad";
$text['check-loggedout-status']['uk-ua'] = "Вийшов";

$text['check-do-not-disturb-status']['en-us'] = "Do Not Disturb";
$text['check-do-not-disturb-status']['en-gb'] = "Do Not Disturb";
$text['check-do-not-disturb-status']['ar-eg'] = "";
$text['check-do-not-disturb-status']['de-at'] = "Bitte nicht Stören"; //copied from de-de
$text['check-do-not-disturb-status']['de-ch'] = "Bitte nicht Stören"; //copied from de-de
$text['check-do-not-disturb-status']['de-de'] = "Bitte nicht Stören";
$text['check-do-not-disturb-status']['es-cl'] = "No molestar";
$text['check-do-not-disturb-status']['es-mx'] = "No molestar"; //copied from es-cl
$text['check-do-not-disturb-status']['fr-ca'] = "Ne Pas Déranger"; //copied from fr-fr
$text['check-do-not-disturb-status']['fr-fr'] = "Ne Pas Déranger";
$text['check-do-not-disturb-status']['he-il'] = "לא להפריע";
$text['check-do-not-disturb-status']['it-it'] = "Non Disturbare";
$text['check-do-not-disturb-status']['nl-nl'] = "Niet Storen";
$text['check-do-not-disturb-status']['pl-pl'] = "Nie przeszkadzaj (DND)";
$text['check-do-not-disturb-status']['pt-br'] = "Não Pertube";
$text['check-do-not-disturb-status']['pt-pt'] = "Não Perturbar";
$text['check-do-not-disturb-status']['ro-ro'] = "";
$text['check-do-not-disturb-status']['ru-ru'] = "Не беспокоить (DND)";
$text['check-do-not-disturb-status']['sv-se'] = "Stör Ej";
$text['check-do-not-disturb-status']['uk-ua'] = "Не турбувати";

$text['check-available-status']['en-us'] = "Available";
$text['check-available-status']['en-gb'] = "Available";
$text['check-available-status']['ar-eg'] = "";
$text['check-available-status']['de-at'] = "Erreichbar"; //copied from de-de
$text['check-available-status']['de-ch'] = "Erreichbar"; //copied from de-de
$text['check-available-status']['de-de'] = "Erreichbar";
$text['check-available-status']['es-cl'] = "Disponible";
$text['check-available-status']['es-mx'] = "Disponible"; //copied from es-cl
$text['check-available-status']['fr-ca'] = "Disponible"; //copied from fr-fr
$text['check-available-status']['fr-fr'] = "Disponible";
$text['check-available-status']['he-il'] = "זמין";
$text['check-available-status']['it-it'] = "Disponibile";
$text['check-available-status']['nl-nl'] = "Beschikbaar";
$text['check-available-status']['pl-pl'] = "Dostępny";
$text['check-available-status']['pt-br'] = "Disponível"; //copied from pt-pt
$text['check-available-status']['pt-pt'] = "Disponível";
$text['check-available-status']['ro-ro'] = "";
$text['check-available-status']['ru-ru'] = "Доступен";
$text['check-available-status']['sv-se'] = "Anträffbar";
$text['check-available-status']['uk-ua'] = "Доступний";

$text['check-available-on-demand-status']['en-us'] = "Available (On Demand)";
$text['check-available-on-demand-status']['en-gb'] = "Available (On Demand)";
$text['check-available-on-demand-status']['ar-eg'] = "";
$text['check-available-on-demand-status']['de-at'] = "Erreichbar (Auf Anfrage)"; //copied from de-de
$text['check-available-on-demand-status']['de-ch'] = "Erreichbar (Auf Anfrage)"; //copied from de-de
$text['check-available-on-demand-status']['de-de'] = "Erreichbar (Auf Anfrage)";
$text['check-available-on-demand-status']['es-cl'] = "Disponible (On Demand)";
$text['check-available-on-demand-status']['es-mx'] = "Disponible (On Demand)"; //copied from es-cl
$text['check-available-on-demand-status']['fr-ca'] = "Disponible (Sur Demande)"; //copied from fr-fr
$text['check-available-on-demand-status']['fr-fr'] = "Disponible (Sur Demande)";
$text['check-available-on-demand-status']['he-il'] = "";
$text['check-available-on-demand-status']['it-it'] = "Disponibile (Su Richiesta)";
$text['check-available-on-demand-status']['nl-nl'] = "Beschikbaar (op verzoek)";
$text['check-available-on-demand-status']['pl-pl'] = "Dostępny (na żądanie)";
$text['check-available-on-demand-status']['pt-br'] = "Disponível (A pedido)"; //copied from pt-pt
$text['check-available-on-demand-status']['pt-pt'] = "Disponível (A pedido)";
$text['check-available-on-demand-status']['ro-ro'] = "";
$text['check-available-on-demand-status']['ru-ru'] = "Доступен (по требованию)";
$text['check-available-on-demand-status']['sv-se'] = "Anträffbar (På Begäran)";
$text['check-available-on-demand-status']['uk-ua'] = "Доступний (на вимогу)";

$text['button-show_all']['en-us'] = "Show All";
$text['button-show_all']['en-gb'] = "Show All";
$text['button-show_all']['ar-eg'] = "";
$text['button-show_all']['de-at'] = "Alle anzeigen"; //copied from de-de
$text['button-show_all']['de-ch'] = "Alle anzeigen"; //copied from de-de
$text['button-show_all']['de-de'] = "Alle anzeigen";
$text['button-show_all']['es-cl'] = "Mostrar Todos";
$text['button-show_all']['es-mx'] = "Mostrar Todos"; //copied from es-cl
$text['button-show_all']['fr-ca'] = "Montrer Tout"; //copied from fr-fr
$text['button-show_all']['fr-fr'] = "Montrer Tout";
$text['button-show_all']['he-il'] = "";
$text['button-show_all']['it-it'] = "Mostra Tutto";
$text['button-show_all']['nl-nl'] = "Alles tonen";
$text['button-show_all']['pl-pl'] = "Pokaż Wszystkie";
$text['button-show_all']['pt-br'] = "Mostrar Todos"; //copied from pt-pt
$text['button-show_all']['pt-pt'] = "Mostrar Todos";
$text['button-show_all']['ro-ro'] = "";
$text['button-show_all']['ru-ru'] = "Показать все";
$text['button-show_all']['sv-se'] = "Visa Allt";
$text['button-show_all']['uk-ua'] = "Показати всі";

$text['message-calls_ended']['en-us'] = "Calls Ended";
$text['message-calls_ended']['en-gb'] = "Calls Ended";
$text['message-calls_ended']['ar-eg'] = "";
$text['message-calls_ended']['de-at'] = "";
$text['message-calls_ended']['de-ch'] = "";
$text['message-calls_ended']['de-de'] = "";
$text['message-calls_ended']['es-cl'] = "";
$text['message-calls_ended']['es-mx'] = "";
$text['message-calls_ended']['fr-ca'] = "";
$text['message-calls_ended']['fr-fr'] = "";
$text['message-calls_ended']['he-il'] = "";
$text['message-calls_ended']['it-it'] = "";
$text['message-calls_ended']['nl-nl'] = "Beeindigde gesprekken";
$text['message-calls_ended']['pl-pl'] = "";
$text['message-calls_ended']['pt-br'] = "";
$text['message-calls_ended']['pt-pt'] = "";
$text['message-calls_ended']['ro-ro'] = "";
$text['message-calls_ended']['ru-ru'] = "";
$text['message-calls_ended']['sv-se'] = "";
$text['message-calls_ended']['uk-ua'] = "";

?>
