#!/bin/sh
set -e

case "$1" in
  remove|upgrade|deconfigure)
    if [ -d /usr/share/examples/fusionpbx/resources/templates/provision/polycom ]; then
      echo "We're about to remove a configured fusionpbx provisioning templates for polycom phones ..." >&2
    fi
    ;;
  failed-upgrade)
    ;;
  *)
    echo "prerm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#
exit 0
