<?php
#This file was last reorganized on 19th of September 2017 08:54:24 AM UTC

$text['title-pin_numbers']['en-us'] = "PIN Numbers";
$text['title-pin_numbers']['en-gb'] = "PIN Numbers";
$text['title-pin_numbers']['ar-eg'] = "";
$text['title-pin_numbers']['de-at'] = "PIN Nummern"; //copied from de-de
$text['title-pin_numbers']['de-ch'] = "PIN Nummern"; //copied from de-de
$text['title-pin_numbers']['de-de'] = "PIN Nummern";
$text['title-pin_numbers']['es-cl'] = "";
$text['title-pin_numbers']['es-mx'] = "";
$text['title-pin_numbers']['fr-ca'] = "Numéros de pin";
$text['title-pin_numbers']['fr-fr'] = "Numéros de pin";
$text['title-pin_numbers']['he-il'] = "";
$text['title-pin_numbers']['it-it'] = "Numeri PIN";
$text['title-pin_numbers']['nl-nl'] = "PIN codes";
$text['title-pin_numbers']['pl-pl'] = "";
$text['title-pin_numbers']['pt-br'] = "";
$text['title-pin_numbers']['pt-pt'] = "";
$text['title-pin_numbers']['ro-ro'] = "";
$text['title-pin_numbers']['ru-ru'] = "PIN Номеров";
$text['title-pin_numbers']['sv-se'] = "PIN Nummer";
$text['title-pin_numbers']['uk-ua'] = "";

$text['title-pin_number']['en-us'] = "PIN Number";
$text['title-pin_number']['en-gb'] = "PIN Number";
$text['title-pin_number']['ar-eg'] = "";
$text['title-pin_number']['de-at'] = "PIN Nummer"; //copied from de-de
$text['title-pin_number']['de-ch'] = "PIN Nummer"; //copied from de-de
$text['title-pin_number']['de-de'] = "PIN Nummer";
$text['title-pin_number']['es-cl'] = "";
$text['title-pin_number']['es-mx'] = "";
$text['title-pin_number']['fr-ca'] = "Code PIN";
$text['title-pin_number']['fr-fr'] = "Code PIN";
$text['title-pin_number']['he-il'] = "";
$text['title-pin_number']['it-it'] = "Numero PIN";
$text['title-pin_number']['nl-nl'] = "PIN code";
$text['title-pin_number']['pl-pl'] = "";
$text['title-pin_number']['pt-br'] = "";
$text['title-pin_number']['pt-pt'] = "";
$text['title-pin_number']['ro-ro'] = "";
$text['title-pin_number']['ru-ru'] = "PIN Номер";
$text['title-pin_number']['sv-se'] = "PIN Nummer";
$text['title-pin_number']['uk-ua'] = "";

$text['title_description-pin_number']['en-us'] = "List of PIN Numbers and account codes.";
$text['title_description-pin_number']['en-gb'] = "List of PIN Numbers and account codes.";
$text['title_description-pin_number']['ar-eg'] = "";
$text['title_description-pin_number']['de-at'] = "Liste von PIN Nummern und Kontoschlüssel."; //copied from de-de
$text['title_description-pin_number']['de-ch'] = "Liste von PIN Nummern und Kontoschlüssel."; //copied from de-de
$text['title_description-pin_number']['de-de'] = "Liste von PIN Nummern und Kontoschlüssel.";
$text['title_description-pin_number']['es-cl'] = "";
$text['title_description-pin_number']['es-mx'] = "";
$text['title_description-pin_number']['fr-ca'] = "Liste des codes PIN et des codes de compte.";
$text['title_description-pin_number']['fr-fr'] = "Liste des codes PIN et des codes de compte.";
$text['title_description-pin_number']['he-il'] = "";
$text['title_description-pin_number']['it-it'] = "Lista dei numeri PIN e degli account codes.";
$text['title_description-pin_number']['nl-nl'] = "Lijst met PIN codes enaccountcodes.";
$text['title_description-pin_number']['pl-pl'] = "";
$text['title_description-pin_number']['pt-br'] = "";
$text['title_description-pin_number']['pt-pt'] = "";
$text['title_description-pin_number']['ro-ro'] = "";
$text['title_description-pin_number']['ru-ru'] = "Список PIN Номеров и Аккаунт кодов.";
$text['title_description-pin_number']['sv-se'] = "Lista med PIN Nummer och account codes.";
$text['title_description-pin_number']['uk-ua'] = "";

$text['label-pin_number']['en-us'] = "PIN Number";
$text['label-pin_number']['en-gb'] = "PIN Number";
$text['label-pin_number']['ar-eg'] = "";
$text['label-pin_number']['de-at'] = "PIN Nummer"; //copied from de-de
$text['label-pin_number']['de-ch'] = "PIN Nummer"; //copied from de-de
$text['label-pin_number']['de-de'] = "PIN Nummer";
$text['label-pin_number']['es-cl'] = "";
$text['label-pin_number']['es-mx'] = "";
$text['label-pin_number']['fr-ca'] = "Code PIN";
$text['label-pin_number']['fr-fr'] = "Code PIN";
$text['label-pin_number']['he-il'] = "";
$text['label-pin_number']['it-it'] = "Numero PIN";
$text['label-pin_number']['nl-nl'] = "PIN code";
$text['label-pin_number']['pl-pl'] = "";
$text['label-pin_number']['pt-br'] = "";
$text['label-pin_number']['pt-pt'] = "";
$text['label-pin_number']['ro-ro'] = "";
$text['label-pin_number']['ru-ru'] = "PIN Номер";
$text['label-pin_number']['sv-se'] = "PIN Nummer";
$text['label-pin_number']['uk-ua'] = "";

$text['description-pin_number']['en-us'] = "Enter the PIN number.";
$text['description-pin_number']['en-gb'] = "Enter the PIN number.";
$text['description-pin_number']['ar-eg'] = "";
$text['description-pin_number']['de-at'] = "Geben Sie die PIN Nummer ein."; //copied from de-de
$text['description-pin_number']['de-ch'] = "Geben Sie die PIN Nummer ein."; //copied from de-de
$text['description-pin_number']['de-de'] = "Geben Sie die PIN Nummer ein.";
$text['description-pin_number']['es-cl'] = "";
$text['description-pin_number']['es-mx'] = "";
$text['description-pin_number']['fr-ca'] = "Entrez le code PIN.";
$text['description-pin_number']['fr-fr'] = "Entrez le code PIN.";
$text['description-pin_number']['he-il'] = "";
$text['description-pin_number']['it-it'] = "Inserire il PIN";
$text['description-pin_number']['nl-nl'] = "Voer PIN code in.";
$text['description-pin_number']['pl-pl'] = "";
$text['description-pin_number']['pt-br'] = "";
$text['description-pin_number']['pt-pt'] = "";
$text['description-pin_number']['ro-ro'] = "";
$text['description-pin_number']['ru-ru'] = "Введите PIN номер.";
$text['description-pin_number']['sv-se'] = "Ange PIN NUmret.";
$text['description-pin_number']['uk-ua'] = "";

$text['label-accountcode']['en-us'] = "Accountcode";
$text['label-accountcode']['en-gb'] = "Accountcode";
$text['label-accountcode']['ar-eg'] = "";
$text['label-accountcode']['de-at'] = "Kontoschlüssel"; //copied from de-de
$text['label-accountcode']['de-ch'] = "Kontoschlüssel"; //copied from de-de
$text['label-accountcode']['de-de'] = "Kontoschlüssel";
$text['label-accountcode']['es-cl'] = "";
$text['label-accountcode']['es-mx'] = "";
$text['label-accountcode']['fr-ca'] = "Code de compte.";
$text['label-accountcode']['fr-fr'] = "Code de compte.";
$text['label-accountcode']['he-il'] = "";
$text['label-accountcode']['it-it'] = "Accountcode";
$text['label-accountcode']['nl-nl'] = "Accountcode";
$text['label-accountcode']['pl-pl'] = "";
$text['label-accountcode']['pt-br'] = "";
$text['label-accountcode']['pt-pt'] = "";
$text['label-accountcode']['ro-ro'] = "";
$text['label-accountcode']['ru-ru'] = "Код Аккаунта";
$text['label-accountcode']['sv-se'] = "Accountcode";
$text['label-accountcode']['uk-ua'] = "";

$text['description-accountcode']['en-us'] = "Enter the accountcode.";
$text['description-accountcode']['en-gb'] = "Enter the accountcode.";
$text['description-accountcode']['ar-eg'] = "";
$text['description-accountcode']['de-at'] = "Geben Sie den Kontoschlüssel ein."; //copied from de-de
$text['description-accountcode']['de-ch'] = "Geben Sie den Kontoschlüssel ein."; //copied from de-de
$text['description-accountcode']['de-de'] = "Geben Sie den Kontoschlüssel ein.";
$text['description-accountcode']['es-cl'] = "";
$text['description-accountcode']['es-mx'] = "";
$text['description-accountcode']['fr-ca'] = "Entrez le code de compte.";
$text['description-accountcode']['fr-fr'] = "Entrez le code de compte.";
$text['description-accountcode']['he-il'] = "";
$text['description-accountcode']['it-it'] = "Inserire l'accountcode.";
$text['description-accountcode']['nl-nl'] = "Voer de accountcode in.";
$text['description-accountcode']['pl-pl'] = "";
$text['description-accountcode']['pt-br'] = "";
$text['description-accountcode']['pt-pt'] = "";
$text['description-accountcode']['ro-ro'] = "";
$text['description-accountcode']['ru-ru'] = "Введите код Аккаунта.";
$text['description-accountcode']['sv-se'] = "Ange Accountcode";
$text['description-accountcode']['uk-ua'] = "";

$text['label-enabled']['en-us'] = "Enabled";
$text['label-enabled']['en-gb'] = "Enabled";
$text['label-enabled']['ar-eg'] = "";
$text['label-enabled']['de-at'] = "Aktiviert"; //copied from de-de
$text['label-enabled']['de-ch'] = "Aktiviert"; //copied from de-de
$text['label-enabled']['de-de'] = "Aktiviert";
$text['label-enabled']['es-cl'] = "";
$text['label-enabled']['es-mx'] = "";
$text['label-enabled']['fr-ca'] = "Activé";
$text['label-enabled']['fr-fr'] = "Activé";
$text['label-enabled']['he-il'] = "";
$text['label-enabled']['it-it'] = "Abilitato";
$text['label-enabled']['nl-nl'] = "Aan";
$text['label-enabled']['pl-pl'] = "";
$text['label-enabled']['pt-br'] = "";
$text['label-enabled']['pt-pt'] = "";
$text['label-enabled']['ro-ro'] = "";
$text['label-enabled']['ru-ru'] = "Включено";
$text['label-enabled']['sv-se'] = "Aktiverad";
$text['label-enabled']['uk-ua'] = "";

$text['description-enabled']['en-us'] = "Enable or Disable the PIN Number.";
$text['description-enabled']['en-gb'] = "Enable or Disable the PIN Number.";
$text['description-enabled']['ar-eg'] = "";
$text['description-enabled']['de-at'] = "Die PIN Nummer aktivieren und deaktivieren."; //copied from de-de
$text['description-enabled']['de-ch'] = "Die PIN Nummer aktivieren und deaktivieren."; //copied from de-de
$text['description-enabled']['de-de'] = "Die PIN Nummer aktivieren und deaktivieren.";
$text['description-enabled']['es-cl'] = "";
$text['description-enabled']['es-mx'] = "";
$text['description-enabled']['fr-ca'] = "Activer ou désactiver le code PIN.";
$text['description-enabled']['fr-fr'] = "Activer ou désactiver le code PIN.";
$text['description-enabled']['he-il'] = "";
$text['description-enabled']['it-it'] = "Abilita o Disabilita il numero PIN.";
$text['description-enabled']['nl-nl'] = "Zet PIN code aan/uit.";
$text['description-enabled']['pl-pl'] = "";
$text['description-enabled']['pt-br'] = "";
$text['description-enabled']['pt-pt'] = "";
$text['description-enabled']['ro-ro'] = "";
$text['description-enabled']['ru-ru'] = "Включение и отключение PIN Номера.";
$text['description-enabled']['sv-se'] = "Aktivera eller inaktivera PIN Nummer.";
$text['description-enabled']['uk-ua'] = "";

$text['label-description']['en-us'] = "Description";
$text['label-description']['en-gb'] = "Description";
$text['label-description']['ar-eg'] = "";
$text['label-description']['de-at'] = "Beschreibung"; //copied from de-de
$text['label-description']['de-ch'] = "Beschreibung"; //copied from de-de
$text['label-description']['de-de'] = "Beschreibung";
$text['label-description']['es-cl'] = "";
$text['label-description']['es-mx'] = "";
$text['label-description']['fr-ca'] = "Description";
$text['label-description']['fr-fr'] = "Description";
$text['label-description']['he-il'] = "";
$text['label-description']['it-it'] = "Descrizione";
$text['label-description']['nl-nl'] = "Omschrijving";
$text['label-description']['pl-pl'] = "";
$text['label-description']['pt-br'] = "";
$text['label-description']['pt-pt'] = "";
$text['label-description']['ro-ro'] = "";
$text['label-description']['ru-ru'] = "Описание";
$text['label-description']['sv-se'] = "Beskrivning";
$text['label-description']['uk-ua'] = "";

$text['description-description']['en-us'] = "Enter the description.";
$text['description-description']['en-gb'] = "Enter the description.";
$text['description-description']['ar-eg'] = "";
$text['description-description']['de-at'] = "Geben Sie die Beschreibung ein."; //copied from de-de
$text['description-description']['de-ch'] = "Geben Sie die Beschreibung ein."; //copied from de-de
$text['description-description']['de-de'] = "Geben Sie die Beschreibung ein.";
$text['description-description']['es-cl'] = "";
$text['description-description']['es-mx'] = "";
$text['description-description']['fr-ca'] = "Entrez la description";
$text['description-description']['fr-fr'] = "Entrez la description";
$text['description-description']['he-il'] = "";
$text['description-description']['it-it'] = "Inserire la descrizione.";
$text['description-description']['nl-nl'] = "Voer de omschrijving in";
$text['description-description']['pl-pl'] = "";
$text['description-description']['pt-br'] = "";
$text['description-description']['pt-pt'] = "";
$text['description-description']['ro-ro'] = "";
$text['description-description']['ru-ru'] = "Введите описание.";
$text['description-description']['sv-se'] = "Ange beskrivningen.";
$text['description-description']['uk-ua'] = "";

$text['label-column_name']['en-us'] = "Column Name";
$text['label-column_name']['en-gb'] = "Column Name";
$text['label-column_name']['ar-eg'] = "";
$text['label-column_name']['de-at'] = "";
$text['label-column_name']['de-ch'] = "";
$text['label-column_name']['de-de'] = "";
$text['label-column_name']['es-cl'] = "";
$text['label-column_name']['es-mx'] = "";
$text['label-column_name']['fr-ca'] = "Nom de colonne";
$text['label-column_name']['fr-fr'] = "Nom de colonne";
$text['label-column_name']['he-il'] = "";
$text['label-column_name']['it-it'] = "";
$text['label-column_name']['nl-nl'] = "Kolomnaam";
$text['label-column_name']['pl-pl'] = "";
$text['label-column_name']['pt-br'] = "";
$text['label-column_name']['pt-pt'] = "";
$text['label-column_name']['ro-ro'] = "";
$text['label-column_name']['ru-ru'] = "";
$text['label-column_name']['sv-se'] = "";
$text['label-column_name']['uk-ua'] = "";

$text['button-add']['en-us'] = "Add";
$text['button-add']['en-gb'] = "Add";
$text['button-add']['ar-eg'] = "";
$text['button-add']['de-at'] = "Hinzufügen"; //copied from de-de
$text['button-add']['de-ch'] = "Hinzufügen"; //copied from de-de
$text['button-add']['de-de'] = "Hinzufügen";
$text['button-add']['es-cl'] = "";
$text['button-add']['es-mx'] = "";
$text['button-add']['fr-ca'] = "Ajouter";
$text['button-add']['fr-fr'] = "Ajouter";
$text['button-add']['he-il'] = "";
$text['button-add']['it-it'] = "Inserire";
$text['button-add']['nl-nl'] = "Toevoegen";
$text['button-add']['pl-pl'] = "";
$text['button-add']['pt-br'] = "";
$text['button-add']['pt-pt'] = "";
$text['button-add']['ro-ro'] = "";
$text['button-add']['ru-ru'] = "Добавить";
$text['button-add']['sv-se'] = "Lägg Till";
$text['button-add']['uk-ua'] = "";

$text['button-edit']['en-us'] = "Edit";
$text['button-edit']['en-gb'] = "Edit";
$text['button-edit']['ar-eg'] = "";
$text['button-edit']['de-at'] = "Bearbeiten"; //copied from de-de
$text['button-edit']['de-ch'] = "Bearbeiten"; //copied from de-de
$text['button-edit']['de-de'] = "Bearbeiten";
$text['button-edit']['es-cl'] = "";
$text['button-edit']['es-mx'] = "";
$text['button-edit']['fr-ca'] = "Modifier";
$text['button-edit']['fr-fr'] = "Modifier";
$text['button-edit']['he-il'] = "";
$text['button-edit']['it-it'] = "Modificare";
$text['button-edit']['nl-nl'] = "Bewerken";
$text['button-edit']['pl-pl'] = "";
$text['button-edit']['pt-br'] = "";
$text['button-edit']['pt-pt'] = "";
$text['button-edit']['ro-ro'] = "";
$text['button-edit']['ru-ru'] = "Редактировать";
$text['button-edit']['sv-se'] = "Ändra";
$text['button-edit']['uk-ua'] = "";

$text['button-delete']['en-us'] = "Delete";
$text['button-delete']['en-gb'] = "Delete";
$text['button-delete']['ar-eg'] = "";
$text['button-delete']['de-at'] = "Löschen"; //copied from de-de
$text['button-delete']['de-ch'] = "Löschen"; //copied from de-de
$text['button-delete']['de-de'] = "Löschen";
$text['button-delete']['es-cl'] = "";
$text['button-delete']['es-mx'] = "";
$text['button-delete']['fr-ca'] = "Supprimer";
$text['button-delete']['fr-fr'] = "Supprimer";
$text['button-delete']['he-il'] = "";
$text['button-delete']['it-it'] = "Cancellare";
$text['button-delete']['nl-nl'] = "Verwijderen";
$text['button-delete']['pl-pl'] = "";
$text['button-delete']['pt-br'] = "";
$text['button-delete']['pt-pt'] = "";
$text['button-delete']['ro-ro'] = "";
$text['button-delete']['ru-ru'] = "Удалить";
$text['button-delete']['sv-se'] = "Ta Bort";
$text['button-delete']['uk-ua'] = "";

$text['button-save']['en-us'] = "Save";
$text['button-save']['en-gb'] = "Save";
$text['button-save']['ar-eg'] = "";
$text['button-save']['de-at'] = "Speichern"; //copied from de-de
$text['button-save']['de-ch'] = "Speichern"; //copied from de-de
$text['button-save']['de-de'] = "Speichern";
$text['button-save']['es-cl'] = "";
$text['button-save']['es-mx'] = "";
$text['button-save']['fr-ca'] = "Enregistrer";
$text['button-save']['fr-fr'] = "Enregistrer";
$text['button-save']['he-il'] = "";
$text['button-save']['it-it'] = "Salva";
$text['button-save']['nl-nl'] = "Opslaan";
$text['button-save']['pl-pl'] = "";
$text['button-save']['pt-br'] = "Guardar"; //copied from pt-pt
$text['button-save']['pt-pt'] = "Guardar";
$text['button-save']['ro-ro'] = "";
$text['button-save']['ru-ru'] = "Сохранить";
$text['button-save']['sv-se'] = "Spara";
$text['button-save']['uk-ua'] = "";

$text['button-view']['en-us'] = "View";
$text['button-view']['en-gb'] = "View";
$text['button-view']['ar-eg'] = "";
$text['button-view']['de-at'] = "Anzeigen"; //copied from de-de
$text['button-view']['de-ch'] = "Anzeigen"; //copied from de-de
$text['button-view']['de-de'] = "Anzeigen";
$text['button-view']['es-cl'] = "";
$text['button-view']['es-mx'] = "";
$text['button-view']['fr-ca'] = "Vue";
$text['button-view']['fr-fr'] = "Vue";
$text['button-view']['he-il'] = "";
$text['button-view']['it-it'] = "Mostra";
$text['button-view']['nl-nl'] = "Bekijken";
$text['button-view']['pl-pl'] = "";
$text['button-view']['pt-br'] = "";
$text['button-view']['pt-pt'] = "";
$text['button-view']['ro-ro'] = "";
$text['button-view']['ru-ru'] = "";
$text['button-view']['sv-se'] = "Visa";
$text['button-view']['uk-ua'] = "";

$text['button-back']['en-us'] = "Back";
$text['button-back']['en-gb'] = "Back";
$text['button-back']['ar-eg'] = "";
$text['button-back']['de-at'] = "Zurück"; //copied from de-de
$text['button-back']['de-ch'] = "Zurück"; //copied from de-de
$text['button-back']['de-de'] = "Zurück";
$text['button-back']['es-cl'] = "";
$text['button-back']['es-mx'] = "";
$text['button-back']['fr-ca'] = "Retour";
$text['button-back']['fr-fr'] = "Retour";
$text['button-back']['he-il'] = "";
$text['button-back']['it-it'] = "Indietro";
$text['button-back']['nl-nl'] = "Terug";
$text['button-back']['pl-pl'] = "";
$text['button-back']['pt-br'] = "Voltar"; //copied from pt-pt
$text['button-back']['pt-pt'] = "Voltar";
$text['button-back']['ro-ro'] = "";
$text['button-back']['ru-ru'] = "Назад";
$text['button-back']['sv-se'] = "Tillbaka";
$text['button-back']['uk-ua'] = "";

$text['confirm-delete']['en-us'] = "Do you really want to delete this?";
$text['confirm-delete']['en-gb'] = "Do you really want to delete this?";
$text['confirm-delete']['ar-eg'] = "";
$text['confirm-delete']['de-at'] = "Möchten Sie dieses wirklich löschen?"; //copied from de-de
$text['confirm-delete']['de-ch'] = "Möchten Sie dieses wirklich löschen?"; //copied from de-de
$text['confirm-delete']['de-de'] = "Möchten Sie dieses wirklich löschen?";
$text['confirm-delete']['es-cl'] = "";
$text['confirm-delete']['es-mx'] = "";
$text['confirm-delete']['fr-ca'] = "Voulez-vous vraiment supprimer ca";
$text['confirm-delete']['fr-fr'] = "Voulez-vous vraiment supprimer ca";
$text['confirm-delete']['he-il'] = "";
$text['confirm-delete']['it-it'] = "Vuoi veramente cancellarlo?";
$text['confirm-delete']['nl-nl'] = "Wil je dit werkelijk verwijderen?";
$text['confirm-delete']['pl-pl'] = "";
$text['confirm-delete']['pt-br'] = "";
$text['confirm-delete']['pt-pt'] = "";
$text['confirm-delete']['ro-ro'] = "";
$text['confirm-delete']['ru-ru'] = "Вы действительно хотите удалить это?";
$text['confirm-delete']['sv-se'] = "Vill du verkligen ta bort detta?";
$text['confirm-delete']['uk-ua'] = "";

$text['message-add']['en-us'] = "Add Completed";
$text['message-add']['en-gb'] = "Add Completed";
$text['message-add']['ar-eg'] = "";
$text['message-add']['de-at'] = "Erfolgreich hinzugefügt"; //copied from de-de
$text['message-add']['de-ch'] = "Erfolgreich hinzugefügt"; //copied from de-de
$text['message-add']['de-de'] = "Erfolgreich hinzugefügt";
$text['message-add']['es-cl'] = "";
$text['message-add']['es-mx'] = "";
$text['message-add']['fr-ca'] = "Ajouter terminé";
$text['message-add']['fr-fr'] = "Ajouter terminé";
$text['message-add']['he-il'] = "";
$text['message-add']['it-it'] = "Inserimento Completato";
$text['message-add']['nl-nl'] = "Toevoegen gereed";
$text['message-add']['pl-pl'] = "Dodano pomyślnie";
$text['message-add']['pt-br'] = "";
$text['message-add']['pt-pt'] = "";
$text['message-add']['ro-ro'] = "";
$text['message-add']['ru-ru'] = "Добавление выполнено";
$text['message-add']['sv-se'] = "Tillagd";
$text['message-add']['uk-ua'] = "";

$text['message-update']['en-us'] = "Update Completed";
$text['message-update']['en-gb'] = "Update Completed";
$text['message-update']['ar-eg'] = "";
$text['message-update']['de-at'] = "Aktualisierung durchgeführt"; //copied from de-de
$text['message-update']['de-ch'] = "Aktualisierung durchgeführt"; //copied from de-de
$text['message-update']['de-de'] = "Aktualisierung durchgeführt";
$text['message-update']['es-cl'] = "";
$text['message-update']['es-mx'] = "";
$text['message-update']['fr-ca'] = "Mise à jour terminée";
$text['message-update']['fr-fr'] = "Mise à jour terminée";
$text['message-update']['he-il'] = "";
$text['message-update']['it-it'] = "Aggiornamento Completato";
$text['message-update']['nl-nl'] = "Bijwerken gereed";
$text['message-update']['pl-pl'] = "Zaktualizowano pomyślnie";
$text['message-update']['pt-br'] = "";
$text['message-update']['pt-pt'] = "";
$text['message-update']['ro-ro'] = "";
$text['message-update']['ru-ru'] = "Обновление завершено";
$text['message-update']['sv-se'] = "Ändring Utförd";
$text['message-update']['uk-ua'] = "";

$text['message-delete']['en-us'] = "Delete Completed";
$text['message-delete']['en-gb'] = "Delete Completed";
$text['message-delete']['ar-eg'] = "";
$text['message-delete']['de-at'] = "Erfolgreich gelöscht"; //copied from de-de
$text['message-delete']['de-ch'] = "Erfolgreich gelöscht"; //copied from de-de
$text['message-delete']['de-de'] = "Erfolgreich gelöscht";
$text['message-delete']['es-cl'] = "";
$text['message-delete']['es-mx'] = "";
$text['message-delete']['fr-ca'] = "Supprimer terminé";
$text['message-delete']['fr-fr'] = "Supprimer terminé";
$text['message-delete']['he-il'] = "";
$text['message-delete']['it-it'] = "Cancellazione Completato";
$text['message-delete']['nl-nl'] = "Verwijderen gereed";
$text['message-delete']['pl-pl'] = "Usunięto pomyślnie";
$text['message-delete']['pt-br'] = "";
$text['message-delete']['pt-pt'] = "";
$text['message-delete']['ro-ro'] = "";
$text['message-delete']['ru-ru'] = "Удаление завершено";
$text['message-delete']['sv-se'] = "Borttagen";
$text['message-delete']['uk-ua'] = "";

$text['message-required']['en-us'] = "Please provide: ";
$text['message-required']['en-gb'] = "Please provide: ";
$text['message-required']['ar-eg'] = "";
$text['message-required']['de-at'] = "Bitte geben Sie folgendes an:"; //copied from de-de
$text['message-required']['de-ch'] = "Bitte geben Sie folgendes an:"; //copied from de-de
$text['message-required']['de-de'] = "Bitte geben Sie folgendes an:";
$text['message-required']['es-cl'] = "";
$text['message-required']['es-mx'] = "";
$text['message-required']['fr-ca'] = "Veuillez donner";
$text['message-required']['fr-fr'] = "Veuillez donner";
$text['message-required']['he-il'] = "";
$text['message-required']['it-it'] = "Prego fornire:";
$text['message-required']['nl-nl'] = "Geef aub.:";
$text['message-required']['pl-pl'] = "";
$text['message-required']['pt-br'] = "";
$text['message-required']['pt-pt'] = "";
$text['message-required']['ro-ro'] = "";
$text['message-required']['ru-ru'] = "Пожалуйста предоставьте: ";
$text['message-required']['sv-se'] = "Var god ange: ";
$text['message-required']['uk-ua'] = "";

?>
