-- Default settings used by polycom/ccx500/{$mac}.cfg codec preferences
-- Values are codec priority order (lower = higher priority, 0 = disabled)

INSERT INTO v_default_settings (default_setting_uuid, default_setting_category, default_setting_subcategory, default_setting_name, default_setting_value, default_setting_enabled) VALUES (gen_random_uuid(), 'provision', 'polycom_codec_g711a',         'text', '1', 't') ON CONFLICT DO NOTHING;
INSERT INTO v_default_settings (default_setting_uuid, default_setting_category, default_setting_subcategory, default_setting_name, default_setting_value, default_setting_enabled) VALUES (gen_random_uuid(), 'provision', 'polycom_codec_g711mu',        'text', '2', 't') ON CONFLICT DO NOTHING;
INSERT INTO v_default_settings (default_setting_uuid, default_setting_category, default_setting_subcategory, default_setting_name, default_setting_value, default_setting_enabled) VALUES (gen_random_uuid(), 'provision', 'polycom_codec_g722',          'text', '3', 't') ON CONFLICT DO NOTHING;
INSERT INTO v_default_settings (default_setting_uuid, default_setting_category, default_setting_subcategory, default_setting_name, default_setting_value, default_setting_enabled) VALUES (gen_random_uuid(), 'provision', 'polycom_codec_g729ab',        'text', '0', 't') ON CONFLICT DO NOTHING;
INSERT INTO v_default_settings (default_setting_uuid, default_setting_category, default_setting_subcategory, default_setting_name, default_setting_value, default_setting_enabled) VALUES (gen_random_uuid(), 'provision', 'polycom_codec_opus',          'text', '0', 't') ON CONFLICT DO NOTHING;
INSERT INTO v_default_settings (default_setting_uuid, default_setting_category, default_setting_subcategory, default_setting_name, default_setting_value, default_setting_enabled) VALUES (gen_random_uuid(), 'provision', 'polycom_codec_g7221_16kbps',  'text', '0', 't') ON CONFLICT DO NOTHING;
INSERT INTO v_default_settings (default_setting_uuid, default_setting_category, default_setting_subcategory, default_setting_name, default_setting_value, default_setting_enabled) VALUES (gen_random_uuid(), 'provision', 'polycom_codec_g7221_24kbps',  'text', '0', 't') ON CONFLICT DO NOTHING;
INSERT INTO v_default_settings (default_setting_uuid, default_setting_category, default_setting_subcategory, default_setting_name, default_setting_value, default_setting_enabled) VALUES (gen_random_uuid(), 'provision', 'polycom_codec_g7221_32kbps',  'text', '0', 't') ON CONFLICT DO NOTHING;
INSERT INTO v_default_settings (default_setting_uuid, default_setting_category, default_setting_subcategory, default_setting_name, default_setting_value, default_setting_enabled) VALUES (gen_random_uuid(), 'provision', 'polycom_codec_g7221c_24kbps', 'text', '0', 't') ON CONFLICT DO NOTHING;
INSERT INTO v_default_settings (default_setting_uuid, default_setting_category, default_setting_subcategory, default_setting_name, default_setting_value, default_setting_enabled) VALUES (gen_random_uuid(), 'provision', 'polycom_codec_g7221c_32kbps', 'text', '0', 't') ON CONFLICT DO NOTHING;
INSERT INTO v_default_settings (default_setting_uuid, default_setting_category, default_setting_subcategory, default_setting_name, default_setting_value, default_setting_enabled) VALUES (gen_random_uuid(), 'provision', 'polycom_codec_g7221c_48kbps', 'text', '0', 't') ON CONFLICT DO NOTHING;
INSERT INTO v_default_settings (default_setting_uuid, default_setting_category, default_setting_subcategory, default_setting_name, default_setting_value, default_setting_enabled) VALUES (gen_random_uuid(), 'provision', 'polycom_codec_siren14_48kbps','text', '0', 't') ON CONFLICT DO NOTHING;
INSERT INTO v_default_settings (default_setting_uuid, default_setting_category, default_setting_subcategory, default_setting_name, default_setting_value, default_setting_enabled) VALUES (gen_random_uuid(), 'provision', 'polycom_codec_siren22_64kbps','text', '0', 't') ON CONFLICT DO NOTHING;
