<?php
#This file was last reorganized on 19th of September 2017 08:54:24 AM UTC

$text['title-view_email']['en-us'] = "View Email";
$text['title-view_email']['en-gb'] = "View Email";
$text['title-view_email']['ar-eg'] = "";
$text['title-view_email']['de-at'] = "Email anzeigen"; //copied from de-de
$text['title-view_email']['de-ch'] = "Email anzeigen"; //copied from de-de
$text['title-view_email']['de-de'] = "Email anzeigen";
$text['title-view_email']['es-cl'] = "Ver Email";
$text['title-view_email']['es-mx'] = "Ver Email"; //copied from es-cl
$text['title-view_email']['fr-ca'] = "Voir l'email"; //copied from fr-fr
$text['title-view_email']['fr-fr'] = "Voir l'email";
$text['title-view_email']['he-il'] = "";
$text['title-view_email']['it-it'] = "Mostra Email";
$text['title-view_email']['nl-nl'] = "Bekijk E-mail";
$text['title-view_email']['pl-pl'] = "Widok e0maili";
$text['title-view_email']['pt-br'] = "Ver email";
$text['title-view_email']['pt-pt'] = "Ver Email";
$text['title-view_email']['ro-ro'] = "";
$text['title-view_email']['ru-ru'] = "Просмотр Электронной Почты";
$text['title-view_email']['sv-se'] = "Visa E-post";
$text['title-view_email']['uk-ua'] = "";

$text['title-emails']['en-us'] = "Email Logs";
$text['title-emails']['en-gb'] = "Email Logs";
$text['title-emails']['ar-eg'] = "";
$text['title-emails']['de-at'] = "Emails"; //copied from de-de
$text['title-emails']['de-ch'] = "Emails"; //copied from de-de
$text['title-emails']['de-de'] = "Emails";
$text['title-emails']['es-cl'] = "Los Correos Electrónicos";
$text['title-emails']['es-mx'] = "Los Correos Electrónicos"; //copied from es-cl
$text['title-emails']['fr-ca'] = "Journaux de courriel"; //copied from fr-fr
$text['title-emails']['fr-fr'] = "Journaux de courriel";
$text['title-emails']['he-il'] = "";
$text['title-emails']['it-it'] = "Emails";
$text['title-emails']['nl-nl'] = "E-mail log";
$text['title-emails']['pl-pl'] = "E-maile";
$text['title-emails']['pt-br'] = "Emails"; //copied from pt-pt
$text['title-emails']['pt-pt'] = "Emails";
$text['title-emails']['ro-ro'] = "";
$text['title-emails']['ru-ru'] = "Электронная Почта";
$text['title-emails']['sv-se'] = "E-post";
$text['title-emails']['uk-ua'] = "";

$text['message-resend_failed']['en-us'] = "Resend Failed";
$text['message-resend_failed']['en-gb'] = "Resend Failed";
$text['message-resend_failed']['ar-eg'] = "";
$text['message-resend_failed']['de-at'] = "Erneutes Senden Fehlgeschlagen"; //copied from de-de
$text['message-resend_failed']['de-ch'] = "Erneutes Senden Fehlgeschlagen"; //copied from de-de
$text['message-resend_failed']['de-de'] = "Erneutes Senden Fehlgeschlagen";
$text['message-resend_failed']['es-cl'] = "Vuelva a enviar Error";
$text['message-resend_failed']['es-mx'] = "Vuelva a enviar Error"; //copied from es-cl
$text['message-resend_failed']['fr-ca'] = "Le renvoi du message a échoué"; //copied from fr-fr
$text['message-resend_failed']['fr-fr'] = "Le renvoi du message a échoué";
$text['message-resend_failed']['he-il'] = "";
$text['message-resend_failed']['it-it'] = "Rispedimento Fallito";
$text['message-resend_failed']['nl-nl'] = "Herverzend mislukte meldingen";
$text['message-resend_failed']['pl-pl'] = "Próba ponownego wysłania nie powiodła się.";
$text['message-resend_failed']['pt-br'] = "Reenviar falha";
$text['message-resend_failed']['pt-pt'] = "Reenviar Falha";
$text['message-resend_failed']['ro-ro'] = "";
$text['message-resend_failed']['ru-ru'] = "Повторная отправка не удалась";
$text['message-resend_failed']['sv-se'] = "Skicka Misslyckade Igen";
$text['message-resend_failed']['uk-ua'] = "";

$text['message-message_resent']['en-us'] = "Message(s) Resent";
$text['message-message_resent']['en-gb'] = "Message(s) Resent";
$text['message-message_resent']['ar-eg'] = "";
$text['message-message_resent']['de-at'] = "Nachricht erneut gesendet"; //copied from de-de
$text['message-message_resent']['de-ch'] = "Nachricht erneut gesendet"; //copied from de-de
$text['message-message_resent']['de-de'] = "Nachricht erneut gesendet";
$text['message-message_resent']['es-cl'] = "Mensaje Resent";
$text['message-message_resent']['es-mx'] = "Mensaje Resent"; //copied from es-cl
$text['message-message_resent']['fr-ca'] = "Le message a été renvoyé"; //copied from fr-fr
$text['message-message_resent']['fr-fr'] = "Le message a été renvoyé";
$text['message-message_resent']['he-il'] = "";
$text['message-message_resent']['it-it'] = "Messaggio Rispedito";
$text['message-message_resent']['nl-nl'] = "Melding(en) opnieuw verzonden";
$text['message-message_resent']['pl-pl'] = "Wiadomość została wysłana ponownie";
$text['message-message_resent']['pt-br'] = "Mensagem reenviada";
$text['message-message_resent']['pt-pt'] = "Mensagem Reenviada";
$text['message-message_resent']['ro-ro'] = "";
$text['message-message_resent']['ru-ru'] = "Это сообщение было отправлено повторно";
$text['message-message_resent']['sv-se'] = "Meddelande Skickades";
$text['message-message_resent']['uk-ua'] = "";

$text['message-invalid_email']['en-us'] = "Invalid Email";
$text['message-invalid_email']['en-gb'] = "Invalid Email";
$text['message-invalid_email']['ar-eg'] = "";
$text['message-invalid_email']['de-at'] = "Ungültige Email-Adresse"; //copied from de-de
$text['message-invalid_email']['de-ch'] = "Ungültige Email-Adresse"; //copied from de-de
$text['message-invalid_email']['de-de'] = "Ungültige Email-Adresse";
$text['message-invalid_email']['es-cl'] = "No Válida de Correo Electrónico";
$text['message-invalid_email']['es-mx'] = "No Válida de Correo Electrónico"; //copied from es-cl
$text['message-invalid_email']['fr-ca'] = "Adresse de courriel invalide"; //copied from fr-fr
$text['message-invalid_email']['fr-fr'] = "Adresse de courriel invalide";
$text['message-invalid_email']['he-il'] = "";
$text['message-invalid_email']['it-it'] = "Email non Valida";
$text['message-invalid_email']['nl-nl'] = "Ongeldig E-mail adres";
$text['message-invalid_email']['pl-pl'] = "Nieprawidłowy adres email";
$text['message-invalid_email']['pt-br'] = "Endereço de E-mail Inválido";
$text['message-invalid_email']['pt-pt'] = "E-mail Inválido";
$text['message-invalid_email']['ro-ro'] = "";
$text['message-invalid_email']['ru-ru'] = "Несуществующий адрес электронной почты";
$text['message-invalid_email']['sv-se'] = "Ogiltig E-postadress";
$text['message-invalid_email']['uk-ua'] = "";

$text['message-decoding_error']['en-us'] = "MIME Message Decoding Error";
$text['message-decoding_error']['en-gb'] = "MIME Message Decoding Error";
$text['message-decoding_error']['ar-eg'] = "";
$text['message-decoding_error']['de-at'] = "Fehler bei der Dekodierung der MIME Nachricht"; //copied from de-de
$text['message-decoding_error']['de-ch'] = "Fehler bei der Dekodierung der MIME Nachricht"; //copied from de-de
$text['message-decoding_error']['de-de'] = "Fehler bei der Dekodierung der MIME Nachricht";
$text['message-decoding_error']['es-cl'] = "MIME Mensaje Descodificación  de error";
$text['message-decoding_error']['es-mx'] = "MIME Mensaje Descodificación  de error"; //copied from es-cl
$text['message-decoding_error']['fr-ca'] = "Erreur de décodage du message MIME"; //copied from fr-fr
$text['message-decoding_error']['fr-fr'] = "Erreur de décodage du message MIME";
$text['message-decoding_error']['he-il'] = "";
$text['message-decoding_error']['it-it'] = "MIME Message Decoding Error";
$text['message-decoding_error']['nl-nl'] = "MIME bericht decoderingsfout";
$text['message-decoding_error']['pl-pl'] = "Błąd dekodowania wiadomości MIME";
$text['message-decoding_error']['pt-br'] = "MIME mensagem decoding erro";
$text['message-decoding_error']['pt-pt'] = "MIME Mensagem Decoding erro";
$text['message-decoding_error']['ro-ro'] = "";
$text['message-decoding_error']['ru-ru'] = "Ошибка декодирования MIME сообщения";
$text['message-decoding_error']['sv-se'] = "MIME Message Decoding Erro";
$text['message-decoding_error']['uk-ua'] = "";

$text['message-download_failed']['en-us'] = "Download Failed";
$text['message-download_failed']['en-gb'] = "Download Failed";
$text['message-download_failed']['ar-eg'] = "Download Failed";
$text['message-download_failed']['de-at'] = "Download Failed";
$text['message-download_failed']['de-ch'] = "Download Failed";
$text['message-download_failed']['de-de'] = "Download Failed";
$text['message-download_failed']['es-cl'] = "Download Failed";
$text['message-download_failed']['es-mx'] = "Download Failed";
$text['message-download_failed']['fr-ca'] = "Download Failed";
$text['message-download_failed']['fr-fr'] = "Download Failed";
$text['message-download_failed']['he-il'] = "Download Failed";
$text['message-download_failed']['it-it'] = "Download Failed";
$text['message-download_failed']['nl-nl'] = "Ophalen mislukt";
$text['message-download_failed']['pl-pl'] = "Download Failed";
$text['message-download_failed']['pt-br'] = "Download Failed";
$text['message-download_failed']['pt-pt'] = "Download Failed";
$text['message-download_failed']['ro-ro'] = "Download Failed";
$text['message-download_failed']['ru-ru'] = "Download Failed";
$text['message-download_failed']['sv-se'] = "Download Failed";
$text['message-download_failed']['uk-ua'] = "Download Failed";

$text['label-type_voicemail']['en-us'] = "Voicemail";
$text['label-type_voicemail']['en-gb'] = "Voicemail";
$text['label-type_voicemail']['ar-eg'] = "";
$text['label-type_voicemail']['de-at'] = "Mailbox"; //copied from de-de
$text['label-type_voicemail']['de-ch'] = "Mailbox"; //copied from de-de
$text['label-type_voicemail']['de-de'] = "Mailbox";
$text['label-type_voicemail']['es-cl'] = "Correo de Voz";
$text['label-type_voicemail']['es-mx'] = "Correo de Voz"; //copied from es-cl
$text['label-type_voicemail']['fr-ca'] = "Messagerie vocale"; //copied from fr-fr
$text['label-type_voicemail']['fr-fr'] = "Messagerie vocale";
$text['label-type_voicemail']['he-il'] = "";
$text['label-type_voicemail']['it-it'] = "Casella Vocale";
$text['label-type_voicemail']['nl-nl'] = "ANtwoord apparaat";
$text['label-type_voicemail']['pl-pl'] = "Poczta głosowa";
$text['label-type_voicemail']['pt-br'] = "Correio de voz";
$text['label-type_voicemail']['pt-pt'] = "Correio de Voz";
$text['label-type_voicemail']['ro-ro'] = "";
$text['label-type_voicemail']['ru-ru'] = "Голосовая Почта";
$text['label-type_voicemail']['sv-se'] = "Röstbrevlåda";
$text['label-type_voicemail']['uk-ua'] = "";

$text['label-type_missed']['en-us'] = "Missed Call";
$text['label-type_missed']['en-gb'] = "Missed Call";
$text['label-type_missed']['ar-eg'] = "";
$text['label-type_missed']['de-at'] = "Verpasster Anruf"; //copied from de-de
$text['label-type_missed']['de-ch'] = "Verpasster Anruf"; //copied from de-de
$text['label-type_missed']['de-de'] = "Verpasster Anruf";
$text['label-type_missed']['es-cl'] = "Llamada Perdida";
$text['label-type_missed']['es-mx'] = "Llamada Perdida"; //copied from es-cl
$text['label-type_missed']['fr-ca'] = "Appel Manqué"; //copied from fr-fr
$text['label-type_missed']['fr-fr'] = "Appel Manqué";
$text['label-type_missed']['he-il'] = "שיחה שלא נענתה";
$text['label-type_missed']['it-it'] = "Chiamata Persa";
$text['label-type_missed']['nl-nl'] = "Gemiste oproep";
$text['label-type_missed']['pl-pl'] = "Nieodebrane Połączenie";
$text['label-type_missed']['pt-br'] = "Chamada Perdida"; //copied from pt-pt
$text['label-type_missed']['pt-pt'] = "Chamada Perdida";
$text['label-type_missed']['ro-ro'] = "";
$text['label-type_missed']['ru-ru'] = "Пропущенный вызов";
$text['label-type_missed']['sv-se'] = "Missat Samtal";
$text['label-type_missed']['uk-ua'] = "пропущений Дзвінок";

$text['label-type_email2fax']['en-us'] = "Email to fax report";
$text['label-type_email2fax']['en-gb'] = "Email to fax report";
$text['label-type_email2fax']['ar-eg'] = "";
$text['label-type_email2fax']['de-at'] = "Email zu Fax Auswertung"; //copied from de-de
$text['label-type_email2fax']['de-ch'] = "Email zu Fax Auswertung"; //copied from de-de
$text['label-type_email2fax']['de-de'] = "Email zu Fax Auswertung";
$text['label-type_email2fax']['es-cl'] = "";
$text['label-type_email2fax']['es-mx'] = "";
$text['label-type_email2fax']['fr-ca'] = "Rapport d'email à fax ";
$text['label-type_email2fax']['fr-fr'] = "Rapport d'email à fax ";
$text['label-type_email2fax']['he-il'] = "";
$text['label-type_email2fax']['it-it'] = "Rapporto Mail to Fax";
$text['label-type_email2fax']['nl-nl'] = "E-Mail naar fax rapport";
$text['label-type_email2fax']['pl-pl'] = "";
$text['label-type_email2fax']['pt-br'] = "";
$text['label-type_email2fax']['pt-pt'] = "";
$text['label-type_email2fax']['ro-ro'] = "";
$text['label-type_email2fax']['ru-ru'] = "Отчет Электронной Почты на факс";
$text['label-type_email2fax']['sv-se'] = "E-post till fax rapport";
$text['label-type_email2fax']['uk-ua'] = "";

$text['label-type']['en-us'] = "Type";
$text['label-type']['en-gb'] = "Type";
$text['label-type']['ar-eg'] = "";
$text['label-type']['de-at'] = "Art"; //copied from de-de
$text['label-type']['de-ch'] = "Art"; //copied from de-de
$text['label-type']['de-de'] = "Art";
$text['label-type']['es-cl'] = "Tipo";
$text['label-type']['es-mx'] = "Tipo"; //copied from es-cl
$text['label-type']['fr-ca'] = "Type"; //copied from fr-fr
$text['label-type']['fr-fr'] = "Type";
$text['label-type']['he-il'] = "";
$text['label-type']['it-it'] = "Tipo";
$text['label-type']['nl-nl'] = "Type";
$text['label-type']['pl-pl'] = "Typ";
$text['label-type']['pt-br'] = "Tipo"; //copied from pt-pt
$text['label-type']['pt-pt'] = "Tipo";
$text['label-type']['ro-ro'] = "";
$text['label-type']['ru-ru'] = "Тип";
$text['label-type']['sv-se'] = "Typ";
$text['label-type']['uk-ua'] = "";

$text['label-to']['en-us'] = "To";
$text['label-to']['en-gb'] = "To";
$text['label-to']['ar-eg'] = "";
$text['label-to']['de-at'] = "An"; //copied from de-de
$text['label-to']['de-ch'] = "An"; //copied from de-de
$text['label-to']['de-de'] = "An";
$text['label-to']['es-cl'] = "Final";
$text['label-to']['es-mx'] = "Final"; //copied from es-cl
$text['label-to']['fr-ca'] = "À"; //copied from fr-fr
$text['label-to']['fr-fr'] = "À";
$text['label-to']['he-il'] = "";
$text['label-to']['it-it'] = "A";
$text['label-to']['nl-nl'] = "Aan";
$text['label-to']['pl-pl'] = "Do";
$text['label-to']['pt-br'] = "Final"; //copied from pt-pt
$text['label-to']['pt-pt'] = "Final";
$text['label-to']['ro-ro'] = "";
$text['label-to']['ru-ru'] = "To";
$text['label-to']['sv-se'] = "Till";
$text['label-to']['uk-ua'] = "";

$text['label-subject']['en-us'] = "Subject";
$text['label-subject']['en-gb'] = "Subject";
$text['label-subject']['ar-eg'] = "";
$text['label-subject']['de-at'] = "Betreff"; //copied from de-de
$text['label-subject']['de-ch'] = "Betreff"; //copied from de-de
$text['label-subject']['de-de'] = "Betreff";
$text['label-subject']['es-cl'] = "Sujeto";
$text['label-subject']['es-mx'] = "Sujeto"; //copied from es-cl
$text['label-subject']['fr-ca'] = "Sujet"; //copied from fr-fr
$text['label-subject']['fr-fr'] = "Sujet";
$text['label-subject']['he-il'] = "";
$text['label-subject']['it-it'] = "Oggetto";
$text['label-subject']['nl-nl'] = "Onderwerp";
$text['label-subject']['pl-pl'] = "Tytuł";
$text['label-subject']['pt-br'] = "Assunto"; //copied from pt-pt
$text['label-subject']['pt-pt'] = "Assunto";
$text['label-subject']['ro-ro'] = "";
$text['label-subject']['ru-ru'] = "Предмет";
$text['label-subject']['sv-se'] = "Ämne";
$text['label-subject']['uk-ua'] = "";

$text['label-status_failed']['en-us'] = "Failed";
$text['label-status_failed']['en-gb'] = "Failed";
$text['label-status_failed']['ar-eg'] = "";
$text['label-status_failed']['de-at'] = "Fehlgeschlagen"; //copied from de-de
$text['label-status_failed']['de-ch'] = "Fehlgeschlagen"; //copied from de-de
$text['label-status_failed']['de-de'] = "Fehlgeschlagen";
$text['label-status_failed']['es-cl'] = "Fracasado";
$text['label-status_failed']['es-mx'] = "Fracasado"; //copied from es-cl
$text['label-status_failed']['fr-ca'] = "Échoué"; //copied from fr-fr
$text['label-status_failed']['fr-fr'] = "Échoué";
$text['label-status_failed']['he-il'] = "";
$text['label-status_failed']['it-it'] = "Fallito";
$text['label-status_failed']['nl-nl'] = "Mislukt";
$text['label-status_failed']['pl-pl'] = "Nie udało się";
$text['label-status_failed']['pt-br'] = "Falha";
$text['label-status_failed']['pt-pt'] = "Fracassado";
$text['label-status_failed']['ro-ro'] = "";
$text['label-status_failed']['ru-ru'] = "Не удалось";
$text['label-status_failed']['sv-se'] = "Misslyckades";
$text['label-status_failed']['uk-ua'] = "";

$text['label-status']['en-us'] = "Status";
$text['label-status']['en-gb'] = "Status";
$text['label-status']['ar-eg'] = "";
$text['label-status']['de-at'] = "Status"; //copied from de-de
$text['label-status']['de-ch'] = "Status"; //copied from de-de
$text['label-status']['de-de'] = "Status";
$text['label-status']['es-cl'] = "Estado";
$text['label-status']['es-mx'] = "Estado"; //copied from es-cl
$text['label-status']['fr-ca'] = "Statut"; //copied from fr-fr
$text['label-status']['fr-fr'] = "Statut";
$text['label-status']['he-il'] = "";
$text['label-status']['it-it'] = "Stato";
$text['label-status']['nl-nl'] = "Status";
$text['label-status']['pl-pl'] = "Status";
$text['label-status']['pt-br'] = "Estado"; //copied from pt-pt
$text['label-status']['pt-pt'] = "Estado";
$text['label-status']['ro-ro'] = "";
$text['label-status']['ru-ru'] = "Статус";
$text['label-status']['sv-se'] = "Status";
$text['label-status']['uk-ua'] = "";

$text['label-sent']['en-us'] = "Sent";
$text['label-sent']['en-gb'] = "Sent";
$text['label-sent']['ar-eg'] = "";
$text['label-sent']['de-at'] = "Gesendet"; //copied from de-de
$text['label-sent']['de-ch'] = "Gesendet"; //copied from de-de
$text['label-sent']['de-de'] = "Gesendet";
$text['label-sent']['es-cl'] = "Enviado";
$text['label-sent']['es-mx'] = "Enviado"; //copied from es-cl
$text['label-sent']['fr-ca'] = "Envoyé"; //copied from fr-fr
$text['label-sent']['fr-fr'] = "Envoyé";
$text['label-sent']['he-il'] = "";
$text['label-sent']['it-it'] = "Inviato";
$text['label-sent']['nl-nl'] = "Verzonden";
$text['label-sent']['pl-pl'] = "Wysłano";
$text['label-sent']['pt-br'] = "Enviados"; //copied from pt-pt
$text['label-sent']['pt-pt'] = "Enviados";
$text['label-sent']['ro-ro'] = "";
$text['label-sent']['ru-ru'] = "Отправленный";
$text['label-sent']['sv-se'] = "Skickat";
$text['label-sent']['uk-ua'] = "";

$text['label-resend']['en-us'] = "Resend";
$text['label-resend']['en-gb'] = "Resend";
$text['label-resend']['ar-eg'] = "";
$text['label-resend']['de-at'] = "Erneut senden"; //copied from de-de
$text['label-resend']['de-ch'] = "Erneut senden"; //copied from de-de
$text['label-resend']['de-de'] = "Erneut senden";
$text['label-resend']['es-cl'] = "Vuelva a Enviar";
$text['label-resend']['es-mx'] = "Vuelva a Enviar"; //copied from es-cl
$text['label-resend']['fr-ca'] = "Renvoyer"; //copied from fr-fr
$text['label-resend']['fr-fr'] = "Renvoyer";
$text['label-resend']['he-il'] = "";
$text['label-resend']['it-it'] = "Rispedisci";
$text['label-resend']['nl-nl'] = "Herzend";
$text['label-resend']['pl-pl'] = "Wyślij ponownie";
$text['label-resend']['pt-br'] = "Reenviar"; //copied from pt-pt
$text['label-resend']['pt-pt'] = "Reenviar";
$text['label-resend']['ro-ro'] = "";
$text['label-resend']['ru-ru'] = "Отправить";
$text['label-resend']['sv-se'] = "Skicka Igen";
$text['label-resend']['uk-ua'] = "";

$text['label-reference_cdr']['en-us'] = "CDR";
$text['label-reference_cdr']['en-gb'] = "CDR";
$text['label-reference_cdr']['ar-eg'] = "";
$text['label-reference_cdr']['de-at'] = "CDR"; //copied from de-de
$text['label-reference_cdr']['de-ch'] = "CDR"; //copied from de-de
$text['label-reference_cdr']['de-de'] = "CDR";
$text['label-reference_cdr']['es-cl'] = "RDL";
$text['label-reference_cdr']['es-mx'] = "RDL"; //copied from es-cl
$text['label-reference_cdr']['fr-ca'] = "Historique Des Appels"; //copied from fr-fr
$text['label-reference_cdr']['fr-fr'] = "Historique Des Appels";
$text['label-reference_cdr']['he-il'] = "";
$text['label-reference_cdr']['it-it'] = "CDR";
$text['label-reference_cdr']['nl-nl'] = "CDR";
$text['label-reference_cdr']['pl-pl'] = "Wykaz rozmów";
$text['label-reference_cdr']['pt-br'] = "RC"; //copied from pt-pt
$text['label-reference_cdr']['pt-pt'] = "RC";
$text['label-reference_cdr']['ro-ro'] = "";
$text['label-reference_cdr']['ru-ru'] = "CDR - История Вызовов";
$text['label-reference_cdr']['sv-se'] = "CDR";
$text['label-reference_cdr']['uk-ua'] = "";

$text['label-reference']['en-us'] = "Reference";
$text['label-reference']['en-gb'] = "Reference";
$text['label-reference']['ar-eg'] = "";
$text['label-reference']['de-at'] = "Referenz"; //copied from de-de
$text['label-reference']['de-ch'] = "Referenz"; //copied from de-de
$text['label-reference']['de-de'] = "Referenz";
$text['label-reference']['es-cl'] = "Referencia";
$text['label-reference']['es-mx'] = "Referencia"; //copied from es-cl
$text['label-reference']['fr-ca'] = "Référence"; //copied from fr-fr
$text['label-reference']['fr-fr'] = "Référence";
$text['label-reference']['he-il'] = "";
$text['label-reference']['it-it'] = "Riferimento";
$text['label-reference']['nl-nl'] = "Referentie";
$text['label-reference']['pl-pl'] = "Odniesienie";
$text['label-reference']['pt-br'] = "Referência";
$text['label-reference']['pt-pt'] = "Referencia";
$text['label-reference']['ro-ro'] = "";
$text['label-reference']['ru-ru'] = "Справка";
$text['label-reference']['sv-se'] = "Referens";
$text['label-reference']['uk-ua'] = "";

$text['label-message_view']['en-us'] = "View";
$text['label-message_view']['en-gb'] = "View";
$text['label-message_view']['ar-eg'] = "";
$text['label-message_view']['de-at'] = "Anzeigen"; //copied from de-de
$text['label-message_view']['de-ch'] = "Anzeigen"; //copied from de-de
$text['label-message_view']['de-de'] = "Anzeigen";
$text['label-message_view']['es-cl'] = "Ver";
$text['label-message_view']['es-mx'] = "Ver"; //copied from es-cl
$text['label-message_view']['fr-ca'] = "Voir"; //copied from fr-fr
$text['label-message_view']['fr-fr'] = "Voir";
$text['label-message_view']['he-il'] = "";
$text['label-message_view']['it-it'] = "Mostra";
$text['label-message_view']['nl-nl'] = "Bekijk";
$text['label-message_view']['pl-pl'] = "Widok";
$text['label-message_view']['pt-br'] = "Visualizar";
$text['label-message_view']['pt-pt'] = "Vista";
$text['label-message_view']['ro-ro'] = "";
$text['label-message_view']['ru-ru'] = "Посмотреть";
$text['label-message_view']['sv-se'] = "Visa";
$text['label-message_view']['uk-ua'] = "";

$text['label-message']['en-us'] = "Message";
$text['label-message']['en-gb'] = "Message";
$text['label-message']['ar-eg'] = "";
$text['label-message']['de-at'] = "Nachricht"; //copied from de-de
$text['label-message']['de-ch'] = "Nachricht"; //copied from de-de
$text['label-message']['de-de'] = "Nachricht";
$text['label-message']['es-cl'] = "Mensaje";
$text['label-message']['es-mx'] = "Mensaje"; //copied from es-cl
$text['label-message']['fr-ca'] = "Message"; //copied from fr-fr
$text['label-message']['fr-fr'] = "Message";
$text['label-message']['he-il'] = "";
$text['label-message']['it-it'] = "Messaggio";
$text['label-message']['nl-nl'] = "Melding";
$text['label-message']['pl-pl'] = "Wiadomość";
$text['label-message']['pt-br'] = "Mensagem"; //copied from pt-pt
$text['label-message']['pt-pt'] = "Mensagem";
$text['label-message']['ro-ro'] = "";
$text['label-message']['ru-ru'] = "Сообщение";
$text['label-message']['sv-se'] = "Meddelande";
$text['label-message']['uk-ua'] = "";

$text['label-from']['en-us'] = "From";
$text['label-from']['en-gb'] = "From";
$text['label-from']['ar-eg'] = "";
$text['label-from']['de-at'] = "Von"; //copied from de-de
$text['label-from']['de-ch'] = "Von"; //copied from de-de
$text['label-from']['de-de'] = "Von";
$text['label-from']['es-cl'] = "Desde";
$text['label-from']['es-mx'] = "Desde"; //copied from es-cl
$text['label-from']['fr-ca'] = "De"; //copied from fr-fr
$text['label-from']['fr-fr'] = "De";
$text['label-from']['he-il'] = "";
$text['label-from']['it-it'] = "Da";
$text['label-from']['nl-nl'] = "Van";
$text['label-from']['pl-pl'] = "Od";
$text['label-from']['pt-br'] = "Começo";
$text['label-from']['pt-pt'] = "A Partir De";
$text['label-from']['ro-ro'] = "";
$text['label-from']['ru-ru'] = "Из";
$text['label-from']['sv-se'] = "Från";
$text['label-from']['uk-ua'] = "";

$text['label-download']['en-us'] = "Download";
$text['label-download']['en-gb'] = "Download";
$text['label-download']['ar-eg'] = "";
$text['label-download']['de-at'] = "Herunterladen"; //copied from de-de
$text['label-download']['de-ch'] = "Herunterladen"; //copied from de-de
$text['label-download']['de-de'] = "Herunterladen";
$text['label-download']['es-cl'] = "Descargar";
$text['label-download']['es-mx'] = "Descargar"; //copied from es-cl
$text['label-download']['fr-ca'] = "Télécharger"; //copied from fr-fr
$text['label-download']['fr-fr'] = "Télécharger";
$text['label-download']['he-il'] = "";
$text['label-download']['it-it'] = "Scarica";
$text['label-download']['nl-nl'] = "Ophalen";
$text['label-download']['pl-pl'] = "Pobierz";
$text['label-download']['pt-br'] = "Download";
$text['label-download']['pt-pt'] = "Descarregar";
$text['label-download']['ro-ro'] = "";
$text['label-download']['ru-ru'] = "Загрузить";
$text['label-download']['sv-se'] = "Ladda Ned";
$text['label-download']['uk-ua'] = "";

$text['label-attachment']['en-us'] = "Attachment";
$text['label-attachment']['en-gb'] = "Attachment";
$text['label-attachment']['ar-eg'] = "";
$text['label-attachment']['de-at'] = "Anhang"; //copied from de-de
$text['label-attachment']['de-ch'] = "Anhang"; //copied from de-de
$text['label-attachment']['de-de'] = "Anhang";
$text['label-attachment']['es-cl'] = "Accesorio";
$text['label-attachment']['es-mx'] = "Accesorio"; //copied from es-cl
$text['label-attachment']['fr-ca'] = "Pièce jointe"; //copied from fr-fr
$text['label-attachment']['fr-fr'] = "Pièce jointe";
$text['label-attachment']['he-il'] = "";
$text['label-attachment']['it-it'] = "Allegato";
$text['label-attachment']['nl-nl'] = "Aanhangsel";
$text['label-attachment']['pl-pl'] = "Załącznik";
$text['label-attachment']['pt-br'] = "Acessório";
$text['label-attachment']['pt-pt'] = "Accesorio";
$text['label-attachment']['ro-ro'] = "";
$text['label-attachment']['ru-ru'] = "Приложение";
$text['label-attachment']['sv-se'] = "Bifogat";
$text['label-attachment']['uk-ua'] = "";

$text['header-view_email']['en-us'] = "View Email";
$text['header-view_email']['en-gb'] = "View Email";
$text['header-view_email']['ar-eg'] = "";
$text['header-view_email']['de-at'] = "Email anzeigen"; //copied from de-de
$text['header-view_email']['de-ch'] = "Email anzeigen"; //copied from de-de
$text['header-view_email']['de-de'] = "Email anzeigen";
$text['header-view_email']['es-cl'] = "Ver Email";
$text['header-view_email']['es-mx'] = "Ver Email"; //copied from es-cl
$text['header-view_email']['fr-ca'] = "Voir l'email"; //copied from fr-fr
$text['header-view_email']['fr-fr'] = "Voir l'email";
$text['header-view_email']['he-il'] = "";
$text['header-view_email']['it-it'] = "Mostra Email";
$text['header-view_email']['nl-nl'] = "Bekijk E-mail";
$text['header-view_email']['pl-pl'] = "Podgląd e-maili";
$text['header-view_email']['pt-br'] = "Visualizar email";
$text['header-view_email']['pt-pt'] = "Ver Email";
$text['header-view_email']['ro-ro'] = "";
$text['header-view_email']['ru-ru'] = "Просмотр Электронной Почты";
$text['header-view_email']['sv-se'] = "Visa E-post";
$text['header-view_email']['uk-ua'] = "";

$text['header-emails']['en-us'] = "Emails";
$text['header-emails']['en-gb'] = "Emails";
$text['header-emails']['ar-eg'] = "";
$text['header-emails']['de-at'] = "Emails"; //copied from de-de
$text['header-emails']['de-ch'] = "Emails"; //copied from de-de
$text['header-emails']['de-de'] = "Emails";
$text['header-emails']['es-cl'] = "Los Correos Electrónico";
$text['header-emails']['es-mx'] = "Los Correos Electrónico"; //copied from es-cl
$text['header-emails']['fr-ca'] = "Courriels"; //copied from fr-fr
$text['header-emails']['fr-fr'] = "Courriels";
$text['header-emails']['he-il'] = "";
$text['header-emails']['it-it'] = "Emails";
$text['header-emails']['nl-nl'] = "E-mails";
$text['header-emails']['pl-pl'] = "E-maile";
$text['header-emails']['pt-br'] = "Emails"; //copied from pt-pt
$text['header-emails']['pt-pt'] = "Emails";
$text['header-emails']['ro-ro'] = "";
$text['header-emails']['ru-ru'] = "Сообщения Электронной Почты";
$text['header-emails']['sv-se'] = "E-post";
$text['header-emails']['uk-ua'] = "";

$text['header-settings']['en-us'] = "Settings";
$text['header-settings']['en-gb'] = "Settings";
$text['header-settings']['ar-eg'] = "";
$text['header-settings']['de-at'] = "";
$text['header-settings']['de-ch'] = "";
$text['header-settings']['de-de'] = "";
$text['header-settings']['es-cl'] = "";
$text['header-settings']['es-mx'] = "";
$text['header-settings']['fr-ca'] = "Paramètres";
$text['header-settings']['fr-fr'] = "Paramètres";
$text['header-settings']['he-il'] = "";
$text['header-settings']['it-it'] = "";
$text['header-settings']['nl-nl'] = "Instellingen";
$text['header-settings']['pl-pl'] = "";
$text['header-settings']['pt-br'] = "";
$text['header-settings']['pt-pt'] = "";
$text['header-settings']['ro-ro'] = "";
$text['header-settings']['ru-ru'] = "";
$text['header-settings']['sv-se'] = "";
$text['header-settings']['uk-ua'] = "";

$text['header-connection']['en-us'] = "Connection";
$text['header-connection']['en-gb'] = "Connection";
$text['header-connection']['ar-eg'] = "";
$text['header-connection']['de-at'] = "";
$text['header-connection']['de-ch'] = "";
$text['header-connection']['de-de'] = "";
$text['header-connection']['es-cl'] = "";
$text['header-connection']['es-mx'] = "";
$text['header-connection']['fr-ca'] = "Connexion";
$text['header-connection']['fr-fr'] = "Connexion";
$text['header-connection']['he-il'] = "";
$text['header-connection']['it-it'] = "";
$text['header-connection']['nl-nl'] = "Verbinding";
$text['header-connection']['pl-pl'] = "";
$text['header-connection']['pt-br'] = "";
$text['header-connection']['pt-pt'] = "";
$text['header-connection']['ro-ro'] = "";
$text['header-connection']['ru-ru'] = "";
$text['header-connection']['sv-se'] = "";
$text['header-connection']['uk-ua'] = "";

$text['header-result']['en-us'] = "Result";
$text['header-result']['en-gb'] = "Result";
$text['header-result']['ar-eg'] = "";
$text['header-result']['de-at'] = "";
$text['header-result']['de-ch'] = "";
$text['header-result']['de-de'] = "";
$text['header-result']['es-cl'] = "";
$text['header-result']['es-mx'] = "";
$text['header-result']['fr-ca'] = "Résultat ";
$text['header-result']['fr-fr'] = "Résultat ";
$text['header-result']['he-il'] = "";
$text['header-result']['it-it'] = "";
$text['header-result']['nl-nl'] = "Resultaat";
$text['header-result']['pl-pl'] = "";
$text['header-result']['pt-br'] = "";
$text['header-result']['pt-pt'] = "";
$text['header-result']['ro-ro'] = "";
$text['header-result']['ru-ru'] = "";
$text['header-result']['sv-se'] = "";
$text['header-result']['uk-ua'] = "";

$text['description-emails']['en-us'] = "Manage failed email messages.";
$text['description-emails']['en-gb'] = "Manage failed email messages.";
$text['description-emails']['ar-eg'] = "";
$text['description-emails']['de-at'] = "Fehlgeschlagene Email-Nachrichten verwalten."; //copied from de-de
$text['description-emails']['de-ch'] = "Fehlgeschlagene Email-Nachrichten verwalten."; //copied from de-de
$text['description-emails']['de-de'] = "Fehlgeschlagene Email-Nachrichten verwalten.";
$text['description-emails']['es-cl'] = "Gestionar los mensajes fallidos.";
$text['description-emails']['es-mx'] = "Gestionar los mensajes fallidos."; //copied from es-cl
$text['description-emails']['fr-ca'] = "Gérer les courriels échoués."; //copied from fr-fr
$text['description-emails']['fr-fr'] = "Gérer les courriels échoués.";
$text['description-emails']['he-il'] = "";
$text['description-emails']['it-it'] = "Gestisce i messaggi email falliti.";
$text['description-emails']['nl-nl'] = "Beheer mislukte E-mail berichten.";
$text['description-emails']['pl-pl'] = "Zarządzaj wiadomościami e-mail, które nie zostały wysłane.";
$text['description-emails']['pt-br'] = "Gerenciar mensagens de email que falharam ";
$text['description-emails']['pt-pt'] = "Gerenciar mensagens de e-mail falhou.";
$text['description-emails']['ro-ro'] = "";
$text['description-emails']['ru-ru'] = "Управление ошибочными сообщениями электронной почты.";
$text['description-emails']['sv-se'] = "Hantera misslyckade e-post meddelanden.";
$text['description-emails']['uk-ua'] = "";

$text['button-test']['en-us'] = "Test";
$text['button-test']['en-gb'] = "Test";
$text['button-test']['ar-eg'] = "";
$text['button-test']['de-at'] = "";
$text['button-test']['de-ch'] = "";
$text['button-test']['de-de'] = "";
$text['button-test']['es-cl'] = "";
$text['button-test']['es-mx'] = "";
$text['button-test']['fr-ca'] = "Test";
$text['button-test']['fr-fr'] = "Test";
$text['button-test']['he-il'] = "";
$text['button-test']['it-it'] = "";
$text['button-test']['nl-nl'] = "Test";
$text['button-test']['pl-pl'] = "";
$text['button-test']['pt-br'] = "";
$text['button-test']['pt-pt'] = "";
$text['button-test']['ro-ro'] = "";
$text['button-test']['ru-ru'] = "";
$text['button-test']['sv-se'] = "";
$text['button-test']['uk-ua'] = "";

$text['button-send']['en-us'] = "Send";
$text['button-send']['en-gb'] = "Send";
$text['button-send']['ar-eg'] = "";
$text['button-send']['de-at'] = "";
$text['button-send']['de-ch'] = "";
$text['button-send']['de-de'] = "";
$text['button-send']['es-cl'] = "";
$text['button-send']['es-mx'] = "";
$text['button-send']['fr-ca'] = "Envoyer";
$text['button-send']['fr-fr'] = "Envoyer";
$text['button-send']['he-il'] = "";
$text['button-send']['it-it'] = "";
$text['button-send']['nl-nl'] = "Zend";
$text['button-send']['pl-pl'] = "";
$text['button-send']['pt-br'] = "";
$text['button-send']['pt-pt'] = "";
$text['button-send']['ro-ro'] = "";
$text['button-send']['ru-ru'] = "";
$text['button-send']['sv-se'] = "";
$text['button-send']['uk-ua'] = "";

$text['button-close']['en-us'] = "Close";
$text['button-close']['en-gb'] = "Close";
$text['button-close']['ar-eg'] = "";
$text['button-close']['de-at'] = "";
$text['button-close']['de-ch'] = "";
$text['button-close']['de-de'] = "";
$text['button-close']['es-cl'] = "";
$text['button-close']['es-mx'] = "";
$text['button-close']['fr-ca'] = "Close";
$text['button-close']['fr-fr'] = "Close";
$text['button-close']['he-il'] = "";
$text['button-close']['it-it'] = "";
$text['button-close']['nl-nl'] = "Sluit";
$text['button-close']['pl-pl'] = "";
$text['button-close']['pt-br'] = "";
$text['button-close']['pt-pt'] = "";
$text['button-close']['ro-ro'] = "";
$text['button-close']['ru-ru'] = "";
$text['button-close']['sv-se'] = "";
$text['button-close']['uk-ua'] = "";

$text['button-resend']['en-us'] = "Resend";
$text['button-resend']['en-gb'] = "Resend";
$text['button-resend']['ar-eg'] = "";
$text['button-resend']['de-at'] = "Erneut senden"; //copied from de-de
$text['button-resend']['de-ch'] = "Erneut senden"; //copied from de-de
$text['button-resend']['de-de'] = "Erneut senden";
$text['button-resend']['es-cl'] = "Vuelva a Enviar";
$text['button-resend']['es-mx'] = "Vuelva a Enviar"; //copied from es-cl
$text['button-resend']['fr-ca'] = "Renvoyer"; //copied from fr-fr
$text['button-resend']['fr-fr'] = "Renvoyer";
$text['button-resend']['he-il'] = "";
$text['button-resend']['it-it'] = "Rispedisci";
$text['button-resend']['nl-nl'] = "Herzend";
$text['button-resend']['pl-pl'] = "Wyślij ponownie";
$text['button-resend']['pt-br'] = "Reenviar"; //copied from pt-pt
$text['button-resend']['pt-pt'] = "Reenviar";
$text['button-resend']['ro-ro'] = "";
$text['button-resend']['ru-ru'] = "Повторно Отправить";
$text['button-resend']['sv-se'] = "Skicka Igen";
$text['button-resend']['uk-ua'] = "";

$text['confirm-resend']['en-us'] = "Do you really want to resend this?";
$text['confirm-resend']['en-gb'] = "Do you really want to resend this?";
$text['confirm-resend']['ar-eg'] = "Do you really want to resend this?";
$text['confirm-resend']['de-at'] = "Do you really want to resend this?";
$text['confirm-resend']['de-ch'] = "Do you really want to resend this?";
$text['confirm-resend']['de-de'] = "Do you really want to resend this?";
$text['confirm-resend']['es-cl'] = "Do you really want to resend this?";
$text['confirm-resend']['es-mx'] = "Do you really want to resend this?";
$text['confirm-resend']['fr-ca'] = "Do you really want to resend this?";
$text['confirm-resend']['fr-fr'] = "Do you really want to resend this?";
$text['confirm-resend']['he-il'] = "Do you really want to resend this?";
$text['confirm-resend']['it-it'] = "Do you really want to resend this?";
$text['confirm-resend']['nl-nl'] = "Wil je dit werkelijk herzenen?";
$text['confirm-resend']['pl-pl'] = "Do you really want to resend this?";
$text['confirm-resend']['pt-br'] = "Do you really want to resend this?";
$text['confirm-resend']['pt-pt'] = "Do you really want to resend this?";
$text['confirm-resend']['ro-ro'] = "Do you really want to resend this?";
$text['confirm-resend']['ru-ru'] = "Do you really want to resend this?";
$text['confirm-resend']['sv-se'] = "Do you really want to resend this?";
$text['confirm-resend']['uk-ua'] = "Do you really want to resend this?";
$text['confirm-resend']['tr-tr'] = "Do you really want to resend this?";

?>
