<?php

$x++;
$array['dashboard_widgets'][$x]['dashboard_uuid'] = '3e2cbaa4-2bec-41b2-a626-999a59b8b19c';
$array['dashboard_widgets'][$x]['dashboard_widget_uuid'] = '4c63234b-e5d2-4232-9787-4734d342557b';
$array['dashboard_widgets'][$x]['widget_name'] = 'Active Calls';
$array['dashboard_widgets'][$x]['widget_path'] = 'active_calls/active_calls';
$array['dashboard_widgets'][$x]['widget_icon'] = 'fa-solid fa-phone';
$array['dashboard_widgets'][$x]['widget_icon_color'] = '#bfbfbf';
$array['dashboard_widgets'][$x]['widget_url'] = '';
$array['dashboard_widgets'][$x]['widget_target'] = '';
$array['dashboard_widgets'][$x]['widget_width'] = '';
$array['dashboard_widgets'][$x]['widget_height'] = '';
$array['dashboard_widgets'][$x]['widget_content'] = '';
$array['dashboard_widgets'][$x]['widget_content_text_align'] = '';
$array['dashboard_widgets'][$x]['widget_content_details'] = '';
$array['dashboard_widgets'][$x]['widget_chart_type'] = 'icon';
$array['dashboard_widgets'][$x]['widget_chart_type_options'] = ['icon', 'line'];
$array['dashboard_widgets'][$x]['widget_label_enabled'] = 'true';
$array['dashboard_widgets'][$x]['widget_label_text_color'] = '#444444';
$array['dashboard_widgets'][$x]['widget_label_text_color_hover'] = '';
$array['dashboard_widgets'][$x]['widget_label_background_color'] = '';
$array['dashboard_widgets'][$x]['widget_label_background_color_hover'] = '';
$array['dashboard_widgets'][$x]['widget_number_text_color'] = '';
$array['dashboard_widgets'][$x]['widget_number_text_color_hover'] = '';
$array['dashboard_widgets'][$x]['widget_number_background_color'] = '';
$array['dashboard_widgets'][$x]['widget_background_color'] = '';
$array['dashboard_widgets'][$x]['widget_background_color_hover'] = '';
$array['dashboard_widgets'][$x]['widget_detail_background_color'] = '';
$array['dashboard_widgets'][$x]['widget_column_span'] = '1';
$array['dashboard_widgets'][$x]['widget_row_span'] = '1';
$array['dashboard_widgets'][$x]['widget_details_state'] = 'hidden';
$array['dashboard_widgets'][$x]['widget_order'] = '90';
$array['dashboard_widgets'][$x]['widget_enabled'] = 'true';
$array['dashboard_widgets'][$x]['widget_description'] = 'System information like Disk usage.';
$y = 0;
$array['dashboard_widgets'][$x]['dashboard_widget_groups'][$y]['dashboard_uuid'] = '3e2cbaa4-2bec-41b2-a626-999a59b8b19c';
$array['dashboard_widgets'][$x]['dashboard_widget_groups'][$y]['dashboard_widget_group_uuid'] = 'a792add7-95a8-4d0e-a7c6-48495de8bae9';
$array['dashboard_widgets'][$x]['dashboard_widget_groups'][$y]['dashboard_widget_uuid'] = '4c63234b-e5d2-4232-9787-4734d342557b';
$array['dashboard_widgets'][$x]['dashboard_widget_groups'][$y]['group_name'] = 'superadmin';
$y++;
$array['dashboard_widgets'][$x]['dashboard_widget_groups'][$y]['dashboard_uuid'] = '3e2cbaa4-2bec-41b2-a626-999a59b8b19c';
$array['dashboard_widgets'][$x]['dashboard_widget_groups'][$y]['dashboard_widget_group_uuid'] = '2fc95ca2-fad0-41a4-bd58-6aba37eebc75';
$array['dashboard_widgets'][$x]['dashboard_widget_groups'][$y]['dashboard_widget_uuid'] = '4c63234b-e5d2-4232-9787-4734d342557b';
$array['dashboard_widgets'][$x]['dashboard_widget_groups'][$y]['group_name'] = 'admin';
$y++;
$array['dashboard_widgets'][$x]['dashboard_widget_groups'][$y]['dashboard_uuid'] = '3e2cbaa4-2bec-41b2-a626-999a59b8b19c';
$array['dashboard_widgets'][$x]['dashboard_widget_groups'][$y]['dashboard_widget_group_uuid'] = 'c5205a44-1eb7-4294-86a8-8b0d2b9ece98';
$array['dashboard_widgets'][$x]['dashboard_widget_groups'][$y]['dashboard_widget_uuid'] = '4c63234b-e5d2-4232-9787-4734d342557b';
$array['dashboard_widgets'][$x]['dashboard_widget_groups'][$y]['group_name'] = 'user';
