<?php

$text['label-switch_status']['en-us'] = "Switch Status";
$text['label-switch_status']['en-gb'] = "Switch Status";
$text['label-switch_status']['ar-eg'] = "";
$text['label-switch_status']['de-at'] = "Switch"; //copied from de-de
$text['label-switch_status']['de-ch'] = "Switch"; //copied from de-de
$text['label-switch_status']['de-de'] = "Switch";
$text['label-switch_status']['el-gr'] = "Switch";
$text['label-switch_status']['es-cl'] = "Switch";
$text['label-switch_status']['es-mx'] = "Switch"; //copied from es-cl
$text['label-switch_status']['fr-ca'] = "Switch"; //copied from fr-fr
$text['label-switch_status']['fr-fr'] = "Switch";
$text['label-switch_status']['he-il'] = "";
$text['label-switch_status']['it-it'] = "Switch";
$text['label-switch_status']['nl-nl'] = "";
$text['label-switch_status']['pl-pl'] = "Switch";
$text['label-switch_status']['pt-br'] = "Switch"; //copied from pt-pt
$text['label-switch_status']['pt-pt'] = "Switch";
$text['label-switch_status']['ro-ro'] = "";
$text['label-switch_status']['ru-ru'] = "FreeSwitch";
$text['label-switch_status']['sv-se'] = "Switch";
$text['label-switch_status']['uk-ua'] = "Switch";

$text['label-channels']['en-us'] = "Channels";
$text['label-channels']['en-gb'] = "Channels";
$text['label-channels']['ar-eg'] = "";
$text['label-channels']['de-at'] = "Kanäle"; //copied from de-de
$text['label-channels']['de-ch'] = "Kanäle"; //copied from de-de
$text['label-channels']['de-de'] = "Kanäle";
$text['label-channels']['el-gr'] = "Κανάλια";
$text['label-channels']['es-cl'] = "Canales";
$text['label-channels']['es-mx'] = "Canales"; //copied from es-cl
$text['label-channels']['fr-ca'] = "Canaux"; //copied from fr-fr
$text['label-channels']['fr-fr'] = "Canaux";
$text['label-channels']['he-il'] = "ערוצים";
$text['label-channels']['it-it'] = "Canali";
$text['label-channels']['nl-nl'] = "";
$text['label-channels']['pl-pl'] = "Kanały";
$text['label-channels']['pt-br'] = "Canais"; //copied from pt-pt
$text['label-channels']['pt-pt'] = "Canais";
$text['label-channels']['ro-ro'] = "Canale";
$text['label-channels']['ru-ru'] = "Каналы";
$text['label-channels']['sv-se'] = "Kanaler";
$text['label-channels']['uk-ua'] = "Канали";

$text['label-registrations']['en-us'] = "Registrations";
$text['label-registrations']['en-gb'] = "Registrations";
$text['label-registrations']['ar-eg'] = "";
$text['label-registrations']['de-at'] = "Registrierungen"; //copied from de-de
$text['label-registrations']['de-ch'] = "Registrierungen"; //copied from de-de
$text['label-registrations']['de-de'] = "Registrierungen";
$text['label-registrations']['el-gr'] = "Συνδέσεις";
$text['label-registrations']['es-cl'] = "Inscripciones";
$text['label-registrations']['es-mx'] = "Inscripciones"; //copied from es-cl
$text['label-registrations']['fr-ca'] = "Enregistrements SIP"; //copied from fr-fr
$text['label-registrations']['fr-fr'] = "Enregistrements SIP";
$text['label-registrations']['he-il'] = "";
$text['label-registrations']['it-it'] = "Registrazioni";
$text['label-registrations']['nl-nl'] = "";
$text['label-registrations']['pl-pl'] = "Rejestracje";
$text['label-registrations']['pt-br'] = "Registros";
$text['label-registrations']['pt-pt'] = "Inscrições";
$text['label-registrations']['ro-ro'] = "";
$text['label-registrations']['ru-ru'] = "Регистрации SIP";
$text['label-registrations']['sv-se'] = "Registreringar";
$text['label-registrations']['uk-ua'] = "Реєстрації";

$text['label-switch_uptime']['en-us'] = "Switch Uptime";
$text['label-switch_uptime']['en-gb'] = "Switch Uptime";
$text['label-switch_uptime']['ar-eg'] = "";
$text['label-switch_uptime']['de-at'] = "Switch Uptime"; //copied from de-de
$text['label-switch_uptime']['de-ch'] = "Switch Uptime"; //copied from de-de
$text['label-switch_uptime']['de-de'] = "Switch Uptime";
$text['label-switch_uptime']['el-gr'] = "Switch Uptime";
$text['label-switch_uptime']['es-cl'] = "Tiempo de actividad Switch";
$text['label-switch_uptime']['es-mx'] = "Tiempo de actividad Switch"; //copied from es-cl
$text['label-switch_uptime']['fr-ca'] = "Switch Uptime"; //copied from fr-fr
$text['label-switch_uptime']['fr-fr'] = "Switch Uptime";
$text['label-switch_uptime']['he-il'] = "";
$text['label-switch_uptime']['it-it'] = "Tempo di attività Switch";
$text['label-switch_uptime']['nl-nl'] = "";
$text['label-switch_uptime']['pl-pl'] = "Switch Uptime";
$text['label-switch_uptime']['pt-br'] = "Tempo de atividade do switch";
$text['label-switch_uptime']['pt-pt'] = "Uptime Switch";
$text['label-switch_uptime']['ro-ro'] = "";
$text['label-switch_uptime']['ru-ru'] = "Время непрерывной работы FreeSwitch";
$text['label-switch_uptime']['sv-se'] = "Switch Uptime";
$text['label-switch_uptime']['uk-ua'] = "Switch Uptime";

$text['label-switch']['en-us'] = "Switch";
$text['label-switch']['en-gb'] = "Switch";
$text['label-switch']['ar-eg'] = "";
$text['label-switch']['de-at'] = "Switch"; //copied from de-de
$text['label-switch']['de-ch'] = "Switch"; //copied from de-de
$text['label-switch']['de-de'] = "Switch";
$text['label-switch']['el-gr'] = "Switch";
$text['label-switch']['es-cl'] = "Switch";
$text['label-switch']['es-mx'] = "Switch"; //copied from es-cl
$text['label-switch']['fr-ca'] = "Switch"; //copied from fr-fr
$text['label-switch']['fr-fr'] = "Switch";
$text['label-switch']['he-il'] = "";
$text['label-switch']['it-it'] = "Switch";
$text['label-switch']['nl-nl'] = "";
$text['label-switch']['pl-pl'] = "Switch";
$text['label-switch']['pt-br'] = "Switch"; //copied from pt-pt
$text['label-switch']['pt-pt'] = "Switch";
$text['label-switch']['ro-ro'] = "";
$text['label-switch']['ru-ru'] = "FreeSwitch";
$text['label-switch']['sv-se'] = "Switch";
$text['label-switch']['uk-ua'] = "Switch";

$text['label-switch']['en-us'] = "Switch";
$text['label-switch']['en-gb'] = "Switch";
$text['label-switch']['ar-eg'] = "";
$text['label-switch']['de-at'] = "Switch"; //copied from de-de
$text['label-switch']['de-ch'] = "Switch"; //copied from de-de
$text['label-switch']['de-de'] = "Switch";
$text['label-switch']['el-gr'] = "Switch";
$text['label-switch']['es-cl'] = "Switch";
$text['label-switch']['es-mx'] = "Switch"; //copied from es-cl
$text['label-switch']['fr-ca'] = "Switch"; //copied from fr-fr
$text['label-switch']['fr-fr'] = "Switch";
$text['label-switch']['he-il'] = "";
$text['label-switch']['it-it'] = "Switch";
$text['label-switch']['nl-nl'] = "";
$text['label-switch']['pl-pl'] = "Switch";
$text['label-switch']['pt-br'] = "Switch"; //copied from pt-pt
$text['label-switch']['pt-pt'] = "Switch";
$text['label-switch']['ro-ro'] = "";
$text['label-switch']['ru-ru'] = "FreeSwitch";
$text['label-switch']['sv-se'] = "Switch";
$text['label-switch']['uk-ua'] = "Switch";

?>