<?php

	//application details
		$apps[$x]['name'] = 'Call Recordings';
		$apps[$x]['uuid'] = '56165644-598d-4ed8-be01-d960bcb8ffed';
		$apps[$x]['category'] = '';
		$apps[$x]['subcategory'] = '';
		$apps[$x]['version'] = '1.1';
		$apps[$x]['license'] = 'Mozilla Public License 1.1';
		$apps[$x]['url'] = 'http://www.fusionpbx.com';
		$apps[$x]['description']['en-us'] = 'Call Recordings';
		$apps[$x]['description']['en-gb'] = 'Call Recordings';
		$apps[$x]['description']['nl-nl'] = 'Gespreksopnamen';

	//permission details
		$y = 0;
		$apps[$x]['permissions'][$y]['name'] = 'call_recording_view';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'call_recording_add';
		//$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'call_recording_edit';
		//$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'call_recording_delete';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'call_recording_all';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'call_recording_play';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'call_recording_download';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'call_recording_transcribe';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';

	//default settings
		$y = 0;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "95cb740e-e377-4852-8894-06441c61e78b";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "call_recordings";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "filesystem_retention_days";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "90";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Number of days to retain the maintenance logs in the database.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "e329db05-2967-422a-a71f-d0175b083828";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "call_recordings";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "record_extension";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "mp3";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Call recording file format options: wav, mp3";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "f8dada74-82a0-4175-8268-2333de308d9d";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "call_recordings";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "record_name";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "\${year}\${month_number}\${day}.\${time}.\${caller_id_number}.\${uuid}.mp3";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Call recording download template. Options: \${uuid}, \${caller_id_name}, \${caller_id_number}, \${caller_destination}, \${destination_number}, \${date}, \${call_direction}, \${year}, \${month_name}, \${month_number}, \${day}, \${time}";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "a21c3dab-36e3-4d7f-8356-9d9fd3eec0a3";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "call_recordings";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "transcribe_enabled";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Call recordings enable transcribe. Options: true, false";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "3a5e8a81-f356-4824-92df-69f6a0da17dc";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "call_recordings";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "summary_enabled";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Call recordings enable call summary. Options: true, false";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "2bbdb343-4e95-4d9b-886a-33bc5918a4c0";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "call_recordings";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "email_address";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Call recordings email address.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "43ce24ca-fc5e-48ca-a0c4-88fb7b7ce679";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "call_recordings";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "email_template";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "transcription";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Call recordings used to select the email template.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "7c188b97-7a51-4358-844b-124dc960a4c5";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "call_recordings";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "summary_model_prompt";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "Summarize this conversation with Key Points, Action Items if any, and Sentiment. Use names when they are provided. Return text without markdown.";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "The language model prompt to generate the call summary.";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "bf1c4aec-ef13-4a6d-aa00-204ab0dbb751";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "call_recordings";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "summary_model_name";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "ministral-3:8b";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "The language model name used to generate the call summary.";
