<?php
#This file was last reorganized on 19th of September 2017 08:54:24 AM UTC

$text['title-install']['en-us'] = "Install";
$text['title-install']['en-gb'] = "Install";
$text['title-install']['ar-eg'] = "للمرة الأولى قم بتثبيت";
$text['title-install']['de-at'] = "Erstinstallation"; //copied from de-de
$text['title-install']['de-ch'] = "Erstinstallation"; //copied from de-de
$text['title-install']['de-de'] = "Erstinstallation";
$text['title-install']['es-cl'] = "Instale";
$text['title-install']['es-mx'] = "Instale"; //copied from es-cl
$text['title-install']['fr-ca'] = "Installation"; //copied from fr-fr
$text['title-install']['fr-fr'] = "Installation";
$text['title-install']['he-il'] = "";
$text['title-install']['it-it'] = "Installazione";
$text['title-install']['nl-nl'] = "";
$text['title-install']['pl-pl'] = "Zainstalować";
$text['title-install']['pt-br'] = "Installation"; //copied from pt-pt
$text['title-install']['pt-pt'] = "Installation";
$text['title-install']['ro-ro'] = "";
$text['title-install']['ru-ru'] = "Установка";
$text['title-install']['sv-se'] = "Installera";
$text['title-install']['uk-ua'] = "Перший раз Встановіть";

$text['title-detected_configuration']['en-us'] = "Detected Configuration";
$text['title-detected_configuration']['en-gb'] = "Detected Configuration";
$text['title-detected_configuration']['ar-eg'] = "تكوين الكشف عن";
$text['title-detected_configuration']['de-at'] = "Erkannte Konfiguration"; //copied from de-de
$text['title-detected_configuration']['de-ch'] = "Erkannte Konfiguration"; //copied from de-de
$text['title-detected_configuration']['de-de'] = "Erkannte Konfiguration";
$text['title-detected_configuration']['es-cl'] = "Configuración detectado";
$text['title-detected_configuration']['es-mx'] = "Configuración detectado"; //copied from es-cl
$text['title-detected_configuration']['fr-ca'] = "Configuration Détectée"; //copied from fr-fr
$text['title-detected_configuration']['fr-fr'] = "Configuration Détectée";
$text['title-detected_configuration']['he-il'] = "";
$text['title-detected_configuration']['it-it'] = "Rilevata Configurazione";
$text['title-detected_configuration']['nl-nl'] = "";
$text['title-detected_configuration']['pl-pl'] = "Wykryto Konfiguracja";
$text['title-detected_configuration']['pt-br'] = "Configuração detectado"; //copied from pt-pt
$text['title-detected_configuration']['pt-pt'] = "Configuração detectado";
$text['title-detected_configuration']['ro-ro'] = "";
$text['title-detected_configuration']['ru-ru'] = "Обнаруженная конфигурация";
$text['title-detected_configuration']['sv-se'] = "Detekterad Konfiguration";
$text['title-detected_configuration']['uk-ua'] = "виявлено Конфігурація";

$text['title-assumed_configuration']['en-us'] = "Assumed Configuration";
$text['title-assumed_configuration']['en-gb'] = "Assumed Configuration";
$text['title-assumed_configuration']['ar-eg'] = "تكوين المفترضة";
$text['title-assumed_configuration']['de-at'] = "Angenommene Konfiguration"; //copied from de-de
$text['title-assumed_configuration']['de-ch'] = "Angenommene Konfiguration"; //copied from de-de
$text['title-assumed_configuration']['de-de'] = "Angenommene Konfiguration";
$text['title-assumed_configuration']['es-cl'] = "Configuración adoptada";
$text['title-assumed_configuration']['es-mx'] = "Configuración adoptada"; //copied from es-cl
$text['title-assumed_configuration']['fr-ca'] = "Configuration supposée"; //copied from fr-fr
$text['title-assumed_configuration']['fr-fr'] = "Configuration supposée";
$text['title-assumed_configuration']['he-il'] = "";
$text['title-assumed_configuration']['it-it'] = "Configurazione accettata";
$text['title-assumed_configuration']['nl-nl'] = "";
$text['title-assumed_configuration']['pl-pl'] = "Zakładana Konfiguracja";
$text['title-assumed_configuration']['pt-br'] = "Assumed Configuration"; //copied from pt-pt
$text['title-assumed_configuration']['pt-pt'] = "Assumed Configuration";
$text['title-assumed_configuration']['ro-ro'] = "";
$text['title-assumed_configuration']['ru-ru'] = "Предполагаемая конфигурация";
$text['title-assumed_configuration']['sv-se'] = "Antagen Konfiguration";
$text['title-assumed_configuration']['uk-ua'] = "передбачуваний Конфігурація";

$text['label-ft-install']['en-us'] = "First Time Install";
$text['label-ft-install']['en-gb'] = "First Time Install";
$text['label-ft-install']['ar-eg'] = "للمرة الأولى قم بتثبيت";
$text['label-ft-install']['de-at'] = "Erstinstallation"; //copied from de-de
$text['label-ft-install']['de-ch'] = "Erstinstallation"; //copied from de-de
$text['label-ft-install']['de-de'] = "Erstinstallation";
$text['label-ft-install']['es-cl'] = "La primera instalación";
$text['label-ft-install']['es-mx'] = "La primera instalación"; //copied from es-cl
$text['label-ft-install']['fr-ca'] = "Première installation"; //copied from fr-fr
$text['label-ft-install']['fr-fr'] = "Première installation";
$text['label-ft-install']['he-il'] = "";
$text['label-ft-install']['it-it'] = "Prima Installazione";
$text['label-ft-install']['nl-nl'] = "";
$text['label-ft-install']['pl-pl'] = "Zainstalować";
$text['label-ft-install']['pt-br'] = "First Time Install"; //copied from pt-pt
$text['label-ft-install']['pt-pt'] = "First Time Install";
$text['label-ft-install']['ro-ro'] = "";
$text['label-ft-install']['ru-ru'] = "Первая установка";
$text['label-ft-install']['sv-se'] = "Första gången Installera";
$text['label-ft-install']['uk-ua'] = "Перший раз Встановіть";

$text['description-ft-install']['en-us'] = "Perform all actions for a First Time Install";
$text['description-ft-install']['en-gb'] = "Perform all actions for a First Time Install";
$text['description-ft-install']['ar-eg'] = "تنفيذ كافة الإجراءات لأول مرة التثبيت";
$text['description-ft-install']['de-at'] = "Führen Sie alle Scritte für eine Erstinstallation durch"; //copied from de-de
$text['description-ft-install']['de-ch'] = "Führen Sie alle Scritte für eine Erstinstallation durch"; //copied from de-de
$text['description-ft-install']['de-de'] = "Führen Sie alle Scritte für eine Erstinstallation durch";
$text['description-ft-install']['es-cl'] = "Realizar todas las acciones para una primera instalación";
$text['description-ft-install']['es-mx'] = "Realizar todas las acciones para una primera instalación"; //copied from es-cl
$text['description-ft-install']['fr-ca'] = "Effectuer toutes les actions pour une première installation"; //copied from fr-fr
$text['description-ft-install']['fr-fr'] = "Effectuer toutes les actions pour une première installation";
$text['description-ft-install']['he-il'] = "";
$text['description-ft-install']['it-it'] = "Esecuzione di tutte le operazione per la Prima Installazione";
$text['description-ft-install']['nl-nl'] = "";
$text['description-ft-install']['pl-pl'] = "Wykonać wszystkie czynności dla pierwszy raz zainstalować";
$text['description-ft-install']['pt-br'] = "Executar todas as ações para uma primeira vez Instalar"; //copied from pt-pt
$text['description-ft-install']['pt-pt'] = "Executar todas as ações para uma primeira vez Instalar";
$text['description-ft-install']['ro-ro'] = "";
$text['description-ft-install']['ru-ru'] = "Выполнять все действия для первой установки";
$text['description-ft-install']['sv-se'] = "Utföra alla åtgärder för första gången Installera";
$text['description-ft-install']['uk-ua'] = "Виконайте всі дії для першого разу Встановіть";

$text['label-add-switch']['en-us'] = "Add a new switch";
$text['label-add-switch']['en-gb'] = "Add a new switch";
$text['label-add-switch']['ar-eg'] = "إضافة مفتاح جديد";
$text['label-add-switch']['de-at'] = "Fügen Sie einen neuen Schalter hinzu"; //copied from de-de
$text['label-add-switch']['de-ch'] = "Fügen Sie einen neuen Schalter hinzu"; //copied from de-de
$text['label-add-switch']['de-de'] = "Fügen Sie einen neuen Schalter hinzu";
$text['label-add-switch']['es-cl'] = "Añadir un nuevo conmutador";
$text['label-add-switch']['es-mx'] = "Añadir un nuevo conmutador"; //copied from es-cl
$text['label-add-switch']['fr-ca'] = "Ajouter un nouveau commutateur"; //copied from fr-fr
$text['label-add-switch']['fr-fr'] = "Ajouter un nouveau commutateur";
$text['label-add-switch']['he-il'] = "";
$text['label-add-switch']['it-it'] = "Aggiungi un nuovo switch";
$text['label-add-switch']['nl-nl'] = "";
$text['label-add-switch']['pl-pl'] = "Dodaj nowy przełącznik";
$text['label-add-switch']['pt-br'] = "Adicionar um novo switch"; //copied from pt-pt
$text['label-add-switch']['pt-pt'] = "Adicionar um novo switch";
$text['label-add-switch']['ro-ro'] = "";
$text['label-add-switch']['ru-ru'] = "Добавить новый коммутатор";
$text['label-add-switch']['sv-se'] = "Lägg till en ny switch";
$text['label-add-switch']['uk-ua'] = "Додати новий перемикач";

$text['label-select_language']['en-us'] = "Language";
$text['label-select_language']['en-gb'] = "Language";
$text['label-select_language']['ar-eg'] = "لغة";
$text['label-select_language']['de-at'] = "Sprache"; //copied from de-de
$text['label-select_language']['de-ch'] = "Sprache"; //copied from de-de
$text['label-select_language']['de-de'] = "Sprache";
$text['label-select_language']['es-cl'] = "Idioma";
$text['label-select_language']['es-mx'] = "Idioma"; //copied from es-cl
$text['label-select_language']['fr-ca'] = "Langue"; //copied from fr-fr
$text['label-select_language']['fr-fr'] = "Langue";
$text['label-select_language']['he-il'] = "";
$text['label-select_language']['it-it'] = "Lingua";
$text['label-select_language']['nl-nl'] = "";
$text['label-select_language']['pl-pl'] = "Język";
$text['label-select_language']['pt-br'] = "Idioma"; //copied from pt-pt
$text['label-select_language']['pt-pt'] = "Idioma";
$text['label-select_language']['ro-ro'] = "";
$text['label-select_language']['ru-ru'] = "Язык";
$text['label-select_language']['sv-se'] = "Språk";
$text['label-select_language']['uk-ua'] = "Мова";

$text['label-event_host']['en-us'] = "Host address";
$text['label-event_host']['en-gb'] = "Host address";
$text['label-event_host']['ar-eg'] = "عنوان المضيف";
$text['label-event_host']['de-at'] = "Host-Adresse"; //copied from de-de
$text['label-event_host']['de-ch'] = "Host-Adresse"; //copied from de-de
$text['label-event_host']['de-de'] = "Host-Adresse";
$text['label-event_host']['es-cl'] = "Dirección de host";
$text['label-event_host']['es-mx'] = "Dirección de host"; //copied from es-cl
$text['label-event_host']['fr-ca'] = "Adresse de l'hôte"; //copied from fr-fr
$text['label-event_host']['fr-fr'] = "Adresse de l'hôte";
$text['label-event_host']['he-il'] = "";
$text['label-event_host']['it-it'] = "Indirizzo Host";
$text['label-event_host']['nl-nl'] = "";
$text['label-event_host']['pl-pl'] = "Adres hosta";
$text['label-event_host']['pt-br'] = "Endereço do host"; //copied from pt-pt
$text['label-event_host']['pt-pt'] = "Endereço do host";
$text['label-event_host']['ro-ro'] = "";
$text['label-event_host']['ru-ru'] = "Адрес хоста";
$text['label-event_host']['sv-se'] = "Host adress";
$text['label-event_host']['uk-ua'] = "адреса хоста";

$text['label-event_port']['en-us'] = "Port";
$text['label-event_port']['en-gb'] = "Port";
$text['label-event_port']['ar-eg'] = "منفذ";
$text['label-event_port']['de-at'] = "Port"; //copied from de-de
$text['label-event_port']['de-ch'] = "Port"; //copied from de-de
$text['label-event_port']['de-de'] = "Port";
$text['label-event_port']['es-cl'] = "Puerto";
$text['label-event_port']['es-mx'] = "Puerto"; //copied from es-cl
$text['label-event_port']['fr-ca'] = "Port"; //copied from fr-fr
$text['label-event_port']['fr-fr'] = "Port";
$text['label-event_port']['he-il'] = "";
$text['label-event_port']['it-it'] = "Porta";
$text['label-event_port']['nl-nl'] = "";
$text['label-event_port']['pl-pl'] = "Port";
$text['label-event_port']['pt-br'] = "Porta";
$text['label-event_port']['pt-pt'] = "Porto";
$text['label-event_port']['ro-ro'] = "";
$text['label-event_port']['ru-ru'] = "Порт";
$text['label-event_port']['sv-se'] = "Port";
$text['label-event_port']['uk-ua'] = "Порт";

$text['label-event_password']['en-us'] = "Password";
$text['label-event_password']['en-gb'] = "Password";
$text['label-event_password']['ar-eg'] = "كلمة السر";
$text['label-event_password']['de-at'] = "Passwort"; //copied from de-de
$text['label-event_password']['de-ch'] = "Passwort"; //copied from de-de
$text['label-event_password']['de-de'] = "Passwort";
$text['label-event_password']['es-cl'] = "Contreseña";
$text['label-event_password']['es-mx'] = "Contreseña"; //copied from es-cl
$text['label-event_password']['fr-ca'] = "Mot de Passe"; //copied from fr-fr
$text['label-event_password']['fr-fr'] = "Mot de Passe";
$text['label-event_password']['he-il'] = "";
$text['label-event_password']['it-it'] = "Password";
$text['label-event_password']['nl-nl'] = "";
$text['label-event_password']['pl-pl'] = "Hasło";
$text['label-event_password']['pt-br'] = "Senha";
$text['label-event_password']['pt-pt'] = "Palavra-Chave";
$text['label-event_password']['ro-ro'] = "";
$text['label-event_password']['ru-ru'] = "Пароль";
$text['label-event_password']['sv-se'] = "Lösenord";
$text['label-event_password']['uk-ua'] = "Пароль";

$text['label-username']['en-us'] = "Username";
$text['label-username']['en-gb'] = "Username";
$text['label-username']['ar-eg'] = "اسم المستخدم";
$text['label-username']['de-at'] = "Benutzername"; //copied from de-de
$text['label-username']['de-ch'] = "Benutzername"; //copied from de-de
$text['label-username']['de-de'] = "Benutzername";
$text['label-username']['es-cl'] = "Nombre de usuario";
$text['label-username']['es-mx'] = "Nombre de usuario"; //copied from es-cl
$text['label-username']['fr-ca'] = "Utilisateur"; //copied from fr-fr
$text['label-username']['fr-fr'] = "Utilisateur";
$text['label-username']['he-il'] = "";
$text['label-username']['it-it'] = "Nome Utente";
$text['label-username']['nl-nl'] = "";
$text['label-username']['pl-pl'] = "Użytkownik";
$text['label-username']['pt-br'] = "Nome do Usuário";
$text['label-username']['pt-pt'] = "Utilizador";
$text['label-username']['ro-ro'] = "";
$text['label-username']['ru-ru'] = "Имя пользователя";
$text['label-username']['sv-se'] = "Användarnamn";
$text['label-username']['uk-ua'] = "Ім’я користувача";

$text['label-port']['en-us'] = "Port";
$text['label-port']['en-gb'] = "Port";
$text['label-port']['ar-eg'] = "منفذ";
$text['label-port']['de-at'] = "Port"; //copied from de-de
$text['label-port']['de-ch'] = "Port"; //copied from de-de
$text['label-port']['de-de'] = "Port";
$text['label-port']['es-cl'] = "Puerto";
$text['label-port']['es-mx'] = "Puerto"; //copied from es-cl
$text['label-port']['fr-ca'] = "Port"; //copied from fr-fr
$text['label-port']['fr-fr'] = "Port";
$text['label-port']['he-il'] = "";
$text['label-port']['it-it'] = "Porta";
$text['label-port']['nl-nl'] = "";
$text['label-port']['pl-pl'] = "Port";
$text['label-port']['pt-br'] = "Porta";
$text['label-port']['pt-pt'] = "Porto";
$text['label-port']['ro-ro'] = "";
$text['label-port']['ru-ru'] = "Порт";
$text['label-port']['sv-se'] = "Port";
$text['label-port']['uk-ua'] = "Порт";

$text['label-path']['en-us'] = "Path";
$text['label-path']['en-gb'] = "Path";
$text['label-path']['ar-eg'] = "مسار";
$text['label-path']['de-at'] = "Pfad"; //copied from de-de
$text['label-path']['de-ch'] = "Pfad"; //copied from de-de
$text['label-path']['de-de'] = "Pfad";
$text['label-path']['es-cl'] = "Ruta";
$text['label-path']['es-mx'] = "Ruta"; //copied from es-cl
$text['label-path']['fr-ca'] = "Chemin"; //copied from fr-fr
$text['label-path']['fr-fr'] = "Chemin";
$text['label-path']['he-il'] = "";
$text['label-path']['it-it'] = "Percorso";
$text['label-path']['nl-nl'] = "";
$text['label-path']['pl-pl'] = "Ścieżka";
$text['label-path']['pt-br'] = "Caminho"; //copied from pt-pt
$text['label-path']['pt-pt'] = "Caminho";
$text['label-path']['ro-ro'] = "";
$text['label-path']['ru-ru'] = "Путь";
$text['label-path']['sv-se'] = "Sökväg";
$text['label-path']['uk-ua'] = "Шлях";

$text['label-host']['en-us'] = "Host";
$text['label-host']['en-gb'] = "Host";
$text['label-host']['ar-eg'] = "مضيف";
$text['label-host']['de-at'] = "Host"; //copied from de-de
$text['label-host']['de-ch'] = "Host"; //copied from de-de
$text['label-host']['de-de'] = "Host";
$text['label-host']['es-cl'] = "Host";
$text['label-host']['es-mx'] = "Host"; //copied from es-cl
$text['label-host']['fr-ca'] = "Hôte"; //copied from fr-fr
$text['label-host']['fr-fr'] = "Hôte";
$text['label-host']['he-il'] = "";
$text['label-host']['it-it'] = "Host";
$text['label-host']['nl-nl'] = "";
$text['label-host']['pl-pl'] = "Host";
$text['label-host']['pt-br'] = "Máquina"; //copied from pt-pt
$text['label-host']['pt-pt'] = "Máquina";
$text['label-host']['ro-ro'] = "";
$text['label-host']['ru-ru'] = "Хост";
$text['label-host']['sv-se'] = "Värd";
$text['label-host']['uk-ua'] = "Хост";

$text['label-domain_name']['en-us'] = "Domain Name";
$text['label-domain_name']['en-gb'] = "Domain Name";
$text['label-domain_name']['ar-eg'] = "النطاق";
$text['label-domain_name']['de-at'] = "Domäne"; //copied from de-de
$text['label-domain_name']['de-ch'] = "Domäne"; //copied from de-de
$text['label-domain_name']['de-de'] = "Domäne";
$text['label-domain_name']['el-gr'] = "Τομέας";
$text['label-domain_name']['es-cl'] = "Dominio";
$text['label-domain_name']['es-mx'] = "Dominio"; //copied from es-cl
$text['label-domain_name']['fr-ca'] = "Domaine"; //copied from fr-fr
$text['label-domain_name']['fr-fr'] = "Domaine";
$text['label-domain_name']['he-il'] = "דומיין";
$text['label-domain_name']['it-it'] = "Dominio";
$text['label-domain_name']['nl-nl'] = "";
$text['label-domain_name']['pl-pl'] = "Domena";
$text['label-domain_name']['pt-br'] = "Domínio";
$text['label-domain_name']['pt-pt'] = "Domínio";
$text['label-domain_name']['ro-ro'] = "Domeniu";
$text['label-domain_name']['ru-ru'] = "Домен";
$text['label-domain_name']['sv-se'] = "Domän";
$text['label-domain_name']['uk-ua'] = "Домен";
$text['label-domain_name']['tr-tr'] = "Alan Adı";

$text['label-driver']['en-us'] = "Driver";
$text['label-driver']['en-gb'] = "Driver";
$text['label-driver']['ar-eg'] = "سائق";
$text['label-driver']['de-at'] = "Treiber"; //copied from de-de
$text['label-driver']['de-ch'] = "Treiber"; //copied from de-de
$text['label-driver']['de-de'] = "Treiber";
$text['label-driver']['es-cl'] = "Controlador";
$text['label-driver']['es-mx'] = "Controlador"; //copied from es-cl
$text['label-driver']['fr-ca'] = "Pilote";
$text['label-driver']['fr-fr'] = "Pilote";
$text['label-driver']['he-il'] = "";
$text['label-driver']['it-it'] = "Driver";
$text['label-driver']['nl-nl'] = "";
$text['label-driver']['pl-pl'] = "Sterownik";
$text['label-driver']['pt-br'] = "Driver"; //copied from pt-pt
$text['label-driver']['pt-pt'] = "Driver";
$text['label-driver']['ro-ro'] = "";
$text['label-driver']['ru-ru'] = "Драйвер";
$text['label-driver']['sv-se'] = "Drivrutin";
$text['label-driver']['uk-ua'] = "Драйвер";

$text['header-install']['en-us'] = "Install";
$text['header-install']['en-gb'] = "Install";
$text['header-install']['ar-eg'] = "تثبيت";
$text['header-install']['de-at'] = "Installieren"; //copied from de-de
$text['header-install']['de-ch'] = "Installieren"; //copied from de-de
$text['header-install']['de-de'] = "Installieren";
$text['header-install']['es-cl'] = "Instalar";
$text['header-install']['es-mx'] = "Instalar"; //copied from es-cl
$text['header-install']['fr-ca'] = "Installer"; //copied from fr-fr
$text['header-install']['fr-fr'] = "Installer";
$text['header-install']['he-il'] = "";
$text['header-install']['it-it'] = "Installazione";
$text['header-install']['nl-nl'] = "";
$text['header-install']['pl-pl'] = "Zainstalować";
$text['header-install']['pt-br'] = "Instalar"; //copied from pt-pt
$text['header-install']['pt-pt'] = "Instalar";
$text['header-install']['ro-ro'] = "";
$text['header-install']['ru-ru'] = "Установка";
$text['header-install']['sv-se'] = "Installera";
$text['header-install']['uk-ua'] = "встановлювати";

$text['header-select_language']['en-us'] = "Select Language";
$text['header-select_language']['en-gb'] = "Select Language";
$text['header-select_language']['ar-eg'] = "اختار اللغة";
$text['header-select_language']['de-at'] = "Sprache auswählen"; //copied from de-de
$text['header-select_language']['de-ch'] = "Sprache auswählen"; //copied from de-de
$text['header-select_language']['de-de'] = "Sprache auswählen";
$text['header-select_language']['es-cl'] = "Selecciona idioma";
$text['header-select_language']['es-mx'] = "Selecciona idioma"; //copied from es-cl
$text['header-select_language']['fr-ca'] = "Sélectionnez la langue"; //copied from fr-fr
$text['header-select_language']['fr-fr'] = "Sélectionnez la langue";
$text['header-select_language']['he-il'] = "";
$text['header-select_language']['it-it'] = "Seleziona Lingua";
$text['header-select_language']['nl-nl'] = "";
$text['header-select_language']['pl-pl'] = "Wybierz język";
$text['header-select_language']['pt-br'] = "Selecione o idioma"; //copied from pt-pt
$text['header-select_language']['pt-pt'] = "Selecione o idioma";
$text['header-select_language']['ro-ro'] = "";
$text['header-select_language']['ru-ru'] = "Выберите язык";
$text['header-select_language']['sv-se'] = "Välj språk";
$text['header-select_language']['uk-ua'] = "вибір мови";

$text['header-event_socket']['en-us'] = "Event Socket Configuration";
$text['header-event_socket']['en-gb'] = "Event Socket Configuration";
$text['header-event_socket']['ar-eg'] = "تكوين المقبس الحدث";
$text['header-event_socket']['de-at'] = "Event-Socket Konfigurieren"; //copied from de-de
$text['header-event_socket']['de-ch'] = "Event-Socket Konfigurieren"; //copied from de-de
$text['header-event_socket']['de-de'] = "Event-Socket Konfigurieren";
$text['header-event_socket']['es-cl'] = "Configuración del zócalo evento";
$text['header-event_socket']['es-mx'] = "Configuración del zócalo evento"; //copied from es-cl
$text['header-event_socket']['fr-ca'] = "Configuration du socket d'événement"; //copied from fr-fr
$text['header-event_socket']['fr-fr'] = "Configuration du socket d'événement";
$text['header-event_socket']['he-il'] = "";
$text['header-event_socket']['it-it'] = "Configurazione degli eventi Socket";
$text['header-event_socket']['nl-nl'] = "";
$text['header-event_socket']['pl-pl'] = "Zdarzenie Gniazdo Konfiguracja";
$text['header-event_socket']['pt-br'] = "Configuração soquete evento"; //copied from pt-pt
$text['header-event_socket']['pt-pt'] = "Configuração soquete evento";
$text['header-event_socket']['ro-ro'] = "";
$text['header-event_socket']['ru-ru'] = "Конфигурация сокета событий";
$text['header-event_socket']['sv-se'] = "Händelse Socket Konfiguration";
$text['header-event_socket']['uk-ua'] = "Конфігурація гніздо Подія";

$text['header-config_detail']['en-us'] = "Admin Configuration";
$text['header-config_detail']['en-gb'] = "Admin Configuration";
$text['header-config_detail']['ar-eg'] = "تكوين المشرف";
$text['header-config_detail']['de-at'] = "Admin-Konfiguration"; //copied from de-de
$text['header-config_detail']['de-ch'] = "Admin-Konfiguration"; //copied from de-de
$text['header-config_detail']['de-de'] = "Admin-Konfiguration";
$text['header-config_detail']['es-cl'] = "Configuración de administración";
$text['header-config_detail']['es-mx'] = "Configuración de administración"; //copied from es-cl
$text['header-config_detail']['fr-ca'] = "Configuration Admin"; //copied from fr-fr
$text['header-config_detail']['fr-fr'] = "Configuration Admin";
$text['header-config_detail']['he-il'] = "";
$text['header-config_detail']['it-it'] = "Configurazione Amministratore";
$text['header-config_detail']['nl-nl'] = "";
$text['header-config_detail']['pl-pl'] = "Konfiguracja Admin";
$text['header-config_detail']['pt-br'] = "Configuração de administrador"; //copied from pt-pt
$text['header-config_detail']['pt-pt'] = "Configuração de administrador";
$text['header-config_detail']['ro-ro'] = "";
$text['header-config_detail']['ru-ru'] = "Конфигурация администратора";
$text['header-config_detail']['sv-se'] = "Admin Konfiguration";
$text['header-config_detail']['uk-ua'] = "конфігурація Адмін";

$text['header-config_database']['en-us'] = "Database Configuration";
$text['header-config_database']['en-gb'] = "Database Configuration";
$text['header-config_database']['ar-eg'] = "تكوين قاعدة بيانات";
$text['header-config_database']['de-at'] = "Datenbankkonfiguration "; //copied from de-de
$text['header-config_database']['de-ch'] = "Datenbankkonfiguration "; //copied from de-de
$text['header-config_database']['de-de'] = "Datenbankkonfiguration ";
$text['header-config_database']['es-cl'] = "Configuración de la base de datos";
$text['header-config_database']['es-mx'] = "Configuración de la base de datos"; //copied from es-cl
$text['header-config_database']['fr-ca'] = "Configuration de base de données"; //copied from fr-fr
$text['header-config_database']['fr-fr'] = "Configuration de base de données";
$text['header-config_database']['he-il'] = "";
$text['header-config_database']['it-it'] = "Configurazione Database";
$text['header-config_database']['nl-nl'] = "";
$text['header-config_database']['pl-pl'] = "Konfiguracja bazy danych";
$text['header-config_database']['pt-br'] = "Configuration Database"; //copied from pt-pt
$text['header-config_database']['pt-pt'] = "Configuration Database";
$text['header-config_database']['ro-ro'] = "";
$text['header-config_database']['ru-ru'] = "Конфигурация базы данных";
$text['header-config_database']['sv-se'] = "Databaskonfiguration ";
$text['header-config_database']['uk-ua'] = "конфігурація бази даних";

$text['header-installing']['en-us'] = "Executing Install";
$text['header-installing']['en-gb'] = "Executing Install";
$text['header-installing']['ar-eg'] = "تنفيذ التثبيت";
$text['header-installing']['de-at'] = "Installation ausführen"; //copied from de-de
$text['header-installing']['de-ch'] = "Installation ausführen"; //copied from de-de
$text['header-installing']['de-de'] = "Installation ausführen";
$text['header-installing']['es-cl'] = "Instalar la ejecución";
$text['header-installing']['es-mx'] = "Instalar la ejecución"; //copied from es-cl
$text['header-installing']['fr-ca'] = "Installez exécution"; //copied from fr-fr
$text['header-installing']['fr-fr'] = "Installez exécution";
$text['header-installing']['he-il'] = "";
$text['header-installing']['it-it'] = "Installazione in corso";
$text['header-installing']['nl-nl'] = "";
$text['header-installing']['pl-pl'] = "Wykonywanie Install";
$text['header-installing']['pt-br'] = "Execução Instalar"; //copied from pt-pt
$text['header-installing']['pt-pt'] = "Execução Instalar";
$text['header-installing']['ro-ro'] = "";
$text['header-installing']['ru-ru'] = "Выполнение установки";
$text['header-installing']['sv-se'] = "Exekvera Installera";
$text['header-installing']['uk-ua'] = "виконання Встановіть";

$text['description-event_host']['en-us'] = "Enter the event socket host name or IP address.";
$text['description-event_host']['en-gb'] = "Enter the event socket host name or IP address.";
$text['description-event_host']['ar-eg'] = "أدخل اسم المضيف مأخذ الحدث.";
$text['description-event_host']['de-at'] = "Geben Sie die Hostnamen oder die IP-Adresse  für den Event-Socket an."; //copied from de-de
$text['description-event_host']['de-ch'] = "Geben Sie die Hostnamen oder die IP-Adresse  für den Event-Socket an."; //copied from de-de
$text['description-event_host']['de-de'] = "Geben Sie die Hostnamen oder die IP-Adresse  für den Event-Socket an.";
$text['description-event_host']['es-cl'] = "Introduzca el nombre de host toma evento o dirección IP.";
$text['description-event_host']['es-mx'] = "Introduzca el nombre de host toma evento o dirección IP."; //copied from es-cl
$text['description-event_host']['fr-ca'] = "Entrez le socket nom d'hôte de l'événement ou de l'adresse IP."; //copied from fr-fr
$text['description-event_host']['fr-fr'] = "Entrez le socket nom d'hôte de l'événement ou de l'adresse IP.";
$text['description-event_host']['he-il'] = "";
$text['description-event_host']['it-it'] = "Inserisci il nome host o l'indirizzo IP per gli eventi socket.";
$text['description-event_host']['nl-nl'] = "";
$text['description-event_host']['pl-pl'] = "Wprowadź nazwę hosta gniazda wydarzenie lub adres IP.";
$text['description-event_host']['pt-br'] = "Digite o nome do host tomada evento ou endereço IP."; //copied from pt-pt
$text['description-event_host']['pt-pt'] = "Digite o nome do host tomada evento ou endereço IP.";
$text['description-event_host']['ro-ro'] = "";
$text['description-event_host']['ru-ru'] = "Введите имя хоста сокета события или IP-адрес.";
$text['description-event_host']['sv-se'] = "Ange händelsen uttag värdnamn eller IP-adress.";
$text['description-event_host']['uk-ua'] = "Введіть проведення сокета ім'я хоста або IP-адресу.";

$text['description-event_port']['en-us'] = "Enter the event socket port number.";
$text['description-event_port']['en-gb'] = "Enter the event socket port number.";
$text['description-event_port']['ar-eg'] = "أدخل رقم الحدث ميناء المقبس.";
$text['description-event_port']['de-at'] = "Geben Sie die Portnummer des Event-Sockets an"; //copied from de-de
$text['description-event_port']['de-ch'] = "Geben Sie die Portnummer des Event-Sockets an"; //copied from de-de
$text['description-event_port']['de-de'] = "Geben Sie die Portnummer des Event-Sockets an";
$text['description-event_port']['es-cl'] = "Introduzca el número de puerto de socket evento.";
$text['description-event_port']['es-mx'] = "Introduzca el número de puerto de socket evento."; //copied from es-cl
$text['description-event_port']['fr-ca'] = "Entrez le numéro cas de port du socket."; //copied from fr-fr
$text['description-event_port']['fr-fr'] = "Entrez le numéro cas de port du socket.";
$text['description-event_port']['he-il'] = "";
$text['description-event_port']['it-it'] = "Inseriesci il numero porta per gli eventi socket.";
$text['description-event_port']['nl-nl'] = "";
$text['description-event_port']['pl-pl'] = "Wprowadź numer portu gniazda zdarzenia.";
$text['description-event_port']['pt-br'] = "Digite o número do evento porta de soquete."; //copied from pt-pt
$text['description-event_port']['pt-pt'] = "Digite o número do evento porta de soquete.";
$text['description-event_port']['ro-ro'] = "";
$text['description-event_port']['ru-ru'] = "Введите номер порта сокета события.";
$text['description-event_port']['sv-se'] = "Ange händelsen socket portnummer.";
$text['description-event_port']['uk-ua'] = "Введіть номер подія гніздо порту.";

$text['description-event_password']['en-us'] = "Enter the event socket password.";
$text['description-event_password']['en-gb'] = "Enter the event socket password.";
$text['description-event_password']['ar-eg'] = "أدخل كلمة المرور مأخذ الحدث.";
$text['description-event_password']['de-at'] = "Geben Sie das Passwort für den Event-Socket an."; //copied from de-de
$text['description-event_password']['de-ch'] = "Geben Sie das Passwort für den Event-Socket an."; //copied from de-de
$text['description-event_password']['de-de'] = "Geben Sie das Passwort für den Event-Socket an.";
$text['description-event_password']['es-cl'] = "Introduzca la toma evento contraseña.";
$text['description-event_password']['es-mx'] = "Introduzca la toma evento contraseña."; //copied from es-cl
$text['description-event_password']['fr-ca'] = "Saisissez la prise de mot de passe de l'événement."; //copied from fr-fr
$text['description-event_password']['fr-fr'] = "Saisissez la prise de mot de passe de l'événement.";
$text['description-event_password']['he-il'] = "";
$text['description-event_password']['it-it'] = "Inserisci la password per gli eventi socket.";
$text['description-event_password']['nl-nl'] = "";
$text['description-event_password']['pl-pl'] = "Wprowadź hasło gniazda zdarzenia.";
$text['description-event_password']['pt-br'] = "Digite tomada a senha evento."; //copied from pt-pt
$text['description-event_password']['pt-pt'] = "Digite tomada a senha evento.";
$text['description-event_password']['ro-ro'] = "";
$text['description-event_password']['ru-ru'] = "Введите пароль сокета события.";
$text['description-event_password']['sv-se'] = "Ange händelsen uttag lösenord.";
$text['description-event_password']['uk-ua'] = "Введіть гніздо пароль подією.";

$text['description-username']['en-us'] = "Enter the database username.";
$text['description-username']['en-gb'] = "Enter the database username.";
$text['description-username']['ar-eg'] = "أدخل اسم المستخدم هنا";
$text['description-username']['de-at'] = "Geben Sie den Benutzernamen für die Datenbank an."; //copied from de-de
$text['description-username']['de-ch'] = "Geben Sie den Benutzernamen für die Datenbank an."; //copied from de-de
$text['description-username']['de-de'] = "Geben Sie den Benutzernamen für die Datenbank an.";
$text['description-username']['es-cl'] = "Ingrese el nombre de usuario de la base de datos.";
$text['description-username']['es-mx'] = "Ingrese el nombre de usuario de la base de datos."; //copied from es-cl
$text['description-username']['fr-ca'] = "Entrer le nom d'utilisateur de la Base de données."; //copied from fr-fr
$text['description-username']['fr-fr'] = "Entrer le nom d'utilisateur de la Base de données.";
$text['description-username']['he-il'] = "";
$text['description-username']['it-it'] = "Inserisci il nome utente del database.";
$text['description-username']['nl-nl'] = "";
$text['description-username']['pl-pl'] = "Wprowadź nazwę użytkownika";
$text['description-username']['pt-br'] = "Insira o nome do usuário";
$text['description-username']['pt-pt'] = "Introduza o utilizador da base de dados.";
$text['description-username']['ro-ro'] = "";
$text['description-username']['ru-ru'] = "Введите имя пользователя базы данных.";
$text['description-username']['sv-se'] = "Ange databasen användarnamn här.";
$text['description-username']['uk-ua'] = "Введіть ім’я користувача бази даних";

$text['description-type']['en-us'] = "Select the database type.";
$text['description-type']['en-gb'] = "Select the database type.";
$text['description-type']['ar-eg'] = "إختر نوع قاعدة البيانات";
$text['description-type']['de-at'] = "Wählen Sie den Datenbank Typ."; //copied from de-de
$text['description-type']['de-ch'] = "Wählen Sie den Datenbank Typ."; //copied from de-de
$text['description-type']['de-de'] = "Wählen Sie den Datenbank Typ.";
$text['description-type']['es-cl'] = "Seleccione el tipo de base de datos";
$text['description-type']['es-mx'] = "Seleccione el tipo de base de datos"; //copied from es-cl
$text['description-type']['fr-ca'] = "Choisir le type de Base de données."; //copied from fr-fr
$text['description-type']['fr-fr'] = "Choisir le type de Base de données.";
$text['description-type']['he-il'] = "";
$text['description-type']['it-it'] = "Seleziona il tipo di database.";
$text['description-type']['nl-nl'] = "";
$text['description-type']['pl-pl'] = "Wprowadź rodzaj bazy danych";
$text['description-type']['pt-br'] = "Introduza o tipo de definição.";
$text['description-type']['pt-pt'] = "Escolha o tipo de base de dados.";
$text['description-type']['ro-ro'] = "";
$text['description-type']['ru-ru'] = "Выберите тип базы данных.";
$text['description-type']['sv-se'] = "Välj databastyp";
$text['description-type']['uk-ua'] = "Виберіть тип бази даних";

$text['description-port']['en-us'] = "Enter the port number.";
$text['description-port']['en-gb'] = "Enter the port number.";
$text['description-port']['ar-eg'] = "أدخل رقم المنفذ";
$text['description-port']['de-at'] = "Geben Sie die Portnummer an."; //copied from de-de
$text['description-port']['de-ch'] = "Geben Sie die Portnummer an."; //copied from de-de
$text['description-port']['de-de'] = "Geben Sie die Portnummer an.";
$text['description-port']['es-cl'] = "Ingrese el número del puerto.";
$text['description-port']['es-mx'] = "Ingrese el número del puerto."; //copied from es-cl
$text['description-port']['fr-ca'] = "Entrer le numéro de port."; //copied from fr-fr
$text['description-port']['fr-fr'] = "Entrer le numéro de port.";
$text['description-port']['he-il'] = "";
$text['description-port']['it-it'] = "Inserisci il numero di porta.";
$text['description-port']['nl-nl'] = "";
$text['description-port']['pl-pl'] = "Wprowadź numer portu";
$text['description-port']['pt-br'] = "Insira o número da porta";
$text['description-port']['pt-pt'] = "Introduza o número do porto.";
$text['description-port']['ro-ro'] = "";
$text['description-port']['ru-ru'] = "Введите номер порта.";
$text['description-port']['sv-se'] = "Ange portnummer";
$text['description-port']['uk-ua'] = "Введіть номер порта";

$text['description-path']['en-us'] = "Enter the database file path (SQLite only).";
$text['description-path']['en-gb'] = "Enter the database file path (SQLite only).";
$text['description-path']['ar-eg'] = "أدخل مسار ملف قاعدة البيانات (سكليتي فقط).";
$text['description-path']['de-at'] = "Geben Sie den Datenbank Pfad an (nur für SQLite)."; //copied from de-de
$text['description-path']['de-ch'] = "Geben Sie den Datenbank Pfad an (nur für SQLite)."; //copied from de-de
$text['description-path']['de-de'] = "Geben Sie den Datenbank Pfad an (nur für SQLite).";
$text['description-path']['es-cl'] = "Ingrese la ruta al archivo de datos (solo SQLite).";
$text['description-path']['es-mx'] = "Ingrese la ruta al archivo de datos (solo SQLite)."; //copied from es-cl
$text['description-path']['fr-ca'] = "Entrer le chemin du fichier Base de données (Spécifique SQLite)."; //copied from fr-fr
$text['description-path']['fr-fr'] = "Entrer le chemin du fichier Base de données (Spécifique SQLite).";
$text['description-path']['he-il'] = "";
$text['description-path']['it-it'] = "Inserisci il percorso del database (solo SQLite).";
$text['description-path']['nl-nl'] = "";
$text['description-path']['pl-pl'] = "Wprowadź ścieżkę do pliku bazy danych (tylko SQLite)";
$text['description-path']['pt-br'] = "Insira o caminho da base de dados (SQLite)";
$text['description-path']['pt-pt'] = "Introduza o caminho da base de dados (apenas SQLite)";
$text['description-path']['ro-ro'] = "";
$text['description-path']['ru-ru'] = "Введите путь к файлу базы данных (только для SQLite).";
$text['description-path']['sv-se'] = "Ange databasens sökväg (gäller endast SQLite).";
$text['description-path']['uk-ua'] = "Вкажіть шлях до файлу бази даних (тільки SQLite).";

$text['description-password']['en-us'] = "Enter the database password.";
$text['description-password']['en-gb'] = "Enter the database password.";
$text['description-password']['ar-eg'] = "أدخل الرقم السري الخاص بقاعدة البيانات";
$text['description-password']['de-at'] = "Geben Sie das Password für die Datenbank ein."; //copied from de-de
$text['description-password']['de-ch'] = "Geben Sie das Password für die Datenbank ein."; //copied from de-de
$text['description-password']['de-de'] = "Geben Sie das Password für die Datenbank ein.";
$text['description-password']['es-cl'] = "Ingrese la contraseña de la base de datos.";
$text['description-password']['es-mx'] = "Ingrese la contraseña de la base de datos."; //copied from es-cl
$text['description-password']['fr-ca'] = "Entrer le mot de passe pour la Base de données."; //copied from fr-fr
$text['description-password']['fr-fr'] = "Entrer le mot de passe pour la Base de données.";
$text['description-password']['he-il'] = "";
$text['description-password']['it-it'] = "Inserisci la password del database.";
$text['description-password']['nl-nl'] = "";
$text['description-password']['pl-pl'] = "Wpisz hasło";
$text['description-password']['pt-br'] = "Introduza a senha";
$text['description-password']['pt-pt'] = "Introduza a palavra-chave da base de dados.";
$text['description-password']['ro-ro'] = "";
$text['description-password']['ru-ru'] = "Введите пароль базы данных.";
$text['description-password']['sv-se'] = "Ange databasens lösenord.";
$text['description-password']['uk-ua'] = "Введіть пароль бази даних.";

$text['description-name']['en-us'] = "Enter the database name.";
$text['description-name']['en-gb'] = "Enter the database name.";
$text['description-name']['ar-eg'] = "أدخل إسم قاعدة البيانات";
$text['description-name']['de-at'] = "Geben Sie den Namen der Datenbank an"; //copied from de-de
$text['description-name']['de-ch'] = "Geben Sie den Namen der Datenbank an"; //copied from de-de
$text['description-name']['de-de'] = "Geben Sie den Namen der Datenbank an";
$text['description-name']['es-cl'] = "Ingrese el nombre de la base de datos.";
$text['description-name']['es-mx'] = "Ingrese el nombre de la base de datos."; //copied from es-cl
$text['description-name']['fr-ca'] = "Entrer le nom de la Base de données."; //copied from fr-fr
$text['description-name']['fr-fr'] = "Entrer le nom de la Base de données.";
$text['description-name']['he-il'] = "";
$text['description-name']['it-it'] = "Inserisci il nome del database.";
$text['description-name']['nl-nl'] = "";
$text['description-name']['pl-pl'] = "Wprowadź nazwę bazy danych.";
$text['description-name']['pt-br'] = "Insira o nome do menu";
$text['description-name']['pt-pt'] = "Introduza o nome da base de dados.";
$text['description-name']['ro-ro'] = "";
$text['description-name']['ru-ru'] = "Введите имя базы данных.";
$text['description-name']['sv-se'] = "Ange databasens namn.";
$text['description-name']['uk-ua'] = "Введіть ім'я бази даних.";

$text['description-host']['en-us'] = "Enter the host name.";
$text['description-host']['en-gb'] = "Enter the host name.";
$text['description-host']['ar-eg'] = "أدخل إسم المضيف";
$text['description-host']['de-at'] = "Geben Sie den Hostnamen ein."; //copied from de-de
$text['description-host']['de-ch'] = "Geben Sie den Hostnamen ein."; //copied from de-de
$text['description-host']['de-de'] = "Geben Sie den Hostnamen ein.";
$text['description-host']['es-cl'] = "Ingrese el nombre de host";
$text['description-host']['es-mx'] = "Ingrese el nombre de host"; //copied from es-cl
$text['description-host']['fr-ca'] = "Entrer le nom de l'hôte."; //copied from fr-fr
$text['description-host']['fr-fr'] = "Entrer le nom de l'hôte.";
$text['description-host']['he-il'] = "";
$text['description-host']['it-it'] = "Inserisci il nome host.";
$text['description-host']['nl-nl'] = "";
$text['description-host']['pl-pl'] = "Wprowadź nazwę hosta.";
$text['description-host']['pt-br'] = "Insira o nome da máquina ";
$text['description-host']['pt-pt'] = "Introduza o nome da máquina.";
$text['description-host']['ro-ro'] = "";
$text['description-host']['ru-ru'] = "Введите имя хоста.";
$text['description-host']['sv-se'] = "Ange värdnamnet";
$text['description-host']['uk-ua'] = "Введіть ім'я хоста.";

$text['description-driver']['en-us'] = "Select the database driver.";
$text['description-driver']['en-gb'] = "Select the database driver.";
$text['description-driver']['ar-eg'] = "حدد برنامج تشغيل قاعدة البيانات.";
$text['description-driver']['de-at'] = "Wählen Sie den Datenbank Treiber."; //copied from de-de
$text['description-driver']['de-ch'] = "Wählen Sie den Datenbank Treiber."; //copied from de-de
$text['description-driver']['de-de'] = "Wählen Sie den Datenbank Treiber.";
$text['description-driver']['es-cl'] = "Seleccione un controlador de base de datos.";
$text['description-driver']['es-mx'] = "Seleccione un controlador de base de datos."; //copied from es-cl
$text['description-driver']['fr-ca'] = "Choisir le driver de la Base de données."; //copied from fr-fr
$text['description-driver']['fr-fr'] = "Choisir le driver de la Base de données.";
$text['description-driver']['he-il'] = "";
$text['description-driver']['it-it'] = "Seleziona il driver del database.";
$text['description-driver']['nl-nl'] = "";
$text['description-driver']['pl-pl'] = "Wybierz sterownik bazy danych.";
$text['description-driver']['pt-br'] = "Escolha o driver da base de dados"; //copied from pt-pt
$text['description-driver']['pt-pt'] = "Escolha o driver da base de dados";
$text['description-driver']['ro-ro'] = "";
$text['description-driver']['ru-ru'] = "Выберите драйвер базы данных.";
$text['description-driver']['sv-se'] = "Välj databas drivrutin.";
$text['description-driver']['uk-ua'] = "Виберіть драйвер бази даних.";

$text['description-install']['en-us'] = "Select the action below you wish to perform.";
$text['description-install']['en-gb'] = "Select the action below you wish to perform.";
$text['description-install']['ar-eg'] = "حدد الإجراء أدناه كنت ترغب في القيام بها.";
$text['description-install']['de-at'] = "Wählen Sie eine Aktion."; //copied from de-de
$text['description-install']['de-ch'] = "Wählen Sie eine Aktion."; //copied from de-de
$text['description-install']['de-de'] = "Wählen Sie eine Aktion.";
$text['description-install']['es-cl'] = "Seleccione las accion a continuación que desea realizar.";
$text['description-install']['es-mx'] = "Seleccione las accion a continuación que desea realizar."; //copied from es-cl
$text['description-install']['fr-ca'] = "Sélectionnez l'action ci-dessous que vous souhaitez effectuer."; //copied from fr-fr
$text['description-install']['fr-fr'] = "Sélectionnez l'action ci-dessous que vous souhaitez effectuer.";
$text['description-install']['he-il'] = "";
$text['description-install']['it-it'] = "Seleziona l'azione che si vuole eseguire.";
$text['description-install']['nl-nl'] = "";
$text['description-install']['pl-pl'] = "Wybierz opcje, które chcesz wykonać.";
$text['description-install']['pt-br'] = "Seleciona as ações abaixo que deseja executar ";
$text['description-install']['pt-pt'] = "Selecione as ações abaixo você deseja executar.";
$text['description-install']['ro-ro'] = "";
$text['description-install']['ru-ru'] = "Выберите действие ниже, которое вы хотите выполнить.";
$text['description-install']['sv-se'] = "Välj de åtgärder nedan som du vill utföra.";
$text['description-install']['uk-ua'] = "Виберіть об’єкти для оновлення";

$text['description-database-edit']['en-us'] = "Database connection information.";
$text['description-database-edit']['en-gb'] = "Database connection information.";
$text['description-database-edit']['ar-eg'] = "بيانات الإتصال الخاص بقاعدة البيانات";
$text['description-database-edit']['de-at'] = "Datenbank Verbindungsinformation."; //copied from de-de
$text['description-database-edit']['de-ch'] = "Datenbank Verbindungsinformation."; //copied from de-de
$text['description-database-edit']['de-de'] = "Datenbank Verbindungsinformation.";
$text['description-database-edit']['es-cl'] = "Información de conexión a base de datos.";
$text['description-database-edit']['es-mx'] = "Información de conexión a base de datos."; //copied from es-cl
$text['description-database-edit']['fr-ca'] = "Informations de connexion à la Base"; //copied from fr-fr
$text['description-database-edit']['fr-fr'] = "Informations de connexion à la Base";
$text['description-database-edit']['he-il'] = "";
$text['description-database-edit']['it-it'] = "Informazioni di connessione al Database.";
$text['description-database-edit']['nl-nl'] = "";
$text['description-database-edit']['pl-pl'] = "Informacje o połączeniach z bazą danych.";
$text['description-database-edit']['pt-br'] = "Informações da ligação na base de dados";
$text['description-database-edit']['pt-pt'] = "Informação da ligação à base de dados.";
$text['description-database-edit']['ro-ro'] = "";
$text['description-database-edit']['ru-ru'] = "Информация о соединении с базой данных.";
$text['description-database-edit']['sv-se'] = "Information om Databasanslutning";
$text['description-database-edit']['uk-ua'] = "інформація про підключення до бази даних.";

$text['description-database-add']['en-us'] = "Database connection information.";
$text['description-database-add']['en-gb'] = "Database connection information.";
$text['description-database-add']['ar-eg'] = "بيانات الإتصال الخاص بقاعدة البيانات";
$text['description-database-add']['de-at'] = "Datenbank Verbindungsinformation."; //copied from de-de
$text['description-database-add']['de-ch'] = "Datenbank Verbindungsinformation."; //copied from de-de
$text['description-database-add']['de-de'] = "Datenbank Verbindungsinformation.";
$text['description-database-add']['es-cl'] = "Información de conexión a base de datos.";
$text['description-database-add']['es-mx'] = "Información de conexión a base de datos."; //copied from es-cl
$text['description-database-add']['fr-ca'] = "Informations de connexion à la Base de donnée."; //copied from fr-fr
$text['description-database-add']['fr-fr'] = "Informations de connexion à la Base de donnée.";
$text['description-database-add']['he-il'] = "";
$text['description-database-add']['it-it'] = "Informazioni di connessione al Database.";
$text['description-database-add']['nl-nl'] = "";
$text['description-database-add']['pl-pl'] = "Informacje o połączeniach z bazą danych.";
$text['description-database-add']['pt-br'] = "Informações da ligação na base de dados";
$text['description-database-add']['pt-pt'] = "Informação da ligação à base de dados.";
$text['description-database-add']['ro-ro'] = "";
$text['description-database-add']['ru-ru'] = "Информация о соединении с базой данных.";
$text['description-database-add']['sv-se'] = "Information om Databasanslutning";
$text['description-database-add']['uk-ua'] = "інформація про підключення до бази даних.";

$text['description-select_language']['en-us'] = "Please select the language you want to use";
$text['description-select_language']['en-gb'] = "Please select the language you want to use";
$text['description-select_language']['ar-eg'] = "يرجى اختيار اللغة التي تريد استخدامها";
$text['description-select_language']['de-at'] = "Bitte wählen Sie die zu verwendende Sprache aus"; //copied from de-de
$text['description-select_language']['de-ch'] = "Bitte wählen Sie die zu verwendende Sprache aus"; //copied from de-de
$text['description-select_language']['de-de'] = "Bitte wählen Sie die zu verwendende Sprache aus";
$text['description-select_language']['es-cl'] = "Por favor, seleccione el idioma que desea utilizar";
$text['description-select_language']['es-mx'] = "Por favor, seleccione el idioma que desea utilizar"; //copied from es-cl
$text['description-select_language']['fr-ca'] = "S'il vous plaît choisir la langue que vous souhaitez utiliser"; //copied from fr-fr
$text['description-select_language']['fr-fr'] = "S'il vous plaît choisir la langue que vous souhaitez utiliser";
$text['description-select_language']['he-il'] = "";
$text['description-select_language']['it-it'] = "Per favore seleziona la lingua che desideri usare";
$text['description-select_language']['nl-nl'] = "";
$text['description-select_language']['pl-pl'] = "Wybierz język, którego chcesz używać";
$text['description-select_language']['pt-br'] = "Por favor, selecione o idioma que deseja usar"; //copied from pt-pt
$text['description-select_language']['pt-pt'] = "Por favor, selecione o idioma que deseja usar";
$text['description-select_language']['ro-ro'] = "";
$text['description-select_language']['ru-ru'] = "Выберите язык, который вы хотите использовать";
$text['description-select_language']['sv-se'] = "Välj det språk du vill använda";
$text['description-select_language']['uk-ua'] = "Виберіть мову, який ви хочете використовувати";

$text['button-detect']['en-us'] = "Detect Configuration";
$text['button-detect']['en-gb'] = "Detect Configuration";
$text['button-detect']['ar-eg'] = "كشف تكوين";
$text['button-detect']['de-at'] = "Konfiguration ermitteln"; //copied from de-de
$text['button-detect']['de-ch'] = "Konfiguration ermitteln"; //copied from de-de
$text['button-detect']['de-de'] = "Konfiguration ermitteln";
$text['button-detect']['es-cl'] = "Detectar Configuración";
$text['button-detect']['es-mx'] = "Detectar Configuración"; //copied from es-cl
$text['button-detect']['fr-ca'] = "Détecter Configuration"; //copied from fr-fr
$text['button-detect']['fr-fr'] = "Détecter Configuration";
$text['button-detect']['he-il'] = "";
$text['button-detect']['it-it'] = "Rileva Configurazione";
$text['button-detect']['nl-nl'] = "";
$text['button-detect']['pl-pl'] = "Wykrywanie Konfiguracja";
$text['button-detect']['pt-br'] = "Detectar Configuração"; //copied from pt-pt
$text['button-detect']['pt-pt'] = "Detectar Configuração";
$text['button-detect']['ro-ro'] = "";
$text['button-detect']['ru-ru'] = "Определить конфигурацию";
$text['button-detect']['sv-se'] = "Detektera Konfiguration";
$text['button-detect']['uk-ua'] = "виявлення Конфігурація";

$text['button-select']['en-us'] = "Select";
$text['button-select']['en-gb'] = "Select";
$text['button-select']['ar-eg'] = "اختار";
$text['button-select']['de-at'] = "Auswählen"; //copied from de-de
$text['button-select']['de-ch'] = "Auswählen"; //copied from de-de
$text['button-select']['de-de'] = "Auswählen";
$text['button-select']['es-cl'] = "Seleccionar";
$text['button-select']['es-mx'] = "Seleccionar"; //copied from es-cl
$text['button-select']['fr-ca'] = "Sélectionner"; //copied from fr-fr
$text['button-select']['fr-fr'] = "Sélectionner";
$text['button-select']['he-il'] = "";
$text['button-select']['it-it'] = "Seleziona";
$text['button-select']['nl-nl'] = "";
$text['button-select']['pl-pl'] = "Wybierz";
$text['button-select']['pt-br'] = "Selecionar"; //copied from pt-pt
$text['button-select']['pt-pt'] = "Selecionar";
$text['button-select']['ro-ro'] = "";
$text['button-select']['ru-ru'] = "Выбрать";
$text['button-select']['sv-se'] = "Välj";
$text['button-select']['uk-ua'] = "вибрати";

?>
