<?php
#This file was last reorganized on 19th of September 2017 08:54:24 AM UTC

$text['title-music_on_hold_settings']['en-us'] = "Music on Hold Settings";
$text['title-music_on_hold_settings']['en-gb'] = "Music on Hold Settings";
$text['title-music_on_hold_settings']['ar-eg'] = "";
$text['title-music_on_hold_settings']['de-at'] = "Wartemusik Einstellungen"; //copied from de-de
$text['title-music_on_hold_settings']['de-ch'] = "Wartemusik Einstellungen"; //copied from de-de
$text['title-music_on_hold_settings']['de-de'] = "Wartemusik Einstellungen";
$text['title-music_on_hold_settings']['es-cl'] = "Musica en Espera ajustes";
$text['title-music_on_hold_settings']['es-mx'] = "Musica en Espera ajustes"; //copied from es-cl
$text['title-music_on_hold_settings']['fr-ca'] = "Musique d'attente paramètres"; //copied from fr-fr
$text['title-music_on_hold_settings']['fr-fr'] = "Musique d'attente paramètres";
$text['title-music_on_hold_settings']['he-il'] = "מוסיקה על גדרות מתן";
$text['title-music_on_hold_settings']['it-it'] = "Parametri Musica di Attesa";
$text['title-music_on_hold_settings']['nl-nl'] = "Wachtmuziek instellingen";
$text['title-music_on_hold_settings']['pl-pl'] = "Muzyka na czekanie ustawienia";
$text['title-music_on_hold_settings']['pt-br'] = "Música de espera configurações";
$text['title-music_on_hold_settings']['pt-pt'] = "Música em Espera configurações";
$text['title-music_on_hold_settings']['ro-ro'] = "";
$text['title-music_on_hold_settings']['ru-ru'] = "Музыка на удержание параметры";
$text['title-music_on_hold_settings']['sv-se'] = "Väntmusik inställningar";
$text['title-music_on_hold_settings']['uk-ua'] = "Музика на утриманні настройки";

$text['title-music_on_hold']['en-us'] = "Music on Hold";
$text['title-music_on_hold']['en-gb'] = "Music on Hold";
$text['title-music_on_hold']['ar-eg'] = "";
$text['title-music_on_hold']['de-at'] = "Wartemusik"; //copied from de-de
$text['title-music_on_hold']['de-ch'] = "Wartemusik"; //copied from de-de
$text['title-music_on_hold']['de-de'] = "Wartemusik";
$text['title-music_on_hold']['es-cl'] = "Musica en Espera";
$text['title-music_on_hold']['es-mx'] = "Musica en Espera"; //copied from es-cl
$text['title-music_on_hold']['fr-ca'] = "Musique d'attente"; //copied from fr-fr
$text['title-music_on_hold']['fr-fr'] = "Musique d'attente";
$text['title-music_on_hold']['he-il'] = "מוסיקה בהמתנה";
$text['title-music_on_hold']['it-it'] = "Musica di Attesa";
$text['title-music_on_hold']['nl-nl'] = "Wachtmuziek";
$text['title-music_on_hold']['pl-pl'] = "Muzyka na czekanie";
$text['title-music_on_hold']['pt-br'] = "Música de espera";
$text['title-music_on_hold']['pt-pt'] = "Música em Espera";
$text['title-music_on_hold']['ro-ro'] = "";
$text['title-music_on_hold']['ru-ru'] = "Музыка на удержании";
$text['title-music_on_hold']['sv-se'] = "Väntmusik";
$text['title-music_on_hold']['uk-ua'] = "Музика на утриманні";

$text['label-others']['en-us'] = "Others";
$text['label-others']['en-gb'] = "Others";
$text['label-others']['ar-eg'] = "آخرون";
$text['label-others']['de-at'] = "Andere"; //copied from de-de
$text['label-others']['de-ch'] = "Andere"; //copied from de-de
$text['label-others']['de-de'] = "Andere";
$text['label-others']['es-cl'] = "";
$text['label-others']['es-mx'] = "";
$text['label-others']['fr-ca'] = "Autres"; //copied from fr-fr
$text['label-others']['fr-fr'] = "Autres";
$text['label-others']['he-il'] = "אחרים";
$text['label-others']['it-it'] = "Altri";
$text['label-others']['nl-nl'] = "Andere";
$text['label-others']['pl-pl'] = "Pozostałe";
$text['label-others']['pt-br'] = "Outras"; //copied from pt-pt
$text['label-others']['pt-pt'] = "Outras";
$text['label-others']['ro-ro'] = "";
$text['label-others']['ru-ru'] = "другие";
$text['label-others']['sv-se'] = "Andra";
$text['label-others']['uk-ua'] = "інші";

$text['option-local']['en-us'] = "Local";
$text['option-local']['en-gb'] = "Local";
$text['option-local']['ar-eg'] = "";
$text['option-local']['de-at'] = "lokal"; //copied from de-de
$text['option-local']['de-ch'] = "lokal"; //copied from de-de
$text['option-local']['de-de'] = "lokal";
$text['option-local']['es-cl'] = "Local";
$text['option-local']['es-mx'] = "Local"; //copied from es-cl
$text['option-local']['fr-ca'] = "locale"; //copied from fr-fr
$text['option-local']['fr-fr'] = "locale";
$text['option-local']['he-il'] = "מְקוֹמִי";
$text['option-local']['it-it'] = "Locale";
$text['option-local']['nl-nl'] = "Lokaal";
$text['option-local']['pl-pl'] = "Lokalny";
$text['option-local']['pt-br'] = "Local"; //copied from pt-pt
$text['option-local']['pt-pt'] = "Local";
$text['option-local']['ro-ro'] = "";
$text['option-local']['ru-ru'] = "Местный";
$text['option-local']['sv-se'] = "Lokal";
$text['option-local']['uk-ua'] = "місцевий";

$text['option-global']['en-us'] = "Global";
$text['option-global']['en-gb'] = "Global";
$text['option-global']['ar-eg'] = "";
$text['option-global']['de-at'] = "Global"; //copied from de-de
$text['option-global']['de-ch'] = "Global"; //copied from de-de
$text['option-global']['de-de'] = "Global";
$text['option-global']['es-cl'] = "Global";
$text['option-global']['es-mx'] = "Global"; //copied from es-cl
$text['option-global']['fr-ca'] = "Mondial"; //copied from fr-fr
$text['option-global']['fr-fr'] = "Mondial";
$text['option-global']['he-il'] = "כללי";
$text['option-global']['it-it'] = "Globale";
$text['option-global']['nl-nl'] = "Globaal";
$text['option-global']['pl-pl'] = "Globalny";
$text['option-global']['pt-br'] = "Global"; //copied from pt-pt
$text['option-global']['pt-pt'] = "Global";
$text['option-global']['ro-ro'] = "";
$text['option-global']['ru-ru'] = "Глобальный";
$text['option-global']['sv-se'] = "Global";
$text['option-global']['uk-ua'] = "Глобальний";

$text['option-default']['en-us'] = "Default";
$text['option-default']['en-gb'] = "Default";
$text['option-default']['ar-eg'] = "";
$text['option-default']['de-at'] = "Standard"; //copied from de-de
$text['option-default']['de-ch'] = "Standard"; //copied from de-de
$text['option-default']['de-de'] = "Standard";
$text['option-default']['es-cl'] = "Predeterminado";
$text['option-default']['es-mx'] = "Predeterminado"; //copied from es-cl
$text['option-default']['fr-ca'] = "Par défaut"; //copied from fr-fr
$text['option-default']['fr-fr'] = "Par défaut";
$text['option-default']['he-il'] = "ברירת מחדל";
$text['option-default']['it-it'] = "Default";
$text['option-default']['nl-nl'] = "Standaard";
$text['option-default']['pl-pl'] = "Domyślna";
$text['option-default']['pt-br'] = "Predefinido"; //copied from pt-pt
$text['option-default']['pt-pt'] = "Predefinido";
$text['option-default']['ro-ro'] = "";
$text['option-default']['ru-ru'] = "По умолчанию";
$text['option-default']['sv-se'] = "Standard";
$text['option-default']['uk-ua'] = "Типово";

$text['message-upload_completed']['en-us'] = "Upload Completed";
$text['message-upload_completed']['en-gb'] = "Upload Completed";
$text['message-upload_completed']['ar-eg'] = "";
$text['message-upload_completed']['de-at'] = "Erfolgreich hochgeladen"; //copied from de-de
$text['message-upload_completed']['de-ch'] = "Erfolgreich hochgeladen"; //copied from de-de
$text['message-upload_completed']['de-de'] = "Erfolgreich hochgeladen";
$text['message-upload_completed']['es-cl'] = "Cargar Completado";
$text['message-upload_completed']['es-mx'] = "Cargar Completado"; //copied from es-cl
$text['message-upload_completed']['fr-ca'] = "Fichier reçu"; //copied from fr-fr
$text['message-upload_completed']['fr-fr'] = "Fichier reçu";
$text['message-upload_completed']['he-il'] = "העדכון הושלם בהצלחה";
$text['message-upload_completed']['it-it'] = "Caricamento Completato";
$text['message-upload_completed']['nl-nl'] = "Opsturen gereed";
$text['message-upload_completed']['pl-pl'] = "Wysłano pomyślnie";
$text['message-upload_completed']['pt-br'] = "Carregar Concluído"; //copied from pt-pt
$text['message-upload_completed']['pt-pt'] = "Carregar Concluído";
$text['message-upload_completed']['ro-ro'] = "";
$text['message-upload_completed']['ru-ru'] = "Загрузка завершена";
$text['message-upload_completed']['sv-se'] = "Ladda Avslutat";
$text['message-upload_completed']['uk-ua'] = "Завантажено";

$text['message-nofiles']['en-us'] = "No files found.";
$text['message-nofiles']['en-gb'] = "No files found.";
$text['message-nofiles']['ar-eg'] = "";
$text['message-nofiles']['de-at'] = "Es wurden keine Dateien gefunden."; //copied from de-de
$text['message-nofiles']['de-ch'] = "Es wurden keine Dateien gefunden."; //copied from de-de
$text['message-nofiles']['de-de'] = "Es wurden keine Dateien gefunden.";
$text['message-nofiles']['es-cl'] = "No se encontraron archivos.";
$text['message-nofiles']['es-mx'] = "No se encontraron archivos."; //copied from es-cl
$text['message-nofiles']['fr-ca'] = "Pas de fichier trouvé."; //copied from fr-fr
$text['message-nofiles']['fr-fr'] = "Pas de fichier trouvé.";
$text['message-nofiles']['he-il'] = "לא נמצאו קבצים";
$text['message-nofiles']['it-it'] = "File non trovato/i.";
$text['message-nofiles']['nl-nl'] = "Geen bestand gevonden.";
$text['message-nofiles']['pl-pl'] = "Nie znaleziono plików";
$text['message-nofiles']['pt-br'] = "Não foram encontrados os arquivos";
$text['message-nofiles']['pt-pt'] = "Não foram encontrados ficheiros.";
$text['message-nofiles']['ro-ro'] = "";
$text['message-nofiles']['ru-ru'] = "Файлы не найдены";
$text['message-nofiles']['sv-se'] = "Ingen ljudfil.";
$text['message-nofiles']['uk-ua'] = "Файлів не знайдено";

$text['message-missing_required_fields']['en-us'] = "Missing Required Fields";
$text['message-missing_required_fields']['en-gb'] = "Missing Required Fields";
$text['message-missing_required_fields']['ar-eg'] = "";
$text['message-missing_required_fields']['de-at'] = "Fehlende Pflichtangaben "; //copied from de-de
$text['message-missing_required_fields']['de-ch'] = "Fehlende Pflichtangaben "; //copied from de-de
$text['message-missing_required_fields']['de-de'] = "Fehlende Pflichtangaben ";
$text['message-missing_required_fields']['es-cl'] = "Missing Campos requeridos";
$text['message-missing_required_fields']['es-mx'] = "Missing Campos requeridos"; //copied from es-cl
$text['message-missing_required_fields']['fr-ca'] = "Manquant Champs obligatoires"; //copied from fr-fr
$text['message-missing_required_fields']['fr-fr'] = "Manquant Champs obligatoires";
$text['message-missing_required_fields']['he-il'] = "חסרים שדות חובה";
$text['message-missing_required_fields']['it-it'] = "Campi Richiesti Mancanti";
$text['message-missing_required_fields']['nl-nl'] = "Er zijn ontbrekende velden";
$text['message-missing_required_fields']['pl-pl'] = "Brakujące pola wymagane";
$text['message-missing_required_fields']['pt-br'] = "Faltando Campos obrigatórios"; //copied from pt-pt
$text['message-missing_required_fields']['pt-pt'] = "Faltando Campos obrigatórios";
$text['message-missing_required_fields']['ro-ro'] = "";
$text['message-missing_required_fields']['ru-ru'] = "Отсутствуют обязательные поля";
$text['message-missing_required_fields']['sv-se'] = "Saknas Obligatoriska fält";
$text['message-missing_required_fields']['uk-ua'] = "Відсутні поля обов'язкові для заповнення";

$text['message-event-socket']['en-us'] = "Connection to Event Socket failed.";
$text['message-event-socket']['en-gb'] = "Connection to Event Socket failed.";
$text['message-event-socket']['ar-eg'] = "";
$text['message-event-socket']['de-at'] = "Verbindung zum Event Socket unterbrochen."; //copied from de-de
$text['message-event-socket']['de-ch'] = "Verbindung zum Event Socket unterbrochen."; //copied from de-de
$text['message-event-socket']['de-de'] = "Verbindung zum Event Socket unterbrochen.";
$text['message-event-socket']['es-cl'] = "Conexión a socket fallida.";
$text['message-event-socket']['es-mx'] = "Conexión a socket fallida."; //copied from es-cl
$text['message-event-socket']['fr-ca'] = "Connexion à l'Event Socket échouée."; //copied from fr-fr
$text['message-event-socket']['fr-fr'] = "Connexion à l'Event Socket échouée.";
$text['message-event-socket']['he-il'] = "";
$text['message-event-socket']['it-it'] = "Connessione alla Event Socket fallita.";
$text['message-event-socket']['nl-nl'] = "Verbinding met Event-Socket mislukt.";
$text['message-event-socket']['pl-pl'] = "Polączenie do „Event Socket” nie powiodło się.";
$text['message-event-socket']['pt-br'] = "A conexão ao evento Socket falhou";
$text['message-event-socket']['pt-pt'] = "A Conexão ao Event Socket falhou.";
$text['message-event-socket']['ro-ro'] = "";
$text['message-event-socket']['ru-ru'] = "Подключение к сокету событий не удалось.";
$text['message-event-socket']['sv-se'] = "Kontakt till 'Event Socket' misslyckades.";
$text['message-event-socket']['uk-ua'] = "Помилка підключення до сокета подій";

$text['message-click-select']['en-us'] = "Double-Click to Select an Existing Category";
$text['message-click-select']['en-gb'] = "Double-Click to Select an Existing Category";
$text['message-click-select']['ar-eg'] = "";
$text['message-click-select']['de-at'] = "Doppelklicken Sie um eine existierende Kategorie auszuwählen"; //copied from de-de
$text['message-click-select']['de-ch'] = "Doppelklicken Sie um eine existierende Kategorie auszuwählen"; //copied from de-de
$text['message-click-select']['de-de'] = "Doppelklicken Sie um eine existierende Kategorie auszuwählen";
$text['message-click-select']['es-cl'] = "Doble click para seleccionar una categoría existente";
$text['message-click-select']['es-mx'] = "Doble click para seleccionar una categoría existente"; //copied from es-cl
$text['message-click-select']['fr-ca'] = "Double cliquez pour choisir une Catégorie existante"; //copied from fr-fr
$text['message-click-select']['fr-fr'] = "Double cliquez pour choisir une Catégorie existante";
$text['message-click-select']['he-il'] = "לחץ פעמיים כדי לבחור קטגוריה קיימת";
$text['message-click-select']['it-it'] = "Doppio click per selezionare una Categoria Esistente";
$text['message-click-select']['nl-nl'] = "Dubbel-klik om een bestaande categorie kiezen";
$text['message-click-select']['pl-pl'] = "Kliknij dwa razy aby wybrać obecną kategorię.";
$text['message-click-select']['pt-br'] = "Duplo clique para selecionar uma categoria existente";
$text['message-click-select']['pt-pt'] = "Duplo-Clique para Seleccionar uma Categoria Existente";
$text['message-click-select']['ro-ro'] = "";
$text['message-click-select']['ru-ru'] = "Дважды щелкните, чтобы выбрать существующую категорию";
$text['message-click-select']['sv-se'] = "Dubbelklicka för att välja en existerande kategori.";
$text['message-click-select']['uk-ua'] = "Двічі клацніть, щоб вибрати існуючу категорію";

$text['label-upload-music_on_hold']['en-us'] = "Upload Music";
$text['label-upload-music_on_hold']['en-gb'] = "Upload Music";
$text['label-upload-music_on_hold']['ar-eg'] = "";
$text['label-upload-music_on_hold']['de-at'] = "Musik hochladen"; //copied from de-de
$text['label-upload-music_on_hold']['de-ch'] = "Musik hochladen"; //copied from de-de
$text['label-upload-music_on_hold']['de-de'] = "Musik hochladen";
$text['label-upload-music_on_hold']['es-cl'] = "Subir Música";
$text['label-upload-music_on_hold']['es-mx'] = "Subir Música"; //copied from es-cl
$text['label-upload-music_on_hold']['fr-ca'] = "Envoyer une musique"; //copied from fr-fr
$text['label-upload-music_on_hold']['fr-fr'] = "Envoyer une musique";
$text['label-upload-music_on_hold']['he-il'] = "הטען מוסיקה";
$text['label-upload-music_on_hold']['it-it'] = "Carica Musica";
$text['label-upload-music_on_hold']['nl-nl'] = "Muziek opsturen";
$text['label-upload-music_on_hold']['pl-pl'] = "Prześlij plik z muzyką";
$text['label-upload-music_on_hold']['pt-br'] = "Carregar música";
$text['label-upload-music_on_hold']['pt-pt'] = "Carregar Música";
$text['label-upload-music_on_hold']['ro-ro'] = "";
$text['label-upload-music_on_hold']['ru-ru'] = "Загрузить музыку";
$text['label-upload-music_on_hold']['sv-se'] = "Ladda Upp Musik";
$text['label-upload-music_on_hold']['uk-ua'] = "Завантажити мелодію";

$text['label-tools']['en-us'] = "Tools";
$text['label-tools']['en-gb'] = "Tools";
$text['label-tools']['ar-eg'] = "";
$text['label-tools']['de-at'] = "Funktionen"; //copied from de-de
$text['label-tools']['de-ch'] = "Funktionen"; //copied from de-de
$text['label-tools']['de-de'] = "Funktionen";
$text['label-tools']['es-cl'] = "Instrumentos";
$text['label-tools']['es-mx'] = "Instrumentos"; //copied from es-cl
$text['label-tools']['fr-ca'] = "Outils"; //copied from fr-fr
$text['label-tools']['fr-fr'] = "Outils";
$text['label-tools']['he-il'] = "כלים";
$text['label-tools']['it-it'] = "Strumenti";
$text['label-tools']['nl-nl'] = "Gereedschappen";
$text['label-tools']['pl-pl'] = "Narzędzia";
$text['label-tools']['pt-br'] = "Ferramentas"; //copied from pt-pt
$text['label-tools']['pt-pt'] = "Ferramentas";
$text['label-tools']['ro-ro'] = "";
$text['label-tools']['ru-ru'] = "Инструменты";
$text['label-tools']['sv-se'] = "Verktyg";
$text['label-tools']['uk-ua'] = "Інструменти";

$text['label-stop']['en-us'] = "Stop";
$text['label-stop']['en-gb'] = "Stop";
$text['label-stop']['ar-eg'] = "";
$text['label-stop']['de-at'] = "Halt"; //copied from de-de
$text['label-stop']['de-ch'] = "Halt"; //copied from de-de
$text['label-stop']['de-de'] = "Halt";
$text['label-stop']['es-cl'] = "Detener";
$text['label-stop']['es-mx'] = "Detener"; //copied from es-cl
$text['label-stop']['fr-ca'] = "Arrêtez"; //copied from fr-fr
$text['label-stop']['fr-fr'] = "Arrêtez";
$text['label-stop']['he-il'] = "תפסיק";
$text['label-stop']['it-it'] = "Ferma";
$text['label-stop']['nl-nl'] = "Stop";
$text['label-stop']['pl-pl'] = "Zatrzymaj się";
$text['label-stop']['pt-br'] = "Pare"; //copied from pt-pt
$text['label-stop']['pt-pt'] = "Pare";
$text['label-stop']['ro-ro'] = "";
$text['label-stop']['ru-ru'] = "Стоп";
$text['label-stop']['sv-se'] = "Sluta";
$text['label-stop']['uk-ua'] = "СТОП";

$text['label-stereo']['en-us'] = "Stereo";
$text['label-stereo']['en-gb'] = "Stereo";
$text['label-stereo']['ar-eg'] = "";
$text['label-stereo']['de-at'] = "Stereo"; //copied from de-de
$text['label-stereo']['de-ch'] = "Stereo"; //copied from de-de
$text['label-stereo']['de-de'] = "Stereo";
$text['label-stereo']['es-cl'] = "Estéreo";
$text['label-stereo']['es-mx'] = "Estéreo"; //copied from es-cl
$text['label-stereo']['fr-ca'] = "Stéréo"; //copied from fr-fr
$text['label-stereo']['fr-fr'] = "Stéréo";
$text['label-stereo']['he-il'] = "סטריאו";
$text['label-stereo']['it-it'] = "Stereo";
$text['label-stereo']['nl-nl'] = "Stereo";
$text['label-stereo']['pl-pl'] = "Stereofoniczny";
$text['label-stereo']['pt-br'] = "Estéreo"; //copied from pt-pt
$text['label-stereo']['pt-pt'] = "Estéreo";
$text['label-stereo']['ro-ro'] = "";
$text['label-stereo']['ru-ru'] = "Стерео";
$text['label-stereo']['sv-se'] = "Stereo";
$text['label-stereo']['uk-ua'] = "стерео";

$text['label-shuffle']['en-us'] = "Shuffle";
$text['label-shuffle']['en-gb'] = "Shuffle";
$text['label-shuffle']['ar-eg'] = "";
$text['label-shuffle']['de-at'] = "Shuffle"; //copied from de-de
$text['label-shuffle']['de-ch'] = "Shuffle"; //copied from de-de
$text['label-shuffle']['de-de'] = "Shuffle";
$text['label-shuffle']['es-cl'] = "Barajar";
$text['label-shuffle']['es-mx'] = "Barajar"; //copied from es-cl
$text['label-shuffle']['fr-ca'] = "battage"; //copied from fr-fr
$text['label-shuffle']['fr-fr'] = "battage";
$text['label-shuffle']['he-il'] = "לְעַרְבֵּב";
$text['label-shuffle']['it-it'] = "Mischia";
$text['label-shuffle']['nl-nl'] = "Wisselen";
$text['label-shuffle']['pl-pl'] = "Człapać";
$text['label-shuffle']['pt-br'] = "embaralhar";
$text['label-shuffle']['pt-pt'] = "battage";
$text['label-shuffle']['ro-ro'] = "";
$text['label-shuffle']['ru-ru'] = "Перемешать";
$text['label-shuffle']['sv-se'] = "Blanda";
$text['label-shuffle']['uk-ua'] = "тасування";

$text['label-select_a_file']['en-us'] = "Select a file...";
$text['label-select_a_file']['en-gb'] = "Select a file...";
$text['label-select_a_file']['ar-eg'] = "";
$text['label-select_a_file']['de-at'] = "Wählen Sie eine Datei ..."; //copied from de-de
$text['label-select_a_file']['de-ch'] = "Wählen Sie eine Datei ..."; //copied from de-de
$text['label-select_a_file']['de-de'] = "Wählen Sie eine Datei ...";
$text['label-select_a_file']['es-cl'] = "Seleccione un archivo...";
$text['label-select_a_file']['es-mx'] = "Seleccione un archivo..."; //copied from es-cl
$text['label-select_a_file']['fr-ca'] = "Sélectionner un fichier..."; //copied from fr-fr
$text['label-select_a_file']['fr-fr'] = "Sélectionner un fichier...";
$text['label-select_a_file']['he-il'] = "בחר קובץ ...";
$text['label-select_a_file']['it-it'] = "Seleziona un file...";
$text['label-select_a_file']['nl-nl'] = "Kies een bestand...";
$text['label-select_a_file']['pl-pl'] = "Wybierz plik ...";
$text['label-select_a_file']['pt-br'] = "Selecione um arquivo ..."; //copied from pt-pt
$text['label-select_a_file']['pt-pt'] = "Selecione um arquivo ...";
$text['label-select_a_file']['ro-ro'] = "";
$text['label-select_a_file']['ru-ru'] = "Виберите файл ...";
$text['label-select_a_file']['sv-se'] = "Välj en fil ...";
$text['label-select_a_file']['uk-ua'] = "Виберіть файл ...";

$text['label-rate']['en-us'] = "Sampling";
$text['label-rate']['en-gb'] = "Sampling";
$text['label-rate']['ar-eg'] = "";
$text['label-rate']['de-at'] = "Abtastrate"; //copied from de-de
$text['label-rate']['de-ch'] = "Abtastrate"; //copied from de-de
$text['label-rate']['de-de'] = "Abtastrate";
$text['label-rate']['es-cl'] = "Muestreo";
$text['label-rate']['es-mx'] = "Muestreo"; //copied from es-cl
$text['label-rate']['fr-ca'] = "Échantillonnage"; //copied from fr-fr
$text['label-rate']['fr-fr'] = "Échantillonnage";
$text['label-rate']['he-il'] = "דגימת קול";
$text['label-rate']['it-it'] = "Campionamento";
$text['label-rate']['nl-nl'] = "Bemonsteren";
$text['label-rate']['pl-pl'] = "Sampling";
$text['label-rate']['pt-br'] = "Amostragem"; //copied from pt-pt
$text['label-rate']['pt-pt'] = "Amostragem";
$text['label-rate']['ro-ro'] = "";
$text['label-rate']['ru-ru'] = "Частота семплирования";
$text['label-rate']['sv-se'] = "Sampling";
$text['label-rate']['uk-ua'] = "Якість";

$text['label-play']['en-us'] = "Play";
$text['label-play']['en-gb'] = "Play";
$text['label-play']['ar-eg'] = "";
$text['label-play']['de-at'] = "Play"; //copied from de-de
$text['label-play']['de-ch'] = "Play"; //copied from de-de
$text['label-play']['de-de'] = "Play";
$text['label-play']['es-cl'] = "Reproducir";
$text['label-play']['es-mx'] = "Reproducir"; //copied from es-cl
$text['label-play']['fr-ca'] = "Lire"; //copied from fr-fr
$text['label-play']['fr-fr'] = "Lire";
$text['label-play']['he-il'] = "נגן";
$text['label-play']['it-it'] = "Suona";
$text['label-play']['nl-nl'] = "Spelen";
$text['label-play']['pl-pl'] = "Odtwórz";
$text['label-play']['pt-br'] = "Tocar"; //copied from pt-pt
$text['label-play']['pt-pt'] = "Tocar";
$text['label-play']['ro-ro'] = "";
$text['label-play']['ru-ru'] = "Проиграть";
$text['label-play']['sv-se'] = "Spela Upp";
$text['label-play']['uk-ua'] = "Відтворити";

$text['label-path']['en-us'] = "Path";
$text['label-path']['en-gb'] = "Path";
$text['label-path']['ar-eg'] = "";
$text['label-path']['de-at'] = "Pfad"; //copied from de-de
$text['label-path']['de-ch'] = "Pfad"; //copied from de-de
$text['label-path']['de-de'] = "Pfad";
$text['label-path']['es-cl'] = "Camino";
$text['label-path']['es-mx'] = "Camino"; //copied from es-cl
$text['label-path']['fr-ca'] = "Chemin"; //copied from fr-fr
$text['label-path']['fr-fr'] = "Chemin";
$text['label-path']['he-il'] = "Path";
$text['label-path']['it-it'] = "Percorso";
$text['label-path']['nl-nl'] = "Pad";
$text['label-path']['pl-pl'] = "Ścieżka";
$text['label-path']['pt-br'] = "Caminho"; //copied from pt-pt
$text['label-path']['pt-pt'] = "Caminho";
$text['label-path']['ro-ro'] = "";
$text['label-path']['ru-ru'] = "Путь";
$text['label-path']['sv-se'] = "Väg";
$text['label-path']['uk-ua'] = "Path";

$text['label-pause']['en-us'] = "Pause";
$text['label-pause']['en-gb'] = "Pause";
$text['label-pause']['ar-eg'] = "";
$text['label-pause']['de-at'] = "Pause"; //copied from de-de
$text['label-pause']['de-ch'] = "Pause"; //copied from de-de
$text['label-pause']['de-de'] = "Pause";
$text['label-pause']['es-cl'] = "Pausa";
$text['label-pause']['es-mx'] = "Pausa"; //copied from es-cl
$text['label-pause']['fr-ca'] = "Pause"; //copied from fr-fr
$text['label-pause']['fr-fr'] = "Pause";
$text['label-pause']['he-il'] = "השהייה";
$text['label-pause']['it-it'] = "Pausa";
$text['label-pause']['nl-nl'] = "Pause";
$text['label-pause']['pl-pl'] = "Pauza";
$text['label-pause']['pt-br'] = "Pausado";
$text['label-pause']['pt-pt'] = "Pausa";
$text['label-pause']['ro-ro'] = "";
$text['label-pause']['ru-ru'] = "Пауза";
$text['label-pause']['sv-se'] = "Paus";
$text['label-pause']['uk-ua'] = "Призупинити";

$text['label-mono']['en-us'] = "Mono";
$text['label-mono']['en-gb'] = "Mono";
$text['label-mono']['ar-eg'] = "";
$text['label-mono']['de-at'] = "Mono"; //copied from de-de
$text['label-mono']['de-ch'] = "Mono"; //copied from de-de
$text['label-mono']['de-de'] = "Mono";
$text['label-mono']['es-cl'] = "Cosa";
$text['label-mono']['es-mx'] = "Cosa"; //copied from es-cl
$text['label-mono']['fr-ca'] = "Chose"; //copied from fr-fr
$text['label-mono']['fr-fr'] = "Chose";
$text['label-mono']['he-il'] = "דבר";
$text['label-mono']['it-it'] = "Mono";
$text['label-mono']['nl-nl'] = "Mono";
$text['label-mono']['pl-pl'] = "rzecz";
$text['label-mono']['pt-br'] = "Coisa"; //copied from pt-pt
$text['label-mono']['pt-pt'] = "Coisa";
$text['label-mono']['ro-ro'] = "";
$text['label-mono']['ru-ru'] = "Моно";
$text['label-mono']['sv-se'] = "sak";
$text['label-mono']['uk-ua'] = "річ";

$text['label-music_on_hold']['en-us'] = "Music on Hold";
$text['label-music_on_hold']['en-gb'] = "Music on Hold";
$text['label-music_on_hold']['ar-eg'] = "";
$text['label-music_on_hold']['de-at'] = "Wartemusik"; //copied from de-de
$text['label-music_on_hold']['de-ch'] = "Wartemusik"; //copied from de-de
$text['label-music_on_hold']['de-de'] = "Wartemusik";
$text['label-music_on_hold']['es-cl'] = "Musica en Espera";
$text['label-music_on_hold']['es-mx'] = "Musica en Espera"; //copied from es-cl
$text['label-music_on_hold']['fr-ca'] = "Musique d'attente"; //copied from fr-fr
$text['label-music_on_hold']['fr-fr'] = "Musique d'attente";
$text['label-music_on_hold']['he-il'] = "מוסיקה בהמתנה";
$text['label-music_on_hold']['it-it'] = "Musica di Attesa";
$text['label-music_on_hold']['nl-nl'] = "Wachtmuziek";
$text['label-music_on_hold']['pl-pl'] = "Muzyka na czekanie";
$text['label-music_on_hold']['pt-br'] = "Música de espera";
$text['label-music_on_hold']['pt-pt'] = "Música em Espera";
$text['label-music_on_hold']['ro-ro'] = "";
$text['label-music_on_hold']['ru-ru'] = "Музыка на удержании";
$text['label-music_on_hold']['sv-se'] = "Väntmusik";
$text['label-music_on_hold']['uk-ua'] = "Музика на утриманні";

$text['label-location']['en-us'] = "Location";
$text['label-location']['en-gb'] = "Location";
$text['label-location']['ar-eg'] = "";
$text['label-location']['de-at'] = "Standort"; //copied from de-de
$text['label-location']['de-ch'] = "Standort"; //copied from de-de
$text['label-location']['de-de'] = "Standort";
$text['label-location']['es-cl'] = "Ubicación";
$text['label-location']['es-mx'] = "Ubicación"; //copied from es-cl
$text['label-location']['fr-ca'] = "Emplacement"; //copied from fr-fr
$text['label-location']['fr-fr'] = "Emplacement";
$text['label-location']['he-il'] = "מיקום";
$text['label-location']['it-it'] = "Luogo";
$text['label-location']['nl-nl'] = "Plaats";
$text['label-location']['pl-pl'] = "Lokalizacja";
$text['label-location']['pt-br'] = "Localização"; //copied from pt-pt
$text['label-location']['pt-pt'] = "Localização";
$text['label-location']['ro-ro'] = "";
$text['label-location']['ru-ru'] = "Место нахождения";
$text['label-location']['sv-se'] = "Plats";
$text['label-location']['uk-ua'] = "Розміщення";

$text['label-interval']['en-us'] = "Interval";
$text['label-interval']['en-gb'] = "Interval";
$text['label-interval']['ar-eg'] = "";
$text['label-interval']['de-at'] = "Intervall"; //copied from de-de
$text['label-interval']['de-ch'] = "Intervall"; //copied from de-de
$text['label-interval']['de-de'] = "Intervall";
$text['label-interval']['es-cl'] = "Intervalo";
$text['label-interval']['es-mx'] = "Intervalo"; //copied from es-cl
$text['label-interval']['fr-ca'] = "Intervalle"; //copied from fr-fr
$text['label-interval']['fr-fr'] = "Intervalle";
$text['label-interval']['he-il'] = "";
$text['label-interval']['it-it'] = "Intervallo";
$text['label-interval']['nl-nl'] = "Interval";
$text['label-interval']['pl-pl'] = "Interwał";
$text['label-interval']['pt-br'] = "Intervalo"; //copied from pt-pt
$text['label-interval']['pt-pt'] = "Intervalo";
$text['label-interval']['ro-ro'] = "";
$text['label-interval']['ru-ru'] = "Интервал";
$text['label-interval']['sv-se'] = "Intervall";
$text['label-interval']['uk-ua'] = "Інтервал";

$text['label-timer_name']['en-us'] = "Timer Name";
$text['label-timer_name']['en-gb'] = "Timer Name";
$text['label-timer_name']['ar-eg'] = "";
$text['label-timer_name']['de-at'] = "Timer Name"; //copied from de-de
$text['label-timer_name']['de-ch'] = "Timer Name"; //copied from de-de
$text['label-timer_name']['de-de'] = "Timer Name";
$text['label-timer_name']['es-cl'] = "";
$text['label-timer_name']['es-mx'] = "";
$text['label-timer_name']['fr-ca'] = "Nom de la minuterie";
$text['label-timer_name']['fr-fr'] = "Nom de la minuterie";
$text['label-timer_name']['he-il'] = "";
$text['label-timer_name']['it-it'] = "Nome timer";
$text['label-timer_name']['nl-nl'] = "Klok naam";
$text['label-timer_name']['pl-pl'] = "";
$text['label-timer_name']['pt-br'] = "";
$text['label-timer_name']['pt-pt'] = "";
$text['label-timer_name']['ro-ro'] = "";
$text['label-timer_name']['ru-ru'] = "Имя Таймера";
$text['label-timer_name']['sv-se'] = "Timer Namn";
$text['label-timer_name']['uk-ua'] = "";

$text['label-global']['en-us'] = "Global";
$text['label-global']['en-gb'] = "Global";
$text['label-global']['ar-eg'] = "";
$text['label-global']['de-at'] = "Global"; //copied from de-de
$text['label-global']['de-ch'] = "Global"; //copied from de-de
$text['label-global']['de-de'] = "Global";
$text['label-global']['es-cl'] = "Global";
$text['label-global']['es-mx'] = "Global"; //copied from es-cl
$text['label-global']['fr-ca'] = "Mondial"; //copied from fr-fr
$text['label-global']['fr-fr'] = "Mondial";
$text['label-global']['he-il'] = "כללי";
$text['label-global']['it-it'] = "Globale";
$text['label-global']['nl-nl'] = "Globaal";
$text['label-global']['pl-pl'] = "Globalny";
$text['label-global']['pt-br'] = "Global"; //copied from pt-pt
$text['label-global']['pt-pt'] = "Global";
$text['label-global']['ro-ro'] = "";
$text['label-global']['ru-ru'] = "Глобальный";
$text['label-global']['sv-se'] = "Global";
$text['label-global']['uk-ua'] = "Глобальний";

$text['label-file_name']['en-us'] = "File Name";
$text['label-file_name']['en-gb'] = "File Name";
$text['label-file_name']['ar-eg'] = "";
$text['label-file_name']['de-at'] = "Dateiname"; //copied from de-de
$text['label-file_name']['de-ch'] = "Dateiname"; //copied from de-de
$text['label-file_name']['de-de'] = "Dateiname";
$text['label-file_name']['es-cl'] = "Nombre del Archivo";
$text['label-file_name']['es-mx'] = "Nombre del Archivo"; //copied from es-cl
$text['label-file_name']['fr-ca'] = "Nom du fichier"; //copied from fr-fr
$text['label-file_name']['fr-fr'] = "Nom du fichier";
$text['label-file_name']['he-il'] = "שם קובץ";
$text['label-file_name']['it-it'] = "Nome File";
$text['label-file_name']['nl-nl'] = "Bestandsnaam";
$text['label-file_name']['pl-pl'] = "Nazwa pliku";
$text['label-file_name']['pt-br'] = "Nome do arquivo";
$text['label-file_name']['pt-pt'] = "Nome do Arquivo";
$text['label-file_name']['ro-ro'] = "";
$text['label-file_name']['ru-ru'] = "Имя Файла";
$text['label-file_name']['sv-se'] = "Fil-namn";
$text['label-file_name']['uk-ua'] = "Назва файлу";

$text['label-file-size']['en-us'] = "File Size";
$text['label-file-size']['en-gb'] = "File Size";
$text['label-file-size']['ar-eg'] = "";
$text['label-file-size']['de-at'] = "Dateigröße"; //copied from de-de
$text['label-file-size']['de-ch'] = "Dateigröße"; //copied from de-de
$text['label-file-size']['de-de'] = "Dateigröße";
$text['label-file-size']['es-cl'] = "Tamaño del archivo";
$text['label-file-size']['es-mx'] = "Tamaño del archivo"; //copied from es-cl
$text['label-file-size']['fr-ca'] = "Taille du fichier"; //copied from fr-fr
$text['label-file-size']['fr-fr'] = "Taille du fichier";
$text['label-file-size']['he-il'] = "גודל קובץ";
$text['label-file-size']['it-it'] = "Dimens. file";
$text['label-file-size']['nl-nl'] = "Bestandsomvang";
$text['label-file-size']['pl-pl'] = "Rozmiar pliku";
$text['label-file-size']['pt-br'] = "Tamanho do arquivo";
$text['label-file-size']['pt-pt'] = "Tamanho do Ficheiro";
$text['label-file-size']['ro-ro'] = "";
$text['label-file-size']['ru-ru'] = "Размер Файла";
$text['label-file-size']['sv-se'] = "Filstorlek";
$text['label-file-size']['uk-ua'] = "Розмір файлу";

$text['label-file-path']['en-us'] = "File Path";
$text['label-file-path']['en-gb'] = "File Path";
$text['label-file-path']['ar-eg'] = "";
$text['label-file-path']['de-at'] = "Dateipfad"; //copied from de-de
$text['label-file-path']['de-ch'] = "Dateipfad"; //copied from de-de
$text['label-file-path']['de-de'] = "Dateipfad";
$text['label-file-path']['es-cl'] = "Ruta al archivo";
$text['label-file-path']['es-mx'] = "Ruta al archivo"; //copied from es-cl
$text['label-file-path']['fr-ca'] = "Chemin du Fichier"; //copied from fr-fr
$text['label-file-path']['fr-fr'] = "Chemin du Fichier";
$text['label-file-path']['he-il'] = "נתיב קובץ";
$text['label-file-path']['it-it'] = "Percorso File";
$text['label-file-path']['nl-nl'] = "Bestandspad";
$text['label-file-path']['pl-pl'] = "Ścieżka do pliku";
$text['label-file-path']['pt-br'] = "Caminho do arquivo";
$text['label-file-path']['pt-pt'] = "Caminho do Ficheiro";
$text['label-file-path']['ro-ro'] = "";
$text['label-file-path']['ru-ru'] = "Путь к Файлу";
$text['label-file-path']['sv-se'] = "Sökväg till fil";
$text['label-file-path']['uk-ua'] = "Шлях";

$text['label-download']['en-us'] = "Download";
$text['label-download']['en-gb'] = "Download";
$text['label-download']['ar-eg'] = "";
$text['label-download']['de-at'] = "Herunterladen"; //copied from de-de
$text['label-download']['de-ch'] = "Herunterladen"; //copied from de-de
$text['label-download']['de-de'] = "Herunterladen";
$text['label-download']['es-cl'] = "Descargar";
$text['label-download']['es-mx'] = "Descargar"; //copied from es-cl
$text['label-download']['fr-ca'] = "Télécharger"; //copied from fr-fr
$text['label-download']['fr-fr'] = "Télécharger";
$text['label-download']['he-il'] = "הורדה";
$text['label-download']['it-it'] = "Scarica";
$text['label-download']['nl-nl'] = "Ophalen";
$text['label-download']['pl-pl'] = "Pobierz";
$text['label-download']['pt-br'] = "Download";
$text['label-download']['pt-pt'] = "Descarregar";
$text['label-download']['ro-ro'] = "";
$text['label-download']['ru-ru'] = "Загрузить";
$text['label-download']['sv-se'] = "Ladda Ned";
$text['label-download']['uk-ua'] = "Скачати";

$text['label-domain']['en-us'] = "Domain";
$text['label-domain']['en-gb'] = "Domain";
$text['label-domain']['ar-eg'] = "النطاق";
$text['label-domain']['de-at'] = "Domäne"; //copied from de-de
$text['label-domain']['de-ch'] = "Domäne"; //copied from de-de
$text['label-domain']['de-de'] = "Domäne";
$text['label-domain']['es-cl'] = "Dominio";
$text['label-domain']['es-mx'] = "Dominio"; //copied from es-cl
$text['label-domain']['fr-ca'] = "Domaine"; //copied from fr-fr
$text['label-domain']['fr-fr'] = "Domaine";
$text['label-domain']['he-il'] = "דומיין";
$text['label-domain']['it-it'] = "Dominio";
$text['label-domain']['nl-nl'] = "Domein";
$text['label-domain']['pl-pl'] = "Domena";
$text['label-domain']['pt-br'] = "Dominio";
$text['label-domain']['pt-pt'] = "Domínio";
$text['label-domain']['ro-ro'] = "Domeniu";
$text['label-domain']['ru-ru'] = "Домен";
$text['label-domain']['sv-se'] = "Domän";
$text['label-domain']['uk-ua'] = "Домен";

$text['label-delete-category']['en-us'] = "Delete Category";
$text['label-delete-category']['en-gb'] = "Delete Category";
$text['label-delete-category']['ar-eg'] = "";
$text['label-delete-category']['de-at'] = "Kategorie löschen"; //copied from de-de
$text['label-delete-category']['de-ch'] = "Kategorie löschen"; //copied from de-de
$text['label-delete-category']['de-de'] = "Kategorie löschen";
$text['label-delete-category']['es-cl'] = "Eliminar categoría";
$text['label-delete-category']['es-mx'] = "Eliminar categoría"; //copied from es-cl
$text['label-delete-category']['fr-ca'] = "Supprimer la Catégorie"; //copied from fr-fr
$text['label-delete-category']['fr-fr'] = "Supprimer la Catégorie";
$text['label-delete-category']['he-il'] = "מחק קטגוריה";
$text['label-delete-category']['it-it'] = "Cancellare Categoria";
$text['label-delete-category']['nl-nl'] = "Categorie verwijderen";
$text['label-delete-category']['pl-pl'] = "Usuń kategorię";
$text['label-delete-category']['pt-br'] = "Remover categoria";
$text['label-delete-category']['pt-pt'] = "Remover Categoria";
$text['label-delete-category']['ro-ro'] = "";
$text['label-delete-category']['ru-ru'] = "Удалить категорию";
$text['label-delete-category']['sv-se'] = "Ta Bort Kategori";
$text['label-delete-category']['uk-ua'] = "Видалити категорію";

$text['label-default']['en-us'] = "Default";
$text['label-default']['en-gb'] = "Default";
$text['label-default']['ar-eg'] = "";
$text['label-default']['de-at'] = "Standard"; //copied from de-de
$text['label-default']['de-ch'] = "Standard"; //copied from de-de
$text['label-default']['de-de'] = "Standard";
$text['label-default']['es-cl'] = "Predeterminado";
$text['label-default']['es-mx'] = "Predeterminado"; //copied from es-cl
$text['label-default']['fr-ca'] = "Par défaut"; //copied from fr-fr
$text['label-default']['fr-fr'] = "Par défaut";
$text['label-default']['he-il'] = "ברירת מחדל";
$text['label-default']['it-it'] = "Default";
$text['label-default']['nl-nl'] = "Standaard";
$text['label-default']['pl-pl'] = "Pliki ze standardowymi melodiami";
$text['label-default']['pt-br'] = "Predefinido"; //copied from pt-pt
$text['label-default']['pt-pt'] = "Predefinido";
$text['label-default']['ro-ro'] = "";
$text['label-default']['ru-ru'] = "По умолчанию";
$text['label-default']['sv-se'] = "Standard";
$text['label-default']['uk-ua'] = "Типово";

$text['label-chime_maximum']['en-us'] = "Chime Maximum";
$text['label-chime_maximum']['en-gb'] = "Chime Maximum";
$text['label-chime_maximum']['ar-eg'] = "الحد الأقصى الدقات";
$text['label-chime_maximum']['de-at'] = "Maximale Chimes"; //copied from de-de
$text['label-chime_maximum']['de-ch'] = "Maximale Chimes"; //copied from de-de
$text['label-chime_maximum']['de-de'] = "Maximale Chimes";
$text['label-chime_maximum']['es-cl'] = "máximos Chimes";
$text['label-chime_maximum']['es-mx'] = "máximos Chimes"; //copied from es-cl
$text['label-chime_maximum']['fr-ca'] = "Chimes maximum"; //copied from fr-fr
$text['label-chime_maximum']['fr-fr'] = "Chimes maximum";
$text['label-chime_maximum']['he-il'] = "פעמונים מקסימאליים";
$text['label-chime_maximum']['it-it'] = "Massimo Suono";
$text['label-chime_maximum']['nl-nl'] = "Maximum geluid";
$text['label-chime_maximum']['pl-pl'] = "Maksymalnie kuranty";
$text['label-chime_maximum']['pt-br'] = "Chimes máximos"; //copied from pt-pt
$text['label-chime_maximum']['pt-pt'] = "Chimes máximos";
$text['label-chime_maximum']['ro-ro'] = "maxime Chimes";
$text['label-chime_maximum']['ru-ru'] = "Максимальный перезвон";
$text['label-chime_maximum']['sv-se'] = "maximala Chimes";
$text['label-chime_maximum']['uk-ua'] = "максимум куранти";

$text['label-chime_list']['en-us'] = "Chime File";
$text['label-chime_list']['en-gb'] = "Chime File";
$text['label-chime_list']['ar-eg'] = "الملف تتناغم";
$text['label-chime_list']['de-at'] = "Chime Datei"; //copied from de-de
$text['label-chime_list']['de-ch'] = "Chime Datei"; //copied from de-de
$text['label-chime_list']['de-de'] = "Chime Datei";
$text['label-chime_list']['es-cl'] = "archivo carillón";
$text['label-chime_list']['es-mx'] = "archivo carillón"; //copied from es-cl
$text['label-chime_list']['fr-ca'] = "fichier Chime"; //copied from fr-fr
$text['label-chime_list']['fr-fr'] = "fichier Chime";
$text['label-chime_list']['he-il'] = "קובץ Chime";
$text['label-chime_list']['it-it'] = "File Suono";
$text['label-chime_list']['nl-nl'] = "Geluidsbestand";
$text['label-chime_list']['pl-pl'] = "Chime pliku";
$text['label-chime_list']['pt-br'] = "Arquivo Chime"; //copied from pt-pt
$text['label-chime_list']['pt-pt'] = "Arquivo Chime";
$text['label-chime_list']['ro-ro'] = "Fișier chime";
$text['label-chime_list']['ru-ru'] = "Файл перезвона";
$text['label-chime_list']['sv-se'] = "chime File";
$text['label-chime_list']['uk-ua'] = "передзвін файлу";

$text['label-chime_frequency']['en-us'] = "Chime Frequency";
$text['label-chime_frequency']['en-gb'] = "Chime Frequency";
$text['label-chime_frequency']['ar-eg'] = "تردد الرنين";
$text['label-chime_frequency']['de-at'] = "Chime Frequenz"; //copied from de-de
$text['label-chime_frequency']['de-ch'] = "Chime Frequenz"; //copied from de-de
$text['label-chime_frequency']['de-de'] = "Chime Frequenz";
$text['label-chime_frequency']['es-cl'] = "Frecuencia carillón";
$text['label-chime_frequency']['es-mx'] = "Frecuencia carillón"; //copied from es-cl
$text['label-chime_frequency']['fr-ca'] = "Fréquence Chime"; //copied from fr-fr
$text['label-chime_frequency']['fr-fr'] = "Fréquence Chime";
$text['label-chime_frequency']['he-il'] = "תדירות Chime";
$text['label-chime_frequency']['it-it'] = "Frequenza Suono";
$text['label-chime_frequency']['nl-nl'] = "Geluids frequentie";
$text['label-chime_frequency']['pl-pl'] = "Częstotliwość Chime";
$text['label-chime_frequency']['pt-br'] = "Frequência Chime"; //copied from pt-pt
$text['label-chime_frequency']['pt-pt'] = "Frequência Chime";
$text['label-chime_frequency']['ro-ro'] = "Frecventa chime";
$text['label-chime_frequency']['ru-ru'] = "Частота перезвона";
$text['label-chime_frequency']['sv-se'] = "chime Frekvens";
$text['label-chime_frequency']['uk-ua'] = "передзвін Частота";

$text['label-channels']['en-us'] = "Channels";
$text['label-channels']['en-gb'] = "Channels";
$text['label-channels']['ar-eg'] = "قنوات";
$text['label-channels']['de-at'] = "Kanäle"; //copied from de-de
$text['label-channels']['de-ch'] = "Kanäle"; //copied from de-de
$text['label-channels']['de-de'] = "Kanäle";
$text['label-channels']['es-cl'] = "Canales";
$text['label-channels']['es-mx'] = "Canales"; //copied from es-cl
$text['label-channels']['fr-ca'] = "Canaux"; //copied from fr-fr
$text['label-channels']['fr-fr'] = "Canaux";
$text['label-channels']['he-il'] = "ערוצים";
$text['label-channels']['it-it'] = "Canali";
$text['label-channels']['nl-nl'] = "Kanalen";
$text['label-channels']['pl-pl'] = "Kanały";
$text['label-channels']['pt-br'] = "Canais"; //copied from pt-pt
$text['label-channels']['pt-pt'] = "Canais";
$text['label-channels']['ro-ro'] = "Canale";
$text['label-channels']['ru-ru'] = "Каналы";
$text['label-channels']['sv-se'] = "Kanaler";
$text['label-channels']['uk-ua'] = "Канали";

$text['header-music_on_hold_settings']['en-us'] = "Music on Hold Settings";
$text['header-music_on_hold_settings']['en-gb'] = "Music on Hold Settings";
$text['header-music_on_hold_settings']['ar-eg'] = "";
$text['header-music_on_hold_settings']['de-at'] = "Wartemusik Einstellungen"; //copied from de-de
$text['header-music_on_hold_settings']['de-ch'] = "Wartemusik Einstellungen"; //copied from de-de
$text['header-music_on_hold_settings']['de-de'] = "Wartemusik Einstellungen";
$text['header-music_on_hold_settings']['es-cl'] = "Musica en Espera ajustes";
$text['header-music_on_hold_settings']['es-mx'] = "Musica en Espera ajustes"; //copied from es-cl
$text['header-music_on_hold_settings']['fr-ca'] = "Musique d'attente paramètres"; //copied from fr-fr
$text['header-music_on_hold_settings']['fr-fr'] = "Musique d'attente paramètres";
$text['header-music_on_hold_settings']['he-il'] = "מוסיקה על גדרות מתן";
$text['header-music_on_hold_settings']['it-it'] = "Parametri Musica di Attesa";
$text['header-music_on_hold_settings']['nl-nl'] = "Wachtmuziek instellingen";
$text['header-music_on_hold_settings']['pl-pl'] = "Muzyka na czekanie ustawienia";
$text['header-music_on_hold_settings']['pt-br'] = "Música de espera configurações";
$text['header-music_on_hold_settings']['pt-pt'] = "Música em Espera configurações";
$text['header-music_on_hold_settings']['ro-ro'] = "";
$text['header-music_on_hold_settings']['ru-ru'] = "Музыка на удержании параметы";
$text['header-music_on_hold_settings']['sv-se'] = "Väntmusik inställningar";
$text['header-music_on_hold_settings']['uk-ua'] = "Музика на утриманні настройки";

$text['title_description-music_on_hold']['en-us'] = "Music on hold can be in WAV or MP3 format. For best performance upload 16 bit, 8/16/32/48 kHz <i>mono</i> WAV files.";
$text['title_description-music_on_hold']['en-gb'] = "Music on hold can be in WAV or MP3 format. For best performance upload 16 bit, 8/16/32/48 kHz <i>mono</i> WAV files.";
$text['title_description-music_on_hold']['ar-eg'] = "";
$text['title_description-music_on_hold']['de-at'] = "Haltemusik können Dateien im WAV oder MP3 Format sein. Für beste Funktionalität laden Sie 16bit, 8/16/32/48 kHz mono WAV Dateien hoch."; //copied from de-de
$text['title_description-music_on_hold']['de-ch'] = "Haltemusik können Dateien im WAV oder MP3 Format sein. Für beste Funktionalität laden Sie 16bit, 8/16/32/48 kHz mono WAV Dateien hoch."; //copied from de-de
$text['title_description-music_on_hold']['de-de'] = "Haltemusik können Dateien im WAV oder MP3 Format sein. Für beste Funktionalität laden Sie 16bit, 8/16/32/48 kHz mono WAV Dateien hoch.";
$text['title_description-music_on_hold']['es-cl'] = "La música en espera puede estar en formato WAV o MP3. Para el mejor rendimiento se recomienda utilizar archivos en formato WAV 16 bit, 8/16/32/48 kHz <i>mono</i>.";
$text['title_description-music_on_hold']['es-mx'] = "La música en espera puede estar en formato WAV o MP3. Para el mejor rendimiento se recomienda utilizar archivos en formato WAV 16 bit, 8/16/32/48 kHz <i>mono</i>."; //copied from es-cl
$text['title_description-music_on_hold']['fr-ca'] = "La Musique d'attente peut être en WAV ou en MP3. Le volume peut être réglé dans la partie configuration. Pour de meilleures performances, utiliser des fichiers WAV 16 bit, 8/16/32/48 kHz <i>mono</i>."; //copied from fr-fr
$text['title_description-music_on_hold']['fr-fr'] = "La Musique d'attente peut être en WAV ou en MP3. Pour de meilleures performances, utiliser des fichiers WAV 16 bit, 8/16/32/48 kHz <i>mono</i>.";
$text['title_description-music_on_hold']['he-il'] = "";
$text['title_description-music_on_hold']['it-it'] = "La musica di attesa può essere in formato WAV o MP3. Per una migliore qualità caricare file 16 bit, 8/16/32/48 kHz <i>mono</i> WAV files.";
$text['title_description-music_on_hold']['nl-nl'] = "Wachtmuziek mag in WAV of MP3 formaat zijn. Voor de beste prestaties gebruik 16 bit, 8/16/32/48 kHz <i>mono</i> WAV files.";
$text['title_description-music_on_hold']['pl-pl'] = "Muzyka na czekanie może być w formacie wav lub mp3. W celu osiągniecia najlepszej jakości prześlij pliki w formacie wav o następującej specyfikacji: 16 bit, 8/16/32/48 kHz mono.";
$text['title_description-music_on_hold']['pt-br'] = "Música em espera pode ser com base em arquivos com o formato WAV ou MP3. Pode ajustar o volume do áudio MP3 a partir da tab 'Definições'. Para um melhor desempenho carregue ficheiros WAV de 16 bit, 8/16/32/48 kHz mono.";
$text['title_description-music_on_hold']['pt-pt'] = "Música em espera pode ser com base em ficheiros com o formato WAV ou MP3. Para um melhor desempenho carregue ficheiros WAV de 16 bit, 8/16/32/48 kHz <i>mono</i>.";
$text['title_description-music_on_hold']['ro-ro'] = "";
$text['title_description-music_on_hold']['ru-ru'] = "Музыка на удержании может быть в формате WAV или MP3. Для лучшей производительности загружайте 16-битные, 8/16/32/48 кГц <i> моно </ i> файлы WAV.";
$text['title_description-music_on_hold']['sv-se'] = "Väntmusik kan vara i formaten WAV eller MP3. För bästa prestanda, ladda upp 16 bit, 8/16/32/48 kHz mono WAV filer.";
$text['title_description-music_on_hold']['uk-ua'] = "Музика на утриманні може бути в WAV або MP3 формат. Для кращої продуктивності завантаження 16 біт, моно 8/16/32/48 кГц WAV файлів.";

$text['button-upload']['en-us'] = "Upload";
$text['button-upload']['en-gb'] = "Upload";
$text['button-upload']['ar-eg'] = "";
$text['button-upload']['de-at'] = "Hochladen"; //copied from de-de
$text['button-upload']['de-ch'] = "Hochladen"; //copied from de-de
$text['button-upload']['de-de'] = "Hochladen";
$text['button-upload']['es-cl'] = "Subir";
$text['button-upload']['es-mx'] = "Subir"; //copied from es-cl
$text['button-upload']['fr-ca'] = "Télécharger"; //copied from fr-fr
$text['button-upload']['fr-fr'] = "Télécharger";
$text['button-upload']['he-il'] = "הטען";
$text['button-upload']['it-it'] = "Carica";
$text['button-upload']['nl-nl'] = "Opsturen";
$text['button-upload']['pl-pl'] = "Wyślij";
$text['button-upload']['pt-br'] = "Submeter";
$text['button-upload']['pt-pt'] = "Carregar";
$text['button-upload']['ro-ro'] = "";
$text['button-upload']['ru-ru'] = "Загрузить";
$text['button-upload']['sv-se'] = "Ladda Upp";
$text['button-upload']['uk-ua'] = "Завантажити";

$text['button-clear']['en-us'] = "Clear";
$text['button-clear']['en-gb'] = "Clear";
$text['button-clear']['ar-eg'] = "";
$text['button-clear']['de-at'] = "Zurücksetzen"; //copied from de-de
$text['button-clear']['de-ch'] = "Zurücksetzen"; //copied from de-de
$text['button-clear']['de-de'] = "Zurücksetzen";
$text['button-clear']['es-cl'] = "Limpiar";
$text['button-clear']['es-mx'] = "Limpiar"; //copied from es-cl
$text['button-clear']['fr-ca'] = "Effacer"; //copied from fr-fr
$text['button-clear']['fr-fr'] = "Effacer";
$text['button-clear']['he-il'] = "נקה";
$text['button-clear']['it-it'] = "Resetta";
$text['button-clear']['nl-nl'] = "Schoonmaken";
$text['button-clear']['pl-pl'] = "Wyczyść";
$text['button-clear']['pt-br'] = "Apagar"; //copied from pt-pt
$text['button-clear']['pt-pt'] = "Apagar";
$text['button-clear']['ro-ro'] = "";
$text['button-clear']['ru-ru'] = "Очистить";
$text['button-clear']['sv-se'] = "Rensa";
$text['button-clear']['uk-ua'] = "Очистити";

?>
