<?php
#This file was last reorganized on 19th of September 2017 08:54:24 AM UTC

$text['title-apps']['en-us'] = "App Manager";
$text['title-apps']['en-gb'] = "App Manager";
$text['title-apps']['ar-eg'] = "";
$text['title-apps']['de-at'] = "Applikation Verwaltung"; //copied from de-de
$text['title-apps']['de-ch'] = "Applikation Verwaltung"; //copied from de-de
$text['title-apps']['de-de'] = "Applikation Verwaltung";
$text['title-apps']['es-cl'] = "Administrador de Aplicaciones";
$text['title-apps']['es-mx'] = "Administrador de Aplicaciones"; //copied from es-cl
$text['title-apps']['fr-ca'] = "Gestionnaire App"; //copied from fr-fr
$text['title-apps']['fr-fr'] = "Gestionnaire App";
$text['title-apps']['he-il'] = "";
$text['title-apps']['it-it'] = "Gestore App";
$text['title-apps']['nl-nl'] = "";
$text['title-apps']['pl-pl'] = "Menedżer aplikacji";
$text['title-apps']['pt-br'] = "Gerenciador de aplicações";
$text['title-apps']['pt-pt'] = "Gestor de Aplicações";
$text['title-apps']['ro-ro'] = "";
$text['title-apps']['ru-ru'] = "Управление приложениями";
$text['title-apps']['sv-se'] = "App Inställningar";
$text['title-apps']['uk-ua'] = "Керування додатками";
$text['title-apps']['tr-tr'] = "Uygulama Yöneticisi";


$text['title-app-edit']['en-us'] = "App Edit";
$text['title-app-edit']['en-gb'] = "App Edit";
$text['title-app-edit']['ar-eg'] = "";
$text['title-app-edit']['de-at'] = "Applikationen Editieren"; //copied from de-de
$text['title-app-edit']['de-ch'] = "Applikationen Editieren"; //copied from de-de
$text['title-app-edit']['de-de'] = "Applikationen Editieren";
$text['title-app-edit']['es-cl'] = "Editar Aplicaciones";
$text['title-app-edit']['es-mx'] = "Editar Aplicaciones"; //copied from es-cl
$text['title-app-edit']['fr-ca'] = "Editer l'application"; //copied from fr-fr
$text['title-app-edit']['fr-fr'] = "Editer l'application";
$text['title-app-edit']['he-il'] = "";
$text['title-app-edit']['it-it'] = "Modifica App";
$text['title-app-edit']['nl-nl'] = "";
$text['title-app-edit']['pl-pl'] = "Edytuj aplikację ";
$text['title-app-edit']['pt-br'] = "Editar aplicação"; //copied from pt-pt
$text['title-app-edit']['pt-pt'] = "Editar aplicação";
$text['title-app-edit']['ro-ro'] = "";
$text['title-app-edit']['ru-ru'] = "Изменеие приложения";
$text['title-app-edit']['sv-se'] = "Ändra App";
$text['title-app-edit']['uk-ua'] = "Редагувати додаток";
$text['title-app-edit']['tr-tr'] = "Uygulama Düzenle";

$text['label-version']['en-us'] = "Version";
$text['label-version']['en-gb'] = "Version";
$text['label-version']['ar-eg'] = "";
$text['label-version']['de-at'] = "Version"; //copied from de-de
$text['label-version']['de-ch'] = "Version"; //copied from de-de
$text['label-version']['de-de'] = "Version";
$text['label-version']['es-cl'] = "Versión";
$text['label-version']['es-mx'] = "Versión"; //copied from es-cl
$text['label-version']['fr-ca'] = "Version"; //copied from fr-fr
$text['label-version']['fr-fr'] = "Version";
$text['label-version']['he-il'] = "";
$text['label-version']['it-it'] = "Versione";
$text['label-version']['nl-nl'] = "";
$text['label-version']['pl-pl'] = "Wersja";
$text['label-version']['pt-br'] = "Versão"; //copied from pt-pt
$text['label-version']['pt-pt'] = "Versão";
$text['label-version']['ro-ro'] = "";
$text['label-version']['ru-ru'] = "Версия";
$text['label-version']['sv-se'] = "Version";
$text['label-version']['uk-ua'] = "Версія";
$text['label-version']['tr-tr'] = "Sürüm";

$text['header-apps']['en-us'] = "App Manager";
$text['header-apps']['en-gb'] = "App Manager";
$text['header-apps']['ar-eg'] = "";
$text['header-apps']['de-at'] = "Applikation verwalten"; //copied from de-de
$text['header-apps']['de-ch'] = "Applikation verwalten"; //copied from de-de
$text['header-apps']['de-de'] = "Applikation verwalten";
$text['header-apps']['es-cl'] = "Administrador de Aplicaciones";
$text['header-apps']['es-mx'] = "Administrador de Aplicaciones"; //copied from es-cl
$text['header-apps']['fr-ca'] = "Gestionnaire App"; //copied from fr-fr
$text['header-apps']['fr-fr'] = "Gestionnaire App";
$text['header-apps']['he-il'] = "";
$text['header-apps']['it-it'] = "Gestore App";
$text['header-apps']['nl-nl'] = "";
$text['header-apps']['pl-pl'] = "Menedżer aplikacji";
$text['header-apps']['pt-br'] = "Gerenciador de aplicações";
$text['header-apps']['pt-pt'] = "Gestor de Aplicações";
$text['header-apps']['ro-ro'] = "";
$text['header-apps']['ru-ru'] = "Управление приложениями";
$text['header-apps']['sv-se'] = "App Inställningar";
$text['header-apps']['uk-ua'] = "Керування додатками";
$text['header-apps']['tr-tr'] = "Uygulama Yöneticisi";

$text['header-app-edit']['en-us'] = "App Edit";
$text['header-app-edit']['en-gb'] = "App Edit";
$text['header-app-edit']['ar-eg'] = "";
$text['header-app-edit']['de-at'] = "Applikation bearbeiten"; //copied from de-de
$text['header-app-edit']['de-ch'] = "Applikation bearbeiten"; //copied from de-de
$text['header-app-edit']['de-de'] = "Applikation bearbeiten";
$text['header-app-edit']['es-cl'] = "Editar Aplicaciones";
$text['header-app-edit']['es-mx'] = "Editar Aplicaciones"; //copied from es-cl
$text['header-app-edit']['fr-ca'] = "Editer l'application"; //copied from fr-fr
$text['header-app-edit']['fr-fr'] = "Editer l'application";
$text['header-app-edit']['he-il'] = "";
$text['header-app-edit']['it-it'] = "Modifica App";
$text['header-app-edit']['nl-nl'] = "";
$text['header-app-edit']['pl-pl'] = "Edytuj aplikację ";
$text['header-app-edit']['pt-br'] = "Editar aplicação"; //copied from pt-pt
$text['header-app-edit']['pt-pt'] = "Editar aplicação";
$text['header-app-edit']['ro-ro'] = "";
$text['header-app-edit']['ru-ru'] = "Изменеие приложения";
$text['header-app-edit']['sv-se'] = "Ändra App";
$text['header-app-edit']['uk-ua'] = "Редагувати додаток";
$text['header-app-edit']['tr-tr'] = "Uygulama Düzenle";

$text['description-apps']['en-us'] = "Manage the applications that are installed.";
$text['description-apps']['en-gb'] = "Manage the applications that are installed.";
$text['description-apps']['ar-eg'] = "";
$text['description-apps']['de-at'] = "Installierte Applikationen verwalten"; //copied from de-de
$text['description-apps']['de-ch'] = "Installierte Applikationen verwalten"; //copied from de-de
$text['description-apps']['de-de'] = "Installierte Applikationen verwalten";
$text['description-apps']['es-cl'] = "Administre las aplicaciones instaladas.";
$text['description-apps']['es-mx'] = "Administre las aplicaciones instaladas."; //copied from es-cl
$text['description-apps']['fr-ca'] = "Gérer les applications installées."; //copied from fr-fr
$text['description-apps']['fr-fr'] = "Gérer les applications installées.";
$text['description-apps']['he-il'] = "";
$text['description-apps']['it-it'] = "Gestisce le applicazioni installate.";
$text['description-apps']['nl-nl'] = "";
$text['description-apps']['pl-pl'] = "Zarządzajnie zainstalowanymi aplikacjami.";
$text['description-apps']['pt-br'] = "Gerenciar as aplicações instaladas";
$text['description-apps']['pt-pt'] = "Gerir as aplicações instaladas.";
$text['description-apps']['ro-ro'] = "";
$text['description-apps']['ru-ru'] = "Управление установленными приложениями.";
$text['description-apps']['sv-se'] = "Hantera de applikationer som är installerade.";
$text['description-apps']['uk-ua'] = "Керування встановленими додатками";
$text['description-apps']['tr-tr'] = "Yüklü bulunan uygulamaları düzenleyin.";

$text['description-app-edit']['en-us'] = "Manage the applications that are installed.";
$text['description-app-edit']['en-gb'] = "Manage the applications that are installed.";
$text['description-app-edit']['ar-eg'] = "";
$text['description-app-edit']['de-at'] = "Installierte Applikationen verwalten"; //copied from de-de
$text['description-app-edit']['de-ch'] = "Installierte Applikationen verwalten"; //copied from de-de
$text['description-app-edit']['de-de'] = "Installierte Applikationen verwalten";
$text['description-app-edit']['es-cl'] = "Administre las aplicaciones instaladas.";
$text['description-app-edit']['es-mx'] = "Administre las aplicaciones instaladas."; //copied from es-cl
$text['description-app-edit']['fr-ca'] = "Gérer les applications installées"; //copied from fr-fr
$text['description-app-edit']['fr-fr'] = "Gérer les applications installées";
$text['description-app-edit']['he-il'] = "";
$text['description-app-edit']['it-it'] = "Gestisce le applicazioni installate.";
$text['description-app-edit']['nl-nl'] = "";
$text['description-app-edit']['pl-pl'] = "Zarządzajnie zainstalowanymi aplikacjami.";
$text['description-app-edit']['pt-br'] = "Gerenciar as aplicações instaladas";
$text['description-app-edit']['pt-pt'] = "Gerir as aplicações instaladas.";
$text['description-app-edit']['ro-ro'] = "";
$text['description-app-edit']['ru-ru'] = "Управление установленными приложениями.";
$text['description-app-edit']['sv-se'] = "Hantera de applikationer som är installerade.";
$text['description-app-edit']['uk-ua'] = "Керування встановленими додатками";
$text['description-app-edit']['tr-tr'] = "Yüklü bulunan uygulamaları düzenleyin.";


?>
