<?php
#This file was last reorganized on 12th of June 2017 10:57:41 AM UTC

$text['title-apps']['en-us'] = "App Manager";
$text['title-apps']['ar-eg'] = "";
$text['title-apps']['de-at'] = "Applikation Verwaltung";
$text['title-apps']['de-ch'] = "Applikation Verwaltung"; //copied from de-de
$text['title-apps']['de-de'] = "Applikation Verwaltung";
$text['title-apps']['es-cl'] = "Administrador de Aplicaciones";
$text['title-apps']['es-mx'] = "Administrador de Aplicaciones"; //copied from es-cl
$text['title-apps']['fr-ca'] = "Gestionnaire App"; //copied from fr-fr
$text['title-apps']['fr-fr'] = "Gestionnaire App";
$text['title-apps']['he-il'] = "";
$text['title-apps']['it-it'] = "Gestore applicazioni";
$text['title-apps']['nl-nl'] = "";
$text['title-apps']['pl-pl'] = "Menedżer aplikacji";
$text['title-apps']['pt-br'] = "Gerenciador de aplicações";
$text['title-apps']['pt-pt'] = "Gestor de Aplicações";
$text['title-apps']['ro-ro'] = "";
$text['title-apps']['ru-ru'] = "Управление приложениями";
$text['title-apps']['sv-se'] = "App Inställningar";
$text['title-apps']['uk-ua'] = "Керування додатками";

$text['title-app-edit']['en-us'] = "App Edit";
$text['title-app-edit']['ar-eg'] = "";
$text['title-app-edit']['de-at'] = "Applikationen Editieren";
$text['title-app-edit']['de-ch'] = "Applikationen Editieren"; //copied from de-de
$text['title-app-edit']['de-de'] = "Applikationen Editieren";
$text['title-app-edit']['es-cl'] = "Editar Aplicaciones";
$text['title-app-edit']['es-mx'] = "Editar Aplicaciones"; //copied from es-cl
$text['title-app-edit']['fr-ca'] = "Editer l'application"; //copied from fr-fr
$text['title-app-edit']['fr-fr'] = "Editer l'application";
$text['title-app-edit']['he-il'] = "";
$text['title-app-edit']['it-it'] = "Modifica applicazione";
$text['title-app-edit']['nl-nl'] = "";
$text['title-app-edit']['pl-pl'] = "Edytuj aplikację ";
$text['title-app-edit']['pt-br'] = "Editar aplicação";
$text['title-app-edit']['pt-pt'] = "Editar aplicação";
$text['title-app-edit']['ro-ro'] = "";
$text['title-app-edit']['ru-ru'] = "Изменеие приложения";
$text['title-app-edit']['sv-se'] = "Ändra App";
$text['title-app-edit']['uk-ua'] = "Редагувати додаток";

$text['label-version']['en-us'] = "Version";
$text['label-version']['ar-eg'] = "";
$text['label-version']['de-at'] = "Version";
$text['label-version']['de-ch'] = "Version"; //copied from de-de
$text['label-version']['de-de'] = "Version";
$text['label-version']['es-cl'] = "Versión";
$text['label-version']['es-mx'] = "Versión"; //copied from es-cl
$text['label-version']['fr-ca'] = "Version"; //copied from fr-fr
$text['label-version']['fr-fr'] = "Version";
$text['label-version']['he-il'] = "";
$text['label-version']['it-it'] = "Versione";
$text['label-version']['nl-nl'] = "";
$text['label-version']['pl-pl'] = "Wersja";
$text['label-version']['pt-br'] = "Versão";
$text['label-version']['pt-pt'] = "Versão";
$text['label-version']['ro-ro'] = "";
$text['label-version']['ru-ru'] = "Версия";
$text['label-version']['sv-se'] = "Version";
$text['label-version']['uk-ua'] = "Версія";

$text['label-required_version']['en-us'] = "Required Version";
$text['label-required_version']['ar-eg'] = "النسخة المطلوبة"; //translation provided by Google Translate
$text['label-required_version']['de-at'] = "Erforderliche Version"; //translation provided by Google Translate
$text['label-required_version']['de-ch'] = "Erforderliche Version"; //translation provided by Google Translate
$text['label-required_version']['de-de'] = "Erforderliche Version"; //translation provided by Google Translate
$text['label-required_version']['es-cl'] = "Versión requerida"; //translation provided by Google Translate
$text['label-required_version']['es-mx'] = "Versión requerida";  //translation provided by Google Translate
$text['label-required_version']['fr-ca'] = "Version requise";  //translation provided by Google Translate
$text['label-required_version']['fr-fr'] = "Version requise"; //translation provided by Google Translate
$text['label-required_version']['he-il'] = "גרסה דרושה"; //translation provided by Google Translate
$text['label-required_version']['it-it'] = "Versione richiesta"; //translation provided by Google Translate
$text['label-required_version']['nl-nl'] = "Vereiste versie"; //translation provided by Google Translate
$text['label-required_version']['pl-pl'] = "Wymagana wersja"; //translation provided by Google Translate
$text['label-required_version']['pt-br'] = "Versão requerida"; //translation provided by Google Translate
$text['label-required_version']['pt-pt'] = "Versão requerida"; //translation provided by Google Translate
$text['label-required_version']['ro-ro'] = "Versiunea cerută"; //translation provided by Google Translate
$text['label-required_version']['ru-ru'] = "Требуемая версия"; //translation provided by Google Translate
$text['label-required_version']['sv-se'] = "Nödvändig version"; //translation provided by Google Translate
$text['label-required_version']['uk-ua'] = "необхідна версія"; //translation provided by Google Translate

$text['description-required_version']['en-us'] = "Minimum System version required by application";
$text['description-required_version']['ar-eg'] = "الحد الأدنى إصدار النظام المطلوبة من قبل التطبيق"; //translation provided by Google Translate
$text['description-required_version']['de-at'] = "Mindestsystemversion erforderlich"; //translation provided by Google Translate
$text['description-required_version']['de-ch'] = "Mindestsystemversion erforderlich"; //translation provided by Google Translate
$text['description-required_version']['de-de'] = "Mindestsystemversion erforderlich"; //translation provided by Google Translate
$text['description-required_version']['es-cl'] = "Versión mínima del sistema requerida por la aplicación"; //translation provided by Google Translate
$text['description-required_version']['es-mx'] = "Versión mínima del sistema requerida por la aplicación";  //translation provided by Google Translate
$text['description-required_version']['fr-ca'] = "Version minimum requise par l'application";  //translation provided by Google Translate
$text['description-required_version']['fr-fr'] = "Version minimum requise par l'application"; //translation provided by Google Translate
$text['description-required_version']['he-il'] = "גירסת מערכת מינימלית הנדרשת על-ידי היישום"; //translation provided by Google Translate
$text['description-required_version']['it-it'] = "Versione System minima richiesta dall'applicazione"; //translation provided by Google Translate
$text['description-required_version']['nl-nl'] = "Minimum systeemversie vereist bij toepassing"; //translation provided by Google Translate
$text['description-required_version']['pl-pl'] = "Minimalna wersja systemu wymagana przez aplikację"; //translation provided by Google Translate
$text['description-required_version']['pt-br'] = "Versão mínima do sistema exigida pelo aplicativo"; //translation provided by Google Translate
$text['description-required_version']['pt-pt'] = "Versão mínima do sistema exigida pelo aplicativo"; //translation provided by Google Translate
$text['description-required_version']['ro-ro'] = "Versiunea minimă de sistem cerută de aplicație"; //translation provided by Google Translate
$text['description-required_version']['ru-ru'] = "Минимальная системная версия, требуемая приложением"; //translation provided by Google Translate
$text['description-required_version']['sv-se'] = "Minsta systemversion krävs av ansökan"; //translation provided by Google Translate
$text['description-required_version']['uk-ua'] = "Мінімальна версія системи вимагає застосування"; //translation provided by Google Translate

$text['header-apps']['en-us'] = "App Manager";
$text['header-apps']['ar-eg'] = "";
$text['header-apps']['de-at'] = "Applikation verwalten";
$text['header-apps']['de-ch'] = "Applikation verwalten"; //copied from de-de
$text['header-apps']['de-de'] = "Applikation verwalten";
$text['header-apps']['es-cl'] = "Administrador de Aplicaciones";
$text['header-apps']['es-mx'] = "Administrador de Aplicaciones"; //copied from es-cl
$text['header-apps']['fr-ca'] = "Gestionnaire App"; //copied from fr-fr
$text['header-apps']['fr-fr'] = "Gestionnaire App";
$text['header-apps']['he-il'] = "";
$text['header-apps']['it-it'] = "Gestore applicazioni";
$text['header-apps']['nl-nl'] = "";
$text['header-apps']['pl-pl'] = "Menedżer aplikacji";
$text['header-apps']['pt-br'] = "Gerenciador de aplicações";
$text['header-apps']['pt-pt'] = "Gestor de Aplicações";
$text['header-apps']['ro-ro'] = "";
$text['header-apps']['ru-ru'] = "Управление приложениями";
$text['header-apps']['sv-se'] = "App Inställningar";
$text['header-apps']['uk-ua'] = "Керування додатками";

$text['header-app-edit']['en-us'] = "App Edit";
$text['header-app-edit']['ar-eg'] = "";
$text['header-app-edit']['de-at'] = "Applikation bearbeiten";
$text['header-app-edit']['de-ch'] = "Applikation bearbeiten"; //copied from de-de
$text['header-app-edit']['de-de'] = "Applikation bearbeiten";
$text['header-app-edit']['es-cl'] = "Editar Aplicaciones";
$text['header-app-edit']['es-mx'] = "Editar Aplicaciones"; //copied from es-cl
$text['header-app-edit']['fr-ca'] = "Editer l'application"; //copied from fr-fr
$text['header-app-edit']['fr-fr'] = "Editer l'application";
$text['header-app-edit']['he-il'] = "";
$text['header-app-edit']['it-it'] = "Modifica applicazione";
$text['header-app-edit']['nl-nl'] = "";
$text['header-app-edit']['pl-pl'] = "Edytuj aplikację ";
$text['header-app-edit']['pt-br'] = "Editar aplicação";
$text['header-app-edit']['pt-pt'] = "Editar aplicação";
$text['header-app-edit']['ro-ro'] = "";
$text['header-app-edit']['ru-ru'] = "Изменеие приложения";
$text['header-app-edit']['sv-se'] = "Ändra App";
$text['header-app-edit']['uk-ua'] = "Редагувати додаток";

$text['description-apps']['en-us'] = "Manage the applications that are installed.";
$text['description-apps']['ar-eg'] = "";
$text['description-apps']['de-at'] = "Installierte Applikationen verwalten";
$text['description-apps']['de-ch'] = "Installierte Applikationen verwalten"; //copied from de-de
$text['description-apps']['de-de'] = "Installierte Applikationen verwalten";
$text['description-apps']['es-cl'] = "Administre las aplicaciones instaladas.";
$text['description-apps']['es-mx'] = "Administre las aplicaciones instaladas."; //copied from es-cl
$text['description-apps']['fr-ca'] = "Gérer les applications installées."; //copied from fr-fr
$text['description-apps']['fr-fr'] = "Gérer les applications installées.";
$text['description-apps']['he-il'] = "";
$text['description-apps']['it-it'] = "Gestisci le applicazioni installate.";
$text['description-apps']['nl-nl'] = "";
$text['description-apps']['pl-pl'] = "Zarządzajnie zainstalowanymi aplikacjami.";
$text['description-apps']['pt-br'] = "Gerenciar aplicações instaladas";
$text['description-apps']['pt-pt'] = "Gerir as aplicações instaladas.";
$text['description-apps']['ro-ro'] = "";
$text['description-apps']['ru-ru'] = "Управление установленными приложениями.";
$text['description-apps']['sv-se'] = "Hantera de applikationer som är installerade.";
$text['description-apps']['uk-ua'] = "Керування встановленими додатками";

$text['description-app-edit']['en-us'] = "Manage the applications that are installed.";
$text['description-app-edit']['ar-eg'] = "";
$text['description-app-edit']['de-at'] = "Installierte Applikationen verwalten";
$text['description-app-edit']['de-ch'] = "Installierte Applikationen verwalten"; //copied from de-at
$text['description-app-edit']['de-de'] = "Installierte Applikationen verwalten"; //copied from de-at
$text['description-app-edit']['es-cl'] = "Administre las aplicaciones instaladas.";
$text['description-app-edit']['es-mx'] = "Administre las aplicaciones instaladas."; //copied from es-cl
$text['description-app-edit']['fr-ca'] = "Gérer les applications installées"; //copied from fr-fr
$text['description-app-edit']['fr-fr'] = "Gérer les applications installées";
$text['description-app-edit']['he-il'] = "";
$text['description-app-edit']['it-it'] = "Gestisci le applicazioni installate.";
$text['description-app-edit']['nl-nl'] = "";
$text['description-app-edit']['pl-pl'] = "Zarządzajnie zainstalowanymi aplikacjami.";
$text['description-app-edit']['pt-br'] = "Gerenciar aplicações instaladas";
$text['description-app-edit']['pt-pt'] = "Gerir as aplicações instaladas.";
$text['description-app-edit']['ro-ro'] = "";
$text['description-app-edit']['ru-ru'] = "Управление установленными приложениями.";
$text['description-app-edit']['sv-se'] = "Hantera de applikationer som är installerade.";
$text['description-app-edit']['uk-ua'] = "Керування встановленими додатками";

?>
