<?php
/*
 * Contributor(s):
 * denisent dev team
 */

	//application details
		$apps[$x]['name'] = "Paging and Intercom";
		$apps[$x]['uuid'] = "bae044dd-e773-471c-a890-5220ebca3bc9";
		$apps[$x]['category'] = "";
		$apps[$x]['subcategory'] = "";
		$apps[$x]['version'] = "0.1";
		$apps[$x]['license'] = "Mozilla Public License 1.1";
		$apps[$x]['url'] = "https://www.fusionpbx.com";
		$apps[$x]['description']['en-us'] = "Manage paging groups and intercom features.";

	//destination details
		$y = 0;
		$apps[$x]['destinations'][$y]['type'] = "sql";
		$apps[$x]['destinations'][$y]['label'] = "paging";
		$apps[$x]['destinations'][$y]['name'] = "paging";
		$apps[$x]['destinations'][$y]['where'] = "where domain_uuid = '\${domain_uuid}' and paging_group_enabled = true ";
		$apps[$x]['destinations'][$y]['order_by'] = "natural_sort(paging_group_extension) asc";
		$apps[$x]['destinations'][$y]['field']['uuid'] = "paging_group_uuid";
		$apps[$x]['destinations'][$y]['field']['name'] = "paging_group_name";
		$apps[$x]['destinations'][$y]['field']['extension'] = "paging_group_extension";
		$apps[$x]['destinations'][$y]['select_value']['dialplan_detail_data'] = "paging_group_extension";
		$apps[$x]['destinations'][$y]['select_label']['dialplan_detail_data'] = "concat(paging_group_name, ' ', paging_group_extension)";
		$y++;

	//default settings
		$y = 0;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "8f5c3d4a-2a15-4a2e-96c8-0f1f70b47001";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "paging";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "extension_range";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "4700-4799";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set the suggested extension range(s) for paging groups.";
		$y++;

	//permissions
		$y = 0;
		$apps[$x]['permissions'][$y]['name'] = "paging_group_view";
		$apps[$x]['permissions'][$y]['menu']['uuid'] = "7bea539e-b1af-486c-9622-3cc5c95cfa0d";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "paging_group_add";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "paging_group_edit";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "paging_group_delete";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;

        $apps[$x]['permissions'][$y]['name'] = "paging_group_destination_view";
        $apps[$x]['permissions'][$y]['groups'][] = "superadmin";
        $apps[$x]['permissions'][$y]['groups'][] = "admin";
        $y++;
        $apps[$x]['permissions'][$y]['name'] = "paging_group_destination_add";
        $apps[$x]['permissions'][$y]['groups'][] = "superadmin";
        $apps[$x]['permissions'][$y]['groups'][] = "admin";
        $y++;
        $apps[$x]['permissions'][$y]['name'] = "paging_group_destination_edit";
        $apps[$x]['permissions'][$y]['groups'][] = "superadmin";
        $apps[$x]['permissions'][$y]['groups'][] = "admin";
        $y++;
        $apps[$x]['permissions'][$y]['name'] = "paging_group_destination_delete";
        $apps[$x]['permissions'][$y]['groups'][] = "superadmin";
        $apps[$x]['permissions'][$y]['groups'][] = "admin";
        $y++;

        //schema details
		$y = 0;
		$apps[$x]['db'][$y]['table']['name'] = "v_paging_groups";
		$apps[$x]['db'][$y]['table']['parent'] = "";
		$z = 0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "paging_group_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_domains";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "domain_uuid";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "dialplan_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_dialplans";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "dialplan_uuid";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "paging_group_extension";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "text";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "paging_group_name";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "text";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "paging_group_description";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "text";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "paging_group_enabled";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "boolean";
		$z++;
        $apps[$x]['db'][$y]['fields'][$z]['name'] = "paging_group_cid_name";
        $apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "text";
        $z++;
        $apps[$x]['db'][$y]['fields'][$z]['name'] = "paging_group_cid_number";
        $apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "text";
        $z++;
        $apps[$x]['db'][$y]['fields'][$z]['name'] = "paging_group_type";
        $apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "text";
        $z++;
        $apps[$x]['db'][$y]['fields'][$z]['name'] = "paging_group_pin_number";
        $apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "text";
        $z++;
        $apps[$x]['db'][$y]['fields'][$z]['name'] = "paging_group_recording_uuid";
        $apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
        $z++;
        $apps[$x]['db'][$y]['fields'][$z]['name'] = "paging_group_announcement_source";
        $apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "text";
        $z++;
        $apps[$x]['db'][$y]['fields'][$z]['name'] = "paging_group_announcement_sound";
        $apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "text";
        $z++;
        $apps[$x]['db'][$y]['fields'][$z]['name'] = "paging_group_announcement_recording_uuid";
        $apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
        $z++;
        $apps[$x]['db'][$y]['fields'][$z]['name'] = "paging_group_timeout";
        $apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "numeric";
        $z++;
        $apps[$x]['db'][$y]['fields'][$z]['name'] = "paging_group_skip_busy";
        $apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "boolean";
        $z++;
        $apps[$x]['db'][$y]['fields'][$z]['name'] = "paging_group_registered_only";
        $apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "boolean";
        $z++;
        $apps[$x]['db'][$y]['fields'][$z]['name'] = "paging_group_include_originator";
        $apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "boolean";
        $z++;
        $apps[$x]['db'][$y]['fields'][$z]['name'] = "paging_group_auto_answer";
        $apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "text";
        $z++;
        $apps[$x]['db'][$y]['fields'][$z]['name'] = "paging_group_join_tone";
        $apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "boolean";
        $z++;
        $apps[$x]['db'][$y]['fields'][$z]['name'] = "paging_group_leave_tone";
        $apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "boolean";
        $z++;
        $apps[$x]['db'][$y]['fields'][$z]['name'] = "paging_group_waiver_enabled";
        $apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "boolean";
        $z++;
        $apps[$x]['db'][$y]['fields'][$z]['name'] = "paging_group_waiver_accept_user";
        $apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
        $z++;
        $apps[$x]['db'][$y]['fields'][$z]['name'] = "paging_group_waiver_accept_date";
        $apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamp";
        $z++;
        $apps[$x]['db'][$y]['fields'][$z]['name'] = "paging_group_waiver_remove_user";
        $apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
        $z++;
        $apps[$x]['db'][$y]['fields'][$z]['name'] = "paging_group_waiver_remove_date";
        $apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamp";
        $z++;
        $apps[$x]['db'][$y]['fields'][$z]['name'] = "insert_date";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamp";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "insert_user";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "update_date";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamp";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "update_user";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$z++;
		$y++;

		$apps[$x]['db'][$y]['table']['name'] = "v_paging_group_destinations";
		$apps[$x]['db'][$y]['table']['parent'] = "v_paging_groups";
		$z = 0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "paging_group_destination_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "paging_group_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_paging_groups";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "paging_group_uuid";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "destination_number";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "text";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "destination_order";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "numeric";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "destination_enabled";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "boolean";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "insert_date";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamp";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "insert_user";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "update_date";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamp";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "update_user";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$z++;

?>
