[program:fusionpbx-horizon]
process_name=%(program_name)s
command=php /var/www/fusionpbx/artisan horizon
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/fusionpbx/storage/logs/horizon.log
stopwaitsecs=3600

[program:fusionpbx-reverb]
process_name=%(program_name)s
command=php /var/www/fusionpbx/artisan reverb:start
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/fusionpbx/storage/logs/reverb.log

[program:fusionpbx-schedule]
process_name=%(program_name)s
command=php /var/www/fusionpbx/artisan schedule:work
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/fusionpbx/storage/logs/schedule.log

[group:fusionpbx]
programs=fusionpbx-horizon,fusionpbx-reverb,fusionpbx-schedule
