<?php
#This file was last reorganized on 19th of September 2017 08:54:24 AM UTC

$text['title-settings-update']['en-us'] = "Setting Update";
$text['title-settings-update']['ar-eg'] = "";
$text['title-settings-update']['de-at'] = "Einstellungen aktualisieren"; //copied from de-de
$text['title-settings-update']['de-ch'] = "Einstellungen aktualisieren"; //copied from de-de
$text['title-settings-update']['de-de'] = "Einstellungen aktualisieren";
$text['title-settings-update']['es-cl'] = "Actualizar Configuración";
$text['title-settings-update']['es-mx'] = "Actualizar Configuración"; //copied from es-cl
$text['title-settings-update']['fr-ca'] = "Mise à jour de la configuration"; //copied from fr-fr
$text['title-settings-update']['fr-fr'] = "Mise à jour de la configuration";
$text['title-settings-update']['he-il'] = "";
$text['title-settings-update']['it-it'] = "Aggiornamento Parametri";
$text['title-settings-update']['nl-nl'] = "";
$text['title-settings-update']['pl-pl'] = "Aktualizacja ustawienia";
$text['title-settings-update']['pt-br'] = "Atualizar configurações";
$text['title-settings-update']['pt-pt'] = "Actualizar a Configuração";
$text['title-settings-update']['ro-ro'] = "";
$text['title-settings-update']['ru-ru'] = "Обновление Параметров";
$text['title-settings-update']['sv-se'] = "Ändra Inställningar";
$text['title-settings-update']['uk-ua'] = "Оновлення налаштувань";

$text['title-settings-add']['en-us'] = "Setting Add";
$text['title-settings-add']['ar-eg'] = "";
$text['title-settings-add']['de-at'] = "Einstellung hinzufügen"; //copied from de-de
$text['title-settings-add']['de-ch'] = "Einstellung hinzufügen"; //copied from de-de
$text['title-settings-add']['de-de'] = "Einstellung hinzufügen";
$text['title-settings-add']['es-cl'] = "Añadir Configuración";
$text['title-settings-add']['es-mx'] = "Añadir Configuración"; //copied from es-cl
$text['title-settings-add']['fr-ca'] = "Ajouter Cadre"; //copied from fr-fr
$text['title-settings-add']['fr-fr'] = "Ajouter Cadre";
$text['title-settings-add']['he-il'] = "";
$text['title-settings-add']['it-it'] = "Inserire Parametro";
$text['title-settings-add']['nl-nl'] = "";
$text['title-settings-add']['pl-pl'] = "Dodaj ustawienie";
$text['title-settings-add']['pt-br'] = "Adionar configuração";
$text['title-settings-add']['pt-pt'] = "Adicionar Configuração";
$text['title-settings-add']['ro-ro'] = "";
$text['title-settings-add']['ru-ru'] = "Параметры добавлены";
$text['title-settings-add']['sv-se'] = "Lägg Till Inställning";
$text['title-settings-add']['uk-ua'] = "Додавання налаштувань";

$text['label-xml-rpc-user']['en-us'] = "XML RPC Auth User";
$text['label-xml-rpc-user']['ar-eg'] = "";
$text['label-xml-rpc-user']['de-at'] = "XML RPC Auth Benutzer"; //copied from de-de
$text['label-xml-rpc-user']['de-ch'] = "XML RPC Auth Benutzer"; //copied from de-de
$text['label-xml-rpc-user']['de-de'] = "XML RPC Auth Benutzer";
$text['label-xml-rpc-user']['es-cl'] = "Usuario XML RPC";
$text['label-xml-rpc-user']['es-mx'] = "Usuario XML RPC"; //copied from es-cl
$text['label-xml-rpc-user']['fr-ca'] = "Auth usager XML RPC"; //copied from fr-fr
$text['label-xml-rpc-user']['fr-fr'] = "Auth usager XML RPC";
$text['label-xml-rpc-user']['he-il'] = "";
$text['label-xml-rpc-user']['it-it'] = "XML RPC Auth User";
$text['label-xml-rpc-user']['nl-nl'] = "";
$text['label-xml-rpc-user']['pl-pl'] = "Użytkownik XML RPC";
$text['label-xml-rpc-user']['pt-br'] = "Utilizar autenticação de XML RPC";
$text['label-xml-rpc-user']['pt-pt'] = "Utilizador de autenticação de XML RPC";
$text['label-xml-rpc-user']['ro-ro'] = "";
$text['label-xml-rpc-user']['ru-ru'] = "Использовать XML RPC для подлинности Пользователя";
$text['label-xml-rpc-user']['sv-se'] = "XML RPC Auth User";
$text['label-xml-rpc-user']['uk-ua'] = "XML RPC Auth User ";

$text['label-xml-rpc-realm']['en-us'] = "XML RPC Auth Realm";
$text['label-xml-rpc-realm']['ar-eg'] = "";
$text['label-xml-rpc-realm']['de-at'] = "XML RPC Auth Realm"; //copied from de-de
$text['label-xml-rpc-realm']['de-ch'] = "XML RPC Auth Realm"; //copied from de-de
$text['label-xml-rpc-realm']['de-de'] = "XML RPC Auth Realm";
$text['label-xml-rpc-realm']['es-cl'] = "Reino de Autenticación XML RPC";
$text['label-xml-rpc-realm']['es-mx'] = "Reino de Autenticación XML RPC"; //copied from es-cl
$text['label-xml-rpc-realm']['fr-ca'] = "XML RPC Auth Realm"; //copied from fr-fr
$text['label-xml-rpc-realm']['fr-fr'] = "XML RPC Auth Realm";
$text['label-xml-rpc-realm']['he-il'] = "";
$text['label-xml-rpc-realm']['it-it'] = "XML RPC Auth Realm";
$text['label-xml-rpc-realm']['nl-nl'] = "";
$text['label-xml-rpc-realm']['pl-pl'] = "Realm (domena) XML RPC";
$text['label-xml-rpc-realm']['pt-br'] = "Reutilizar autenticação de XML RPC";
$text['label-xml-rpc-realm']['pt-pt'] = "Realm de autenticação do XML RPC";
$text['label-xml-rpc-realm']['ro-ro'] = "";
$text['label-xml-rpc-realm']['ru-ru'] = "Область проверки подлинности XML RPC";
$text['label-xml-rpc-realm']['sv-se'] = "XML RPC Auth Realm";
$text['label-xml-rpc-realm']['uk-ua'] = "XML RPC Auth Realm ";

$text['label-xml-rpc-pw']['en-us'] = "XML RPC Auth Password";
$text['label-xml-rpc-pw']['ar-eg'] = "";
$text['label-xml-rpc-pw']['de-at'] = "XML RPC Auth Passwort"; //copied from de-de
$text['label-xml-rpc-pw']['de-ch'] = "XML RPC Auth Passwort"; //copied from de-de
$text['label-xml-rpc-pw']['de-de'] = "XML RPC Auth Passwort";
$text['label-xml-rpc-pw']['es-cl'] = "Ingrese la contraseña XML RPC";
$text['label-xml-rpc-pw']['es-mx'] = "Ingrese la contraseña XML RPC"; //copied from es-cl
$text['label-xml-rpc-pw']['fr-ca'] = "Mot de passe XML RPC"; //copied from fr-fr
$text['label-xml-rpc-pw']['fr-fr'] = "Mot de passe XML RPC";
$text['label-xml-rpc-pw']['he-il'] = "";
$text['label-xml-rpc-pw']['it-it'] = "XML RPC Auth Password";
$text['label-xml-rpc-pw']['nl-nl'] = "";
$text['label-xml-rpc-pw']['pl-pl'] = "Hasło XML RPC";
$text['label-xml-rpc-pw']['pt-br'] = "Palavra chave de autenticação do XML RPC";
$text['label-xml-rpc-pw']['pt-pt'] = "Palavra-passe de autenticação do XML RPC";
$text['label-xml-rpc-pw']['ro-ro'] = "";
$text['label-xml-rpc-pw']['ru-ru'] = "XML RPC Пароль проверки подлинности";
$text['label-xml-rpc-pw']['sv-se'] = "XML RPC Auth Password";
$text['label-xml-rpc-pw']['uk-ua'] = "XML RPC Auth Password ";

$text['label-xml-rpc-port']['en-us'] = "XML RPC HTTP Port";
$text['label-xml-rpc-port']['ar-eg'] = "";
$text['label-xml-rpc-port']['de-at'] = "XML RPC HTTP Port "; //copied from de-de
$text['label-xml-rpc-port']['de-ch'] = "XML RPC HTTP Port "; //copied from de-de
$text['label-xml-rpc-port']['de-de'] = "XML RPC HTTP Port ";
$text['label-xml-rpc-port']['es-cl'] = "Puerto XML RPC HTTP";
$text['label-xml-rpc-port']['es-mx'] = "Puerto XML RPC HTTP"; //copied from es-cl
$text['label-xml-rpc-port']['fr-ca'] = "XML RPC HTTP Port"; //copied from fr-fr
$text['label-xml-rpc-port']['fr-fr'] = "XML RPC HTTP Port";
$text['label-xml-rpc-port']['he-il'] = "";
$text['label-xml-rpc-port']['it-it'] = "XML RPC HTTP Port";
$text['label-xml-rpc-port']['nl-nl'] = "";
$text['label-xml-rpc-port']['pl-pl'] = "Port HTTP XML RPC";
$text['label-xml-rpc-port']['pt-br'] = "Porta HTTP do XML RPC";
$text['label-xml-rpc-port']['pt-pt'] = "Porto HTTP do XML RPC";
$text['label-xml-rpc-port']['ro-ro'] = "";
$text['label-xml-rpc-port']['ru-ru'] = "XML RPC HTTP Порт";
$text['label-xml-rpc-port']['sv-se'] = "XML RPC HTTP Port";
$text['label-xml-rpc-port']['uk-ua'] = "XML RPC HTTP Port ";

$text['label-shout-volume']['en-us'] = "Mod Shout Volume";
$text['label-shout-volume']['ar-eg'] = "";
$text['label-shout-volume']['de-at'] = "Mod Shout Lautstärke"; //copied from de-de
$text['label-shout-volume']['de-ch'] = "Mod Shout Lautstärke"; //copied from de-de
$text['label-shout-volume']['de-de'] = "Mod Shout Lautstärke";
$text['label-shout-volume']['es-cl'] = "Volumen Mod Shout";
$text['label-shout-volume']['es-mx'] = "Volumen Mod Shout"; //copied from es-cl
$text['label-shout-volume']['fr-ca'] = "Mod Shout Volume"; //copied from fr-fr
$text['label-shout-volume']['fr-fr'] = "Mod Shout Volume";
$text['label-shout-volume']['he-il'] = "";
$text['label-shout-volume']['it-it'] = "Volume Mod Shout";
$text['label-shout-volume']['nl-nl'] = "";
$text['label-shout-volume']['pl-pl'] = "Głośność modułu mod_shout";
$text['label-shout-volume']['pt-br'] = "Volume do Mod Shout"; //copied from pt-pt
$text['label-shout-volume']['pt-pt'] = "Volume do Mod Shout";
$text['label-shout-volume']['ro-ro'] = "";
$text['label-shout-volume']['ru-ru'] = "Mod Shout Volume";
$text['label-shout-volume']['sv-se'] = "Mod Shout Volume";
$text['label-shout-volume']['uk-ua'] = "Mod Shout Volume ";

$text['label-shout-decoder']['en-us'] = "Mod Shout Decoder";
$text['label-shout-decoder']['ar-eg'] = "";
$text['label-shout-decoder']['de-at'] = "Mod Shout Decoder"; //copied from de-de
$text['label-shout-decoder']['de-ch'] = "Mod Shout Decoder"; //copied from de-de
$text['label-shout-decoder']['de-de'] = "Mod Shout Decoder";
$text['label-shout-decoder']['es-cl'] = "Descodificador Mod Shout (MP3)";
$text['label-shout-decoder']['es-mx'] = "Descodificador Mod Shout (MP3)"; //copied from es-cl
$text['label-shout-decoder']['fr-ca'] = "Décodeur Mod Shout (MP3)"; //copied from fr-fr
$text['label-shout-decoder']['fr-fr'] = "Décodeur Mod Shout (MP3)";
$text['label-shout-decoder']['he-il'] = "";
$text['label-shout-decoder']['it-it'] = "Decoder Mod Shout";
$text['label-shout-decoder']['nl-nl'] = "";
$text['label-shout-decoder']['pl-pl'] = "Dekoder modułu mod_shout";
$text['label-shout-decoder']['pt-br'] = "Decodificador do Mod Shout (MP3) ";
$text['label-shout-decoder']['pt-pt'] = "Descodificador do Mod Shout (MP3)";
$text['label-shout-decoder']['ro-ro'] = "";
$text['label-shout-decoder']['ru-ru'] = "Mod Shout Decoder";
$text['label-shout-decoder']['sv-se'] = "Mod Shout Decoder";
$text['label-shout-decoder']['uk-ua'] = "Mod Shout Decoder ";

$text['label-event-socket-pw']['en-us'] = "Event Socket Password";
$text['label-event-socket-pw']['ar-eg'] = "";
$text['label-event-socket-pw']['de-at'] = "Event Socket Passwort"; //copied from de-de
$text['label-event-socket-pw']['de-ch'] = "Event Socket Passwort"; //copied from de-de
$text['label-event-socket-pw']['de-de'] = "Event Socket Passwort";
$text['label-event-socket-pw']['es-cl'] = "Contraseña del Docket de Eventos";
$text['label-event-socket-pw']['es-mx'] = "Contraseña del Docket de Eventos"; //copied from es-cl
$text['label-event-socket-pw']['fr-ca'] = "Mot de Passe Event Socket"; //copied from fr-fr
$text['label-event-socket-pw']['fr-fr'] = "Mot de Passe Event Socket";
$text['label-event-socket-pw']['he-il'] = "";
$text['label-event-socket-pw']['it-it'] = "Password Event Socket";
$text['label-event-socket-pw']['nl-nl'] = "";
$text['label-event-socket-pw']['pl-pl'] = "Hasło 'Event Socket'";
$text['label-event-socket-pw']['pt-br'] = "Palavra-chave do Evento Socket ";
$text['label-event-socket-pw']['pt-pt'] = "Palavra-chave do Event Socket";
$text['label-event-socket-pw']['ro-ro'] = "";
$text['label-event-socket-pw']['ru-ru'] = "Пароль сокета событий";
$text['label-event-socket-pw']['sv-se'] = "Event Socket Password";
$text['label-event-socket-pw']['uk-ua'] = "Event Socket Password ";

$text['label-event-socket-port']['en-us'] = "Event Socket Port";
$text['label-event-socket-port']['ar-eg'] = "";
$text['label-event-socket-port']['de-at'] = "Event Socket Port"; //copied from de-de
$text['label-event-socket-port']['de-ch'] = "Event Socket Port"; //copied from de-de
$text['label-event-socket-port']['de-de'] = "Event Socket Port";
$text['label-event-socket-port']['es-cl'] = "Puerto del Socket de Eventos";
$text['label-event-socket-port']['es-mx'] = "Puerto del Socket de Eventos"; //copied from es-cl
$text['label-event-socket-port']['fr-ca'] = "Event Socket Port"; //copied from fr-fr
$text['label-event-socket-port']['fr-fr'] = "Event Socket Port";
$text['label-event-socket-port']['he-il'] = "";
$text['label-event-socket-port']['it-it'] = "Porta Event Socket";
$text['label-event-socket-port']['nl-nl'] = "";
$text['label-event-socket-port']['pl-pl'] = "Port 'Event Socket'";
$text['label-event-socket-port']['pt-br'] = "Porta do Evento Socket ";
$text['label-event-socket-port']['pt-pt'] = "Porto do Event Socket";
$text['label-event-socket-port']['ro-ro'] = "";
$text['label-event-socket-port']['ru-ru'] = "Порт сокета событий";
$text['label-event-socket-port']['sv-se'] = "Event Socket Port ";
$text['label-event-socket-port']['uk-ua'] = "Event Socket Port ";

$text['label-event-socket-ip']['en-us'] = "Event Socket IP Address";
$text['label-event-socket-ip']['ar-eg'] = "";
$text['label-event-socket-ip']['de-at'] = "Event Socket IP Adresse"; //copied from de-de
$text['label-event-socket-ip']['de-ch'] = "Event Socket IP Adresse"; //copied from de-de
$text['label-event-socket-ip']['de-de'] = "Event Socket IP Adresse";
$text['label-event-socket-ip']['es-cl'] = "Dirección IP del Socket de Eventos";
$text['label-event-socket-ip']['es-mx'] = "Dirección IP del Socket de Eventos"; //copied from es-cl
$text['label-event-socket-ip']['fr-ca'] = "Adresse IP pour Event Socket"; //copied from fr-fr
$text['label-event-socket-ip']['fr-fr'] = "Adresse IP pour Event Socket";
$text['label-event-socket-ip']['he-il'] = "";
$text['label-event-socket-ip']['it-it'] = "IP Address Event Socket";
$text['label-event-socket-ip']['nl-nl'] = "";
$text['label-event-socket-ip']['pl-pl'] = "Adres IP 'Event Socket'";
$text['label-event-socket-ip']['pt-br'] = "Endreço IP do Evento Socket ";
$text['label-event-socket-ip']['pt-pt'] = "Endreço IP do Event Socket";
$text['label-event-socket-ip']['ro-ro'] = "";
$text['label-event-socket-ip']['ru-ru'] = "IP Address сокета событий";
$text['label-event-socket-ip']['sv-se'] = "Event Socket IP Address";
$text['label-event-socket-ip']['uk-ua'] = "Event Socket IP Address";

$text['description-xml-rpc-user']['en-us'] = "Enter the XML RPC Auth User. default: xmlrpc";
$text['description-xml-rpc-user']['ar-eg'] = "";
$text['description-xml-rpc-user']['de-at'] = "Geben Sie den XML RPC Auth Benutzer an. Standard: xmlrpc"; //copied from de-de
$text['description-xml-rpc-user']['de-ch'] = "Geben Sie den XML RPC Auth Benutzer an. Standard: xmlrpc"; //copied from de-de
$text['description-xml-rpc-user']['de-de'] = "Geben Sie den XML RPC Auth Benutzer an. Standard: xmlrpc";
$text['description-xml-rpc-user']['es-cl'] = "Ingrese usuario XML RPC. Predeterminado: xmlrpc";
$text['description-xml-rpc-user']['es-mx'] = "Ingrese usuario XML RPC. Predeterminado: xmlrpc"; //copied from es-cl
$text['description-xml-rpc-user']['fr-ca'] = "Usager XML RPC. défaut: xmlrpc"; //copied from fr-fr
$text['description-xml-rpc-user']['fr-fr'] = "Usager XML RPC. défaut: xmlrpc";
$text['description-xml-rpc-user']['he-il'] = "";
$text['description-xml-rpc-user']['it-it'] = "Inserire the XML RPC Auth User. default: xmlrpc";
$text['description-xml-rpc-user']['nl-nl'] = "";
$text['description-xml-rpc-user']['pl-pl'] = "Wprowadź użytkownika XML RPC (domyślny xmlrpc)";
$text['description-xml-rpc-user']['pt-br'] = "Introduza o utilizador de autenticação do XML RPC.xmlrpc ";
$text['description-xml-rpc-user']['pt-pt'] = "Introduza o utilizador de autenticação do XML RPC. omissão: xmlrpc";
$text['description-xml-rpc-user']['ro-ro'] = "";
$text['description-xml-rpc-user']['ru-ru'] = "Введите XML RPC для авторизации пользователя. По умолчанию: xmlrpc";
$text['description-xml-rpc-user']['sv-se'] = "Fyll i XML RPC Auth User. default: xmlrpc";
$text['description-xml-rpc-user']['uk-ua'] = "Enter the XML RPC Auth User. default: xmlrpc ";

$text['description-xml-rpc-realm']['en-us'] = "Enter the XML RPC Auth Realm. default: freeswitch";
$text['description-xml-rpc-realm']['ar-eg'] = "";
$text['description-xml-rpc-realm']['de-at'] = "Geben Sie den XML RPC Auth Realm an. Standard: freeswitch"; //copied from de-de
$text['description-xml-rpc-realm']['de-ch'] = "Geben Sie den XML RPC Auth Realm an. Standard: freeswitch"; //copied from de-de
$text['description-xml-rpc-realm']['de-de'] = "Geben Sie den XML RPC Auth Realm an. Standard: freeswitch";
$text['description-xml-rpc-realm']['es-cl'] = "Ingrese el reino de autenticación XML RPC. Predeterminado: freeswitch";
$text['description-xml-rpc-realm']['es-mx'] = "Ingrese el reino de autenticación XML RPC. Predeterminado: freeswitch"; //copied from es-cl
$text['description-xml-rpc-realm']['fr-ca'] = "Royaume d'authentification XML RPC. défaut: freeswitch"; //copied from fr-fr
$text['description-xml-rpc-realm']['fr-fr'] = "Royaume d'authentification XML RPC. défaut: freeswitch";
$text['description-xml-rpc-realm']['he-il'] = "";
$text['description-xml-rpc-realm']['it-it'] = "Inserire lo XML RPC Auth Realm. default: freeswitch";
$text['description-xml-rpc-realm']['nl-nl'] = "";
$text['description-xml-rpc-realm']['pl-pl'] = "Wprowadź realm (domenę) XML RPC (domyślna freeswitch).";
$text['description-xml-rpc-realm']['pt-br'] = "Introduza o dominio de autenticação do XML RPC.  freeswitch ";
$text['description-xml-rpc-realm']['pt-pt'] = "Introduza o Realm de autenticação do XML RPC. omissão: freeswitch";
$text['description-xml-rpc-realm']['ro-ro'] = "";
$text['description-xml-rpc-realm']['ru-ru'] = "Введите XML RPC области аутентификации. По умолчанию: freeswitch";
$text['description-xml-rpc-realm']['sv-se'] = "Fyll i XML RPC Auth Realm. default: freeswitch ";
$text['description-xml-rpc-realm']['uk-ua'] = "Enter the XML RPC Auth Realm. default: freeswitch ";

$text['description-xml-rpc-pw']['en-us'] = "Enter the XML RPC Auth Password.";
$text['description-xml-rpc-pw']['ar-eg'] = "";
$text['description-xml-rpc-pw']['de-at'] = "Geben Sie das XML RPC Auth Passwort an."; //copied from de-de
$text['description-xml-rpc-pw']['de-ch'] = "Geben Sie das XML RPC Auth Passwort an."; //copied from de-de
$text['description-xml-rpc-pw']['de-de'] = "Geben Sie das XML RPC Auth Passwort an.";
$text['description-xml-rpc-pw']['es-cl'] = "Ingrese la contraseña XML RPC.";
$text['description-xml-rpc-pw']['es-mx'] = "Ingrese la contraseña XML RPC."; //copied from es-cl
$text['description-xml-rpc-pw']['fr-ca'] = "Mot de passe pour XML RPC."; //copied from fr-fr
$text['description-xml-rpc-pw']['fr-fr'] = "Mot de passe pour XML RPC.";
$text['description-xml-rpc-pw']['he-il'] = "";
$text['description-xml-rpc-pw']['it-it'] = "Inserire la XML RPC Auth Password.";
$text['description-xml-rpc-pw']['nl-nl'] = "";
$text['description-xml-rpc-pw']['pl-pl'] = "Wprowadź hasło XML RPC";
$text['description-xml-rpc-pw']['pt-br'] = "Introduza a palavra-chave de autenticação do XML RPC. ";
$text['description-xml-rpc-pw']['pt-pt'] = "Introduza a palavra-passe de autenticação do XML RPC.";
$text['description-xml-rpc-pw']['ro-ro'] = "";
$text['description-xml-rpc-pw']['ru-ru'] = "Введите XML RPC Пароль для авторизации.";
$text['description-xml-rpc-pw']['sv-se'] = "Fyll i XML RPC Auth Password.";
$text['description-xml-rpc-pw']['uk-ua'] = "Enter the XML RPC Auth Password. ";

$text['description-xml-rpc-port']['en-us'] = "Enter the XML RPC HTTP Port. default: 8080";
$text['description-xml-rpc-port']['ar-eg'] = "";
$text['description-xml-rpc-port']['de-at'] = "Geben Sie den XML RPC HTTP Port an. Standard: 8080"; //copied from de-de
$text['description-xml-rpc-port']['de-ch'] = "Geben Sie den XML RPC HTTP Port an. Standard: 8080"; //copied from de-de
$text['description-xml-rpc-port']['de-de'] = "Geben Sie den XML RPC HTTP Port an. Standard: 8080";
$text['description-xml-rpc-port']['es-cl'] = "Ingrese el puerto XML RPC HTTP. Predeterminado: 8080";
$text['description-xml-rpc-port']['es-mx'] = "Ingrese el puerto XML RPC HTTP. Predeterminado: 8080"; //copied from es-cl
$text['description-xml-rpc-port']['fr-ca'] = "Port pour joindre le service  XML RPC HTTP. défaut: 8080"; //copied from fr-fr
$text['description-xml-rpc-port']['fr-fr'] = "Port pour joindre le service  XML RPC HTTP. défaut: 8080";
$text['description-xml-rpc-port']['he-il'] = "";
$text['description-xml-rpc-port']['it-it'] = "Inserire la XML RPC HTTP Port. default: 8080";
$text['description-xml-rpc-port']['nl-nl'] = "";
$text['description-xml-rpc-port']['pl-pl'] = "Wprowadź port HTTP XML RPC";
$text['description-xml-rpc-port']['pt-br'] = "Introduza a oirta HTTP para o XML RPC. 8080 ";
$text['description-xml-rpc-port']['pt-pt'] = "Introduza o porto HTTP para o XML RPC. omissão: 8080";
$text['description-xml-rpc-port']['ro-ro'] = "";
$text['description-xml-rpc-port']['ru-ru'] = "Введите XML RPC HTTP Порт. По умолчанию: 8080";
$text['description-xml-rpc-port']['sv-se'] = "Fyll i XML RPC HTTP Port. default: 8080";
$text['description-xml-rpc-port']['uk-ua'] = "Enter the XML RPC HTTP Port. default: 8080 ";

$text['description-shout-volume']['en-us'] = "Enter Mod Shout Volume.";
$text['description-shout-volume']['ar-eg'] = "";
$text['description-shout-volume']['de-at'] = "Geben Sie Mod Shout Lautstärke an."; //copied from de-de
$text['description-shout-volume']['de-ch'] = "Geben Sie Mod Shout Lautstärke an."; //copied from de-de
$text['description-shout-volume']['de-de'] = "Geben Sie Mod Shout Lautstärke an.";
$text['description-shout-volume']['es-cl'] = "Ingrese el volumen del Mod Shout.";
$text['description-shout-volume']['es-mx'] = "Ingrese el volumen del Mod Shout."; //copied from es-cl
$text['description-shout-volume']['fr-ca'] = "Choisir l'amplification du volume pour Mod Shout."; //copied from fr-fr
$text['description-shout-volume']['fr-fr'] = "Choisir l'amplification du volume pour Mod Shout.";
$text['description-shout-volume']['he-il'] = "";
$text['description-shout-volume']['it-it'] = "Inserire Volume Mod Shout.";
$text['description-shout-volume']['nl-nl'] = "";
$text['description-shout-volume']['pl-pl'] = "Wprowadź głośność modułu Mod Shout";
$text['description-shout-volume']['pt-br'] = "Introduza o volume do Mod Shout. ";
$text['description-shout-volume']['pt-pt'] = "Introduza o volume do Mod Shout.";
$text['description-shout-volume']['ro-ro'] = "";
$text['description-shout-volume']['ru-ru'] = "Введите Mod Shout Volume.";
$text['description-shout-volume']['sv-se'] = "Fyll i Mod Shout Volume.";
$text['description-shout-volume']['uk-ua'] = "Enter Mod Shout Volume. ";

$text['description-shout-decoder']['en-us'] = "Enter the Decoder. default: i386";
$text['description-shout-decoder']['ar-eg'] = "";
$text['description-shout-decoder']['de-at'] = "Wählen Sie den Decoder. Standard: i386"; //copied from de-de
$text['description-shout-decoder']['de-ch'] = "Wählen Sie den Decoder. Standard: i386"; //copied from de-de
$text['description-shout-decoder']['de-de'] = "Wählen Sie den Decoder. Standard: i386";
$text['description-shout-decoder']['es-cl'] = "Ingrese el tipo de descodificador. Predeterminado: i386";
$text['description-shout-decoder']['es-mx'] = "Ingrese el tipo de descodificador. Predeterminado: i386"; //copied from es-cl
$text['description-shout-decoder']['fr-ca'] = "Type de Décodeur. défaut: i386"; //copied from fr-fr
$text['description-shout-decoder']['fr-fr'] = "Type de Décodeur. défaut: i386";
$text['description-shout-decoder']['he-il'] = "";
$text['description-shout-decoder']['it-it'] = "Inserire il Decoder. default: i386";
$text['description-shout-decoder']['nl-nl'] = "";
$text['description-shout-decoder']['pl-pl'] = "Wprowadź rodzaj dekodera (domyślny i386)";
$text['description-shout-decoder']['pt-br'] = "Tipo de descodificador. i386 ";
$text['description-shout-decoder']['pt-pt'] = "Tipo de descodificador. omissão: i386";
$text['description-shout-decoder']['ro-ro'] = "";
$text['description-shout-decoder']['ru-ru'] = "Введите Decoder. По умолчанию: i386";
$text['description-shout-decoder']['sv-se'] = "Fyll i Decoder. default: i386";
$text['description-shout-decoder']['uk-ua'] = "Enter the Decoder. default: i386 ";

$text['description-event-socket-pw']['en-us'] = "Enter the event socket password.";
$text['description-event-socket-pw']['ar-eg'] = "";
$text['description-event-socket-pw']['de-at'] = "Geben Sie das Event Socket Passwort an."; //copied from de-de
$text['description-event-socket-pw']['de-ch'] = "Geben Sie das Event Socket Passwort an."; //copied from de-de
$text['description-event-socket-pw']['de-de'] = "Geben Sie das Event Socket Passwort an.";
$text['description-event-socket-pw']['es-cl'] = "Ingrese la contraseña del socket de eventos.";
$text['description-event-socket-pw']['es-mx'] = "Ingrese la contraseña del socket de eventos."; //copied from es-cl
$text['description-event-socket-pw']['fr-ca'] = "Mot de passe pour se connecter au module Event Socket."; //copied from fr-fr
$text['description-event-socket-pw']['fr-fr'] = "Mot de passe pour se connecter au module Event Socket.";
$text['description-event-socket-pw']['he-il'] = "";
$text['description-event-socket-pw']['it-it'] = "Inserire la password della event socket.";
$text['description-event-socket-pw']['nl-nl'] = "";
$text['description-event-socket-pw']['pl-pl'] = "Wprowadź hasło 'Event Socket'";
$text['description-event-socket-pw']['pt-br'] = "Introduza a palavra-chave do event socket. ";
$text['description-event-socket-pw']['pt-pt'] = "Introduza a palavra-chave do event socket.";
$text['description-event-socket-pw']['ro-ro'] = "";
$text['description-event-socket-pw']['ru-ru'] = "Введите пароль сокета событий.";
$text['description-event-socket-pw']['sv-se'] = "Fyll i event socket password.";
$text['description-event-socket-pw']['uk-ua'] = "Enter the event socket password. ";

$text['description-event-socket-port']['en-us'] = "Enter the event socket port. default: 8021";
$text['description-event-socket-port']['ar-eg'] = "";
$text['description-event-socket-port']['de-at'] = "Geben Sie den Event Socket Port an. Standard: 8021"; //copied from de-de
$text['description-event-socket-port']['de-ch'] = "Geben Sie den Event Socket Port an. Standard: 8021"; //copied from de-de
$text['description-event-socket-port']['de-de'] = "Geben Sie den Event Socket Port an. Standard: 8021";
$text['description-event-socket-port']['es-cl'] = "Puerto del Socket de eventos. Predeterminado: 8021";
$text['description-event-socket-port']['es-mx'] = "Puerto del Socket de eventos. Predeterminado: 8021"; //copied from es-cl
$text['description-event-socket-port']['fr-ca'] = "Port du module Event Socket. défaut: 8021"; //copied from fr-fr
$text['description-event-socket-port']['fr-fr'] = "Port du module Event Socket. défaut: 8021";
$text['description-event-socket-port']['he-il'] = "";
$text['description-event-socket-port']['it-it'] = "Inserire la porta della event socket. default: 8021";
$text['description-event-socket-port']['nl-nl'] = "";
$text['description-event-socket-port']['pl-pl'] = "Wprowadź port 'Event Socket' (domyślny 8021)";
$text['description-event-socket-port']['pt-br'] = "Introduza o porto do evento socket. 8021 ";
$text['description-event-socket-port']['pt-pt'] = "Introduza o porto do event socket. omissão: 8021";
$text['description-event-socket-port']['ro-ro'] = "";
$text['description-event-socket-port']['ru-ru'] = "Введите порт сокета событий. По умолчанию: 8021";
$text['description-event-socket-port']['sv-se'] = "Fyll i event socket port. default: 8021";
$text['description-event-socket-port']['uk-ua'] = "Enter the event socket port. default: 8021 ";

$text['description-event-socket-ip']['en-us'] = "Enter the event socket IP address. default: 127.0.0.1";
$text['description-event-socket-ip']['ar-eg'] = "";
$text['description-event-socket-ip']['de-at'] = "Geben Sie die Event Socket IP Addresse an. Standard: 127.0.0.1"; //copied from de-de
$text['description-event-socket-ip']['de-ch'] = "Geben Sie die Event Socket IP Addresse an. Standard: 127.0.0.1"; //copied from de-de
$text['description-event-socket-ip']['de-de'] = "Geben Sie die Event Socket IP Addresse an. Standard: 127.0.0.1";
$text['description-event-socket-ip']['es-cl'] = "Dirección IP del socket de eventos. Predeterminada: 127.0.0.1";
$text['description-event-socket-ip']['es-mx'] = "Dirección IP del socket de eventos. Predeterminada: 127.0.0.1"; //copied from es-cl
$text['description-event-socket-ip']['fr-ca'] = "Adresse IP pour le module Event Socket. défaut: 127.0.0.1"; //copied from fr-fr
$text['description-event-socket-ip']['fr-fr'] = "Adresse IP pour le module Event Socket. défaut: 127.0.0.1";
$text['description-event-socket-ip']['he-il'] = "";
$text['description-event-socket-ip']['it-it'] = "Inserire l'IP address della event socket. default: 127.0.0.1";
$text['description-event-socket-ip']['nl-nl'] = "";
$text['description-event-socket-ip']['pl-pl'] = "Wprowadź adres IP 'Event Socket' (domyślny 127.0.0.1)";
$text['description-event-socket-ip']['pt-br'] = "Introduza o endereço IP do evento socket. omissão: 127.0.0.1 ";
$text['description-event-socket-ip']['pt-pt'] = "Introduza o endereço IP do event socket. omissão: 127.0.0.1";
$text['description-event-socket-ip']['ro-ro'] = "";
$text['description-event-socket-ip']['ru-ru'] = "Введите IP адрес сокета событий. по умолчанию: 127.0.0.1";
$text['description-event-socket-ip']['sv-se'] = "Fyll i event socket IP address. default: 127.0.0.1";
$text['description-event-socket-ip']['uk-ua'] = "Enter the event socket IP address. default: 127.0.0.1 ";

?>
