<?php
#This file was last reorganized on 19th of September 2017 08:54:24 AM UTC

$text['title']['en-us'] = "Voicemail Greetings";
$text['title']['en-gb'] = "Voicemail Greetings";
$text['title']['ar-eg'] = "";
$text['title']['de-at'] = "Begrüßungen für Sprachnachrichten"; //copied from de-de
$text['title']['de-ch'] = "Begrüßungen für Sprachnachrichten"; //copied from de-de
$text['title']['de-de'] = "Begrüßungen für Sprachnachrichten";
$text['title']['es-cl'] = "";
$text['title']['es-mx'] = "";
$text['title']['fr-ca'] = "Salutations de la messagerie"; //copied from fr-fr
$text['title']['fr-fr'] = "Salutations de la messagerie";
$text['title']['he-il'] = "הגדרת חשבון";
$text['title']['it-it'] = "Saluti Caselle Vocali";
$text['title']['nl-nl'] = "Antwoordapparaat begroetingen";
$text['title']['pl-pl'] = "Ustawienia konta";
$text['title']['pt-br'] = "Configurações da Conta";
$text['title']['pt-pt'] = "Saudações de correio de voz";
$text['title']['ro-ro'] = "";
$text['title']['ru-ru'] = "";
$text['title']['sv-se'] = "Röstbrevlåda Hälsningar";
$text['title']['uk-ua'] = "Привітання";

$text['label-size']['en-us'] = "Size";
$text['label-size']['en-gb'] = "Size";
$text['label-size']['ar-eg'] = "";
$text['label-size']['de-at'] = "Größe"; //copied from de-de
$text['label-size']['de-ch'] = "Größe"; //copied from de-de
$text['label-size']['de-de'] = "Größe";
$text['label-size']['es-cl'] = "Tamaño";
$text['label-size']['es-mx'] = "Tamaño"; //copied from es-cl
$text['label-size']['fr-ca'] = "Taille"; //copied from fr-fr
$text['label-size']['fr-fr'] = "Taille";
$text['label-size']['he-il'] = "גודל";
$text['label-size']['it-it'] = "Dimensione";
$text['label-size']['nl-nl'] = "Omvang";
$text['label-size']['pl-pl'] = "Rozmiar";
$text['label-size']['pt-br'] = "Tamanho"; //copied from pt-pt
$text['label-size']['pt-pt'] = "Tamanho";
$text['label-size']['ro-ro'] = "";
$text['label-size']['ru-ru'] = "";
$text['label-size']['sv-se'] = "Storlek";
$text['label-size']['uk-ua'] = "Розмір";

$text['label-number']['en-us'] = "#";
$text['label-number']['en-gb'] = "#";
$text['label-number']['ar-eg'] = "#";
$text['label-number']['de-at'] = "#"; //copied from de-de
$text['label-number']['de-ch'] = "#"; //copied from de-de
$text['label-number']['de-de'] = "#";
$text['label-number']['es-cl'] = "Número";
$text['label-number']['es-mx'] = "Número"; //copied from es-cl
$text['label-number']['fr-ca'] = "Nombre"; //copied from fr-fr
$text['label-number']['fr-fr'] = "Nombre";
$text['label-number']['he-il'] = "#";
$text['label-number']['it-it'] = "#";
$text['label-number']['nl-nl'] = "Nummer";
$text['label-number']['pl-pl'] = "liczba";
$text['label-number']['pt-br'] = "Número"; //copied from pt-pt
$text['label-number']['pt-pt'] = "Número";
$text['label-number']['ro-ro'] = "#";
$text['label-number']['ru-ru'] = "#";
$text['label-number']['sv-se'] = "#";
$text['label-number']['uk-ua'] = "кількість";

$text['label-name']['en-us'] = "Name";
$text['label-name']['en-gb'] = "Name";
$text['label-name']['ar-eg'] = "";
$text['label-name']['de-at'] = "Name"; //copied from de-de
$text['label-name']['de-ch'] = "Name"; //copied from de-de
$text['label-name']['de-de'] = "Name";
$text['label-name']['es-cl'] = "Nombre";
$text['label-name']['es-mx'] = "Nombre"; //copied from es-cl
$text['label-name']['fr-ca'] = "Nom"; //copied from fr-fr
$text['label-name']['fr-fr'] = "Nom";
$text['label-name']['he-il'] = "שם";
$text['label-name']['it-it'] = "Nome";
$text['label-name']['nl-nl'] = "Naam";
$text['label-name']['pl-pl'] = "Nazwa";
$text['label-name']['pt-br'] = "Nome"; //copied from pt-pt
$text['label-name']['pt-pt'] = "Nome";
$text['label-name']['ro-ro'] = "";
$text['label-name']['ru-ru'] = "";
$text['label-name']['sv-se'] = "Namn";
$text['label-name']['uk-ua'] = "Назва";

$text['label-description']['en-us'] = "Description";
$text['label-description']['en-gb'] = "Description";
$text['label-description']['ar-eg'] = "";
$text['label-description']['de-at'] = "Beschreibung"; //copied from de-de
$text['label-description']['de-ch'] = "Beschreibung"; //copied from de-de
$text['label-description']['de-de'] = "Beschreibung";
$text['label-description']['es-cl'] = "Descripción";
$text['label-description']['es-mx'] = "Descripción"; //copied from es-cl
$text['label-description']['fr-ca'] = "Description"; //copied from fr-fr
$text['label-description']['fr-fr'] = "Description";
$text['label-description']['he-il'] = "תיאור";
$text['label-description']['it-it'] = "Descrizione";
$text['label-description']['nl-nl'] = "Omschrijving";
$text['label-description']['pl-pl'] = "Opis";
$text['label-description']['pt-br'] = "Descrição"; //copied from pt-pt
$text['label-description']['pt-pt'] = "Descrição";
$text['label-description']['ro-ro'] = "";
$text['label-description']['ru-ru'] = "";
$text['label-description']['sv-se'] = "Beskrivning";
$text['label-description']['uk-ua'] = "Опис";

$text['message-uploaded']['en-us'] = "Upload Complete";
$text['message-uploaded']['en-gb'] = "Upload Complete";
$text['message-uploaded']['ar-eg'] = "";
$text['message-uploaded']['de-at'] = "Hochladen abgeschlossen"; //copied from de-de
$text['message-uploaded']['de-ch'] = "Hochladen abgeschlossen"; //copied from de-de
$text['message-uploaded']['de-de'] = "Hochladen abgeschlossen";
$text['message-uploaded']['es-cl'] = "Subida Finalizada";
$text['message-uploaded']['es-mx'] = "Subida Finalizada"; //copied from es-cl
$text['message-uploaded']['fr-ca'] = "Enregistrer Complet"; //copied from fr-fr
$text['message-uploaded']['fr-fr'] = "Enregistrer Complet";
$text['message-uploaded']['he-il'] = "הטענה הושלמה";
$text['message-uploaded']['it-it'] = "Caricamento Completato";
$text['message-uploaded']['nl-nl'] = "Opsturen gereed";
$text['message-uploaded']['pl-pl'] = "Plik wysłano  poprawnie";
$text['message-uploaded']['pt-br'] = "Arquivo carregado para";
$text['message-uploaded']['pt-pt'] = "Carregamento Finalizado";
$text['message-uploaded']['ro-ro'] = "";
$text['message-uploaded']['ru-ru'] = "";
$text['message-uploaded']['sv-se'] = "Uppladdning Klar";
$text['message-uploaded']['uk-ua'] = "Завантажено";

$text['message-greeting_selected']['en-us'] = "Greeting Selected";
$text['message-greeting_selected']['en-gb'] = "Greeting Selected";
$text['message-greeting_selected']['ar-eg'] = "";
$text['message-greeting_selected']['de-at'] = "Begrüßung ausgewählt"; //copied from de-de
$text['message-greeting_selected']['de-ch'] = "Begrüßung ausgewählt"; //copied from de-de
$text['message-greeting_selected']['de-de'] = "Begrüßung ausgewählt";
$text['message-greeting_selected']['es-cl'] = "Saludo Seleccionado";
$text['message-greeting_selected']['es-mx'] = "Saludo Seleccionado"; //copied from es-cl
$text['message-greeting_selected']['fr-ca'] = "Message d'accueil Sélectionné"; //copied from fr-fr
$text['message-greeting_selected']['fr-fr'] = "Message d'accueil Sélectionné";
$text['message-greeting_selected']['he-il'] = "הברכה נבחרה";
$text['message-greeting_selected']['it-it'] = "Saluto Selezionato";
$text['message-greeting_selected']['nl-nl'] = "Begroeting geselecteerd";
$text['message-greeting_selected']['pl-pl'] = "POWITANIE Wybrane";
$text['message-greeting_selected']['pt-br'] = "Saudação Selecionada"; //copied from pt-pt
$text['message-greeting_selected']['pt-pt'] = "Saudação Selecionada";
$text['message-greeting_selected']['ro-ro'] = "";
$text['message-greeting_selected']['ru-ru'] = "";
$text['message-greeting_selected']['sv-se'] = "Hälsning Vald";
$text['message-greeting_selected']['uk-ua'] = "привітання Вибрані";

$text['label-tools']['en-us'] = "Tools";
$text['label-tools']['en-gb'] = "Tools";
$text['label-tools']['ar-eg'] = "";
$text['label-tools']['de-at'] = "Werkzeuge"; //copied from de-de
$text['label-tools']['de-ch'] = "Werkzeuge"; //copied from de-de
$text['label-tools']['de-de'] = "Werkzeuge";
$text['label-tools']['es-cl'] = "Instrumentos";
$text['label-tools']['es-mx'] = "Instrumentos"; //copied from es-cl
$text['label-tools']['fr-ca'] = "Outils"; //copied from fr-fr
$text['label-tools']['fr-fr'] = "Outils";
$text['label-tools']['he-il'] = "כלים";
$text['label-tools']['it-it'] = "Strumenti";
$text['label-tools']['nl-nl'] = "Gereedschappen";
$text['label-tools']['pl-pl'] = "Narzędzia";
$text['label-tools']['pt-br'] = "Ferramentas"; //copied from pt-pt
$text['label-tools']['pt-pt'] = "Ferramentas";
$text['label-tools']['ro-ro'] = "";
$text['label-tools']['ru-ru'] = "";
$text['label-tools']['sv-se'] = "Verktyg";
$text['label-tools']['uk-ua'] = "Параметри";

$text['label-select_a_file']['en-us'] = "Select a file...";
$text['label-select_a_file']['en-gb'] = "Select a file...";
$text['label-select_a_file']['ar-eg'] = "";
$text['label-select_a_file']['de-at'] = "Wähle eine Datei aus..."; //copied from de-de
$text['label-select_a_file']['de-ch'] = "Wähle eine Datei aus..."; //copied from de-de
$text['label-select_a_file']['de-de'] = "Wähle eine Datei aus...";
$text['label-select_a_file']['es-cl'] = "Seleccione un archivo...";
$text['label-select_a_file']['es-mx'] = "Seleccione un archivo..."; //copied from es-cl
$text['label-select_a_file']['fr-ca'] = "Sélectionner un fichier..."; //copied from fr-fr
$text['label-select_a_file']['fr-fr'] = "Sélectionner un fichier...";
$text['label-select_a_file']['he-il'] = "בחר קובץ ...";
$text['label-select_a_file']['it-it'] = "Selezionare un file...";
$text['label-select_a_file']['nl-nl'] = "Kies een bestand...";
$text['label-select_a_file']['pl-pl'] = "Wybierz plik ...";
$text['label-select_a_file']['pt-br'] = "Selecione um arquivo ..."; //copied from pt-pt
$text['label-select_a_file']['pt-pt'] = "Selecione um arquivo ...";
$text['label-select_a_file']['ro-ro'] = "";
$text['label-select_a_file']['ru-ru'] = "";
$text['label-select_a_file']['sv-se'] = "Välj en fil ...";
$text['label-select_a_file']['uk-ua'] = "Виберіть файл ...";

$text['label-play']['en-us'] = "Play";
$text['label-play']['en-gb'] = "Play";
$text['label-play']['ar-eg'] = "";
$text['label-play']['de-at'] = "Abspielen"; //copied from de-de
$text['label-play']['de-ch'] = "Abspielen"; //copied from de-de
$text['label-play']['de-de'] = "Abspielen";
$text['label-play']['es-cl'] = "Reproducir";
$text['label-play']['es-mx'] = "Reproducir"; //copied from es-cl
$text['label-play']['fr-ca'] = "Jouer"; //copied from fr-fr
$text['label-play']['fr-fr'] = "Jouer";
$text['label-play']['he-il'] = "נגן";
$text['label-play']['it-it'] = "Suona";
$text['label-play']['nl-nl'] = "Afspelen";
$text['label-play']['pl-pl'] = "Odtwórz";
$text['label-play']['pt-br'] = "Tocar"; //copied from pt-pt
$text['label-play']['pt-pt'] = "Tocar";
$text['label-play']['ro-ro'] = "";
$text['label-play']['ru-ru'] = "";
$text['label-play']['sv-se'] = "Spela Upp";
$text['label-play']['uk-ua'] = "Відтворити";

$text['label-pause']['en-us'] = "Pause";
$text['label-pause']['en-gb'] = "Pause";
$text['label-pause']['ar-eg'] = "";
$text['label-pause']['de-at'] = "Pause"; //copied from de-de
$text['label-pause']['de-ch'] = "Pause"; //copied from de-de
$text['label-pause']['de-de'] = "Pause";
$text['label-pause']['es-cl'] = "Pausa";
$text['label-pause']['es-mx'] = "Pausa"; //copied from es-cl
$text['label-pause']['fr-ca'] = "Pause"; //copied from fr-fr
$text['label-pause']['fr-fr'] = "Pause";
$text['label-pause']['he-il'] = "השהייה";
$text['label-pause']['it-it'] = "Pausa";
$text['label-pause']['nl-nl'] = "Pause";
$text['label-pause']['pl-pl'] = "Pauza";
$text['label-pause']['pt-br'] = "Pausado";
$text['label-pause']['pt-pt'] = "Pausa";
$text['label-pause']['ro-ro'] = "";
$text['label-pause']['ru-ru'] = "";
$text['label-pause']['sv-se'] = "Pausa";
$text['label-pause']['uk-ua'] = "Призупинити";

$text['label-greeting']['en-us'] = "Greeting";
$text['label-greeting']['en-gb'] = "Greeting";
$text['label-greeting']['ar-eg'] = "";
$text['label-greeting']['de-at'] = "Begrüßung"; //copied from de-de
$text['label-greeting']['de-ch'] = "Begrüßung"; //copied from de-de
$text['label-greeting']['de-de'] = "Begrüßung";
$text['label-greeting']['es-cl'] = "Saludo";
$text['label-greeting']['es-mx'] = "Saludo"; //copied from es-cl
$text['label-greeting']['fr-ca'] = "Salutation"; //copied from fr-fr
$text['label-greeting']['fr-fr'] = "Salutation";
$text['label-greeting']['he-il'] = "ברכה";
$text['label-greeting']['it-it'] = "Saluto";
$text['label-greeting']['nl-nl'] = "Begroeting";
$text['label-greeting']['pl-pl'] = "powitanie";
$text['label-greeting']['pt-br'] = "Saudação"; //copied from pt-pt
$text['label-greeting']['pt-pt'] = "Saudação";
$text['label-greeting']['ro-ro'] = "";
$text['label-greeting']['ru-ru'] = "";
$text['label-greeting']['sv-se'] = "Hälsning";
$text['label-greeting']['uk-ua'] = "привітання";

$text['label-filename']['en-us'] = "File Name";
$text['label-filename']['en-gb'] = "File Name";
$text['label-filename']['ar-eg'] = "";
$text['label-filename']['de-at'] = "Dateiname"; //copied from de-de
$text['label-filename']['de-ch'] = "Dateiname"; //copied from de-de
$text['label-filename']['de-de'] = "Dateiname";
$text['label-filename']['es-cl'] = "Nombre Del Archivo";
$text['label-filename']['es-mx'] = "Nombre Del Archivo"; //copied from es-cl
$text['label-filename']['fr-ca'] = "Nom de fichier"; //copied from fr-fr
$text['label-filename']['fr-fr'] = "Nom de fichier";
$text['label-filename']['he-il'] = "שם קובץ";
$text['label-filename']['it-it'] = "Nome File";
$text['label-filename']['nl-nl'] = "Bestandsnaam";
$text['label-filename']['pl-pl'] = "Nazwa Pliku";
$text['label-filename']['pt-br'] = "Nome Do Arquivo"; //copied from pt-pt
$text['label-filename']['pt-pt'] = "Nome Do Arquivo";
$text['label-filename']['ro-ro'] = "";
$text['label-filename']['ru-ru'] = "";
$text['label-filename']['sv-se'] = "Filnamn";
$text['label-filename']['uk-ua'] = "ім'я Файлу";

$text['label-edit']['en-us'] = "Edit Greeting";
$text['label-edit']['en-gb'] = "Edit Greeting";
$text['label-edit']['ar-eg'] = "";
$text['label-edit']['de-at'] = "Begrüßung bearbeiten"; //copied from de-de
$text['label-edit']['de-ch'] = "Begrüßung bearbeiten"; //copied from de-de
$text['label-edit']['de-de'] = "Begrüßung bearbeiten";
$text['label-edit']['es-cl'] = "Edición de Saludo";
$text['label-edit']['es-mx'] = "Edición de Saludo"; //copied from es-cl
$text['label-edit']['fr-ca'] = "Editer Salutation"; //copied from fr-fr
$text['label-edit']['fr-fr'] = "Editer Salutation";
$text['label-edit']['he-il'] = "עריכה";
$text['label-edit']['it-it'] = "Modificare Saluto";
$text['label-edit']['nl-nl'] = "Bewerk begroeting";
$text['label-edit']['pl-pl'] = "Edytuj";
$text['label-edit']['pt-br'] = "Editar";
$text['label-edit']['pt-pt'] = "Editar Saudação";
$text['label-edit']['ro-ro'] = "";
$text['label-edit']['ru-ru'] = "";
$text['label-edit']['sv-se'] = "Ändra Hälsning";
$text['label-edit']['uk-ua'] = "Редагувати";

$text['label-download']['en-us'] = "Download";
$text['label-download']['en-gb'] = "Download";
$text['label-download']['ar-eg'] = "";
$text['label-download']['de-at'] = "Herunterladen"; //copied from de-de
$text['label-download']['de-ch'] = "Herunterladen"; //copied from de-de
$text['label-download']['de-de'] = "Herunterladen";
$text['label-download']['es-cl'] = "Descargar";
$text['label-download']['es-mx'] = "Descargar"; //copied from es-cl
$text['label-download']['fr-ca'] = "Télécharger"; //copied from fr-fr
$text['label-download']['fr-fr'] = "Télécharger";
$text['label-download']['he-il'] = "הורדה";
$text['label-download']['it-it'] = "Scaricare";
$text['label-download']['nl-nl'] = "Ophalen";
$text['label-download']['pl-pl'] = "Pobierz";
$text['label-download']['pt-br'] = "Download";
$text['label-download']['pt-pt'] = "Descarregar";
$text['label-download']['ro-ro'] = "";
$text['label-download']['ru-ru'] = "";
$text['label-download']['sv-se'] = "Ladda Ned";
$text['label-download']['uk-ua'] = "Завантажини";

$text['label-add']['en-us'] = "Add Greeting";
$text['label-add']['en-gb'] = "Add Greeting";
$text['label-add']['ar-eg'] = "";
$text['label-add']['de-at'] = "Begrüßung hinzufügen"; //copied from de-de
$text['label-add']['de-ch'] = "Begrüßung hinzufügen"; //copied from de-de
$text['label-add']['de-de'] = "Begrüßung hinzufügen";
$text['label-add']['es-cl'] = "Agregar Saludo";
$text['label-add']['es-mx'] = "Agregar Saludo"; //copied from es-cl
$text['label-add']['fr-ca'] = "Ajouter salutation"; //copied from fr-fr
$text['label-add']['fr-fr'] = "Ajouter salutation";
$text['label-add']['he-il'] = "הוסף ברכה";
$text['label-add']['it-it'] = "Inserire Saluto";
$text['label-add']['nl-nl'] = "Voeg begroeting toe";
$text['label-add']['pl-pl'] = "Dodaj powitanie";
$text['label-add']['pt-br'] = "Adicionar Greeting";
$text['label-add']['pt-pt'] = "Adicionar Saudação";
$text['label-add']['ro-ro'] = "";
$text['label-add']['ru-ru'] = "";
$text['label-add']['sv-se'] = "Lägg Till Hälsning";
$text['label-add']['uk-ua'] = "Додати привітання";

$text['label-selected']['en-us'] = "Selected";
$text['label-selected']['en-gb'] = "Selected";
$text['label-selected']['ar-eg'] = "";
$text['label-selected']['de-at'] = "Ausgewählt"; //copied from de-de
$text['label-selected']['de-ch'] = "Ausgewählt"; //copied from de-de
$text['label-selected']['de-de'] = "Ausgewählt";
$text['label-selected']['es-cl'] = "Seleccionado";
$text['label-selected']['es-mx'] = "Seleccionado"; //copied from es-cl
$text['label-selected']['fr-ca'] = "Sélectionné"; //copied from fr-fr
$text['label-selected']['fr-fr'] = "Sélectionné";
$text['label-selected']['he-il'] = "";
$text['label-selected']['it-it'] = "Selezionato";
$text['label-selected']['nl-nl'] = "";
$text['label-selected']['pl-pl'] = "Wybrane";
$text['label-selected']['pt-br'] = "Selecionado"; //copied from pt-pt
$text['label-selected']['pt-pt'] = "Selecionado";
$text['label-selected']['ro-ro'] = "";
$text['label-selected']['ru-ru'] = "Выбор";
$text['label-selected']['sv-se'] = "Valt";
$text['label-selected']['uk-ua'] = "";

$text['description-name']['en-us'] = "A name for the greeting (not parsed).";
$text['description-name']['en-gb'] = "A name for the greeting (not parsed).";
$text['description-name']['ar-eg'] = "";
$text['description-name']['de-at'] = "Ein Namen für die Begrüßung."; //copied from de-de
$text['description-name']['de-ch'] = "Ein Namen für die Begrüßung."; //copied from de-de
$text['description-name']['de-de'] = "Ein Namen für die Begrüßung.";
$text['description-name']['es-cl'] = "Nombre de Bienvenida.";
$text['description-name']['es-mx'] = "Nombre de Bienvenida."; //copied from es-cl
$text['description-name']['fr-ca'] = "Nome da Salutation  (non parsé)."; //copied from fr-fr
$text['description-name']['fr-fr'] = "Nome da Salutation  (non parsé).";
$text['description-name']['he-il'] = "הכנס את השם";
$text['description-name']['it-it'] = "Un nome per il saluto (non parsato).";
$text['description-name']['nl-nl'] = "Een naam voor de begroeting.";
$text['description-name']['pl-pl'] = "Wprowadź nazwę";
$text['description-name']['pt-br'] = "Insira o nome do menu";
$text['description-name']['pt-pt'] = "Nome da Saudação.";
$text['description-name']['ro-ro'] = "";
$text['description-name']['ru-ru'] = "";
$text['description-name']['sv-se'] = "Ett namn för hälsningen.";
$text['description-name']['uk-ua'] = "Введіть назву привітання";

$text['description-info']['en-us'] = "You may enter a description here for your reference (not parsed).";
$text['description-info']['en-gb'] = "You may enter a description here for your reference (not parsed).";
$text['description-info']['ar-eg'] = "";
$text['description-info']['de-at'] = "Sie können hier eine Beschreibung als Referenz eintragen."; //copied from de-de
$text['description-info']['de-ch'] = "Sie können hier eine Beschreibung als Referenz eintragen."; //copied from de-de
$text['description-info']['de-de'] = "Sie können hier eine Beschreibung als Referenz eintragen.";
$text['description-info']['es-cl'] = "Ingrese una descripción (Opcional).";
$text['description-info']['es-mx'] = "Ingrese una descripción (Opcional)."; //copied from es-cl
$text['description-info']['fr-ca'] = "Vous pouvez entrer ici une description pour votre référence (non parsé)."; //copied from fr-fr
$text['description-info']['fr-fr'] = "Vous pouvez entrer ici une description pour votre référence (non parsé).";
$text['description-info']['he-il'] = "הכנס תאור";
$text['description-info']['it-it'] = "Puoi inserire qui una descrizione per tuo riferimento (non parsato).";
$text['description-info']['nl-nl'] = "Je kan een omschrijving invoeren als referentie.";
$text['description-info']['pl-pl'] = "Wprowadź opis";
$text['description-info']['pt-br'] = "Inisra uma descrição";
$text['description-info']['pt-pt'] = "Pode inserir uma descrição para referência futura aqui.";
$text['description-info']['ro-ro'] = "";
$text['description-info']['ru-ru'] = "";
$text['description-info']['sv-se'] = "Du kan ange en beskrivning här som din egna referens.";
$text['description-info']['uk-ua'] = "Введіть опис";

$text['description']['en-us'] = "Select the active greeting message to play for extension:";
$text['description']['en-gb'] = "Select the active greeting message to play for extension:";
$text['description']['ar-eg'] = "";
$text['description']['de-at'] = "Wählen Sie die aktive Begrüßung aus, welche für diese Nebenstelle abgespielt werden soll:"; //copied from de-de
$text['description']['de-ch'] = "Wählen Sie die aktive Begrüßung aus, welche für diese Nebenstelle abgespielt werden soll:"; //copied from de-de
$text['description']['de-de'] = "Wählen Sie die aktive Begrüßung aus, welche für diese Nebenstelle abgespielt werden soll:";
$text['description']['es-cl'] = "Seleccione el mensaje activo para reproducir:";
$text['description']['es-mx'] = "Seleccione el mensaje activo para reproducir:"; //copied from es-cl
$text['description']['fr-ca'] = "Choisir le message de salutation à jouer pour l'extension:"; //copied from fr-fr
$text['description']['fr-fr'] = "Choisir le message de salutation à jouer pour l'extension:";
$text['description']['he-il'] = "ערוך את פרטי החשבון";
$text['description']['it-it'] = "Selezionare il messaggio di saluto attivo da suonare per l'interno:";
$text['description']['nl-nl'] = "Kies de aktieve begroeting om op het toestel af te spelen:";
$text['description']['pl-pl'] = "Edytuj informacje o koncie";
$text['description']['pt-br'] = "Editar informações da conta.";
$text['description']['pt-pt'] = "Escolha e active uma mensagem de saudação a aplicar na extensão:";
$text['description']['ro-ro'] = "";
$text['description']['ru-ru'] = "";
$text['description']['sv-se'] = "Välj hälsning att som skall användas för anknytning:";
$text['description']['uk-ua'] = "Виберіть активне привітання для розширення";

$text['confirm-name']['en-us'] = "Please provide: Greeting Name";
$text['confirm-name']['en-gb'] = "Please provide: Greeting Name";
$text['confirm-name']['ar-eg'] = "";
$text['confirm-name']['de-at'] = "Bitte bereitstellen: Namen der Begrüßung"; //copied from de-de
$text['confirm-name']['de-ch'] = "Bitte bereitstellen: Namen der Begrüßung"; //copied from de-de
$text['confirm-name']['de-de'] = "Bitte bereitstellen: Namen der Begrüßung";
$text['confirm-name']['es-cl'] = "Por favor indique: Nombre de Bienvenida";
$text['confirm-name']['es-mx'] = "Por favor indique: Nombre de Bienvenida"; //copied from es-cl
$text['confirm-name']['fr-ca'] = "Merci d'indiquer: Nom de salutation"; //copied from fr-fr
$text['confirm-name']['fr-fr'] = "Merci d'indiquer: Nom de salutation";
$text['confirm-name']['he-il'] = "אנא הוסף: שם ברכה";
$text['confirm-name']['it-it'] = "Prego fornire: Nome Saluto";
$text['confirm-name']['nl-nl'] = "Geef aub: Begroetingsnaam";
$text['confirm-name']['pl-pl'] = "Wprowadź: Nazwę";
$text['confirm-name']['pt-br'] = "Por favor indique: Nome";
$text['confirm-name']['pt-pt'] = "Por favor indique: Nome da saudação";
$text['confirm-name']['ro-ro'] = "";
$text['confirm-name']['ru-ru'] = "";
$text['confirm-name']['sv-se'] = "Var god ange: Hälsningsnamn";
$text['confirm-name']['uk-ua'] = "Введіть назву привітання";

$text['confirm-filename']['en-us'] = "Please provide: Greeting Filename";
$text['confirm-filename']['en-gb'] = "Please provide: Greeting Filename";
$text['confirm-filename']['ar-eg'] = "";
$text['confirm-filename']['de-at'] = "Bitte bereitstellen: Dateinamen der Begrüßung"; //copied from de-de
$text['confirm-filename']['de-ch'] = "Bitte bereitstellen: Dateinamen der Begrüßung"; //copied from de-de
$text['confirm-filename']['de-de'] = "Bitte bereitstellen: Dateinamen der Begrüßung";
$text['confirm-filename']['es-cl'] = "Por favor indique: Nombre Del Archivo";
$text['confirm-filename']['es-mx'] = "Por favor indique: Nombre Del Archivo"; //copied from es-cl
$text['confirm-filename']['fr-ca'] = "Merci d'indiquer: Nom De Fichier"; //copied from fr-fr
$text['confirm-filename']['fr-fr'] = "Merci d'indiquer: Nom De Fichier";
$text['confirm-filename']['he-il'] = "אנא הוסף: שם קובץ לברכה";
$text['confirm-filename']['it-it'] = "Prego fornire: Nome File Saluto";
$text['confirm-filename']['nl-nl'] = "Geef aub: Begroetingsbestandsnaam";
$text['confirm-filename']['pl-pl'] = "Proszę podać: Greeting Infomacje";
$text['confirm-filename']['pt-br'] = "Por favor indique: Nome Do Arquivo"; //copied from pt-pt
$text['confirm-filename']['pt-pt'] = "Por favor indique: Nome Do Arquivo";
$text['confirm-filename']['ro-ro'] = "";
$text['confirm-filename']['ru-ru'] = "";
$text['confirm-filename']['sv-se'] = "Var god ange: Hälsnings Filnamn";
$text['confirm-filename']['uk-ua'] = "Будь ласка, надайте: Привітання файлу";

?>
