<?php
#This file was last reorganized on 19th of September 2017 08:54:24 AM UTC

$text['title-call_flows']['en-us'] = "Call Flows";
$text['title-call_flows']['en-gb'] = "Call Flows";
$text['title-call_flows']['ar-eg'] = "";
$text['title-call_flows']['de-at'] = "Anruf Steuerung"; //copied from de-de
$text['title-call_flows']['de-ch'] = "Anruf Steuerung"; //copied from de-de
$text['title-call_flows']['de-de'] = "Anruf Steuerung";
$text['title-call_flows']['es-cl'] = "Flujo de Llamada";
$text['title-call_flows']['es-mx'] = "Flujo de Llamada"; //copied from es-cl
$text['title-call_flows']['fr-ca'] = "Flux d'appel"; //copied from fr-fr
$text['title-call_flows']['fr-fr'] = "Flux d'appel";
$text['title-call_flows']['he-il'] = "";
$text['title-call_flows']['it-it'] = "Deviatori di Chiamata";
$text['title-call_flows']['nl-nl'] = "Oproep besturing";
$text['title-call_flows']['pl-pl'] = "Przepływ rozmów";
$text['title-call_flows']['pt-br'] = "Fluxo de chamadas";
$text['title-call_flows']['pt-pt'] = "Fluxo de Chamadas";
$text['title-call_flows']['ro-ro'] = "";
$text['title-call_flows']['ru-ru'] = "Переключатели вызовов";
$text['title-call_flows']['sv-se'] = "Samtalsflöden";
$text['title-call_flows']['uk-ua'] = "Потоки дзвінків";

$text['title-call_flow']['en-us'] = "Call Flow";
$text['title-call_flow']['en-gb'] = "Call Flow";
$text['title-call_flow']['ar-eg'] = "";
$text['title-call_flow']['de-at'] = "Anruf Steuerung"; //copied from de-de
$text['title-call_flow']['de-ch'] = "Anruf Steuerung"; //copied from de-de
$text['title-call_flow']['de-de'] = "Anruf Steuerung";
$text['title-call_flow']['es-cl'] = "Flujo de Llamada";
$text['title-call_flow']['es-mx'] = "Flujo de Llamada"; //copied from es-cl
$text['title-call_flow']['fr-ca'] = "Editer le flux"; //copied from fr-fr
$text['title-call_flow']['fr-fr'] = "Editer le flux";
$text['title-call_flow']['he-il'] = "";
$text['title-call_flow']['it-it'] = "";
$text['title-call_flow']['nl-nl'] = "Oproep besturing";
$text['title-call_flow']['pl-pl'] = "Przepływ rozmów";
$text['title-call_flow']['pt-br'] = "Fluxo de chamada";
$text['title-call_flow']['pt-pt'] = "Fluxo de Chamada";
$text['title-call_flow']['ro-ro'] = "";
$text['title-call_flow']['ru-ru'] = "Переключатель вызовов";
$text['title-call_flow']['sv-se'] = "Samtalsflöde";
$text['title-call_flow']['uk-ua'] = "Потік дзвінків";

$text['label-call_flow_name']['en-us'] = "Name";
$text['label-call_flow_name']['en-gb'] = "Name";
$text['label-call_flow_name']['ar-eg'] = "";
$text['label-call_flow_name']['de-at'] = "Name"; //copied from de-de
$text['label-call_flow_name']['de-ch'] = "Name"; //copied from de-de
$text['label-call_flow_name']['de-de'] = "Name";
$text['label-call_flow_name']['es-cl'] = "Nombre";
$text['label-call_flow_name']['es-mx'] = "Nombre"; //copied from es-cl
$text['label-call_flow_name']['fr-ca'] = "Nom"; //copied from fr-fr
$text['label-call_flow_name']['fr-fr'] = "Nom";
$text['label-call_flow_name']['he-il'] = "";
$text['label-call_flow_name']['it-it'] = "";
$text['label-call_flow_name']['nl-nl'] = "Naam";
$text['label-call_flow_name']['pl-pl'] = "Nazwa";
$text['label-call_flow_name']['pt-br'] = "Nome"; //copied from pt-pt
$text['label-call_flow_name']['pt-pt'] = "Nome";
$text['label-call_flow_name']['ro-ro'] = "";
$text['label-call_flow_name']['ru-ru'] = "Имя";
$text['label-call_flow_name']['sv-se'] = "Namn";
$text['label-call_flow_name']['uk-ua'] = "Назва";

$text['label-call_flow_status']['en-us'] = "Status";
$text['label-call_flow_status']['en-gb'] = "Status";
$text['label-call_flow_status']['ar-eg'] = "";
$text['label-call_flow_status']['de-at'] = "Aktiviert"; //copied from de-de
$text['label-call_flow_status']['de-ch'] = "Aktiviert"; //copied from de-de
$text['label-call_flow_status']['de-de'] = "Aktiviert";
$text['label-call_flow_status']['es-cl'] = "Estado";
$text['label-call_flow_status']['es-mx'] = "Estado"; //copied from es-cl
$text['label-call_flow_status']['fr-ca'] = "Etat"; //copied from fr-fr
$text['label-call_flow_status']['fr-fr'] = "Etat";
$text['label-call_flow_status']['he-il'] = "";
$text['label-call_flow_status']['it-it'] = "";
$text['label-call_flow_status']['nl-nl'] = "Status";
$text['label-call_flow_status']['pl-pl'] = "Status";
$text['label-call_flow_status']['pt-br'] = "Estado"; //copied from pt-pt
$text['label-call_flow_status']['pt-pt'] = "Estado";
$text['label-call_flow_status']['ro-ro'] = "";
$text['label-call_flow_status']['ru-ru'] = "Статус";
$text['label-call_flow_status']['sv-se'] = "Status";
$text['label-call_flow_status']['uk-ua'] = "Статус";

$text['label-call_flow_pin_number']['en-us'] = "PIN Number";
$text['label-call_flow_pin_number']['en-gb'] = "PIN Number";
$text['label-call_flow_pin_number']['ar-eg'] = "";
$text['label-call_flow_pin_number']['de-at'] = "PIN Nummer"; //copied from de-de
$text['label-call_flow_pin_number']['de-ch'] = "PIN Nummer"; //copied from de-de
$text['label-call_flow_pin_number']['de-de'] = "PIN Nummer";
$text['label-call_flow_pin_number']['es-cl'] = "Número PIN";
$text['label-call_flow_pin_number']['es-mx'] = "Número PIN"; //copied from es-cl
$text['label-call_flow_pin_number']['fr-ca'] = "Code PIN"; //copied from fr-fr
$text['label-call_flow_pin_number']['fr-fr'] = "Code PIN";
$text['label-call_flow_pin_number']['he-il'] = "";
$text['label-call_flow_pin_number']['it-it'] = "";
$text['label-call_flow_pin_number']['nl-nl'] = "PIN code";
$text['label-call_flow_pin_number']['pl-pl'] = "Numer PIN";
$text['label-call_flow_pin_number']['pt-br'] = "Código PIN"; //copied from pt-pt
$text['label-call_flow_pin_number']['pt-pt'] = "Código PIN";
$text['label-call_flow_pin_number']['ro-ro'] = "";
$text['label-call_flow_pin_number']['ru-ru'] = "PIN код";
$text['label-call_flow_pin_number']['sv-se'] = "PIN Kod";
$text['label-call_flow_pin_number']['uk-ua'] = "PIN-код";

$text['label-call_flow_feature_code']['en-us'] = "Feature Code";
$text['label-call_flow_feature_code']['en-gb'] = "Feature Code";
$text['label-call_flow_feature_code']['ar-eg'] = "";
$text['label-call_flow_feature_code']['de-at'] = "Funktions-Code"; //copied from de-de
$text['label-call_flow_feature_code']['de-ch'] = "Funktions-Code"; //copied from de-de
$text['label-call_flow_feature_code']['de-de'] = "Funktions-Code";
$text['label-call_flow_feature_code']['es-cl'] = "Código distintivo";
$text['label-call_flow_feature_code']['es-mx'] = "Código distintivo"; //copied from es-cl
$text['label-call_flow_feature_code']['fr-ca'] = "Code Fonction"; //copied from fr-fr
$text['label-call_flow_feature_code']['fr-fr'] = "Code Fonction";
$text['label-call_flow_feature_code']['he-il'] = "";
$text['label-call_flow_feature_code']['it-it'] = "";
$text['label-call_flow_feature_code']['nl-nl'] = "Functie-code";
$text['label-call_flow_feature_code']['pl-pl'] = "";
$text['label-call_flow_feature_code']['pt-br'] = "Código de função";
$text['label-call_flow_feature_code']['pt-pt'] = "Código de Função";
$text['label-call_flow_feature_code']['ro-ro'] = "";
$text['label-call_flow_feature_code']['ru-ru'] = "Код функции";
$text['label-call_flow_feature_code']['sv-se'] = "Funktionskod";
$text['label-call_flow_feature_code']['uk-ua'] = "";

$text['label-call_flow_extension']['en-us'] = "Extension";
$text['label-call_flow_extension']['en-gb'] = "Extension";
$text['label-call_flow_extension']['ar-eg'] = "";
$text['label-call_flow_extension']['de-at'] = "Nebenstelle"; //copied from de-de
$text['label-call_flow_extension']['de-ch'] = "Nebenstelle"; //copied from de-de
$text['label-call_flow_extension']['de-de'] = "Nebenstelle";
$text['label-call_flow_extension']['es-cl'] = "Extensión";
$text['label-call_flow_extension']['es-mx'] = "Extensión"; //copied from es-cl
$text['label-call_flow_extension']['fr-ca'] = "Extension"; //copied from fr-fr
$text['label-call_flow_extension']['fr-fr'] = "Extension";
$text['label-call_flow_extension']['he-il'] = "";
$text['label-call_flow_extension']['it-it'] = "";
$text['label-call_flow_extension']['nl-nl'] = "Toestel";
$text['label-call_flow_extension']['pl-pl'] = "Numer wewnętrzny";
$text['label-call_flow_extension']['pt-br'] = "Ramal";
$text['label-call_flow_extension']['pt-pt'] = "Extensão";
$text['label-call_flow_extension']['ro-ro'] = "";
$text['label-call_flow_extension']['ru-ru'] = "Внутренний номер";
$text['label-call_flow_extension']['sv-se'] = "Anknytning";
$text['label-call_flow_extension']['uk-ua'] = "Розширення (Extention)";

$text['label-call_flow_label']['en-us'] = "Destination Label";
$text['label-call_flow_label']['en-gb'] = "Destination Label";
$text['label-call_flow_label']['ar-eg'] = "";
$text['label-call_flow_label']['de-at'] = "Ziel Kennzeichnung"; //copied from de-de
$text['label-call_flow_label']['de-ch'] = "Ziel Kennzeichnung"; //copied from de-de
$text['label-call_flow_label']['de-de'] = "Ziel Kennzeichnung";
$text['label-call_flow_label']['es-cl'] = "Etiqueta de Destino";
$text['label-call_flow_label']['es-mx'] = "Etiqueta de Destino"; //copied from es-cl
$text['label-call_flow_label']['fr-ca'] = "Label de la destination"; //copied from fr-fr
$text['label-call_flow_label']['fr-fr'] = "Label de la destination";
$text['label-call_flow_label']['he-il'] = "";
$text['label-call_flow_label']['it-it'] = "";
$text['label-call_flow_label']['nl-nl'] = "Bestemmingskenmerk";
$text['label-call_flow_label']['pl-pl'] = "Etykieta destynacji";
$text['label-call_flow_label']['pt-br'] = "Etiqueta de destino";
$text['label-call_flow_label']['pt-pt'] = "Destino";
$text['label-call_flow_label']['ro-ro'] = "";
$text['label-call_flow_label']['ru-ru'] = "Название направления";
$text['label-call_flow_label']['sv-se'] = "Destination Etikett";
$text['label-call_flow_label']['uk-ua'] = "призначення етикетки";

$text['label-call_flow_destination']['en-us'] = "Destination";
$text['label-call_flow_destination']['en-gb'] = "Destination";
$text['label-call_flow_destination']['ar-eg'] = "";
$text['label-call_flow_destination']['de-at'] = "Ziel"; //copied from de-de
$text['label-call_flow_destination']['de-ch'] = "Ziel"; //copied from de-de
$text['label-call_flow_destination']['de-de'] = "Ziel";
$text['label-call_flow_destination']['es-cl'] = "Destino";
$text['label-call_flow_destination']['es-mx'] = "Destino"; //copied from es-cl
$text['label-call_flow_destination']['fr-ca'] = "Destination"; //copied from fr-fr
$text['label-call_flow_destination']['fr-fr'] = "Destination";
$text['label-call_flow_destination']['he-il'] = "";
$text['label-call_flow_destination']['it-it'] = "";
$text['label-call_flow_destination']['nl-nl'] = "Bestemming";
$text['label-call_flow_destination']['pl-pl'] = "Destynacja";
$text['label-call_flow_destination']['pt-br'] = "Número de destino";
$text['label-call_flow_destination']['pt-pt'] = "Destino";
$text['label-call_flow_destination']['ro-ro'] = "";
$text['label-call_flow_destination']['ru-ru'] = "Направление";
$text['label-call_flow_destination']['sv-se'] = "Destination";
$text['label-call_flow_destination']['uk-ua'] = "Номер";

$text['label-call_flow_context']['en-us'] = "Context";
$text['label-call_flow_context']['en-gb'] = "Context";
$text['label-call_flow_context']['ar-eg'] = "";
$text['label-call_flow_context']['de-at'] = "Kontext"; //copied from de-de
$text['label-call_flow_context']['de-ch'] = "Kontext"; //copied from de-de
$text['label-call_flow_context']['de-de'] = "Kontext";
$text['label-call_flow_context']['es-cl'] = "Contexto";
$text['label-call_flow_context']['es-mx'] = "Contexto"; //copied from es-cl
$text['label-call_flow_context']['fr-ca'] = "Contexte"; //copied from fr-fr
$text['label-call_flow_context']['fr-fr'] = "Contexte";
$text['label-call_flow_context']['he-il'] = "";
$text['label-call_flow_context']['it-it'] = "";
$text['label-call_flow_context']['nl-nl'] = "Context";
$text['label-call_flow_context']['pl-pl'] = "Kontekst";
$text['label-call_flow_context']['pt-br'] = "Contexto"; //copied from pt-pt
$text['label-call_flow_context']['pt-pt'] = "Contexto";
$text['label-call_flow_context']['ro-ro'] = "";
$text['label-call_flow_context']['ru-ru'] = "Контекст";
$text['label-call_flow_context']['sv-se'] = "Context";
$text['label-call_flow_context']['uk-ua'] = "Контекст";

$text['label-call_flow_alternate_label']['en-us'] = "Alternate Label";
$text['label-call_flow_alternate_label']['en-gb'] = "Alternate Label";
$text['label-call_flow_alternate_label']['ar-eg'] = "";
$text['label-call_flow_alternate_label']['de-at'] = "Alternative Bezeichnung"; //copied from de-de
$text['label-call_flow_alternate_label']['de-ch'] = "Alternative Bezeichnung"; //copied from de-de
$text['label-call_flow_alternate_label']['de-de'] = "Alternative Bezeichnung";
$text['label-call_flow_alternate_label']['es-cl'] = "Etiqueta alternativa";
$text['label-call_flow_alternate_label']['es-mx'] = "Etiqueta alternativa"; //copied from es-cl
$text['label-call_flow_alternate_label']['fr-ca'] = "Label alternatif"; //copied from fr-fr
$text['label-call_flow_alternate_label']['fr-fr'] = "Label alternatif";
$text['label-call_flow_alternate_label']['he-il'] = "";
$text['label-call_flow_alternate_label']['it-it'] = "";
$text['label-call_flow_alternate_label']['nl-nl'] = "Alternatief kenmerk";
$text['label-call_flow_alternate_label']['pl-pl'] = "Alternatywna etykieta";
$text['label-call_flow_alternate_label']['pt-br'] = "Etqueta alternativa";
$text['label-call_flow_alternate_label']['pt-pt'] = "Etiqueta Alternativa";
$text['label-call_flow_alternate_label']['ro-ro'] = "";
$text['label-call_flow_alternate_label']['ru-ru'] = "Название альтернативного направления";
$text['label-call_flow_alternate_label']['sv-se'] = "Alternativ Etikett";
$text['label-call_flow_alternate_label']['uk-ua'] = "альтернативні етикетки";

$text['label-call_flow_alternate_destination']['en-us'] = "Alternate Destination";
$text['label-call_flow_alternate_destination']['en-gb'] = "Alternate Destination";
$text['label-call_flow_alternate_destination']['ar-eg'] = "";
$text['label-call_flow_alternate_destination']['de-at'] = "Alternatives Ziel"; //copied from de-de
$text['label-call_flow_alternate_destination']['de-ch'] = "Alternatives Ziel"; //copied from de-de
$text['label-call_flow_alternate_destination']['de-de'] = "Alternatives Ziel";
$text['label-call_flow_alternate_destination']['es-cl'] = "Destino Alternativo";
$text['label-call_flow_alternate_destination']['es-mx'] = "Destino Alternativo"; //copied from es-cl
$text['label-call_flow_alternate_destination']['fr-ca'] = "Destination alternative"; //copied from fr-fr
$text['label-call_flow_alternate_destination']['fr-fr'] = "Destination alternative";
$text['label-call_flow_alternate_destination']['he-il'] = "";
$text['label-call_flow_alternate_destination']['it-it'] = "";
$text['label-call_flow_alternate_destination']['nl-nl'] = "Alternatieve bestemming";
$text['label-call_flow_alternate_destination']['pl-pl'] = "Alternatywna destynacja";
$text['label-call_flow_alternate_destination']['pt-br'] = "Destino alternativo";
$text['label-call_flow_alternate_destination']['pt-pt'] = "Destino Alternativo";
$text['label-call_flow_alternate_destination']['ro-ro'] = "";
$text['label-call_flow_alternate_destination']['ru-ru'] = "Альтернативное направление";
$text['label-call_flow_alternate_destination']['sv-se'] = "Alternativ Destination";
$text['label-call_flow_alternate_destination']['uk-ua'] = "альтернативні варіанти призначення";

$text['label-call_flow_sound']['en-us'] = "Sound";
$text['label-call_flow_sound']['en-gb'] = "Sound";
$text['label-call_flow_sound']['ar-eg'] = "";
$text['label-call_flow_sound']['de-at'] = "Rufton"; //copied from de-de
$text['label-call_flow_sound']['de-ch'] = "Rufton"; //copied from de-de
$text['label-call_flow_sound']['de-de'] = "Rufton";
$text['label-call_flow_sound']['es-cl'] = "Sonar";
$text['label-call_flow_sound']['es-mx'] = "Sonar"; //copied from es-cl
$text['label-call_flow_sound']['fr-ca'] = "Sonner"; //copied from fr-fr
$text['label-call_flow_sound']['fr-fr'] = "Sonner";
$text['label-call_flow_sound']['he-il'] = "";
$text['label-call_flow_sound']['it-it'] = "";
$text['label-call_flow_sound']['nl-nl'] = "Geluid";
$text['label-call_flow_sound']['pl-pl'] = "Dźwięk";
$text['label-call_flow_sound']['pt-br'] = "Som"; //copied from pt-pt
$text['label-call_flow_sound']['pt-pt'] = "Som";
$text['label-call_flow_sound']['ro-ro'] = "";
$text['label-call_flow_sound']['ru-ru'] = "Звук";
$text['label-call_flow_sound']['sv-se'] = "Ljud";
$text['label-call_flow_sound']['uk-ua'] = "звук";

$text['label-call_flow_alternate_sound']['en-us'] = "Alternate Sound";
$text['label-call_flow_alternate_sound']['en-gb'] = "Alternate Sound";
$text['label-call_flow_alternate_sound']['ar-eg'] = "";
$text['label-call_flow_alternate_sound']['de-at'] = "Alternativer Rufton"; //copied from de-de
$text['label-call_flow_alternate_sound']['de-ch'] = "Alternativer Rufton"; //copied from de-de
$text['label-call_flow_alternate_sound']['de-de'] = "Alternativer Rufton";
$text['label-call_flow_alternate_sound']['es-cl'] = "sonido alternativo";
$text['label-call_flow_alternate_sound']['es-mx'] = "sonido alternativo"; //copied from es-cl
$text['label-call_flow_alternate_sound']['fr-ca'] = "son suppléant"; //copied from fr-fr
$text['label-call_flow_alternate_sound']['fr-fr'] = "son suppléant";
$text['label-call_flow_alternate_sound']['he-il'] = "";
$text['label-call_flow_alternate_sound']['it-it'] = "";
$text['label-call_flow_alternate_sound']['nl-nl'] = "Alternatief geluid";
$text['label-call_flow_alternate_sound']['pl-pl'] = "Alternatywny dźwięk";
$text['label-call_flow_alternate_sound']['pt-br'] = "Som alternativo";
$text['label-call_flow_alternate_sound']['pt-pt'] = "som alternativo";
$text['label-call_flow_alternate_sound']['ro-ro'] = "";
$text['label-call_flow_alternate_sound']['ru-ru'] = "Альтернативный звук";
$text['label-call_flow_alternate_sound']['sv-se'] = "alternativt ljud";
$text['label-call_flow_alternate_sound']['uk-ua'] = "альтернативний звук";

$text['label-call_flow_description']['en-us'] = "Description";
$text['label-call_flow_description']['en-gb'] = "Description";
$text['label-call_flow_description']['ar-eg'] = "";
$text['label-call_flow_description']['de-at'] = "Beschreibung"; //copied from de-de
$text['label-call_flow_description']['de-ch'] = "Beschreibung"; //copied from de-de
$text['label-call_flow_description']['de-de'] = "Beschreibung";
$text['label-call_flow_description']['es-cl'] = "Descripción";
$text['label-call_flow_description']['es-mx'] = "Descripción"; //copied from es-cl
$text['label-call_flow_description']['fr-ca'] = "Description"; //copied from fr-fr
$text['label-call_flow_description']['fr-fr'] = "Description";
$text['label-call_flow_description']['he-il'] = "";
$text['label-call_flow_description']['it-it'] = "";
$text['label-call_flow_description']['nl-nl'] = "Omschrijving";
$text['label-call_flow_description']['pl-pl'] = "Opis";
$text['label-call_flow_description']['pt-br'] = "Descrição";
$text['label-call_flow_description']['pt-pt'] = "Descripção";
$text['label-call_flow_description']['ro-ro'] = "";
$text['label-call_flow_description']['ru-ru'] = "Описание";
$text['label-call_flow_description']['sv-se'] = "Beskrivning";
$text['label-call_flow_description']['uk-ua'] = "Опис";

$text['header-call_flows']['en-us'] = "Call Flows";
$text['header-call_flows']['en-gb'] = "Call Flows";
$text['header-call_flows']['ar-eg'] = "";
$text['header-call_flows']['de-at'] = "Anruf Steuerung"; //copied from de-de
$text['header-call_flows']['de-ch'] = "Anruf Steuerung"; //copied from de-de
$text['header-call_flows']['de-de'] = "Anruf Steuerung";
$text['header-call_flows']['es-cl'] = "flujo de Llamada";
$text['header-call_flows']['es-mx'] = "flujo de Llamada"; //copied from es-cl
$text['header-call_flows']['fr-ca'] = "Flux d'appel"; //copied from fr-fr
$text['header-call_flows']['fr-fr'] = "Flux d'appel";
$text['header-call_flows']['he-il'] = "";
$text['header-call_flows']['it-it'] = "Deviatori di Chiamata";
$text['header-call_flows']['nl-nl'] = "Oproep besturing";
$text['header-call_flows']['pl-pl'] = "Przepływ rozmów";
$text['header-call_flows']['pt-br'] = "Fluxo de chamadas";
$text['header-call_flows']['pt-pt'] = "Fluxo de Chamadas";
$text['header-call_flows']['ro-ro'] = "";
$text['header-call_flows']['ru-ru'] = "Переключатель вызовов";
$text['header-call_flows']['sv-se'] = "Samtalsflöden";
$text['header-call_flows']['uk-ua'] = "Потоки дзвінків";

$text['header-call_flow']['en-us'] = "Call Flow";
$text['header-call_flow']['en-gb'] = "Call Flow";
$text['header-call_flow']['ar-eg'] = "";
$text['header-call_flow']['de-at'] = "Anruf Steuerung"; //copied from de-de
$text['header-call_flow']['de-ch'] = "Anruf Steuerung"; //copied from de-de
$text['header-call_flow']['de-de'] = "Anruf Steuerung";
$text['header-call_flow']['es-cl'] = "Flujo de Llamada";
$text['header-call_flow']['es-mx'] = "Flujo de Llamada"; //copied from es-cl
$text['header-call_flow']['fr-ca'] = "Editer le flux"; //copied from fr-fr
$text['header-call_flow']['fr-fr'] = "Editer le flux";
$text['header-call_flow']['he-il'] = "";
$text['header-call_flow']['it-it'] = "";
$text['header-call_flow']['nl-nl'] = "Oproep besturing";
$text['header-call_flow']['pl-pl'] = "Przepływ rozmów";
$text['header-call_flow']['pt-br'] = "Fluxo de chamada";
$text['header-call_flow']['pt-pt'] = "Fluxo de Chamada";
$text['header-call_flow']['ro-ro'] = "";
$text['header-call_flow']['ru-ru'] = "Переключатель вызовов";
$text['header-call_flow']['sv-se'] = "Samtalsflöde";
$text['header-call_flow']['uk-ua'] = "Потік дзвінка";

$text['description-call_flow_status']['en-us'] = "Select the status.";
$text['description-call_flow_status']['en-gb'] = "Select the status.";
$text['description-call_flow_status']['ar-eg'] = "";
$text['description-call_flow_status']['de-at'] = "Status festlegen."; //copied from de-de
$text['description-call_flow_status']['de-ch'] = "Status festlegen."; //copied from de-de
$text['description-call_flow_status']['de-de'] = "Status festlegen.";
$text['description-call_flow_status']['es-cl'] = "Seleccione el estado.";
$text['description-call_flow_status']['es-mx'] = "Seleccione el estado."; //copied from es-cl
$text['description-call_flow_status']['fr-ca'] = "Choisir le statut."; //copied from fr-fr
$text['description-call_flow_status']['fr-fr'] = "Choisir le statut.";
$text['description-call_flow_status']['he-il'] = "";
$text['description-call_flow_status']['it-it'] = "";
$text['description-call_flow_status']['nl-nl'] = "Kies de status";
$text['description-call_flow_status']['pl-pl'] = "Wybierz status użytkownika";
$text['description-call_flow_status']['pt-br'] = "Escolha o estado.";
$text['description-call_flow_status']['pt-pt'] = "Seleccione o estado.";
$text['description-call_flow_status']['ro-ro'] = "";
$text['description-call_flow_status']['ru-ru'] = "Виберите состояние.";
$text['description-call_flow_status']['sv-se'] = "Välj Status";
$text['description-call_flow_status']['uk-ua'] = "Виберіть статус користувача";

$text['description-call_flow_pin_number']['en-us'] = "Enter the pin number.";
$text['description-call_flow_pin_number']['en-gb'] = "Enter the pin number.";
$text['description-call_flow_pin_number']['ar-eg'] = "";
$text['description-call_flow_pin_number']['de-at'] = "Geben Sie eine PIN ein."; //copied from de-de
$text['description-call_flow_pin_number']['de-ch'] = "Geben Sie eine PIN ein."; //copied from de-de
$text['description-call_flow_pin_number']['de-de'] = "Geben Sie eine PIN ein.";
$text['description-call_flow_pin_number']['es-cl'] = "Ingrese el número PIN.";
$text['description-call_flow_pin_number']['es-mx'] = "Ingrese el número PIN."; //copied from es-cl
$text['description-call_flow_pin_number']['fr-ca'] = "Choisir le code PIN."; //copied from fr-fr
$text['description-call_flow_pin_number']['fr-fr'] = "Choisir le code PIN.";
$text['description-call_flow_pin_number']['he-il'] = "";
$text['description-call_flow_pin_number']['it-it'] = "";
$text['description-call_flow_pin_number']['nl-nl'] = "Voer de PIN code in.";
$text['description-call_flow_pin_number']['pl-pl'] = "Wprowadź numer PIN";
$text['description-call_flow_pin_number']['pt-br'] = "Insira o código PIN.";
$text['description-call_flow_pin_number']['pt-pt'] = "Introduza o código PIN";
$text['description-call_flow_pin_number']['ro-ro'] = "";
$text['description-call_flow_pin_number']['ru-ru'] = "Введите пин-код.";
$text['description-call_flow_pin_number']['sv-se'] = "Ange PIN Kod.";
$text['description-call_flow_pin_number']['uk-ua'] = "Введіть пін - код.";

$text['description-call_flow_name']['en-us'] = "Enter the name.";
$text['description-call_flow_name']['en-gb'] = "Enter the name.";
$text['description-call_flow_name']['ar-eg'] = "";
$text['description-call_flow_name']['de-at'] = "Geben Sie den Namen an"; //copied from de-de
$text['description-call_flow_name']['de-ch'] = "Geben Sie den Namen an"; //copied from de-de
$text['description-call_flow_name']['de-de'] = "Geben Sie den Namen an";
$text['description-call_flow_name']['es-cl'] = "Ingrese el nombre.";
$text['description-call_flow_name']['es-mx'] = "Ingrese el nombre."; //copied from es-cl
$text['description-call_flow_name']['fr-ca'] = "Choisir le nom."; //copied from fr-fr
$text['description-call_flow_name']['fr-fr'] = "Choisir le nom.";
$text['description-call_flow_name']['he-il'] = "";
$text['description-call_flow_name']['it-it'] = "";
$text['description-call_flow_name']['nl-nl'] = "Voer de naam in.";
$text['description-call_flow_name']['pl-pl'] = "Wprowadź nazwę";
$text['description-call_flow_name']['pt-br'] = "Insira o nome.";
$text['description-call_flow_name']['pt-pt'] = "Introduza o nome.";
$text['description-call_flow_name']['ro-ro'] = "";
$text['description-call_flow_name']['ru-ru'] = "Введите имя.";
$text['description-call_flow_name']['sv-se'] = "Ange Namn.";
$text['description-call_flow_name']['uk-ua'] = "Введіть назву меню";

$text['description-call_flow_feature_code']['en-us'] = "Enter the feature code.";
$text['description-call_flow_feature_code']['en-gb'] = "Enter the feature code.";
$text['description-call_flow_feature_code']['ar-eg'] = "";
$text['description-call_flow_feature_code']['de-at'] = "Geben Sie den Funktions-Code an."; //copied from de-de
$text['description-call_flow_feature_code']['de-ch'] = "Geben Sie den Funktions-Code an."; //copied from de-de
$text['description-call_flow_feature_code']['de-de'] = "Geben Sie den Funktions-Code an.";
$text['description-call_flow_feature_code']['es-cl'] = "Ingrese el código distintivo.";
$text['description-call_flow_feature_code']['es-mx'] = "Ingrese el código distintivo."; //copied from es-cl
$text['description-call_flow_feature_code']['fr-ca'] = "Choisir le code la fonction"; //copied from fr-fr
$text['description-call_flow_feature_code']['fr-fr'] = "Choisir le code la fonction";
$text['description-call_flow_feature_code']['he-il'] = "";
$text['description-call_flow_feature_code']['it-it'] = "";
$text['description-call_flow_feature_code']['nl-nl'] = "Voer de functie-code in";
$text['description-call_flow_feature_code']['pl-pl'] = "Dodaj specjalny kod";
$text['description-call_flow_feature_code']['pt-br'] = "Insira o código de função.";
$text['description-call_flow_feature_code']['pt-pt'] = "Introduza o código de função.";
$text['description-call_flow_feature_code']['ro-ro'] = "";
$text['description-call_flow_feature_code']['ru-ru'] = "Введите код функции.";
$text['description-call_flow_feature_code']['sv-se'] = "Ange Funktionskoden.";
$text['description-call_flow_feature_code']['uk-ua'] = "Введіть код об'єкта.";

$text['description-call_flow_extension']['en-us'] = "Enter the extension number.";
$text['description-call_flow_extension']['en-gb'] = "Enter the extension number.";
$text['description-call_flow_extension']['ar-eg'] = "";
$text['description-call_flow_extension']['de-at'] = "Weisen Sie die Nebenstelle aus."; //copied from de-de
$text['description-call_flow_extension']['de-ch'] = "Weisen Sie die Nebenstelle aus."; //copied from de-de
$text['description-call_flow_extension']['de-de'] = "Weisen Sie die Nebenstelle aus.";
$text['description-call_flow_extension']['es-cl'] = "Ingrese el número de extensión.";
$text['description-call_flow_extension']['es-mx'] = "Ingrese el número de extensión."; //copied from es-cl
$text['description-call_flow_extension']['fr-ca'] = "Choisir le numéro d'extension."; //copied from fr-fr
$text['description-call_flow_extension']['fr-fr'] = "Choisir le numéro d'extension.";
$text['description-call_flow_extension']['he-il'] = "";
$text['description-call_flow_extension']['it-it'] = "";
$text['description-call_flow_extension']['nl-nl'] = "Voer het toestelnummer in";
$text['description-call_flow_extension']['pl-pl'] = "Wprowadź alfanumeryczny numer wewnętrzny. Domyślna konfiguracja pozwala na 2-7 cyfrowe  numery wewnętrzne";
$text['description-call_flow_extension']['pt-br'] = "Atribua o número de ramal.";
$text['description-call_flow_extension']['pt-pt'] = "Introduza o número da extensão.";
$text['description-call_flow_extension']['ro-ro'] = "";
$text['description-call_flow_extension']['ru-ru'] = "Введите внутренний номер.";
$text['description-call_flow_extension']['sv-se'] = "Ange anknytningsnumret.";
$text['description-call_flow_extension']['uk-ua'] = "Введіть номер розширення.";

$text['description-call_flow_destination_label']['en-us'] = "Enter the destination label.";
$text['description-call_flow_destination_label']['en-gb'] = "Enter the destination label.";
$text['description-call_flow_destination_label']['ar-eg'] = "";
$text['description-call_flow_destination_label']['de-at'] = "Geben Sie eine Beschreibung für das Ziel an."; //copied from de-de
$text['description-call_flow_destination_label']['de-ch'] = "Geben Sie eine Beschreibung für das Ziel an."; //copied from de-de
$text['description-call_flow_destination_label']['de-de'] = "Geben Sie eine Beschreibung für das Ziel an.";
$text['description-call_flow_destination_label']['es-cl'] = "Ingrese la etiqueta de destino.";
$text['description-call_flow_destination_label']['es-mx'] = "Ingrese la etiqueta de destino."; //copied from es-cl
$text['description-call_flow_destination_label']['fr-ca'] = "Choisir le label de la destination."; //copied from fr-fr
$text['description-call_flow_destination_label']['fr-fr'] = "Choisir le label de la destination.";
$text['description-call_flow_destination_label']['he-il'] = "";
$text['description-call_flow_destination_label']['it-it'] = "";
$text['description-call_flow_destination_label']['nl-nl'] = "Voer het bestemmingskenmerk in.";
$text['description-call_flow_destination_label']['pl-pl'] = "Wprowadź opis destynacji";
$text['description-call_flow_destination_label']['pt-br'] = "Insira o destino.";
$text['description-call_flow_destination_label']['pt-pt'] = "Introduza o destino.";
$text['description-call_flow_destination_label']['ro-ro'] = "";
$text['description-call_flow_destination_label']['ru-ru'] = "Введите название направления.";
$text['description-call_flow_destination_label']['sv-se'] = "Ange Destinations Etiketten.";
$text['description-call_flow_destination_label']['uk-ua'] = "Введіть мітку призначення.";

$text['description-call_flow_destination']['en-us'] = "Select the destination.";
$text['description-call_flow_destination']['en-gb'] = "Select the destination.";
$text['description-call_flow_destination']['ar-eg'] = "";
$text['description-call_flow_destination']['de-at'] = "Wählen Sie das Ziel."; //copied from de-de
$text['description-call_flow_destination']['de-ch'] = "Wählen Sie das Ziel."; //copied from de-de
$text['description-call_flow_destination']['de-de'] = "Wählen Sie das Ziel.";
$text['description-call_flow_destination']['es-cl'] = "Seleccione el destino.";
$text['description-call_flow_destination']['es-mx'] = "Seleccione el destino."; //copied from es-cl
$text['description-call_flow_destination']['fr-ca'] = "Choisir la destination."; //copied from fr-fr
$text['description-call_flow_destination']['fr-fr'] = "Choisir la destination.";
$text['description-call_flow_destination']['he-il'] = "";
$text['description-call_flow_destination']['it-it'] = "";
$text['description-call_flow_destination']['nl-nl'] = "Voer de bestemming in.";
$text['description-call_flow_destination']['pl-pl'] = "Wybierz numer docelowy.";
$text['description-call_flow_destination']['pt-br'] = "Selecionar o destino da chamada.";
$text['description-call_flow_destination']['pt-pt'] = "Seleccione o destino.";
$text['description-call_flow_destination']['ro-ro'] = "";
$text['description-call_flow_destination']['ru-ru'] = "Выберите назначение.";
$text['description-call_flow_destination']['sv-se'] = "Välj destinationen.";
$text['description-call_flow_destination']['uk-ua'] = "Відправити дзвінок на розширення, меню IVR, конференцію, або будь-який інший номер.";

$text['description-call_flow_context']['en-us'] = "Enter the context.";
$text['description-call_flow_context']['en-gb'] = "Enter the context.";
$text['description-call_flow_context']['ar-eg'] = "";
$text['description-call_flow_context']['de-at'] = "Geben Sie den Kontext hier an."; //copied from de-de
$text['description-call_flow_context']['de-ch'] = "Geben Sie den Kontext hier an."; //copied from de-de
$text['description-call_flow_context']['de-de'] = "Geben Sie den Kontext hier an.";
$text['description-call_flow_context']['es-cl'] = "Ingrese el contexto.";
$text['description-call_flow_context']['es-mx'] = "Ingrese el contexto."; //copied from es-cl
$text['description-call_flow_context']['fr-ca'] = "Choisir le contexte."; //copied from fr-fr
$text['description-call_flow_context']['fr-fr'] = "Choisir le contexte.";
$text['description-call_flow_context']['he-il'] = "";
$text['description-call_flow_context']['it-it'] = "";
$text['description-call_flow_context']['nl-nl'] = "Voer de Context in.";
$text['description-call_flow_context']['pl-pl'] = "Wprowadź kontekst";
$text['description-call_flow_context']['pt-br'] = "Insira o contexto.";
$text['description-call_flow_context']['pt-pt'] = "Introduza o contexto";
$text['description-call_flow_context']['ro-ro'] = "";
$text['description-call_flow_context']['ru-ru'] = "Введите контекст.";
$text['description-call_flow_context']['sv-se'] = "Ange Context.";
$text['description-call_flow_context']['uk-ua'] = "Введіть контекст.";

$text['description-call_flows']['en-us'] = "Direct calls between two destinations by calling a feature code.";
$text['description-call_flows']['en-gb'] = "Direct calls between two destinations by calling a feature code.";
$text['description-call_flows']['ar-eg'] = "";
$text['description-call_flows']['de-at'] = "Leiten Sie Anrufe zwischen zwei Zielen um indem Sie einen Funktions-Code wählen."; //copied from de-de
$text['description-call_flows']['de-ch'] = "Leiten Sie Anrufe zwischen zwei Zielen um indem Sie einen Funktions-Code wählen."; //copied from de-de
$text['description-call_flows']['de-de'] = "Leiten Sie Anrufe zwischen zwei Zielen um indem Sie einen Funktions-Code wählen.";
$text['description-call_flows']['es-cl'] = "Llamadas directas entre dos destinatarios llamando a un código distintivo.";
$text['description-call_flows']['es-mx'] = "Llamadas directas entre dos destinatarios llamando a un código distintivo."; //copied from es-cl
$text['description-call_flows']['fr-ca'] = "Appels directs entre deux destinations en appelant une fonction."; //copied from fr-fr
$text['description-call_flows']['fr-fr'] = "Appels directs entre deux destinations en appelant une fonction.";
$text['description-call_flows']['he-il'] = "";
$text['description-call_flows']['it-it'] = "Devia le chiamate tra due destinazioni chiamando un codice di attivazione.";
$text['description-call_flows']['nl-nl'] = "Direkte oproepen tussen tw bestemmingen via een functie-code.";
$text['description-call_flows']['pl-pl'] = "Kieruj rozmowy bezpośrednio pomiędzy dwoma destynacjami poprzez prowadzenie specjalnego kodu.";
$text['description-call_flows']['pt-br'] = "Chamadas diretas para dois dispositivos utilizando o código de função.";
$text['description-call_flows']['pt-pt'] = "Chamadas directas entre dois destinos recorrendo a um código de função.";
$text['description-call_flows']['ro-ro'] = "";
$text['description-call_flows']['ru-ru'] = "Переключите вызовы между двумя направлениями с помощью кода дополнительного вида обслуживания.";
$text['description-call_flows']['sv-se'] = "Samtal mellan två destinationer genom att ringa en funktionskod.";
$text['description-call_flows']['uk-ua'] = "Прямі виклики між двома пунктами шляхом виклику коду функції.";

$text['description-call_flow_alternate_label']['en-us'] = "Enter the alternate destination label.";
$text['description-call_flow_alternate_label']['en-gb'] = "Enter the alternate destination label.";
$text['description-call_flow_alternate_label']['ar-eg'] = "";
$text['description-call_flow_alternate_label']['de-at'] = "Geben Sie eine Beschreibung für das alternative Ziel ein."; //copied from de-de
$text['description-call_flow_alternate_label']['de-ch'] = "Geben Sie eine Beschreibung für das alternative Ziel ein."; //copied from de-de
$text['description-call_flow_alternate_label']['de-de'] = "Geben Sie eine Beschreibung für das alternative Ziel ein.";
$text['description-call_flow_alternate_label']['es-cl'] = "Ingrese la etiqueta de destino alternativo.";
$text['description-call_flow_alternate_label']['es-mx'] = "Ingrese la etiqueta de destino alternativo."; //copied from es-cl
$text['description-call_flow_alternate_label']['fr-ca'] = "Choisir le label de la destination alternative."; //copied from fr-fr
$text['description-call_flow_alternate_label']['fr-fr'] = "Choisir le label de la destination alternative.";
$text['description-call_flow_alternate_label']['he-il'] = "";
$text['description-call_flow_alternate_label']['it-it'] = "";
$text['description-call_flow_alternate_label']['nl-nl'] = "Voer alternatieve bestemmingskenmerk in";
$text['description-call_flow_alternate_label']['pl-pl'] = "Wprowadź alternatywny opis destynacji";
$text['description-call_flow_alternate_label']['pt-br'] = "Insira um destino alternativo.";
$text['description-call_flow_alternate_label']['pt-pt'] = "Introduza um destino alternativo.";
$text['description-call_flow_alternate_label']['ro-ro'] = "";
$text['description-call_flow_alternate_label']['ru-ru'] = "Введите название альтернативного направления.";
$text['description-call_flow_alternate_label']['sv-se'] = "Ange den alternativa destinations etiketten.";
$text['description-call_flow_alternate_label']['uk-ua'] = "Введіть альтернативний ярлик призначення.";

$text['description-call_flow_alternate_destination']['en-us'] = "Select the alternate destination.";
$text['description-call_flow_alternate_destination']['en-gb'] = "Select the alternate destination.";
$text['description-call_flow_alternate_destination']['ar-eg'] = "";
$text['description-call_flow_alternate_destination']['de-at'] = "Wählen Sie ein alternatives Ziel."; //copied from de-de
$text['description-call_flow_alternate_destination']['de-ch'] = "Wählen Sie ein alternatives Ziel."; //copied from de-de
$text['description-call_flow_alternate_destination']['de-de'] = "Wählen Sie ein alternatives Ziel.";
$text['description-call_flow_alternate_destination']['es-cl'] = "Seleccione el destino alternativo.";
$text['description-call_flow_alternate_destination']['es-mx'] = "Seleccione el destino alternativo."; //copied from es-cl
$text['description-call_flow_alternate_destination']['fr-ca'] = "Choisir la destination alternative."; //copied from fr-fr
$text['description-call_flow_alternate_destination']['fr-fr'] = "Choisir la destination alternative.";
$text['description-call_flow_alternate_destination']['he-il'] = "";
$text['description-call_flow_alternate_destination']['it-it'] = "";
$text['description-call_flow_alternate_destination']['nl-nl'] = "Kies alternatieve bestemming.";
$text['description-call_flow_alternate_destination']['pl-pl'] = "Wybierz alternatywną destynację";
$text['description-call_flow_alternate_destination']['pt-br'] = "Selecione um destino alternativo.";
$text['description-call_flow_alternate_destination']['pt-pt'] = "Seleccione um destino alternativo.";
$text['description-call_flow_alternate_destination']['ro-ro'] = "";
$text['description-call_flow_alternate_destination']['ru-ru'] = "Выберите альтернативное направление.";
$text['description-call_flow_alternate_destination']['sv-se'] = "Välj den alternativa destinationen.";
$text['description-call_flow_alternate_destination']['uk-ua'] = "Виберіть інше розташування.";

$text['description-call_flow_sound']['en-us'] = "Select the sound to play when the status is set to the destinations.";
$text['description-call_flow_sound']['en-gb'] = "Select the sound to play when the status is set to the destinations.";
$text['description-call_flow_sound']['ar-eg'] = "";
$text['description-call_flow_sound']['de-at'] = "Wählen Sie den zu spielenden Rufton aus, wenn das primäre Ziel ausgewählt ist."; //copied from de-de
$text['description-call_flow_sound']['de-ch'] = "Wählen Sie den zu spielenden Rufton aus, wenn das primäre Ziel ausgewählt ist."; //copied from de-de
$text['description-call_flow_sound']['de-de'] = "Wählen Sie den zu spielenden Rufton aus, wenn das primäre Ziel ausgewählt ist.";
$text['description-call_flow_sound']['es-cl'] = "Seleccione el sonido a reproducir cuando el estado se establece en el destino.";
$text['description-call_flow_sound']['es-mx'] = "Seleccione el sonido a reproducir cuando el estado se establece en el destino."; //copied from es-cl
$text['description-call_flow_sound']['fr-ca'] = "Sélectionnez le son à jouer lorsque l'état est réglé sur la destination."; //copied from fr-fr
$text['description-call_flow_sound']['fr-fr'] = "Sélectionnez le son à jouer lorsque l'état est réglé sur la destination.";
$text['description-call_flow_sound']['he-il'] = "";
$text['description-call_flow_sound']['it-it'] = "";
$text['description-call_flow_sound']['nl-nl'] = "Kies het geluid om af te spelen als status bestemming is. ";
$text['description-call_flow_sound']['pl-pl'] = "Wybierz dźwięk do odtworzenia, gdy status jest ustawiony do miejsca przeznaczenia.";
$text['description-call_flow_sound']['pt-br'] = "Selecione o som para tocar quando o status é definido para o destino.";
$text['description-call_flow_sound']['pt-pt'] = "Selecione o som para tocar quando o status é definido como o destino.";
$text['description-call_flow_sound']['ro-ro'] = "";
$text['description-call_flow_sound']['ru-ru'] = "Выберите звук для воспроизведения, когда состояние устанавливается в пункты назначения.";
$text['description-call_flow_sound']['sv-se'] = "Välj ljud att spela när status är inställd på destinationen.";
$text['description-call_flow_sound']['uk-ua'] = "Виберіть звук для відтворення , коли статус встановлений в пункти призначення.";

$text['description-call_flow_alternate_sound']['en-us'] = "Select the sound to play when status is set to the alternate destination.";
$text['description-call_flow_alternate_sound']['en-gb'] = "Select the sound to play when status is set to the alternate destination.";
$text['description-call_flow_alternate_sound']['ar-eg'] = "";
$text['description-call_flow_alternate_sound']['de-at'] = "Wählen Sie den zu spielenden Rufton aus, wenn das alternative Ziel ausgewählt ist."; //copied from de-de
$text['description-call_flow_alternate_sound']['de-ch'] = "Wählen Sie den zu spielenden Rufton aus, wenn das alternative Ziel ausgewählt ist."; //copied from de-de
$text['description-call_flow_alternate_sound']['de-de'] = "Wählen Sie den zu spielenden Rufton aus, wenn das alternative Ziel ausgewählt ist.";
$text['description-call_flow_alternate_sound']['es-cl'] = "Seleccione el sonido a reproducir cuando el estado se establece en el destino alternativo.";
$text['description-call_flow_alternate_sound']['es-mx'] = "Seleccione el sonido a reproducir cuando el estado se establece en el destino alternativo."; //copied from es-cl
$text['description-call_flow_alternate_sound']['fr-ca'] = "Sélectionnez le son à jouer lorsque l'état est réglé sur la destination alternative."; //copied from fr-fr
$text['description-call_flow_alternate_sound']['fr-fr'] = "Sélectionnez le son à jouer lorsque l'état est réglé sur la destination alternative.";
$text['description-call_flow_alternate_sound']['he-il'] = "";
$text['description-call_flow_alternate_sound']['it-it'] = "";
$text['description-call_flow_alternate_sound']['nl-nl'] = "Kies het geluid om af te spelen als de status alternatieve bestemming is.";
$text['description-call_flow_alternate_sound']['pl-pl'] = "Wybierz dźwięk do odtworzenia, gdy status jest ustawiony na alternatywnego przeznaczenia.";
$text['description-call_flow_alternate_sound']['pt-br'] = "Selecione o som para tocar quando o status é definido para o destino alternativo.";
$text['description-call_flow_alternate_sound']['pt-pt'] = "Selecione o som para tocar quando o status é definido como o destino alternativo.";
$text['description-call_flow_alternate_sound']['ro-ro'] = "";
$text['description-call_flow_alternate_sound']['ru-ru'] = "Выберите звук, который воспроизводится когда статус устанавливается в альтернативное направление.";
$text['description-call_flow_alternate_sound']['sv-se'] = "Välj ljud att spela när status är inställd på den alternativa destinationen.";
$text['description-call_flow_alternate_sound']['uk-ua'] = "Виберіть звук для відтворення , коли встановлено стан альтернативного призначення.";

$text['recordings']['en-us'] = "Recordings";
$text['recordings']['en-gb'] = "Recordings";
$text['recordings']['ar-eg'] = "";
$text['recordings']['de-at'] = "Aufnahmen"; //copied from de-de
$text['recordings']['de-ch'] = "Aufnahmen"; //copied from de-de
$text['recordings']['de-de'] = "Aufnahmen";
$text['recordings']['es-cl'] = "grabaciones";
$text['recordings']['es-mx'] = "grabaciones"; //copied from es-cl
$text['recordings']['fr-ca'] = "Enregistrements d'appels"; //copied from fr-fr
$text['recordings']['fr-fr'] = "Enregistrements d'appels";
$text['recordings']['he-il'] = "";
$text['recordings']['it-it'] = "Registrazioni";
$text['recordings']['nl-nl'] = "Opnamen";
$text['recordings']['pl-pl'] = "nagrania";
$text['recordings']['pt-br'] = "Gravações";
$text['recordings']['pt-pt'] = "gravações";
$text['recordings']['ro-ro'] = "";
$text['recordings']['ru-ru'] = "Записи";
$text['recordings']['sv-se'] = "inspelningar";
$text['recordings']['uk-ua'] = "записи";

$text['miscellaneous']['en-us'] = "Miscellaneous";
$text['miscellaneous']['en-gb'] = "Miscellaneous";
$text['miscellaneous']['ar-eg'] = "";
$text['miscellaneous']['de-at'] = "Sonstiges"; //copied from de-de
$text['miscellaneous']['de-ch'] = "Sonstiges"; //copied from de-de
$text['miscellaneous']['de-de'] = "Sonstiges";
$text['miscellaneous']['es-cl'] = "Diverso";
$text['miscellaneous']['es-mx'] = "Diverso"; //copied from es-cl
$text['miscellaneous']['fr-ca'] = "Divers"; //copied from fr-fr
$text['miscellaneous']['fr-fr'] = "Divers";
$text['miscellaneous']['he-il'] = "";
$text['miscellaneous']['it-it'] = "Varie";
$text['miscellaneous']['nl-nl'] = "Overigen";
$text['miscellaneous']['pl-pl'] = "Różne";
$text['miscellaneous']['pt-br'] = "Diversos";
$text['miscellaneous']['pt-pt'] = "Variado";
$text['miscellaneous']['ro-ro'] = "";
$text['miscellaneous']['ru-ru'] = "Разное";
$text['miscellaneous']['sv-se'] = "Diverse";
$text['miscellaneous']['uk-ua'] = "Різне";

$text['sounds']['en-us'] = "Sounds";
$text['sounds']['en-gb'] = "Sounds";
$text['sounds']['ar-eg'] = "";
$text['sounds']['de-at'] = "Ruftöne"; //copied from de-de
$text['sounds']['de-ch'] = "Ruftöne"; //copied from de-de
$text['sounds']['de-de'] = "Ruftöne";
$text['sounds']['es-cl'] = "Sonidos";
$text['sounds']['es-mx'] = "Sonidos"; //copied from es-cl
$text['sounds']['fr-ca'] = "des sons"; //copied from fr-fr
$text['sounds']['fr-fr'] = "des sons";
$text['sounds']['he-il'] = "";
$text['sounds']['it-it'] = "Audio";
$text['sounds']['nl-nl'] = "Geluiden";
$text['sounds']['pl-pl'] = "Dźwięki";
$text['sounds']['pt-br'] = "Sons"; //copied from pt-pt
$text['sounds']['pt-pt'] = "Sons";
$text['sounds']['ro-ro'] = "";
$text['sounds']['ru-ru'] = "Звуки";
$text['sounds']['sv-se'] = "Ljud";
$text['sounds']['uk-ua'] = "звуки";

?>
