<?php
#This file was last reorganized on 19th of September 2017 08:54:24 AM UTC

$text['title-manage-files']['en-us'] = "Manage Files";
$text['title-manage-files']['ar-eg'] = "";
$text['title-manage-files']['de-at'] = "Dateien verwalten"; //copied from de-de
$text['title-manage-files']['de-ch'] = "Dateien verwalten"; //copied from de-de
$text['title-manage-files']['de-de'] = "Dateien verwalten";
$text['title-manage-files']['es-cl'] = "Gestión de Archivos";
$text['title-manage-files']['es-mx'] = "Gestión de Archivos"; //copied from es-cl
$text['title-manage-files']['fr-ca'] = "Gérer les Fichiers"; //copied from fr-fr
$text['title-manage-files']['fr-fr'] = "Gérer les Fichiers";
$text['title-manage-files']['he-il'] = "";
$text['title-manage-files']['it-it'] = "Gestione Files";
$text['title-manage-files']['nl-nl'] = "";
$text['title-manage-files']['pl-pl'] = "";
$text['title-manage-files']['pt-br'] = "Gerenciar Arquivos"; //copied from pt-pt
$text['title-manage-files']['pt-pt'] = "Gerenciar Arquivos";
$text['title-manage-files']['ro-ro'] = "";
$text['title-manage-files']['ru-ru'] = "Управление файлами";
$text['title-manage-files']['sv-se'] = "Hantera Filer";
$text['title-manage-files']['uk-ua'] = "";

$text['title-manage-clips']['en-us'] = "Manage Clips";
$text['title-manage-clips']['ar-eg'] = "";
$text['title-manage-clips']['de-at'] = "Clips verwalten"; //copied from de-de
$text['title-manage-clips']['de-ch'] = "Clips verwalten"; //copied from de-de
$text['title-manage-clips']['de-de'] = "Clips verwalten";
$text['title-manage-clips']['es-cl'] = "Gestión de Clips";
$text['title-manage-clips']['es-mx'] = "Gestión de Clips"; //copied from es-cl
$text['title-manage-clips']['fr-ca'] = "Gérer les clips"; //copied from fr-fr
$text['title-manage-clips']['fr-fr'] = "Gérer les clips";
$text['title-manage-clips']['he-il'] = "";
$text['title-manage-clips']['it-it'] = "Gestione Clips";
$text['title-manage-clips']['nl-nl'] = "";
$text['title-manage-clips']['pl-pl'] = "";
$text['title-manage-clips']['pt-br'] = "Gerir Clipes"; //copied from pt-pt
$text['title-manage-clips']['pt-pt'] = "Gerir Clipes";
$text['title-manage-clips']['ro-ro'] = "";
$text['title-manage-clips']['ru-ru'] = "Управление клипами";
$text['title-manage-clips']['sv-se'] = "Hantera Klipp";
$text['title-manage-clips']['uk-ua'] = "";

$text['label-folder']['en-us'] = "Folder:";
$text['label-folder']['ar-eg'] = "";
$text['label-folder']['de-at'] = "Ordner:"; //copied from de-de
$text['label-folder']['de-ch'] = "Ordner:"; //copied from de-de
$text['label-folder']['de-de'] = "Ordner:";
$text['label-folder']['es-cl'] = "Carpeta:";
$text['label-folder']['es-mx'] = "Carpeta:"; //copied from es-cl
$text['label-folder']['fr-ca'] = "Dossier:"; //copied from fr-fr
$text['label-folder']['fr-fr'] = "Dossier:";
$text['label-folder']['he-il'] = "";
$text['label-folder']['it-it'] = "Cartella:";
$text['label-folder']['nl-nl'] = "";
$text['label-folder']['pl-pl'] = "";
$text['label-folder']['pt-br'] = "Ficheiro:"; //copied from pt-pt
$text['label-folder']['pt-pt'] = "Ficheiro:";
$text['label-folder']['ro-ro'] = "";
$text['label-folder']['ru-ru'] = "Папка:";
$text['label-folder']['sv-se'] = "Mapp:";
$text['label-folder']['uk-ua'] = "";

$text['label-before-selection']['en-us'] = "Before Selection:";
$text['label-before-selection']['ar-eg'] = "";
$text['label-before-selection']['de-at'] = "Vor der Auswahl:"; //copied from de-de
$text['label-before-selection']['de-ch'] = "Vor der Auswahl:"; //copied from de-de
$text['label-before-selection']['de-de'] = "Vor der Auswahl:";
$text['label-before-selection']['es-cl'] = "Antes de seleccionar:";
$text['label-before-selection']['es-mx'] = "Antes de seleccionar:"; //copied from es-cl
$text['label-before-selection']['fr-ca'] = "Avant la Selection:"; //copied from fr-fr
$text['label-before-selection']['fr-fr'] = "Avant la Selection:";
$text['label-before-selection']['he-il'] = "";
$text['label-before-selection']['it-it'] = "Precedente Selezione:";
$text['label-before-selection']['nl-nl'] = "";
$text['label-before-selection']['pl-pl'] = "";
$text['label-before-selection']['pt-br'] = "Antes da Selecção:"; //copied from pt-pt
$text['label-before-selection']['pt-pt'] = "Antes da Selecção:";
$text['label-before-selection']['ro-ro'] = "";
$text['label-before-selection']['ru-ru'] = "Перед выбором:";
$text['label-before-selection']['sv-se'] = "Före Val:";
$text['label-before-selection']['uk-ua'] = "";

$text['label-after-selection']['en-us'] = "After Selection:";
$text['label-after-selection']['ar-eg'] = "";
$text['label-after-selection']['de-at'] = "Nach der Auswahl:"; //copied from de-de
$text['label-after-selection']['de-ch'] = "Nach der Auswahl:"; //copied from de-de
$text['label-after-selection']['de-de'] = "Nach der Auswahl:";
$text['label-after-selection']['es-cl'] = "Despues de seleccionar:";
$text['label-after-selection']['es-mx'] = "Despues de seleccionar:"; //copied from es-cl
$text['label-after-selection']['fr-ca'] = "Après la Selection:"; //copied from fr-fr
$text['label-after-selection']['fr-fr'] = "Après la Selection:";
$text['label-after-selection']['he-il'] = "";
$text['label-after-selection']['it-it'] = "Successiva Selezione:";
$text['label-after-selection']['nl-nl'] = "";
$text['label-after-selection']['pl-pl'] = "";
$text['label-after-selection']['pt-br'] = "Depois da Selecção:"; //copied from pt-pt
$text['label-after-selection']['pt-pt'] = "Depois da Selecção:";
$text['label-after-selection']['ro-ro'] = "";
$text['label-after-selection']['ru-ru'] = "После выбора:";
$text['label-after-selection']['sv-se'] = "Efter Val:";
$text['label-after-selection']['uk-ua'] = "";

$text['label-notes']['en-us'] = "Notes:";
$text['label-notes']['ar-eg'] = "";
$text['label-notes']['de-at'] = "Notiz:"; //copied from de-de
$text['label-notes']['de-ch'] = "Notiz:"; //copied from de-de
$text['label-notes']['de-de'] = "Notiz:";
$text['label-notes']['es-cl'] = "Notas:";
$text['label-notes']['es-mx'] = "Notas:"; //copied from es-cl
$text['label-notes']['fr-ca'] = "Remarques:"; //copied from fr-fr
$text['label-notes']['fr-fr'] = "Remarques:";
$text['label-notes']['he-il'] = "";
$text['label-notes']['it-it'] = "Note:";
$text['label-notes']['nl-nl'] = "";
$text['label-notes']['pl-pl'] = "";
$text['label-notes']['pt-br'] = "Notas:"; //copied from pt-pt
$text['label-notes']['pt-pt'] = "Notas:";
$text['label-notes']['ro-ro'] = "";
$text['label-notes']['ru-ru'] = "Заметки:";
$text['label-notes']['sv-se'] = "Noteringar:";
$text['label-notes']['uk-ua'] = "";

$text['message-give-up']['en-us'] = "Giving up :( Cannot create an XMLHTTP instance";
$text['message-give-up']['ar-eg'] = "";
$text['message-give-up']['de-at'] = "Vorgang abgebrochen :( Konnte XMLHTTP Instanz nich erzeugen"; //copied from de-de
$text['message-give-up']['de-ch'] = "Vorgang abgebrochen :( Konnte XMLHTTP Instanz nich erzeugen"; //copied from de-de
$text['message-give-up']['de-de'] = "Vorgang abgebrochen :( Konnte XMLHTTP Instanz nich erzeugen";
$text['message-give-up']['es-cl'] = "Cancelando, no se puede crear una instancia XMLHTTP";
$text['message-give-up']['es-mx'] = "Cancelando, no se puede crear una instancia XMLHTTP"; //copied from es-cl
$text['message-give-up']['fr-ca'] = "Abandonner :( Ne peut pas créer un instance XMLHTTP"; //copied from fr-fr
$text['message-give-up']['fr-fr'] = "Abandonner :( Ne peut pas créer un instance XMLHTTP";
$text['message-give-up']['he-il'] = "";
$text['message-give-up']['it-it'] = "Abbandono :( Non riesco a creare un'instanza XMLHTTP";
$text['message-give-up']['nl-nl'] = "";
$text['message-give-up']['pl-pl'] = "";
$text['message-give-up']['pt-br'] = "Desistindo :( Não é possível criar uma instância XMLHTTP"; //copied from pt-pt
$text['message-give-up']['pt-pt'] = "Desistindo :( Não é possível criar uma instância XMLHTTP";
$text['message-give-up']['ro-ro'] = "";
$text['message-give-up']['ru-ru'] = "Операция отменена :( Невозможно создать XMLHTTP экземпляр";
$text['message-give-up']['sv-se'] = "Ger upp :( Kan inte skapa en XMLHTTP instans";
$text['message-give-up']['uk-ua'] = "";

$text['message-problem']['en-us'] = "There was a problem with the request.";
$text['message-problem']['ar-eg'] = "";
$text['message-problem']['de-at'] = "Es gab ein Problem mit der Anfrage."; //copied from de-de
$text['message-problem']['de-ch'] = "Es gab ein Problem mit der Anfrage."; //copied from de-de
$text['message-problem']['de-de'] = "Es gab ein Problem mit der Anfrage.";
$text['message-problem']['es-cl'] = "Hubo un problema con la petición.";
$text['message-problem']['es-mx'] = "Hubo un problema con la petición."; //copied from es-cl
$text['message-problem']['fr-ca'] = "Il y avait un problème avec la demande."; //copied from fr-fr
$text['message-problem']['fr-fr'] = "Il y avait un problème avec la demande.";
$text['message-problem']['he-il'] = "";
$text['message-problem']['it-it'] = "C'è stato un problema con la richiesta.";
$text['message-problem']['nl-nl'] = "";
$text['message-problem']['pl-pl'] = "";
$text['message-problem']['pt-br'] = "Ocorreu um problema com o pedido."; //copied from pt-pt
$text['message-problem']['pt-pt'] = "Ocorreu um problema com o pedido.";
$text['message-problem']['ro-ro'] = "";
$text['message-problem']['ru-ru'] = "Возникла проблема с запросом.";
$text['message-problem']['sv-se'] = "Det uppstod ett problem med begäran.";
$text['message-problem']['uk-ua'] = "";

$text['label-clip-library']['en-us'] = "Clip Library";
$text['label-clip-library']['ar-eg'] = "";
$text['label-clip-library']['de-at'] = "Clip Bibliothek"; //copied from de-de
$text['label-clip-library']['de-ch'] = "Clip Bibliothek"; //copied from de-de
$text['label-clip-library']['de-de'] = "Clip Bibliothek";
$text['label-clip-library']['es-cl'] = "Librería de Clips";
$text['label-clip-library']['es-mx'] = "Librería de Clips"; //copied from es-cl
$text['label-clip-library']['fr-ca'] = "Clip Libraries"; //copied from fr-fr
$text['label-clip-library']['fr-fr'] = "Clip Libraries";
$text['label-clip-library']['he-il'] = "";
$text['label-clip-library']['it-it'] = "Libreria Clip";
$text['label-clip-library']['nl-nl'] = "";
$text['label-clip-library']['pl-pl'] = "";
$text['label-clip-library']['pt-br'] = "Biblioteca de Clips"; //copied from pt-pt
$text['label-clip-library']['pt-pt'] = "Biblioteca de Clips";
$text['label-clip-library']['ro-ro'] = "";
$text['label-clip-library']['ru-ru'] = "Библиотека клипов";
$text['label-clip-library']['sv-se'] = "Klipp Bibliotek";
$text['label-clip-library']['uk-ua'] = "";

$text['label-selected-clip']['en-us'] = "Selected Clip";
$text['label-selected-clip']['ar-eg'] = "";
$text['label-selected-clip']['de-at'] = "Ausgewählter Clip"; //copied from de-de
$text['label-selected-clip']['de-ch'] = "Ausgewählter Clip"; //copied from de-de
$text['label-selected-clip']['de-de'] = "Ausgewählter Clip";
$text['label-selected-clip']['es-cl'] = "Clip Seleccionado";
$text['label-selected-clip']['es-mx'] = "Clip Seleccionado"; //copied from es-cl
$text['label-selected-clip']['fr-ca'] = "Clip Sélectionné"; //copied from fr-fr
$text['label-selected-clip']['fr-fr'] = "Clip Sélectionné";
$text['label-selected-clip']['he-il'] = "";
$text['label-selected-clip']['it-it'] = "Clip Selezionate";
$text['label-selected-clip']['nl-nl'] = "";
$text['label-selected-clip']['pl-pl'] = "";
$text['label-selected-clip']['pt-br'] = "Clipe Selecionado"; //copied from pt-pt
$text['label-selected-clip']['pt-pt'] = "Clipe Selecionado";
$text['label-selected-clip']['ro-ro'] = "";
$text['label-selected-clip']['ru-ru'] = "Выбранный клип";
$text['label-selected-clip']['sv-se'] = "";
$text['label-selected-clip']['uk-ua'] = "";

$text['button-edit-clip']['en-us'] = "Edit Clip";
$text['button-edit-clip']['ar-eg'] = "";
$text['button-edit-clip']['de-at'] = "Clip bearbeiten"; //copied from de-de
$text['button-edit-clip']['de-ch'] = "Clip bearbeiten"; //copied from de-de
$text['button-edit-clip']['de-de'] = "Clip bearbeiten";
$text['button-edit-clip']['es-cl'] = "Editar Clip";
$text['button-edit-clip']['es-mx'] = "Editar Clip"; //copied from es-cl
$text['button-edit-clip']['fr-ca'] = "Editer le Clip"; //copied from fr-fr
$text['button-edit-clip']['fr-fr'] = "Editer le Clip";
$text['button-edit-clip']['he-il'] = "";
$text['button-edit-clip']['it-it'] = "Modifica Clip";
$text['button-edit-clip']['nl-nl'] = "";
$text['button-edit-clip']['pl-pl'] = "";
$text['button-edit-clip']['pt-br'] = "Editar Clip"; //copied from pt-pt
$text['button-edit-clip']['pt-pt'] = "Editar Clip";
$text['button-edit-clip']['ro-ro'] = "";
$text['button-edit-clip']['ru-ru'] = "Редактировать клип";
$text['button-edit-clip']['sv-se'] = "Ändra Klipp";
$text['button-edit-clip']['uk-ua'] = "";

$text['button-add-clip']['en-us'] = "Add Clip";
$text['button-add-clip']['ar-eg'] = "";
$text['button-add-clip']['de-at'] = "Clip hinzufügen"; //copied from de-de
$text['button-add-clip']['de-ch'] = "Clip hinzufügen"; //copied from de-de
$text['button-add-clip']['de-de'] = "Clip hinzufügen";
$text['button-add-clip']['es-cl'] = "Agregar Clip";
$text['button-add-clip']['es-mx'] = "Agregar Clip"; //copied from es-cl
$text['button-add-clip']['fr-ca'] = "Ajouter un Clip"; //copied from fr-fr
$text['button-add-clip']['fr-fr'] = "Ajouter un Clip";
$text['button-add-clip']['he-il'] = "";
$text['button-add-clip']['it-it'] = "Inserisci Clip";
$text['button-add-clip']['nl-nl'] = "";
$text['button-add-clip']['pl-pl'] = "";
$text['button-add-clip']['pt-br'] = "Adicionar Clip"; //copied from pt-pt
$text['button-add-clip']['pt-pt'] = "Adicionar Clip";
$text['button-add-clip']['ro-ro'] = "";
$text['button-add-clip']['ru-ru'] = "Добавить клип";
$text['button-add-clip']['sv-se'] = "Lägg Till Klipp";
$text['button-add-clip']['uk-ua'] = "";

$text['message-delete-clip']['en-us'] = "Are you sure you want to delete the selected clip?";
$text['message-delete-clip']['ar-eg'] = "";
$text['message-delete-clip']['de-at'] = "Sind Sie sicher, dass Sie den ausgewählten Clip löschen möchten?"; //copied from de-de
$text['message-delete-clip']['de-ch'] = "Sind Sie sicher, dass Sie den ausgewählten Clip löschen möchten?"; //copied from de-de
$text['message-delete-clip']['de-de'] = "Sind Sie sicher, dass Sie den ausgewählten Clip löschen möchten?";
$text['message-delete-clip']['es-cl'] = "¿Realmente desea eliminar el clip seleccionado?";
$text['message-delete-clip']['es-mx'] = "¿Realmente desea eliminar el clip seleccionado?"; //copied from es-cl
$text['message-delete-clip']['fr-ca'] = "Etes-vous sûr de vouloir supprimer le CLIP sélectionné?"; //copied from fr-fr
$text['message-delete-clip']['fr-fr'] = "Etes-vous sûr de vouloir supprimer le CLIP sélectionné?";
$text['message-delete-clip']['he-il'] = "";
$text['message-delete-clip']['it-it'] = "Sei sicuro di voler cancellare le clip selezionate?";
$text['message-delete-clip']['nl-nl'] = "";
$text['message-delete-clip']['pl-pl'] = "";
$text['message-delete-clip']['pt-br'] = "Tem a certeza que pretende remover o clip seleccionado?"; //copied from pt-pt
$text['message-delete-clip']['pt-pt'] = "Tem a certeza que pretende remover o clip seleccionado?";
$text['message-delete-clip']['ro-ro'] = "";
$text['message-delete-clip']['ru-ru'] = "Вы действительно хотите удалить выбранный клип?";
$text['message-delete-clip']['sv-se'] = "Är du säker på att du vill radera det valda klippet?";
$text['message-delete-clip']['uk-ua'] = "";

$text['button-close']['en-us'] = "Close";
$text['button-close']['ar-eg'] = "";
$text['button-close']['de-at'] = "Schließen"; //copied from de-de
$text['button-close']['de-ch'] = "Schließen"; //copied from de-de
$text['button-close']['de-de'] = "Schließen";
$text['button-close']['es-cl'] = "Cerrar";
$text['button-close']['es-mx'] = "Cerrar"; //copied from es-cl
$text['button-close']['fr-ca'] = "Fermé"; //copied from fr-fr
$text['button-close']['fr-fr'] = "Fermé";
$text['button-close']['he-il'] = "";
$text['button-close']['it-it'] = "Chiudi";
$text['button-close']['nl-nl'] = "";
$text['button-close']['pl-pl'] = "";
$text['button-close']['pt-br'] = "Fechar"; //copied from pt-pt
$text['button-close']['pt-pt'] = "Fechar";
$text['button-close']['ro-ro'] = "";
$text['button-close']['ru-ru'] = "Закрыть";
$text['button-close']['sv-se'] = "Stäng";
$text['button-close']['uk-ua'] = "";

$text['label-path']['en-us'] = "Path:";
$text['label-path']['ar-eg'] = "";
$text['label-path']['de-at'] = "Pfad:"; //copied from de-de
$text['label-path']['de-ch'] = "Pfad:"; //copied from de-de
$text['label-path']['de-de'] = "Pfad:";
$text['label-path']['es-cl'] = "Ruta:";
$text['label-path']['es-mx'] = "Ruta:"; //copied from es-cl
$text['label-path']['fr-ca'] = "Chemin:"; //copied from fr-fr
$text['label-path']['fr-fr'] = "Chemin:";
$text['label-path']['he-il'] = "";
$text['label-path']['it-it'] = "Percorso:";
$text['label-path']['nl-nl'] = "";
$text['label-path']['pl-pl'] = "";
$text['label-path']['pt-br'] = "Caminho:"; //copied from pt-pt
$text['label-path']['pt-pt'] = "Caminho:";
$text['label-path']['ro-ro'] = "";
$text['label-path']['ru-ru'] = "Путь:";
$text['label-path']['sv-se'] = "Sökväg:";
$text['label-path']['uk-ua'] = "";

$text['label-file-name']['en-us'] = "File Name:";
$text['label-file-name']['ar-eg'] = "";
$text['label-file-name']['de-at'] = "Dateiname:"; //copied from de-de
$text['label-file-name']['de-ch'] = "Dateiname:"; //copied from de-de
$text['label-file-name']['de-de'] = "Dateiname:";
$text['label-file-name']['es-cl'] = "Nombre de Archivo:";
$text['label-file-name']['es-mx'] = "Nombre de Archivo:"; //copied from es-cl
$text['label-file-name']['fr-ca'] = "Nom du Fichier:"; //copied from fr-fr
$text['label-file-name']['fr-fr'] = "Nom du Fichier:";
$text['label-file-name']['he-il'] = "";
$text['label-file-name']['it-it'] = "Nome File:";
$text['label-file-name']['nl-nl'] = "";
$text['label-file-name']['pl-pl'] = "";
$text['label-file-name']['pt-br'] = "Nome do ficheiro:"; //copied from pt-pt
$text['label-file-name']['pt-pt'] = "Nome do ficheiro:";
$text['label-file-name']['ro-ro'] = "";
$text['label-file-name']['ru-ru'] = "Имя Файла:";
$text['label-file-name']['sv-se'] = "Filnamn:";
$text['label-file-name']['uk-ua'] = "";

$text['button-new-file']['en-us'] = "New File";
$text['button-new-file']['ar-eg'] = "";
$text['button-new-file']['de-at'] = "Neue Datei"; //copied from de-de
$text['button-new-file']['de-ch'] = "Neue Datei"; //copied from de-de
$text['button-new-file']['de-de'] = "Neue Datei";
$text['button-new-file']['es-cl'] = "Nuevo Archivo";
$text['button-new-file']['es-mx'] = "Nuevo Archivo"; //copied from es-cl
$text['button-new-file']['fr-ca'] = "Nouveau Fichier"; //copied from fr-fr
$text['button-new-file']['fr-fr'] = "Nouveau Fichier";
$text['button-new-file']['he-il'] = "";
$text['button-new-file']['it-it'] = "Nuovo File";
$text['button-new-file']['nl-nl'] = "";
$text['button-new-file']['pl-pl'] = "";
$text['button-new-file']['pt-br'] = "Novo Ficheiro"; //copied from pt-pt
$text['button-new-file']['pt-pt'] = "Novo Ficheiro";
$text['button-new-file']['ro-ro'] = "";
$text['button-new-file']['ru-ru'] = "Новый Файл";
$text['button-new-file']['sv-se'] = "Ny Fil";
$text['button-new-file']['uk-ua'] = "";

$text['label-file-name-orig']['en-us'] = "Original File Name:";
$text['label-file-name-orig']['ar-eg'] = "";
$text['label-file-name-orig']['de-at'] = "Ursprünglicher Dateiname:"; //copied from de-de
$text['label-file-name-orig']['de-ch'] = "Ursprünglicher Dateiname:"; //copied from de-de
$text['label-file-name-orig']['de-de'] = "Ursprünglicher Dateiname:";
$text['label-file-name-orig']['es-cl'] = "Nombre de Archivo Original:";
$text['label-file-name-orig']['es-mx'] = "Nombre de Archivo Original:"; //copied from es-cl
$text['label-file-name-orig']['fr-ca'] = "Nom du Fichier Original:"; //copied from fr-fr
$text['label-file-name-orig']['fr-fr'] = "Nom du Fichier Original:";
$text['label-file-name-orig']['he-il'] = "";
$text['label-file-name-orig']['it-it'] = "Nome Originale File:";
$text['label-file-name-orig']['nl-nl'] = "";
$text['label-file-name-orig']['pl-pl'] = "";
$text['label-file-name-orig']['pt-br'] = "Nome do Ficheiro Original:"; //copied from pt-pt
$text['label-file-name-orig']['pt-pt'] = "Nome do Ficheiro Original:";
$text['label-file-name-orig']['ro-ro'] = "";
$text['label-file-name-orig']['ru-ru'] = "Оригинальное Имя Файла:";
$text['label-file-name-orig']['sv-se'] = "Original Filnamn:";
$text['label-file-name-orig']['uk-ua'] = "";

$text['label-rename-file-to']['en-us'] = "Rename File To:";
$text['label-rename-file-to']['ar-eg'] = "";
$text['label-rename-file-to']['de-at'] = "Datei umbenennen in:"; //copied from de-de
$text['label-rename-file-to']['de-ch'] = "Datei umbenennen in:"; //copied from de-de
$text['label-rename-file-to']['de-de'] = "Datei umbenennen in:";
$text['label-rename-file-to']['es-cl'] = "Renombrar a:";
$text['label-rename-file-to']['es-mx'] = "Renombrar a:"; //copied from es-cl
$text['label-rename-file-to']['fr-ca'] = "Renommer le Fichier en:"; //copied from fr-fr
$text['label-rename-file-to']['fr-fr'] = "Renommer le Fichier en:";
$text['label-rename-file-to']['he-il'] = "";
$text['label-rename-file-to']['it-it'] = "Rinomina File In:";
$text['label-rename-file-to']['nl-nl'] = "";
$text['label-rename-file-to']['pl-pl'] = "";
$text['label-rename-file-to']['pt-br'] = "Renomear Ficheiro Para:"; //copied from pt-pt
$text['label-rename-file-to']['pt-pt'] = "Renomear Ficheiro Para:";
$text['label-rename-file-to']['ro-ro'] = "";
$text['label-rename-file-to']['ru-ru'] = "Переименовать Файл:";
$text['label-rename-file-to']['sv-se'] = "Ändra Filnamn Till:";
$text['label-rename-file-to']['uk-ua'] = "";

$text['label-files']['en-us'] = "Files";
$text['label-files']['ar-eg'] = "";
$text['label-files']['de-at'] = "Dateien"; //copied from de-de
$text['label-files']['de-ch'] = "Dateien"; //copied from de-de
$text['label-files']['de-de'] = "Dateien";
$text['label-files']['es-cl'] = "Archivos";
$text['label-files']['es-mx'] = "Archivos"; //copied from es-cl
$text['label-files']['fr-ca'] = "Fichiers"; //copied from fr-fr
$text['label-files']['fr-fr'] = "Fichiers";
$text['label-files']['he-il'] = "";
$text['label-files']['it-it'] = "Files";
$text['label-files']['nl-nl'] = "";
$text['label-files']['pl-pl'] = "";
$text['label-files']['pt-br'] = "Ficheiros"; //copied from pt-pt
$text['label-files']['pt-pt'] = "Ficheiros";
$text['label-files']['ro-ro'] = "";
$text['label-files']['ru-ru'] = "Файлы";
$text['label-files']['sv-se'] = "Filer";
$text['label-files']['uk-ua'] = "";

$text['button-add-file']['en-us'] = "Add File";
$text['button-add-file']['ar-eg'] = "";
$text['button-add-file']['de-at'] = "Datei hinzufügen"; //copied from de-de
$text['button-add-file']['de-ch'] = "Datei hinzufügen"; //copied from de-de
$text['button-add-file']['de-de'] = "Datei hinzufügen";
$text['button-add-file']['es-cl'] = "";
$text['button-add-file']['es-mx'] = "";
$text['button-add-file']['fr-ca'] = "Ajouter Fichier"; //copied from fr-fr
$text['button-add-file']['fr-fr'] = "Ajouter Fichier";
$text['button-add-file']['he-il'] = "";
$text['button-add-file']['it-it'] = "Inserisci File";
$text['button-add-file']['nl-nl'] = "";
$text['button-add-file']['pl-pl'] = "";
$text['button-add-file']['pt-br'] = "Adicionar Ficheiro"; //copied from pt-pt
$text['button-add-file']['pt-pt'] = "Adicionar Ficheiro";
$text['button-add-file']['ro-ro'] = "";
$text['button-add-file']['ru-ru'] = "Добавить Файл";
$text['button-add-file']['sv-se'] = "Lägg Till Fil";
$text['button-add-file']['uk-ua'] = "";

$text['button-add-dir']['en-us'] = "Add Dir";
$text['button-add-dir']['ar-eg'] = "";
$text['button-add-dir']['de-at'] = "Verzeichnis erstellen"; //copied from de-de
$text['button-add-dir']['de-ch'] = "Verzeichnis erstellen"; //copied from de-de
$text['button-add-dir']['de-de'] = "Verzeichnis erstellen";
$text['button-add-dir']['es-cl'] = "Agregar Carpeta";
$text['button-add-dir']['es-mx'] = "Agregar Carpeta"; //copied from es-cl
$text['button-add-dir']['fr-ca'] = "Ajouter un Répertoire"; //copied from fr-fr
$text['button-add-dir']['fr-fr'] = "Ajouter un Répertoire";
$text['button-add-dir']['he-il'] = "";
$text['button-add-dir']['it-it'] = "Inserisci Dir";
$text['button-add-dir']['nl-nl'] = "";
$text['button-add-dir']['pl-pl'] = "";
$text['button-add-dir']['pt-br'] = "Adicionar Directoria"; //copied from pt-pt
$text['button-add-dir']['pt-pt'] = "Adicionar Directoria";
$text['button-add-dir']['ro-ro'] = "";
$text['button-add-dir']['ru-ru'] = "Добавить Каталог";
$text['button-add-dir']['sv-se'] = "Lägg Till Katalog";
$text['button-add-dir']['uk-ua'] = "";

$text['button-rename-file']['en-us'] = "Rename File";
$text['button-rename-file']['ar-eg'] = "";
$text['button-rename-file']['de-at'] = "Datei umbenennen"; //copied from de-de
$text['button-rename-file']['de-ch'] = "Datei umbenennen"; //copied from de-de
$text['button-rename-file']['de-de'] = "Datei umbenennen";
$text['button-rename-file']['es-cl'] = "Renombrar Archivo";
$text['button-rename-file']['es-mx'] = "Renombrar Archivo"; //copied from es-cl
$text['button-rename-file']['fr-ca'] = "Renommer le Fichier"; //copied from fr-fr
$text['button-rename-file']['fr-fr'] = "Renommer le Fichier";
$text['button-rename-file']['he-il'] = "";
$text['button-rename-file']['it-it'] = "Rinomina File";
$text['button-rename-file']['nl-nl'] = "";
$text['button-rename-file']['pl-pl'] = "";
$text['button-rename-file']['pt-br'] = "Renomear Ficheiro"; //copied from pt-pt
$text['button-rename-file']['pt-pt'] = "Renomear Ficheiro";
$text['button-rename-file']['ro-ro'] = "";
$text['button-rename-file']['ru-ru'] = "Переименовать Файл";
$text['button-rename-file']['sv-se'] = "Namnändra Fil";
$text['button-rename-file']['uk-ua'] = "";

$text['message-delete-file']['en-us'] = "Are you sure you want to delete the selected file?";
$text['message-delete-file']['ar-eg'] = "";
$text['message-delete-file']['de-at'] = "Sind Sie sicher, dass Sie die markierte Datei löschen möchten?"; //copied from de-de
$text['message-delete-file']['de-ch'] = "Sind Sie sicher, dass Sie die markierte Datei löschen möchten?"; //copied from de-de
$text['message-delete-file']['de-de'] = "Sind Sie sicher, dass Sie die markierte Datei löschen möchten?";
$text['message-delete-file']['es-cl'] = "¿Realmente desea eliminar el archivo seleccionado?";
$text['message-delete-file']['es-mx'] = "¿Realmente desea eliminar el archivo seleccionado?"; //copied from es-cl
$text['message-delete-file']['fr-ca'] = "Etes-vous sûr de vouloir supprimer le fichier sélectionné?"; //copied from fr-fr
$text['message-delete-file']['fr-fr'] = "Etes-vous sûr de vouloir supprimer le fichier sélectionné?";
$text['message-delete-file']['he-il'] = "";
$text['message-delete-file']['it-it'] = "Sei sicuro di voler cancellare il file selezionato?";
$text['message-delete-file']['nl-nl'] = "";
$text['message-delete-file']['pl-pl'] = "";
$text['message-delete-file']['pt-br'] = "Tem a certeza que pretende remover o ficheiro seleccionado?"; //copied from pt-pt
$text['message-delete-file']['pt-pt'] = "Tem a certeza que pretende remover o ficheiro seleccionado?";
$text['message-delete-file']['ro-ro'] = "";
$text['message-delete-file']['ru-ru'] = "Вы уверены, что хотите удалить выбранный файл?";
$text['message-delete-file']['sv-se'] = "Är du säker på att du vill radera den valda filen?";
$text['message-delete-file']['uk-ua'] = "";

$text['button-del-file']['en-us'] = "Delete File";
$text['button-del-file']['ar-eg'] = "";
$text['button-del-file']['de-at'] = "Datei löschen"; //copied from de-de
$text['button-del-file']['de-ch'] = "Datei löschen"; //copied from de-de
$text['button-del-file']['de-de'] = "Datei löschen";
$text['button-del-file']['es-cl'] = "Eliminar Archivo";
$text['button-del-file']['es-mx'] = "Eliminar Archivo"; //copied from es-cl
$text['button-del-file']['fr-ca'] = "Supprimer le Fichier"; //copied from fr-fr
$text['button-del-file']['fr-fr'] = "Supprimer le Fichier";
$text['button-del-file']['he-il'] = "";
$text['button-del-file']['it-it'] = "Cancella File";
$text['button-del-file']['nl-nl'] = "";
$text['button-del-file']['pl-pl'] = "";
$text['button-del-file']['pt-br'] = "Remover Ficheiro"; //copied from pt-pt
$text['button-del-file']['pt-pt'] = "Remover Ficheiro";
$text['button-del-file']['ro-ro'] = "";
$text['button-del-file']['ru-ru'] = "Удалить Файл";
$text['button-del-file']['sv-se'] = "Ta Bort Fil";
$text['button-del-file']['uk-ua'] = "";

$text['message-delete-folder']['en-us'] = "Are you sure you want to delete the selected folder?";
$text['message-delete-folder']['ar-eg'] = "";
$text['message-delete-folder']['de-at'] = "SSind Sie sicher, dass Sie den markierten Ordner löschen möchten?"; //copied from de-de
$text['message-delete-folder']['de-ch'] = "SSind Sie sicher, dass Sie den markierten Ordner löschen möchten?"; //copied from de-de
$text['message-delete-folder']['de-de'] = "SSind Sie sicher, dass Sie den markierten Ordner löschen möchten?";
$text['message-delete-folder']['es-cl'] = "¿Realmente desea eliminar la carpeta seleccionada?";
$text['message-delete-folder']['es-mx'] = "¿Realmente desea eliminar la carpeta seleccionada?"; //copied from es-cl
$text['message-delete-folder']['fr-ca'] = "Etes-vous sûr de vouloir supprimer le répertoire sélectionné?"; //copied from fr-fr
$text['message-delete-folder']['fr-fr'] = "Etes-vous sûr de vouloir supprimer le répertoire sélectionné?";
$text['message-delete-folder']['he-il'] = "";
$text['message-delete-folder']['it-it'] = "Sei sicuro di voler cancellare la cartella selezionata?";
$text['message-delete-folder']['nl-nl'] = "";
$text['message-delete-folder']['pl-pl'] = "";
$text['message-delete-folder']['pt-br'] = "Tem a certeza que pretende remover a pasta seleccionada?"; //copied from pt-pt
$text['message-delete-folder']['pt-pt'] = "Tem a certeza que pretende remover a pasta seleccionada?";
$text['message-delete-folder']['ro-ro'] = "";
$text['message-delete-folder']['ru-ru'] = "Вы действительно хотите удалить выбранный Каталог?";
$text['message-delete-folder']['sv-se'] = "Är du säker på att du vill radera den valda mappen?";
$text['message-delete-folder']['uk-ua'] = "";

$text['button-del-dir']['en-us'] = "Delete Dir";
$text['button-del-dir']['ar-eg'] = "";
$text['button-del-dir']['de-at'] = "Verzeichnis löschen"; //copied from de-de
$text['button-del-dir']['de-ch'] = "Verzeichnis löschen"; //copied from de-de
$text['button-del-dir']['de-de'] = "Verzeichnis löschen";
$text['button-del-dir']['es-cl'] = "Eliminar Carpeta";
$text['button-del-dir']['es-mx'] = "Eliminar Carpeta"; //copied from es-cl
$text['button-del-dir']['fr-ca'] = "Supprimer le Répertoire"; //copied from fr-fr
$text['button-del-dir']['fr-fr'] = "Supprimer le Répertoire";
$text['button-del-dir']['he-il'] = "";
$text['button-del-dir']['it-it'] = "Cancella Dir";
$text['button-del-dir']['nl-nl'] = "";
$text['button-del-dir']['pl-pl'] = "";
$text['button-del-dir']['pt-br'] = "Remover Directoria"; //copied from pt-pt
$text['button-del-dir']['pt-pt'] = "Remover Directoria";
$text['button-del-dir']['ro-ro'] = "";
$text['button-del-dir']['ru-ru'] = "Удалить Каталог";
$text['button-del-dir']['sv-se'] = "Ta Bort Mapp";
$text['button-del-dir']['uk-ua'] = "";

$text['message-error']['en-us'] = "Error!!";
$text['message-error']['ar-eg'] = "";
$text['message-error']['de-at'] = "Fehler!!"; //copied from de-de
$text['message-error']['de-ch'] = "Fehler!!"; //copied from de-de
$text['message-error']['de-de'] = "Fehler!!";
$text['message-error']['es-cl'] = "Error";
$text['message-error']['es-mx'] = "Error"; //copied from es-cl
$text['message-error']['fr-ca'] = "Erreur!!"; //copied from fr-fr
$text['message-error']['fr-fr'] = "Erreur!!";
$text['message-error']['he-il'] = "";
$text['message-error']['it-it'] = "Errore!!";
$text['message-error']['nl-nl'] = "";
$text['message-error']['pl-pl'] = "";
$text['message-error']['pt-br'] = "Erro!!"; //copied from pt-pt
$text['message-error']['pt-pt'] = "Erro!!";
$text['message-error']['ro-ro'] = "";
$text['message-error']['ru-ru'] = "Ошибка!!";
$text['message-error']['sv-se'] = "Fel!!";
$text['message-error']['uk-ua'] = "";

$text['label-folder-name']['en-us'] = "Folder Name:";
$text['label-folder-name']['ar-eg'] = "";
$text['label-folder-name']['de-at'] = "Verzeichnis Name:"; //copied from de-de
$text['label-folder-name']['de-ch'] = "Verzeichnis Name:"; //copied from de-de
$text['label-folder-name']['de-de'] = "Verzeichnis Name:";
$text['label-folder-name']['es-cl'] = "Nombre de Carpeta:";
$text['label-folder-name']['es-mx'] = "Nombre de Carpeta:"; //copied from es-cl
$text['label-folder-name']['fr-ca'] = "Nom du Répertoire:"; //copied from fr-fr
$text['label-folder-name']['fr-fr'] = "Nom du Répertoire:";
$text['label-folder-name']['he-il'] = "";
$text['label-folder-name']['it-it'] = "Nome Cartella:";
$text['label-folder-name']['nl-nl'] = "";
$text['label-folder-name']['pl-pl'] = "";
$text['label-folder-name']['pt-br'] = "Nome da Pasta:"; //copied from pt-pt
$text['label-folder-name']['pt-pt'] = "Nome da Pasta:";
$text['label-folder-name']['ro-ro'] = "";
$text['label-folder-name']['ru-ru'] = "Имя Каталога";
$text['label-folder-name']['sv-se'] = "Katalog Namn:";
$text['label-folder-name']['uk-ua'] = "";

$text['button-new-folder']['en-us'] = "New Folder";
$text['button-new-folder']['ar-eg'] = "";
$text['button-new-folder']['de-at'] = "Neues Verzeichnis"; //copied from de-de
$text['button-new-folder']['de-ch'] = "Neues Verzeichnis"; //copied from de-de
$text['button-new-folder']['de-de'] = "Neues Verzeichnis";
$text['button-new-folder']['es-cl'] = "Nueva Carpeta";
$text['button-new-folder']['es-mx'] = "Nueva Carpeta"; //copied from es-cl
$text['button-new-folder']['fr-ca'] = "Nouveau Répertoire"; //copied from fr-fr
$text['button-new-folder']['fr-fr'] = "Nouveau Répertoire";
$text['button-new-folder']['he-il'] = "";
$text['button-new-folder']['it-it'] = "Nuova Cartella";
$text['button-new-folder']['nl-nl'] = "";
$text['button-new-folder']['pl-pl'] = "";
$text['button-new-folder']['pt-br'] = "Novo Ficheiro"; //copied from pt-pt
$text['button-new-folder']['pt-pt'] = "Novo Ficheiro";
$text['button-new-folder']['ro-ro'] = "";
$text['button-new-folder']['ru-ru'] = "Новый Каталогr";
$text['button-new-folder']['sv-se'] = "Ny Mapp";
$text['button-new-folder']['uk-ua'] = "";

$text['button-delete-this']['en-us'] = "Are you sure want to delete this?";
$text['button-delete-this']['ar-eg'] = "";
$text['button-delete-this']['de-at'] = "Sind Sie sicher, dass Sie dieses löschen möchten?"; //copied from de-de
$text['button-delete-this']['de-ch'] = "Sind Sie sicher, dass Sie dieses löschen möchten?"; //copied from de-de
$text['button-delete-this']['de-de'] = "Sind Sie sicher, dass Sie dieses löschen möchten?";
$text['button-delete-this']['es-cl'] = "¿Realmente desea eliminar esto?";
$text['button-delete-this']['es-mx'] = "¿Realmente desea eliminar esto?"; //copied from es-cl
$text['button-delete-this']['fr-ca'] = "Voulez-vous vraiment supprimer cela?"; //copied from fr-fr
$text['button-delete-this']['fr-fr'] = "Voulez-vous vraiment supprimer cela?";
$text['button-delete-this']['he-il'] = "";
$text['button-delete-this']['it-it'] = "Sei sicuro di volerlo cancellare?";
$text['button-delete-this']['nl-nl'] = "";
$text['button-delete-this']['pl-pl'] = "";
$text['button-delete-this']['pt-br'] = "Tem a certeza que pretende remover isto?"; //copied from pt-pt
$text['button-delete-this']['pt-pt'] = "Tem a certeza que pretende remover isto?";
$text['button-delete-this']['ro-ro'] = "";
$text['button-delete-this']['ru-ru'] = "Вы действительно хотите удалить это?";
$text['button-delete-this']['sv-se'] = "Vill du verkligen ta bort det här?";
$text['button-delete-this']['uk-ua'] = "";

$text['label-file']['en-us'] = "File:";
$text['label-file']['ar-eg'] = "";
$text['label-file']['de-at'] = "Datei:"; //copied from de-de
$text['label-file']['de-ch'] = "Datei:"; //copied from de-de
$text['label-file']['de-de'] = "Datei:";
$text['label-file']['es-cl'] = "Archivo:";
$text['label-file']['es-mx'] = "Archivo:"; //copied from es-cl
$text['label-file']['fr-ca'] = "Fichier:"; //copied from fr-fr
$text['label-file']['fr-fr'] = "Fichier:";
$text['label-file']['he-il'] = "";
$text['label-file']['it-it'] = "File:";
$text['label-file']['nl-nl'] = "";
$text['label-file']['pl-pl'] = "";
$text['label-file']['pt-br'] = "Ficheiro:"; //copied from pt-pt
$text['label-file']['pt-pt'] = "Ficheiro:";
$text['label-file']['ro-ro'] = "";
$text['label-file']['ru-ru'] = "Файл:";
$text['label-file']['sv-se'] = "Fil:";
$text['label-file']['uk-ua'] = "";

?>
