<?php

	$y=0;
	$apps[$x]['menu'][$y]['title']['en-us'] = "Script Editor";
	$apps[$x]['menu'][$y]['title']['ar-eg'] = "Script Editor";
	$apps[$x]['menu'][$y]['title']['de-at'] = "Skript Editor";
	$apps[$x]['menu'][$y]['title']['de-ch'] = "Script Editor";
	$apps[$x]['menu'][$y]['title']['de-de'] = "Skript Editor";
	$apps[$x]['menu'][$y]['title']['es-cl'] = "Editor de Scripts";
	$apps[$x]['menu'][$y]['title']['es-mx'] = "Script Editor";
	$apps[$x]['menu'][$y]['title']['fr-ca'] = "Script Editor";
	$apps[$x]['menu'][$y]['title']['fr-fr'] = "Editeur de script";
	$apps[$x]['menu'][$y]['title']['he-il'] = "עורך תסריט";
	$apps[$x]['menu'][$y]['title']['it-it'] = "Editor Script";
	$apps[$x]['menu'][$y]['title']['nl-nl'] = "Scipt bewerker";
	$apps[$x]['menu'][$y]['title']['pl-pl'] = "Scripter";
	$apps[$x]['menu'][$y]['title']['pt-br'] = "Editor de texto";
	$apps[$x]['menu'][$y]['title']['pt-pt'] = "Editor de Scripts";
	$apps[$x]['menu'][$y]['title']['ro-ro'] = "Editor de scripturi";
	$apps[$x]['menu'][$y]['title']['ru-ru'] = "Редактор скриптов";
	$apps[$x]['menu'][$y]['title']['sv-se'] = "Skriptredigerare";
	$apps[$x]['menu'][$y]['title']['uk-ua'] = "Редактор сценарію";
	$apps[$x]['menu'][$y]['title']['zh-cn'] = '脚本编辑器';
	$apps[$x]['menu'][$y]['title']['ja-jp'] = 'スクリプトエディタ';
	$apps[$x]['menu'][$y]['title']['ko-kr'] = '스크립트 편집기';
	$apps[$x]['menu'][$y]['uuid'] = "f1905fec-0577-daef-6045-59d09b7d3f94";
	$apps[$x]['menu'][$y]['parent_uuid'] = "594d99c5-6128-9c88-ca35-4b33392cec0f";
	$apps[$x]['menu'][$y]['category'] = "external";
	$apps[$x]['menu'][$y]['path'] = "/app/edit/index.php?dir=scripts";
	$apps[$x]['menu'][$y]['groups'][] = "superadmin";
	$y++;
	$apps[$x]['menu'][$y]['title']['en-us'] = "XML Editor";
	$apps[$x]['menu'][$y]['title']['ar-eg'] = "XML Editor";
	$apps[$x]['menu'][$y]['title']['de-at'] = "XML Editor";
	$apps[$x]['menu'][$y]['title']['de-ch'] = "XML Editor";
	$apps[$x]['menu'][$y]['title']['de-de'] = "XML Editor";
	$apps[$x]['menu'][$y]['title']['es-cl'] = "Editor XML";
	$apps[$x]['menu'][$y]['title']['es-mx'] = "XML Editor";
	$apps[$x]['menu'][$y]['title']['fr-ca'] = "XML Editor";
	$apps[$x]['menu'][$y]['title']['fr-fr'] = "Editeur XML";
	$apps[$x]['menu'][$y]['title']['he-il'] = "עורך XML";
	$apps[$x]['menu'][$y]['title']['it-it'] = "Editor XML";
	$apps[$x]['menu'][$y]['title']['nl-nl'] = "XML bewerking";
	$apps[$x]['menu'][$y]['title']['pl-pl'] = "XML";
	$apps[$x]['menu'][$y]['title']['pt-br'] = "Editor de XML";
	$apps[$x]['menu'][$y]['title']['pt-pt'] = "Editor XML";
	$apps[$x]['menu'][$y]['title']['ro-ro'] = "Editor XML";
	$apps[$x]['menu'][$y]['title']['ru-ru'] = "Редактор XML";
	$apps[$x]['menu'][$y]['title']['sv-se'] = "XML Editor";
	$apps[$x]['menu'][$y]['title']['uk-ua'] = "XML редактор";
	$apps[$x]['menu'][$y]['title']['zh-cn'] = "XML编辑器";
	$apps[$x]['menu'][$y]['title']['ja-jp'] = "XMLエディタ";
	$apps[$x]['menu'][$y]['title']['ko-kr'] = "XML 편집기";
	$apps[$x]['menu'][$y]['uuid'] = "16013877-606a-2a05-7d6a-c1b215839131";
	$apps[$x]['menu'][$y]['parent_uuid'] = "594d99c5-6128-9c88-ca35-4b33392cec0f";
	$apps[$x]['menu'][$y]['category'] = "external";
	$apps[$x]['menu'][$y]['path'] = "/app/edit/index.php?dir=xml";
	$apps[$x]['menu'][$y]['groups'][] = "superadmin";
	$y++;
	$apps[$x]['menu'][$y]['title']['en-us'] = "Provision Editor";
	$apps[$x]['menu'][$y]['title']['ar-eg'] = "محرر";
	$apps[$x]['menu'][$y]['title']['de-at'] = "Bereitstellungs Editor";
	$apps[$x]['menu'][$y]['title']['de-ch'] = "Beschreibung";
	$apps[$x]['menu'][$y]['title']['de-de'] = "Bereitstellungs Editor";
	$apps[$x]['menu'][$y]['title']['es-cl'] = "Editor de Provisionamiento";
	$apps[$x]['menu'][$y]['title']['es-mx'] = "Redacción";
	$apps[$x]['menu'][$y]['title']['fr-ca'] = "Rédacteur";
	$apps[$x]['menu'][$y]['title']['fr-fr'] = "Editeur de Provisioning";
	$apps[$x]['menu'][$y]['title']['he-il'] = "עורך Provision";
	$apps[$x]['menu'][$y]['title']['it-it'] = "Editor di Provisioning";
	$apps[$x]['menu'][$y]['title']['nl-nl'] = "Voorzieningen bewerker";
	$apps[$x]['menu'][$y]['title']['pl-pl'] = "Oficjalna strona";
	$apps[$x]['menu'][$y]['title']['pt-br'] = "Editor de Provisão";
	$apps[$x]['menu'][$y]['title']['pt-pt'] = "Editor de Provisionamento";
	$apps[$x]['menu'][$y]['title']['ro-ro'] = "Editor de provizii";
	$apps[$x]['menu'][$y]['title']['ru-ru'] = "Редактор шаблонов автоконфигурации";
	$apps[$x]['menu'][$y]['title']['sv-se'] = "Provision Editor";
	$apps[$x]['menu'][$y]['title']['uk-ua'] = "Редактор даних";
	$apps[$x]['menu'][$y]['title']['zh-cn'] = "规定编辑器";
	$apps[$x]['menu'][$y]['title']['ja-jp'] = "プロビジョニングエディター";
	$apps[$x]['menu'][$y]['title']['ko-kr'] = "프로비저닝 편집자";
	$apps[$x]['menu'][$y]['uuid'] = "57773542-a565-1a29-605d-6535da1a0870";
	$apps[$x]['menu'][$y]['parent_uuid'] = "594d99c5-6128-9c88-ca35-4b33392cec0f";
	$apps[$x]['menu'][$y]['category'] = "external";
	$apps[$x]['menu'][$y]['path'] = "/app/edit/index.php?dir=provision";
	$apps[$x]['menu'][$y]['groups'][] = "superadmin";
	$y++;
	$apps[$x]['menu'][$y]['title']['en-us'] = "PHP Editor";
	$apps[$x]['menu'][$y]['title']['ar-eg'] = "PHP Editor";
	$apps[$x]['menu'][$y]['title']['de-at'] = "PHP Editor";
	$apps[$x]['menu'][$y]['title']['de-ch'] = "PHP Editor";
	$apps[$x]['menu'][$y]['title']['de-de'] = "PHP Editor";
	$apps[$x]['menu'][$y]['title']['es-cl'] = "Editor PHP";
	$apps[$x]['menu'][$y]['title']['es-mx'] = "PHP Editor";
	$apps[$x]['menu'][$y]['title']['fr-ca'] = "PHP Editor";
	$apps[$x]['menu'][$y]['title']['fr-fr'] = "Editeur PHP";
	$apps[$x]['menu'][$y]['title']['he-il'] = "עורך PHP";
	$apps[$x]['menu'][$y]['title']['it-it'] = "Editor PHP";
	$apps[$x]['menu'][$y]['title']['nl-nl'] = "PHP bewerker";
	$apps[$x]['menu'][$y]['title']['pl-pl'] = "PHP Editor";
	$apps[$x]['menu'][$y]['title']['pt-br'] = "Editor de PHP";
	$apps[$x]['menu'][$y]['title']['pt-pt'] = "Editor de PHP";
	$apps[$x]['menu'][$y]['title']['ro-ro'] = "Editor PHP";
	$apps[$x]['menu'][$y]['title']['ru-ru'] = "Редактор PHP";
	$apps[$x]['menu'][$y]['title']['sv-se'] = "PHP redaktör";
	$apps[$x]['menu'][$y]['title']['uk-ua'] = "Редактор PHP";
	$apps[$x]['menu'][$y]['title']['zh-cn'] = "PHP编辑器";
	$apps[$x]['menu'][$y]['title']['ja-jp'] = "PHPエディタ";
	$apps[$x]['menu'][$y]['title']['ko-kr'] = "PHP 편집기";
	$apps[$x]['menu'][$y]['uuid'] = "eae1f2d6-789b-807c-cc26-44501e848693";
	$apps[$x]['menu'][$y]['parent_uuid'] = "594d99c5-6128-9c88-ca35-4b33392cec0f";
	$apps[$x]['menu'][$y]['category'] = "external";
	$apps[$x]['menu'][$y]['icon'] = "external-link-alt";
	$apps[$x]['menu'][$y]['path'] = "/app/edit/index.php?dir=php";
	$apps[$x]['menu'][$y]['groups'][] = "superadmin";
	$y++;

?>
