<?php
#This file was last reorganized on 19th of September 2017 08:54:24 AM UTC

$text['title-call_broadcasts']['en-us'] = "Call Broadcasts";
$text['title-call_broadcasts']['en-gb'] = "Call Broadcasts";
$text['title-call_broadcasts']['ar-eg'] = "";
$text['title-call_broadcasts']['de-at'] = "Rundrufe"; //copied from de-de
$text['title-call_broadcasts']['de-ch'] = "Rundrufe"; //copied from de-de
$text['title-call_broadcasts']['de-de'] = "Rundrufe";
$text['title-call_broadcasts']['es-cl'] = "Llamada Masiva (Broadcast)";
$text['title-call_broadcasts']['es-mx'] = "Llamada Masiva (Broadcast)"; //copied from es-cl
$text['title-call_broadcasts']['fr-ca'] = "Campagne d'appels"; //copied from fr-fr
$text['title-call_broadcasts']['fr-fr'] = "Campagne d'appels";
$text['title-call_broadcasts']['he-il'] = "הגדרת חשבון";
$text['title-call_broadcasts']['it-it'] = "Chiamate Multiple";
$text['title-call_broadcasts']['nl-nl'] = "Omroep";
$text['title-call_broadcasts']['pl-pl'] = "Rozsyłanie rozmów";
$text['title-call_broadcasts']['pt-br'] = "Configurações da Conta";
$text['title-call_broadcasts']['pt-pt'] = "Chamadas de Broadcast";
$text['title-call_broadcasts']['ro-ro'] = "";
$text['title-call_broadcasts']['ru-ru'] = "Массовые вызовы";
$text['title-call_broadcasts']['sv-se'] = "Samtalsdistributioner";
$text['title-call_broadcasts']['uk-ua'] = "Трансляція дзвінків";

$text['title-call_broadcast']['en-us'] = "Call Broadcast";
$text['title-call_broadcast']['en-gb'] = "Call Broadcast";
$text['title-call_broadcast']['ar-eg'] = "";
$text['title-call_broadcast']['de-at'] = "Rundrufe"; //copied from de-de
$text['title-call_broadcast']['de-ch'] = "Rundrufe"; //copied from de-de
$text['title-call_broadcast']['de-de'] = "Rundrufe";
$text['title-call_broadcast']['es-cl'] = "Llamada Masiva (Broadcast)";
$text['title-call_broadcast']['es-mx'] = "Llamada Masiva (Broadcast)"; //copied from es-cl
$text['title-call_broadcast']['fr-ca'] = "Campagne d'appels"; //copied from fr-fr
$text['title-call_broadcast']['fr-fr'] = "Campagne d'appels";
$text['title-call_broadcast']['he-il'] = "הגדרת חשבון";
$text['title-call_broadcast']['it-it'] = "Chiamate Multiple";
$text['title-call_broadcast']['nl-nl'] = "Omroep";
$text['title-call_broadcast']['pl-pl'] = "Rozsyłanie rozmów";
$text['title-call_broadcast']['pt-br'] = "Configurações da Conta";
$text['title-call_broadcast']['pt-pt'] = "Chamadas de Broadcast";
$text['title-call_broadcast']['ro-ro'] = "";
$text['title-call_broadcast']['ru-ru'] = "Массовые вызовы";
$text['title-call_broadcast']['sv-se'] = "Samtalsdistributioner";
$text['title-call_broadcast']['uk-ua'] = "Трансляція дзвінків";

$text['title_description-call_broadcast']['en-us'] = "Manage the delivery of pre-recorded messages to mass recipients.";
$text['title_description-call_broadcast']['en-gb'] = "Manage the delivery of pre-recorded messages to mass recipients.";
$text['title_description-call_broadcast']['ar-eg'] = "";
$text['title_description-call_broadcast']['de-at'] = "";
$text['title_description-call_broadcast']['de-ch'] = "";
$text['title_description-call_broadcast']['de-de'] = "";
$text['title_description-call_broadcast']['es-cl'] = "";
$text['title_description-call_broadcast']['es-mx'] = "";
$text['title_description-call_broadcast']['fr-ca'] = "";
$text['title_description-call_broadcast']['fr-fr'] = "";
$text['title_description-call_broadcast']['he-il'] = "";
$text['title_description-call_broadcast']['it-it'] = "";
$text['title_description-call_broadcast']['nl-nl'] = "Beheer de aflevering van voor-opgenomen boodschappen naar meerdere ontvangers.";
$text['title_description-call_broadcast']['pl-pl'] = "";
$text['title_description-call_broadcast']['pt-br'] = "";
$text['title_description-call_broadcast']['pt-pt'] = "";
$text['title_description-call_broadcast']['ro-ro'] = "";
$text['title_description-call_broadcast']['ru-ru'] = "";
$text['title_description-call_broadcast']['sv-se'] = "";
$text['title_description-call_broadcast']['uk-ua'] = "";

$text['option-true']['en-us'] = "True";
$text['option-true']['en-gb'] = "True";
$text['option-true']['ar-eg'] = "";
$text['option-true']['de-at'] = "Ein"; //copied from de-de
$text['option-true']['de-ch'] = "Ein"; //copied from de-de
$text['option-true']['de-de'] = "Ein";
$text['option-true']['es-cl'] = "Verdadero";
$text['option-true']['es-mx'] = "Verdadero"; //copied from es-cl
$text['option-true']['fr-ca'] = "Oui"; //copied from fr-fr
$text['option-true']['fr-fr'] = "Oui";
$text['option-true']['he-il'] = "חוקי";
$text['option-true']['it-it'] = "";
$text['option-true']['nl-nl'] = "Aan";
$text['option-true']['pl-pl'] = "Tak";
$text['option-true']['pt-br'] = "Sim"; //copied from pt-pt
$text['option-true']['pt-pt'] = "Sim";
$text['option-true']['ro-ro'] = "";
$text['option-true']['ru-ru'] = "Да";
$text['option-true']['sv-se'] = "Sann";
$text['option-true']['uk-ua'] = "Так";

$text['option-false']['en-us'] = "False";
$text['option-false']['en-gb'] = "False";
$text['option-false']['ar-eg'] = "";
$text['option-false']['de-at'] = "Aus"; //copied from de-de
$text['option-false']['de-ch'] = "Aus"; //copied from de-de
$text['option-false']['de-de'] = "Aus";
$text['option-false']['es-cl'] = "Falso";
$text['option-false']['es-mx'] = "Falso"; //copied from es-cl
$text['option-false']['fr-ca'] = "Non"; //copied from fr-fr
$text['option-false']['fr-fr'] = "Non";
$text['option-false']['he-il'] = "לא חוקי";
$text['option-false']['it-it'] = "";
$text['option-false']['nl-nl'] = "Uit";
$text['option-false']['pl-pl'] = "Nie";
$text['option-false']['pt-br'] = "Não"; //copied from pt-pt
$text['option-false']['pt-pt'] = "Não";
$text['option-false']['ro-ro'] = "";
$text['option-false']['ru-ru'] = "Нет";
$text['option-false']['sv-se'] = "Falsk";
$text['option-false']['uk-ua'] = "Ні";

$text['label-view-calls']['en-us'] = "View Calls";
$text['label-view-calls']['en-gb'] = "View Calls";
$text['label-view-calls']['ar-eg'] = "";
$text['label-view-calls']['de-at'] = "Anrufe ansehen"; //copied from de-de
$text['label-view-calls']['de-ch'] = "Anrufe ansehen"; //copied from de-de
$text['label-view-calls']['de-de'] = "Anrufe ansehen";
$text['label-view-calls']['es-cl'] = "Ver llamadas";
$text['label-view-calls']['es-mx'] = "Ver llamadas"; //copied from es-cl
$text['label-view-calls']['fr-ca'] = "Voir les appels"; //copied from fr-fr
$text['label-view-calls']['fr-fr'] = "Voir les appels";
$text['label-view-calls']['he-il'] = "";
$text['label-view-calls']['it-it'] = "Visualizza Chiamate";
$text['label-view-calls']['nl-nl'] = "Oproepen bekijken";
$text['label-view-calls']['pl-pl'] = "Podgląd rozmów";
$text['label-view-calls']['pt-br'] = "Ver chamadas";
$text['label-view-calls']['pt-pt'] = "Ver Chamadas";
$text['label-view-calls']['ro-ro'] = "";
$text['label-view-calls']['ru-ru'] = "Показать вызовы";
$text['label-view-calls']['sv-se'] = "Granska Samtal";
$text['label-view-calls']['uk-ua'] = "Перегляд дзвінків";

$text['label-start_time']['en-us'] = "Start Time";
$text['label-start_time']['en-gb'] = "Start Time";
$text['label-start_time']['ar-eg'] = "Start Time";
$text['label-start_time']['de-at'] = "Start Time"; //copied from de-de
$text['label-start_time']['de-ch'] = "Start Time"; //copied from de-de
$text['label-start_time']['de-de'] = "Start Time";
$text['label-start_time']['es-cl'] = "Start Time";
$text['label-start_time']['es-mx'] = "Start Time"; //copied from es-cl
$text['label-start_time']['fr-ca'] = "Start Time"; //copied from fr-fr
$text['label-start_time']['fr-fr'] = "Start Time";
$text['label-start_time']['he-il'] = "Start Time";
$text['label-start_time']['it-it'] = "Start Time";
$text['label-start_time']['nl-nl'] = "Start Time";
$text['label-start_time']['pl-pl'] = "Start Time";
$text['label-start_time']['pt-br'] = "Start Time";
$text['label-start_time']['pt-pt'] = "Start Time";
$text['label-start_time']['ro-ro'] = "Start Time";
$text['label-start_time']['ru-ru'] = "Start Time";
$text['label-start_time']['sv-se'] = "Start Time";
$text['label-start_time']['uk-ua'] = "Start Time";


$text['label-timeout']['en-us'] = "Timeout";
$text['label-timeout']['en-gb'] = "Timeout";
$text['label-timeout']['ar-eg'] = "";
$text['label-timeout']['de-at'] = "Zeitüberschreitung"; //copied from de-de
$text['label-timeout']['de-ch'] = "Zeitüberschreitung"; //copied from de-de
$text['label-timeout']['de-de'] = "Zeitüberschreitung";
$text['label-timeout']['es-cl'] = "Tiempo Líimite";
$text['label-timeout']['es-mx'] = "Tiempo Líimite"; //copied from es-cl
$text['label-timeout']['fr-ca'] = "Timeout"; //copied from fr-fr
$text['label-timeout']['fr-fr'] = "Timeout";
$text['label-timeout']['he-il'] = "";
$text['label-timeout']['it-it'] = "";
$text['label-timeout']['nl-nl'] = "Tijdsoverschrijding";
$text['label-timeout']['pl-pl'] = "Przekroczenie czasu oczekiwania (timeout)";
$text['label-timeout']['pt-br'] = "Tempo limite";
$text['label-timeout']['pt-pt'] = "Timeout";
$text['label-timeout']['ro-ro'] = "";
$text['label-timeout']['ru-ru'] = "Тайм-аут";
$text['label-timeout']['sv-se'] = "Tidsgräns";
$text['label-timeout']['uk-ua'] = "Таймаут";

$text['label-phone']['en-us'] = "Phone Number List";
$text['label-phone']['en-gb'] = "Phone Number List";
$text['label-phone']['ar-eg'] = "";
$text['label-phone']['de-at'] = "Liste der Telefonnummern"; //copied from de-de
$text['label-phone']['de-ch'] = "Liste der Telefonnummern"; //copied from de-de
$text['label-phone']['de-de'] = "Liste der Telefonnummern";
$text['label-phone']['es-cl'] = "Lista de Números de Telefono";
$text['label-phone']['es-mx'] = "Lista de Números de Telefono"; //copied from es-cl
$text['label-phone']['fr-ca'] = "Liste de Numéros de téléphone"; //copied from fr-fr
$text['label-phone']['fr-fr'] = "Liste de Numéros de téléphone";
$text['label-phone']['he-il'] = "רשימת מספרי טלפון";
$text['label-phone']['it-it'] = "Lista Numeri di Telefono";
$text['label-phone']['nl-nl'] = "Telefoonnummer lijst";
$text['label-phone']['pl-pl'] = "Lista numerów telefonu";
$text['label-phone']['pt-br'] = "Lista de números de telefone";
$text['label-phone']['pt-pt'] = "Lista de Números de Telefone";
$text['label-phone']['ro-ro'] = "";
$text['label-phone']['ru-ru'] = "Список телефонних номеров";
$text['label-phone']['sv-se'] = "Lista Med Telefonnummer";
$text['label-phone']['uk-ua'] = "Список телефонних номерів";

$text['label-message']['en-us'] = "Message";
$text['label-message']['en-gb'] = "Message";
$text['label-message']['ar-eg'] = "";
$text['label-message']['de-at'] = "Nachricht"; //copied from de-de
$text['label-message']['de-ch'] = "Nachricht"; //copied from de-de
$text['label-message']['de-de'] = "Nachricht";
$text['label-message']['es-cl'] = "Mensaje";
$text['label-message']['es-mx'] = "Mensaje"; //copied from es-cl
$text['label-message']['fr-ca'] = "Message"; //copied from fr-fr
$text['label-message']['fr-fr'] = "Message";
$text['label-message']['he-il'] = "הודעה";
$text['label-message']['it-it'] = "Messaggio";
$text['label-message']['nl-nl'] = "Boodschappen";
$text['label-message']['pl-pl'] = "Wiadomość";
$text['label-message']['pt-br'] = "Mensagem"; //copied from pt-pt
$text['label-message']['pt-pt'] = "Mensagem";
$text['label-message']['ro-ro'] = "";
$text['label-message']['ru-ru'] = "Сообщение";
$text['label-message']['sv-se'] = "Meddelande";
$text['label-message']['uk-ua'] = "Повідомлення";

$text['label-has-been']['en-us'] = "has been started";
$text['label-has-been']['en-gb'] = "has been started";
$text['label-has-been']['ar-eg'] = "";
$text['label-has-been']['de-at'] = "wurde gestartet"; //copied from de-de
$text['label-has-been']['de-ch'] = "wurde gestartet"; //copied from de-de
$text['label-has-been']['de-de'] = "wurde gestartet";
$text['label-has-been']['es-cl'] = "iniciada";
$text['label-has-been']['es-mx'] = "iniciada"; //copied from es-cl
$text['label-has-been']['fr-ca'] = "a commencé"; //copied from fr-fr
$text['label-has-been']['fr-fr'] = "a commencé";
$text['label-has-been']['he-il'] = "";
$text['label-has-been']['it-it'] = "è iniziato.";
$text['label-has-been']['nl-nl'] = "is gestart";
$text['label-has-been']['pl-pl'] = "rozpoczęto";
$text['label-has-been']['pt-br'] = "foi inicializada"; //copied from pt-pt
$text['label-has-been']['pt-pt'] = "foi inicializada";
$text['label-has-been']['ro-ro'] = "";
$text['label-has-been']['ru-ru'] = "было запущено";
$text['label-has-been']['sv-se'] = "har startat";
$text['label-has-been']['uk-ua'] = "було запущено";

$text['label-destination']['en-us'] = "Destination Number";
$text['label-destination']['en-gb'] = "Destination Number";
$text['label-destination']['ar-eg'] = "";
$text['label-destination']['de-at'] = "Zielnummer"; //copied from de-de
$text['label-destination']['de-ch'] = "Zielnummer"; //copied from de-de
$text['label-destination']['de-de'] = "Zielnummer";
$text['label-destination']['es-cl'] = "Número de Destino";
$text['label-destination']['es-mx'] = "Número de Destino"; //copied from es-cl
$text['label-destination']['fr-ca'] = "Numéro de Destination"; //copied from fr-fr
$text['label-destination']['fr-fr'] = "Numéro de Destination";
$text['label-destination']['he-il'] = "יעד";
$text['label-destination']['it-it'] = "Numero di Destinazione";
$text['label-destination']['nl-nl'] = "Bestemmingnummer";
$text['label-destination']['pl-pl'] = "Destynacja";
$text['label-destination']['pt-br'] = "Número de destino";
$text['label-destination']['pt-pt'] = "Número de Destino";
$text['label-destination']['ro-ro'] = "";
$text['label-destination']['ru-ru'] = "Номер назначения";
$text['label-destination']['sv-se'] = "Destinationsnummer";
$text['label-destination']['uk-ua'] = "Номер";

$text['label-concurrent-limit']['en-us'] = "Concurrent Limit";
$text['label-concurrent-limit']['en-gb'] = "Concurrent Limit";
$text['label-concurrent-limit']['ar-eg'] = "";
$text['label-concurrent-limit']['de-at'] = "Gleichzeitige Anrufe"; //copied from de-de
$text['label-concurrent-limit']['de-ch'] = "Gleichzeitige Anrufe"; //copied from de-de
$text['label-concurrent-limit']['de-de'] = "Gleichzeitige Anrufe";
$text['label-concurrent-limit']['es-cl'] = "Límite de concurrencia";
$text['label-concurrent-limit']['es-mx'] = "Límite de concurrencia"; //copied from es-cl
$text['label-concurrent-limit']['fr-ca'] = "Appels Simultanés"; //copied from fr-fr
$text['label-concurrent-limit']['fr-fr'] = "Appels Simultanés";
$text['label-concurrent-limit']['he-il'] = "";
$text['label-concurrent-limit']['it-it'] = "Limite Chiamate Contemporanee";
$text['label-concurrent-limit']['nl-nl'] = "Maximaal aantal gelijktijdige oproepen";
$text['label-concurrent-limit']['pl-pl'] = "Limit jednoczesnych rozmów";
$text['label-concurrent-limit']['pt-br'] = "Limite de chamadas simultâneas";
$text['label-concurrent-limit']['pt-pt'] = "Limite de chamadas concorrentes";
$text['label-concurrent-limit']['ro-ro'] = "";
$text['label-concurrent-limit']['ru-ru'] = "Ограничение параллельных вызовов";
$text['label-concurrent-limit']['sv-se'] = "Samtidig Gräns";
$text['label-concurrent-limit']['uk-ua'] = "Обмеження одночасної кількості";

$text['label-callerid-number']['en-us'] = "Caller ID Number";
$text['label-callerid-number']['en-gb'] = "Caller ID Number";
$text['label-callerid-number']['ar-eg'] = "";
$text['label-callerid-number']['de-at'] = "Anruferkennung (Nummer)"; //copied from de-de
$text['label-callerid-number']['de-ch'] = "Anruferkennung (Nummer)"; //copied from de-de
$text['label-callerid-number']['de-de'] = "Anruferkennung (Nummer)";
$text['label-callerid-number']['es-cl'] = "Número de Origen";
$text['label-callerid-number']['es-mx'] = "Número de Origen"; //copied from es-cl
$text['label-callerid-number']['fr-ca'] = "Numéro d'appelant"; //copied from fr-fr
$text['label-callerid-number']['fr-fr'] = "Numéro d'appelant";
$text['label-callerid-number']['he-il'] = "";
$text['label-callerid-number']['it-it'] = "Numero Chiamante";
$text['label-callerid-number']['nl-nl'] = "CID Nummer";
$text['label-callerid-number']['pl-pl'] = "Prezentacja numeru dzwoniącego";
$text['label-callerid-number']['pt-br'] = "Número do discador";
$text['label-callerid-number']['pt-pt'] = "Número do Chamador";
$text['label-callerid-number']['ro-ro'] = "";
$text['label-callerid-number']['ru-ru'] = "Caller ID Номер";
$text['label-callerid-number']['sv-se'] = "Caller ID Nummer";
$text['label-callerid-number']['uk-ua'] = "Caller ID Номер";

$text['label-caller-id-name']['en-us'] = "Caller ID Name";
$text['label-caller-id-name']['en-gb'] = "Caller ID Name";
$text['label-caller-id-name']['ar-eg'] = "";
$text['label-caller-id-name']['de-at'] = "Anruferkennung (Name)"; //copied from de-de
$text['label-caller-id-name']['de-ch'] = "Anruferkennung (Name)"; //copied from de-de
$text['label-caller-id-name']['de-de'] = "Anruferkennung (Name)";
$text['label-caller-id-name']['es-cl'] = "Nombre de origen";
$text['label-caller-id-name']['es-mx'] = "Nombre de origen"; //copied from es-cl
$text['label-caller-id-name']['fr-ca'] = "Nom d'appelant"; //copied from fr-fr
$text['label-caller-id-name']['fr-fr'] = "Nom d'appelant";
$text['label-caller-id-name']['he-il'] = "";
$text['label-caller-id-name']['it-it'] = "Nome Chiamante";
$text['label-caller-id-name']['nl-nl'] = "CID Naam";
$text['label-caller-id-name']['pl-pl'] = "Prezentacja nazwy dzwoniącego";
$text['label-caller-id-name']['pt-br'] = "Nome do discador";
$text['label-caller-id-name']['pt-pt'] = "Nome do Chamador";
$text['label-caller-id-name']['ro-ro'] = "";
$text['label-caller-id-name']['ru-ru'] = "Caller ID Имя";
$text['label-caller-id-name']['sv-se'] = "Caller ID Namn";
$text['label-caller-id-name']['uk-ua'] = "Caller ID Ім’я";

$text['label-call-broadcasts']['en-us'] = "Call Broadcasts";
$text['label-call-broadcasts']['en-gb'] = "Call Broadcasts";
$text['label-call-broadcasts']['ar-eg'] = "";
$text['label-call-broadcasts']['de-at'] = "Rundrufe"; //copied from de-de
$text['label-call-broadcasts']['de-ch'] = "Rundrufe"; //copied from de-de
$text['label-call-broadcasts']['de-de'] = "Rundrufe";
$text['label-call-broadcasts']['es-cl'] = "Llamadas Masivas (Broadcast)";
$text['label-call-broadcasts']['es-mx'] = "Llamadas Masivas (Broadcast)"; //copied from es-cl
$text['label-call-broadcasts']['fr-ca'] = "Diffusions d'appels"; //copied from fr-fr
$text['label-call-broadcasts']['fr-fr'] = "Diffusions d'appels";
$text['label-call-broadcasts']['he-il'] = "";
$text['label-call-broadcasts']['it-it'] = "Chiamate Multiple";
$text['label-call-broadcasts']['nl-nl'] = "Omroepen";
$text['label-call-broadcasts']['pl-pl'] = "Rozsyłanie rozmów";
$text['label-call-broadcasts']['pt-br'] = "Chamadas broadcast";
$text['label-call-broadcasts']['pt-pt'] = "Chamadas de Broadcast";
$text['label-call-broadcasts']['ro-ro'] = "";
$text['label-call-broadcasts']['ru-ru'] = "Массовые вызовы";
$text['label-call-broadcasts']['sv-se'] = "Samtalsdistributioner";
$text['label-call-broadcasts']['uk-ua'] = "Трансляція дзвінків";

$text['label-call-broadcast']['en-us'] = "Call Broadcast";
$text['label-call-broadcast']['en-gb'] = "Call Broadcast";
$text['label-call-broadcast']['ar-eg'] = "";
$text['label-call-broadcast']['de-at'] = "Rundrufe"; //copied from de-de
$text['label-call-broadcast']['de-ch'] = "Rundrufe"; //copied from de-de
$text['label-call-broadcast']['de-de'] = "Rundrufe";
$text['label-call-broadcast']['es-cl'] = "Llamada Masiva (Broadcast)";
$text['label-call-broadcast']['es-mx'] = "Llamada Masiva (Broadcast)"; //copied from es-cl
$text['label-call-broadcast']['fr-ca'] = "Diffusion d'appels"; //copied from fr-fr
$text['label-call-broadcast']['fr-fr'] = "Diffusion d'appels";
$text['label-call-broadcast']['he-il'] = "";
$text['label-call-broadcast']['it-it'] = "Chiamata Multipla";
$text['label-call-broadcast']['nl-nl'] = "Omroep";
$text['label-call-broadcast']['pl-pl'] = "Rozsyłanie rozmów";
$text['label-call-broadcast']['pt-br'] = "Chamada de broadcast";
$text['label-call-broadcast']['pt-pt'] = "Chamada de Broadcast";
$text['label-call-broadcast']['ro-ro'] = "";
$text['label-call-broadcast']['ru-ru'] = "Массовый вызов";
$text['label-call-broadcast']['sv-se'] = "Samtalsdistribution";
$text['label-call-broadcast']['uk-ua'] = "Трансляція дзвінка";

$text['label-avmd']['en-us'] = "Voicemail Detection";
$text['label-avmd']['en-gb'] = "Voicemail Detection";
$text['label-avmd']['ar-eg'] = "";
$text['label-avmd']['de-at'] = "Erkennung von Sprachnachrichten"; //copied from de-de
$text['label-avmd']['de-ch'] = "Erkennung von Sprachnachrichten"; //copied from de-de
$text['label-avmd']['de-de'] = "Erkennung von Sprachnachrichten";
$text['label-avmd']['es-cl'] = "Detección de correo de voz";
$text['label-avmd']['es-mx'] = "Detección de correo de voz"; //copied from es-cl
$text['label-avmd']['fr-ca'] = "Détection de la messagerie vocale"; //copied from fr-fr
$text['label-avmd']['fr-fr'] = "Détection de la messagerie vocale";
$text['label-avmd']['he-il'] = "";
$text['label-avmd']['it-it'] = "Rilevamento Segreteria";
$text['label-avmd']['nl-nl'] = "Antwoordapparaat ontdekt";
$text['label-avmd']['pl-pl'] = "Wykrywanie poczty głosowej";
$text['label-avmd']['pt-br'] = "Detecção Voicemail";
$text['label-avmd']['pt-pt'] = "Voicemail Detecção";
$text['label-avmd']['ro-ro'] = "";
$text['label-avmd']['ru-ru'] = "Определение голосовой почты";
$text['label-avmd']['sv-se'] = "Känn Av Röstbrevlåda";
$text['label-avmd']['uk-ua'] = "Виявлення голосової пошти";

$text['label-broadcast_toll_allow']['en-us'] = "Toll Allow";
$text['label-broadcast_toll_allow']['en-gb'] = "Toll Allow";
$text['label-broadcast_toll_allow']['ar-eg'] = "";
$text['label-broadcast_toll_allow']['de-at'] = "Berechtigung"; //copied from de-de
$text['label-broadcast_toll_allow']['de-ch'] = "Berechtigung"; //copied from de-de
$text['label-broadcast_toll_allow']['de-de'] = "Berechtigung";
$text['label-broadcast_toll_allow']['es-cl'] = "Permitir Tarifas Especiales";
$text['label-broadcast_toll_allow']['es-mx'] = "Permitir Tarifas Especiales"; //copied from es-cl
$text['label-broadcast_toll_allow']['fr-ca'] = "droits"; //copied from fr-fr
$text['label-broadcast_toll_allow']['fr-fr'] = "droits";
$text['label-broadcast_toll_allow']['he-il'] = "";
$text['label-broadcast_toll_allow']['it-it'] = "Destinazioni Abilitate";
$text['label-broadcast_toll_allow']['nl-nl'] = "betaald gesprek toestaan";
$text['label-broadcast_toll_allow']['pl-pl'] = "Zezwalaj na drogie/szczególwe połaczenia";
$text['label-broadcast_toll_allow']['pt-br'] = "Categoria de Ligação"; //copied from pt-pt
$text['label-broadcast_toll_allow']['pt-pt'] = "Permissões";
$text['label-broadcast_toll_allow']['ro-ro'] = "";
$text['label-broadcast_toll_allow']['ru-ru'] = "Разрешить Платное Соединение";
$text['label-broadcast_toll_allow']['sv-se'] = "Toll Allow";
$text['label-broadcast_toll_allow']['uk-ua'] = "";

$text['label-accountcode']['en-us'] = "Accountcode";
$text['label-accountcode']['en-gb'] = "Accountcode";
$text['label-accountcode']['ar-eg'] = "";
$text['label-accountcode']['de-at'] = "Kontoschlüssel"; //copied from de-de
$text['label-accountcode']['de-ch'] = "Kontoschlüssel"; //copied from de-de
$text['label-accountcode']['de-de'] = "Kontoschlüssel";
$text['label-accountcode']['es-cl'] = "Código de cuenta";
$text['label-accountcode']['es-mx'] = "Código de cuenta"; //copied from es-cl
$text['label-accountcode']['fr-ca'] = "Code de compte"; //copied from fr-fr
$text['label-accountcode']['fr-fr'] = "Code de compte";
$text['label-accountcode']['he-il'] = "קוד חשבון";
$text['label-accountcode']['it-it'] = "";
$text['label-accountcode']['nl-nl'] = "Account code";
$text['label-accountcode']['pl-pl'] = "Numer konta billingowego";
$text['label-accountcode']['pt-br'] = "Código da conta";
$text['label-accountcode']['pt-pt'] = "Accountcode";
$text['label-accountcode']['ro-ro'] = "";
$text['label-accountcode']['ru-ru'] = "Код Авторизации";
$text['label-accountcode']['sv-se'] = "Accountcode";
$text['label-accountcode']['uk-ua'] = "Код облікового запису";

$text['label-sample_file']['en-us'] = "Sample CSV File";
$text['label-sample_file']['en-gb'] = "Sample CSV File";
$text['label-sample_file']['ar-eg'] = "Sample CSV File";
$text['label-sample_file']['de-at'] = "Sample CSV File";
$text['label-sample_file']['de-ch'] = "Sample CSV File";
$text['label-sample_file']['de-de'] = "Sample CSV File";
$text['label-sample_file']['es-cl'] = "Sample CSV File";
$text['label-sample_file']['es-mx'] = "Sample CSV File";
$text['label-sample_file']['fr-ca'] = "Sample CSV File";
$text['label-sample_file']['fr-fr'] = "Sample CSV File";
$text['label-sample_file']['he-il'] = "Sample CSV File";
$text['label-sample_file']['it-it'] = "Sample CSV File";
$text['label-sample_file']['nl-nl'] = "Voorbeeld CSV File";
$text['label-sample_file']['pl-pl'] = "Sample CSV File";
$text['label-sample_file']['pt-br'] = "Sample CSV File";
$text['label-sample_file']['pt-pt'] = "Sample CSV File";
$text['label-sample_file']['ro-ro'] = "Sample CSV File";
$text['label-sample_file']['ru-ru'] = "Sample CSV File";
$text['label-sample_file']['sv-se'] = "Sample CSV File";
$text['label-sample_file']['uk-ua'] = "Sample CSV File";

$text['label-list_example']['en-us'] = "Number|First,Last\nNumber|First,Last\n...";
$text['label-list_example']['en-gb'] = "Number|First,Last\nNumber|First,Last\n...";
$text['label-list_example']['ar-eg'] = "Number|First,Last\nNumber|First,Last\n...";
$text['label-list_example']['de-at'] = "Number|First,Last\nNumber|First,Last\n...";
$text['label-list_example']['de-ch'] = "Number|First,Last\nNumber|First,Last\n...";
$text['label-list_example']['de-de'] = "Number|First,Last\nNumber|First,Last\n...";
$text['label-list_example']['es-cl'] = "Number|First,Last\nNumber|First,Last\n...";
$text['label-list_example']['es-mx'] = "Number|First,Last\nNumber|First,Last\n...";
$text['label-list_example']['fr-ca'] = "Number|First,Last\nNumber|First,Last\n...";
$text['label-list_example']['fr-fr'] = "Number|First,Last\nNumber|First,Last\n...";
$text['label-list_example']['he-il'] = "Number|First,Last\nNumber|First,Last\n...";
$text['label-list_example']['it-it'] = "Number|First,Last\nNumber|First,Last\n...";
$text['label-list_example']['nl-nl'] = "Nummer|Eerste,Laatste\nNummer|Eerste,Laatste\n...";
$text['label-list_example']['pl-pl'] = "Number|First,Last\nNumber|First,Last\n...";
$text['label-list_example']['pt-br'] = "Number|First,Last\nNumber|First,Last\n...";
$text['label-list_example']['pt-pt'] = "Number|First,Last\nNumber|First,Last\n...";
$text['label-list_example']['ro-ro'] = "Number|First,Last\nNumber|First,Last\n...";
$text['label-list_example']['ru-ru'] = "Number|First,Last\nNumber|First,Last\n...";
$text['label-list_example']['sv-se'] = "Number|First,Last\nNumber|First,Last\n...";
$text['label-list_example']['uk-ua'] = "Number|First,Last\nNumber|First,Last\n...";

$text['description-start_time']['en-us'] = "Is the time in seconds to start sending calls.";
$text['description-start_time']['en-gb'] = "";
$text['description-start_time']['ar-eg'] = "";
$text['description-start_time']['de-at'] = ""; //copied from de-de
$text['description-start_time']['de-ch'] = ""; //copied from de-de
$text['description-start_time']['de-de'] = "";
$text['description-start_time']['es-cl'] = "";
$text['description-start_time']['es-mx'] = "";
$text['description-start_time']['fr-ca'] = "";
$text['description-start_time']['fr-fr'] = "";
$text['description-start_time']['he-il'] = "";
$text['description-start_time']['it-it'] = "";
$text['description-start_time']['nl-nl'] = "";
$text['description-start_time']['pl-pl'] = "";
$text['description-start_time']['pt-br'] = ""; //copied from pt-pt
$text['description-start_time']['pt-pt'] = "";
$text['description-start_time']['ro-ro'] = "";
$text['description-start_time']['ru-ru'] = "";
$text['description-start_time']['sv-se'] = "";
$text['description-start_time']['uk-ua'] = "";

$text['description-accountcode']['en-us'] = "Account code used most often used for billing systems.";
$text['description-accountcode']['en-gb'] = "";
$text['description-accountcode']['ar-eg'] = "";
$text['description-accountcode']['de-at'] = ""; //copied from de-de
$text['description-accountcode']['de-ch'] = ""; //copied from de-de
$text['description-accountcode']['de-de'] = "";
$text['description-accountcode']['es-cl'] = "";
$text['description-accountcode']['es-mx'] = "";
$text['description-accountcode']['fr-ca'] = "";
$text['description-accountcode']['fr-fr'] = "";
$text['description-accountcode']['he-il'] = "";
$text['description-accountcode']['it-it'] = "";
$text['description-accountcode']['nl-nl'] = "";
$text['description-accountcode']['pl-pl'] = "";
$text['description-accountcode']['pt-br'] = ""; //copied from pt-pt
$text['description-accountcode']['pt-pt'] = "";
$text['description-accountcode']['ro-ro'] = "";
$text['description-accountcode']['ru-ru'] = "";
$text['description-accountcode']['sv-se'] = "";
$text['description-accountcode']['uk-ua'] = "";

$text['description-timeout']['en-us'] = "Specify the absolute timeout in seconds.";
$text['description-timeout']['en-gb'] = "Specify the absolute timeout in seconds.";
$text['description-timeout']['ar-eg'] = "";
$text['description-timeout']['de-at'] = "Geben Sie die absolute Zeitüberschreitung in Sekunden an."; //copied from de-de
$text['description-timeout']['de-ch'] = "Geben Sie die absolute Zeitüberschreitung in Sekunden an."; //copied from de-de
$text['description-timeout']['de-de'] = "Geben Sie die absolute Zeitüberschreitung in Sekunden an.";
$text['description-timeout']['es-cl'] = "";
$text['description-timeout']['es-mx'] = "";
$text['description-timeout']['fr-ca'] = "Spécifiez le délai d'expiration absolu en secondes";
$text['description-timeout']['fr-fr'] = "Spécifiez le délai d'expiration absolu en secondes";
$text['description-timeout']['he-il'] = "";
$text['description-timeout']['it-it'] = "";
$text['description-timeout']['nl-nl'] = "Geef de absolute tijdsoverschrijding in seconden aan.";
$text['description-timeout']['pl-pl'] = "Ilość milisekund oczekiwania po odtworzeniu nagrania lub potwierdzenia makro.";
$text['description-timeout']['pt-br'] = "Limite de tempo (em milissegundos) de espera após reproduzir gravações ou confirmar a macro."; //copied from pt-pt
$text['description-timeout']['pt-pt'] = "Limite de tempo (em milissegundos) de espera após reproduzir gravações ou confirmar a macro.";
$text['description-timeout']['ro-ro'] = "";
$text['description-timeout']['ru-ru'] = "Время ожидания (в миллисекундах) после воспроизведения записи или подтверждения макроса.";
$text['description-timeout']['sv-se'] = "Specificera den absoluta timeout:en i sekunder.";
$text['description-timeout']['uk-ua'] = "";

$text['description-phone']['en-us'] = "Select a TXT/CSV file for upload, or enter Phone Numbers one per line in the format shown above.";
$text['description-phone']['en-gb'] = "Select a TXT/CSV file for upload, or enter Phone Numbers one per line in the format shown above.";
$text['description-phone']['ar-eg'] = "";
$text['description-phone']['de-at'] = "Optional: Ergänzen Sie eine Liste von Telefonnummern, eine Nummer pro Zeile im folgenden Format: 123-123-1234|Nachname,Vorname"; //copied from de-de
$text['description-phone']['de-ch'] = "Optional: Ergänzen Sie eine Liste von Telefonnummern, eine Nummer pro Zeile im folgenden Format: 123-123-1234|Nachname,Vorname"; //copied from de-de
$text['description-phone']['de-de'] = "Optional: Ergänzen Sie eine Liste von Telefonnummern, eine Nummer pro Zeile im folgenden Format: 123-123-1234|Nachname,Vorname";
$text['description-phone']['es-cl'] = "Opcional, definir una lista de números de telefono, uno por línea en el siguiente formato: 123-123-1234|Apellido,Nombre";
$text['description-phone']['es-mx'] = "Opcional, definir una lista de números de telefono, uno por línea en el siguiente formato: 123-123-1234|Apellido,Nombre"; //copied from es-cl
$text['description-phone']['fr-ca'] = "Optionnel, Insérer une liste de numéros de téléphone, un par ligne, dans le format suivant ; 0123456789|Nom,Prénom"; //copied from fr-fr
$text['description-phone']['fr-fr'] = "Optionnel, Insérer une liste de numéros de téléphone, un par ligne, dans le format suivant ; 0123456789|Nom,Prénom";
$text['description-phone']['he-il'] = "";
$text['description-phone']['it-it'] = "Opzionale, inserire una lista di numeri di telefono, uno per riga, nel formato 123-123-1234|Cognome,Nome";
$text['description-phone']['nl-nl'] = "Selecteer een TXT/CSV file om te 'uploaden' of voer Telefoonnummers in een per regel in het bovenstaande formaat.";
$text['description-phone']['pl-pl'] = "Opcjonalne - ułóż listę numerów (jeden pod drugim) w formacie: 123-123-1234|Nazwisko,Imię";
$text['description-phone']['pt-br'] = "Opcional, definir uma lista de números de telefone, um por linha, no seguinte formato: 210000000|Apelido,Primeiro Nome.";
$text['description-phone']['pt-pt'] = "Opcional, definir uma lista de números de telefone, um por linha, no seguinte formato: 210000000|Apelido,Primeiro Nome";
$text['description-phone']['ro-ro'] = "";
$text['description-phone']['ru-ru'] = "Дополнительно, задайте список телефонных номеров, по одному в ряд, в формате: 123-123-1234|Фамилия,Имя";
$text['description-phone']['sv-se'] = "Frivillig, fyll i en lista med nummer (ett per rad) i följande format: 123-123-1234|Efternamn,Förnamn";
$text['description-phone']['uk-ua'] = "Додатково, задайте список телефонних номерів по одному на рядок в наступному форматі: 123-123-1234|Прізвище,ім'я";

$text['description-name']['en-us'] = "Enter the name here.";
$text['description-name']['en-gb'] = "Enter the name here.";
$text['description-name']['ar-eg'] = "";
$text['description-name']['de-at'] = "Geben Sie den Namen an."; //copied from de-de
$text['description-name']['de-ch'] = "Geben Sie den Namen an."; //copied from de-de
$text['description-name']['de-de'] = "Geben Sie den Namen an.";
$text['description-name']['es-cl'] = "Ingrese el nombre aquí.";
$text['description-name']['es-mx'] = "Ingrese el nombre aquí."; //copied from es-cl
$text['description-name']['fr-ca'] = "Insérer le Nom."; //copied from fr-fr
$text['description-name']['fr-fr'] = "Insérer le Nom.";
$text['description-name']['he-il'] = "הכנס את השם";
$text['description-name']['it-it'] = "Inserire il nome qui.";
$text['description-name']['nl-nl'] = "Voer de naam hier in.";
$text['description-name']['pl-pl'] = "Wprowadź nazwę";
$text['description-name']['pt-br'] = "Insira o nome do broadcast.";
$text['description-name']['pt-pt'] = "Introduza o nome aqui.";
$text['description-name']['ro-ro'] = "";
$text['description-name']['ru-ru'] = "Введите имя";
$text['description-name']['sv-se'] = "Skriv in namnet här.";
$text['description-name']['uk-ua'] = "Введіть назву";

$text['description-info']['en-us'] = "Enter the description here.";
$text['description-info']['en-gb'] = "Enter the description here.";
$text['description-info']['ar-eg'] = "";
$text['description-info']['de-at'] = "Geben Sie eine Beschreibung an."; //copied from de-de
$text['description-info']['de-ch'] = "Geben Sie eine Beschreibung an."; //copied from de-de
$text['description-info']['de-de'] = "Geben Sie eine Beschreibung an.";
$text['description-info']['es-cl'] = "Ingrese descripción aquí.";
$text['description-info']['es-mx'] = "Ingrese descripción aquí."; //copied from es-cl
$text['description-info']['fr-ca'] = "Entrez la description ici";
$text['description-info']['fr-fr'] = "Entrez la description ici";
$text['description-info']['he-il'] = "הכנס תאור";
$text['description-info']['it-it'] = "Inserire la descrizione qui.";
$text['description-info']['nl-nl'] = "Voer de omschrijving hier in.";
$text['description-info']['pl-pl'] = "Wprowadź opis";
$text['description-info']['pt-br'] = "Inisra uma descrição";
$text['description-info']['pt-pt'] = "Insira a descrição aqui.";
$text['description-info']['ro-ro'] = "";
$text['description-info']['ru-ru'] = "Введите описание";
$text['description-info']['sv-se'] = "Ange beskrivning här.";
$text['description-info']['uk-ua'] = "Введіть опис";

$text['description-destination']['en-us'] = "Send the call to the extension an IVR Menu, Conference Room, or any other number.";
$text['description-destination']['en-gb'] = "Send the call to the extension an IVR Menu, Conference Room, or any other number.";
$text['description-destination']['ar-eg'] = "";
$text['description-destination']['de-at'] = "Der Anruf wird an eine Nebenstelle, eine Automatische Vermittlung, ein Konferenzraum oder jede andere Nummer weitergeleitet."; //copied from de-de
$text['description-destination']['de-ch'] = "Der Anruf wird an eine Nebenstelle, eine Automatische Vermittlung, ein Konferenzraum oder jede andere Nummer weitergeleitet."; //copied from de-de
$text['description-destination']['de-de'] = "Der Anruf wird an eine Nebenstelle, eine Automatische Vermittlung, ein Konferenzraum oder jede andere Nummer weitergeleitet.";
$text['description-destination']['es-cl'] = "Enviar la llamada a extension a IVR, conferencias o cualquier otro número.";
$text['description-destination']['es-mx'] = "Enviar la llamada a extension a IVR, conferencias o cualquier otro número."; //copied from es-cl
$text['description-destination']['fr-ca'] = "Emettre l'appel vers un SVI, salle de conférence, ou tout autre numéro."; //copied from fr-fr
$text['description-destination']['fr-fr'] = "Emettre l'appel vers un SVI, salle de conférence, ou tout autre numéro.";
$text['description-destination']['he-il'] = "";
$text['description-destination']['it-it'] = "Connetti la chiamata con un interno, un IVR, un'audioconferenza, o qualsiasi altro servizio.";
$text['description-destination']['nl-nl'] = "Send de oproep naar een toestel, IVR Menu, conferentie of een willekeurig ander nummer.";
$text['description-destination']['pl-pl'] = "Wybierz numer docelowy.";
$text['description-destination']['pt-br'] = "Enviar a chamada para a extensão de um menu de IVR, Sala de Conferência ou qualquer outro número. ";
$text['description-destination']['pt-pt'] = "Enviar a chamada para a extensão de um menu de IVR, Sala de Conferência ou qualquer outro número.";
$text['description-destination']['ro-ro'] = "";
$text['description-destination']['ru-ru'] = "Отправить вызов на внутренний номер, IVR, конференцию или любой другой номер.";
$text['description-destination']['sv-se'] = "Skicka samtalet till en anknytning, IVR Meny, Konferens Rum eller något annat nummer.";
$text['description-destination']['uk-ua'] = "Відправити дзвінок на розширення, меню IVR, конференцію, або будь-який інший номер.";

$text['description-concurrent-limit']['en-us'] = "Limit the approximate number of concurrent calls. Leave this empty for no limit.";
$text['description-concurrent-limit']['en-gb'] = "Limit the approximate number of concurrent calls. Leave this empty for no limit.";
$text['description-concurrent-limit']['ar-eg'] = "";
$text['description-concurrent-limit']['de-at'] = "Begrenzt die Anzahl gleichzeitiger Anrufe. Kein Limit wenn leer gelassen."; //copied from de-de
$text['description-concurrent-limit']['de-ch'] = "Begrenzt die Anzahl gleichzeitiger Anrufe. Kein Limit wenn leer gelassen."; //copied from de-de
$text['description-concurrent-limit']['de-de'] = "Begrenzt die Anzahl gleichzeitiger Anrufe. Kein Limit wenn leer gelassen.";
$text['description-concurrent-limit']['es-cl'] = "Limitar el número de llamadas simultaneas. Deje en blanco para no establecer un límite.";
$text['description-concurrent-limit']['es-mx'] = "Limitar el número de llamadas simultaneas. Deje en blanco para no establecer un límite."; //copied from es-cl
$text['description-concurrent-limit']['fr-ca'] = "Limite le nombre d'appels concurrents. Laisser vide pour illimité."; //copied from fr-fr
$text['description-concurrent-limit']['fr-fr'] = "Limite le nombre d'appels concurrents. Laisser vide pour illimité.";
$text['description-concurrent-limit']['he-il'] = "";
$text['description-concurrent-limit']['it-it'] = "Limita approssimativamente il numero di chiamate contemporanee. Lasciare vuoto per nessun limite.";
$text['description-concurrent-limit']['nl-nl'] = "Beperk de geschatter aantallen gelijktijdige oproepen. Laat leeg om geen limiet op te geven.";
$text['description-concurrent-limit']['pl-pl'] = "Ogranicz liczbę równoczesnych  połączeń. Aby nie było limitu zostaw to pole puste.";
$text['description-concurrent-limit']['pt-br'] = "Limitar o número de chamadas simultâneas. Deixe este campo em branco para não ter limite.";
$text['description-concurrent-limit']['pt-pt'] = "Limitar o número de chamadas concurrentes. Deixe este campo em branco para não ter limite.";
$text['description-concurrent-limit']['ro-ro'] = "";
$text['description-concurrent-limit']['ru-ru'] = "Ограничение примерного количества параллельных вызовов. Оставьте пустым для его отсутствия.";
$text['description-concurrent-limit']['sv-se'] = "Begränsa ungefärliga antalet samtidiga samtal. Lämna det här tomt för ingen gräns.";
$text['description-concurrent-limit']['uk-ua'] = "Обмеження приблизної кількості одночасних дзвінків. Якщо пусто - без обмежень";

$text['description-caller-id-number']['en-us'] = "Applicable if the provider that allow the Caller ID number to be sent. default: 0000000000";
$text['description-caller-id-number']['en-gb'] = "Applicable if the provider that allow the Caller ID number to be sent. default: 0000000000";
$text['description-caller-id-number']['ar-eg'] = "";
$text['description-caller-id-number']['de-at'] = "Geben Sie die Anruferkennung (Nummer) hier ein."; //copied from de-de
$text['description-caller-id-number']['de-ch'] = "Geben Sie die Anruferkennung (Nummer) hier ein."; //copied from de-de
$text['description-caller-id-number']['de-de'] = "Geben Sie die Anruferkennung (Nummer) hier ein.";
$text['description-caller-id-number']['es-cl'] = "";
$text['description-caller-id-number']['es-mx'] = "";
$text['description-caller-id-number']['fr-ca'] = "Applicable uniquement si le fournisseur d'accès authorise l'acheminement du numéro d'appelant. Par défaut: 0000000000"; //copied from fr-fr
$text['description-caller-id-number']['fr-fr'] = "Applicable uniquement si le fournisseur d'accès authorise l'acheminement du numéro d'appelant. Par défaut: 0000000000";
$text['description-caller-id-number']['he-il'] = "";
$text['description-caller-id-number']['it-it'] = "Si usa se il provider permette la modifica del numero chiamante. Default: 0000000000";
$text['description-caller-id-number']['nl-nl'] = "Geef het afzender telefoonnummer hier in. standaard: 0000000000";
$text['description-caller-id-number']['pl-pl'] = "Zastosowane w przypadku jeżeli operator zezwala na prezentację numeru. Standardowo prezentacja jest w formacie: 0000000000";
$text['description-caller-id-number']['pt-br'] = "Aplicável se o provedor permitir o envio do número do originador das chamadas. Omissão: 0000000000.";
$text['description-caller-id-number']['pt-pt'] = "Aplicável se o provedor permitir o envio do número do originador das chamadas. Omissão: 0000000000";
$text['description-caller-id-number']['ro-ro'] = "";
$text['description-caller-id-number']['ru-ru'] = "Используется, если провайдер поддерживает передачу CallerID(number). По умолчанию: 0000000000";
$text['description-caller-id-number']['sv-se'] = "Gäller om leverantör tillåter att Caller ID nummer skickas. Standard: 0000000000";
$text['description-caller-id-number']['uk-ua'] = "Стосується, якщо постачальник, дозволяє надсилати номер абонента (Caller ID номер). За замовчуванням: 0000000000";

$text['description-caller-id-name']['en-us'] = "Applicable if the provider allow the Caller ID Name to be set. default: anonymous";
$text['description-caller-id-name']['en-gb'] = "Applicable if the provider allow the Caller ID Name to be set. default: anonymous";
$text['description-caller-id-name']['ar-eg'] = "";
$text['description-caller-id-name']['de-at'] = "Geben Sie die Anruferkennung (Name) hier ein, sofern der Provider dieses unterstützt. Default: anonym."; //copied from de-de
$text['description-caller-id-name']['de-ch'] = "Geben Sie die Anruferkennung (Name) hier ein, sofern der Provider dieses unterstützt. Default: anonym."; //copied from de-de
$text['description-caller-id-name']['de-de'] = "Geben Sie die Anruferkennung (Name) hier ein, sofern der Provider dieses unterstützt. Default: anonym.";
$text['description-caller-id-name']['es-cl'] = "Applicable si el proveedor permite enviar el número de origen. Por defecto: 0000000000";
$text['description-caller-id-name']['es-mx'] = "Applicable si el proveedor permite enviar el número de origen. Por defecto: 0000000000"; //copied from es-cl
$text['description-caller-id-name']['fr-ca'] = "Applicable uniquement si le fournisseur d'accès authorise l'acheminement du nom d'appelant. Par défaut: anonymous"; //copied from fr-fr
$text['description-caller-id-name']['fr-fr'] = "Applicable uniquement si le fournisseur d'accès authorise l'acheminement du nom d'appelant. Par défaut: anonymous";
$text['description-caller-id-name']['he-il'] = "";
$text['description-caller-id-name']['it-it'] = "Si usa se il provider permette la modifica del nome chiamante. Default: anonymous";
$text['description-caller-id-name']['nl-nl'] = "Geef de afzenderkenmerk (naam) hier, voorzover de provider die ondersteund. Standaard: anoniem ";
$text['description-caller-id-name']['pl-pl'] = "Zastosowane w przypadku jeżeli operator zezwala na prezentację nazwy. Standardowo prezentacja jest w formacie: 0000000000";
$text['description-caller-id-name']['pt-br'] = "Aplicável se o provedor de telefônia liberar o nome de quem está discando. Por padrão: anonymous (anônimo).";
$text['description-caller-id-name']['pt-pt'] = "Aplicável se o provedor permitir o envio do nome do originador das chamadas. Omissão: anonymous";
$text['description-caller-id-name']['ro-ro'] = "";
$text['description-caller-id-name']['ru-ru'] = "Используется, если провайдер поддерживает передачу CallerID(name). По умолчанию: anonymous";
$text['description-caller-id-name']['sv-se'] = "Gäller om leverantör tillåter att Caller ID namn skickas. Standard: anonymous";
$text['description-caller-id-name']['uk-ua'] = "Стосується, якщо постачальник, дозволяє надсилати ім’я абонента (Caller ID Ім’я). За замовчуванням: anonymous";

$text['description-avmd']['en-us'] = "Select whether to enable or disable the detection of voicemail messaging and answering machine systems.";
$text['description-avmd']['en-gb'] = "Select whether to enable or disable the detection of voicemail messaging and answering machine systems.";
$text['description-avmd']['ar-eg'] = "";
$text['description-avmd']['de-at'] = "Wählen Sie ob die Erkennung von Sprach-Mailboxen und automatischen Anrufbeantwortern Ein- oder Ausgeschaltet werden soll."; //copied from de-de
$text['description-avmd']['de-ch'] = "Wählen Sie ob die Erkennung von Sprach-Mailboxen und automatischen Anrufbeantwortern Ein- oder Ausgeschaltet werden soll."; //copied from de-de
$text['description-avmd']['de-de'] = "Wählen Sie ob die Erkennung von Sprach-Mailboxen und automatischen Anrufbeantwortern Ein- oder Ausgeschaltet werden soll.";
$text['description-avmd']['es-cl'] = "Seleccione si desea activar o desactivar la detección de sistemas de contestador automático de mensajes de correo de voz y.";
$text['description-avmd']['es-mx'] = "Seleccione si desea activar o desactivar la detección de sistemas de contestador automático de mensajes de correo de voz y."; //copied from es-cl
$text['description-avmd']['fr-ca'] = "Indiquez si vous souhaitez activer ou désactiver la détection de la messagerie vocale et les systèmes de machines de répondeur."; //copied from fr-fr
$text['description-avmd']['fr-fr'] = "Indiquez si vous souhaitez activer ou désactiver la détection de la messagerie vocale et les systèmes de machines de répondeur.";
$text['description-avmd']['he-il'] = "";
$text['description-avmd']['it-it'] = "Selezionare se si vuole abilitare o disabilitare il rilevamento delle segreterie telefoniche e dei messaggi registrati.";
$text['description-avmd']['nl-nl'] = "Selecteer of een antwoordapparaat detectie aan of uitgezet moet worden.";
$text['description-avmd']['pl-pl'] = "Wybierz, czy chcesz włączyć lub wyłączyć wykrywanie wiadomości poczty głosowej lub innych systemów automatycznego odbierania rozmów.";
$text['description-avmd']['pt-br'] = "Selecione se deseja ativar ou desativar a detecção de mensagens de correio de voz e sistemas de secretária eletrônica."; //copied from pt-pt
$text['description-avmd']['pt-pt'] = "Selecione se deseja ativar ou desativar a detecção de mensagens de correio de voz e sistemas de secretária eletrônica.";
$text['description-avmd']['ro-ro'] = "";
$text['description-avmd']['ru-ru'] = "Выберите, стоит ли использовать систему определения голосовой почты или автоответчика.";
$text['description-avmd']['sv-se'] = "Välj om deteketering av röstbrevlåda skall användas.";
$text['description-avmd']['uk-ua'] = "Виберіть, чи слід включити або відключити виявлення повідомлень голосової пошти і систему автовідповідача.";

$text['description-broadcast_toll_allow']['en-us'] = "Enter the toll allow value here.  (Examples: domestic,international,local)";
$text['description-broadcast_toll_allow']['en-gb'] = "Enter the toll allow value here.  (Examples: domestic,international,local)";
$text['description-broadcast_toll_allow']['ar-eg'] = "";
$text['description-broadcast_toll_allow']['de-at'] = "Geben Sie die Berechtigung an. (z.B.: domestic, international, local)"; //copied from de-de
$text['description-broadcast_toll_allow']['de-ch'] = "Geben Sie die Berechtigung an. (z.B.: domestic, international, local)"; //copied from de-de
$text['description-broadcast_toll_allow']['de-de'] = "Geben Sie die Berechtigung an. (z.B.: domestic, international, local)";
$text['description-broadcast_toll_allow']['es-cl'] = "Ingrese el tipo de tarifa especial a permitir (ej: doméstica, internacional, local).";
$text['description-broadcast_toll_allow']['es-mx'] = "Ingrese el tipo de tarifa especial a permitir (ej: doméstica, internacional, local)."; //copied from es-cl
$text['description-broadcast_toll_allow']['fr-ca'] = "Insérer les droits d'accès. (Exemples: domestic,international,local)"; //copied from fr-fr
$text['description-broadcast_toll_allow']['fr-fr'] = "Insérer les droits d'accès. (Exemples: domestic,international,local)";
$text['description-broadcast_toll_allow']['he-il'] = "";
$text['description-broadcast_toll_allow']['it-it'] = "Inserire qui le destinazioni permesse. (Es. fisso, mobile, internazionale, premium)";
$text['description-broadcast_toll_allow']['nl-nl'] = "Voer de betaalbaar waarde hier in (Voobeeld: domestic, international, local)";
$text['description-broadcast_toll_allow']['pl-pl'] = "Wpisz wartość drogich/szczegółowych połączeń.";
$text['description-broadcast_toll_allow']['pt-br'] = "Insira as categorias de ligação aqui. (Exemplos: Internacional, Local, DDD, DDI, Celular)";
$text['description-broadcast_toll_allow']['pt-pt'] = "Introduza as permissões aqui. (Exemplos: internacional, local)";
$text['description-broadcast_toll_allow']['ro-ro'] = "";
$text['description-broadcast_toll_allow']['ru-ru'] = "Введите здесь доступные значения. (Примеры: domestic,international,local)";
$text['description-broadcast_toll_allow']['sv-se'] = "Ange 'toll allow' värde här. (Exempel: domestic,international,local)";
$text['description-broadcast_toll_allow']['uk-ua'] = "";

$text['confirm-update']['en-us'] = "Update Complete";
$text['confirm-update']['en-gb'] = "Update Complete";
$text['confirm-update']['ar-eg'] = "";
$text['confirm-update']['de-at'] = "Aktualisierung durchgeführt"; //copied from de-de
$text['confirm-update']['de-ch'] = "Aktualisierung durchgeführt"; //copied from de-de
$text['confirm-update']['de-de'] = "Aktualisierung durchgeführt";
$text['confirm-update']['es-cl'] = "Actualización Completa";
$text['confirm-update']['es-mx'] = "Actualización Completa"; //copied from es-cl
$text['confirm-update']['fr-ca'] = "Mise à jour terminée"; //copied from fr-fr
$text['confirm-update']['fr-fr'] = "Mise à jour terminée";
$text['confirm-update']['he-il'] = "עידכון הושלם";
$text['confirm-update']['it-it'] = "Aggiornamento Completato.";
$text['confirm-update']['nl-nl'] = "Bijwerken gereed";
$text['confirm-update']['pl-pl'] = "Aktualizacja zakonczona";
$text['confirm-update']['pt-br'] = "Atualização Efetuada";
$text['confirm-update']['pt-pt'] = "Actualização Efectuada";
$text['confirm-update']['ro-ro'] = "";
$text['confirm-update']['ru-ru'] = "Обновление завершено";
$text['confirm-update']['sv-se'] = "Uppdatering Klar";
$text['confirm-update']['uk-ua'] = "Оновлення завершено";

$text['confirm-name']['en-us'] = "Please provide: Name";
$text['confirm-name']['en-gb'] = "Please provide: Name";
$text['confirm-name']['ar-eg'] = "";
$text['confirm-name']['de-at'] = "Bitte geben Sie den Namen an"; //copied from de-de
$text['confirm-name']['de-ch'] = "Bitte geben Sie den Namen an"; //copied from de-de
$text['confirm-name']['de-de'] = "Bitte geben Sie den Namen an";
$text['confirm-name']['es-cl'] = "Por favor agregue: Nombre";
$text['confirm-name']['es-mx'] = "Por favor agregue: Nombre"; //copied from es-cl
$text['confirm-name']['fr-ca'] = "Merci d'indiquer: Nom"; //copied from fr-fr
$text['confirm-name']['fr-fr'] = "Merci d'indiquer: Nom";
$text['confirm-name']['he-il'] = "";
$text['confirm-name']['it-it'] = "Prego fornire: Nome";
$text['confirm-name']['nl-nl'] = "Geef aub: Naam";
$text['confirm-name']['pl-pl'] = "Wprowadź: Nazwę";
$text['confirm-name']['pt-br'] = "Por favor insira: Nome";
$text['confirm-name']['pt-pt'] = "Por favor indique: Nome";
$text['confirm-name']['ro-ro'] = "";
$text['confirm-name']['ru-ru'] = "Пожалуйста, укажите: Имя";
$text['confirm-name']['sv-se'] = "Ange: Namn";
$text['confirm-name']['uk-ua'] = "Введіть назву";

$text['confirm-delete-info']['en-us'] = "Do you really want to delete this?";
$text['confirm-delete-info']['en-gb'] = "Do you really want to delete this?";
$text['confirm-delete-info']['ar-eg'] = "";
$text['confirm-delete-info']['de-at'] = "Wollen Sie das wirklich löschen?"; //copied from de-de
$text['confirm-delete-info']['de-ch'] = "Wollen Sie das wirklich löschen?"; //copied from de-de
$text['confirm-delete-info']['de-de'] = "Wollen Sie das wirklich löschen?";
$text['confirm-delete-info']['es-cl'] = "¿Desea realmente eliminar esto?";
$text['confirm-delete-info']['es-mx'] = "¿Desea realmente eliminar esto?"; //copied from es-cl
$text['confirm-delete-info']['fr-ca'] = "Voulez-vous vraiment supprimer cela?"; //copied from fr-fr
$text['confirm-delete-info']['fr-fr'] = "Voulez-vous vraiment supprimer cela?";
$text['confirm-delete-info']['he-il'] = "";
$text['confirm-delete-info']['it-it'] = "Vuoi veramente cancellarlo?";
$text['confirm-delete-info']['nl-nl'] = "Wilt u dit echt verwijderen?";
$text['confirm-delete-info']['pl-pl'] = "Czy na pewno chcesz to usunąć?";
$text['confirm-delete-info']['pt-br'] = "Deseja realmente remover isto?"; //copied from pt-pt
$text['confirm-delete-info']['pt-pt'] = "Deseja realmente remover isto?";
$text['confirm-delete-info']['ro-ro'] = "";
$text['confirm-delete-info']['ru-ru'] = "Вы действительно хотите это удалить?";
$text['confirm-delete-info']['sv-se'] = "Vill du verkligen ta bort detta?";
$text['confirm-delete-info']['uk-ua'] = "Ви дійсно бажаєте це видалити?";

$text['confirm-add']['en-us'] = "Add Complete";
$text['confirm-add']['en-gb'] = "Add Complete";
$text['confirm-add']['ar-eg'] = "";
$text['confirm-add']['de-at'] = "Erfolgreich hinzugefügt"; //copied from de-de
$text['confirm-add']['de-ch'] = "Erfolgreich hinzugefügt"; //copied from de-de
$text['confirm-add']['de-de'] = "Erfolgreich hinzugefügt";
$text['confirm-add']['es-cl'] = "Ingreso Completo";
$text['confirm-add']['es-mx'] = "Ingreso Completo"; //copied from es-cl
$text['confirm-add']['fr-ca'] = "Ajouté"; //copied from fr-fr
$text['confirm-add']['fr-fr'] = "Ajouté";
$text['confirm-add']['he-il'] = "הוספה הושלמה";
$text['confirm-add']['it-it'] = "Inserimento Completato";
$text['confirm-add']['nl-nl'] = "Toevoegen gereed";
$text['confirm-add']['pl-pl'] = "Dodano poprawnie";
$text['confirm-add']['pt-br'] = "Criação efetuada";
$text['confirm-add']['pt-pt'] = "Adição Efectuada";
$text['confirm-add']['ro-ro'] = "";
$text['confirm-add']['ru-ru'] = "Добавление завершено";
$text['confirm-add']['sv-se'] = "Tillagd";
$text['confirm-add']['uk-ua'] = "Додано";

$text['file-error']['en-us'] = "Sorry, File type not allowed";
$text['file-error']['en-gb'] = "Sorry, File type not allowed";
$text['file-error']['ar-eg'] = "";
$text['file-error']['de-at'] = "Entschuldigung, Dateityp nicht erlaubt"; //copied from de-de
$text['file-error']['de-ch'] = "Entschuldigung, Dateityp nicht erlaubt"; //copied from de-de
$text['file-error']['de-de'] = "Entschuldigung, Dateityp nicht erlaubt";
$text['file-error']['es-cl'] = "Lo sentimos, no se permite el tipo de archivo";
$text['file-error']['es-mx'] = "Lo sentimos, no se permite el tipo de archivo"; //copied from es-cl
$text['file-error']['fr-ca'] = "Désolé, le type de fichier n'est pas autorisé"; //copied from fr-fr
$text['file-error']['fr-fr'] = "Désolé, le type de fichier n'est pas autorisé";
$text['file-error']['he-il'] = "מצטערים, סוג הקובץ אינו מותר";
$text['file-error']['it-it'] = "";
$text['file-error']['nl-nl'] = "Sorry, File type niet toegestaan";
$text['file-error']['pl-pl'] = "Niestety, Typ pliku jest niedozwolony";
$text['file-error']['pt-br'] = "Desculpe, tipo de arquivo não permitido";
$text['file-error']['pt-pt'] = "Desculpe, tipo de arquivo não permitido";
$text['file-error']['ro-ro'] = "";
$text['file-error']['ru-ru'] = "Обновление завершено";
$text['file-error']['sv-se'] = "Uppdatering Klar";
$text['file-error']['uk-ua'] = "Оновлення завершено";

?>
