<?php
#This file was last reorganized on 13th of May 2017 07:32:22 AM UTC

$text['title-databases']['en-us'] = "Databases";
$text['title-databases']['ar-eg'] = "";
$text['title-databases']['de-at'] = "Datenbanken";
$text['title-databases']['de-de'] = "Datenbanken";
$text['title-databases']['es-cl'] = "Bases de datos";
$text['title-databases']['fr-fr'] = "Bases de données";
$text['title-databases']['he-il'] = "";
$text['title-databases']['it-it'] = "Database";
$text['title-databases']['nl-nl'] = "";
$text['title-databases']['pl-pl'] = "Bazy danych";
$text['title-databases']['pt-br'] = "Base de dados";
$text['title-databases']['pt-pt'] = "Bases de Dados";
$text['title-databases']['ru-ru'] = "Базы даных";
$text['title-databases']['sv-se'] = "Databaser";
$text['title-databases']['uk-ua'] = "Бази даних";

$text['title-command']['en-us'] = "Command";
$text['title-command']['ar-eg'] = "";
$text['title-command']['de-at'] = "Befehl";
$text['title-command']['de-de'] = "Befehl";
$text['title-command']['es-cl'] = "Comando";
$text['title-command']['fr-fr'] = "Commande";
$text['title-command']['he-il'] = "";
$text['title-command']['it-it'] = "Comando";
$text['title-command']['nl-nl'] = "";
$text['title-command']['pl-pl'] = "Polecenie";
$text['title-command']['pt-br'] = "Comando";
$text['title-command']['pt-pt'] = "Comando";
$text['title-command']['ru-ru'] = "Команды";
$text['title-command']['sv-se'] = "Kommando";
$text['title-command']['uk-ua'] = "Команди";

$text['option-result_type_view']['en-us'] = "View";
$text['option-result_type_view']['ar-eg'] = "";
$text['option-result_type_view']['de-at'] = "Ansicht";
$text['option-result_type_view']['de-de'] = "Ansicht";
$text['option-result_type_view']['es-cl'] = "Ver";
$text['option-result_type_view']['fr-fr'] = "Voir";
$text['option-result_type_view']['he-il'] = "";
$text['option-result_type_view']['it-it'] = "Visualizza";
$text['option-result_type_view']['nl-nl'] = "";
$text['option-result_type_view']['pl-pl'] = "Widok";
$text['option-result_type_view']['pt-br'] = "Visualizar";
$text['option-result_type_view']['pt-pt'] = "Ver";
$text['option-result_type_view']['ru-ru'] = "Просмотр";
$text['option-result_type_view']['sv-se'] = "Granska";
$text['option-result_type_view']['uk-ua'] = "Перегляд";

$text['option-result_type_insert']['en-us'] = "SQL";
$text['option-result_type_insert']['ar-eg'] = "";
$text['option-result_type_insert']['de-at'] = "SQL";
$text['option-result_type_insert']['de-de'] = "SQL";
$text['option-result_type_insert']['es-cl'] = "SQL";
$text['option-result_type_insert']['fr-fr'] = "SQL";
$text['option-result_type_insert']['he-il'] = "";
$text['option-result_type_insert']['it-it'] = "SQL";
$text['option-result_type_insert']['nl-nl'] = "";
$text['option-result_type_insert']['pl-pl'] = "SQL";
$text['option-result_type_insert']['pt-br'] = "SQL";
$text['option-result_type_insert']['pt-pt'] = "SQL";
$text['option-result_type_insert']['ru-ru'] = "SQL";
$text['option-result_type_insert']['sv-se'] = "SQL";
$text['option-result_type_insert']['uk-ua'] = "SQL ";

$text['option-result_type_csv']['en-us'] = "CSV";
$text['option-result_type_csv']['ar-eg'] = "";
$text['option-result_type_csv']['de-at'] = "CSV";
$text['option-result_type_csv']['de-de'] = "CSV";
$text['option-result_type_csv']['es-cl'] = "CSV";
$text['option-result_type_csv']['fr-fr'] = "CSV";
$text['option-result_type_csv']['he-il'] = "";
$text['option-result_type_csv']['it-it'] = "CSV";
$text['option-result_type_csv']['nl-nl'] = "";
$text['option-result_type_csv']['pl-pl'] = "CSV";
$text['option-result_type_csv']['pt-br'] = "CSV";
$text['option-result_type_csv']['pt-pt'] = "CSV";
$text['option-result_type_csv']['ru-ru'] = "CSV";
$text['option-result_type_csv']['sv-se'] = "CSV";
$text['option-result_type_csv']['uk-ua'] = "CSV ";

$text['label-table']['en-us'] = "Table";
$text['label-table']['ar-eg'] = "";
$text['label-table']['de-at'] = "Tabelle";
$text['label-table']['de-de'] = "Tabelle";
$text['label-table']['es-cl'] = "Tabla";
$text['label-table']['fr-fr'] = "Table";
$text['label-table']['he-il'] = "";
$text['label-table']['it-it'] = "Tabella";
$text['label-table']['nl-nl'] = "";
$text['label-table']['pl-pl'] = "Tabela";
$text['label-table']['pt-br'] = "Tabela";
$text['label-table']['pt-pt'] = "Tabela";
$text['label-table']['ru-ru'] = "Таблица";
$text['label-table']['sv-se'] = "TAbell";
$text['label-table']['uk-ua'] = "Таблиця";

$text['label-switch']['en-us'] = "Switch";
$text['label-switch']['ar-eg'] = "";
$text['label-switch']['de-at'] = "Switch";
$text['label-switch']['de-de'] = "Switch";
$text['label-switch']['es-cl'] = "Comando de switch";
$text['label-switch']['fr-fr'] = "Commande CLI Freeswitch";
$text['label-switch']['he-il'] = "";
$text['label-switch']['it-it'] = "Switch";
$text['label-switch']['nl-nl'] = "";
$text['label-switch']['pl-pl'] = "PBX";
$text['label-switch']['pt-br'] = "Comando Freeswitch ";
$text['label-switch']['pt-pt'] = "Comando Freeswitch";
$text['label-switch']['ru-ru'] = "Команды CLI Freeswitch";
$text['label-switch']['sv-se'] = "Switch";
$text['label-switch']['uk-ua'] = "FreeSwitch";

$text['label-shell']['en-us'] = "Shell";
$text['label-shell']['ar-eg'] = "";
$text['label-shell']['de-at'] = "Shell";
$text['label-shell']['de-de'] = "Shell";
$text['label-shell']['es-cl'] = "Terminal de Comandos";
$text['label-shell']['fr-fr'] = "Commande Shell";
$text['label-shell']['he-il'] = "";
$text['label-shell']['it-it'] = "Terminale dei Comandi";
$text['label-shell']['nl-nl'] = "";
$text['label-shell']['pl-pl'] = "Powłoka (shell)";
$text['label-shell']['pt-br'] = "Comando Shell ";
$text['label-shell']['pt-pt'] = "Comando Shell";
$text['label-shell']['ru-ru'] = "Консоль";
$text['label-shell']['sv-se'] = "Shell";
$text['label-shell']['uk-ua'] = "Консоль";

$text['label-results']['en-us'] = "Results";
$text['label-results']['ar-eg'] = "";
$text['label-results']['de-at'] = "Ergebnisse";
$text['label-results']['de-de'] = "Ergebnisse";
$text['label-results']['es-cl'] = "Resultados";
$text['label-results']['fr-fr'] = "Résultats";
$text['label-results']['he-il'] = "";
$text['label-results']['it-it'] = "Risultati";
$text['label-results']['nl-nl'] = "";
$text['label-results']['pl-pl'] = "Rezultaty";
$text['label-results']['pt-br'] = "Resultados";
$text['label-results']['pt-pt'] = "Resultados";
$text['label-results']['ru-ru'] = "Результаты";
$text['label-results']['sv-se'] = "Resultat";
$text['label-results']['uk-ua'] = "Результати";

$text['label-result_type']['en-us'] = "Result";
$text['label-result_type']['ar-eg'] = "";
$text['label-result_type']['de-at'] = "Ergebnis";
$text['label-result_type']['de-de'] = "Ergebnis";
$text['label-result_type']['es-cl'] = "Resultado";
$text['label-result_type']['fr-fr'] = "Résultat";
$text['label-result_type']['he-il'] = "";
$text['label-result_type']['it-it'] = "Risultati";
$text['label-result_type']['nl-nl'] = "";
$text['label-result_type']['pl-pl'] = "Rezultat";
$text['label-result_type']['pt-br'] = "Resultado";
$text['label-result_type']['pt-pt'] = "Resultado";
$text['label-result_type']['ru-ru'] = "Результат";
$text['label-result_type']['sv-se'] = "Resultat";
$text['label-result_type']['uk-ua'] = "Результат";

$text['label-response']['en-us'] = "Response";
$text['label-response']['ar-eg'] = "";
$text['label-response']['de-at'] = "Antwort";
$text['label-response']['de-de'] = "Antwort";
$text['label-response']['es-cl'] = "Respuesta";
$text['label-response']['fr-fr'] = "Réponse";
$text['label-response']['he-il'] = "";
$text['label-response']['it-it'] = "Risposta";
$text['label-response']['nl-nl'] = "";
$text['label-response']['pl-pl'] = "Odpowiedź";
$text['label-response']['pt-br'] = "Resposta";
$text['label-response']['pt-pt'] = "Resposta";
$text['label-response']['ru-ru'] = "Ответ";
$text['label-response']['sv-se'] = "Respons";
$text['label-response']['uk-ua'] = "Відповідь";

$text['label-reset']['en-us'] = "Reset";
$text['label-reset']['ar-eg'] = "إعادة تعيين";
$text['label-reset']['de-at'] = "Zurücksetzen";
$text['label-reset']['de-de'] = "Zurücksetzen";
$text['label-reset']['es-cl'] = "Reajustar";
$text['label-reset']['fr-fr'] = "Remettre";
$text['label-reset']['he-il'] = "אפס";
$text['label-reset']['it-it'] = "Reimposta";
$text['label-reset']['nl-nl'] = "";
$text['label-reset']['pl-pl'] = "Resetuj";
$text['label-reset']['pt-br'] = "Restabelecer";
$text['label-reset']['pt-pt'] = "Restabelecer";
$text['label-reset']['ru-ru'] = "Сбросить";
$text['label-reset']['sv-se'] = "Återställ";
$text['label-reset']['uk-ua'] = "Скинути";

$text['label-records']['en-us'] = "Records";
$text['label-records']['ar-eg'] = "";
$text['label-records']['de-at'] = "Einträge";
$text['label-records']['de-de'] = "Einträge";
$text['label-records']['es-cl'] = "Archivos";
$text['label-records']['fr-fr'] = "Enregistrements";
$text['label-records']['he-il'] = "";
$text['label-records']['it-it'] = "Records";
$text['label-records']['nl-nl'] = "";
$text['label-records']['pl-pl'] = "Dokumentacja";
$text['label-records']['pt-br'] = "Registros";
$text['label-records']['pt-pt'] = "Registros";
$text['label-records']['ru-ru'] = "Записи";
$text['label-records']['sv-se'] = "Uppgifter";
$text['label-records']['uk-ua'] = "документація";

$text['label-sql']['en-us'] = "SQL";
$text['label-sql']['ar-eg'] = "";
$text['label-sql']['de-at'] = "SQL";
$text['label-sql']['de-de'] = "SQL";
$text['label-sql']['es-cl'] = "SQL";
$text['label-sql']['fr-fr'] = "SQL";
$text['label-sql']['he-il'] = "";
$text['label-sql']['it-it'] = "SQL";
$text['label-sql']['nl-nl'] = "";
$text['label-sql']['pl-pl'] = "SQL";
$text['label-sql']['pt-br'] = "SQL";
$text['label-sql']['pt-pt'] = "SQL";
$text['label-sql']['ru-ru'] = "SQL";
$text['label-sql']['sv-se'] = "SQL";
$text['label-sql']['uk-ua'] = "SQL";

$text['label-php']['en-us'] = "PHP";
$text['label-php']['ar-eg'] = "";
$text['label-php']['de-at'] = "PHP";
$text['label-php']['de-de'] = "PHP";
$text['label-php']['es-cl'] = "Comando PHP";
$text['label-php']['fr-fr'] = "Commande PHP";
$text['label-php']['he-il'] = "";
$text['label-php']['it-it'] = "PHP";
$text['label-php']['nl-nl'] = "";
$text['label-php']['pl-pl'] = "PHP";
$text['label-php']['pt-br'] = "Comandos PHP ";
$text['label-php']['pt-pt'] = "Comandos PHP";
$text['label-php']['ru-ru'] = "Команды PHP";
$text['label-php']['sv-se'] = "PHP";
$text['label-php']['uk-ua'] = "PHP";

$text['label-execute']['en-us'] = "Execute Command";
$text['label-execute']['ar-eg'] = "";
$text['label-execute']['de-at'] = "Befehl Ausführen";
$text['label-execute']['de-de'] = "Befehl Ausführen";
$text['label-execute']['es-cl'] = "Ejecutar Comando";
$text['label-execute']['fr-fr'] = "Executer la Commande";
$text['label-execute']['he-il'] = "";
$text['label-execute']['it-it'] = "Esegui Comando";
$text['label-execute']['nl-nl'] = "";
$text['label-execute']['pl-pl'] = "Wykonywanie poleceń";
$text['label-execute']['pt-br'] = "Executar";
$text['label-execute']['pt-pt'] = "Executar Comando";
$text['label-execute']['ru-ru'] = "Выполнить команду";
$text['label-execute']['sv-se'] = "Utför Kommando";
$text['label-execute']['uk-ua'] = "Виконання команд";

$text['label-error']['en-us'] = "Error";
$text['label-error']['ar-eg'] = "";
$text['label-error']['de-at'] = "Fehler";
$text['label-error']['de-de'] = "Fehler";
$text['label-error']['es-cl'] = "Error";
$text['label-error']['fr-fr'] = "Erreur";
$text['label-error']['he-il'] = "";
$text['label-error']['it-it'] = "Errore";
$text['label-error']['nl-nl'] = "";
$text['label-error']['pl-pl'] = "Błąd";
$text['label-error']['pt-br'] = "Erro";
$text['label-error']['pt-pt'] = "Erro";
$text['label-error']['ru-ru'] = "Ошибка";
$text['label-error']['sv-se'] = "Fel";
$text['label-error']['uk-ua'] = "Помилка";

$text['header-databases']['en-us'] = "Databases";
$text['header-databases']['ar-eg'] = "";
$text['header-databases']['de-at'] = "Datenbanken";
$text['header-databases']['de-de'] = "Datenbanken";
$text['header-databases']['es-cl'] = "Bases de datos";
$text['header-databases']['fr-fr'] = "Bases de données";
$text['header-databases']['he-il'] = "";
$text['header-databases']['it-it'] = "Databases";
$text['header-databases']['nl-nl'] = "";
$text['header-databases']['pl-pl'] = "Bazy danych";
$text['header-databases']['pt-br'] = "Base de dados";
$text['header-databases']['pt-pt'] = "Bases de Dados";
$text['header-databases']['ru-ru'] = "База Данных";
$text['header-databases']['sv-se'] = "Databaser";
$text['header-databases']['uk-ua'] = "Бази даних";

$text['description-switch']['en-us'] = "Switch CLI. View valid commands with: 'help'.";
$text['description-switch']['ar-eg'] = "";
$text['description-switch']['de-at'] = "Um eine Liste der gültigen Befehle zu erhalten tippen Sie: 'help'";
$text['description-switch']['de-de'] = "Um eine Liste der gültigen Befehle zu erhalten tippen Sie: 'help'";
$text['description-switch']['es-cl'] = "Para un listado de comandos válidos use: help";
$text['description-switch']['fr-fr'] = "Pour la liste des commandes valides, utiliser : help";
$text['description-switch']['he-il'] = "";
$text['description-switch']['it-it'] = "Switch CLI. Visualizza i comandi validi digitando: 'help'.";
$text['description-switch']['nl-nl'] = "";
$text['description-switch']['pl-pl'] = "Aby uzyskać listę poprawnych poleceń użyj pomocy";
$text['description-switch']['pt-br'] = "Para verificar a lista de comandos válidos utilize: Ajuda";
$text['description-switch']['pt-pt'] = "Para uma lista dos comandos válidos utilize: help";
$text['description-switch']['ru-ru'] = "Switch CLI.Для получения списка доступных команд, используйте:'help'.";
$text['description-switch']['sv-se'] = "För en lista med giltiga kommandon använd: help";
$text['description-switch']['uk-ua'] = "Для перегляду списку команд виконайте команду: help";

$text['description-shell']['en-us'] = "Execute system commands.";
$text['description-shell']['ar-eg'] = "";
$text['description-shell']['de-at'] = "System Befehle ausführen";
$text['description-shell']['de-de'] = "System Befehle ausführen";
$text['description-shell']['es-cl'] = "Comandos de sistema";
$text['description-shell']['fr-fr'] = "Commande Système";
$text['description-shell']['he-il'] = "";
$text['description-shell']['it-it'] = "Esegui comandi di sistema.";
$text['description-shell']['nl-nl'] = "";
$text['description-shell']['pl-pl'] = "Polecenia systemowe.";
$text['description-shell']['pt-br'] = "Comando do sistema";
$text['description-shell']['pt-pt'] = "Comandos do sistema.";
$text['description-shell']['ru-ru'] = "Выполните системные команды.";
$text['description-shell']['sv-se'] = "System Kommandon.";
$text['description-shell']['uk-ua'] = "Системні команди";

$text['description-sql']['en-us'] = "Execute statements against the database.";
$text['description-sql']['ar-eg'] = "";
$text['description-sql']['de-at'] = "Abfragen gegen die Datenbank ausführen.";
$text['description-sql']['de-de'] = "";
$text['description-sql']['es-cl'] = "Ejecutar instrucciones de consulta contra la base de datos.";
$text['description-sql']['fr-fr'] = "Exécuter les instructions de requête contre la base de données.";
$text['description-sql']['he-il'] = "";
$text['description-sql']['it-it'] = "Esegue istruzioni nel database.";
$text['description-sql']['nl-nl'] = "";
$text['description-sql']['pl-pl'] = "Wykonać polecenie zapytania do bazy danych.";
$text['description-sql']['pt-br'] = "Executar instruções de consulta no banco de dados.";
$text['description-sql']['pt-pt'] = "Executar instruções de consulta no banco de dados.";
$text['description-sql']['ru-ru'] = "Выполнение запросов для базы данных.";
$text['description-sql']['sv-se'] = "Utför fråge uttalanden mot databasen.";
$text['description-sql']['uk-ua'] = "Виконання операторів запитів до бази даних.";

$text['description-php']['en-us'] = "Execute PHP commands.  See: <a href='http://php.net/manual/' target='_blank'>PHP Manual</a>";
$text['description-php']['ar-eg'] = "";
$text['description-php']['de-at'] = "PHP Befehle ausführen. Benutzen Sie folgenden Link als PHP Referenz: <a href='http://php.net/manual/>PHP Manual</a>";
$text['description-php']['de-de'] = "PHP Befehle ausführen. Benutzen Sie folgenden Link als PHP Referenz: <a href='http://php.net/manual/>PHP Manual</a>";
$text['description-php']['es-cl'] = "Utilice el siguiente enlace como referencia para PHP: <a href='http://php.net/manual/' target='_blank'>Manual PHP</a>";
$text['description-php']['fr-fr'] = "Utiliser le lien suivant comme référence pour le PHP: <a href='http://php.net/manual/' target='_blank'>Manuel PHP</a>";
$text['description-php']['he-il'] = "";
$text['description-php']['it-it'] = "Esegui comandi PHP.  Visualizza: <a href='http://php.net/manual/' target='_blank'>Manuale PHP</a>";
$text['description-php']['nl-nl'] = "";
$text['description-php']['pl-pl'] = "Aby użyć odniesienia do PHP kliknij na ten link: <a href='http://php.net/manual/' target='_blank'>PHP Manual</a>";
$text['description-php']['pt-br'] = "Utilize a ligação seguinte como referência para o PHP: <a href='http://php.net/manual/' target='_blank'>PHP Manual</a>";
$text['description-php']['pt-pt'] = "Utilize a ligação seguinte como referência para o PHP: <a href='http://php.net/manual/' target='_blank'>PHP Manual</a>";
$text['description-php']['ru-ru'] = "Выполнение PHP команд. Смотрите: <a href='http://php.net/manual/' target='_blank'>PHP Manual</a>";
$text['description-php']['sv-se'] = "Använd följande länk som en referens gällande PHP: <a href='http://php.net/manual/' target='_blank'>PHP Manual</a>";
$text['description-php']['uk-ua'] = "Посилання на довідку PHP: <a href='http://php.net/manual/' target='_blank'>PHP Manual</a>";

$text['description-execute']['en-us'] = "Provides a conventient way to execute system, PHP, switch and SQL commands.";
$text['description-execute']['ar-eg'] = "";
$text['description-execute']['de-at'] = "Bietet die Möglichkeit System, PHP, Switch und SQL Befehle auszuführen.";
$text['description-execute']['de-de'] = "Bietet die Möglichkeit System, PHP, Switch und SQL Befehle auszuführen.";
$text['description-execute']['es-cl'] = "Provee un modo conveniente de ejecutar comandos de sistema, PHP o del switch.";
$text['description-execute']['fr-fr'] = "Fournir un moyen pour executer des commandes système, PHP et switch. ";
$text['description-execute']['he-il'] = "";
$text['description-execute']['it-it'] = "Offre un modo comodo per eseguire comandi di sistema, PHP, switch e SQL.";
$text['description-execute']['nl-nl'] = "";
$text['description-execute']['pl-pl'] = "Ta funkcja zapewnia dogodny sposób wykonywania poleceń systemowych, PHP oraz switch.";
$text['description-execute']['pt-br'] = "Utilize facilmente a execução de comandos do sistema, PHP e switch ";
$text['description-execute']['pt-pt'] = "Oferece uma maneira fácil de executar comandos de sistema, PHP, e switch.";
$text['description-execute']['ru-ru'] = "Обеспечивает удобный способ выполнения команд системы, PHP, FreeSwitch и SQL.";
$text['description-execute']['sv-se'] = "Erbjuder ett smidigt sätt att köra system, PHP och switch kommandon.";
$text['description-execute']['uk-ua'] = "Забезпечує зручний спосіб виконати команди PHP, switch, а також системні команди";

$text['description-databases']['en-us'] = "Select the database to execute SQL query statements against.";
$text['description-databases']['ar-eg'] = "";
$text['description-databases']['de-at'] = "Wählen Sie die Datenbank für die SQL Abfrage aus.";
$text['description-databases']['de-de'] = "Wählen Sie die Datenbank für die SQL Abfrage aus.";
$text['description-databases']['es-cl'] = "Seleccione la base de datos para ejecutar la consulta SQL.";
$text['description-databases']['fr-fr'] = "Choisir la base de données utilisée par la requête SQL.";
$text['description-databases']['he-il'] = "";
$text['description-databases']['it-it'] = "Seleziona il database su cui eseguire la query SQL.";
$text['description-databases']['nl-nl'] = "";
$text['description-databases']['pl-pl'] = "Informacje o bazie danych.";
$text['description-databases']['pt-br'] = "Informações sobre a base de dados";
$text['description-databases']['pt-pt'] = "Escolha a base de dados a utilizar.";
$text['description-databases']['ru-ru'] = "Выберите базу данных для выполнения SQL-запросов.";
$text['description-databases']['sv-se'] = "Välj databas att använda för SQL Fråga.";
$text['description-databases']['uk-ua'] = "Інформація про базу даних.";

$text['button-select_database']['en-us'] = "Select Database";
$text['button-select_database']['ar-eg'] = "";
$text['button-select_database']['de-at'] = "Datenbank auswählen";
$text['button-select_database']['de-de'] = "Datenbank auswählen";
$text['button-select_database']['es-cl'] = "Seleccionar Base de Datos";
$text['button-select_database']['fr-fr'] = "Choisir la Base de données";
$text['button-select_database']['he-il'] = "";
$text['button-select_database']['it-it'] = "Seleziona Database";
$text['button-select_database']['nl-nl'] = "";
$text['button-select_database']['pl-pl'] = "Wybierz bazę danych";
$text['button-select_database']['pt-br'] = "Selecionar base de dados";
$text['button-select_database']['pt-pt'] = "Seleccionar Base de Dados";
$text['button-select_database']['ru-ru'] = "Выберите Базу Данных";
$text['button-select_database']['sv-se'] = "Välj Databas";
$text['button-select_database']['uk-ua'] = "Вибрати БД";

$text['button-manage']['en-us'] = "Manage";
$text['button-manage']['ar-eg'] = "";
$text['button-manage']['de-at'] = "Verwalten";
$text['button-manage']['de-de'] = "Verwalten";
$text['button-manage']['es-cl'] = "Administrar";
$text['button-manage']['fr-fr'] = "Gérer";
$text['button-manage']['he-il'] = "";
$text['button-manage']['it-it'] = "Gestisci";
$text['button-manage']['nl-nl'] = "";
$text['button-manage']['pl-pl'] = "Zarządzaj";
$text['button-manage']['pt-br'] = "Gerenciar";
$text['button-manage']['pt-pt'] = "Gerir";
$text['button-manage']['ru-ru'] = "Управление";
$text['button-manage']['sv-se'] = "Hantera";
$text['button-manage']['uk-ua'] = "Керувати";

$text['button-backup']['en-us'] = "Backup";
$text['button-backup']['ar-eg'] = "";
$text['button-backup']['de-at'] = "Sichern";
$text['button-backup']['de-de'] = "Sichern";
$text['button-backup']['es-cl'] = "Respaldar";
$text['button-backup']['fr-fr'] = "Sauvegarder";
$text['button-backup']['he-il'] = "";
$text['button-backup']['it-it'] = "Backup";
$text['button-backup']['nl-nl'] = "";
$text['button-backup']['pl-pl'] = "Kopia Zapasowa";
$text['button-backup']['pt-br'] = "Backup";
$text['button-backup']['pt-pt'] = "Backup";
$text['button-backup']['ru-ru'] = "Резервное Копирование";
$text['button-backup']['sv-se'] = "Backup";
$text['button-backup']['uk-ua'] = "Резервна копія";

?>
