<?php
	$payment_plugin[$x]['name'] = 'Paypal';						// Name of the plugin, it will apear in webpage
	$payment_plugin[$x]['icon'] = 'pay-button.jpg';					// Icon
	$payment_plugin[$x]['path'] = PROJECT_PATH . "/app/billing/resources/plugins/paypal";	// Absolute path to directory
	$payment_plugin[$x]['currency'][] = 'AUD';
	$payment_plugin[$x]['currency'][] = 'CAD';
	$payment_plugin[$x]['currency'][] = 'CHF';
	$payment_plugin[$x]['currency'][] = 'CZK';
	$payment_plugin[$x]['currency'][] = 'DKK';
	$payment_plugin[$x]['currency'][] = 'EUR';
	$payment_plugin[$x]['currency'][] = 'GBP';
	$payment_plugin[$x]['currency'][] = 'HKD';
	$payment_plugin[$x]['currency'][] = 'HUF';
	$payment_plugin[$x]['currency'][] = 'ILS';
	$payment_plugin[$x]['currency'][] = 'JPY';
	$payment_plugin[$x]['currency'][] = 'MXN';
	$payment_plugin[$x]['currency'][] = 'NZD';
	$payment_plugin[$x]['currency'][] = 'NOK';
	$payment_plugin[$x]['currency'][] = 'PHP';
	$payment_plugin[$x]['currency'][] = 'PLN';
	$payment_plugin[$x]['currency'][] = 'RUB';
	$payment_plugin[$x]['currency'][] = 'SGD';
	$payment_plugin[$x]['currency'][] = 'SEK';
	$payment_plugin[$x]['currency'][] = 'THB';
	$payment_plugin[$x]['currency'][] = 'TWD';
	$payment_plugin[$x]['currency'][] = 'USD';
	$payment_plugin[$x]['message']['es'] = '';
	$payment_plugin[$x]['message']['en'] = '';
