<?php

$text['title-variables_advanced']['en-us'] = "Switch Variables: Advanced";
$text['title-variables_advanced']['en-gb'] = "Switch Variables: Advanced";
$text['title-variables_advanced']['ar-eg'] = "تبديل المتغيرات: متقدم";
$text['title-variables_advanced']['de-at'] = "Switch Variablen: Erweitert"; //copied from de-de
$text['title-variables_advanced']['de-ch'] = "Switch Variablen: Erweitert"; //copied from de-de
$text['title-variables_advanced']['de-de'] = "Switch Variablen: Erweitert";
$text['title-variables_advanced']['es-cl'] = "Variables de Switch: Avanzadas";
$text['title-variables_advanced']['es-mx'] = "Variables de Switch: Avanzadas"; //copied from es-cl
$text['title-variables_advanced']['fr-ca'] = "Variables Système: Avancé"; //copied from fr-fr
$text['title-variables_advanced']['fr-fr'] = "Variables Système: Avancé";
$text['title-variables_advanced']['he-il'] = "מתג משתני: מתקדם";
$text['title-variables_advanced']['it-it'] = "Variabili Centrale: Avanzate";
$text['title-variables_advanced']['nl-nl'] = "Centrale variabelen: Uitgebreid";
$text['title-variables_advanced']['pl-pl'] = "Zmienne PBXu (zaawansowane)";
$text['title-variables_advanced']['pt-br'] = "Variáveis do Softswitch: Avançadas ";
$text['title-variables_advanced']['pt-pt'] = "Variáveis do Softswitch: Avançadas";
$text['title-variables_advanced']['ro-ro'] = "Variabile de comutare: Avansat";
$text['title-variables_advanced']['ru-ru'] = "Параметры FreeSwitch: Расширенные";
$text['title-variables_advanced']['sv-se'] = "Switch Variabler: Avancerat";
$text['title-variables_advanced']['uk-ua'] = "Задання змінних: Додатково";

$text['title-variables']['en-us'] = "Switch Variables";
$text['title-variables']['en-gb'] = "Switch Variables";
$text['title-variables']['ar-eg'] = "تبديل المتغيرات";
$text['title-variables']['de-at'] = "Switch Variablen"; //copied from de-de
$text['title-variables']['de-ch'] = "Switch Variablen"; //copied from de-de
$text['title-variables']['de-de'] = "Switch Variablen";
$text['title-variables']['es-cl'] = "Variables de Switch";
$text['title-variables']['es-mx'] = "Variables de Switch"; //copied from es-cl
$text['title-variables']['fr-ca'] = "Variables Système"; //copied from fr-fr
$text['title-variables']['fr-fr'] = "Variables Système";
$text['title-variables']['he-il'] = "החלף משתנים";
$text['title-variables']['it-it'] = "Variabili Centrale";
$text['title-variables']['nl-nl'] = "Centrale variabelen";
$text['title-variables']['pl-pl'] = "Zmienne PBXu";
$text['title-variables']['pt-br'] = "Variáveis do Softswitch ";
$text['title-variables']['pt-pt'] = "Variáveis do Softswitch";
$text['title-variables']['ro-ro'] = "Comutare variabile";
$text['title-variables']['ru-ru'] = "Параметры FreeSwitch";
$text['title-variables']['sv-se'] = "Switch Variabler";
$text['title-variables']['uk-ua'] = "Задання змінних ";

$text['title-variable']['en-us'] = "Variable";
$text['title-variable']['en-gb'] = "Variable";
$text['title-variable']['ar-eg'] = "عامل";
$text['title-variable']['de-at'] = "Variable"; //copied from de-de
$text['title-variable']['de-ch'] = "Variable"; //copied from de-de
$text['title-variable']['de-de'] = "Variable";
$text['title-variable']['es-cl'] = "Editar Variable";
$text['title-variable']['es-mx'] = "Editar Variable"; //copied from es-cl
$text['title-variable']['fr-ca'] = "Editer la Variable"; //copied from fr-fr
$text['title-variable']['fr-fr'] = "Editer la Variable";
$text['title-variable']['he-il'] = "מִשְׁתַנֶה";
$text['title-variable']['it-it'] = "Variabile";
$text['title-variable']['nl-nl'] = "Variabele bijwerken";
$text['title-variable']['pl-pl'] = "Zmienna";
$text['title-variable']['pt-br'] = "Editar Variável ";
$text['title-variable']['pt-pt'] = "Editar Variável";
$text['title-variable']['ro-ro'] = "Variabil";
$text['title-variable']['ru-ru'] = "Переменная";
$text['title-variable']['sv-se'] = "Variabel";
$text['title-variable']['uk-ua'] = "Змінна";

$text['label-command']['en-us'] = "Command";
$text['label-command']['en-gb'] = "Command";
$text['label-command']['ar-eg'] = "يأمر";
$text['label-command']['de-at'] = "Befehl";
$text['label-command']['de-ch'] = "Befehl";
$text['label-command']['de-de'] = "Befehl";
$text['label-command']['es-cl'] = "Dominio";
$text['label-command']['es-mx'] = "Dominio";
$text['label-command']['fr-ca'] = "Command";
$text['label-command']['fr-fr'] = "Command";
$text['label-command']['he-il'] = "פקודה";
$text['label-command']['it-it'] = "Comando";
$text['label-command']['nl-nl'] = "Commando";
$text['label-command']['pl-pl'] = "Komenda";
$text['label-command']['pt-br'] = "Comando";
$text['label-command']['pt-pt'] = "Comando";
$text['label-command']['ro-ro'] = "Comanda";
$text['label-command']['ru-ru'] = "Команда";
$text['label-command']['sv-se'] = "Kommando";
$text['label-command']['uk-ua'] = "Команда";

$text['option-set']['en-us'] = "Set";
$text['option-set']['en-gb'] = "Set";
$text['option-set']['ar-eg'] = "تعيين";
$text['option-set']['de-at'] = "Satz";
$text['option-set']['de-ch'] = "Satz";
$text['option-set']['de-de'] = "Satz";
$text['option-set']['es-cl'] = "Colocar";
$text['option-set']['es-mx'] = "Colocar";
$text['option-set']['fr-ca'] = "Définir";
$text['option-set']['fr-fr'] = "Définir";
$text['option-set']['he-il'] = "מַעֲרֶכֶת";
$text['option-set']['it-it'] = "Impostato";
$text['option-set']['nl-nl'] = "Definieer";
$text['option-set']['pl-pl'] = "Ustawić";
$text['option-set']['pt-br'] = "Definir";
$text['option-set']['pt-pt'] = "Definir";
$text['option-set']['ro-ro'] = "A stabilit";
$text['option-set']['ru-ru'] = "Набор";
$text['option-set']['sv-se'] = "Uppsättning";
$text['option-set']['uk-ua'] = "встановити";

$text['option-exec-set']['en-us'] = "Execute & Set";
$text['option-exec-set']['en-gb'] = "Execute & Set";
$text['option-exec-set']['ar-eg'] = "تنفيذ وتعيين";
$text['option-exec-set']['de-at'] = "Ausführen und setzen";
$text['option-exec-set']['de-ch'] = "Ausführen und setzen";
$text['option-exec-set']['de-de'] = "Ausführen und setzen";
$text['option-exec-set']['es-cl'] = "Ejecutar y Establecer";
$text['option-exec-set']['es-mx'] = "Ejecutar y Establecer";
$text['option-exec-set']['fr-ca'] = "Exécuter et définir";
$text['option-exec-set']['fr-fr'] = "Exécuter et définir";
$text['option-exec-set']['he-il'] = "בצע והגדר";
$text['option-exec-set']['it-it'] = "Esegui e imposta";
$text['option-exec-set']['nl-nl'] = "Uitvoeren en instellen";
$text['option-exec-set']['pl-pl'] = "Wykonaj i ustaw";
$text['option-exec-set']['pt-br'] = "Executar e definir";
$text['option-exec-set']['pt-pt'] = "Executar e definir";
$text['option-exec-set']['ro-ro'] = "Executați și setați";
$text['option-exec-set']['ru-ru'] = "Выполнить и установить";
$text['option-exec-set']['sv-se'] = "Kör och ställ in";
$text['option-exec-set']['uk-ua'] = "Виконати та встановити";

$text['label-hostname']['en-us'] = "Hostname";
$text['label-hostname']['en-gb'] = "Hostname";
$text['label-hostname']['ar-eg'] = "اسم المضيف";
$text['label-hostname']['de-at'] = "Hostname"; //copied from de-de
$text['label-hostname']['de-ch'] = "Hostname"; //copied from de-de
$text['label-hostname']['de-de'] = "Hostname";
$text['label-hostname']['es-cl'] = "Nombre de Host";
$text['label-hostname']['es-mx'] = "Nombre de Host";
$text['label-hostname']['fr-ca'] = "Nom d'hôte"; //copied from fr-fr
$text['label-hostname']['fr-fr'] = "Nom d'hôte";
$text['label-hostname']['he-il'] = "שם מארח";
$text['label-hostname']['it-it'] = "Hostname";
$text['label-hostname']['nl-nl'] = "Hostnaam";
$text['label-hostname']['pl-pl'] = "Nazwa hosta";
$text['label-hostname']['pt-br'] = "Hostname"; //copied from pt-pt
$text['label-hostname']['pt-pt'] = "Hostname";
$text['label-hostname']['ro-ro'] = "Nume gazdă";
$text['label-hostname']['ru-ru'] = "Имя хоста";
$text['label-hostname']['sv-se'] = "Hostname";
$text['label-hostname']['uk-ua'] = "Назва хоста";

$text['label-codec_information']['en-us'] = "Codec Information";
$text['label-codec_information']['en-gb'] = "Codec Information";
$text['label-codec_information']['ar-eg'] = "معلومات الترميز";
$text['label-codec_information']['de-at'] = "Codec Information"; //copied from de-de
$text['label-codec_information']['de-ch'] = "Codec Information"; //copied from de-de
$text['label-codec_information']['de-de'] = "Codec Information";
$text['label-codec_information']['es-cl'] = "Informatión de Codec";
$text['label-codec_information']['es-mx'] = "Informatión de Codec"; //copied from es-cl
$text['label-codec_information']['fr-ca'] = "Codec Information"; //copied from fr-fr
$text['label-codec_information']['fr-fr'] = "Codec Information";
$text['label-codec_information']['he-il'] = "מידע על Codec";
$text['label-codec_information']['it-it'] = "Informazioni Codec";
$text['label-codec_information']['nl-nl'] = "Codec informatie";
$text['label-codec_information']['pl-pl'] = "Informacja o kodekach";
$text['label-codec_information']['pt-br'] = "Informações sobre o Codec";
$text['label-codec_information']['pt-pt'] = "Informação do Codec";
$text['label-codec_information']['ro-ro'] = "Informații codec";
$text['label-codec_information']['ru-ru'] = "Информация о кодеке";
$text['label-codec_information']['sv-se'] = "Codec Information";
$text['label-codec_information']['uk-ua'] = "Інформація про кодек";

$text['header-variables_advanced']['en-us'] = "Switch Variables: Advanced";
$text['header-variables_advanced']['en-gb'] = "Switch Variables: Advanced";
$text['header-variables_advanced']['ar-eg'] = "تبديل المتغيرات: متقدم";
$text['header-variables_advanced']['de-at'] = "Switch Variablen: Erweitert"; //copied from de-de
$text['header-variables_advanced']['de-ch'] = "Switch Variablen: Erweitert"; //copied from de-de
$text['header-variables_advanced']['de-de'] = "Switch Variablen: Erweitert";
$text['header-variables_advanced']['es-cl'] = "Variables de Switch: Avanzadas";
$text['header-variables_advanced']['es-mx'] = "Variables de Switch: Avanzadas"; //copied from es-cl
$text['header-variables_advanced']['fr-ca'] = "Variables Système: Avancé"; //copied from fr-fr
$text['header-variables_advanced']['fr-fr'] = "Variables Système: Avancé";
$text['header-variables_advanced']['he-il'] = "מתג משתני: מתקדם";
$text['header-variables_advanced']['it-it'] = "Variabili Centrale: Avanzate";
$text['header-variables_advanced']['nl-nl'] = "Centrale variabelen: Uitgebreid";
$text['header-variables_advanced']['pl-pl'] = "Zamień zmienne (zaawansowane)";
$text['header-variables_advanced']['pt-br'] = "Variáveis do Softswitch: Avançadas ";
$text['header-variables_advanced']['pt-pt'] = "Variáveis do Softswitch: Avançadas";
$text['header-variables_advanced']['ro-ro'] = "Variabile de comutare: Avansat";
$text['header-variables_advanced']['ru-ru'] = "Параметры FreeSwitch: Расширенный";
$text['header-variables_advanced']['sv-se'] = "Switch Variabler: Avancerat";
$text['header-variables_advanced']['uk-ua'] = "Задання змінних: Додатково";

$text['header-variables']['en-us'] = "Switch Variables";
$text['header-variables']['en-gb'] = "Switch Variables";
$text['header-variables']['ar-eg'] = "تبديل المتغيرات";
$text['header-variables']['de-at'] = "Switch Variablen"; //copied from de-de
$text['header-variables']['de-ch'] = "Switch Variablen"; //copied from de-de
$text['header-variables']['de-de'] = "Switch Variablen";
$text['header-variables']['es-cl'] = "Variables de Switch";
$text['header-variables']['es-mx'] = "Variables de Switch"; //copied from es-cl
$text['header-variables']['fr-ca'] = "Variables Système"; //copied from fr-fr
$text['header-variables']['fr-fr'] = "Variables Système";
$text['header-variables']['he-il'] = "החלף משתנים";
$text['header-variables']['it-it'] = "Variabili Centrale";
$text['header-variables']['nl-nl'] = "Centrale variabelen";
$text['header-variables']['pl-pl'] = "Zmienne PBXu";
$text['header-variables']['pt-br'] = "Variáveis do Softswitch ";
$text['header-variables']['pt-pt'] = "Variáveis do Softswitch";
$text['header-variables']['ro-ro'] = "Comutare variabile";
$text['header-variables']['ru-ru'] = "Параметры FreeSwitch";
$text['header-variables']['sv-se'] = "Switch Variabler";
$text['header-variables']['uk-ua'] = "Задання змінних";

$text['header-variable']['en-us'] = "Variable";
$text['header-variable']['en-gb'] = "Variable";
$text['header-variable']['ar-eg'] = "عامل";
$text['header-variable']['de-at'] = "Variable"; //copied from de-de
$text['header-variable']['de-ch'] = "Variable"; //copied from de-de
$text['header-variable']['de-de'] = "Variable";
$text['header-variable']['es-cl'] = "Editar Variable";
$text['header-variable']['es-mx'] = "Editar Variable"; //copied from es-cl
$text['header-variable']['fr-ca'] = "Editer la Variable"; //copied from fr-fr
$text['header-variable']['fr-fr'] = "Editer la Variable";
$text['header-variable']['he-il'] = "מִשְׁתַנֶה";
$text['header-variable']['it-it'] = "Variabile";
$text['header-variable']['nl-nl'] = "Variabelen";
$text['header-variable']['pl-pl'] = "Zmienna";
$text['header-variable']['pt-br'] = "Editar variável"; //copied from pt-pt
$text['header-variable']['pt-pt'] = "Editar variável";
$text['header-variable']['ro-ro'] = "Variabil";
$text['header-variable']['ru-ru'] = "Переменная";
$text['header-variable']['sv-se'] = "Variabel";
$text['header-variable']['uk-ua'] = "Змінна";

$text['header-hostname']['en-us'] = "Hostname";
$text['header-hostname']['en-gb'] = "Hostname";
$text['header-hostname']['ar-eg'] = "اسم المضيف";
$text['header-hostname']['de-at'] = "Hostname"; //copied from de-de
$text['header-hostname']['de-ch'] = "Hostname"; //copied from de-de
$text['header-hostname']['de-de'] = "Hostname";
$text['header-hostname']['es-cl'] = "Nombre de Host";
$text['header-hostname']['es-mx'] = "Nombre de Host";
$text['header-hostname']['fr-ca'] = "Nom d'hôte"; //copied from fr-fr
$text['header-hostname']['fr-fr'] = "Nom d'hôte";
$text['header-hostname']['he-il'] = "שם מארח";
$text['header-hostname']['it-it'] = "Hostname";
$text['header-hostname']['nl-nl'] = "Hostnaam";
$text['header-hostname']['pl-pl'] = "Nazwa hosta";
$text['header-hostname']['pt-br'] = "Hostname"; //copied from pt-pt
$text['header-hostname']['pt-pt'] = "Hostname";
$text['header-hostname']['ro-ro'] = "Nume gazdă";
$text['header-hostname']['ru-ru'] = "Имя хоста";
$text['header-hostname']['sv-se'] = "Hostname";
$text['header-hostname']['uk-ua'] = "Назва хоста";

$text['description-variables_advanced']['en-us'] = "Define preprocessor variables here. Can be accessed in the xml configuration with $.";
$text['description-variables_advanced']['en-gb'] = "Define preprocessor variables here. Can be accessed in the xml configuration with $.";
$text['description-variables_advanced']['ar-eg'] = "حدد متغيرات المعالج المسبق هنا. يمكن الوصول إليه في تكوين xml باستخدام $.";
$text['description-variables_advanced']['de-at'] = "Definieren Sie Preprozessor Variablen. Auf diese kann in der XML Konfiguration mittels $ zugegriffen werden."; //copied from de-de
$text['description-variables_advanced']['de-ch'] = "Definieren Sie Preprozessor Variablen. Auf diese kann in der XML Konfiguration mittels $ zugegriffen werden."; //copied from de-de
$text['description-variables_advanced']['de-de'] = "Definieren Sie Preprozessor Variablen. Auf diese kann in der XML Konfiguration mittels $ zugegriffen werden.";
$text['description-variables_advanced']['es-cl'] = "Defina variables de preprocesador aquí. Pueden ser accesadas en la configuración XML con $.";
$text['description-variables_advanced']['es-mx'] = "Defina variables de preprocesador aquí. Pueden ser accesadas en la configuración XML con $."; //copied from es-cl
$text['description-variables_advanced']['fr-ca'] = "Définir ici les variables préprocessées. Se retrouve dans la configuration XML avec $."; //copied from fr-fr
$text['description-variables_advanced']['fr-fr'] = "Définir ici les variables préprocessées. Se retrouve dans la configuration XML avec $.";
$text['description-variables_advanced']['he-il'] = "הגדר כאן משתני קדם-מעבד. ניתן לגשת בתצורת xml עם $.";
$text['description-variables_advanced']['it-it'] = "Definire qui le variabili per il preprocessore. Possono essere usate nella configurazione xml con $.";
$text['description-variables_advanced']['nl-nl'] = "Definieer voorbewerkings variabelen. Kan in XML configuraties gebruikt worden met $.";
$text['description-variables_advanced']['pl-pl'] = "Tutaj zdefiniuj zmienne preprocesora. Mogą być dostępne w konfiguracji xml z $.";
$text['description-variables_advanced']['pt-br'] = "Defina as variáveis aqui. Podem ser acessadas na configuração XML com $";
$text['description-variables_advanced']['pt-pt'] = "Defina as variáveis aqui. Podem ser acedidas na configuração xml com $.";
$text['description-variables_advanced']['ro-ro'] = "Definiți aici variabilele preprocesorului. Poate fi accesat în configurația xml cu $.";
$text['description-variables_advanced']['ru-ru'] = "Определите здесь параметры FreeSwitch. Доступ к файлу xml можно получить с помощью $.";
$text['description-variables_advanced']['sv-se'] = "Definiera preprocessor variabler här. Kan nås i xml konfigurationen med $.";
$text['description-variables_advanced']['uk-ua'] = "Задайте змінні препроцесора тут. Вони будуть доступними в конфігурації XML з символом $.";

$text['description-variables']['en-us'] = "Define preprocessor variables here. A switch restart is required for changes to take effect.";
$text['description-variables']['en-gb'] = "Define preprocessor variables here. A switch restart is required for changes to take effect.";
$text['description-variables']['ar-eg'] = "حدد متغيرات المعالج المسبق هنا. يلزم إعادة تشغيل المفتاح حتى تصبح التغييرات سارية المفعول.";
$text['description-variables']['de-at'] = "Definieren Sie Preprozessor Variablen."; //copied from de-de
$text['description-variables']['de-ch'] = "Definieren Sie Preprozessor Variablen."; //copied from de-de
$text['description-variables']['de-de'] = "Definieren Sie Preprozessor Variablen.";
$text['description-variables']['es-cl'] = "Defina variables de procesador aquí.";
$text['description-variables']['es-mx'] = "Defina variables de procesador aquí."; //copied from es-cl
$text['description-variables']['fr-ca'] = "Définir ici les variables préprocessées."; //copied from fr-fr
$text['description-variables']['fr-fr'] = "Définir ici les variables préprocessées.";
$text['description-variables']['he-il'] = "הגדר כאן משתני קדם-מעבד. נדרשת הפעלה מחדש של מתג כדי שהשינויים ייכנסו לתוקף.";
$text['description-variables']['it-it'] = "Definire qui le variabili per il preprocessore.";
$text['description-variables']['nl-nl'] = "Definieer hier voorbewerkings variabelen";
$text['description-variables']['pl-pl'] = "Tutaj zdefiniuj zmienne preprocesora";
$text['description-variables']['pt-br'] = "Defina as variáveis aqui:";
$text['description-variables']['pt-pt'] = "Defina as variáveis aqui.";
$text['description-variables']['ro-ro'] = "Definiți aici variabilele preprocesorului. Este necesară o repornire a comutatorului pentru ca modificările să intre în vigoare.";
$text['description-variables']['ru-ru'] = "Определите здесь параметры FreeSwitch.";
$text['description-variables']['sv-se'] = "Definiera preprocessor variabler här.";
$text['description-variables']['uk-ua'] = "Задайте змінні препроцесора тут.";

$text['description-command']['en-us'] = "Set the command.";
$text['description-command']['en-gb'] = "Set the command.";
$text['description-command']['ar-eg'] = "اضبط الأمر.";
$text['description-command']['de-at'] = "Stellen Sie den Befehl ein.";
$text['description-command']['de-ch'] = "Stellen Sie den Befehl ein.";
$text['description-command']['de-de'] = "Stellen Sie den Befehl ein.";
$text['description-command']['es-cl'] = "Establezca el comando.";
$text['description-command']['es-mx'] = "Establezca el comando.";
$text['description-command']['fr-ca'] = "Définir la commande";
$text['description-command']['fr-fr'] = "Définir la commande";
$text['description-command']['he-il'] = "הגדר את הפקודה.";
$text['description-command']['it-it'] = "Imposta il comando.";
$text['description-command']['nl-nl'] = "Stel commando in";
$text['description-command']['pl-pl'] = "Ustaw polecenie.";
$text['description-command']['pt-br'] = "Defina o comando.";
$text['description-command']['pt-pt'] = "Defina o comando.";
$text['description-command']['ro-ro'] = "Setați comanda.";
$text['description-command']['ru-ru'] = "Установите команду.";
$text['description-command']['sv-se'] = "Ställ in kommandot.";
$text['description-command']['uk-ua'] = "Встановіть команду.";

$text['description-name']['en-us'] = "Enter the variable name.";
$text['description-name']['en-gb'] = "Enter the variable name.";
$text['description-name']['ar-eg'] = "أدخل اسم المتغير.";
$text['description-name']['de-at'] = "Geben Sie den Namen der Variable an."; //copied from de-de
$text['description-name']['de-ch'] = "Geben Sie den Namen der Variable an."; //copied from de-de
$text['description-name']['de-de'] = "Geben Sie den Namen der Variable an.";
$text['description-name']['es-cl'] = "Ingrese el nombre de la variable.";
$text['description-name']['es-mx'] = "Ingrese el nombre de la variable."; //copied from es-cl
$text['description-name']['fr-ca'] = "Entrez le nom de la variable";
$text['description-name']['fr-fr'] = "Entrez le nom de la variable";
$text['description-name']['he-il'] = "הזן את שם המשתנה.";
$text['description-name']['it-it'] = "Inserire nome variabile.";
$text['description-name']['nl-nl'] = "Voer variabelenaam in.";
$text['description-name']['pl-pl'] = "Wprowadź nazwę zmiennej";
$text['description-name']['pt-br'] = "Insira o nome do menu";
$text['description-name']['pt-pt'] = "Introduza o nome da variável.";
$text['description-name']['ro-ro'] = "Introduceți numele variabilei.";
$text['description-name']['ru-ru'] = "Введите имя переменной.";
$text['description-name']['sv-se'] = "Skriv in namnet på menyn.";
$text['description-name']['uk-ua'] = "Введіть назву змінної";

$text['description-hostname']['en-us'] = "Enter the hostname / switchname.";
$text['description-hostname']['en-gb'] = "Enter the hostname / switchname.";
$text['description-hostname']['ar-eg'] = "أدخل اسم المضيف / اسم التحويل.";
$text['description-hostname']['de-at'] = "Geben Sie den Hostnamen / Switchnamen an."; //copied from de-de
$text['description-hostname']['de-ch'] = "Geben Sie den Hostnamen / Switchnamen an."; //copied from de-de
$text['description-hostname']['de-de'] = "Geben Sie den Hostnamen / Switchnamen an.";
$text['description-hostname']['es-cl'] = "Ingrese el nombre de host/nombre del conmutador.";
$text['description-hostname']['es-mx'] = "Ingrese el nombre de host/nombre del conmutador.";
$text['description-hostname']['fr-ca'] = "Entrer le nom de l'hôte / du switch."; //copied from fr-fr
$text['description-hostname']['fr-fr'] = "Entrer le nom de l'hôte / du switch.";
$text['description-hostname']['he-il'] = "הזן את שם המארח / שם המתג.";
$text['description-hostname']['it-it'] = "Inserire l'hostname / switchname.";
$text['description-hostname']['nl-nl'] = "Voer Hostnaam / centrale naam in.";
$text['description-hostname']['pl-pl'] = "Wprowadź nazwę hosta / PBXu";
$text['description-hostname']['pt-br'] = "Introduza o hostname"; //copied from pt-pt
$text['description-hostname']['pt-pt'] = "Introduza o hostname";
$text['description-hostname']['ro-ro'] = "Introduceți numele de gazdă/numele comutatorului.";
$text['description-hostname']['ru-ru'] = "Введите имя хоста / имя_схемы.";
$text['description-hostname']['sv-se'] = "Fyll i hostname / switchname.";
$text['description-hostname']['uk-ua'] = "Введіть назву хоста / switchname.";

$text['description-enabled']['en-us'] = "Enable or disable this variable.";
$text['description-enabled']['en-gb'] = "Enable or disable this variable.";
$text['description-enabled']['ar-eg'] = "تمكين أو تعطيل هذا المتغير.";
$text['description-enabled']['de-at'] = "Aktivieren oder deaktivieren Sie diese Variable.";
$text['description-enabled']['de-ch'] = "Aktivieren oder deaktivieren Sie diese Variable.";
$text['description-enabled']['de-de'] = "Aktivieren oder deaktivieren Sie diese Variable.";
$text['description-enabled']['es-cl'] = "Habilite o deshabilite esta variable.";
$text['description-enabled']['es-mx'] = "Habilite o deshabilite esta variable.";
$text['description-enabled']['fr-ca'] = "Activer ou désactiver cette variable";
$text['description-enabled']['fr-fr'] = "Activer ou désactiver cette variable";
$text['description-enabled']['he-il'] = "הפעל או השבת את המשתנה הזה.";
$text['description-enabled']['it-it'] = "Abilita o disabilita questa variabile.";
$text['description-enabled']['nl-nl'] = "Deze variabele aan of uit zetten.";
$text['description-enabled']['pl-pl'] = "Włącz lub wyłącz tę zmienną.";
$text['description-enabled']['pt-br'] = "Ative ou desative esta variável.";
$text['description-enabled']['pt-pt'] = "Ative ou desative esta variável.";
$text['description-enabled']['ro-ro'] = "Activați sau dezactivați această variabilă.";
$text['description-enabled']['ru-ru'] = "Включите или отключите эту переменную.";
$text['description-enabled']['sv-se'] = "Aktivera eller inaktivera denna variabel.";
$text['description-enabled']['uk-ua'] = "Aktivera eller inaktivera denna variabel.";

$text['description-order']['en-us'] = "Select the order.";
$text['description-order']['en-gb'] = "Select the order.";
$text['description-order']['ar-eg'] = "حدد الطلب.";
$text['description-order']['de-at'] = "Wählen Sie die Bestellung aus.";
$text['description-order']['de-ch'] = "Wählen Sie die Bestellung aus.";
$text['description-order']['de-de'] = "Wählen Sie die Bestellung aus.";
$text['description-order']['es-cl'] = "Selecciona el pedido.";
$text['description-order']['es-mx'] = "Selecciona el pedido.";
$text['description-order']['fr-ca'] = "Sélectionnez l'ordre";
$text['description-order']['fr-fr'] = "Sélectionnez l'ordre";
$text['description-order']['he-il'] = "בחר את ההזמנה.";
$text['description-order']['it-it'] = "Seleziona l'ordine.";
$text['description-order']['nl-nl'] = "Kies de volgorde.";
$text['description-order']['pl-pl'] = "Wybierz zamówienie.";
$text['description-order']['pt-br'] = "Selecione o pedido.";
$text['description-order']['pt-pt'] = "Selecione o pedido.";
$text['description-order']['ro-ro'] = "Selectați comanda.";
$text['description-order']['ru-ru'] = "Selectați comanda.";
$text['description-order']['sv-se'] = "Välj beställning.";
$text['description-order']['uk-ua'] = "Виберіть замовлення.";

$text['description-description']['en-us'] = "Enter the description.";
$text['description-description']['en-gb'] = "Enter the description.";
$text['description-description']['ar-eg'] = "أدخل الوصف.";
$text['description-description']['de-at'] = "Geben Sie die Beschreibung ein.";
$text['description-description']['de-ch'] = "Geben Sie die Beschreibung ein.";
$text['description-description']['de-de'] = "Geben Sie die Beschreibung ein.";
$text['description-description']['es-cl'] = "Introduce la descripción.";
$text['description-description']['es-mx'] = "Introduce la descripción.";
$text['description-description']['fr-ca'] = "Entrez la description";
$text['description-description']['fr-fr'] = "Entrez la description";
$text['description-description']['he-il'] = "Inserisci la descrizione.";
$text['description-description']['it-it'] = "Inserisci la descrizione.";
$text['description-description']['nl-nl'] = "Voer de omschrijving in.";
$text['description-description']['pl-pl'] = "Wprowadź opis.";
$text['description-description']['pt-br'] = "Digite a descrição.";
$text['description-description']['pt-pt'] = "Digite a descrição.";
$text['description-description']['ro-ro'] = "Introduceți descrierea.";
$text['description-description']['ru-ru'] = "Введите описание.";
$text['description-description']['sv-se'] = "Ange beskrivningen.";
$text['description-description']['uk-ua'] = "Введіть опис.";

?>