<?php
#This file was last reorganized on 19th of September 2017 08:54:24 AM UTC

$text['title-traffic_graph']['en-us'] = "Traffic Graph";
$text['title-traffic_graph']['ar-eg'] = "";
$text['title-traffic_graph']['de-at'] = "Netzauslastung"; //copied from de-de
$text['title-traffic_graph']['de-ch'] = "Netzauslastung"; //copied from de-de
$text['title-traffic_graph']['de-de'] = "Netzauslastung";
$text['title-traffic_graph']['es-cl'] = "Gráfico de Tráfico";
$text['title-traffic_graph']['es-mx'] = "Gráfico de Tráfico"; //copied from es-cl
$text['title-traffic_graph']['fr-ca'] = "Graphique de Traffic"; //copied from fr-fr
$text['title-traffic_graph']['fr-fr'] = "Graphique de Traffic";
$text['title-traffic_graph']['he-il'] = "";
$text['title-traffic_graph']['it-it'] = "Grafico Traffico Dati";
$text['title-traffic_graph']['nl-nl'] = "";
$text['title-traffic_graph']['pl-pl'] = "Wykres przesyłu danych";
$text['title-traffic_graph']['pt-br'] = "Gráfico de tráfego";
$text['title-traffic_graph']['pt-pt'] = "Gráfico do Tráfego";
$text['title-traffic_graph']['ro-ro'] = "";
$text['title-traffic_graph']['ru-ru'] = "График трафика";
$text['title-traffic_graph']['sv-se'] = "Trafik Graf";
$text['title-traffic_graph']['uk-ua'] = "Графік трафіку";

$text['message-no_interfaces_found']['en-us'] = "No interfaces found.";
$text['message-no_interfaces_found']['ar-eg'] = "";
$text['message-no_interfaces_found']['de-at'] = "Keine Netzwerkkarte gefunden."; //copied from de-de
$text['message-no_interfaces_found']['de-ch'] = "Keine Netzwerkkarte gefunden."; //copied from de-de
$text['message-no_interfaces_found']['de-de'] = "Keine Netzwerkkarte gefunden.";
$text['message-no_interfaces_found']['es-cl'] = "Sin interfaces encontrados.";
$text['message-no_interfaces_found']['es-mx'] = "Sin interfaces encontrados."; //copied from es-cl
$text['message-no_interfaces_found']['fr-ca'] = "Aucune interface trouvé."; //copied from fr-fr
$text['message-no_interfaces_found']['fr-fr'] = "Aucune interface trouvé.";
$text['message-no_interfaces_found']['he-il'] = "";
$text['message-no_interfaces_found']['it-it'] = "Nessuna interfaccia trovata.";
$text['message-no_interfaces_found']['nl-nl'] = "";
$text['message-no_interfaces_found']['pl-pl'] = "Nie znaleziono interfejsy.";
$text['message-no_interfaces_found']['pt-br'] = "Sem interfaces encontrados."; //copied from pt-pt
$text['message-no_interfaces_found']['pt-pt'] = "Sem interfaces encontrados.";
$text['message-no_interfaces_found']['ro-ro'] = "";
$text['message-no_interfaces_found']['ru-ru'] = "Интерфейсы не найдены.";
$text['message-no_interfaces_found']['sv-se'] = "Inga gränssnitt hittades.";
$text['message-no_interfaces_found']['uk-ua'] = "Не знайдено жодного  інтерфейсу";

$text['label-interface']['en-us'] = "Interface";
$text['label-interface']['ar-eg'] = "";
$text['label-interface']['de-at'] = "Netzwerkkarte"; //copied from de-de
$text['label-interface']['de-ch'] = "Netzwerkkarte"; //copied from de-de
$text['label-interface']['de-de'] = "Netzwerkkarte";
$text['label-interface']['es-cl'] = "Interfaz";
$text['label-interface']['es-mx'] = "Interfaz"; //copied from es-cl
$text['label-interface']['fr-ca'] = "Interface"; //copied from fr-fr
$text['label-interface']['fr-fr'] = "Interface";
$text['label-interface']['he-il'] = "";
$text['label-interface']['it-it'] = "Interfaccia";
$text['label-interface']['nl-nl'] = "";
$text['label-interface']['pl-pl'] = "Wybierz interfejs";
$text['label-interface']['pt-br'] = "Interface"; //copied from pt-pt
$text['label-interface']['pt-pt'] = "Interface";
$text['label-interface']['ro-ro'] = "";
$text['label-interface']['ru-ru'] = "Интерфейсы";
$text['label-interface']['sv-se'] = "Gränssnitt";
$text['label-interface']['uk-ua'] = "Інтерфейс";

$text['header-traffic_graph']['en-us'] = "Traffic Graph";
$text['header-traffic_graph']['ar-eg'] = "";
$text['header-traffic_graph']['de-at'] = "Netzauslastung"; //copied from de-de
$text['header-traffic_graph']['de-ch'] = "Netzauslastung"; //copied from de-de
$text['header-traffic_graph']['de-de'] = "Netzauslastung";
$text['header-traffic_graph']['es-cl'] = "Gráfico de Tráfico";
$text['header-traffic_graph']['es-mx'] = "Gráfico de Tráfico"; //copied from es-cl
$text['header-traffic_graph']['fr-ca'] = "Graphique de Traffic"; //copied from fr-fr
$text['header-traffic_graph']['fr-fr'] = "Graphique de Traffic";
$text['header-traffic_graph']['he-il'] = "";
$text['header-traffic_graph']['it-it'] = "Grafico Traffico Dati";
$text['header-traffic_graph']['nl-nl'] = "";
$text['header-traffic_graph']['pl-pl'] = "Wykres przesyłu danych";
$text['header-traffic_graph']['pt-br'] = "Gráfico de tráfego";
$text['header-traffic_graph']['pt-pt'] = "Gráfico do Tráfego";
$text['header-traffic_graph']['ro-ro'] = "";
$text['header-traffic_graph']['ru-ru'] = "График трафика";
$text['header-traffic_graph']['sv-se'] = "Trafik Graf";
$text['header-traffic_graph']['uk-ua'] = "Графік трафіку";

$text['description-traffic_graph']['en-us'] = "A browser (or plugin) that supports Scalable Vector Graphics (SVG) is required to view the traffic graph below.";
$text['description-traffic_graph']['ar-eg'] = "";
$text['description-traffic_graph']['de-at'] = "Um die Netzauslastung anzuzeigen ist ein Browser (oder Plugin) erforderlich, das SVG Dateien (Scalable Vector Graphics) unterstützt."; //copied from de-de
$text['description-traffic_graph']['de-ch'] = "Um die Netzauslastung anzuzeigen ist ein Browser (oder Plugin) erforderlich, das SVG Dateien (Scalable Vector Graphics) unterstützt."; //copied from de-de
$text['description-traffic_graph']['de-de'] = "Um die Netzauslastung anzuzeigen ist ein Browser (oder Plugin) erforderlich, das SVG Dateien (Scalable Vector Graphics) unterstützt.";
$text['description-traffic_graph']['es-cl'] = "Un navegador (o plugin) que soporte SVG (Scalable Vector Graphics) es necesario para ver el gráfico siguiente.";
$text['description-traffic_graph']['es-mx'] = "Un navegador (o plugin) que soporte SVG (Scalable Vector Graphics) es necesario para ver el gráfico siguiente."; //copied from es-cl
$text['description-traffic_graph']['fr-ca'] = "Un explorateur (ou plugin) qui support le Graphique Vectoriel Evolutif (SVG) est nécessaire pour afficher les graphique ci-dessous."; //copied from fr-fr
$text['description-traffic_graph']['fr-fr'] = "Un explorateur (ou plugin) qui support le Graphique Vectoriel Evolutif (SVG) est nécessaire pour afficher les graphique ci-dessous.";
$text['description-traffic_graph']['he-il'] = "";
$text['description-traffic_graph']['it-it'] = "E' necessario un browser (o plugin) che supporti Scalable Vector Graphics (SVG) per vedere il grafico del traffico qui sotto.";
$text['description-traffic_graph']['nl-nl'] = "";
$text['description-traffic_graph']['pl-pl'] = "Aby zobaczyć przesytu danych wymagana jest przeglądarka (lub wtyczka), która obsługuje Scalable Vector Graphics (SVG). ";
$text['description-traffic_graph']['pt-br'] = "Um browser (ou plugin) que suporte SVG (Scalable Vector Graphics) é necessário para ver o gráfico do tráfego abaixo. ";
$text['description-traffic_graph']['pt-pt'] = "Um browser (ou plugin) que suporte SVG (Scalable Vector Graphics) é necessário para ver o gráfico do tráfego abaixo.";
$text['description-traffic_graph']['ro-ro'] = "";
$text['description-traffic_graph']['ru-ru'] = "Для просмотра графика трафика ниже требуется браузер (или плагин), который поддерживает масштабируемую векторную графику (SVG).";
$text['description-traffic_graph']['sv-se'] = "En webbläsare (eller plugin) som stöder Scalable Vector Graphics (SVG) krävs för att visa trafik grafen nedan.";
$text['description-traffic_graph']['uk-ua'] = "Браузер (або плагін), який підтримує Scalable Vector Graphics (SVG) необхідний для перегляду графіка руху нижче.";

$text['description-no_svg']['en-us'] = "Unfortunately your browser does not currently support Scalable Vector Graphics (SVG).  To view the traffic graph, please use a browser (or plugin) that supports Scalable Vector Graphics (SVG).";
$text['description-no_svg']['ar-eg'] = "";
$text['description-no_svg']['de-at'] = "Offensichtlich unterstützt Ihr Browser keine SVG Dateien (Scalable Vector Graphics). Um die Netzauslastung anzuzeigen benutzen Sie bitte einen Browser (oder Plugin) welcher SVG Dateien unterstützt."; //copied from de-de
$text['description-no_svg']['de-ch'] = "Offensichtlich unterstützt Ihr Browser keine SVG Dateien (Scalable Vector Graphics). Um die Netzauslastung anzuzeigen benutzen Sie bitte einen Browser (oder Plugin) welcher SVG Dateien unterstützt."; //copied from de-de
$text['description-no_svg']['de-de'] = "Offensichtlich unterstützt Ihr Browser keine SVG Dateien (Scalable Vector Graphics). Um die Netzauslastung anzuzeigen benutzen Sie bitte einen Browser (oder Plugin) welcher SVG Dateien unterstützt.";
$text['description-no_svg']['es-cl'] = "Su navegador no soporta SVG (Scalable Vector Graphics). Para ver el gráfico debe utilizar un navegador (o plugin) que soporte SVG.";
$text['description-no_svg']['es-mx'] = "Su navegador no soporta SVG (Scalable Vector Graphics). Para ver el gráfico debe utilizar un navegador (o plugin) que soporte SVG."; //copied from es-cl
$text['description-no_svg']['fr-ca'] = "Malheureusement votre explorateur ne ssupporte pas le Graphique Vectoriel Evolutif (SVG). Pour voir le graphique, merci d'utiliser un explorateur (ou plugin) qui le supporte."; //copied from fr-fr
$text['description-no_svg']['fr-fr'] = "Malheureusement votre explorateur ne ssupporte pas le Graphique Vectoriel Evolutif (SVG). Pour voir le graphique, merci d'utiliser un explorateur (ou plugin) qui le supporte.";
$text['description-no_svg']['he-il'] = "";
$text['description-no_svg']['it-it'] = "Sfortunatamente il tuo browser non supporta al momento Scalable Vector Graphics (SVG). Per vedere il grafico del traffico, ti preghiamo di usare un browser (o plugin) che supporti grafica SVG.";
$text['description-no_svg']['nl-nl'] = "";
$text['description-no_svg']['pl-pl'] = "Niestety twoja przeglądarka nie obsługuje obecnie Scalable Vector Graphics (SVG). Aby wyświetlić wykres przesyłu danych, należy użyć przeglądarki (lub wtyczki), który obsługuje Scalable Vector Graphics (SVG).";
$text['description-no_svg']['pt-br'] = "Infelizmente o seu browser não suporta SVG (Scalable Vector Graphics). Para ver o gráfico do tráfego por favor utilize um browser (ou plugin) que suporte SVG."; //copied from pt-pt
$text['description-no_svg']['pt-pt'] = "Infelizmente o seu browser não suporta SVG (Scalable Vector Graphics). Para ver o gráfico do tráfego por favor utilize um browser (ou plugin) que suporte SVG.";
$text['description-no_svg']['ro-ro'] = "";
$text['description-no_svg']['ru-ru'] = "К сожалению, ваш браузер в настоящее время не поддерживает масштабируемую векторную графику (SVG). Чтобы просмотреть график трафика, используйте браузер (или плагин), который поддерживает масштабируемую векторную графику (SVG).";
$text['description-no_svg']['sv-se'] = "Din webbläsare stödjer tyvärr inte Scalable Vector Graphics (SVG). Om du vill visa trafik grafen, vänligen använd en webbläsare (eller plugin) som stöder Scalable Vector Graphics (SVG) ";
$text['description-no_svg']['uk-ua'] = "На жаль, браузер не підтримує Scalable Vector Graphics (SVG). Для перегляду графіка, будь ласка, використовуйте браузер (або плагін), який підтримує Scalable Vector Graphics (SVG).";

?>
