<?php
	
	//application details
	$apps[$x]['name'] = "Websockets Service";
	$apps[$x]['uuid'] = "c43e956a-cd38-4b27-838b-db43dc3f3204";
	$apps[$x]['category'] = "";
	$apps[$x]['subcategory'] = "";
	$apps[$x]['version'] = "1.0";
	$apps[$x]['license'] = "Mozilla Public License 1.1";
	$apps[$x]['url'] = "http://www.fusionpbx.com";
	$apps[$x]['description']['en-us'] = "Web sockets service";
	$apps[$x]['description']['en-gb'] = "Web sockets service";
	$apps[$x]['description']['ar-eg'] = "";
	$apps[$x]['description']['de-at'] = "";
	$apps[$x]['description']['de-ch'] = "";
	$apps[$x]['description']['de-de'] = "";
	$apps[$x]['description']['es-cl'] = "";
	$apps[$x]['description']['es-mx'] = "";
	$apps[$x]['description']['fr-ca'] = "";
	$apps[$x]['description']['fr-fr'] = "";
	$apps[$x]['description']['he-il'] = "";
	$apps[$x]['description']['it-it'] = "";
	$apps[$x]['description']['ka-ge'] = "";
	$apps[$x]['description']['nl-nl'] = "";
	$apps[$x]['description']['pl-pl'] = "";
	$apps[$x]['description']['pt-br'] = "";
	$apps[$x]['description']['pt-pt'] = "";
	$apps[$x]['description']['ro-ro'] = "";
	$apps[$x]['description']['ru-ru'] = "";
	$apps[$x]['description']['sv-se'] = "";
	$apps[$x]['description']['uk-ua'] = "";

	//default settings
	$y=0;
	$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "f7d404f6-7184-4eef-9487-7b2ec213c1fc";
	$apps[$x]['default_settings'][$y]['default_setting_category'] = "active_calls";
	$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "auto_reload_seconds";
	$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
	$apps[$x]['default_settings'][$y]['default_setting_value'] = "5";
	$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
	$apps[$x]['default_settings'][$y]['default_setting_description'] = "Number of seconds before refreshing the active calls page. Use 0 to disable or set to false (default).";
	$y++;
	$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "bfa7aa18-2e66-429d-8756-216f84de2667";
	$apps[$x]['default_settings'][$y]['default_setting_category'] = "active_calls";
	$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "remove_completed_calls";
	$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
	$apps[$x]['default_settings'][$y]['default_setting_value'] = "true";
	$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
	$apps[$x]['default_settings'][$y]['default_setting_description'] = "Remove calls when they are completed. Default is True";
	$y++;
	$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "ac1afb07-6b46-43de-8fa0-d30e5868a7fb";
	$apps[$x]['default_settings'][$y]['default_setting_category'] = "active_calls";
	$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "truncate_application_data_length";
	$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
	$apps[$x]['default_settings'][$y]['default_setting_value'] = "80";
	$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
	$apps[$x]['default_settings'][$y]['default_setting_description'] = "Number of characters to show in the application column data. Default value is 80. To disable truncating use 0.";

	//permission details
	$y=0;
	$apps[$x]['permissions'][$y]['name'] = "call_active_view";
	$apps[$x]['permissions'][$y]['menu']['uuid'] = "eba3d07f-dd5c-6b7b-6880-493b44113ade";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	//$y++;
	//$apps[$x]['permissions'][$y]['name'] = "call_active_transfer";
	//$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "call_active_eavesdrop";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "call_active_hangup";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	//$y++;
	//$apps[$x]['permissions'][$y]['name'] = "call_active_park";
	//$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	//$y++;
	//$apps[$x]['permissions'][$y]['name'] = "call_active_rec";
	//$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "call_active_all";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "call_active_direction";
	//$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "call_active_profile";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "call_active_application";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "call_active_codec";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "call_active_secure";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "call_active_domain";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	/////////////////////////////////////////////////////////////////////////
	// Permissions that could be implemented on a per switch event capture //
	/////////////////////////////////////////////////////////////////////////
	/*
	//
	// The following permissions relate to the switch event socket events that are emitted
	// Each of the permissions can be assigned to the subscriber so they can receive the
	// event when it arrives on the web socket server instance.
	//
	$apps[$x]['permissions'][$y]['name'] = "event_all";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_command";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_custom";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_clone";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_channel_create";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_channel_destroy";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_channel_state";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_channel_callstate";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_channel_answer";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_channel_hangup";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_channel_hangup_complete";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_channel_execute";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_channel_execute_complete";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_channel_hold";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_channel_unhold";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_channel_bridge";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_channel_unbridge";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_channel_progress";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_channel_progress_media";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_channel_outgoing";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_channel_application";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_channel_originate";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_channel_uuid";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_api";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_log";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_inbound_chan";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_outbound_chan";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_startup";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_shutdown";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_publish";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_unpublish";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_talk";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_notalk";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_session_crash";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_module_load";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_module_unload";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_dtmf";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_message";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_presence_in";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_notify_in";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_presence_out";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_presence_probe";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_message_waiting";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_message_query";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_roster";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_codec";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_background_job";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_detected_speech";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_detected_tone";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_private_command";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_heartbeat";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_trap";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_add_schedule";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_del_schedule";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_exe_schedule";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_re_schedule";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_reloadxml";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_notify";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_phone_feature";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_phone_feature_subscribe";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_send_message";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_recv_message";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_request_params";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_channel_data";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_general";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_command";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_session_heartbeat";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_client_disconnected";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_server_disconnected";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_send_info";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_recv_info";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_recv_rtcp_message";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_send_rtcp_message";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_call_secure";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_nat";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_record_start";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_record_stop";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_playback_start";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_playback_stop";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_call_update";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_failure";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_socket_data";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_media_bug_start";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_media_bug_stop";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_conference_data_query";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_conference_data";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_call_setup_req";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_call_setup_result";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_call_detail";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_device_state";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_text";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_shutdown_requested";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_all";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_channel_park";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_channel_unpark";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";

	// These events are the API commands and can be expanded for more modules
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "event_valet_parking::info";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
*/
