<?php
#This file was last reorganized on 19th of September 2017 08:54:24 AM UTC

$text['title-sys-status']['en-us'] = "System Status";
$text['title-sys-status']['en-gb'] = "System Status";
$text['title-sys-status']['ar-eg'] = "";
$text['title-sys-status']['de-at'] = "System Status"; //copied from de-de
$text['title-sys-status']['de-ch'] = "System Status"; //copied from de-de
$text['title-sys-status']['de-de'] = "System Status";
$text['title-sys-status']['es-cl'] = "Estado del Sistema";
$text['title-sys-status']['es-mx'] = "Estado del Sistema"; //copied from es-cl
$text['title-sys-status']['fr-ca'] = "État du Système"; //copied from fr-fr
$text['title-sys-status']['fr-fr'] = "État du Système";
$text['title-sys-status']['he-il'] = "";
$text['title-sys-status']['it-it'] = "Stato Sistema";
$text['title-sys-status']['nl-nl'] = "Systeem Status";
$text['title-sys-status']['pl-pl'] = "Stan systemu";
$text['title-sys-status']['pt-br'] = "Status do sistema";
$text['title-sys-status']['pt-pt'] = "Status do Sistema";
$text['title-sys-status']['ro-ro'] = "";
$text['title-sys-status']['ru-ru'] = "Статус Системы";
$text['title-sys-status']['sv-se'] = "System Status";
$text['title-sys-status']['uk-ua'] = "Стан системи ";

$text['title-sys-info']['en-us'] = "System Information";
$text['title-sys-info']['en-gb'] = "System Information";
$text['title-sys-info']['ar-eg'] = "";
$text['title-sys-info']['de-at'] = "System Information"; //copied from de-de
$text['title-sys-info']['de-ch'] = "System Information"; //copied from de-de
$text['title-sys-info']['de-de'] = "System Information";
$text['title-sys-info']['es-cl'] = "Información de Sistema";
$text['title-sys-info']['es-mx'] = "Información de Sistema"; //copied from es-cl
$text['title-sys-info']['fr-ca'] = "Info Système"; //copied from fr-fr
$text['title-sys-info']['fr-fr'] = "Info Système";
$text['title-sys-info']['he-il'] = "";
$text['title-sys-info']['it-it'] = "Informazioni Sistema";
$text['title-sys-info']['nl-nl'] = "Systeem Informatie";
$text['title-sys-info']['pl-pl'] = "Informacje o systemie";
$text['title-sys-info']['pt-br'] = "Informação do sistema";
$text['title-sys-info']['pt-pt'] = "Informação do Sistema";
$text['title-sys-info']['ro-ro'] = "";
$text['title-sys-info']['ru-ru'] = "Системная информация";
$text['title-sys-info']['sv-se'] = "System Information";
$text['title-sys-info']['uk-ua'] = "Інформація про систему";

$text['title-os-info']['en-us'] = "Operating System Information";
$text['title-os-info']['en-gb'] = "Operating System Information";
$text['title-os-info']['ar-eg'] = "";
$text['title-os-info']['de-at'] = "Informationen zum Betriebssystem"; //copied from de-de
$text['title-os-info']['de-ch'] = "Informationen zum Betriebssystem"; //copied from de-de
$text['title-os-info']['de-de'] = "Informationen zum Betriebssystem";
$text['title-os-info']['es-cl'] = "Información de Sistema Operativo";
$text['title-os-info']['es-mx'] = "Información de Sistema Operativo"; //copied from es-cl
$text['title-os-info']['fr-ca'] = "Informations sur le système d'exploitation"; //copied from fr-fr
$text['title-os-info']['fr-fr'] = "Informations sur le système d'exploitation";
$text['title-os-info']['he-il'] = "";
$text['title-os-info']['it-it'] = "Informazioni Sistema Operativo";
$text['title-os-info']['nl-nl'] = "Operating Systeem Informatie";
$text['title-os-info']['pl-pl'] = "Informacje o Systemie operacyjnym";
$text['title-os-info']['pt-br'] = "Informação do Sistema operacional";
$text['title-os-info']['pt-pt'] = "Informação do Sistema Operativo";
$text['title-os-info']['ro-ro'] = "";
$text['title-os-info']['ru-ru'] = "Информация о операционной системе";
$text['title-os-info']['sv-se'] = "Operativsystem Systeminformation";
$text['title-os-info']['uk-ua'] = "Інформація про Операційна система ";

$text['title-memcache']['en-us'] = "Memcache Information";
$text['title-memcache']['en-gb'] = "Memcache Information";
$text['title-memcache']['ar-eg'] = "";
$text['title-memcache']['de-at'] = "Memcache Information"; //copied from de-de
$text['title-memcache']['de-ch'] = "Memcache Information"; //copied from de-de
$text['title-memcache']['de-de'] = "Memcache Information";
$text['title-memcache']['es-cl'] = "Información de Memcache";
$text['title-memcache']['es-mx'] = "Información de Memcache"; //copied from es-cl
$text['title-memcache']['fr-ca'] = "Information Memcache"; //copied from fr-fr
$text['title-memcache']['fr-fr'] = "Information Memcache";
$text['title-memcache']['he-il'] = "";
$text['title-memcache']['it-it'] = "Informazioni Memcache";
$text['title-memcache']['nl-nl'] = "Memcache Informatie";
$text['title-memcache']['pl-pl'] = "Informacje o pamięci podręcznej (memcache)";
$text['title-memcache']['pt-br'] = "Informação da memória cache";
$text['title-memcache']['pt-pt'] = "Informação da Memcache";
$text['title-memcache']['ro-ro'] = "";
$text['title-memcache']['ru-ru'] = "Информация о кеш памяти";
$text['title-memcache']['sv-se'] = "Memcache Information ";
$text['title-memcache']['uk-ua'] = "Інформація про кеш-пам'ять ";

$text['title-mem']['en-us'] = "Memory Information";
$text['title-mem']['en-gb'] = "Memory Information";
$text['title-mem']['ar-eg'] = "";
$text['title-mem']['de-at'] = "Speicher Information"; //copied from de-de
$text['title-mem']['de-ch'] = "Speicher Information"; //copied from de-de
$text['title-mem']['de-de'] = "Speicher Information";
$text['title-mem']['es-cl'] = "Información de Memoria";
$text['title-mem']['es-mx'] = "Información de Memoria"; //copied from es-cl
$text['title-mem']['fr-ca'] = "Information Mémoire"; //copied from fr-fr
$text['title-mem']['fr-fr'] = "Information Mémoire";
$text['title-mem']['he-il'] = "";
$text['title-mem']['it-it'] = "Informazioni Memoria";
$text['title-mem']['nl-nl'] = "Geheugen Informatie";
$text['title-mem']['pl-pl'] = "Informacje o pamięci";
$text['title-mem']['pt-br'] = "Informação da memória";
$text['title-mem']['pt-pt'] = "Informação da Memória";
$text['title-mem']['ro-ro'] = "";
$text['title-mem']['ru-ru'] = "Информация о памяти";
$text['title-mem']['sv-se'] = "Minnes Information";
$text['title-mem']['uk-ua'] = "Інформація про пам'ять ";

$text['title-drive']['en-us'] = "Drive Information";
$text['title-drive']['en-gb'] = "Drive Information";
$text['title-drive']['ar-eg'] = "";
$text['title-drive']['de-at'] = "Festplatten Information"; //copied from de-de
$text['title-drive']['de-ch'] = "Festplatten Information"; //copied from de-de
$text['title-drive']['de-de'] = "Festplatten Information";
$text['title-drive']['es-cl'] = "Información de Disco";
$text['title-drive']['es-mx'] = "Información de Disco"; //copied from es-cl
$text['title-drive']['fr-ca'] = "Info Disque"; //copied from fr-fr
$text['title-drive']['fr-fr'] = "Info Disque";
$text['title-drive']['he-il'] = "";
$text['title-drive']['it-it'] = "Informazioni Disco";
$text['title-drive']['nl-nl'] = "Disk Informatie";
$text['title-drive']['pl-pl'] = "Informacje o dysku";
$text['title-drive']['pt-br'] = "Informação do disco";
$text['title-drive']['pt-pt'] = "Informação do Disco";
$text['title-drive']['ro-ro'] = "";
$text['title-drive']['ru-ru'] = "Сведения о дисках";
$text['title-drive']['sv-se'] = "Enhetsinformation";
$text['title-drive']['uk-ua'] = "Інформація про привід ";

$text['title-cpu']['en-us'] = "CPU Information";
$text['title-cpu']['en-gb'] = "CPU Information";
$text['title-cpu']['ar-eg'] = "";
$text['title-cpu']['de-at'] = "CPU Information"; //copied from de-de
$text['title-cpu']['de-ch'] = "CPU Information"; //copied from de-de
$text['title-cpu']['de-de'] = "CPU Information";
$text['title-cpu']['es-cl'] = "Info CPU";
$text['title-cpu']['es-mx'] = "Info CPU"; //copied from es-cl
$text['title-cpu']['fr-ca'] = "Info CPU"; //copied from fr-fr
$text['title-cpu']['fr-fr'] = "Info CPU";
$text['title-cpu']['he-il'] = "";
$text['title-cpu']['it-it'] = "Informazioni CPU";
$text['title-cpu']['nl-nl'] = "CPU Informatie";
$text['title-cpu']['pl-pl'] = "Informacje o procesorze";
$text['title-cpu']['pt-br'] = "Informação da CPU";
$text['title-cpu']['pt-pt'] = "Informação de CPU";
$text['title-cpu']['ro-ro'] = "";
$text['title-cpu']['ru-ru'] = "Информация о процессоре";
$text['title-cpu']['sv-se'] = "CPU Information";
$text['title-cpu']['uk-ua'] = "Інформація про процесор";

$text['message-unavailable']['en-us'] = "Unavailable";
$text['message-unavailable']['en-gb'] = "Unavailable";
$text['message-unavailable']['ar-eg'] = "";
$text['message-unavailable']['de-at'] = "Nicht verfügbar"; //copied from de-de
$text['message-unavailable']['de-ch'] = "Nicht verfügbar"; //copied from de-de
$text['message-unavailable']['de-de'] = "Nicht verfügbar";
$text['message-unavailable']['es-cl'] = "Indisponible";
$text['message-unavailable']['es-mx'] = "Indisponible"; //copied from es-cl
$text['message-unavailable']['fr-ca'] = "Indisponible"; //copied from fr-fr
$text['message-unavailable']['fr-fr'] = "Indisponible";
$text['message-unavailable']['he-il'] = "";
$text['message-unavailable']['it-it'] = "Non Disponibile";
$text['message-unavailable']['nl-nl'] = "Niet beschikbaar";
$text['message-unavailable']['pl-pl'] = "Niedostępny";
$text['message-unavailable']['pt-br'] = "Indisponivel";
$text['message-unavailable']['pt-pt'] = "Indisponível";
$text['message-unavailable']['ro-ro'] = "";
$text['message-unavailable']['ru-ru'] = "Недоступен";
$text['message-unavailable']['sv-se'] = "Otillgänglig";
$text['message-unavailable']['uk-ua'] = "Недоступний ";

$text['label-os']['en-us'] = "Operating System";
$text['label-os']['en-gb'] = "Operating System";
$text['label-os']['ar-eg'] = "";
$text['label-os']['de-at'] = "Betriebssystem"; //copied from de-de
$text['label-os']['de-ch'] = "Betriebssystem"; //copied from de-de
$text['label-os']['de-de'] = "Betriebssystem";
$text['label-os']['es-cl'] = "Sistema Operativo";
$text['label-os']['es-mx'] = "Sistema Operativo"; //copied from es-cl
$text['label-os']['fr-ca'] = "Système D'exploitation"; //copied from fr-fr
$text['label-os']['fr-fr'] = "Système D'exploitation";
$text['label-os']['he-il'] = "";
$text['label-os']['it-it'] = "Sistema Operativo";
$text['label-os']['nl-nl'] = "Operating Systeem";
$text['label-os']['pl-pl'] = "System operacyjny";
$text['label-os']['pt-br'] = "Sistema operacional";
$text['label-os']['pt-pt'] = "Sistema Operativo";
$text['label-os']['ro-ro'] = "";
$text['label-os']['ru-ru'] = "Операционная система";
$text['label-os']['sv-se'] = "Operativsystem";
$text['label-os']['uk-ua'] = "Операційна система";

$text['label-kernel']['en-us'] = "Kernel";
$text['label-kernel']['en-gb'] = "Kernel";
$text['label-kernel']['ar-eg'] = "";
$text['label-kernel']['de-at'] = "Kernel"; //copied from de-de
$text['label-kernel']['de-ch'] = "Kernel"; //copied from de-de
$text['label-kernel']['de-de'] = "Kernel";
$text['label-kernel']['es-cl'] = "";
$text['label-kernel']['es-mx'] = "";
$text['label-kernel']['fr-ca'] = "Noyau";
$text['label-kernel']['fr-fr'] = "Noyau";
$text['label-kernel']['he-il'] = "";
$text['label-kernel']['it-it'] = "";
$text['label-kernel']['nl-nl'] = "Kern";
$text['label-kernel']['pl-pl'] = "";
$text['label-kernel']['pt-br'] = "";
$text['label-kernel']['pt-pt'] = "";
$text['label-kernel']['ro-ro'] = "";
$text['label-kernel']['ru-ru'] = "";
$text['label-kernel']['sv-se'] = "";
$text['label-kernel']['uk-ua'] = "";

$text['label-version']['en-us'] = "Version";
$text['label-version']['en-gb'] = "Version";
$text['label-version']['ar-eg'] = "";
$text['label-version']['de-at'] = "Version"; //copied from de-de
$text['label-version']['de-ch'] = "Version"; //copied from de-de
$text['label-version']['de-de'] = "Version";
$text['label-version']['es-cl'] = "Versión";
$text['label-version']['es-mx'] = "Versión"; //copied from es-cl
$text['label-version']['fr-ca'] = "Version"; //copied from fr-fr
$text['label-version']['fr-fr'] = "Version";
$text['label-version']['he-il'] = "";
$text['label-version']['it-it'] = "Versione";
$text['label-version']['nl-nl'] = "Versie";
$text['label-version']['pl-pl'] = "Wersja";
$text['label-version']['pt-br'] = "Versão"; //copied from pt-pt
$text['label-version']['pt-pt'] = "Versão";
$text['label-version']['ro-ro'] = "";
$text['label-version']['ru-ru'] = "Версия";
$text['label-version']['sv-se'] = "Version";
$text['label-version']['uk-ua'] = "версія";

$text['label-path']['en-us'] = "Project Path";
$text['label-path']['en-gb'] = "Project Path";
$text['label-path']['ar-eg'] = "";
$text['label-path']['de-at'] = "Projektpfad"; //copied from de-de
$text['label-path']['de-ch'] = "Projektpfad"; //copied from de-de
$text['label-path']['de-de'] = "Projektpfad";
$text['label-path']['es-cl'] = "Ruta del proyecto";
$text['label-path']['es-mx'] = "Ruta del proyecto"; //copied from es-cl
$text['label-path']['fr-ca'] = "Chemin du projet"; //copied from fr-fr
$text['label-path']['fr-fr'] = "Chemin du projet";
$text['label-path']['he-il'] = "";
$text['label-path']['it-it'] = "Percorso Progetto";
$text['label-path']['nl-nl'] = "Project pad";
$text['label-path']['pl-pl'] = "Ścieżka projektu";
$text['label-path']['pt-br'] = "Caminho do projeto"; //copied from pt-pt
$text['label-path']['pt-pt'] = "Caminho do projeto";
$text['label-path']['ro-ro'] = "";
$text['label-path']['ru-ru'] = "Путь к проекту";
$text['label-path']['sv-se'] = "Projekt Path";
$text['label-path']['uk-ua'] = "шлях проекту";

$text['label-git_info']['en-us'] = "Git Information";
$text['label-git_info']['en-gb'] = "Git Information";
$text['label-git_info']['ar-eg'] = "";
$text['label-git_info']['de-at'] = "Git Informationen"; //copied from de-de
$text['label-git_info']['de-ch'] = "Git Informationen"; //copied from de-de
$text['label-git_info']['de-de'] = "Git Informationen";
$text['label-git_info']['es-cl'] = "Información Git";
$text['label-git_info']['es-mx'] = "Información Git"; //copied from es-cl
$text['label-git_info']['fr-ca'] = "Informations Git"; //copied from fr-fr
$text['label-git_info']['fr-fr'] = "Informations Git";
$text['label-git_info']['he-il'] = "";
$text['label-git_info']['it-it'] = "Informazioni Git";
$text['label-git_info']['nl-nl'] = "Git Informatie";
$text['label-git_info']['pl-pl'] = "git informacji";
$text['label-git_info']['pt-br'] = "Informações git"; //copied from pt-pt
$text['label-git_info']['pt-pt'] = "Informações git";
$text['label-git_info']['ro-ro'] = "";
$text['label-git_info']['ru-ru'] = "Информация о Git";
$text['label-git_info']['sv-se'] = "Git Information";
$text['label-git_info']['uk-ua'] = "Гіт інформація";

$text['label-git_corrupted']['en-us'] = "Git data is corrupt";
$text['label-git_corrupted']['en-gb'] = "Git data is corrupt";
$text['label-git_corrupted']['ar-eg'] = "";
$text['label-git_corrupted']['de-at'] = "Git Daten sind korrupt"; //copied from de-de
$text['label-git_corrupted']['de-ch'] = "Git Daten sind korrupt"; //copied from de-de
$text['label-git_corrupted']['de-de'] = "Git Daten sind korrupt";
$text['label-git_corrupted']['es-cl'] = "Git datos es corrupto";
$text['label-git_corrupted']['es-mx'] = "Git datos es corrupto"; //copied from es-cl
$text['label-git_corrupted']['fr-ca'] = "Données Git est corrompu"; //copied from fr-fr
$text['label-git_corrupted']['fr-fr'] = "Données Git est corrompu";
$text['label-git_corrupted']['he-il'] = "";
$text['label-git_corrupted']['it-it'] = "Dati Git è corrotto";
$text['label-git_corrupted']['nl-nl'] = "Git data is corrupt";
$text['label-git_corrupted']['pl-pl'] = "Git danych jest uszkodzony";
$text['label-git_corrupted']['pt-br'] = "Dados Git é corrupto"; //copied from pt-pt
$text['label-git_corrupted']['pt-pt'] = "Dados Git é corrupto";
$text['label-git_corrupted']['ro-ro'] = "";
$text['label-git_corrupted']['ru-ru'] = "Git Данные повреждены";
$text['label-git_corrupted']['sv-se'] = "Git data är korrupt";
$text['label-git_corrupted']['uk-ua'] = "Гіт дані пошкоджені";

$text['label-switch']['en-us'] = "Switch";
$text['label-switch']['en-gb'] = "Switch";
$text['label-switch']['ar-eg'] = "";
$text['label-switch']['de-at'] = "Switch"; //copied from de-de
$text['label-switch']['de-ch'] = "Switch"; //copied from de-de
$text['label-switch']['de-de'] = "Switch";
$text['label-switch']['es-cl'] = "Cambiar";
$text['label-switch']['es-mx'] = "Cambiar"; //copied from es-cl
$text['label-switch']['fr-ca'] = "Interrupteur"; //copied from fr-fr
$text['label-switch']['fr-fr'] = "Interrupteur";
$text['label-switch']['he-il'] = "";
$text['label-switch']['it-it'] = "Switch";
$text['label-switch']['nl-nl'] = "Centrale";
$text['label-switch']['pl-pl'] = "Przełącznik";
$text['label-switch']['pt-br'] = "Interruptor"; //copied from pt-pt
$text['label-switch']['pt-pt'] = "Interruptor";
$text['label-switch']['ro-ro'] = "";
$text['label-switch']['ru-ru'] = "FreeSwitch";
$text['label-switch']['sv-se'] = "Switch";
$text['label-switch']['uk-ua'] = "перемикач";

$text['label-git_branch']['en-us'] = "Branch";
$text['label-git_branch']['en-gb'] = "Branch";
$text['label-git_branch']['ar-eg'] = "";
$text['label-git_branch']['de-at'] = "Zweig"; //copied from de-de
$text['label-git_branch']['de-ch'] = "Zweig"; //copied from de-de
$text['label-git_branch']['de-de'] = "Zweig";
$text['label-git_branch']['es-cl'] = "Rama";
$text['label-git_branch']['es-mx'] = "Rama"; //copied from es-cl
$text['label-git_branch']['fr-ca'] = "Une succursale"; //copied from fr-fr
$text['label-git_branch']['fr-fr'] = "Une succursale";
$text['label-git_branch']['he-il'] = "";
$text['label-git_branch']['it-it'] = "Branch:";
$text['label-git_branch']['nl-nl'] = "Aftakking:";
$text['label-git_branch']['pl-pl'] = "Gałąź";
$text['label-git_branch']['pt-br'] = "Ramo"; //copied from pt-pt
$text['label-git_branch']['pt-pt'] = "Ramo";
$text['label-git_branch']['ro-ro'] = "";
$text['label-git_branch']['ru-ru'] = "Ветка";
$text['label-git_branch']['sv-se'] = "Branch";
$text['label-git_branch']['uk-ua'] = "філія";

$text['label-php']['en-us'] = "PHP";
$text['label-php']['en-gb'] = "PHP";
$text['label-php']['ar-eg'] = "PHP";
$text['label-php']['de-at'] = "PHP";
$text['label-php']['de-ch'] = "PHP";
$text['label-php']['de-de'] = "PHP";
$text['label-php']['es-cl'] = "PHP";
$text['label-php']['es-mx'] = "PHP";
$text['label-php']['fr-ca'] = "PHP";
$text['label-php']['fr-fr'] = "PHP";
$text['label-php']['he-il'] = "PHP";
$text['label-php']['it-it'] = "PHP";
$text['label-php']['nl-nl'] = "PHP";
$text['label-php']['pl-pl'] = "PHP";
$text['label-php']['pt-br'] = "PHP";
$text['label-php']['pt-pt'] = "PHP";
$text['label-php']['ro-ro'] = "PHP";
$text['label-php']['ru-ru'] = "PHP";
$text['label-php']['sv-se'] = "PHP";
$text['label-php']['uk-ua'] = "PHP";

$text['label-git_commit']['en-us'] = "Commit";
$text['label-git_commit']['en-gb'] = "Commit";
$text['label-git_commit']['ar-eg'] = "";
$text['label-git_commit']['de-at'] = "Übergeben"; //copied from de-de
$text['label-git_commit']['de-ch'] = "Übergeben"; //copied from de-de
$text['label-git_commit']['de-de'] = "Übergeben";
$text['label-git_commit']['es-cl'] = "Cometer";
$text['label-git_commit']['es-mx'] = "Cometer"; //copied from es-cl
$text['label-git_commit']['fr-ca'] = "Commettre"; //copied from fr-fr
$text['label-git_commit']['fr-fr'] = "Commettre";
$text['label-git_commit']['he-il'] = "";
$text['label-git_commit']['it-it'] = "Commit:";
$text['label-git_commit']['nl-nl'] = "Vastleggen:";
$text['label-git_commit']['pl-pl'] = "Zatwierdzenie";
$text['label-git_commit']['pt-br'] = "cometer"; //copied from pt-pt
$text['label-git_commit']['pt-pt'] = "cometer";
$text['label-git_commit']['ro-ro'] = "";
$text['label-git_commit']['ru-ru'] = "Фиксация";
$text['label-git_commit']['sv-se'] = "Commit";
$text['label-git_commit']['uk-ua'] = "здійснити";

$text['label-git_origin']['en-us'] = "Origin";
$text['label-git_origin']['en-gb'] = "Origin";
$text['label-git_origin']['ar-eg'] = "";
$text['label-git_origin']['de-at'] = "Quelle"; //copied from de-de
$text['label-git_origin']['de-ch'] = "Quelle"; //copied from de-de
$text['label-git_origin']['de-de'] = "Quelle";
$text['label-git_origin']['es-cl'] = "Origen";
$text['label-git_origin']['es-mx'] = "Origen"; //copied from es-cl
$text['label-git_origin']['fr-ca'] = "Origine"; //copied from fr-fr
$text['label-git_origin']['fr-fr'] = "Origine";
$text['label-git_origin']['he-il'] = "";
$text['label-git_origin']['it-it'] = "Origin:";
$text['label-git_origin']['nl-nl'] = "Bron:";
$text['label-git_origin']['pl-pl'] = "Pochodzenie";
$text['label-git_origin']['pt-br'] = "Origem"; //copied from pt-pt
$text['label-git_origin']['pt-pt'] = "Origem";
$text['label-git_origin']['ro-ro'] = "";
$text['label-git_origin']['ru-ru'] = "Происхождение";
$text['label-git_origin']['sv-se'] = "Ursprung";
$text['label-git_origin']['uk-ua'] = "походження";

$text['label-git_status']['en-us'] = "Status";
$text['label-git_status']['en-gb'] = "Status";
$text['label-git_status']['ar-eg'] = "";
$text['label-git_status']['de-at'] = "Status"; //copied from de-de
$text['label-git_status']['de-ch'] = "Status"; //copied from de-de
$text['label-git_status']['de-de'] = "Status";
$text['label-git_status']['es-cl'] = "Estado de";
$text['label-git_status']['es-mx'] = "Estado de"; //copied from es-cl
$text['label-git_status']['fr-ca'] = "Statut"; //copied from fr-fr
$text['label-git_status']['fr-fr'] = "Statut";
$text['label-git_status']['he-il'] = "";
$text['label-git_status']['it-it'] = "Stato";
$text['label-git_status']['nl-nl'] = "Status";
$text['label-git_status']['pl-pl'] = "Status";
$text['label-git_status']['pt-br'] = "Status do"; //copied from pt-pt
$text['label-git_status']['pt-pt'] = "Status do";
$text['label-git_status']['ro-ro'] = "";
$text['label-git_status']['ru-ru'] = "Статус";
$text['label-git_status']['sv-se'] = "Status";
$text['label-git_status']['uk-ua'] = "Статус";

$text['label-memcache_status']['en-us'] = "Memcache Status";
$text['label-memcache_status']['en-gb'] = "Memcache Status";
$text['label-memcache_status']['ar-eg'] = "";
$text['label-memcache_status']['de-at'] = "Memcache Status"; //copied from de-de
$text['label-memcache_status']['de-ch'] = "Memcache Status"; //copied from de-de
$text['label-memcache_status']['de-de'] = "Memcache Status";
$text['label-memcache_status']['es-cl'] = "Estado de Memcache";
$text['label-memcache_status']['es-mx'] = "Estado de Memcache"; //copied from es-cl
$text['label-memcache_status']['fr-ca'] = "Statut Memcache"; //copied from fr-fr
$text['label-memcache_status']['fr-fr'] = "Statut Memcache";
$text['label-memcache_status']['he-il'] = "";
$text['label-memcache_status']['it-it'] = "Stato Memcache";
$text['label-memcache_status']['nl-nl'] = "Memcache Status";
$text['label-memcache_status']['pl-pl'] = "Status pamięci podręcznej (memcache)";
$text['label-memcache_status']['pt-br'] = "Estado da memória cache";
$text['label-memcache_status']['pt-pt'] = "Estado da Memcache";
$text['label-memcache_status']['ro-ro'] = "";
$text['label-memcache_status']['ru-ru'] = "Статус кеш памяти";
$text['label-memcache_status']['sv-se'] = "Memcache Status ";
$text['label-memcache_status']['uk-ua'] = "Стан кеш-пам'яті";

$text['label-mem']['en-us'] = "Memory Status";
$text['label-mem']['en-gb'] = "Memory Status";
$text['label-mem']['ar-eg'] = "";
$text['label-mem']['de-at'] = "Speicher Status"; //copied from de-de
$text['label-mem']['de-ch'] = "Speicher Status"; //copied from de-de
$text['label-mem']['de-de'] = "Speicher Status";
$text['label-mem']['es-cl'] = "Estado de Memoria";
$text['label-mem']['es-mx'] = "Estado de Memoria"; //copied from es-cl
$text['label-mem']['fr-ca'] = "Statut Mémoire"; //copied from fr-fr
$text['label-mem']['fr-fr'] = "Statut Mémoire";
$text['label-mem']['he-il'] = "";
$text['label-mem']['it-it'] = "Stato Memoria";
$text['label-mem']['nl-nl'] = "Geheugen Status";
$text['label-mem']['pl-pl'] = "Status pamięci";
$text['label-mem']['pt-br'] = "Estado de memória";
$text['label-mem']['pt-pt'] = "Estado da Memória";
$text['label-mem']['ro-ro'] = "";
$text['label-mem']['ru-ru'] = "Статус памяти";
$text['label-mem']['sv-se'] = "Minnesstatus";
$text['label-mem']['uk-ua'] = "Стан пам'яті ";

$text['label-drive-percent']['en-us'] = "Percent Free";
$text['label-drive-percent']['en-gb'] = "Percent Free";
$text['label-drive-percent']['ar-eg'] = "";
$text['label-drive-percent']['de-at'] = "Prozent Frei"; //copied from de-de
$text['label-drive-percent']['de-ch'] = "Prozent Frei"; //copied from de-de
$text['label-drive-percent']['de-de'] = "Prozent Frei";
$text['label-drive-percent']['es-cl'] = "Porcentaje Libre";
$text['label-drive-percent']['es-mx'] = "Porcentaje Libre"; //copied from es-cl
$text['label-drive-percent']['fr-ca'] = "Pourcent Libre"; //copied from fr-fr
$text['label-drive-percent']['fr-fr'] = "Pourcent Libre";
$text['label-drive-percent']['he-il'] = "";
$text['label-drive-percent']['it-it'] = "Percentuale Libera";
$text['label-drive-percent']['nl-nl'] = "Percentage beschikbaar";
$text['label-drive-percent']['pl-pl'] = "Dostępne w %";
$text['label-drive-percent']['pt-br'] = "Percentagem livre";
$text['label-drive-percent']['pt-pt'] = "Percentagem Livre";
$text['label-drive-percent']['ro-ro'] = "";
$text['label-drive-percent']['ru-ru'] = "Процент свободных";
$text['label-drive-percent']['sv-se'] = "Procent Ledigt";
$text['label-drive-percent']['uk-ua'] = "Відсоток вільного";

$text['label-drive-free']['en-us'] = "Free Space";
$text['label-drive-free']['en-gb'] = "Free Space";
$text['label-drive-free']['ar-eg'] = "";
$text['label-drive-free']['de-at'] = "Freier Speicherplatz"; //copied from de-de
$text['label-drive-free']['de-ch'] = "Freier Speicherplatz"; //copied from de-de
$text['label-drive-free']['de-de'] = "Freier Speicherplatz";
$text['label-drive-free']['es-cl'] = "Espacio Libre";
$text['label-drive-free']['es-mx'] = "Espacio Libre"; //copied from es-cl
$text['label-drive-free']['fr-ca'] = "Espace Libre"; //copied from fr-fr
$text['label-drive-free']['fr-fr'] = "Espace Libre";
$text['label-drive-free']['he-il'] = "";
$text['label-drive-free']['it-it'] = "Spazio Libero";
$text['label-drive-free']['nl-nl'] = "Vrije ruimte";
$text['label-drive-free']['pl-pl'] = "Wolne miejsce";
$text['label-drive-free']['pt-br'] = "Espeço livre";
$text['label-drive-free']['pt-pt'] = "Espaço Livre";
$text['label-drive-free']['ro-ro'] = "";
$text['label-drive-free']['ru-ru'] = "Свободное место";
$text['label-drive-free']['sv-se'] = "Ledigt Utrymme";
$text['label-drive-free']['uk-ua'] = "Вільно";

$text['label-drive-capacity']['en-us'] = "Capacity";
$text['label-drive-capacity']['en-gb'] = "Capacity";
$text['label-drive-capacity']['ar-eg'] = "";
$text['label-drive-capacity']['de-at'] = "Kapazität"; //copied from de-de
$text['label-drive-capacity']['de-ch'] = "Kapazität"; //copied from de-de
$text['label-drive-capacity']['de-de'] = "Kapazität";
$text['label-drive-capacity']['es-cl'] = "Capacidad";
$text['label-drive-capacity']['es-mx'] = "Capacidad"; //copied from es-cl
$text['label-drive-capacity']['fr-ca'] = "Capacité"; //copied from fr-fr
$text['label-drive-capacity']['fr-fr'] = "Capacité";
$text['label-drive-capacity']['he-il'] = "";
$text['label-drive-capacity']['it-it'] = "Capacittà";
$text['label-drive-capacity']['nl-nl'] = "Capaciteit";
$text['label-drive-capacity']['pl-pl'] = "Pojemność";
$text['label-drive-capacity']['pt-br'] = "Capacidade"; //copied from pt-pt
$text['label-drive-capacity']['pt-pt'] = "Capacidade";
$text['label-drive-capacity']['ro-ro'] = "";
$text['label-drive-capacity']['ru-ru'] = "Вместимость";
$text['label-drive-capacity']['sv-se'] = "Kapacitet";
$text['label-drive-capacity']['uk-ua'] = "Емність";

$text['label-drive']['en-us'] = "Drive Space";
$text['label-drive']['en-gb'] = "Drive Space";
$text['label-drive']['ar-eg'] = "";
$text['label-drive']['de-at'] = "Festplatten Speicher"; //copied from de-de
$text['label-drive']['de-ch'] = "Festplatten Speicher"; //copied from de-de
$text['label-drive']['de-de'] = "Festplatten Speicher";
$text['label-drive']['es-cl'] = "Espacio en Disco";
$text['label-drive']['es-mx'] = "Espacio en Disco"; //copied from es-cl
$text['label-drive']['fr-ca'] = "Espace Disque"; //copied from fr-fr
$text['label-drive']['fr-fr'] = "Espace Disque";
$text['label-drive']['he-il'] = "";
$text['label-drive']['it-it'] = "Spazio Disco";
$text['label-drive']['nl-nl'] = "Diskruimte";
$text['label-drive']['pl-pl'] = "Pojemność dysku";
$text['label-drive']['pt-br'] = "Espaço do disco";
$text['label-drive']['pt-pt'] = "Espaço do Disco";
$text['label-drive']['ro-ro'] = "";
$text['label-drive']['ru-ru'] = "Объем дискового пространства";
$text['label-drive']['sv-se'] = "Enhetsutrymme";
$text['label-drive']['uk-ua'] = "Диски";

$text['label-cpu']['en-us'] = "CPU Status";
$text['label-cpu']['en-gb'] = "CPU Status";
$text['label-cpu']['ar-eg'] = "";
$text['label-cpu']['de-at'] = "CPU Status"; //copied from de-de
$text['label-cpu']['de-ch'] = "CPU Status"; //copied from de-de
$text['label-cpu']['de-de'] = "CPU Status";
$text['label-cpu']['es-cl'] = "Estado de CPU";
$text['label-cpu']['es-mx'] = "Estado de CPU"; //copied from es-cl
$text['label-cpu']['fr-ca'] = "CPU Statut"; //copied from fr-fr
$text['label-cpu']['fr-fr'] = "CPU Statut";
$text['label-cpu']['he-il'] = "";
$text['label-cpu']['it-it'] = "Stato CPU";
$text['label-cpu']['nl-nl'] = "CPU Status";
$text['label-cpu']['pl-pl'] = "Status procesora";
$text['label-cpu']['pt-br'] = "Estado da CPU";
$text['label-cpu']['pt-pt'] = "Estado do CPU";
$text['label-cpu']['ro-ro'] = "";
$text['label-cpu']['ru-ru'] = "Статус процессора";
$text['label-cpu']['sv-se'] = "CPU Status";
$text['label-cpu']['uk-ua'] = "Стан процесора ";

$text['label-cpu_usage']['en-us'] = "CPU Usage";
$text['label-cpu_usage']['en-gb'] = "CPU Usage";
$text['label-cpu_usage']['ar-eg'] = "معالج الاستخدام";
$text['label-cpu_usage']['de-at'] = "Prozessorauslastung "; //copied from de-de
$text['label-cpu_usage']['de-ch'] = "Prozessorauslastung "; //copied from de-de
$text['label-cpu_usage']['de-de'] = "Prozessorauslastung ";
$text['label-cpu_usage']['el-gr'] = "Χρήση CPU";
$text['label-cpu_usage']['es-cl'] = "uso del procesador";
$text['label-cpu_usage']['es-mx'] = "uso del procesador"; //copied from es-cl
$text['label-cpu_usage']['fr-ca'] = "processeur Utilisation"; //copied from fr-fr
$text['label-cpu_usage']['fr-fr'] = "processeur Utilisation";
$text['label-cpu_usage']['he-il'] = "שימוש מעבד";
$text['label-cpu_usage']['it-it'] = "Uso CPU";
$text['label-cpu_usage']['nl-nl'] = "";
$text['label-cpu_usage']['pl-pl'] = "Wykorzystanie procesora";
$text['label-cpu_usage']['pt-br'] = "Uso do processador";
$text['label-cpu_usage']['pt-pt'] = "O uso do processador";
$text['label-cpu_usage']['ro-ro'] = "procesor de utilizare";
$text['label-cpu_usage']['ru-ru'] = "Использование CPU";
$text['label-cpu_usage']['sv-se'] = "processor Usage";
$text['label-cpu_usage']['uk-ua'] = "Використання процесора";

$text['label-cpu_cores']['en-us'] = "CPU Cores";
$text['label-cpu_cores']['en-gb'] = "CPU Cores";
$text['label-cpu_cores']['ar-eg'] = "CPU Cores";
$text['label-cpu_cores']['de-at'] = "CPU Cores"; //copied from de-de
$text['label-cpu_cores']['de-ch'] = "CPU Cores"; //copied from de-de
$text['label-cpu_cores']['de-de'] = "CPU Cores";
$text['label-cpu_cores']['el-gr'] = "CPU Cores";
$text['label-cpu_cores']['es-cl'] = "CPU Cores";
$text['label-cpu_cores']['es-mx'] = "CPU Cores"; //copied from es-cl
$text['label-cpu_cores']['fr-ca'] = "CPU Cores"; //copied from fr-fr
$text['label-cpu_cores']['fr-fr'] = "CPU Cores";
$text['label-cpu_cores']['he-il'] = "CPU Cores";
$text['label-cpu_cores']['it-it'] = "CPU Cores";
$text['label-cpu_cores']['nl-nl'] = "CPU Cores";
$text['label-cpu_cores']['pl-pl'] = "Rdzenie CPU";
$text['label-cpu_cores']['pt-br'] = "CPU Cores";
$text['label-cpu_cores']['pt-pt'] = "CPU Cores";
$text['label-cpu_cores']['ro-ro'] = "CPU Cores";
$text['label-cpu_cores']['ru-ru'] = "CPU Cores";
$text['label-cpu_cores']['sv-se'] = "CPU Cores";
$text['label-cpu_cores']['uk-ua'] = "CPU Cores";

$text['label-load_average']['en-us'] = "Load Average";
$text['label-load_average']['en-gb'] = "Load Average";
$text['label-load_average']['ar-eg'] = "Load Average";
$text['label-load_average']['de-at'] = "Load Average"; //copied from de-de
$text['label-load_average']['de-ch'] = "Load Average"; //copied from de-de
$text['label-load_average']['de-de'] = "Load Average";
$text['label-load_average']['el-gr'] = "Load Average";
$text['label-load_average']['es-cl'] = "Load Average";
$text['label-load_average']['es-mx'] = "Load Average"; //copied from es-cl
$text['label-load_average']['fr-ca'] = "Load Average"; //copied from fr-fr
$text['label-load_average']['fr-fr'] = "Load Average";
$text['label-load_average']['he-il'] = "Load Average";
$text['label-load_average']['it-it'] = "Load Average";
$text['label-load_average']['nl-nl'] = "Load Average";
$text['label-load_average']['pl-pl'] = "Średnie Obciążenie";
$text['label-load_average']['pt-br'] = "Load Average";
$text['label-load_average']['pt-pt'] = "Load Average";
$text['label-load_average']['ro-ro'] = "Load Average";
$text['label-load_average']['ru-ru'] = "Load Average";
$text['label-load_average']['sv-se'] = "Load Average";
$text['label-load_average']['uk-ua'] = "Load Average";

$text['header-sys-status']['en-us'] = "System Status";
$text['header-sys-status']['en-gb'] = "System Status";
$text['header-sys-status']['ar-eg'] = "";
$text['header-sys-status']['de-at'] = "System Status"; //copied from de-de
$text['header-sys-status']['de-ch'] = "System Status"; //copied from de-de
$text['header-sys-status']['de-de'] = "System Status";
$text['header-sys-status']['es-cl'] = "Estado del Sistema";
$text['header-sys-status']['es-mx'] = "Estado del Sistema"; //copied from es-cl
$text['header-sys-status']['fr-ca'] = "État du Système"; //copied from fr-fr
$text['header-sys-status']['fr-fr'] = "État du Système";
$text['header-sys-status']['he-il'] = "";
$text['header-sys-status']['it-it'] = "Stato Sistema";
$text['header-sys-status']['nl-nl'] = "Systeem Status";
$text['header-sys-status']['pl-pl'] = "Status systemu";
$text['header-sys-status']['pt-br'] = "Status do sistema";
$text['header-sys-status']['pt-pt'] = "Status do Sistema";
$text['header-sys-status']['ro-ro'] = "";
$text['header-sys-status']['ru-ru'] = "Статус Системы";
$text['header-sys-status']['sv-se'] = "System Status";
$text['header-sys-status']['uk-ua'] = "Стан системи ";

?>
