<?php
#This file was last reorganized on 19th of September 2017 08:54:24 AM UTC

$text['title-queues']['en-us'] = "Queues";
$text['title-queues']['en-gb'] = "Queues";
$text['title-queues']['ar-eg'] = "";
$text['title-queues']['de-at'] = "Warteschlangen"; //copied from de-de
$text['title-queues']['de-ch'] = "Warteschlangen"; //copied from de-de
$text['title-queues']['de-de'] = "Warteschlangen";
$text['title-queues']['es-cl'] = "Colas";
$text['title-queues']['es-mx'] = "Colas"; //copied from es-cl
$text['title-queues']['fr-ca'] = "Files d'attente"; //copied from fr-fr
$text['title-queues']['fr-fr'] = "Files d'attente";
$text['title-queues']['he-il'] = "";
$text['title-queues']['it-it'] = "Code";
$text['title-queues']['nl-nl'] = "Wachtrijen";
$text['title-queues']['pl-pl'] = "Kolejki";
$text['title-queues']['pt-br'] = "Filas"; //copied from pt-pt
$text['title-queues']['pt-pt'] = "Filas";
$text['title-queues']['ro-ro'] = "";
$text['title-queues']['ru-ru'] = "Очереди";
$text['title-queues']['sv-se'] = "Kö:er";
$text['title-queues']['uk-ua'] = "";

$text['title-queue_edit']['en-us'] = "Queue Edit";
$text['title-queue_edit']['en-gb'] = "Queue Edit";
$text['title-queue_edit']['ar-eg'] = "";
$text['title-queue_edit']['de-at'] = "Warteschlangen bearbeiten"; //copied from de-de
$text['title-queue_edit']['de-ch'] = "Warteschlangen bearbeiten"; //copied from de-de
$text['title-queue_edit']['de-de'] = "Warteschlangen bearbeiten";
$text['title-queue_edit']['es-cl'] = "Editar Cola";
$text['title-queue_edit']['es-mx'] = "Editar Cola"; //copied from es-cl
$text['title-queue_edit']['fr-ca'] = "Editer la Queue"; //copied from fr-fr
$text['title-queue_edit']['fr-fr'] = "Editer la Queue";
$text['title-queue_edit']['he-il'] = "";
$text['title-queue_edit']['it-it'] = "Modificare Coda";
$text['title-queue_edit']['nl-nl'] = "Wachtrij aanpassen";
$text['title-queue_edit']['pl-pl'] = "Edytuj kolejkę";
$text['title-queue_edit']['pt-br'] = "Editar Fila"; //copied from pt-pt
$text['title-queue_edit']['pt-pt'] = "Editar Fila";
$text['title-queue_edit']['ro-ro'] = "";
$text['title-queue_edit']['ru-ru'] = "Редактирование очереди";
$text['title-queue_edit']['sv-se'] = "Editera Kö";
$text['title-queue_edit']['uk-ua'] = "";

$text['title-queue_detail_edit']['en-us'] = "Queue Detail Edit";
$text['title-queue_detail_edit']['en-gb'] = "Queue Detail Edit";
$text['title-queue_detail_edit']['ar-eg'] = "";
$text['title-queue_detail_edit']['de-at'] = "Warteschlangen Details bearbeiten"; //copied from de-de
$text['title-queue_detail_edit']['de-ch'] = "Warteschlangen Details bearbeiten"; //copied from de-de
$text['title-queue_detail_edit']['de-de'] = "Warteschlangen Details bearbeiten";
$text['title-queue_detail_edit']['es-cl'] = "Editar Detalle de Cola";
$text['title-queue_detail_edit']['es-mx'] = "Editar Detalle de Cola"; //copied from es-cl
$text['title-queue_detail_edit']['fr-ca'] = "Editer Détails"; //copied from fr-fr
$text['title-queue_detail_edit']['fr-fr'] = "Editer Détails";
$text['title-queue_detail_edit']['he-il'] = "";
$text['title-queue_detail_edit']['it-it'] = "Modificare Dettagli Coda";
$text['title-queue_detail_edit']['nl-nl'] = "Wachtrij detail aanpassen";
$text['title-queue_detail_edit']['pl-pl'] = "Edytuj szczegóły kolejki.";
$text['title-queue_detail_edit']['pt-br'] = "Editar Detalhes da Fila"; //copied from pt-pt
$text['title-queue_detail_edit']['pt-pt'] = "Editar Detalhes da Fila";
$text['title-queue_detail_edit']['ro-ro'] = "";
$text['title-queue_detail_edit']['ru-ru'] = "Редактирование очереди";
$text['title-queue_detail_edit']['sv-se'] = "Editera Kö Detaljer";
$text['title-queue_detail_edit']['uk-ua'] = "";

$text['title-queue_detail_add']['en-us'] = "Queue Detail Add";
$text['title-queue_detail_add']['en-gb'] = "Queue Detail Add";
$text['title-queue_detail_add']['ar-eg'] = "";
$text['title-queue_detail_add']['de-at'] = "Warteschlangen Details hinzufügen."; //copied from de-de
$text['title-queue_detail_add']['de-ch'] = "Warteschlangen Details hinzufügen."; //copied from de-de
$text['title-queue_detail_add']['de-de'] = "Warteschlangen Details hinzufügen.";
$text['title-queue_detail_add']['es-cl'] = "Agregar Detalle de Cola";
$text['title-queue_detail_add']['es-mx'] = "Agregar Detalle de Cola"; //copied from es-cl
$text['title-queue_detail_add']['fr-ca'] = "Ajouter détail de la file d'attente"; //copied from fr-fr
$text['title-queue_detail_add']['fr-fr'] = "Ajouter détail de la file d'attente";
$text['title-queue_detail_add']['he-il'] = "";
$text['title-queue_detail_add']['it-it'] = "Inserire Dettagli Coda";
$text['title-queue_detail_add']['nl-nl'] = "Wachtrij detail toevoegen";
$text['title-queue_detail_add']['pl-pl'] = "Dodaj szczegóły kolejki.";
$text['title-queue_detail_add']['pt-br'] = "Adicionar Detalhes à Fila"; //copied from pt-pt
$text['title-queue_detail_add']['pt-pt'] = "Adicionar Detalhes à Fila";
$text['title-queue_detail_add']['ro-ro'] = "";
$text['title-queue_detail_add']['ru-ru'] = "Добавление детали в очередь";
$text['title-queue_detail_add']['sv-se'] = "Lägg Till Kö Detaljer";
$text['title-queue_detail_add']['uk-ua'] = "";

$text['title-queue_add']['en-us'] = "Queue Add";
$text['title-queue_add']['en-gb'] = "Queue Add";
$text['title-queue_add']['ar-eg'] = "";
$text['title-queue_add']['de-at'] = "Warteschlange hinzufügen"; //copied from de-de
$text['title-queue_add']['de-ch'] = "Warteschlange hinzufügen"; //copied from de-de
$text['title-queue_add']['de-de'] = "Warteschlange hinzufügen";
$text['title-queue_add']['es-cl'] = "Cola Agregar";
$text['title-queue_add']['es-mx'] = "Cola Agregar"; //copied from es-cl
$text['title-queue_add']['fr-ca'] = "Ajouter une file d'attente Add"; //copied from fr-fr
$text['title-queue_add']['fr-fr'] = "Ajouter une file d'attente Add";
$text['title-queue_add']['he-il'] = "";
$text['title-queue_add']['it-it'] = "Inserire Coda";
$text['title-queue_add']['nl-nl'] = "Wachtrij toevoegen";
$text['title-queue_add']['pl-pl'] = "Dodaj kolejkę";
$text['title-queue_add']['pt-br'] = "Adicionar Fila"; //copied from pt-pt
$text['title-queue_add']['pt-pt'] = "Adicionar Fila";
$text['title-queue_add']['ro-ro'] = "";
$text['title-queue_add']['ru-ru'] = "Добавить Очередь";
$text['title-queue_add']['sv-se'] = "Lägg Till Kö";
$text['title-queue_add']['uk-ua'] = "";

$text['option-true']['en-us'] = "True";
$text['option-true']['en-gb'] = "True";
$text['option-true']['ar-eg'] = "";
$text['option-true']['de-at'] = "Ein"; //copied from de-de
$text['option-true']['de-ch'] = "Ein"; //copied from de-de
$text['option-true']['de-de'] = "Ein";
$text['option-true']['es-cl'] = "verdadero";
$text['option-true']['es-mx'] = "verdadero"; //copied from es-cl
$text['option-true']['fr-ca'] = "Oui"; //copied from fr-fr
$text['option-true']['fr-fr'] = "Oui";
$text['option-true']['he-il'] = "";
$text['option-true']['it-it'] = "Vero";
$text['option-true']['nl-nl'] = "Aan";
$text['option-true']['pl-pl'] = "Tak";
$text['option-true']['pt-br'] = "Sim"; //copied from pt-pt
$text['option-true']['pt-pt'] = "Sim";
$text['option-true']['ro-ro'] = "";
$text['option-true']['ru-ru'] = "Да";
$text['option-true']['sv-se'] = "Sann";
$text['option-true']['uk-ua'] = "";

$text['option-parameter']['en-us'] = "Parameter";
$text['option-parameter']['en-gb'] = "Parameter";
$text['option-parameter']['ar-eg'] = "";
$text['option-parameter']['de-at'] = "Parameter"; //copied from de-de
$text['option-parameter']['de-ch'] = "Parameter"; //copied from de-de
$text['option-parameter']['de-de'] = "Parameter";
$text['option-parameter']['es-cl'] = "Parámetro";
$text['option-parameter']['es-mx'] = "Parámetro"; //copied from es-cl
$text['option-parameter']['fr-ca'] = "Paramètre"; //copied from fr-fr
$text['option-parameter']['fr-fr'] = "Paramètre";
$text['option-parameter']['he-il'] = "";
$text['option-parameter']['it-it'] = "Parametro";
$text['option-parameter']['nl-nl'] = "Parameter";
$text['option-parameter']['pl-pl'] = "Parametr";
$text['option-parameter']['pt-br'] = "Parâmetro"; //copied from pt-pt
$text['option-parameter']['pt-pt'] = "Parâmetro";
$text['option-parameter']['ro-ro'] = "";
$text['option-parameter']['ru-ru'] = "Параметр";
$text['option-parameter']['sv-se'] = "Parameter";
$text['option-parameter']['uk-ua'] = "";

$text['option-false']['en-us'] = "False";
$text['option-false']['en-gb'] = "False";
$text['option-false']['ar-eg'] = "";
$text['option-false']['de-at'] = "Aus"; //copied from de-de
$text['option-false']['de-ch'] = "Aus"; //copied from de-de
$text['option-false']['de-de'] = "Aus";
$text['option-false']['es-cl'] = "falso";
$text['option-false']['es-mx'] = "falso"; //copied from es-cl
$text['option-false']['fr-ca'] = "Non"; //copied from fr-fr
$text['option-false']['fr-fr'] = "Non";
$text['option-false']['he-il'] = "";
$text['option-false']['it-it'] = "Falso";
$text['option-false']['nl-nl'] = "Uit";
$text['option-false']['pl-pl'] = "Nie";
$text['option-false']['pt-br'] = "Não"; //copied from pt-pt
$text['option-false']['pt-pt'] = "Não";
$text['option-false']['ro-ro'] = "";
$text['option-false']['ru-ru'] = "Нет";
$text['option-false']['sv-se'] = "Falsk";
$text['option-false']['uk-ua'] = "";

$text['option-condition']['en-us'] = "Condition";
$text['option-condition']['en-gb'] = "Condition";
$text['option-condition']['ar-eg'] = "";
$text['option-condition']['de-at'] = "Bedingung"; //copied from de-de
$text['option-condition']['de-ch'] = "Bedingung"; //copied from de-de
$text['option-condition']['de-de'] = "Bedingung";
$text['option-condition']['es-cl'] = "Condición";
$text['option-condition']['es-mx'] = "Condición"; //copied from es-cl
$text['option-condition']['fr-ca'] = "Condition"; //copied from fr-fr
$text['option-condition']['fr-fr'] = "Condition";
$text['option-condition']['he-il'] = "";
$text['option-condition']['it-it'] = "Condizione";
$text['option-condition']['nl-nl'] = "Voorwaarde";
$text['option-condition']['pl-pl'] = "Warunek";
$text['option-condition']['pt-br'] = "Condição"; //copied from pt-pt
$text['option-condition']['pt-pt'] = "Condição";
$text['option-condition']['ro-ro'] = "";
$text['option-condition']['ru-ru'] = "Состояние";
$text['option-condition']['sv-se'] = "Skick";
$text['option-condition']['uk-ua'] = "";

$text['option-anti-action']['en-us'] = "Anti-Action";
$text['option-anti-action']['en-gb'] = "Anti-Action";
$text['option-anti-action']['ar-eg'] = "";
$text['option-anti-action']['de-at'] = "Anti-Aktion"; //copied from de-de
$text['option-anti-action']['de-ch'] = "Anti-Aktion"; //copied from de-de
$text['option-anti-action']['de-de'] = "Anti-Aktion";
$text['option-anti-action']['es-cl'] = "Anti-Acción";
$text['option-anti-action']['es-mx'] = "Anti-Acción"; //copied from es-cl
$text['option-anti-action']['fr-ca'] = "Anti-Action"; //copied from fr-fr
$text['option-anti-action']['fr-fr'] = "Anti-Action";
$text['option-anti-action']['he-il'] = "";
$text['option-anti-action']['it-it'] = "Anti-Action";
$text['option-anti-action']['nl-nl'] = "Tegen-Aktie";
$text['option-anti-action']['pl-pl'] = "Anty-Operacja";
$text['option-anti-action']['pt-br'] = "Anti-Acção"; //copied from pt-pt
$text['option-anti-action']['pt-pt'] = "Anti-Acção";
$text['option-anti-action']['ro-ro'] = "";
$text['option-anti-action']['ru-ru'] = "Anti-Action";
$text['option-anti-action']['sv-se'] = "Anti-Action";
$text['option-anti-action']['uk-ua'] = "";

$text['option-action']['en-us'] = "Action";
$text['option-action']['en-gb'] = "Action";
$text['option-action']['ar-eg'] = "";
$text['option-action']['de-at'] = "Aktion"; //copied from de-de
$text['option-action']['de-ch'] = "Aktion"; //copied from de-de
$text['option-action']['de-de'] = "Aktion";
$text['option-action']['es-cl'] = "Acción";
$text['option-action']['es-mx'] = "Acción"; //copied from es-cl
$text['option-action']['fr-ca'] = "Action"; //copied from fr-fr
$text['option-action']['fr-fr'] = "Action";
$text['option-action']['he-il'] = "";
$text['option-action']['it-it'] = "Action";
$text['option-action']['nl-nl'] = "Aktie";
$text['option-action']['pl-pl'] = "Operacja";
$text['option-action']['pt-br'] = "Acção"; //copied from pt-pt
$text['option-action']['pt-pt'] = "Acção";
$text['option-action']['ro-ro'] = "";
$text['option-action']['ru-ru'] = "Действие";
$text['option-action']['sv-se'] = "Action";
$text['option-action']['uk-ua'] = "";

$text['label-tag']['en-us'] = "Tag";
$text['label-tag']['en-gb'] = "Tag";
$text['label-tag']['ar-eg'] = "";
$text['label-tag']['de-at'] = "Kennzeichnen"; //copied from de-de
$text['label-tag']['de-ch'] = "Kennzeichnen"; //copied from de-de
$text['label-tag']['de-de'] = "Kennzeichnen";
$text['label-tag']['es-cl'] = "Etiqueta";
$text['label-tag']['es-mx'] = "Etiqueta"; //copied from es-cl
$text['label-tag']['fr-ca'] = "Étiquette"; //copied from fr-fr
$text['label-tag']['fr-fr'] = "Étiquette";
$text['label-tag']['he-il'] = "";
$text['label-tag']['it-it'] = "Tag";
$text['label-tag']['nl-nl'] = "Kenmerk";
$text['label-tag']['pl-pl'] = "Tag";
$text['label-tag']['pt-br'] = "Tag"; //copied from pt-pt
$text['label-tag']['pt-pt'] = "Tag";
$text['label-tag']['ro-ro'] = "";
$text['label-tag']['ru-ru'] = "Тег";
$text['label-tag']['sv-se'] = "Tag";
$text['label-tag']['uk-ua'] = "";

$text['label-field']['en-us'] = "Field";
$text['label-field']['en-gb'] = "Field";
$text['label-field']['ar-eg'] = "";
$text['label-field']['de-at'] = "Feld"; //copied from de-de
$text['label-field']['de-ch'] = "Feld"; //copied from de-de
$text['label-field']['de-de'] = "Feld";
$text['label-field']['es-cl'] = "Campo";
$text['label-field']['es-mx'] = "Campo"; //copied from es-cl
$text['label-field']['fr-ca'] = "Champs"; //copied from fr-fr
$text['label-field']['fr-fr'] = "Champs";
$text['label-field']['he-il'] = "";
$text['label-field']['it-it'] = "Campo";
$text['label-field']['nl-nl'] = "Veld";
$text['label-field']['pl-pl'] = "Pole";
$text['label-field']['pt-br'] = "Campo"; //copied from pt-pt
$text['label-field']['pt-pt'] = "Campo";
$text['label-field']['ro-ro'] = "";
$text['label-field']['ru-ru'] = "Поле";
$text['label-field']['sv-se'] = "Fält";
$text['label-field']['uk-ua'] = "";

$text['label-extension']['en-us'] = "Extension";
$text['label-extension']['en-gb'] = "Extension";
$text['label-extension']['ar-eg'] = "";
$text['label-extension']['de-at'] = "Nebenstelle"; //copied from de-de
$text['label-extension']['de-ch'] = "Nebenstelle"; //copied from de-de
$text['label-extension']['de-de'] = "Nebenstelle";
$text['label-extension']['es-cl'] = "Extensión";
$text['label-extension']['es-mx'] = "Extensión"; //copied from es-cl
$text['label-extension']['fr-ca'] = "Extension"; //copied from fr-fr
$text['label-extension']['fr-fr'] = "Extension";
$text['label-extension']['he-il'] = "";
$text['label-extension']['it-it'] = "Interno";
$text['label-extension']['nl-nl'] = "Toestel";
$text['label-extension']['pl-pl'] = "Numer wewnętrzny";
$text['label-extension']['pt-br'] = "Extensão"; //copied from pt-pt
$text['label-extension']['pt-pt'] = "Extensão";
$text['label-extension']['ro-ro'] = "";
$text['label-extension']['ru-ru'] = "Внутренний Номер";
$text['label-extension']['sv-se'] = "Anknytning";
$text['label-extension']['uk-ua'] = "";

$text['label-expression']['en-us'] = "Expression";
$text['label-expression']['en-gb'] = "Expression";
$text['label-expression']['ar-eg'] = "";
$text['label-expression']['de-at'] = "Ausdruck"; //copied from de-de
$text['label-expression']['de-ch'] = "Ausdruck"; //copied from de-de
$text['label-expression']['de-de'] = "Ausdruck";
$text['label-expression']['es-cl'] = "Expresión";
$text['label-expression']['es-mx'] = "Expresión"; //copied from es-cl
$text['label-expression']['fr-ca'] = "Expression"; //copied from fr-fr
$text['label-expression']['fr-fr'] = "Expression";
$text['label-expression']['he-il'] = "";
$text['label-expression']['it-it'] = "Espressione";
$text['label-expression']['nl-nl'] = "Uitdrukking";
$text['label-expression']['pl-pl'] = "Wyrażenie";
$text['label-expression']['pt-br'] = "Expressão"; //copied from pt-pt
$text['label-expression']['pt-pt'] = "Expressão";
$text['label-expression']['ro-ro'] = "";
$text['label-expression']['ru-ru'] = "Выражение";
$text['label-expression']['sv-se'] = "Uttryck";
$text['label-expression']['uk-ua'] = "";

$text['label-data']['en-us'] = "Data";
$text['label-data']['en-gb'] = "Data";
$text['label-data']['ar-eg'] = "";
$text['label-data']['de-at'] = "Daten"; //copied from de-de
$text['label-data']['de-ch'] = "Daten"; //copied from de-de
$text['label-data']['de-de'] = "Daten";
$text['label-data']['es-cl'] = "Datos";
$text['label-data']['es-mx'] = "Datos"; //copied from es-cl
$text['label-data']['fr-ca'] = "Données"; //copied from fr-fr
$text['label-data']['fr-fr'] = "Données";
$text['label-data']['he-il'] = "";
$text['label-data']['it-it'] = "Dato";
$text['label-data']['nl-nl'] = "Data";
$text['label-data']['pl-pl'] = "Dane";
$text['label-data']['pt-br'] = "Data"; //copied from pt-pt
$text['label-data']['pt-pt'] = "Data";
$text['label-data']['ro-ro'] = "";
$text['label-data']['ru-ru'] = "Дата";
$text['label-data']['sv-se'] = "Data";
$text['label-data']['uk-ua'] = "";

$text['label-continue']['en-us'] = "Continue";
$text['label-continue']['en-gb'] = "Continue";
$text['label-continue']['ar-eg'] = "";
$text['label-continue']['de-at'] = "Fortsetzen"; //copied from de-de
$text['label-continue']['de-ch'] = "Fortsetzen"; //copied from de-de
$text['label-continue']['de-de'] = "Fortsetzen";
$text['label-continue']['es-cl'] = "Continuar";
$text['label-continue']['es-mx'] = "Continuar"; //copied from es-cl
$text['label-continue']['fr-ca'] = "Continue"; //copied from fr-fr
$text['label-continue']['fr-fr'] = "Continue";
$text['label-continue']['he-il'] = "";
$text['label-continue']['it-it'] = "Continua";
$text['label-continue']['nl-nl'] = "Doorgaan";
$text['label-continue']['pl-pl'] = "Kontynuuj";
$text['label-continue']['pt-br'] = "Continuar"; //copied from pt-pt
$text['label-continue']['pt-pt'] = "Continuar";
$text['label-continue']['ro-ro'] = "";
$text['label-continue']['ru-ru'] = "Продолжить";
$text['label-continue']['sv-se'] = "Fortsätt";
$text['label-continue']['uk-ua'] = "";

$text['label-application']['en-us'] = "Application";
$text['label-application']['en-gb'] = "Application";
$text['label-application']['ar-eg'] = "";
$text['label-application']['de-at'] = "Anwendung"; //copied from de-de
$text['label-application']['de-ch'] = "Anwendung"; //copied from de-de
$text['label-application']['de-de'] = "Anwendung";
$text['label-application']['es-cl'] = "Aplicación";
$text['label-application']['es-mx'] = "Aplicación"; //copied from es-cl
$text['label-application']['fr-ca'] = "Application"; //copied from fr-fr
$text['label-application']['fr-fr'] = "Application";
$text['label-application']['he-il'] = "";
$text['label-application']['it-it'] = "Applicazione";
$text['label-application']['nl-nl'] = "Toepassing";
$text['label-application']['pl-pl'] = "Aplikacja";
$text['label-application']['pt-br'] = "Aplicação"; //copied from pt-pt
$text['label-application']['pt-pt'] = "Aplicação";
$text['label-application']['ro-ro'] = "";
$text['label-application']['ru-ru'] = "Заявка";
$text['label-application']['sv-se'] = "Applikation";
$text['label-application']['uk-ua'] = "";

$text['label-agent_queue_extension']['en-us'] = "Queue Extension Number";
$text['label-agent_queue_extension']['en-gb'] = "Queue Extension Number";
$text['label-agent_queue_extension']['ar-eg'] = "";
$text['label-agent_queue_extension']['de-at'] = "Nebenstelle der Warteschlange"; //copied from de-de
$text['label-agent_queue_extension']['de-ch'] = "Nebenstelle der Warteschlange"; //copied from de-de
$text['label-agent_queue_extension']['de-de'] = "Nebenstelle der Warteschlange";
$text['label-agent_queue_extension']['es-cl'] = "Número de Extensión de Cola";
$text['label-agent_queue_extension']['es-mx'] = "Número de Extensión de Cola"; //copied from es-cl
$text['label-agent_queue_extension']['fr-ca'] = "Numéro de poste de la file d'attente"; //copied from fr-fr
$text['label-agent_queue_extension']['fr-fr'] = "Numéro de poste de la file d'attente";
$text['label-agent_queue_extension']['he-il'] = "";
$text['label-agent_queue_extension']['it-it'] = "Interno della Coda";
$text['label-agent_queue_extension']['nl-nl'] = "Wachtrij toestel nummer";
$text['label-agent_queue_extension']['pl-pl'] = "Numer wew kolejki.";
$text['label-agent_queue_extension']['pt-br'] = "Número da Extensão da Fila"; //copied from pt-pt
$text['label-agent_queue_extension']['pt-pt'] = "Número da Extensão da Fila";
$text['label-agent_queue_extension']['ro-ro'] = "";
$text['label-agent_queue_extension']['ru-ru'] = "Очередь Внутренних Номеров";
$text['label-agent_queue_extension']['sv-se'] = "Kö Anknytningsnummer";
$text['label-agent_queue_extension']['uk-ua'] = "";

$text['label-agent_loginout_extension']['en-us'] = "Login/Logout Extension Number";
$text['label-agent_loginout_extension']['en-gb'] = "Login/Logout Extension Number";
$text['label-agent_loginout_extension']['ar-eg'] = "";
$text['label-agent_loginout_extension']['de-at'] = "Nebenstelle für Anmeldung/Abmeldung"; //copied from de-de
$text['label-agent_loginout_extension']['de-ch'] = "Nebenstelle für Anmeldung/Abmeldung"; //copied from de-de
$text['label-agent_loginout_extension']['de-de'] = "Nebenstelle für Anmeldung/Abmeldung";
$text['label-agent_loginout_extension']['es-cl'] = "Número de Extensión de Conexión/Desconexión";
$text['label-agent_loginout_extension']['es-mx'] = "Número de Extensión de Conexión/Desconexión"; //copied from es-cl
$text['label-agent_loginout_extension']['fr-ca'] = "Connexion / Déconnexion numéro de poste"; //copied from fr-fr
$text['label-agent_loginout_extension']['fr-fr'] = "Connexion / Déconnexion numéro de poste";
$text['label-agent_loginout_extension']['he-il'] = "";
$text['label-agent_loginout_extension']['it-it'] = "Interno per il Login/Logout";
$text['label-agent_loginout_extension']['nl-nl'] = "Log aan/uit toestelnummer";
$text['label-agent_loginout_extension']['pl-pl'] = "Włączony/wyłączony numer wewnętrzny";
$text['label-agent_loginout_extension']['pt-br'] = "Login/Logout Número de Extensão"; //copied from pt-pt
$text['label-agent_loginout_extension']['pt-pt'] = "Login/Logout Número de Extensão";
$text['label-agent_loginout_extension']['ro-ro'] = "";
$text['label-agent_loginout_extension']['ru-ru'] = "Внутренний номер вход / выход";
$text['label-agent_loginout_extension']['sv-se'] = "Logga In/Logga Ut Anknytningsnummer";
$text['label-agent_loginout_extension']['uk-ua'] = "";

$text['header-queues']['en-us'] = "Queues";
$text['header-queues']['en-gb'] = "Queues";
$text['header-queues']['ar-eg'] = "";
$text['header-queues']['de-at'] = "Warteschlangen"; //copied from de-de
$text['header-queues']['de-ch'] = "Warteschlangen"; //copied from de-de
$text['header-queues']['de-de'] = "Warteschlangen";
$text['header-queues']['es-cl'] = "Colas";
$text['header-queues']['es-mx'] = "Colas"; //copied from es-cl
$text['header-queues']['fr-ca'] = "Files d'attente"; //copied from fr-fr
$text['header-queues']['fr-fr'] = "Files d'attente";
$text['header-queues']['he-il'] = "";
$text['header-queues']['it-it'] = "Code";
$text['header-queues']['nl-nl'] = "Wachtrijen";
$text['header-queues']['pl-pl'] = "Kolejki";
$text['header-queues']['pt-br'] = "Filas"; //copied from pt-pt
$text['header-queues']['pt-pt'] = "Filas";
$text['header-queues']['ro-ro'] = "";
$text['header-queues']['ru-ru'] = "Очереди";
$text['header-queues']['sv-se'] = "Kö:er";
$text['header-queues']['uk-ua'] = "";

$text['header-queue_edit']['en-us'] = "Queue Edit";
$text['header-queue_edit']['en-gb'] = "Queue Edit";
$text['header-queue_edit']['ar-eg'] = "";
$text['header-queue_edit']['de-at'] = "Warteschlange bearbeiten"; //copied from de-de
$text['header-queue_edit']['de-ch'] = "Warteschlange bearbeiten"; //copied from de-de
$text['header-queue_edit']['de-de'] = "Warteschlange bearbeiten";
$text['header-queue_edit']['es-cl'] = "Editar Cola";
$text['header-queue_edit']['es-mx'] = "Editar Cola"; //copied from es-cl
$text['header-queue_edit']['fr-ca'] = "Editer les files d'attente"; //copied from fr-fr
$text['header-queue_edit']['fr-fr'] = "Editer les files d'attente";
$text['header-queue_edit']['he-il'] = "";
$text['header-queue_edit']['it-it'] = "Modificare Coda";
$text['header-queue_edit']['nl-nl'] = "Wachtrij aanpassen";
$text['header-queue_edit']['pl-pl'] = "Edytuj kolejkę";
$text['header-queue_edit']['pt-br'] = "Editar Fila"; //copied from pt-pt
$text['header-queue_edit']['pt-pt'] = "Editar Fila";
$text['header-queue_edit']['ro-ro'] = "";
$text['header-queue_edit']['ru-ru'] = "редиктирование Очереди";
$text['header-queue_edit']['sv-se'] = "Editera Kö";
$text['header-queue_edit']['uk-ua'] = "";

$text['header-queue_detail_edit']['en-us'] = "Queue Detail Edit";
$text['header-queue_detail_edit']['en-gb'] = "Queue Detail Edit";
$text['header-queue_detail_edit']['ar-eg'] = "";
$text['header-queue_detail_edit']['de-at'] = "Warteschlange Details bearbeiten"; //copied from de-de
$text['header-queue_detail_edit']['de-ch'] = "Warteschlange Details bearbeiten"; //copied from de-de
$text['header-queue_detail_edit']['de-de'] = "Warteschlange Details bearbeiten";
$text['header-queue_detail_edit']['es-cl'] = "Editar Detalle de Cola";
$text['header-queue_detail_edit']['es-mx'] = "Editar Detalle de Cola"; //copied from es-cl
$text['header-queue_detail_edit']['fr-ca'] = "Modifier le détail de la file d'attente"; //copied from fr-fr
$text['header-queue_detail_edit']['fr-fr'] = "Modifier le détail de la file d'attente";
$text['header-queue_detail_edit']['he-il'] = "";
$text['header-queue_detail_edit']['it-it'] = "Modificare Dettagli Coda";
$text['header-queue_detail_edit']['nl-nl'] = "Wachtrij detail aanpassen";
$text['header-queue_detail_edit']['pl-pl'] = "Edytuj szczegóły kolejki";
$text['header-queue_detail_edit']['pt-br'] = "Editar Detalhes da Fila"; //copied from pt-pt
$text['header-queue_detail_edit']['pt-pt'] = "Editar Detalhes da Fila";
$text['header-queue_detail_edit']['ro-ro'] = "";
$text['header-queue_detail_edit']['ru-ru'] = "Редактирование деталей Очереди";
$text['header-queue_detail_edit']['sv-se'] = "Editera Kö Detaljer";
$text['header-queue_detail_edit']['uk-ua'] = "";

$text['header-queue_detail_add']['en-us'] = "Queue Detail Add";
$text['header-queue_detail_add']['en-gb'] = "Queue Detail Add";
$text['header-queue_detail_add']['ar-eg'] = "";
$text['header-queue_detail_add']['de-at'] = "Warteschlange Details hinzufügen"; //copied from de-de
$text['header-queue_detail_add']['de-ch'] = "Warteschlange Details hinzufügen"; //copied from de-de
$text['header-queue_detail_add']['de-de'] = "Warteschlange Details hinzufügen";
$text['header-queue_detail_add']['es-cl'] = "Agregar Detalle de Cola";
$text['header-queue_detail_add']['es-mx'] = "Agregar Detalle de Cola"; //copied from es-cl
$text['header-queue_detail_add']['fr-ca'] = "Ajouter détail de la file d'attente "; //copied from fr-fr
$text['header-queue_detail_add']['fr-fr'] = "Ajouter détail de la file d'attente ";
$text['header-queue_detail_add']['he-il'] = "";
$text['header-queue_detail_add']['it-it'] = "Inserire Dettagli Coda";
$text['header-queue_detail_add']['nl-nl'] = "Wachtrij detail toevoegen";
$text['header-queue_detail_add']['pl-pl'] = "Dodaj szczegóły kolejki";
$text['header-queue_detail_add']['pt-br'] = "Adicionado Detalhes da Fila"; //copied from pt-pt
$text['header-queue_detail_add']['pt-pt'] = "Adicionado Detalhes da Fila";
$text['header-queue_detail_add']['ro-ro'] = "";
$text['header-queue_detail_add']['ru-ru'] = "Добавление деталей в Очередь";
$text['header-queue_detail_add']['sv-se'] = "Lägg Till Kö Detalj";
$text['header-queue_detail_add']['uk-ua'] = "";

$text['header-queue_add']['en-us'] = "Queue Add";
$text['header-queue_add']['en-gb'] = "Queue Add";
$text['header-queue_add']['ar-eg'] = "";
$text['header-queue_add']['de-at'] = "Warteschlange hinzufügen"; //copied from de-de
$text['header-queue_add']['de-ch'] = "Warteschlange hinzufügen"; //copied from de-de
$text['header-queue_add']['de-de'] = "Warteschlange hinzufügen";
$text['header-queue_add']['es-cl'] = "Agregar Cola";
$text['header-queue_add']['es-mx'] = "Agregar Cola"; //copied from es-cl
$text['header-queue_add']['fr-ca'] = "Ajouter un file d'attente"; //copied from fr-fr
$text['header-queue_add']['fr-fr'] = "Ajouter un file d'attente";
$text['header-queue_add']['he-il'] = "";
$text['header-queue_add']['it-it'] = "Inserire Coda";
$text['header-queue_add']['nl-nl'] = "Wachtrij toevoegen";
$text['header-queue_add']['pl-pl'] = "Dodaj kolejkę";
$text['header-queue_add']['pt-br'] = "Adicionar Fila"; //copied from pt-pt
$text['header-queue_add']['pt-pt'] = "Adicionar Fila";
$text['header-queue_add']['ro-ro'] = "";
$text['header-queue_add']['ru-ru'] = "Добавить Очередь";
$text['header-queue_add']['sv-se'] = "Lägg Till Kö";
$text['header-queue_add']['uk-ua'] = "";

$text['header-conditions_and_actions']['en-us'] = "Conditions and Actions";
$text['header-conditions_and_actions']['en-gb'] = "Conditions and Actions";
$text['header-conditions_and_actions']['ar-eg'] = "";
$text['header-conditions_and_actions']['de-at'] = "Bedingungen und Aktionen"; //copied from de-de
$text['header-conditions_and_actions']['de-ch'] = "Bedingungen und Aktionen"; //copied from de-de
$text['header-conditions_and_actions']['de-de'] = "Bedingungen und Aktionen";
$text['header-conditions_and_actions']['es-cl'] = "Condiciones y Acciones";
$text['header-conditions_and_actions']['es-mx'] = "Condiciones y Acciones"; //copied from es-cl
$text['header-conditions_and_actions']['fr-ca'] = "Conditions et Actions"; //copied from fr-fr
$text['header-conditions_and_actions']['fr-fr'] = "Conditions et Actions";
$text['header-conditions_and_actions']['he-il'] = "";
$text['header-conditions_and_actions']['it-it'] = "Condizioni e Azioni";
$text['header-conditions_and_actions']['nl-nl'] = "Voorwaarden en akties";
$text['header-conditions_and_actions']['pl-pl'] = "Warunki i operacje";
$text['header-conditions_and_actions']['pt-br'] = "Condições e Acções"; //copied from pt-pt
$text['header-conditions_and_actions']['pt-pt'] = "Condições e Acções";
$text['header-conditions_and_actions']['ro-ro'] = "";
$text['header-conditions_and_actions']['ru-ru'] = "Условия и действия";
$text['header-conditions_and_actions']['sv-se'] = "Tillstånd och Actions";
$text['header-conditions_and_actions']['uk-ua'] = "";

$text['header-agent_details']['en-us'] = "Agent Details";
$text['header-agent_details']['en-gb'] = "Agent Details";
$text['header-agent_details']['ar-eg'] = "";
$text['header-agent_details']['de-at'] = "Agenten Details"; //copied from de-de
$text['header-agent_details']['de-ch'] = "Agenten Details"; //copied from de-de
$text['header-agent_details']['de-de'] = "Agenten Details";
$text['header-agent_details']['es-cl'] = "Detalles de Agente";
$text['header-agent_details']['es-mx'] = "Detalles de Agente"; //copied from es-cl
$text['header-agent_details']['fr-ca'] = "Détails de l'Agent"; //copied from fr-fr
$text['header-agent_details']['fr-fr'] = "Détails de l'Agent";
$text['header-agent_details']['he-il'] = "";
$text['header-agent_details']['it-it'] = "Dettagli Agente";
$text['header-agent_details']['nl-nl'] = "Agent details";
$text['header-agent_details']['pl-pl'] = "Szczegóły agenta";
$text['header-agent_details']['pt-br'] = "Detalhes do Agente"; //copied from pt-pt
$text['header-agent_details']['pt-pt'] = "Detalhes do Agente";
$text['header-agent_details']['ro-ro'] = "";
$text['header-agent_details']['ru-ru'] = "Сведения об агенте";
$text['header-agent_details']['sv-se'] = "Agent Detaljer";
$text['header-agent_details']['uk-ua'] = "";

$text['header-additional_information']['en-us'] = "Additional Information";
$text['header-additional_information']['en-gb'] = "Additional Information";
$text['header-additional_information']['ar-eg'] = "";
$text['header-additional_information']['de-at'] = "Weiterführende Informationen"; //copied from de-de
$text['header-additional_information']['de-ch'] = "Weiterführende Informationen"; //copied from de-de
$text['header-additional_information']['de-de'] = "Weiterführende Informationen";
$text['header-additional_information']['es-cl'] = "Información Adicional";
$text['header-additional_information']['es-mx'] = "Información Adicional"; //copied from es-cl
$text['header-additional_information']['fr-ca'] = "Informations Additionnelles"; //copied from fr-fr
$text['header-additional_information']['fr-fr'] = "Informations Additionnelles";
$text['header-additional_information']['he-il'] = "";
$text['header-additional_information']['it-it'] = "Informazioni Aggiuntive";
$text['header-additional_information']['nl-nl'] = "Bijgevoegde informatie";
$text['header-additional_information']['pl-pl'] = "Informacje dodatkowe";
$text['header-additional_information']['pt-br'] = "Informação Adicional"; //copied from pt-pt
$text['header-additional_information']['pt-pt'] = "Informação Adicional";
$text['header-additional_information']['ro-ro'] = "";
$text['header-additional_information']['ru-ru'] = "Дополнительная информация";
$text['header-additional_information']['sv-se'] = "Ytterligare Information";
$text['header-additional_information']['uk-ua'] = "";

$text['description-queues']['en-us'] = "Queues are used to setup waiting lines for callers. Also known as FIFO Queues.";
$text['description-queues']['en-gb'] = "Queues are used to setup waiting lines for callers. Also known as FIFO Queues.";
$text['description-queues']['ar-eg'] = "";
$text['description-queues']['de-at'] = "Warteschlangen werden verwendt um Warteschleifen für Anrufer zu erstellen. Diese sind auch als FIFO-Warteschlangen bekannt."; //copied from de-de
$text['description-queues']['de-ch'] = "Warteschlangen werden verwendt um Warteschleifen für Anrufer zu erstellen. Diese sind auch als FIFO-Warteschlangen bekannt."; //copied from de-de
$text['description-queues']['de-de'] = "Warteschlangen werden verwendt um Warteschleifen für Anrufer zu erstellen. Diese sind auch als FIFO-Warteschlangen bekannt.";
$text['description-queues']['es-cl'] = "Las colas son usadas para configurar líneas de espera. Son conocidas como colas FIFO.";
$text['description-queues']['es-mx'] = "Las colas son usadas para configurar líneas de espera. Son conocidas como colas FIFO."; //copied from es-cl
$text['description-queues']['fr-ca'] = "Les files d'attente sont également appelées files d'attentes ou FIFO queues."; //copied from fr-fr
$text['description-queues']['fr-fr'] = "Les files d'attente sont également appelées files d'attentes ou FIFO queues.";
$text['description-queues']['he-il'] = "";
$text['description-queues']['it-it'] = "Le code sono usate per creare linee di attesa per i chiamanti. Anche dette Code FIFO.";
$text['description-queues']['nl-nl'] = "Wachtrijen worden aangemaakt om bellers op volgorde van binnenkomst (FIFO) af te handelen.";
$text['description-queues']['pl-pl'] = "Kolejki są używane do konfiguracji linii oczekiwania dla wielu jednoczesnych rozmówców. Znane one są również jako kolejki FIFO.";
$text['description-queues']['pt-br'] = "As filas são utilizadas para configurar linhas de espera para os originadores das chamadas. Também são chamadas de filas FIFO."; //copied from pt-pt
$text['description-queues']['pt-pt'] = "As filas são utilizadas para configurar linhas de espera para os originadores das chamadas. Também são chamadas de filas FIFO.";
$text['description-queues']['ro-ro'] = "";
$text['description-queues']['ru-ru'] = "Очереди используются для установки ожидающих линий для вызывающих абонентов. Также известны как очереди FIFO.";
$text['description-queues']['sv-se'] = "Köer används för att konfigurera väntelinjer för uppringare. Även känd som FIFO Kö:er.";
$text['description-queues']['uk-ua'] = "";

$text['description-queue_edit']['en-us'] = "Queues are used to setup waiting lines for callers. Also known as FIFO Queues.";
$text['description-queue_edit']['en-gb'] = "Queues are used to setup waiting lines for callers. Also known as FIFO Queues.";
$text['description-queue_edit']['ar-eg'] = "";
$text['description-queue_edit']['de-at'] = "Warteschlangen werden verwendt um Warteschleifen für Anrufer zu erstellen. Diese sind auch als FIFO-Warteschlangen bekannt."; //copied from de-de
$text['description-queue_edit']['de-ch'] = "Warteschlangen werden verwendt um Warteschleifen für Anrufer zu erstellen. Diese sind auch als FIFO-Warteschlangen bekannt."; //copied from de-de
$text['description-queue_edit']['de-de'] = "Warteschlangen werden verwendt um Warteschleifen für Anrufer zu erstellen. Diese sind auch als FIFO-Warteschlangen bekannt.";
$text['description-queue_edit']['es-cl'] = "Las colas son usadas para configurar líneas de espera. Son conocidas como colas FIFO.";
$text['description-queue_edit']['es-mx'] = "Las colas son usadas para configurar líneas de espera. Son conocidas como colas FIFO."; //copied from es-cl
$text['description-queue_edit']['fr-ca'] = "Les files d'attente sont également appelées files d'attentes ou FIFO queues."; //copied from fr-fr
$text['description-queue_edit']['fr-fr'] = "Les files d'attente sont également appelées files d'attentes ou FIFO queues.";
$text['description-queue_edit']['he-il'] = "";
$text['description-queue_edit']['it-it'] = "Le code sono usate per creare linee di attesa per i chiamanti. Anche dette Code FIFO.";
$text['description-queue_edit']['nl-nl'] = "Wachtrijen worden aangemaakt om bellers op volgorde van binnenkomst (FIFO) af te handelen.";
$text['description-queue_edit']['pl-pl'] = "Kolejki są używane do konfiguracji linii oczekiwania dla wielu jednoczesnych rozmówców. Znane one są również jako kolejki FIFO.";
$text['description-queue_edit']['pt-br'] = "As filas são utilizadas para configurar linhas de espera para os originadores de chamadas."; //copied from pt-pt
$text['description-queue_edit']['pt-pt'] = "As filas são utilizadas para configurar linhas de espera para os originadores de chamadas.";
$text['description-queue_edit']['ro-ro'] = "";
$text['description-queue_edit']['ru-ru'] = "Очереди используются для установки ожидающих линий для вызывающих абонентов. Также известны как очереди FIFO.";
$text['description-queue_edit']['sv-se'] = "Köer används för att konfigurera väntelinjer för uppringare. Även känd som FIFO Kö:er.";
$text['description-queue_edit']['uk-ua'] = "";

$text['description-queue_add']['en-us'] = "In simple terms queues are holding patterns for callers to wait until someone is available to take the call. Also known as FIFO Queues.";
$text['description-queue_add']['en-gb'] = "In simple terms queues are holding patterns for callers to wait until someone is available to take the call. Also known as FIFO Queues.";
$text['description-queue_add']['ar-eg'] = "";
$text['description-queue_add']['de-at'] = "Einfach ausgedrückt sind WarteschlangenWarteschlangen in denen die Anruf gehalten werden, bit jemand verfügbar ist, der den Anruf annehmen kann. Diese sind als FIFO-Warteschlangen bekannt."; //copied from de-de
$text['description-queue_add']['de-ch'] = "Einfach ausgedrückt sind WarteschlangenWarteschlangen in denen die Anruf gehalten werden, bit jemand verfügbar ist, der den Anruf annehmen kann. Diese sind als FIFO-Warteschlangen bekannt."; //copied from de-de
$text['description-queue_add']['de-de'] = "Einfach ausgedrückt sind WarteschlangenWarteschlangen in denen die Anruf gehalten werden, bit jemand verfügbar ist, der den Anruf annehmen kann. Diese sind als FIFO-Warteschlangen bekannt.";
$text['description-queue_add']['es-cl'] = "En términos simples, las colas son patrones para mantener en espera hasta que alguien está disponible para tomar la llamada. Son conocidas como colas FIFO.";
$text['description-queue_add']['es-mx'] = "En términos simples, las colas son patrones para mantener en espera hasta que alguien está disponible para tomar la llamada. Son conocidas como colas FIFO."; //copied from es-cl
$text['description-queue_add']['fr-ca'] = "En résumé, ces files d'attente diffusent un média aux appelants en attendant que quelqu'un soit disponible pour traiter cet appel."; //copied from fr-fr
$text['description-queue_add']['fr-fr'] = "En résumé, ces files d'attente diffusent un média aux appelants en attendant que quelqu'un soit disponible pour traiter cet appel.";
$text['description-queue_add']['he-il'] = "";
$text['description-queue_add']['it-it'] = "In termini semplici le code sono sequenze di attesa per i chiamanti per aspettare che qualcuno sia disponibile a prendere la chiamata. Sono anche dette Code FIFO.";
$text['description-queue_add']['nl-nl'] = "Wachtrijen worden aangemaakt om bellers op volgorde van binnenkomst (FIFO) af te handelen.";
$text['description-queue_add']['pl-pl'] = "Kolejki przetrzymują dzwoniących aż do momentu, gdy któryś z agentów będzie mógł odebrać rozmowę. Znane one są również jako kolejki FIFO.";
$text['description-queue_add']['pt-br'] = "As filas implementam padrões que permitem aos originadores das chamadas esperar até que algum agente fique disponível para atender a chamada."; //copied from pt-pt
$text['description-queue_add']['pt-pt'] = "As filas implementam padrões que permitem aos originadores das chamadas esperar até que algum agente fique disponível para atender a chamada.";
$text['description-queue_add']['ro-ro'] = "";
$text['description-queue_add']['ru-ru'] = "Говоря простыми словами, очереди удерживают звонящих на линии, пока кто-то не сможет принять вызов. Также известны как очереди FIFO.";
$text['description-queue_add']['sv-se'] = "Enkelt förklarat så är kö:er en vänt plats för inkommande samtal fram tills någon kan ta samtalet. Även känt som FIFO Kö:er.";
$text['description-queue_add']['uk-ua'] = "";

$text['description-name']['en-us'] = "The name the queue will be assigned.";
$text['description-name']['en-gb'] = "The name the queue will be assigned.";
$text['description-name']['ar-eg'] = "";
$text['description-name']['de-at'] = "Der Name, welcher der Warteschlange zugeordnet werden soll."; //copied from de-de
$text['description-name']['de-ch'] = "Der Name, welcher der Warteschlange zugeordnet werden soll."; //copied from de-de
$text['description-name']['de-de'] = "Der Name, welcher der Warteschlange zugeordnet werden soll.";
$text['description-name']['es-cl'] = "El nombre al que la cola que va a ser asignada.";
$text['description-name']['es-mx'] = "El nombre al que la cola que va a ser asignada."; //copied from es-cl
$text['description-name']['fr-ca'] = "Le nom donné à la file d'attente."; //copied from fr-fr
$text['description-name']['fr-fr'] = "Le nom donné à la file d'attente.";
$text['description-name']['he-il'] = "";
$text['description-name']['it-it'] = "Il nome della coda assegnata.";
$text['description-name']['nl-nl'] = "De naam die aan de wachtrij moet worden toegewezen.";
$text['description-name']['pl-pl'] = " Nazwa kolejki.";
$text['description-name']['pt-br'] = "O nome que será atribuído à fila."; //copied from pt-pt
$text['description-name']['pt-pt'] = "O nome que será atribuído à fila.";
$text['description-name']['ro-ro'] = "";
$text['description-name']['ru-ru'] = "Имя очереди будет присвоено.";
$text['description-name']['sv-se'] = "Namnet som kommer att kopplas till kö:n.";
$text['description-name']['uk-ua'] = "";

$text['description-extension']['en-us'] = "The number that will be assigned to the queue.";
$text['description-extension']['en-gb'] = "The number that will be assigned to the queue.";
$text['description-extension']['ar-eg'] = "";
$text['description-extension']['de-at'] = "Die Rufnummer, die der Warteschlange zugeordnet werden soll."; //copied from de-de
$text['description-extension']['de-ch'] = "Die Rufnummer, die der Warteschlange zugeordnet werden soll."; //copied from de-de
$text['description-extension']['de-de'] = "Die Rufnummer, die der Warteschlange zugeordnet werden soll.";
$text['description-extension']['es-cl'] = "El número al que será asignada la cola.";
$text['description-extension']['es-mx'] = "El número al que será asignada la cola."; //copied from es-cl
$text['description-extension']['fr-ca'] = "Numéro d'extension pour joindre la file d'attente. "; //copied from fr-fr
$text['description-extension']['fr-fr'] = "Numéro d'extension pour joindre la file d'attente. ";
$text['description-extension']['he-il'] = "";
$text['description-extension']['it-it'] = "Il numero che sarà assegnato alla coda.";
$text['description-extension']['nl-nl'] = "Het nummer dat je aan de wachtrij wil toewijzen.";
$text['description-extension']['pl-pl'] = "Numer wew kolejki.";
$text['description-extension']['pt-br'] = "O número que será atribuído à fila."; //copied from pt-pt
$text['description-extension']['pt-pt'] = "O número que será atribuído à fila.";
$text['description-extension']['ro-ro'] = "";
$text['description-extension']['ru-ru'] = "Номер, который будет назначен очереди.";
$text['description-extension']['sv-se'] = "Numret som kommer att kopplas till kö:n.";
$text['description-extension']['uk-ua'] = "";

$text['description-continue']['en-us'] = "Continue in most cases should be set to false.";
$text['description-continue']['en-gb'] = "Continue in most cases should be set to false.";
$text['description-continue']['ar-eg'] = "";
$text['description-continue']['de-at'] = "Die Option Weiterführen sollte in der Regel auf Aus stehen."; //copied from de-de
$text['description-continue']['de-ch'] = "Die Option Weiterführen sollte in der Regel auf Aus stehen."; //copied from de-de
$text['description-continue']['de-de'] = "Die Option Weiterführen sollte in der Regel auf Aus stehen.";
$text['description-continue']['es-cl'] = "Continuar en la mayoría de los casos debería configurarse como falso.";
$text['description-continue']['es-mx'] = "Continuar en la mayoría de los casos debería configurarse como falso."; //copied from es-cl
$text['description-continue']['fr-ca'] = "Continuer, Dans la plus part des cas à Non."; //copied from fr-fr
$text['description-continue']['fr-fr'] = "Continuer, Dans la plus part des cas à Non.";
$text['description-continue']['he-il'] = "";
$text['description-continue']['it-it'] = "'Continua' dovrebbe essere falso per la maggior parte dei casi.";
$text['description-continue']['nl-nl'] = "Doorgaan moet in de meeste gevallen op uit staan.";
$text['description-continue']['pl-pl'] = "Kontynuacja w większości przypadków jest ustawiona na NIE.";
$text['description-continue']['pt-br'] = "A acção Continuar deverá ser, na maioria dos casos, definida a false."; //copied from pt-pt
$text['description-continue']['pt-pt'] = "A acção Continuar deverá ser, na maioria dos casos, definida a false.";
$text['description-continue']['ro-ro'] = "";
$text['description-continue']['ru-ru'] = "Для продолжения в большинстве случаев должно быть установлено значение Нет.";
$text['description-continue']['sv-se'] = "Fortsätt i de flesta fall bör detta vara inställd på falsk.";
$text['description-continue']['uk-ua'] = "";

$text['description-conditions_and_actions']['en-us'] = "The following conditions, actions and anti-actions are used in the dialplan to direct call flow. Each is processed in order until you reach the action dialplan_detail_tag which tells what action to perform. You are not limited to only one condition or action dialplan_detail_tag for a given extension.";
$text['description-conditions_and_actions']['en-gb'] = "The following conditions, actions and anti-actions are used in the dialplan to direct call flow. Each is processed in order until you reach the action dialplan_detail_tag which tells what action to perform. You are not limited to only one condition or action dialplan_detail_tag for a given extension.";
$text['description-conditions_and_actions']['ar-eg'] = "";
$text['description-conditions_and_actions']['de-at'] = "Die nachfolgenden Bedingungen, Aktionen und Anti-Aktionen werden im Wählplan verwendet, um den Anruf-Fluss zu steuern. Jeder Anruf wird sequentiell abgearbeitet, bis die Aktion dialplan_detail_tag erreicht wird, welche die auszuführende Aktion bestimmt. Es können mehrere Bedingungen und Aktionen vom Typ dialplan_detail_tag pro Nebenstelle angegeben werden."; //copied from de-de
$text['description-conditions_and_actions']['de-ch'] = "Die nachfolgenden Bedingungen, Aktionen und Anti-Aktionen werden im Wählplan verwendet, um den Anruf-Fluss zu steuern. Jeder Anruf wird sequentiell abgearbeitet, bis die Aktion dialplan_detail_tag erreicht wird, welche die auszuführende Aktion bestimmt. Es können mehrere Bedingungen und Aktionen vom Typ dialplan_detail_tag pro Nebenstelle angegeben werden."; //copied from de-de
$text['description-conditions_and_actions']['de-de'] = "Die nachfolgenden Bedingungen, Aktionen und Anti-Aktionen werden im Wählplan verwendet, um den Anruf-Fluss zu steuern. Jeder Anruf wird sequentiell abgearbeitet, bis die Aktion dialplan_detail_tag erreicht wird, welche die auszuführende Aktion bestimmt. Es können mehrere Bedingungen und Aktionen vom Typ dialplan_detail_tag pro Nebenstelle angegeben werden.";
$text['description-conditions_and_actions']['es-cl'] = "Las siguientes condiciones, acciones y anti-acciones son usada en el plan de marcado para dirigir el flujo de llamado. Cada uno es procesado en orden hasta que se alcanza la accion dialplan_detail_tag, el cual indica la acción a ejecutar. No está limitado a solo una condición o acción dialplan_detail_tag para una extensión dada.";
$text['description-conditions_and_actions']['es-mx'] = "Las siguientes condiciones, acciones y anti-acciones son usada en el plan de marcado para dirigir el flujo de llamado. Cada uno es procesado en orden hasta que se alcanza la accion dialplan_detail_tag, el cual indica la acción a ejecutar. No está limitado a solo una condición o acción dialplan_detail_tag para una extensión dada."; //copied from es-cl
$text['description-conditions_and_actions']['fr-ca'] = "Les conditions suivantes, actions et anti-actions sont utilisées par le plan de nuémrotation pour acheminer l'appel. Chaque appel est géré dans l'ordre jusqu'à atteindre l'action 'dialplan_detail_tag' qui décide de l'action à effectuer. Il n'y a pas de limite sur le nombre de condition ou d'action pour chaque extension."; //copied from fr-fr
$text['description-conditions_and_actions']['fr-fr'] = "Les conditions suivantes, actions et anti-actions sont utilisées par le plan de nuémrotation pour acheminer l'appel. Chaque appel est géré dans l'ordre jusqu'à atteindre l'action 'dialplan_detail_tag' qui décide de l'action à effectuer. Il n'y a pas de limite sur le nombre de condition ou d'action pour chaque extension.";
$text['description-conditions_and_actions']['he-il'] = "";
$text['description-conditions_and_actions']['it-it'] = "Le seguenti condizioni, azioni o anti-azioni vengono usate nel piano numerazioni per gestire il flusso di chiamata. Ciascuna è processata secondo l'ordine fino al raggiungmento del dialplan_detail_tag che dice quale azione eseguire. Non sei limitato ad una condizione o a una sola azione per ogni interno.";
$text['description-conditions_and_actions']['nl-nl'] = "De volgen voorwaarden, akties en tegen-akties worden in het kiesplan gebruikt om de oproep afhandeling te besturen. Elke element wordt verwerkt in genoemde volgorde totdat het kiesplan_detail kenmerk vertelt wat er gedaan moet worden. Er is geen begrenzing aan het aantal voorwaarden of akties bij een toestel nummer.";
$text['description-conditions_and_actions']['pl-pl'] = "Następujące warunki, akcje i anty-akcje są używane przez dialplan do przesyłania rozmów. Każdy z nich jest wykonywany we wcześniej zdefiniowanej kolejności. Użyj tyle warunków, akcji lub anty-akcji ile jest potrzebne do osiągniecia żądanego końcowego przeznaczenia.";
$text['description-conditions_and_actions']['pt-br'] = "As seguintes condições, acções e anti-acções são utilizadas no dialplan para encaminhar as chamadas. Cada condição, acção ou anti-acção é processada por ordem até ser atingida a acção a tomar. Podem ser tomadas mais do que uma condição ou acção para uma determinada extensão."; //copied from pt-pt
$text['description-conditions_and_actions']['pt-pt'] = "As seguintes condições, acções e anti-acções são utilizadas no dialplan para encaminhar as chamadas. Cada condição, acção ou anti-acção é processada por ordem até ser atingida a acção a tomar. Podem ser tomadas mais do que uma condição ou acção para uma determinada extensão.";
$text['description-conditions_and_actions']['ro-ro'] = "";
$text['description-conditions_and_actions']['ru-ru'] = "Следующие условия, действия и антидействия используются в диалплане для направления потока вызовов. Каждый обрабатывается по порядку, пока не будет достигнуто действие dialplan_detail_tag, которое сообщает, какое действие выполнить. Вы не ограничены только одним условием или действием dialplan_detail_tag для данного расширения.";
$text['description-conditions_and_actions']['sv-se'] = "Följande villkor, åtgärder och anti-handlingar används i nummerplanen för att styra ett samtals flöde. Varje steg bearbetas i ordning tills du når steget dialplan_detail_tag som berättar vilken åtgärd som ska utföras. Du är inte begränsad till endast ett villkor eller åtgärd dialplan_detail_tag för en viss anknytning.";
$text['description-conditions_and_actions']['uk-ua'] = "";

$text['description-agent_queue_extension']['en-us'] = "The extension number for agents to dial to either wait for a call to enter the queue, or pick up a call that is in queue. The agent will hear hold music until a caller enters the queue and the call is connected.";
$text['description-agent_queue_extension']['en-gb'] = "The extension number for agents to dial to either wait for a call to enter the queue, or pick up a call that is in queue. The agent will hear hold music until a caller enters the queue and the call is connected.";
$text['description-agent_queue_extension']['ar-eg'] = "";
$text['description-agent_queue_extension']['de-at'] = "Die Nebenstelle für die Agent FIFO Warteschlange."; //copied from de-de
$text['description-agent_queue_extension']['de-ch'] = "Die Nebenstelle für die Agent FIFO Warteschlange."; //copied from de-de
$text['description-agent_queue_extension']['de-de'] = "Die Nebenstelle für die Agent FIFO Warteschlange.";
$text['description-agent_queue_extension']['es-cl'] = "El número de extensión para la cola del Agente FIFO. Este es el patrón de espera para agentes esperando servir llamadas en la cola.";
$text['description-agent_queue_extension']['es-mx'] = "El número de extensión para la cola del Agente FIFO. Este es el patrón de espera para agentes esperando servir llamadas en la cola."; //copied from es-cl
$text['description-agent_queue_extension']['fr-ca'] = "Numéro de la queue pour l'agent. Ce sera le numéro entré par l'agent pour souscrire aux appels de cette queue. "; //copied from fr-fr
$text['description-agent_queue_extension']['fr-fr'] = "Numéro de la queue pour l'agent. Ce sera le numéro entré par l'agent pour souscrire aux appels de cette queue. ";
$text['description-agent_queue_extension']['he-il'] = "";
$text['description-agent_queue_extension']['it-it'] = "Il Numero di interno per l'Agente FIFO della Coda. Questo è il mode    llo di attesa per gli Agenti che attendono al servizio di chiamate nella Coda FIFO.";
$text['description-agent_queue_extension']['nl-nl'] = "Het toestelnummer voor een Agent FIFO Wachtrij. Dit is de wachtrij voor agenten om gesprekken uit de beller wachtrij op te pakken.";
$text['description-agent_queue_extension']['pl-pl'] = "Numer wew agenta w kolejce FIFO. To jest przykład ustawienia agentów oczekujących na rozmowy.";
$text['description-agent_queue_extension']['pt-br'] = "O número de extensão para o agente da fila. Este é o procedimento para que os agentes possam receber chamadas da fila."; //copied from pt-pt
$text['description-agent_queue_extension']['pt-pt'] = "O número de extensão para o agente da fila. Este é o procedimento para que os agentes possam receber chamadas da fila.";
$text['description-agent_queue_extension']['ro-ro'] = "";
$text['description-agent_queue_extension']['ru-ru'] = "Внутренний номер очереди агента FIFO. Это шаблон ожидания для операторов, ожидающих обслуживания вызовов в очереди FIFO вызывающего абонента.";
$text['description-agent_queue_extension']['sv-se'] = "Anknytningsnumret för Agent FIFO Queue. Detta är väntplatsen för agenter som väntar på att betjäna samtal i den uppringande FIFO-köen.";
$text['description-agent_queue_extension']['uk-ua'] = "";

$text['description-agent_loginout_extension']['en-us'] = "Agents use this extension number to login or logout of the Queue. At the prompt, dial 1 to login and 2 to logout. After logging into the agent will be ready to receive calls from the Queue.";
$text['description-agent_loginout_extension']['en-gb'] = "Agents use this extension number to login or logout of the Queue. At the prompt, dial 1 to login and 2 to logout. After logging into the agent will be ready to receive calls from the Queue.";
$text['description-agent_loginout_extension']['ar-eg'] = "";
$text['description-agent_loginout_extension']['de-at'] = "Der Agent verwendet diese Nebenstelle um sich bei der Warteschlange an oder ab zu melden. Nach der Anmeldung kann der Agent Anrufe aus der Warteschlange entgegennehmen."; //copied from de-de
$text['description-agent_loginout_extension']['de-ch'] = "Der Agent verwendet diese Nebenstelle um sich bei der Warteschlange an oder ab zu melden. Nach der Anmeldung kann der Agent Anrufe aus der Warteschlange entgegennehmen."; //copied from de-de
$text['description-agent_loginout_extension']['de-de'] = "Der Agent verwendet diese Nebenstelle um sich bei der Warteschlange an oder ab zu melden. Nach der Anmeldung kann der Agent Anrufe aus der Warteschlange entgegennehmen.";
$text['description-agent_loginout_extension']['es-cl'] = "Los agentes usan este número de extensión para conectarse o desconectarse en la cola. Despues de conectarse, el agente estará listo para recibir llamadas desde la cola.";
$text['description-agent_loginout_extension']['es-mx'] = "Los agentes usan este número de extensión para conectarse o desconectarse en la cola. Despues de conectarse, el agente estará listo para recibir llamadas desde la cola."; //copied from es-cl
$text['description-agent_loginout_extension']['fr-ca'] = "Numéro utilisé par l'agent pour se connecter/déconnecter de la queue. Après s'être connecté, l'agent sera prêt à recevoir des les appels de la queue."; //copied from fr-fr
$text['description-agent_loginout_extension']['fr-fr'] = "Numéro utilisé par l'agent pour se connecter/déconnecter de la queue. Après s'être connecté, l'agent sera prêt à recevoir des les appels de la queue.";
$text['description-agent_loginout_extension']['he-il'] = "";
$text['description-agent_loginout_extension']['it-it'] = "Gli Agenti usano questo numero interno per autenticarsi o disconnettersi dalla Coda. Dopo essersi autenticati saranno disponibili a ricevere chiamate dalla Coda. ";
$text['description-agent_loginout_extension']['nl-nl'] = "Agenten gebruiken dit toestel nummer om een wachtrij aan of uit te zetten op hun toestel. Na aanmelden worden binnenkomende gesprekken doorgeschakeld.";
$text['description-agent_loginout_extension']['pl-pl'] = "Agenci używają numeru wew aby się zalogować lub wylogować z kolejki. Po zalogowaniu agent jest gotowy do odbierania rozmów.";
$text['description-agent_loginout_extension']['pt-br'] = "Os agentes utilizam este número de extensão para entrarem ou sairem da fila. Depois desta configuração o agente receberá chamadas com destino a esta fila."; //copied from pt-pt
$text['description-agent_loginout_extension']['pt-pt'] = "Os agentes utilizam este número de extensão para entrarem ou sairem da fila. Depois desta configuração o agente receberá chamadas com destino a esta fila.";
$text['description-agent_loginout_extension']['ro-ro'] = "";
$text['description-agent_loginout_extension']['ru-ru'] = "Агенты используют этот внутренний номер для входа или выхода из очереди. После входа в агент будет готов принимать вызовы из очереди.";
$text['description-agent_loginout_extension']['sv-se'] = "
Agenter använder det här anknytningsnumret för att logga in eller logga ut från köen. Efter att du loggat in i agenten kommer du att vara redo att ta emot samtal från köen.";
$text['description-agent_loginout_extension']['uk-ua'] = "";

?>
